- topdown/regex_test.go
- topdown/tokens_test.go
- topdown/topdown_test.go
- util/json.go
- util/json_test.go
Fixes: #2331
Signed-off-by: katsew <y.katsew@gmail.com>
> util: Fix UnmarshalJSON parses invalid json in some cases

- docs/content/configuration.md
- plugins/rest/aws.go
- plugins/rest/aws_test.go
AWS_SESSION_TOKEN or AWS_SECURITY_TOKEN is required when signing AWS requests
using ENV credentials from IAM assumed the role. Missing token
results with S3 403 error when trying to download the bundle.
Steps to reproduce the issue:
- Configure service to sign requests using environment variables.
- Instead of using IAM user credentials, assume IAM role and export result credentials.
- Bundle download fails with a 403 error due to missing SecurityToken.
In addition, this fix allows downloading bundles from s3 in AWS Lambda.
Signed-off-by: Kamil Piotrowski <kamil.piotrowski@nordcloud.com>
> Add AWS_SESSION_TOKEN to aws environment credentials

- format/format.go
- format/format_test.go
In 954196a6900082f055e1e11ff09f5caa2b3772a2 we fixed format to show
wildcard variable names if needed, however, ref heads were not handled
properly. This commit just modifies the ref printing to ensure that
heads are formatted properly.
> format: Fix bug in ref formatting

- docs/content/_index.md
On Windows, cmd.exe does not parse out single-quote characters on the
command line so they get passed through to the parser which bails on
them. Just use double-quote characters to avoid this.
Fixes #2391
> dosc: Use double-quote instead of single-quote in opa eval examples

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/reachable.go
- topdown/reachable_test.go
This is a first stab at the solution I proposed in #947.
Some questions:
1. `graph.reachable` currently takes sets (an object of sets in the first
argument, and an initial set in the second argument).  Should this be
extended so it also accepts arrays?
2.  I am working on `Term`s directly in the actual implementation.  This
probably has some overhead compared to working on a `map[string]`
directly; but the downside of the latter is that we'd need constrain
the graph nodes to strings.
And TODOs:
> Add graph.reachable builtin

- cmd/run_test.go
The server was configured with a 0 second graceful shutdown period
which would periodically cause the shutdown to return an error.
This is corrected to have a 1 second shutdown period (plenty of time
as the tests should _NOT_ have any open client requests when they
finish, if they do they _should_ fail).
In addition we don't let the runtime do an os.Exit(1) on error, we
use the lower level `runtime.Serve()` API and catch the error in the
tests.
> cmd: Fix shutdown race in "run" unit tests

- docs/content/envoy-authorization.md
correct is_token_valid logic for envoy example closes #2395
> docs/website: correct is_token_valid logic on envoy page fixes: #2395

- topdown/eval.go
- topdown/instrumentation.go
- topdown/topdown_bench_test.go
In 00a71ef465ffed82c5dcbd6ea141fff434c15c85 we added support for
comprehension indexing, however, there was a bug in the implementation
for sets and objects: the child query was closing over the
parent--we only had test coverage against arrays so this went
uncaught. This meant that sets and objects would still see O(N^2) runtime.
This commit resolves the issue and includes a new instrumentation
counter that should help identify this kind of issue (if the skip and
miss count differs, something is wrong.) Rather than erroring in this
case, we just lazily compute the comprehension.
> topdown: Fix bug in set/array comprehension indexing

- internal/presentation/presentation.go
- repl/repl_test.go
As #2338 comments say, current REPL with pretty-printing is not capable to display valid boolean flags.
If a boolean expression has `true` value, the iteration should show them without ignoring.
At first, I tried to print values except for false like @tsandall wrote:
```
> x[_]
+------+
| x[_] |
+------+
| 1    |
| 1    |
+------+
```
However, it may confuse you because the values look like `int`, not `bool`.
So I implemented the function to print a raw `true`.
```
> x[_]
+------+
| x[_] |
+------+
| true |
| true |
+------+
```
Fixes #2338 
Signed-off-by: Seiji Takahashi <timaki.st@gmail.com>
> repl: Enable pretty mode to print `true` flag

- ast/compile.go
- ast/parser_ext.go
- ast/parser_test.go
- cmd/oracle.go
- cmd/oracle_test.go
- internal/oracle/oracle.go
- internal/oracle/oracle_test.go
- server/server_test.go
This PR adds a new `oracle` command (which is hidden for now) that can be be home for tools that answer queries over policy files. The first oracle command that's implemented is `find-definition` which returns the location of the definition referred to by the filename/offset provided as input.
> Add internal/oracle package for querying ASTs with text locations

- cmd/run.go
- cmd/version.go
- cmd/version_test.go
- docs/content/privacy.md
- internal/report/report.go
- internal/report/report_test.go
- repl/repl.go
- repl/repl_test.go
- runtime/runtime.go
- runtime/runtime_test.go
This PR add a new version reporting feature to OPA. This feature is only applicable to the OPA `run` and `version` commands. With this change, OPA will report its running version to an external service and receive information about the latest released OPA version.
Fixes #1253
> Anonymous version reporting

- docs/content/terraform.md
> docs/content: add terraform module example to tutorial

- Dockerfile
The scratch base image does not contain ca-certificates which meant
that the version check was failing because of TLS errors while
connecting to telemetry.openpolicyagent.org.
> build: Fix image to include ca-certificates from distroless

- format/format.go
- format/testfiles/test_issue_2420.rego
- format/testfiles/test_issue_2420.rego.formatted
When an else block had a comment in between it and the rule body we
were not starting a new line, which triggers a panic in the formatter.
This corrects the issue, and also removes the panics. If the functions
are not called correctly the formatting will be off and tests will
fail. There is little benefit in them causing a panic.
Fixes: #2420
> format: Fix panic with else blocks and comments

- rego/rego.go
- rego/rego_test.go
- server/server.go
- server/server_test.go
Previously the rego package would construct rules for each of the
PE query results when PartialResult() was invoked--however, it would not
check if those rules would be recursive. If the user queried for
`data` (or `data.<partialnamespace>`) then PE would return an
(essentially) unmodified copy of the query and the rego package would
happily construct a rule from it--since the rule is namespaced under
data this leads to a recursion error.
The problem is that the recursion error was caught by running the
compiler--however, since the compiler is shared by the server and
other components and since compile operations do not rollback changes
on error, this approach left OPA in an inconsistent state. Some of the
compiler data structures like the rule tree would include the PE
result but any …
> rego, server: Fix panic caused by compiler misuse

- cover/cover.go
- cover/cover_bench_test.go
- cover/cover_test.go
- profiler/profiler.go
- profiler/profiler_bench_test.go
- profiler/profiler_test.go
- topdown/eval.go
- topdown/query.go
- topdown/query_test.go
- topdown/trace.go
- topdown/trace_test.go
This PR makes a few changes:
* Introduces a new `topdown.CustomTracer` interface which builds on top of the `topdown.Tracer`, but allows for Tracer implementations to supply their configuration requirements for evaluation time.
* Changes the `topdown.Query` and `topdown.Eval` to check if any tracers require variable metadata (via their configuration, as applicable). If none do then that step is skipped on each trace event.
* Updates the profiler and coverage tracers to take advantage of this, and reducing their overhead pretty significantly (Fixing #2245). Results from my dev machine before and after for coverage tracing on a query:
```
name                                                                old time/op    new time/op    delta
BenchmarkCoverBigLocalVar/1Vars1Iterations-8 …
```
> Add ability to disable trace event var plugging

- format/format.go
- format/format_test.go
Previously if we had nested refs we wouldn't print the wildcards with
names, which could cause issues with the resulting policy.
> format: Fix wildcards in nested refs

- CHANGELOG.md
- Makefile
- docs/content/terraform.md
- format/format.go
- format/format_test.go
Includes a fix for the doc content (so it will show up on "latest") and a fix for the formatter which affected the new `opa build` command
> Prepare v0.20.3 release

- format/format.go
- format/format_test.go
Instead of playing games with trying to format them nicely, we instead
can just rewrite them right at the start to no longer be wildcards if
they show up >1 time in the policy.
This fixes a panic being caused if a ref had an array path segment, by
making a new term we were passing along a nil Location. While we could
correct this by just passing the original term from the ref we can
avoid all this special handling altogether by rewriting the wildcards
earlier.
Fixes: #2430
> format: Refactor wildcard names to rewrite early

- ast/policy.go
- ast/policy_test.go
- compile/compile.go
- compile/compile_test.go
- format/format.go
- format/format_test.go
As part of this change, also update the format package to unmangle the
variables slightly differently--just remove the wildcard prefix
instead of translating the variable names. This makes it easier to
tell where the variables came from in the first place and is a bit
less complicated.
Fixes #2439
> format: Deep copy inputs to avoid mutating the caller's copy

- compile/compile.go
- docs/content/wasm.md
Previously it was being bound to `$result` but this was then stripped
out of the resultset by the planner. To avoid this issue we need the
variable to not be seen as a wildcard or generated var. The new one
is just `result`.
The documentation is also now updated to show this behavior. The
various client SDK's can strip it out as needed.
The idea is that this is going to just be a part of the built WASM
binary format. Anyone building with the lower level API's using
ad-hoc queries will not need to worry about anything changing.
Fixes: #2441
> compile: Change name of result var for wasm binary

- CHANGELOG.md
- Makefile
- ast/policy.go
- ast/policy_test.go
- compile/compile.go
- compile/compile_test.go
- docs/content/wasm.md
- format/format.go
- format/format_test.go
Including a handful of fixes for:
* #2441
* #2439 
To unblock some cases of the `opa build` command and WASM users.
> Prepare v0.20.5 release

- compile/compile.go
- topdown/eval.go
- topdown/topdown_partial_test.go
This PR fixes #2455 and contains an improvement on the new compile package implementation that's needed for performance reasons.
> Fix memoization bug in PE of partial object rules

- MAINTAINERS.md
Adding the same maintainers who maintain the gatekeeper repo to the gatekeeper-library repo
> Add maintainers for gatekeeper-library

- test/scheduler/scheduler_bench_test.go
- test/scheduler/scheduler_test.go
- topdown/aggregates_test.go
- topdown/builtins/builtins.go
- topdown/topdown_test.go
The the arithmetic and aggregate builtin functions make use of
builtins.FloatToNumber to convert big floats back into AST number
values for returning to the evaluator. Previously the
builtins.FloatToNumber function used big.Float#String to perform the
conversion--however, this function sets the default precision to 10
which causes loss of precision. The fix simply updates the helper
function to use big.Float#Text instead and set precision to -1 which
uses as many places as necessary. In future, we may want to give users
control over precision to aid in situations where clients cannot deal
with large JSON numbers.
Fixes #2469
> topdown: Fix loss of precision in arithmetic and aggregate builtins

- ast/compile.go
- ast/compile_test.go
- ast/index.go
- cmd/eval.go
- compile/compile.go
- compile/compile_test.go
- docs/content/policy-performance.md
- rego/rego.go
- rego/rego_test.go
- topdown/eval.go
- topdown/eval_test.go
- topdown/query.go
- topdown/save.go
- topdown/topdown_partial_test.go
- topdown/topdown_test.go
- util/test/subtest17.go
This PR contains a bunch of fixes to partial evaluation and a new optimization level for `opa build`.
The new optimization level (`-O=1`) does not inline rules that depend on unknowns. Only rules that are completely known at build-time are evaluated out of the policy. In addition, the copy propagation and negation inlining optimizations are disabled in this mode. This way the output from `opa build` should be structurally similar to the input policy (except for virtual docs that are completely known at build-time; those are removed.)
This PR also improves PE coverage so that references to the full extent partial set/object rules do not trigger an immediate save--instead, inlining is disabled and PE continues.
> Add less aggressive partial evaluation mode to build command

- docs/content/integration.md
Hi, I found two small pieces make the example not working. I found these two changes can make it work
1. module should be policy string above
2. pass context instance for `.Eval`
also add decision output in the example
> docs/content: fix go integration example

- plugins/rest/aws.go
- plugins/rest/aws_test.go
Fixes: #2482
Signed-off-by: Nick Williams <nhw@me.com>
> Implement IMDSv2 for AWS metadata service

- ast/compile.go
- ast/compile_test.go
- docs/content/policy-performance.md
In v0.20. we added support for indexing and caching of comprehensions
in certain cases. There was a bug in the index construction that
allowed for comprehensions to be indexed and cached
incorrectly. Specifically, if any of the candidate keys appear in
nested comprehensions, indexing should not be performed because the
evaluator does not close over variable bindings from the outer scope
when evaluating the comprehension (because this would require cache
invalidation if there were multiple assignments to the variables in
the outer scope).
This fix updates the compiler to check if the candidates appear inside
of any nested comprehensions. If a match is found, no indexing is
performed.
Fixes #2497
> ast: Disqualify indexing if candidate found in nested comprehension

- .github/workflows/nightly.yaml
- Makefile
- docs/devel/DEVELOPMENT.md
We will run the golang race detector nightly (to start with.. we'll
adjust the workflow as needed).
One thing to note is that currently cgo is required for the race
detector, so we have to enable it when running this make target.
Fixes: #2388
> Add nightly github action workflow with race detector job

- topdown/eval.go
- topdown/topdown_partial_test.go
Previously, if an expression was saved due to a `with` statement
containing an unknown value, the vars in the expression were not
marked as unknown. This resulted in subsequent expressions that
depended on those unknowns being evaluated incorrectly.
This commit fixes the issue so that vars in the outputs from the
expression are marked as unknown.
> topdown: Mark vars as unknown in exprs saved due to with stmts

- .github/workflows/nightly.yaml
- docs/devel/DEVELOPMENT.md
We are using a 3rd party action to simplify this. It appears to be
relatively well used, and the code looked pretty safe. It only has
access to the slack webhook secret, which is itself restricted in
permissions, so the risk is minimal.
It is configured to post a message for jobs that fail to the OPA
slack in the #development channel.
> CI: Add slack notifications for periodic jobs

- Makefile
- wasm/Makefile
The `push-builder` target will now check if the tag is already
available via a test with `docker pull`. It will only build and
push if the image is not available remotely.
> CI: Skip pushing wasm builder unless required

- ast/builtins.go
- docs/content/policy-reference.md
- go.mod
- internal/semver/LICENSE
- internal/semver/semver.go
- internal/semver/semver_test.go
- topdown/semver.go
- topdown/semver_test.go
I recently wrote a [gist](https://gist.github.com/charlieegan3/76dbec05c65164ac98dfec74b1381c5a) to compare Semantic Version strings as a proof of concept for something I was working on. Given the domains that OPA is commonly used in, I thought this might be a useful built-in. Especially after learning that it was hardly trivial in Rego alone (see gist).
Our use case was comparing installed software with recommended/insecure versions of the same applications.
Here is an example of what the functions look like:
```
> semver.is_valid("1.0.0")
true
> semver.is_valid(1)
false
> semver.compare("1.0.0", "2.0.0")
-1
> semver.compare("2.0.0", "1.0.0")
1
> semver.compare("1.0.0", "1.0.0")
0
> semver.compare("1.0.0", "1")
1 error occurred: semver.compare("1.0.0", "1"): eval_builtin_error: …
```
> Add is_valid and compare SemVer built-ins

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/regex.go
- topdown/regex_test.go
- topdown/topdown_test.go
I think this is quite self-contained/explanatory. I've also updated the docs to refer to `regex.match` so that we move away from `re_match`.
> Add regex.is_valid built-in function

- rego/rego.go
- rego/rego_test.go
- topdown/builtins.go
- topdown/eval.go
- topdown/query.go
- topdown/time.go
- topdown/time_test.go
Previously topdown did not expose a way for the caller to set the wall
clock time. This makes it impossible to reliably replay policy queries
that depend on time of day. With this change, callers can supply the
wall clock time to use for time.now_ns() calls.
> topdown, rego: Add parameter to set wall clock time

- .github/workflows/post-merge.yaml
- .github/workflows/post-tag.yaml
- Makefile
- docs/devel/DEVELOPMENT.md
- internal/report/report.go
- internal/report/report_test.go
We previously supported overriding via an environment variable, but
this meant for anyone who wanted to run their own telemetry endpoint
they would _always_ have to specify it while running their OPA's.
This change allows for someone to build OPA and encode the custom
url as the default. Ex:
```
make build TELEMETRY_URL=http://localhost:9876/custom/
```
> report: Support build-time telemetry URL

- plugins/rest/aws.go
- plugins/rest/aws_test.go
The AWS v4 signing feature for bundle requests would automatically
add a `Host` header by using the URL hostname. This would break for
URLs that specified a port number (eg: https://127.0.0.1:9000/). That
causes issues with sending a valid request.
This commit changes to use the `URL.Host` which will have the full
`host:port` string, when a port was specified.
Fixes: #2568
> plugins/rest/aws: Include port in Host header

- .github/workflows/post-merge.yaml
- .github/workflows/post-tag.yaml
- docs/devel/DEVELOPMENT.md
Previously we had some required configuration for the Github Actions,
and forks of OPA would need to set them _and_ have the underlying
infra configured (eg, docker registries, s3 bucket, etc).
Now it will check if the secrets are set, and if any required ones
are missing it will skip the steps.
This significantly lowers the bar for OPA forks to be able to run the
normal action workflows without getting errors. The only lost
functionality is primarily around publishing release assets, which
is not required for dev forks, and other forks can opt int to pieces
they care about (eg, only want to publish docker images and no
s3 release assets).
> CI: Skip asset upload/push when missing config

- .github/ISSUE_TEMPLATE.md
- Markdown only allows one # title
- use comments so people don't have to remove content
Apparently, this repo isn't using the latest variant of how _issue templates_ can work in github: https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser -- but I've only been wanting to address a tiny pet-peeve of mine here.
> .github: minor changes to ISSUE_TEMPLATE.md

- ast/check_test.go
- ast/term.go
- docs/content/policy-language.md
- topdown/topdown_test.go
Previously, when OPA attempted to convert an ast.Object to interface{}
it would error if the ast.Object contained any keys that were not
ast.String values. This behaviour was implemented because JSON only
supports object keys as strings.
This commit changes the conversion implementation to simply JSON
marshal non-string object keys when they are encountered. This way
we avoid runtime errors which can be difficult to debug.
Fixes #516
> ast: Marshal non-string object keys when converting to interface{}

- docs/content/wasm.md
- test/wasm/assets/test.js
SDKs don't need to set the heap top address because it's managed by
the malloc implementation and should be left intact across
executions (otherwise the malloc implementation will keep allocating
more memory from the host because the top has been reset across
executions.)
> wasm: Remove references to the heap top address

- ast/check.go
- ast/compare.go
- ast/compile.go
- ast/env.go
- ast/policy.go
- ast/term.go
- ast/transform.go
- ast/unify.go
- ast/visit.go
- topdown/eval.go
The improved iteration doesn't require hashing keys as with complex keys the cost of hashing can become dominant. On a particular policy, this patch improved the evaluation time 10+%.
The second patch introducing the direct use of *object (instead of Object) is to help escape analysis and avoid introducing new mallocs within the ast package when passing a function parameter to Object.Foreach.
Major changes in the benchmarks:
```
RewriteDynamics/1-16                            268ns ± 3%     221ns ± 2%  -17.24%  (p=0.000 n=10+8)
RewriteDynamics/10-16                          2.60µs ± 1%    2.13µs ± 1%  -18.10%  (p=0.000 n=9+10)
RewriteDynamics/100-16                         27.9µs ± 1%    22.7µs ± 3%  -18.83%  (p=0.000 n=9+10)
RewriteDynamics/1000-16                         299µs ± 2% …
```
> ast: Improved object iteration

- cmd/deps.go
- cmd/flags.go
- Changed the data flag description to specify that it can take policy
or data files
- Suffixed some descriptions with "This flag can be repeated." where
applicable
Fixes: #2586
Signed-off-by: Alan Silva <alansq16@gmail.com>
> Changing opa cli flag descriptions to match online docs

- config/config.go
- docs/content/configuration.md
- docs/content/policy-reference.md
- plugins/plugins.go
- plugins/plugins_test.go
- rego/rego.go
- rego/rego_test.go
- server/server.go
- topdown/builtins.go
- topdown/cache/cache.go
- topdown/cache/cache_test.go
- topdown/eval.go
- topdown/http.go
- topdown/http_test.go
- topdown/query.go
- topdown/topdown_test.go
This commit adds a new inter-query cache that built-in
functions can use to cache responses across queries.
The OPA config includes a new "caching" field that can be used
to set the size of the cache. By default there is no limit.
This change also updates `http.send` to optionally utilize the
inter-query cache.
Fixes #1753
> Add a new inter-query cache to cache responses across queries

- cmd/run.go
- runtime/plugins_test.go
- runtime/runtime.go
- util/wait.go
- util/wait_test.go
A new flag introduced `--wait-bundle-timeout`.
This flag controls how long OPA server will wait for configured bundles
to be activated/loaded before listening for incoming traffic.
```bash
opa run -s --wait-bundle-timeout 10s -c config.yaml
```
This can be useful if you can't use the /health?bundle=true endpoint to check for "operational readiness", and 
want to make sure the OPA server is "operational ready" before serving any traffic.
Came across this "obstacle" when running an OPA server in Google Cloud Run, where there's no way of configuring/using a health check. Cloud Run will start serving traffic as soon as the listening `PORT` is open, and so when using OPA server with bundle service, the server is not yet "operational ready".
I guess this could have been solved by some (rather …
> feat: server wait for bundle activation

- runtime/plugins_test.go
We were starting to see test flakes because the timeouts were not very
forgiving. Bumping them so that the difference is orders of magnitude
to account for environments like GHA.
> runtime: Make plugin readiness timeout tests a bit more forgiving

- docs/content/policy-testing.md
The test examples cannot be opened into the playground because they
require multiple files and the playground UI does not support that
today.
Fix #2073
> docs: Remove openable tag from test examples

- topdown/builtins.go
- topdown/eval.go
- topdown/http.go
- topdown/http_test.go
- topdown/query.go
Previously the built-in functions had no way to record metrics for
performance monitoring or other purposes. With this change, built-in
functions can manipulate the evaluation metrics. Initially, only the
http.send function has been updated to report latency.
Fixes #2034
> topdown: Pass metrics to built-ins and record http.send latency

- compile/compile.go
- compile/compile_test.go
- docs/content/policy-performance.md
Previously the build command and the compile package would only mark
input as unknown. If documents under data needed to be treated as
unknown, there was no solution. This commit updates the compile
package to infer unknowns based on the bundle roots. If the policy
refers to a data document _outside_ of one of the bundle roots, that
data document will be marked as unknown during optimization/partial
eval.
Fixes #2581
> compile: Add support for unknowns other than input

- docs/content/configuration.md
- docs/content/management.md
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/rest/rest.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
These changes include:
* A new configurable timeout to the Services
config to set the amount of time to wait for the server's
response headers. Fixes: #2014
*  Logic to set the values for the last request and last successful request
in the discovery bundle status. Fixes: #2630
> Add response header timeout and update discovery bundle status

- plugins/rest/rest.go
After upgrading to 0.23.1 bundle download fails — "context canceled loop"
```text
[INFO] Initializing server.
addrs = |
[
":8181"
]
diagnostic-addrs = []
insecure_addr = ""
[INFO] Starting bundle downloader.
plugin = "bundle"
name = "default"
[INFO] Starting decision logger.
plugin = "decision_logs"
[ERROR] Bundle download failed: bundle read failed: archive read failed: context canceled
plugin = "bundle"
name = "default"
[ERROR] Bundle download failed: bundle read failed: archive read failed: context canceled
plugin = "bundle"
name = "default"
[ERROR] Bundle download failed: bundle read failed: archive read failed: context canceled
plugin = "bundle"
name = "default"
[ERROR] Bundle download failed: bundle read failed: archive read failed: context canceled
plugin = "bundle"
name = …
```
> fix: bundle download failed - context canceled

- ast/check.go
- ast/check_test.go
- ast/compile.go
- ast/compile_test.go
- types/types.go
- types/types_test.go
This PR contains a few combined commits that fix panics found through fuzz testing.
> Fix issues discovered through fuzz testing

- ast/builtins.go
- capabilities.json
- docs/content/policy-reference.md
- test/cases/testdata/urlbuiltins/test-urlbuiltins-1076.yaml
- topdown/encoding.go
This builtin is the reverse of the encode_object builtin and
makes it easier to use the URI query parameters in policies
Fixes #2647
Signed-off-by: Frederic <frederic.vanreet@icloud.com>
> topdown: Add urlquery.decode_object builtin

- Makefile
- build/gen-dev-patch.sh
- build/gen-release-patch.sh
- build/get-build-version.sh
- plugins/logs/plugin_test.go
- version/version.go
This way the semantic version is always set. Tested by generating a fake release:
Cutting the release:
```
(dev)torin:~/src/opa$ make release-patch VERSION=0.24.0 > ~/test.patch
(dev)torin:~/src/opa$ patch -p1 < ~/test.patch
(Stripping trailing CRs from patch; use --binary to disable.)
patching file CHANGELOG.md
(Stripping trailing CRs from patch; use --binary to disable.)
patching file capabilities/v0.24.0.json
(Stripping trailing CRs from patch; use --binary to disable.)
patching file version/version.go
(dev)[*]torin:~/src/opa$ git add .
(dev)[*]torin:~/src/opa$ git commit -a -m 'wip: prepare release'
[dev 077c73b0] wip: prepare release
3 files changed, 3236 insertions(+), 2 deletions(-)
create mode 100644 capabilities/v0.24.0.json
(dev)torin:~/src/opa$ git tag v0.24.0
```
Checking the …
> build: Move VERSION into version/version.go

- CHANGELOG.md
- topdown/http.go
Currently the recorded metric name is "timer_rego_builtin_http.send_ns" which seems inconsistent.
This is not backwards compatible but before even trying to address that, I thought I should raise the PR to understand is the naming intentional.
> topdown: Use an underscore instead of a dot in http.send metric name.

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
The current age of a http response is calculated as the difference
between the current time and the value contained in the "Date" response
header. There are couple of scenarios that could lead to the current age
being represented as a negative duration.
1. Since the value of "Date" response header is parsed using Go's
time.Parse method, it does not contain a monotonic clock reading. As a result,
the time.Sub method uses wall clock readings to determine the difference between
current time and the parsed version of the response time.
2. The server could set a value for the "Date" response header which may not be a true indication of
when the response was generated.
This change updates the logic that determines whether a cached response is fresh or not,
to treat the resposne as stale if the …
> topdown: Address negative duration for the current age of http response

- ast/builtins.go
- capabilities.json
- test/cases/testdata/base64builtins/test-base64builtins-0935.yaml
- topdown/encoding.go
Adds a builtin to verify a string is valid base64. Since it just covers base64, this is perhaps more of a start on #2690 than a full fix, for now, to verify (hah!) that I'm on the right way.
If everything looks good, I can add base64url, urlquery, json and yaml.
> topdown: Add base64.verify builtin

- ast/compile.go
- ast/compile_test.go
- ast/parser_ext.go
- ast/transform.go
- ast/unify.go
The compiler was panicking when it encountered object literal with a comprehension key because the comprehension body may be rewritten which would corrupt the object value.
> Fix panic during safety check reordering

- ast/parser_ext.go
- ast/parser_test.go
This commit fixes a panic caught in the fuzzer due to misuse of
operands returned by expr.Operand().
Fixes #2714
> ast: Fix panic in parser post-processing of expressions

- ast/builtins.go
- capabilities.json
- docs/content/policy-reference.md
- internal/cidr/merge/merge.go
- test/cases/testdata/netcidrmerge/test-netcidrmerge0117.yaml
- topdown/cidr.go
This commit adds a new builtin to merge adjacent subnets and return the
smallest possible list of CIDRs.
To help with computing CIDR blocks between two
IP networks, an implemetation from https://github.com/cilium/cilium
is leveraged.
Fixes: #2692
> Add net.cidr_merge function to produce smallest possible list of CIDRs

- runtime/runtime_test.go
The runtime tests for the telemetry reporting feature contained a data
race because they were setting the version.Version variable which is
read by the runtime in other test cases. Since we now have the
version.Version value set in the source code, we do not have to
overwrite it in the test implementation.
> runtime: Fix data race in runtime package test

- cmd/build.go
- cmd/check.go
- cmd/flags.go
The build and check commands were retrieving registered builtins too
early during initial execution, which did not give enough time for
custom binaries to register custom builtin functions. This change
sets the initial capabilities flag to nil instead, and then retrieves built-ins
immediately prior to instantiating a new compiler. This prevents an
undefined function rego_type_error during the build and check commands.
Fixes #2738.
This is my commit message
> Fix #2738 - undefined function for custom-builtins

- docs/content/configuration.md
- docs/content/management.md
- plugins/bundle/config.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
This commit adds support to persist and load bundles from disk.
A new field is introduced in OPA's bundle configuration that can
be optionally set to specify the location on disk to write and read
bundles. This feature will allow OPA to serve policy decisions in scenarios
such as OPA being unable to communicate with the bundle server.
Fixes #2097
> plugins/bundle: Support for saving and reading bundles from disk

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
If the size of the decision logs buffered exceeeds that of `upload_size_limit_bytes`, the upload will be split into chunks. If one of the attempted uploads return with an error the chunk is stored in the "new" buffer and will be re-attempted at the next invocation of the `oneShot` method. However, once that is done the function returns, leaving any decisions left in the buffer to be discarded.
I've reproduced this by queuing up decisions in OPA above `upload_size_limit_bytes` and having an external mock server on the receiving end which randomly responds with non-OK status codes. Not having written too much golang (yet!) I could however use some guidance in porting these to the OPA test suite.
As for the fix itself - an alternative (and perhaps more sensible?) approach would be to stop …
> Fix discarded logs on chunk upload failure

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
This commit adds two new fields to the http.send builtin
that allow the user to override the caching directives defined
by the server and thus get more control over the caching
behavior.
Fixes: #2666
> topdown/http: Add support for controlling caching in http.send

- Makefile
I keep editing the Makefile to skip WASM when I just want `make build`. I'm aware that I could use `make build-darwin` instead, but my preferred way is to not have docker running 😄 
Anyways, pet peeve aside, I think it's slightly more correct to not assume that docker was running just because the binary is present.
> Makefile: don't attempt to use docker if it's not running

- cmd/version.go
- cmd/version_test.go
- version/version.go
I've seen this in other tools and I thought it was useful.
**To be discussed**: Would you think this should be included in the provenance API response data, too? (I'm inclined to say no...)
> cmd/version: include golang version in output

- plugins/rest/rest_test.go
While toying around with a custom credential plugin I noticed that changing the `wantErr` values had no effect to the outcome for the TestNew tests - they would always pass. This was due to:
1. The `New` function only unmarshalling the JSON config, not actually instantiating plugins and clients (which is where the validation step is done).
2. wantErr was only checked if false on errors, not its opposite, i.e. not if wantErr == true and error == nil.
> Fix plugin config instantiation tests

- topdown/http.go
- topdown/http_test.go
Earlier the validation of the force_cache parameters was performed
after creating the inter-query cache object. So if 'force_cache' was
set and 'force_cache_duration_seconds' was not provided, OPA in server mode
would correctly return an error but OPA running in repl mode would not
return an error and simply would fall back to using the intra-query cache.
This commit updates how the 'force_cache' parameters are validated so that
consistent behavior is seen in both repl and server modes.
> topdown/http: validate force_cache parameters

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
This change updates how errors from http.send are handled.
By default, an error returned by `http.send` halts the policy evaluation.
This commit allows users to return errors in the response object
returned by `http.send` instead of halting evaluation.
Fixes: #2187
> topdown/http: handle http.send errors in-band

- docs/content/policy-language.md
Tiny fix for #2780 to link to the "Grammar" section correctly.
> Docs: Fix incorrect anchor link to Grammar

- docs/content/configuration.md
- plugins/rest/rest.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
Allows OPA to obtain OAuth2 access tokens and present them as bearer tokens for authentication at remote endpoints.
Tested against the AWS Cognito authorization server.
Fixes #1205
> Add REST client option for OAuth2 client credentials

- docs/content/kubernetes-tutorial.md
Create SAN certificate for OPA service because Go 1.15 deprecated CN support.
Go 1.15 [deprecated CN support](https://golang.org/doc/go1.15#commonname) so latest Kubernetes `1.19` which is built on that version
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
has issues with CN only usage.
K8s API server cannot communicate with …
> docs: Update Kubernetes tutorial to create SAN certificate

- plugins/logs/plugin.go
..by breaking out of loop if context is cancelled.
Fixes #2792
Ping @patrick-east 
> Fix decision log hang

- bundle/keys.go
- bundle/keys_test.go
- cmd/build.go
- cmd/build_test.go
- cmd/run.go
The "verification-key" flag used by the `run` and `build` commands
should be able to handle a PEM file containing a public key.
Earlier we were not checking if the value of the flag represents
a file on disk. This change will check if the value points to a
file, then read it contents and set the public key accordingly.
Fixes: #2796
> bundle: Support for handling PEM file containing the public key

- topdown/input.go
- topdown/input_test.go
This commit updates the merging logic to copy input values if
needed to prevent the input values from being mutated unexpectedly. A
copy is required if subsequent with statements would modify a previous
value--this can be caught by checking if any of the subsequent with
statement targets are prefixed by the current with statement target.
This change is required because although topdown plugs with statement
values before merging, the values are not deep copied--they are passed
by reference.
Fixes #2813
> topdown: Fix merge to copy input values if needed

- internal/deepcopy/deepcopy.go
- internal/deepcopy/deepcopy_test.go
- plugins/logs/mask.go
- plugins/logs/mask_test.go
- plugins/logs/plugin.go
- storage/inmem/txn.go
When mask rules targeted /result, it was modifying both the result
in the decision logs (intended) and the result in the API
response (unintended). Added a step to deep copy the result only once, if
there is at least one mask rule targeting the result.
Fixes #2752
Signed-off-by: Grant Shively gshively@godaddy.com
> plugins/logs: Fixes unintended mutation of result

- ast/builtins.go
- capabilities.json
- docs/content/policy-reference.md
- test/cases/testdata/jsonbuiltins/test-is-valid.yaml
- topdown/encoding.go
Follows the naming scheme set by `base64.is_valid`, `regex.is_valid`, and `semver.is_valid`.
> topdown: add yaml.is_valid and json.is_valid

- rego/example_test.go
- topdown/parse_bytes_test.go
- util/graph_test.go
E.g. `GOARCH=386 go test ./...`
- Some tests were failing because of Int overflow
- Test `ExampleRego_custom_function_caching` was failing because it was dependent of rand default seed on 64bits arch
> tests: fix tests failing on 32-bit arch

- plugins/logs/plugin.go
- plugins/plugins.go
- plugins/status/plugin.go
- plugins/status/plugin_test.go
- runtime/runtime.go
- test/e2e/logs/console/console_decision_logger_test.go
This allows logging to console for decisions and status (and possibly other use cases) without having to follow the generic --log-level.
Fixes #2733
> Separate console logger for plugins

- test/cases/testdata/replacen/test-replacen-0374.yaml
- test/cases/testdata/replacen/test-replacen-bad-operands.yaml
- topdown/strings.go
Fixes #2822.
A quick check with the old and new implementation shows:
$ for i in $(seq 0 1000); do ./opa_master eval --format=pretty 'strings.replace_n({"f":"x", "foo": "xxx"}, "foobar")' | grep -v xoobar; done | wc -l
127
$ for i in $(seq 0 1000); do ./opa_wip eval --format=pretty 'strings.replace_n({"f":"x", "foo": "xxx"}, "foobar")' | grep -v xoobar; done | wc -l
0
So the non-determinism should be dealt with.
~Still planning to add test cases to pin down the current behaviour.~ ✔️
> topdown/strings: make strings.replace_n use builtins.ObjectOperand

- Makefile
With the latest CI changes to auto-generate the wasm binary and commit
post-merge we need to have the ci-wasm target run `go generate`. Since
the `wasm-test` target already does this, just re-use it.
> Makefile: Update ci-wasm target to generate wasm binary

- .github/workflows/post-merge.yaml
The "post-merge" flow would trigger whenever a commit is pushed, which
includes when we auto-generate the wasm binaries. If (for whatever
reason) that generate step was non-deterministic it would potentially
mean the CI looping and adding commits until we manually intervene.
This changes to prevent the step from being able to commit on top of
another auto-generated commit.
> ci: Prevent commit loop if build is non-deterministic

- .github/workflows/post-merge.yaml
The token used to push code needs to have enough permission to avoid the branch protection rules. This change pulls a token from the secrets configured on the repo.
> ci: Use a separate token for pushing code

- compile/compile.go
- compile/compile_test.go
- docs/content/wasm.md
- internal/compiler/wasm/wasm.go
- internal/compiler/wasm/wasm_test.go
- internal/ir/ir.go
- internal/ir/walk.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- rego/rego.go
- wasm/src/context.c
- wasm/src/context.h
This PR adds support for multiple entrypoints. See individual commit messages for details.
I don't have an end-to-end test for this feature yet. I'm going to look to see how much work it would be to overload the existing node-based testing we do.
> wasm: Add support for multiple entrypoints

- cmd/build.go
- cmd/build_test.go
Fixes #2848.
Passing `--capabilities` to `opa build` now has the desired effect.
> cmd/build: fix parameter handling

- internal/planner/planner.go
- test/wasm/assets/010_else.yaml
Previously the planner generated an instruction at the end of each
block to check if the return value was defined. If for any reason the
block were to set the return value but then fail before reaching the
end, the check would be skipped and execution would continue to the
next block that in turn could attempt to set the return value causing
a runtime error.
This commit modifies the planner to instead generate the return value
check at the beginning of each block except the first. This ensures
that blocks short-circuit (as expected for ordered rules) but it also
ensures that failures in previous block do not accidentally cause a
fallthrough to later blocks.
This issue was observed with a policy that happened to generate a scan
over the virtual _and_ base document trees.
Signed-off-by: …
> wasm: Fix planning of ordered rules

- plugins/logs/plugin_test.go
This reverts commit ac06c3b73c2fe6ea0781d743dd69f7c999d6c166.
There are test failures because we are attempting to write on the closed channel: https://github.com/open-policy-agent/opa/runs/1355466937?check_suite_focus=true
It seems like even though the plugin shut down it may attempt to retry sending the log. Not sure if we really care or not (at that point it is sort of a "best effort" to get them out of OPA). In the meantime we don't want the tests being flakey so we can revert this.
> Revert "plugins/logs: Close channel in unit test"

- plugins/bundle/config.go
- plugins/bundle/config_test.go
For the deprecated `bundle` config style bundle configuration we were
not setting the default bundle size limit, instead a zero value was
being propagated through when we "upgraded" the older style config
to the newer values.
This corrects that issue by always setting it to the default size
limit, which maintains the previous behavior.
> plugins/bundle: Fix default size limit

- Makefile
- build/check-vet.sh
- build/run-goimports.sh
- resolver/wasm/nop.go
- resolver/wasm/wasm.go
We would previously gate building the was resolver (and in turn pull
in the wasmer stuff) based on whether or not cgo was enabled. However
for library use-cases this isn't ideal as someone might be using cgo
for an unrelated reason, and not wish to enabled the wasmer code in
opa.
There is now a new go tag for the files called "wasmer" and a makefile
flag WASMER_ENABLED (default on) which will trigger it. This means
any libraries building OPA that want to have it enabled will need to
specify this tag with like `-tags=wasmer` or similar when building.
> build: New flag for wasmer dependencies

- internal/wasm/sdk/opa/http/loader.go
We would potentially set the `closing` channel to nil while a
goroutine was still attempting to read from it. This change corrects
the ordering so that the goroutine will catch when we start to close
and would trigger the for-loop in poller() to stop by cancelling the
context, rather than the select in the loop watching the `closing`
channel directly. This ensures that the context is cancelled before
returning, and that there isn't a race on the readers for `closing`.
Fixes: #2884
> internal/wasm/sdk: Fix race in http loader shutdown

- docs/content/policy-reference.md
HMAC JWT encoding would previously break when base64 URL encoding resulted in padded output. This small doc fix should hopefully make it obvious that padding should be avoided, which is now possible with @johanneslarsson 's  PR.
Fixes #2870
> Fix docs on JWT HMAC encoding

- Makefile
- internal/compiler/wasm/wasm.go
- test/wasm/assets/016_with.yaml
- wasm/src/memoize.c
- wasm/src/memoize.h
- wasm/src/value.c
- wasm/src/value.h
- wasm/tests/test.c
This commit updates the C library to expose a global key-value mapping
that can be initialized and supports push/pop operations for
shadowing. The key-value mapping is implemented using opa_object_t to
keep things simple. In the future, this could be replaced with
something more efficient.
The wasm compiler uses the key-value mapping to memoize calls to
planned functions that only depend on input and data. The compiler
uses the function index as the key and the function return value as
the value. The choice to memoize at the call-site as opposed to inside
planned functions was arbitrary.
> wasm: Memoize planned functions without positional args

- Makefile
In 1cc52431074c226af561a68ba1df2e4071e466c1 the dependency was not
added to the ci-release-test target (which also requires it!)
> Makefile: Add missing generate dependency

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
This removes some time-related stuff from both the implementation and
the unit tests with the aim to make it less flakey.
For the implementation we will now rely only on the deadline set by
the original context. We don't mess with canceling it as the signal
that we've completed. We use a new more explicit done channel.
In the unit test we no longer check that it stopped immediately, it
will instead ensure that the plugin was forcefully stopped with logs
still in its buffer.
> plugins/logs: Refactor shutdown log flushing

- internal/report/report.go
Since one second was enough to cause quite frequent timeouts from outside of the US.
> Increase telemetry timout value

- .github/workflows/post-tag.yaml
The post tag workflow used the set-env command to
set the TAG_NAME env variable. The set-env command is
now disabled. This change updates the workflow to remove
usage of the set-env command to use environment files
instead.
> .github: Update post tag workflow to use env files

- docs/content/configuration.md
- plugins/rest/gcp.go
- plugins/rest/gcp_test.go
- plugins/rest/rest.go
- plugins/rest/rest_test.go
Adds support for fetching access and identity tokens from a GCP
metadata server. Identity tokens are used to authenticate to third
party applications running behind Google authentication proxies
such as containers deployed to Google's Cloud Run.
Access tokens are used to authenticate to first party GCP services
such as Google Cloud Storage.
Signed-off-by: Kelsey Hightower <kelsey.hightower@gmail.com>
> plugin/rest: Add GCP metadata server support

- docs/content/policy-reference.md
Based on discussion in https://github.com/open-policy-agent/opa/pull/2937 the "none" signature algorithm is currently unimplemented as both a signer and a verifier, and there are no plans to add an implementation.
> remove unimplemented "none" signature algorithm from docs

- internal/wasm/sdk/test/e2e/exceptions.yaml
The json.patch test cases are causing panics and runtime errors for
the wasm e2e tests. This commit puts an exception in place for them so
we can come back and fix later.
> wasm: Put exceptions in place for json.patch cases

- docs/content/policy-reference.md
This change adds a new column to the built-in functions
section to indicate if the built-in function is
natively supported in Wasm.
> docs: Add Wasm support indication for builtins

- ast/term.go
- topdown/topdown_bench_test.go
See the commit message for details.
> ast: Improve set implementation to memoize groudness

- plugins/logs/plugin.go
Logging plugin had race condition while it was masking the log and plugin was reconfigured at the same time. This caused panic of the OPA. Fixed issue for us and also may fix #2835 .
Masking part of the logging plugin had incorrectly placed mutex -- only
for writing the variable p.mask, but not for reading it. This caused
race condition in the situation when bundle update calls plugin.Reconfigure()
method between setting the p.mask variable and then evaluating it.
Reconfiguration of the plugin sets p.mask to nil and therefore calling
p.mask.Eval() results in panic.
Tests covering functionality shouldn't change, test covering the fixed issue is not delivered, because it's difficult to write a test simulating the race condition (if you know about some efficient way, feel free to guide me, …
> plugins/logs: fixed reconfiguration race condition

- build/changelog.py
The wasm-updater does not sign-off on changes so there is no e-mail
address in the commit message.
> build: Fix changelog.py to tolerate missing e-mail in commit message

- Dockerfile
- Makefile
We originally set the rpath to be relative to the $ORIGIN which
apparently changes if the working directory is overriden. This change
just fixes the rpath to contain /usr/lib/opa and then updates the
Dockerfile to copy the libwasmer.so file into this new directory.
Fixes #2974
> build: Fix rpath to refer to absolute location

- docs/content/security.md
- server/authorizer/authorizer.go
- server/authorizer/authorizer_test.go
- server/server.go
- server/server_test.go
This commit updates the server's basic authorizer to include the
deserialized message body in the input to the authorization policy so
that the latter can make decisions based on policy query input
documents. The authorizer caches the parsed message body on the
request context and the server retrieves the value to avoid parsing twice.
> server: Add message body to authorization policy input

- docs/content/kubernetes-tutorial.md
By default, in an OpenShift cluster, pods will run as a randomly generated non-root user. That works fine with opa, but this example attempts to bind to port 443. Moving to bind at 8443 allows the pod to run as a non-root user successfully (tested).
> Update tutorial to work running as non-root

- docs/content/configuration.md
- internal/config/config.go
- plugins/discovery/discovery.go
- plugins/plugins.go
- plugins/plugins_test.go
- plugins/rest/gcp.go
- plugins/rest/rest.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
Some notes on the implementation:
- Passing along the authPluginLookup function to avoid a circular import between plugins and plugins/rest.
- Updated `DefaultRoundTripperClient` and `DefaultTLSConfig` to be exported so that custom auth plugins can use them. If this isn't appropriate just lmk.
- This approach seems a little messy to me, but I was having a hard time figuring out how else to implement it that avoided the circular import.
- I nested `plugin` under `custom` for credentials in case there was additional config needed for custom auth.
Plugins that implement the HTTPAuthPlugin can be used with a new credentials options under services:
```
services:
my_service:
credentials:
plugin: my_plugin
plugins:
my_plugin: {}
```
Fixes #2758
> plugins, plugins/rest: Support custom auth plugins

- plugins/plugins.go
- plugins/plugins_test.go
The WARN state can be used to signal admins that a plugin is in a
potentially dangerous or degraded state. The optional message may be
used to provide context about the warning.
Fixes #2932
> plugins/plugins: WARN state and optional message

- internal/wasm/sdk/internal/wasm/bindings.go
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/opa_test.go
- wasm/src/glob.cc
- wasm/src/regex.cc
Before, the opa_string_t's *char was used as-is; disregarding its length.
With certain inputs in consequent evaluations, this would end up using old
characters from a previous evaluation.
For example, evaluation
regex.match("^world$", input.message)
with input.message going through the sequence
"no-world"
"world"
would end up running the RE2 PartialMatch against the values
"no-world"
"worldrld"
and the second evaluation would thus wrongly fail.
Since glob.match is using regex.match underneath, it would show a similar
behaviour, as noted in #2962
Fixes #2962.
In the same spirit, changed some string usages in regex.is_valid and regex.find_all_string_submatch_n.
⚠️ I'm by no means an expert in C++, please review carefully. Any advise is appreciated, of course! 😃 
Also provides an …
> wasm: fix some string-handling issues in regex/glob matching

- internal/compiler/wasm/wasm.go
- internal/ir/ir.go
- internal/ir/walk.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/wasm/sdk/opa/opa_test.go
- test/wasm/assets/007_complete.yaml
- test/wasm/assets/008_functions.yaml
- test/wasm/assets/012_partialobjects.yaml
- test/wasm/assets/013_virtual.yaml
- test/wasm/assets/016_with.yaml
- wasm/src/error.c
- wasm/src/error.h
Note that due to the mapping of rego to imperative code, the errors
may look different than what you'd expect. For example, with this rego,
package fr
p {
f(3)
}
f(x) = "y" {
x > 1
}
f(x) = "z" {
x > 2
}
the runtime error is
fun_rets.rego:12:3: var assignment conflict
Whereas `opa eval` gives you
$ opa eval 'data.fr.p' -d fun_rets.rego --format=pretty
1 error occurred: fun_rets.rego:11: eval_conflict_error: functions must not produce multiple outputs for same inputs
To get here, we're adding a new section to the static part of an ir.Policy: Files.
It's carrying the file name constants, and one special entry called `<query>`.
Most of the work in this change is ensuring that source location info is properly
carried over into the IR statements from AST nodes. There are new tests for the …
> wasm: include source location in runtime errors

- server/server.go
- test/e2e/authz/authz_bench_integration_test.go
- test/e2e/logs/remote/remote_decision_logger_benchmark_test.go
- test/e2e/metrics/metrics_test.go
- test/e2e/testing.go
- test/e2e/wasm/authz/authz_bench_integration_test.go
Fixes #3000.
The assertions on the response metrics object should be enough to
cover the bug -- depending on what is happening during eval, the
keys of that object may differ. (E.g. if there's a ref to be resolved,
that operation is timed; if there are none, there's no timer data.)
> server: pass instrumentation via rego.EvalInstrument

- topdown/bindings.go
- topdown/eval.go
The undo was being allocated on the heap unnecessarily. Removing the
heap allocation provides a slight speedup.
$ benchstat /tmp/old.txt /tmp/new.txt
name                      old time/op  new time/op  delta
ArrayIteration/10-20      24.7µs ± 1%  24.0µs ± 1%  -2.49%  (p=0.008n=5+5)
ArrayIteration/100-20      125µs ± 1%   122µs ± 1%  -2.88%  (p=0.008n=5+5)
ArrayIteration/1000-20    1.15ms ± 1%  1.12ms ± 1%  -2.66%  (p=0.008n=5+5)
ArrayIteration/10000-20   11.9ms ± 2%  11.6ms ± 1%  -2.52%  (p=0.008n=5+5)
SetIteration/10-20        28.3µs ± 1%  27.8µs ± 1%  -1.73%  (p=0.008n=5+5)
SetIteration/100-20        157µs ± 1%   154µs ± 1%  -1.81%  (p=0.008n=5+5)
SetIteration/1000-20      1.47ms ± 1%  1.44ms ± 1%  -2.00%  (p=0.008n=5+5)
SetIteration/10000-20     15.8ms ± 1%  16.0ms ± 4%    ~ …
> topdown: Remove unnecessary allocations for binding undos

- internal/wasm/sdk/test/e2e/exceptions.yaml
- test/cases/testdata/arithmetic/test-arithmetic-0813.yaml
- test/cases/testdata/strings/test-strings-0883.yaml
- test/wasm/assets/018_builtins.yaml
- wasm/src/mpd.c
- wasm/src/strings.c
- wasm/tests/test.c
* test/cases: disregard ordering in "strings/concat: set" test
Since anything can happen, we now list the possibilities (3! = 6), and check that any of them was the result.
Fixes #2924.
* wasm: fix rounding mode
Same as in topdown, we should have this be true in wasm:
round(1.5) == 2
round(2.5) == 3
The default rounding mode for libmpdec's maxcontext was MPD_ROUND_HALF_EVEN, would would round 2.5 to 2.
See https://www.bytereef.org/mpdecimal/doc/libmpdec/context.html#rounding
* wasm: fix number truncation format_int
I'm not exactly sure why we had been rounding here before. Topdown truncates when formatting a decimal number as int:
format_int(15.9, 16) == "f"
format_int(-15.9, 16) == "-f"
Fixes #2923.
> wasm: fix some bugs wrt. comparisons, ordering

- bundle/bundle.go
- cmd/build.go
- compile/compile.go
- compile/compile_test.go
We had still been using the deprecated field, _and_ added a WasmModule
to the bundle, leading to two bundle file entries.
Fixes #3007.
> cmd/build: don't package policy.wasm twice

- ast/term.go
- internal/compiler/wasm/wasm.go
- internal/planner/planner.go
- internal/wasm/instruction/variable.go
- internal/wasm/sdk/opa/opa_test.go
- internal/wasm/sdk/test/e2e/exceptions.yaml
- test/cases/testdata/withkeyword/test-withkeyword-1019.yaml
- test/cases/testdata/withkeyword/test-withkeyword-1035.yaml
- test/wasm/assets/016_with.yaml
- topdown/eval.go
- topdown/eval_test.go
- topdown/exported_test.go
- topdown/input.go
- topdown/input_test.go
This was prompted by #2922. In the WASM implementation, with statements overlapping with existing data in an incompatible way (strings vs objects, for example) had returned a conflict error; in topdown, the with statement had won. However, in topdown, multiple incompatibly-overlapping with statements would yield a conflict error.
Discussing how to approach the issue in WASM, we've come to agree that **simpler semantics** for `with` statements that are "overlapping" (or "in conflict") wouldn't be too bad.
So, where before our topdown and WASM implementations declared defeat, like `input with input.foo as "x" with input.foo.bar as "y"`, it'll now resolve to the last applied statement: in this example, `{"foo": {"bar": "y"}}`.
As for backward compatibility, this change means that some …
> re-do `with` conflicts: last one wins, in wasm and topdown

- internal/jwx/jwk/key_ops.go
- repl/repl.go
This was flagged by staticcheck, reported in #3020.
See also https://staticcheck.io/docs/checks#SA9004
> Fix const types in internal/jwx/jwk/key_ops.go and repl/repl.go

- bundle/bundle.go
- bundle/bundle_test.go
As the docs state, signature verification should only be triggered if a keyid is present in the signing block of a bundle configuration. This was not actually the case though as merely the presence of keys in the config would force signatur verification, even if not referenced by the bundle configuration.
Fixes #3028
> Require signature only when signer configured

- server/server.go
- server/server_test.go
Allow writing to /data/foo when /data/foobar is a bundle root.
Fixes #2868
> Fix false positives in bundle root check

- cmd/bench.go
- cmd/bench_test.go
- cmd/eval.go
- cmd/flags.go
This change allows users to get an accurate estimate of partial eval
performance on their policies.
> cmd: Add support for benchmarking partial evaluation queries

- test/e2e/wasm/authz/authz_bench_integration_test.go
This prevents the benchmarks from panicking if someone runs go test
directly without specifying the `opa_wasm` build tag.
> test: Fix wasm authz benchmark to include build tag

- internal/compiler/wasm/wasm.go
- internal/ir/ir.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/wasm/sdk/opa/opa_test.go
- internal/wasm/sdk/test/e2e/exceptions.yaml
- internal/wasm/sdk/test/e2e/external_test.go
- test/cases/testdata/functionerrors/test-functionerrors-1012.yaml
- test/cases/testdata/functionerrors/test-functionerrors-1013.yaml
- test/cases/testdata/functionerrors/test-functionerrors-1014.yaml
There are two kinds of else conflicts in the e2e tests, and one had been failing in WASM (i.e., it didn't fail when it should).
With this change to the planner, the underlying issue is resolved:
With multiple rule bodies for one rule like this, where r1 and r2 both fail,
- r1
- else1
- r2
- else2
previously, else1 and else2 checked if the output variable used for both r1 and r2 was defined, and didn't run it was.
Topdown, however, evaluates both else1 and else2, and checks that they have the same outcome.
The output variable checking in WASM would prohibit else2 from being run when the output variable was set by else1.
**Now**, each rule and its else branches use an output variable _different from the overall output_; and an extra block writing that output variable's value into the …
> wasm: fix "else-conflict 2"

- internal/planner/planner.go
This was introduced with the source location mapping, #2960.
The set was planned, but never the check for not being a member of the set hadn't been appended; the block just dangles there and is forgotten. Somehow, the `ir.NotStmt` wrapping, while crucial, also got lost. 😬
> planner: actually plan the exclude set comparison (bugfix)

- bundle/keys.go
- bundle/keys_test.go
- cmd/build.go
- cmd/sign_test.go
- docs/content/configuration.md
- download/download_test.go
- internal/config/config.go
- internal/report/report.go
- keys/keys.go
- keys/keys_test.go
- plugins/bundle/config.go
- plugins/bundle/config_test.go
- plugins/bundle/plugin_test.go
- plugins/discovery/config.go
- plugins/discovery/config_test.go
- plugins/discovery/discovery.go
- plugins/plugins.go
- plugins/rest/gcp_test.go
- plugins/rest/rest.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
- topdown/tokens.go
Allow OPA to issue JWT's which it uses to authenticate a configured
OAuth2 client, as described in RFC7523. This replaces the client_secret
as the actual credential and allows for either using an entirely new
grant type called "JWT bearer", or using the previously supported
client_credentials grant type, only with the client_secret replaced
by a signed JWT. This change covers both scenarios described in
RFC7523.
Other changes made to accomodate this feature:
- Add `private_key` attribute to keys struct to allow for both public and
private keys to be stored there.
- Refactored the keys configuration struct and logic to its
own package no longer coupled to bundles.
Closes #3055
> OAuth2 JWT bearer grant type and JWT client auth

- wasm/test.js
- wasm/tests/test-glob.cc
- wasm/tests/test.c
When we've removed the --export-all from the build of opa-test.wasm in
https://github.com/open-policy-agent/opa/pull/3061, we've robbed
wasm/test.js of the ability to see and run them.
Now, the existing tests have been explicitly exported, and the test
runner was adapted to fail if nothing was run at all.
> wasm: re-enable wasm-lib-test

- compile/compile.go
- internal/compiler/wasm/wasm.go
- internal/ir/ir.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/wasm/encoding/encoding_test.go
- internal/wasm/encoding/reader.go
- internal/wasm/encoding/writer.go
- internal/wasm/instruction/control.go
- internal/wasm/instruction/numeric.go
- internal/wasm/instruction/parametric.go
- internal/wasm/module/module.go
- internal/wasm/sdk/opa/opa_test.go
- test/wasm/assets/019_call_indirect_optimization.yaml
- test/wasm/assets/test.js
- test/wasm/cmd/wasm-rego-testgen/main.go
- wasm/src/value.c
- wasm/src/value.h
- wasm/tests/test.c
1. write an object corresponding to data paths into the module data
2. initialize an opa_object_t from that using `_initialize`, called
as the module's Start function
3. write out CallDynamicStmts in IR when the ref is not all ground,
but its vars have been seen
4. compile those CallDynamicStmts to call_indirect invocations in
WASM, preceded by a lookup using the path in the object prepared
in (2.)
5. if the lookup fails to come up with a result, the eval goes
undefined
-----
What it looks like:
With t.rego as
package t
p {
data.foo[input.x].bar.p
}
and foo.rego as
package foo.a.bar
p = true
when building policy.wasm using `opa build -t wasm -e t/p t.rego foo.rego`,
the body of function `g0.data.t.p` will contain
i32.const 5
call $opa_array_with_cap
local.set $11
local.get $11
local.get …
> wasm: dynamically dispatch data functions with "seen" ref pieces using call_indirect

- internal/wasm/sdk/internal/wasm/vm.go
With https://github.com/open-policy-agent/opa/pull/3061, these
functions, that haven't been called from the node or golang SDK,
are not exported anymore.
This is just a small cleanup. (Prompted by #3092)
> wasm/sdk: remove opa_heap_top_{set,get}

- .github/workflows/pull-request.yaml
This attempts to give us some more safety for WASM-related changes.
We don't want to break the SDK!
It's introducing some coordination efforts in the future: when a WASM-
related change is supposed to be merged that requires SDKs to change,
we'll have to merge that into npm-opa-wasm first, before the PR can go
in. However, it's better to have this sort of breaking change smoke
test.
I'm undecided whether it's better in nightly or the per-PR checks. It doesn't
take too long, if I also wouldn't want to pile on too much stuff into per-PR
actions 🤔 
👉  Prompted by #3092.
> ci: run npm-opa-wasm example

- server/server.go
- test/e2e/metrics/metrics_test.go
- test/e2e/testing.go
Hi all!
Solves https://github.com/open-policy-agent/opa/issues/3096.
This change adds a `server_handler` timer to the metrics for any POSTs to `/v1/compile`.
So `curl -X POST localhost:8181/v1/compile?metrics ..` will result in:
```
...
"metrics": {
"timer_rego_partial_eval_ns": 145020,
"timer_rego_query_compile_ns": 86415,
"timer_rego_query_parse_ns": 56104,
"timer_server_handler_ns": 377557  #this line is new
}
```
> Add metrics timer for CompilePost

- docs/content/envoy-authorization.md
Recent versions of envoy's docker container have changed the way
dropping privileges works:
- it happens by default
- it's not driven by `securityContext.runAsUser`
So in the docker container's entrypoint, the environment will be
set up: /dev/std{err,out} will be chowned to an unprivileged user,
which will have uid ENVOY_UID. Hence we set that env variable to
match the UID we us with iptables in open-policy-agent/proxy_init.
Fixes #3101 and the issue described in #3091.
> docs/envoy-authorization: update to transport APIv3, Envoy 1.17

- docs/content/configuration.md
- docs/content/management.md
The console logging of decisions or status updates is no longer coupled to
to the "application logger" and not affected by the log level set there.
Seems the docs wasn't updated to reflect this.
> Update docs on console logging

- internal/compiler/wasm/wasm.go
- internal/planner/planner.go
- internal/planner/rules.go
- internal/planner/rules_test.go
- test/wasm/assets/016_with.yaml
Recursively planning all the rules we've found in the optimization
case will make this happen:
Assume we're optimizing the call for data.foo[x] where x is a "seen"
variable. If we have rules for data.foo[x] (for some `x`) that involve
`with` statements, that bumps the funcstack generation in the planner.
The any subsequent planned rule for data.foo[x] will keep using that
bumped 'gen'; and it will eventually cause the CallDynamicStmt's first
path element -- 'gen' -- to not match any of those functions.
(Descriptions are difficult, there's a test case :D)
> wasm: fix `with` handling in call_indirect optimization

- config/config.go
- config/config_test.go
- docs/content/configuration.md
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
This allows configuring the persistence_directory OPA should use for persisting
bundles to disk. While this currently only covers bundles I didn't want to close
the door for persisting other type of objects later, so the
persistence_directory option is kept at the top level of the configuration,
defaulting to $PWD/.opa if not provided.
Bundles will be persisted to ${persistence_directory}/bundles.
Closes #3085
> Configurable persistence_directory

- internal/compiler/wasm/wasm.go
- internal/wasm/sdk/opa/opa_test.go
- wasm/src/mpd.c
- wasm/src/mpd.h
- wasm/tests/test.c
The minimal test case included would fail because on the second run,
the global `initialized`, used in `mpd.c` to record that `mpd_one` had
been prepared, was true; whereas the value that `mpd_one` pointed to
no longer was a valid mpd_t struct. The addition happening in the loop
of the `numbers.range` implementation would thus fail to add NaN to 1,
and everything goes downhill from there.
To remedy this, we expose the init function as `opa_mpd_init`, and
call it from the module's `Start` function (`_initialize`). As a side
effect, tests in test.c (`make wasm-lib-tests`) that use mpd need to
have opa_mpd_init run, too. Those tests are not randomized, so seems
we're OK with having that executed by the added tests, fairly early on
in test.c
The same bug should have affected certain bits …
> wasm: fix caching of mpd values over multiple runs

- .github/workflows/post-merge.yaml
- .github/workflows/pull-request.yaml
- codecov.yaml
The codecov check is not providing any value. Over time we have had to
tweak the check parameters because of false-positives. As well, the
service is often unavailable when clicking through from GitHub. The
final straw was today when the check stopped showing inside of PRs. At
this point everyone is ignoring it.
> build: Remove codecov check

- internal/wasm/sdk/opa/opa_test.go
- test/wasm/assets/test.js
- wasm/src/value.c
- wasm/tests/test.c
Before, the added/altered test cases would have failed: it came down to the
(undefined) data being a==NULL in opa_value_merge.
Fixes #3130.
> wasm: allow for unknown data

- internal/planner/planner.go
- internal/planner/rules_test.go
Before, the planner had decided to shadow all rules whenever a with statement was targeting "data".
Now, it's looking at the ruletrie to see if whatever ref the with statement targets actually is a rule (or package ref). If so, it'll shadow, if not, it won't.
Fixes #3150.
-----
So, for one of the bundles I've been testing this with, it helped a lot:
- Function count: 1102 -> 816
- module size: 700K -> 516K
In that bundle, there's not been ANY func gen increase, so, no with statement was targeting a virtual rule. It also means that the mapping data we're using for #3058 has become a lot smaller, from
```
g0:
foo:
bar: 10
baz: 11
g1:
foo:
bar: 12
baz: 13
...
g78:
foo:
...
```
to only the g0 subtree.
> wasm: only shadow ruletrie with matching data refs

- ast/capabilities.go
- capabilities.json
- compile/compile.go
- compile/compile_test.go
- docs/content/wasm.md
- internal/compiler/wasm/wasm.go
- internal/wasm/sdk/opa/capabilities/capabilities.go
- internal/wasm/sdk/opa/capabilities/capabilities_nowasm.go
This is meant for declaring minor versions: backwards-compatible changes.
TODO:
> wasm: also emit `opa_wasm_abi_minor_version`

- docs/website/layouts/index.html
- docs/website/static/support.html
This was bother me for a while. We refer to this as the ecosystem page
but the link on the frontpage was titled "Integrations".
> website: Rename link on frontpage to ecosystem page

- ast/policy.go
This saves very little in terms of memory consumption (8 bytes for most structs) but on the other hand doesn't cost anything either. The only struct where I think this will make a marginal difference is the Expr one since there can be quite a few of those in a module.
Using https://github.com/orijtech/structslop
> Re-arrange structs for optimal size

- server/server.go
- server/server_test.go
Policy IDs will be decoded in GET, PUT, and DELETE requests to the /policies endpoint.  This will enable users to include non-alphanumeric characters in policy IDs, as well as leading forward slashes, by URL encoding the path component of their requests.
Fixes #2116
> server: URL decode policy IDs

- internal/compiler/wasm/wasm.go
The unreachable instructions cause a crash in the Go runtime on
macOS. It's unclear why they are ever executed after calling
opa_abort/opa_runtime_error but this was observed to fix the issue.
In the future it would be nice to get rid of the panics in the
Go-defined functions like opa_abort. Instead of panicking those
functions should return traps. The problem is that currently returning
a trap requires closing over a store related object which introduces a
memory leak.
Fixes #3168
> wasm: Do not emit unreachable instructions after opa_abort calls

- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- fixed a bug to unregister a listener and not a bulk listener
- added assertions on existing tests
Fixes #3190
Signed-off-by: Bojan Poprzen <bojan.poprzen@sap.com>
> plugins/bundle: properly unregister a listener

- compile/compile.go
- internal/compiler/wasm/optimizations.go
- internal/compiler/wasm/wasm.go
Allow the use of binaryen's `wasm-opt` on the compiled wasm:
- if either the env var `EXPERIMENTAL_WASM_OPT=yes` or `EXPERIMENTAL_WASM_OPT_ARGS` are set, the compiler will attempt to invoke `wasm-opt` on the compiled module. 
- if neither is set, or `wasm-opt` is not found in PATH, it'll be skipped
- ⚠️ This is to be considered experimental. Until documented, it's subject to change and mostly a vehicle to facilitate exploring what wasm-opt can do to our policy wasm.
Relevant for #3185.
> wasm: wire wasm-opt into optimizations (opt-in)

- docs/content/envoy-primer.md
This commit adds more details explaining some of the
fields of the input available to OPA-Envoy.
> docs: Add input-related content to the Envoy section

- cmd/eval.go
This PR updates `eval` function to use local ignore flags, rather than incorrectly using `checkParams` package variable. 
Currently the ignore flags are not applied to the `eval` command. 
It is worth noting that  `ignore` flags are only applied to `--data` paths, and not `--bundle` paths. This may be tackled in separate PR.
Signed-off-by: p0tr3c <p0tr3c@protonmail.com>
> fix eval command ignore flag support

- rego/rego_wasmtarget_test.go
- repl/repl_wasmtarget_test.go
xyz_wasm_test.go makes go implicitly require the GOOS to be wasm.
That's not what we want here.
Example go test list before:
$ go test --tags=opa_wasm ./repl -list TestReplWasmTarget
ok      github.com/open-policy-agent/opa/repl   0.006s
After:
$ go test --tags=opa_wasm ./repl -list TestReplWasmTarget
TestReplWasmTarget
ok      github.com/open-policy-agent/opa/repl   0.007s
> tests: fix wasm tests

- internal/compiler/wasm/optimizations.go
- internal/compiler/wasm/wasm.go
- internal/ir/ir.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/wasm/instruction/control.go
- wasm/src/aggregates.c
- wasm/src/cidr.c
- wasm/src/conversions.c
- wasm/src/encoding.c
- wasm/src/json.c
- wasm/src/memoize.c
- wasm/src/std.h
- wasm/src/strings.c
- wasm/src/types.c
- wasm/src/unicode.c
- wasm/src/unicode.h
- wasm/src/value.c
- wasm/src/value.h
- wasm/tests/test.c
Mixed bag of optimizations:
- for the `ir.StringConst` of a plan, we emit, in addition to the data section with the zero-terminated character strings, another one: a section of `opa_value *` of type `OPA_STRING`, mimicking what they would look like if we had called `opa_string_terminated` on the pointers of the first section
- whenever there's an `ir.MakeStringStmt`, we're emitting a constant pointer to the `opa_value` we've got in that new section
This measure should reduce the number of heap allocations performed needlessly.
- A small restructuring in the planner/compiler allows us to materialize the strings right before they're appended to the array used with `opa_mapping_lookup`
- Together with the interning change, we end up with
```
i32.const 8
call $opa_array_with_cap
local.set $80 …
```
> wasm: misc optimizations (less locals, blocks, interning strings and booleans)

- cmd/eval.go
- internal/presentation/presentation.go
- internal/presentation/presentation_test.go
This is a very simple addition but it's proven extremely useful to us since
it means you can now use `opa` easily in bash scripts, e.g.:
```bash
ACCOUNT_ID="$(opa eval -d accounts.rego --format raw "data.accounts.account")"
```
This means `accounts.rego` can be used by policies as well as e.g. deploy
scripts.
The naming and functionality is inspired by the `-r` flag from `jq`.  In fact,
`jq` can be used to replicate this behaviour, but it is a bit nicer to not rely
on that system dependency.
I wasn't sure what to do when multiple queries and expressions are given.  I
opted to print these in a newline/space separated way since that is consistent
and plays nice with `bash`.
If this seems like a good addition I'll add some tests to this PR, I wanted
to test the waters first.
Signed-off-by: …
> Add a --format=raw option for eval

- internal/prometheus/prometheus.go
I am not a Golang expert so please feel free to continue my work with another pull request or review mine.
This pull request ditches some higher granularity buckets in favour of adding a
few smaller ones. The bucket that I chose was based on https://www.openpolicyagent.org/docs/latest/policy-performance/#high-performance-policy-decisions
where the expectation is "policy evaluation has a budget on the order of 1 millisecond".
Also, I tried to stay within Prometheus's default 10 buckets.
This, when merged, should fix #3196
> Internal/prometheus: Add smaller buckets

- docs/content/policy-reference.md
Since there are better ways of doing what they do and they tend to confuse
people new to Rego we'll hide these from the policy reference for now. Will
eventually be deprecated and removed with issue #2437.
> Remove any() and all() built-ins from policy reference

- docs/content/configuration.md
- plugins/rest/aws.go
- plugins/rest/aws_test.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
This adds a new `service` option to the `s3_signing` config, allowing for other AWS services (such
as API Gateway endpoints) to be used for bundles, decision logs etc.
For example:
```yaml
services:
decision-log-service:
url: https://myrestapi.execute-api.ap-southeast-2.amazonaws.com/prod/
credentials:
s3_signing:
service: execute-api
environment_credentials: {}
decision_logs:
service: decision-log-service
reporting:
min_delay_seconds: 300
max_delay_seconds: 600
```
If no service is specified, we default to `s3` to maintain backwards compatibility.
This updates the sigv4 signer to include the specified service in the signature, and to sign all
request headers for better compatibility with other AWS services, except an explicit ignore list,
as per …
> plugins/rest: SigV4 Signing for any AWS service

- ast/compile.go
- ast/compile_test.go
Before, `resolveRefs` ignored Imports when Package is nil.
This caused `opa eval --import` option to be ignored without `--package` option.
This PR makes query compiler generate temporary package with name of ""
(empty string) when package is nil but import one or many imports are provided.
For example, we have two files.
`filter1.rego`
```
package f
getFamily(i) = { rtn |
rtn := i.characters[_].family
}
getChildren(family) = { rtn |
rtn := family[_].children
}
```
`data.json`
```
{
"characters": [
{
"id": 0,
"name": "Marty McFly",
"cast": "Michael J. Fox",
"family": {
"children": [
"Marty McFly Jr.",
"Marlene McFly"
]
},
"occupation": "student"
}
]
}
```
Before, we had this error because of no `--package` option.
```
opa eval -I --format=pretty -d filter1.rego --import 'data.f' …
```
> ast: parse import without package in resolveRefs

- internal/rego/opa/nop.go
- internal/rego/opa/opa.go
- internal/rego/opa/options.go
- internal/wasm/sdk/internal/wasm/bindings.go
- internal/wasm/sdk/internal/wasm/pool_test.go
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/opa.go
- rego/rego.go
- rego/rego_wasmtarget_test.go
This commit updates the rego package to propagate the time option all
the way down to the SDK and into the built-in dispatcher. This way
callers can control the time-of-day observed by wasm compiled policies.
> wasm: Add support for time option via rego package

- ast/term.go
- ast/term_test.go
- rego/rego.go
In some cases, the caller needs to be able to control the order that
sets are serialized into JSON arrays. This commit adds that wrapper
and exposes the option in the rego package.
> ast: Add ast.JSONWithOpt to complement ast.JSON

- internal/compiler/wasm/optimizations.go
- internal/compiler/wasm/wasm.go
We know which builtins are backed by re2. So, we'll drop all the re2-
related code if they're not used.
With this, the no-op policy gets down to 116K.
Fixes #3250.
<details><summary>example policy.wasm dump from #3250</summary>
```
policy.wasm:	file format wasm 0x1
Section Details:
Type[29]:
- type[0] (i32, i32, i32) -> i32
- type[1] (i32, i32) -> i32
- type[2] (i32, i32) -> nil
- type[3] (i32, i32, i32, i32) -> nil
- type[4] (i32) -> nil
- type[5] (i32) -> i32
- type[6] (i32, i32, i32, i32, i32) -> nil
- type[7] (i32, i32, i32) -> nil
- type[8] (i32, i32, i32, i32, i32, i32, i32) -> nil
- type[9] (i32, i32, i32, i32) -> i32
- type[10] (i32, i32, i32, i32, i32, i32) -> i32
- type[11] (i32, i32, i32, i32, i32) -> i32
- type[12] () -> i32
- type[13] () -> nil
- type[14] (i32, f64) -> i32
- …
```
> wasm: exclude re2 code if no entrypoint found

- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
This was caused by new logger not getting properly initialized in NewClient
call.
Fixes #3255
> Fix crash in v0.27.0 when s3_signing is configured

- internal/compiler/wasm/optimizations.go
- internal/compiler/wasm/optimizations_test.go
There was an offset issue in the calculation if which code entries to stub out and which ones to keep.
I'm still rubbing my eyes on this one, how could this have worked? Lucky accident? 😲 
Found this when digging through some wasm-objdump output and noticing **unnamed functions** having code. That shouldn't happen. Either you have a name and code, or nothing at all.
> wasm: fix offset bug

- topdown/tokens_test.go
Tests were failing on 32-bit arch due to an integer overflow.
```
GOARCH=386 go test ./topdown 
--- FAIL: TestParseTokenConstraints (0.00s)
--- FAIL: TestParseTokenConstraints/Time (0.00s)
--- FAIL: TestParseTokenConstraints/Time/if_provided,_is_parsed_properly (0.00s)
tokens_test.go:123: parseTokenConstraints: token time constraint: must not be negative
--- FAIL: TestParseTokenConstraints/Time/unset,_defaults_to_wallclock (0.00s)
tokens_test.go:134: parseTokenConstraints: token time constraint: must not be negative
FAIL
FAIL    github.com/open-policy-agent/opa/topdown        5.510s
FAIL
```
The unix nano time (`int64`) was converted to an `int`, which caused an overflow on 32-bit architectures.
> tests: fix failing test on 32-bit arch

- Makefile
- test/e2e/logs/console/console_decision_logger_benchmark_test.go
- test/e2e/logs/console/console_decision_logger_test.go
- test/e2e/logs/remote/remote_decision_logger_benchmark_test.go
If you want to run them, use `make perf-noisy`.
> test/e2e: stop running benchmarks that output decision logs in GHA

- compile/compile.go
- compile/compile_test.go
We now discern:
1. If there's no Wasm ABI version array at all in the capabilities of
the `opa` binary used to build a Wasm bundle.
2. If the provided capabilities.json contains EMPTY Wasm ABI versions
array.
(1.) would happen if the binary itself has no support for running the
Wasm module, i.e. it was built without the `opa_wasm` go tag. Anyways,
such a binary is perfactly capable of emitting wasm code, so that's
what we'll allow it to do (with this change).
(2.) still gives you the option to disable building wasm bundles via
capabilities.json, but it's an edge case: usually, you'd use it to
control the ABI versions you're building for. If you want, however,
you can still say "none" by providing an empty array.
----
Fixes #3270.
> compile/wasm: fix capabilities issue with `opa build -t wasm`

- plugins/plugins.go
- plugins/plugins_test.go
- plugins/rest/rest.go
- sdk/logging.go
- sdk/logging_test.go
When using OPA as a library in a Golang project that also uses logrus for logging, the log messages generated from OPA might be missing context or are hard to understand for users. 
This PR adds the ability to configure a plugin manager's logger using an option and also changes the `WithFields`method of `sdk.logger` to inherit the fields of the base logger. This allows to pre-define common fields on the log output that get propagated to log messages further down.
> Allow configuring logger + its fields in library usage

- topdown/http_test.go
- topdown/topdown_test.go
One of the steps to determine if a cached response is
fresh or not is to compute the difference between the wall clock
time set on the builtin context and the value of the Date
response header.
If the Date response header is not explicitly set, the
Go test server sets it to time.Now(). The test runner
also sets the time on the query that runs the test to
the current time (ie. time.Now()).
Ideally the time at which OPA checks if a cached response is
fresh or not should be greater than response orignation time
(ie. Date header value) set by the server. But the manner in
which the tests are setup this is not the case resulting in
incorrectly marking a fresh cached response as stale and thereby
causing test failures. This change updates the test runner such
that the time on the topdown.Query …
> topdown: fix http.send flaky tests

- internal/compiler/wasm/wasm.go
With wasmtime(-go) 0.24.0, we should be in the clear here.
This reverts commit 038da308f7ce9e5df95aca61dbc4419663847445.
----
Ran `make wasm-sdk-e2e-test` and `make go-test` on this macbook, it has passed just fine. ✔️
> Revert "wasm: Do not emit unreachable instructions after opa_abort calls"

- test/wasm/assets/018_builtins.yaml
- wasm/src/glob-compiler.cc
- wasm/src/glob-parser.cc
- wasm/src/glob.cc
- wasm/tests/test-glob.cc
- wasm/tests/test.h
Also use `opa_value_iter` in `opa_glob_match`, add test cases.
Fixes #3294.
> wasm/glob.match: escape default delimiter

- config/config.go
- config/config_test.go
- docs/content/rest-api.md
- plugins/discovery/discovery_test.go
- server/server.go
- server/server_test.go
This commit adds a new API endpoint to fetch OPA's
active configuration. When the discovery feature is enabled,
this API can be used to fetch the discovered configuration
in the last evaluated discovery bundle.
Fixes: #2020
> config: Add API to expose OPA's active config

- docs/content/envoy-tutorial-standalone-envoy.md
This commit removes the deprecated query field of the
OPA-Envoy config in the Envoy tutorial and replaces it
with the path field.
> docs: Update OPA-Envoy plugin config to use path field

- build/run-pigeon.sh
We don't use this anymore. (`git grep pigeon` yields nothing.)
> build: remove run-pigeon.sh

- docs/content/rest-api.md
- server/server.go
- server/server_test.go
- server/types/types.go
This commit just tweaks the new v1/config response to include a
wrapper that nests the config object under a "result" key in the
response. This makes GET v1/config consistent with other OPA APIs and
future-proofs the API to some extent (e.g., if we need to include
additional fields in the future, they do not necessarily have to be
included in the config object itself.)
> server: Add wrapper for GET v1/config response

- topdown/eval.go
- topdown/topdown_partial_test.go
The package path was being mutated after support modules were
created. If a single reference generated multiple support modules,
then the resulting support modules would have the wrong package
path. This only happens when partial namespacing is disabled because
the normal code path implicitly copies the refs when injecting the
namespace into th the package path.
Fixes #3302
> topdown: Copy package path and save term when namespacing off

- topdown/parse_bytes.go
- topdown/parse_bytes_test.go
Often users will provide amounts for something like memory as a fraction
of the most human-readable unit e.g. 1.5KB rather than 1500B. Allow
parse_bytes to support byte amounts provided this way, rounding down to
the nearest integer when something like 1.1KiB would leave a fractional
byte.
Fixes #3297
NB: I've not changed any docs since they are not specific about previously requiring an integer and I think the current wording is valid for floats too
> topdown: Let units.parse_bytes support float values

- Makefile
The `make image` target was relying on the build-docker target to
build the binary that goes into docker image. The problem is that
build-docker runs on the host and can therefore produce a binary for
the wrong environment.
This change just updates the image target to rely on
ci-go-build-docker instead which runs go build inside of a docker
container and ensures the environment is correct.
Since the user is already trying to build a docker image, it seems
reasonable to require docker to build the binary (normally we try to
avoid this dependency for plain binary builds.)
> ci: Use the ci container to build binary for make image

- go.mod
- go.sum
Similar to: https://github.com/open-policy-agent/conftest/pull/513
Relates to:
- https://nvd.nist.gov/vuln/detail/CVE-2021-3121
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
Verified with [nancy](https://github.com/sonatype-nexus-community/nancy)
> Update gogo/protobuf to v1.3.2

- internal/planner/planner.go
- internal/planner/varstack_test.go
- test/cases/testdata/comprehensions/test-comprehensions-and-vars.yaml
Before, variables introduced in a comprehension, like the `x` in
{ x | xs[x] }
would have been recorded in `p.vars`, and have an effect outside of
the scope of this comprehension, leading to wrong plans.
Now, we'll duplicate whatever variables we've known before, and
reset to that state after planning the comprehensions.
Fixes #3325.
> planner: forget variables from comprehensions

- internal/wasm/sdk/examples/basic/main.go
- internal/wasm/sdk/internal/wasm/pool.go
- internal/wasm/sdk/internal/wasm/pool_test.go
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/loader/file/loader.go
- internal/wasm/sdk/opa/loader/file/loader_test.go
- internal/wasm/sdk/opa/loader/http/loader.go
- internal/wasm/sdk/opa/loader/http/loader_test.go
- internal/wasm/sdk/opa/opa.go
- internal/wasm/sdk/opa/opa_test.go
- plugins/plugins.go
- rego/rego_wasmtarget_test.go
- resolver/wasm/nop.go
- resolver/wasm/wasm.go
- server/server.go
- topdown/http.go
- topdown/http_slow_test.go
Now, when an interrupt happens, we'll clean up after ourselves: we keep calling
a cheap function to ensure that the trap has been trapped on.
To get there, we'll move the "defer-recover" further down the call stack.
👉 Also, this changes the cancellation error returned by the topdown builtin. It no
longer is a builtinError with a message indicating that the context was cancelled
(or its deadline reached), but return a CancelErr, the same thing that happens via
the other cancellation mechanisms involved topdown's Cancel (like in cidr.expand).
Compared with master, this isn't worse:
name                       old time/op    new time/op    delta
RESTAuthzForbidAuthn-16       542µs ±15%     525µs ±12%    ~     (p=0.841 n=5+5)
RESTAuthzForbidPath-16        818µs ± 2%     827µs ± 2%    ~ …
> ci: unflake "go perf"

- ast/check.go
- ast/check_test.go
- ast/compile.go
- ast/compile_test.go
- ast/env.go
- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- bundle/bundle.go
- cmd/eval.go
- cmd/eval_test.go
- cmd/flags.go
- docs/content/schemas.md
- go.mod
- go.sum
- loader/loader.go
- rego/rego.go
- rego/rego_test.go
- types/types.go
New support to upload a directory of JSON schema file(s) via "opa eval --schema". Directory can contain schema file(s) for policy input document(s), and schema file(s) for contextual data document(s). These schema files are used then to improve static type checking and to get more precise error reports as you develop Rego code
Also, there is new support for adding annotations on Rules to specify the schemas to be used specifically for type checking the expressions within the scope of that Rule. It helps address issues with schema overloading, and provides even more precise type error reports for a Rego developer.
If your directory contains an `default-input-schema.json` file for the input's schema, that will become the **default** input schema for all rules. This can be overriden with …
> Adding rule annotations with schema type checking support for OPA

- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
This change adds the count of the decision log events that
were dropped when the rate limit was exceeded to the status
plugin's metrics provider. These metrics are part of the periodic
status update and hence should allow control planes to monitor the
number of dropped log events.
> plugins: Include log drop count in the status plugin's metrics

- cmd/refactor.go
- cmd/refactor_test.go
- refactor/refactor.go
- refactor/refactor_test.go
This commit adds a new command to OPA to implement refactoring
operations over Rego modules. To start a new sub-command has been
added to support renaming package paths and other references.
Fixes: #3290
> cmd: Add tooling to support package renaming

- plugins/discovery/discovery_test.go
The test that checks for log drops was utilizing the
test server and would fail sporadically from an unmarshalling
error in the test server.
This change updates the test to not use the test server as
it's not required to meet the goal of the test.
Flaky test run -> https://github.com/open-policy-agent/opa/pull/3358/checks?check_run_id=2296217448#step:3:316  
> plugins/discovery: Fix log drop checking flaky test

- download/download.go
- download/download_test.go
Though the HTTP standard says it should be there, a _lot_ of the HTTP server implementations out there ignores sending the provided ETag back in the 304 response. No wonder given how it would just be echoing what that client just provided.
This fixed bundle caching for at least:
* Nginx
* Azure
* Rego playground (nginx based)
..and probably many more.
Fixes #3361
> bundle: Do not rely on ETag in 304 server response headers

- docs/content/configuration.md
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
As part of TLS configuration for bundle downloads, we currently have `cert` , `private_key` and `private_key_passphrase` fields for TLS authentication, no option available to specify CA file
Hence added an option `ca_cert` to specify CA file 
Additionally, a separate option `system_ca_required` to determine whether or not to bundle the system certificate pool with the desired CA file
Fixes: #1968
Signed-off-by: Arshad Saquib <arshad.saquib@styra.com>
> Add TLS option to specify CA file

- cmd/eval.go
Updating `eval` docs to line up with example in bundle docs. The tree structure example included a file called `baz_test.rego`, however the comments below it referred to it as `baz.rego`
> Fix typo in bundle example

- docs/content/configuration.md
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
This is required by the Azure Identity OAuth2 implementation when the client credentials JWT flow is used.
Fixes #3372
> Add thumbprint config option for x5t JWT header

- .gitignore
- bundle/bundle.go
- bundle/bundle_test.go
- bundle/keys.go
- bundle/sign.go
- bundle/sign_test.go
- bundle/verify.go
- bundle/verify_test.go
- cmd/build.go
- cmd/flags.go
- cmd/sign.go
- docs/content/management.md
It is now possible to register a custom implementation of the sign and verify functions.  We use this to implement Bundle Verification using AWS KMS.
Related to #2757 (this is a prerequisite).
> Refactored bundle sign/verify to use interface

- refactor/refactor.go
The policy ref was being compared to a source
ref by using the its string representation. This check is
not required as the prefix check on the ref that follows will
accomplish this w/o the need to convert ref to a string.
> refactor: Remove unnecessary reference check

- server/server.go
- server/server_test.go
This fixes indentation if pretty query parameter is set for v0 API
No major feature modification or changes in method, hence made no change to unit test 
Fixes: #3332
Signed-off-by: Arshad Saquib <arshad.saquib@styra.com>
> Fix pretty query parameter for v0 API

- docs/content/configuration.md
- docs/content/management.md
- plugins/discovery/discovery.go
- plugins/logs/plugin_test.go
- plugins/status/plugin.go
- plugins/status/plugin_test.go
Added support for plugins in status plugin, similar to the pattern
employed in the decision logs plugin. By setting `status.plugin`
in configuration, you can override how the status plugin sends status
updates.
Related to #3047
> plugins/status: add plugin support

- docs/README.md
- docs/website/layouts/_default/baseof.html
- docs/website/layouts/partials/docs/dashboard-panel.html
This might not be the most efficient or idiomatic way to do it, but
I think it works.
⚠️ Doesn't do in-page anchors, so selecting a different version when on
page /docs/v0.26.0/policy-performance/#benchmarking-queries will get
you to /docs/<other>/policy-performance/ only.
⚠️ Doesn't indicate where the link brings you -- this a UX faux pas, I think, but where possible, I'd think we now meet expectations...
Fixes #3023 to some extend. A little less annoying now, I hope.
> website: link to same page (if possible) from version picker

- refactor/refactor.go
- refactor/refactor_test.go
This commit checks if the constant prefix of the ref is non-empty
before checking if it's a prefix of a source
ref. This is seen for example, when the ref represents a function call.
> refactor: Check for empty constant prefix while renaming ref

- runtime/runtime.go
- runtime/runtime_test.go
This fix gives a Error msg when you start the opa runtime server with authentication as TOKEN and authorization OFF
Fixes #3380
> Authentication option doesn't take effect if there's no authorization policy 

- ast/check.go
- ast/check_test.go
- ast/compare.go
- ast/compare_test.go
- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- ast/schema.go
- ast/transform.go
- ast/transform_test.go
- ast/visit.go
- ast/visit_test.go
- cmd/parse.go
- docs/content/schemas.md
- loader/loader.go
- loader/loader_test.go
This PR adds new annotation scopes (`document`, `package`, and `subpackages`) as well as inline schema definitions. I've updated the schema documentation to include a section describing the new scopes.
> Expand schema annotation support

- cmd/flags.go
- cmd/test.go
> cmd/test: default timeout 30s when benchmarking

- .github/workflows/pull-request.yaml
- Makefile
Also adds a smoke test so this can't happen again. 🚭
> build: ensure the binaries in docker images are executable

- docs/content/envoy-primer.md
- docs/content/envoy-tutorial-standalone-envoy.md
The path matching in the tutorial is wrong. For example:
> glob.match("/people*", [], "/peoplexyz")
true
> glob.match("/people*", [], "/peoplexxxx/1234")
true
This patch updates the examples so that the matches don't return false positives.
> docs: Update path matching in the Envoy tutorial

- wasm/Dockerfile
- wasm/Makefile
- wasm/src/libc++/minimal.cc
There's more changes to the wasm files than in the last bump, 11.0.0 -> 11.1.0; so, it's not entirely straightforward to say what exactly has changed.
That said, our linking and optimization machinery is still intact, and the benchmarks we have don't indicate anything catastrophic:
```
name                                    old time/op  new time/op  delta
WASMArrayIteration/10-16                 423µs ± 5%   405µs ± 4%    ~     (p=0.095 n=5+5)
WASMArrayIteration/100-16                441µs ± 8%   414µs ± 4%  -5.98%  (p=0.032 n=5+5)
WASMArrayIteration/1000-16               572µs ± 2%   559µs ± 2%    ~     (p=0.056 n=5+5)
WASMArrayIteration/10000-16             2.18ms ± 1%  2.35ms ± 6%  +8.11%  (p=0.008 n=5+5)
WASMSetIteration/10-16                   443µs ± 3%   421µs ± 3%  -4.98% …
```
> wasm: use llvm-12 toolchain, bump wabt/binaryen

- download/config.go
- download/config_test.go
- download/download.go
- download/download_test.go
- plugins/rest/rest.go
Earlier the downloader package only supported the http
short polling technique where the client sends periodic
requests to the server to fetch bundles. A drawback of this
method is that a low polling frequency could add unnecessary
burden on the server and network.
This commit adds support for http long polling which helps
to minimize server/network resource usage and also reduces
the delay in delivery of updates to the client.
> download: Add support for http long polling

- cmd/fmt.go
- cmd/fmt_test.go
Running fmt during CI/CD is a common practice to ensure
files being merged are properly formatted. While this
can be accomplished with shell commands the OPA docker
image doesn't ship with a shell so adding this flag to
return a non zero error code allows the docker image to
be used in CI/CD.
Fixes: #2149
Signed-off-by: Joshua Shanks <jjshanks@gmail.com>
> cmd/fmt: Add flag to return non zero exit code on diff

- compile/compile_test.go
- rego/rego_test.go
- topdown/query.go
Before this fix, an optimized bundle would get
non-deterministic order of the support rules.
One example use case where it is necessary for the optimized
bundle to be deterministic is when a hash of the bundle is
used for version tag.
Fixes: #3453
Signed-off-by: Andre Håland <andre.haland@gmail.com>
> Deterministic order of rules for optimized bundles

- runtime/runtime.go
- server/server_test.go
- Allows extending the REST API by creating a custom runtime object ( no separate port required)
- Partly solves https://github.com/open-policy-agent/opa/issues/2777
All changes to public APIs **must** be accompanied with
docs. Examples of public APIs include built-in functions,
config fields, and of course, exported Go types/functions/constants/etc.
Not sure how/whether to document a change of `runtime.Params`
> Add Router to runtime.Params

- .github/workflows/codeql-analysis.yml
- cmd/fmt_test.go
I had proposed that in a PR review... not thinking that it meant
we couldn't run tests using Go 1.15. My assumption that using
go 1.15
in go.mod would protect us from that was wrong, apparently.
> fix codeql go version; use ioutil.Discard.

- plugins/discovery/discovery_test.go
This one wasn't detected reliably, it sometimes appeared and
sometimes did not. Running the test in a loop in a low-resource
docker container make it come out.
> plugins/discovery: fix race in test

- internal/gojsonschema/README.md
- internal/gojsonschema/draft.go
- internal/gojsonschema/schema.go
- internal/gojsonschema/schemaPool.go
- internal/gojsonschema/schema_test.go
- internal/gojsonschema/utils.go
- internal/gojsonschema/validation.go
While Go has had safe type assertions since the version 1, their use did not become standardized until around Go 1.3 - some time after the library we copied was written in 2013. This means the original author relied on a now-defunct (but then reasonable) practice of defining a convenience method for type assertions, `isKind`.
Unfortunately for us, checking for types using the reflect package in this way is both extremely inefficient and unsafe. In refactoring this library I've fixed several bugs which could have caused panics or an incorrect parse. I'll comment below cases where the right fix was ambiguous.
Additionally, the original code used a helper method for checking if a value existed in a map, and then extracted the value if it existed. As written, this retrieves the value from the …
> Remove usage of isKind() from internal/gojsonschema

- ast/compile.go
- ast/schema_test.go
- internal/gojsonschema/schema.go
- internal/gojsonschema/subSchema.go
- internal/gojsonschema/validation.go
This commit fixes the conversion to treat array.items schema as the
dynamic element type in arrays as opposed to the static element
type. If array.items is defined as an object then it applies to ALL
elements in the array. On the other hand, if array.items is defined as
an array then it applies pairwise to the elements in the array.
In order to fix this, we have to expose a new field from the schema library.
> ast: Treat array.items as dynamic element type

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
This commit changes the default of `tls_use_system_certs`
parameter for `http.send` from `false` to `true`
Fixes #2271
Signed-off-by: Olamide Omolola <omololaolamidex@gmail.com>
Fixup to commit 5c213e5
Signed-off-by: Olamide Omolola <omololaolamidex@gmail.com>
> topdown: change the tls_use_system_certs default to true

- go.mod
- go.sum
- vendor/github.com/bytecodealliance/wasmtime-go/README.md
- vendor/modules.txt
Upgrade `github.com/bytecodealliance/wasmtime-go` following wasmtime's security advisory https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-hpqh-2wqx-7qp5
> Upgrade github.com/bytecodealliance/wasmtime-go

- ast/compile.go
- compile/compile.go
This commit tweaks the --debug output format to be slightly more
readable. The comprehension indexing messages now have a prefix to
make them more discernable and the optimizer output is now aggregated
so that it's more concise and clear what parameters are being passed
to partial evaluation.
> ast, compile: Update opa build --debug output

- test/cases/testdata/functions/test-functions-unused-arg.yaml
- topdown/eval.go
...to avoid a panic at run time.
Fixes #3501.
> topdown: move arg count below ir.Empty()

- internal/wasm/sdk/test/e2e/exceptions.yaml
- test/cases/testdata/functions/test-functions-default.yaml
- test/cases/testdata/functions/test-functions-unused-arg.yaml
- topdown/eval.go
They aren't supported, but they can lead to a situation where
ir.Empty() is false, but ir.Rules still has length 0.
> topdown: deal with default functions

- bundle/filefs.go
- bundle/filefs_test.go
To make it possible to create a DirectoryLoader based on the fs.FS interface.
This interface requires go version 1.16 or above.
Fixes: #3489
Signed-off-by: Simon Gottschlag <simon.gottschlag@xenit.se>
> bundle: Implement a DirectoryLoader for fs.FS

- .github/workflows/post-merge.yaml
- .github/workflows/post-tag.yaml
- .github/workflows/pull-request.yaml
- Dockerfile
- Makefile
- internal/rego/opa/nop.go
> build: add static (wasm-disabled) linux build

- Makefile
left-over of #3511, but not to block #3513.
> build: publish edge binaries for linux-static

- cmd/fmt.go
The help text for opa fmt stated that -e could
be used as shorthand. This is not correct.
This commit changed to the correct flag --fail.
Fixes: #3518
Signed-off-by: Andre Håland <andre.haland@gmail.com>
> cmd/fmt: fix incorrect help text

- Makefile
This way `make` does not bomb out if docker not installed/running. This
is similar to what we do for the wasm library build.
> Update check target to test if docker is running

- download/download.go
- download/download_test.go
- plugins/bundle/plugin.go
Earlier the client would reset the etag on the downloader
in case of downloader errors and bundle activation failures.
The drawback of this approach is that OPA could potentially download
the same version of a bundle multiple times thereby unnecessarily
adding to network traffic.
This change resolves the issue by allowing the client to set
the etag on the downloader to the last successful activation
etag value in case of failures.
> Update downloader's Etag to last successful act value

- topdown/eval.go
- topdown/save.go
- topdown/topdown_partial_test.go
When shallow inlining is configured or inlining is disabled on specific
paths, we'll now save the PE'ed function into support and call it if
there are unknowns in either the function definiion (transitively) or
the call-site arguments.
Fixes #3463
Co-authored-by: Stephan Renatus <stephan.renatus@gmail.com>
Co-authored-by: Torin Sandall <torinsandall@gmail.com>
> topdown: Fix inlining controls for functions

- server/server.go
- server/server_test.go
A bundle without a manifest, or a manifest with no roots declared, or a manifest with a `""` declared as one of the roots.. should all be considered owners of all paths.
Caused by change in PR [#3033](https://github.com/open-policy-agent/opa/pull/3033).
Fixes #3521
> Bugfix: treat missing/empty roots as owning all paths

- docs/content/oauth-oidc.md
docs/content/oauth-oidc.md:
The concat command to assemble the url for metadata discovery was not correctly formatted. Missing [] and ending ).
This is my commit message
Signed-off-by: Jonas Iggbom <jonas@curity.io>
> docs/content/oauth-oidc.md: Fixed concat command in metadata discovery method

- topdown/cache/cache.go
- topdown/cache/cache_test.go
Previously while inserting an item in the cache, there was no
check to see if the item's size exceeded the cache limit. This
would result in that item being added to cache which is incorrect
behavior.This change adds an item size check during a cache insert.
> topdown/cache: Check cache value size during insert operation

- docs/content/rest-api.md
- server/server.go
- server/server_test.go
- server/types/types.go
This avoids exposing a "hidden" API on the GET / handler that lets users run Rego queries w/ URL query params.
> Refactor the index.html page to use the v1/query API

- topdown/eval.go
- topdown/topdown_partial_test.go
The PE unknown check in the evalTree phase while finishing a ref was
incorrectly checking for unknowns on the unplugged ref. This mean that
if a ref element was unknown, that the expression would get saved and
evaluation would be skipped even though the ref key was
enumerated. This resulted in more results being generated by PE than
necessary and lead to expressions that could not be indexed.
Fixes #3552
> topdown: Fix PE unknown check to avoid saving unnecessarily

- ast/compile.go
- ast/compile_test.go
- ast/index.go
- ast/index_test.go
- ast/policy.go
- ast/term.go
- topdown/eval.go
- topdown/topdown_bench_test.go
This commit improves the rule indexer to understand function
args. Function arguments are stored via their argument index, to allow
for different variable names (as re-written by the compiler). So, for
f(x, y, z) = { x = 10; y = 12; z > 1 }
the indexer will store the rule at
- args[0]: scalar(10) args[1]: scalar(12)
The callsite-local function arguments are handed off to evalResolver,
which enhances eval's Resolve() method.
Benchmark results:
name                           old time/op    new time/op    delta
FunctionArgumentIndex/10-16      23.2µs ± 6%     6.1µs ± 1%  -73.75%  (p=0.008 n=5+5)
FunctionArgumentIndex/100-16      187µs ± 2%       6µs ± 1%  -96.70%  (p=0.008 n=5+5)
FunctionArgumentIndex/1000-16    2.23ms ± 3%    0.01ms ± 2%  -99.68%  (p=0.008 n=5+5)
name …
> ast, topdown: Improve indexer to understand function args

- topdown/http_test.go
The affected test case checks caching behavior by
making http requests to the test server. It expects
the test server response body to be the same. However
the Date header could be different between calls.
The test case uses the unification operator to assign a
variable to the result of http.send. Then the next expression
in the rule body performs a comparison which would intermittently
fail due to the changing value of the Date header in the
http.send response.
This change updates the test to use diffferent variables to asssign
the result of http.send and thus avoid the comparison.
Flaky test run -> https://github.com/open-policy-agent/opa/runs/2794529947?check_suite_focus=true
> topdown: Fix http send flaky test

- types/types.go
- types/types_bench_test.go
The static properties are stored in sorted order so perform a binary
search to lookup instead of scanning all keys.
> types: Use binary search for static property lookup

- .github/workflows/pull-request.yaml
- Makefile
With this change, we'll execute our binaries on macos, windows, and linux (-static); with wasm enabled where possible.
This closes a gap in CI we've had so far: no automated testing of binaries on windows and macos. It doesn't add too much over the docker image smoke tests we have for the different linux variants, but better safe than sorry (again) 😅
> ci: add binary smoke tests (windows, macos)

- internal/wasm/sdk/opa/opa_test.go
- wasm/src/json.c
- wasm/src/lib/stdio.c
- wasm/src/lib/stdlib.c
- wasm/src/lib/stdlib.h
- wasm/src/malloc.c
- wasm/src/std.h
- wasm/src/undefined.symbols
It's become apparent that a call to opa_abort in opa_agg_count did NOT
stop execution. Failures in bad input there haven't been thoroughly tested.
Comparing to the calls to opa_abort that happen in compiler-emitted code
(as opposed to calls in the C portion of our wasm code base), we find that
they are always emitting `unreachable` after the call to opa_abort.
As it turns out, doing the same thing in the C parts fixes the problem.
It thus seems like this is somehow related to changes in wasmtime's
cranelift (or its backend). It's never wrong to give the compiler some
more information that we can readily share, so let's put some `unreachable`
into the their proper places.
To avoid touching the entire code base of the C parts, we're defining a
function called `opa_abort(msg)` that'll call …
> wasm: emit unreachable instruction after opa_abort()

- internal/wasm/sdk/opa/opa_test.go
- test/cases/testdata/aggregates/test-aggregates-bad-utf8-runes.yaml
- test/cases/testdata/strings/test-strings-indexof-unicode.yaml
- topdown/strings.go
- wasm/src/aggregates.c
- wasm/src/re2/util/utf.h
Previously, we'd bail out when the string count() is given contained
anything that isn't a valid utf-8 rune. Now, we'll have it count the
invalid chars -- they're replaced by chartorune() in the same manner
as happens when passing casting the string to []rune in golang:
package main
import (
"encoding/base64"
"fmt"
)
func main() {
sample, _ := base64.StdEncoding.DecodeString("2E84ZuPUd7zfvCZSNEchVpDEIj6PL7JfLpIqyxVG16k=")
fmt.Printf("% x\n%x\n%d, %d\n", sample, []rune(string(sample)), len(sample), len([]rune(string(sample))))
}
This yields:
d8 4f 38 66 e3 d4 77 bc df bc 26 52 34 47 21 56 90 c4 22 3e 8f 2f b2 5f 2e 92 2a cb 15 46 d7 a9
[fffd 4f 38 66 fffd fffd 77 fffd 7fc 26 52 34 47 21 56 fffd fffd 22 3e fffd 2f fffd 5f 2e fffd 2a fffd 15 46 5e9]
32, 30
Where fffd is the replacement char …
> wasm+topdown: misc utf-8 related issues

- docs/content/envoy-tutorial-istio.md
- docs/content/envoy-tutorial-standalone-envoy.md
- docs/content/extensions.md
- docs/content/http-api-authorization.md
- docs/content/kafka-authorization.md
- docs/content/management-bundles.md
- docs/content/ssh-and-sudo-authorization.md
These aren't required, since github resolves the `master` links properly.
Anyways, let's clean these up.
> docs: update opa-envoy-plugin and contrib default branch

- docs/content/configuration.md
- plugins/rest/rest.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
This change allows users to specify a certificate for the services
that implement the bundle, status etc. APIs. This cert will be
used to create the root CA pool.
Fixes: #1954
> plugins/rest: Add option to specify CA for remote services

- docs/content/extensions.md
I think this helps people who are not as familiar with go to get more expected results. The is issue is that because input and result are interfaces when event is printed to stdout without the map being marshalled to JSON both input and result are printed as memory pointers. This is confusing to someone less familiar with go as they may believe that their input is not present in the decision log. By adding Marshal the stdout will now be standard JSON which will then have result and input with the string values.
Signed-off-by: John Snow <john@styra.com>
> Marshal the decision log in docs so Input and Result are not pointers

- .golangci.yaml
- internal/compiler/wasm/wasm.go
1. disable goconst
2. remove some unused constants, selectively no-lint others, in internal/compiler/wasm.
> misc: disable goconst linter, remove nolint in internal/compiler

- bundle/bundle.go
- bundle/bundle_test.go
- cmd/build.go
- cmd/build_test.go
- cmd/eval.go
- cmd/flags.go
The first commit is just cleanup. The second commit implements the fix.
> Do not write .manifest into bundles unnecessarily

- ast/term.go
- ast/term_test.go
This commit improves the interface conversion function to deal with
non-native types (mostly structs but only cases like []string which
are not manually covered.)
> ast: Improve InterfaceToValue to handle non-native types

- internal/gojsonschema/testdata/draft7/optional/format/time.json
Replace the time `01:01:01,1111` by `14:30`, which is a ISO 8601 valid time, but not a RFC3339 "full time", and is rejected as such by the `TimeFormatChecker`.
Fixes #3589
> Fixes JSON schema test failing with Go 1.17 rc

- .github/dependabot.yml
I suppose we could use it for more than just this dependency, but it's
a start. Commonly, I've been watching this project, but it would be nice
if the bot did it instead.
> ci: enable dependabot for wasmtime-go

- cmd/run.go
- runtime/runtime.go
- server/server.go
- test/e2e/tls/tls_test.go
Opa server now supports minimum TLS version. Since TLS 1.0 and 1.1 are deprecated, default minimum TLS version for opa server is TLS 1.2 . If someone wants to restrict opa to start with a specific minimum tls version, they can specify it using cmd line parameter --min-tls-version. TLS versions supported are 1.0, 1.1, 1.2, 1.3.
fixes #3226
Signed-off-by: Amruta Kale <amruta.kale@styra.com>
> Support for minimum TLS version for opa server

- CHANGELOG.md
- capabilities/v0.30.0.json
- version/version.go
I think the oldest issue resolved in this release is #1954 -- Dec 2019. 👏
> Prepare v0.30.0 release

- internal/rego/opa/nop.go
The typo was actually reported by @johanneslarsson in a commit comment: https://github.com/open-policy-agent/opa/commit/f8ef59c1845f373008865e024147800164385e43#r51520552
> Fix typo in non-wasm error message

- docs/content/policy-reference.md
- topdown/http.go
...since it's not supported by the golang runtime.
Fixes #3612.
> http.send: ignore tls_use_system_certs on windows

- internal/rego/opa/opa.go
- internal/rego/opa/options.go
- internal/wasm/sdk/internal/wasm/bindings.go
- internal/wasm/sdk/internal/wasm/pool_test.go
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/opa.go
- rego/rego.go
- rego/rego_test.go
- rego/rego_wasmtarget_test.go
- topdown/uuid.go
There random seed to be used with the host-provided builtin uuid.rfc4122
was missing from the BuiltinContext that's created in the dispatcher. It
hadn't been thread through from rego to the vm call.
The unit tests for the builtin now run against both targets.
Also some style adjustments to the builtin code for uuid.rfc4122.
Fixes #3622.
> wasm/sdk: handle random seed needed by 'uuid.rfc4122()'

- rego/rego.go
opa.Eval() expects an input of type *interface{}; and for evaluations targetting
the wasm engine, we had been parsing the rawInput (*interface{}) into *ast.Value,
only to run ast.JSON() on it (going back to *interface{}) before passing it off
to the Wasm SDK.
> rego: don't parse inputs for wasm target

- topdown/eval.go
- topdown/topdown_partial_test.go
Before, all the available bindings had been added to the comprehension in
package pkg
p[x] { q[x] }
q[x] {
y := {1 | input} # <---
x := "foo"
}
So after partial eval, the support rule was
p["foo"] {
__local0__2 = {1 |
input
__local1__2 = x12
}
}
Now, only variables that are used in the comprehension in question are
added. The partial eval result becomes
p["foo"] {
__local0__2 = {1 | input}
}
An extra round of the process was added when both lhs and rhs are
comprehensions.
Fixes #3557.
> topdown: only amend comprehensions with used bindings

- docs/content/configuration.md
- docs/content/management-bundles.md
- docs/content/management-decision-logs.md
- docs/content/management-status.md
Since v0.26.0 the deprecated single bundle config section has
generated a warning on startup. This commit just removes stale
mentions of the section from the docs. Also, fix the deprecated field
table in the discovery config section.
> docs: Remove deprecated fields from management pages

- ast/compile.go
- ast/compile_test.go
The compiler assumes that queries are non-empty, however, if the
parser is fed only whitespace and comments then the parsed query will
be empty. Since the compiler makes this assumption and many callers
will make a similar assumption, just reject empty queries at the
beginning.
This issue is unlikely to affect most users unless they send arbitrary
text selections into OPA (e.g., like `opa eval` does...)
Fixes #3625
> ast: Update query compiler to reject empty queries

- topdown/numbers.go
This commit just puts an error check in place to the panic from the
stdlib when rand.intn is called with an input < 1.
> topdown: Fix panic in rand.intn function

- rego/errors.go
- rego/rego.go
- rego/rego_test.go
- topdown/eval.go
Before, functions provided via arguments to `rego.New()` hadn't been
able to halt the topdown evaluation.
Now, they do, if they return a `*rego.HaltError`.
Fixes #3534.
> rego+topdown: allow custom builtins via rego pkg to halt

- internal/cmd/genopawasm/main.go
- internal/wasm/sdk/opa/opa_bench_test.go
The result will always be the same, and on multiple calls to
rego.New() with the wasm target, repeating this work can be
avoided.
Once Go 1.17 is out and we can do something incompatible with
1.15, we can [switch to using the go:embed directive instead.](https://github.com/srenatus/opa/tree/sr/go1.16/use-go-embed-directive-for-wasm-base)
> genopawasm: only unpack wasm and callgraph bytes once

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/builtins.go
- topdown/numbers.go
- topdown/numbers_test.go
This commit combines a few improvements to the rand.intn
implementation:
* Zero and negative integers do not cause an error. In most cases, we
try to make built-in functions return sensible results (rather than
halting evaluation or being undefined.) In this case, it's easy
enough to handle zero and negative integers.
* Use the built-in context seed to generate the source for the rand
call. This helps ensure that rand.intn calls can be
reproduced.
* Use dedicated cache key type instead of overloading uuidCachingKey.
* Add test coverage for caching, partial eval, etc.
> topdown: Improve rand.intn implementation

- ast/term.go
- topdown/eval.go
- topdown/eval_test.go
- topdown/topdown_partial_test.go
- topdown/trace_test.go
We can either cache individual elements (`data.foo.p["bar"]`), or the
full extent of a partial set/object. A cached full extent of the partial
would be used when evaluating individual elements of the partial.
If the first encounter with a partial set/object has to materialize the
full extent with a variable key, like `data.foo.p[x]`, then we cache the
fully-evaluated result for `data.foo.p`.
Fixes #822.
> topdown: memoize partial set results

- ast/parser_ext.go
- ast/parser_test.go
The specific combination where the first character is a tab, and the rest
are falling under `unicode.IsSpace()` would lead to strings.Repeat being
fed an empty count (to determine the position of the error pointer).
Displaying different "spaces" in a discernable way isn't solved here,
but I think it's also an edge case we can accept as-is.
> ast: fix panic in ParseModule() with all space chars, starting with tab

- cmd/bench.go
- cmd/bench_test.go
- cmd/eval.go
- docs/content/policy-performance.md
- internal/presentation/presentation.go
- metrics/metrics.go
- profiler/profiler.go
`opa eval --count=# --profile` will now evaluate the query # times,
and display aggregated results for metrics and the expression-time
profile.
Before, `opa eval --profile` would yield output like this (JSON):
"metrics": {
"timer_rego_external_resolve_ns": 233,
"timer_rego_load_files_ns": 138866,
"timer_rego_module_compile_ns": 432654,
"timer_rego_module_parse_ns": 81454,
"timer_rego_query_compile_ns": 54892,
"timer_rego_query_eval_ns": 135624,
"timer_rego_query_parse_ns": 3886
},
"profile": [
{
"total_time_ns": 75705,
"num_eval": 4,
"num_redo": 2,
"location": {
"file": "t.rego",
"row": 8,
"col": 2
}
},
Now, both of these are replaced by "aggragated_" variants that
include some statistics:
"aggregated_metrics": {
"timer_rego_external_resolve_ns": {
"75%": 1618.5,
"90%": …
> opa eval: add '--count=#' flag

- cmd/eval.go
- cmd/eval_test.go
- cmd/eval_wasmtarget_test.go
- rego/rego.go
This was introduced in #3624: turns out the eval command's code only
passed parsedInput into the rego package, and that only looked at
rawInput when feeding it into the wasm engine.
The approach taken here is to make the rego package more robust: It
should do the right thing if parsedInput is provided for an eval
under the wasm target: the parsing work was already done, let's not
dischard it.
Fixes #3666.
> cmd/eval: pass parsed input into rego package for wasm target if present

- logging/logging.go
- plugins/bundle/plugin.go
- plugins/plugins.go
- plugins/plugins_test.go
- plugins/rest/aws_test.go
- plugins/rest/rest.go
- runtime/runtime.go
- sdk/options.go
This commit fixes the console loggers so that messages are emitted
regardless of the debug log level. The problem was that in 3fcc875 we
updated the plugins to use a console logger obtained from the plugin
manager as opposed to a global logger instantiated in the plugins
package--the console logger obtained from the plugin manager was
instantiated in the runtime package by calling
logging.NewStandardLogger. Unfortunately, logging.NewStandardLogger
does not create a new logger--it returns the global logrus
logger.
This commit fixes the issue by deprecating logging.NewStandardLogger
and introducing two new functions in the logging package:
* logging.Get() - this replaces the old logging.NewStandardLogger
function--this function should be called to obtain the debug logger
used throughout …
> logging: Fix console logger instantiation

- ast/check.go
- ast/compile.go
- ast/compile_test.go
- ast/schema_test.go
- docs/content/schemas.md
- internal/gojsonschema/schema.go
- internal/gojsonschema/subSchema.go
- internal/gojsonschema/validation.go
Currently OPA’s schema checker does not support features like
anyOf and allOf. This commit parses anyOf using types.Any because
anyOf can be implemented by an Or type. I also included a
short explanation in schemas.md.
Fixes: #3592 (partly)
Signed-off-by: Jing Chen <jing.10500@gmail.com>
> Support anyOf in JSON schema type checker

- test/cases/testdata/units/test-parse-bytes.yaml
- topdown/parse_bytes.go
Previous changes to the built-in function to use big.Int et al. had
been made without knowledge of these missing units. So, here they are.
Fixes #2911.
> units.parse_bytes: add E* and P* units

- docs/content/kubernetes-primer.md
Kubernetes `admission.k8s.io/v1` `AdmissionReview` objects have some
optional properties within the `status` field: `code` and
`message`. `reason` is not a valid key for API object
`admission.k8s.io/v1`.
Signed-off-by: Rafael Fernández López <rfernandezlopez@suse.com>
> docs: fix property name of Kubernetes `AdmissionReview` objects

- docs/content/kubernetes-primer.md
Bump the `AdmissionReview` API version to `v1`, and also bump the `Ingress` examples from `extensions` to `networking.k8s.io/v1`.
There are two commits each one targeting a different bump. Let me know if it's fine, or if you want me to do something else with them :)
Submitted as discussed in https://github.com/open-policy-agent/opa/pull/3698#issuecomment-891817050
/cc @srenatus
> Documentation: bump kubernetes resources versions

- docs/content/kubernetes-primer.md
Missed this bit when updating the documentation on a previous PR.
> docs: add mandatory `pathType` property to example Ingress resources

- internal/rego/opa/opa.go
- internal/rego/opa/options.go
- internal/wasm/sdk/internal/wasm/bindings.go
- internal/wasm/sdk/internal/wasm/pool_test.go
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/opa.go
- rego/rego.go
- rego/rego_test.go
- rego/rego_wasmtarget_test.go
Found when looking into #3716.
With this change, multiple calls to a wasm-backed eval that uses http.send
would re-use the results (if caching permits).
> rego: pass inter-query builtin cache to wasm sdk

- ast/compile.go
- ast/compile_test.go
- ast/schema_test.go
- docs/content/schemas.md
- internal/gojsonschema/schema.go
- internal/gojsonschema/subSchema.go
- internal/gojsonschema/validation.go
Currently OPA's schema checker does not support allOf. This commit parses allOf by merging all the subschemas into a single schema before converting to a Rego type. I also included a short explanation in schemas.md.
Related to: open-policy-agent#3592
Signed-off-by: Julia Friedman
> ast: support for allOf in JSON schema type checker

- docs/content/rest-api.md
- server/server.go
- server/server_test.go
- server/types/types.go
- Added a new querystring param to the /health route: `exclude-plugin`
- Can be specified multiple times
- Value is the name of a plugin that should be excluded from the OK
status check performed when the `plugins` qs param is specified
Fixes #3713
Will add tests once implementation is discussed and approved
> server/server: exclude-plugin param in /health route

- ast/compile.go
- ast/compile_test.go
Before, we'd only looked at the vars preceding the comprehension in the body
containing it. In the case of nested comprehensions, that would have excluded
the rule body OUTSIDE of the nested body.
Now, we'll accumulate candidates over multiple bodies -- capturing the ones
that had been missing before.
Fixes #3579.
-----------
I had a more involved fix first, but making it work with the query compiler, I realised that moving the `candiates.Copy()` does the trick, too.
The change to the existing tests also covers the issue underlying #3579, I believe.
> ast/compile: use all vars from rule body for index candidates

- cmd/bench_test.go
- docs/content/integration.md
- rego/example_test.go
- rego/rego.go
- rego/resultset.go
- rego/resultset_test.go
- test/authz/authz_bench_test.go
- test/authz/authz_test.go
Sparked by @charlieegan3's post here, https://charlieegan3.com/posts/2021-05-08-authorization-dsls-in-go/, I've been playing with a the thought of exposing some nice-to-use helper methods for dealing with a `rego.ResultSet`.
This PR adds a very simple helper:
- `(ResultSet) Allowed() bool` that's a shortcut for the common "one value, a bool, indicating allowed-ness"
> rego: add ResultSet Allowed() helper

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
> [issue #3661] http.send unix domain sockets

- internal/presentation/presentation.go
- internal/presentation/presentation_test.go
- internal/rego/opa/engine.go
- rego/errors.go
Before, errors displayed through the presentation package's prettyError()
method would never show their details. The expectation in the code was
that any error that has details would include them in its own Error()
string method.
When error types return their details using an interface, such as
type ErrorDetail interface {
Lines() []string
}
and their Error() method only return a short error message, then that
detail would never make it to the user in any of the non-JSON output
variants.
Before:
$ opa eval -t wasm '1+1'
{
"errors": [
{
"message": "engine not found",
"details": "WebAssembly runtime not supported in this build.\n----------------------------------------------------------------------------------\nPlease download an OPA binary with Wasm enabled …
> CLI: display error details for ErrorDetail errors in eval output

- docs/content/kubernetes-introduction.md
- docs/content/kubernetes-primer.md
- docs/content/kubernetes-tutorial.md
- plugins/logs/plugin_benchmark_test.go
The Kubernetes API server will reject the answer from any webhook that
does not contain the `uid` present in the request [1]. Failing to do
so will not only result in a warning, but in the answer from the
webhook being ignored, and the request rejected [2].
The `default` answer cannot be used, because the `uid` is present in
the `input.request.uid` field, and is not legal to refer to variables
on the `default` statement.
Fallback to an `else` clause to return the `uid` in all cases, when
the request is accepted, and when it's rejected.
[1] https://github.com/kubernetes/apiserver/blob/464eee4062a8f21f785e657b32b83f19d693af8d/pkg/admission/plugin/webhook/request/admissionreview.go#L52-L55
[2] https://github.com/kubernetes/apiserver/blob/464eee4062a8f21f785e657b32b83f19d693af8d/pkg/admission/ …
> documentation: always return the `uid` to the Kubernetes apiserver

- storage/inmem/inmem.go
- storage/inmem/inmem_test.go
- storage/inmem/txn.go
- storage/internal/errors/errors.go
- storage/internal/ptr/ptr.go
This commit just moves some shareable error helpers and the ptr()
function into an internal package so that we can reuse it with the
disk-based store implementation. This commit doesn't change any
existing functionality and no new public APIs are exposed.
> storage/inmem: Move shareable code into internal package

- docs/content/envoy-tutorial-standalone-envoy.md
Added cleanup instructions to return Kubernetes cluster to the state it was before doing the tutorial
> doc/envoy-standalone: added cleanup instruction

- ast/term.go
- ast/term_bench_test.go
Before had been creating slices of strings and passed them to
strings.Join. Now, we're directly making use of a strings.Builder.
The added benchmarks include comparisons to the stdlib json.Marshal
method. Only looking at the String() method's performance, we find
this benchstat output:
```
name                               old time/op    new time/op    delta
ObjectString/5/String()-16           2.47µs ± 3%    0.82µs ± 3%  -66.64%  (p=0.008 n=5+5)
ObjectString/50/String()-16          26.1µs ± 3%    10.4µs ± 3%  -60.37%  (p=0.008 n=5+5)
ObjectString/500/String()-16          307µs ± 4%     173µs ± 4%  -43.61%  (p=0.008 n=5+5)
ObjectString/5000/String()-16        3.81ms ± 4%    2.33ms ± 1%  -38.84%  (p=0.008 n=5+5)
ArrayString/5/String()-16             801ns ± 7%     456ns ± 3%  -43.09% …
```
> ast: improve String() performance for arrays, sets, objects

- ast/capabilities.go
- ast/check.go
- ast/compile.go
- ast/schema.go
- ast/schema_test.go
- ast/testdata/_definitions.json
- cmd/bench.go
- cmd/build.go
- cmd/check.go
- cmd/eval.go
- cmd/eval_test.go
- cmd/flags.go
- cmd/run.go
- docs/content/schemas.md
- internal/gojsonschema/jsonLoader.go
- internal/gojsonschema/jsonschema_test.go
- loader/loader.go
- rego/rego.go
Introducing a package-level var to gojsonschema isn't the prettiest solution,
but since we want this in an all-or-nothing way right now anyways, it does
the trick. And it's more ergonomic than adding extra parameters all over the
place.
Fixes #3746.
Also:
* move some profiling-related default params into newEvalCommandParams
* replace some errors.Wrap by fmt.Errorf in loader pkg
* remove some != nil handling where it didn't make a difference when working on the schema set
* reduces indentation in code examples in `opa eval -h` and `opa check -h` by replacing tabs by four spaces.
-----
It feels to me like the addition to capabilities is a bit dangling right now. We should perhaps tackle #3665 soon.
> add `allow_net` to capabilities, use it to disable fetching remote schemas

- bundle/file.go
bundle: The directory bundle loader currently opens all files before reading them. This causes issues on systems with a file descriptor limit lower than the number of files in the bundle. This PR implements a LazyFile type which will only open the file on first call to the Read method. The Read itself is still performed by the *os.File's Read method. In summary the LazyFile type implements a deferred io.Reader and io.Closer
Existing testing should be adequate as the mechanics are still the same. The new code only defers opening files until they need to be Read
Signed-off-by: Branden Horiuchi <Branden.Horiuchi@blackline.com>
Fixes #3777
> bundle: adding lazy file reader for bundles

- test/cases/testdata/units/test-parse-bytes.yaml
Trivial, but it had tripped up my WIP in npm-opa-wasm: https://github.com/open-policy-agent/npm-opa-wasm/runs/3584873349?check_suite_focus=true#step:11:2483
> testdata/units/test-parse-bytes.yaml: fix indentation

- bundle/keys.go
- bundle/keys_test.go
The bundle package provides a utility to extract a private key
from a file. If the private key is not included in a file, the method
first assumes it's a file name and tries to open it. Based on the size of
the key this could result in a os.PathError such as "file name too long".
This fix changes the logic of how the private key/secret is extracted from
the signing config by first performing a PEM decode on the input and then
falling back on the exisiting mechanism.
Fixes: #3766
> bundle: Update private key extraction mechanism from signing config

- wasm/Makefile
The builtin rules are what causes `make` to attempt to build `src/libc++/mutex`
from `src/libc++/mutex.cc`. The build call will fail like this,
clang++-12  -std=c++17 -MD -MP -nodefaultlibs --target=wasm32-unknown-unknown-wasm -fno-exceptions -fno-rtti -I src/lib -I src/libc++ -I /usr/lib/llvm-12/include/c++/v1 -I /usr/lib/llvm-12/lib/clang/12.0.0/include -I src/re2 -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION -O3   src/libc++/mutex.cc   -o src/libc++/mutex
clang: error: unable to execute command: Executable "wasm-ld" doesn't exist!
clang: error: linker command failed with exit code 1 (use -v to see invocation)
and leave the working tree in a state where `src/libc++/mutex` is deleted,
since it was truncated by the `-o` argument to the cpp compiler, and an
untracked …
> wasm/Makefile: disable builtin rules

- .github/workflows/pull-request.yaml
This splits off the generate call, so that we can have the wasm bits (and capabilities.json) from the PR used in the PR checks. 
The Perf check still is the one taking longest, even with the added matrix build job and the jobs depending on it. The test matrix job was split off to run those in parallel, the binary smoke tests for example can already proceed.
To simplify things, we're relying on the `setup-go` action for both the linux and the darwin unit tests. (We could also use it for the builds of linux and windows binaries... but there, I'm more concerned about a clean build env and reproducibility.)
Fixes #3176.
------
⚠️ If we merge this, we'll need to adjust the repos "required passing checks" settings: "Go Test" now is "Go Test (linux)".
> workflow/pull_request: run tests on macos

- ast/policy.go
- ast/policy_test.go
Previously comments were not being deep copied which could lead to
data races from the transfomer and other places.
Fixes #3793
> ast: Fix deep copy on Module to include comments

- .github/dependabot.yml
This lets dependabot update all golang dependencies, not just wasmtime-go as we had before.
I think we could give this a try. If it becomes too annoying or doesn't work for us, it's easy to turn off again.
> dependabot: let it update all go + GHA dependencies

- capabilities.json
- internal/presentation/presentation_test.go
- types/types.go
- types/types_test.go
This changes updates the implementation of the any type to sort
elements during construction. This way the Compare() function does not
have to sort elements before recursing (which can result in data races
if global type instances from the built-in function declarations or
elsewhere are compared.)
Fixes #3793
> types: Sort any elements during construction

- ast/parser.go
- ast/parser_bench_test.go
- ast/parser_test.go
This change makes the parser cache the results of attempting to parse a certain offset.
The cache structure is a linked-list, each item carries its offset, the term parsed at that offset (if successful), and the post-state (including errors, if unsuccessful). When the parser tries to parse a term at a certain offset, it will first consult the cache.
When inserting something into the cache, each element that has an offset _after_ the inserted element will be dropped.
This is based on the observation that when re-visiting an offset that was already parsed (say, attempting to make sense of the input as a set comprehension after having attempted to parse it as a set) the later offsets never matter. So whenever an offset before a certain other offset is inserted into the cache, the latter …
> ast: avoid extra work parsing objects vs obj comprehensions

- plugins/bundle/config.go
- plugins/bundle/config_test.go
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/plugins.go
- plugins/status/plugin.go
- plugins/status/plugin_test.go
When individual plugins (except discovery) were configured, the
default trigger mode was set as periodic. So if the plugin specified
a different mode (eg. manual), the configuration check would incorrectly
fail on account of a mode mismatch. This commit fixes the issue by
updating the trigger mode check to not specify a default mode in
scenarios when only plugins (except discovery) are configured.
Fixes: #3797
> plugins: Fix default trigger mode in the non-discovery path

- ast/compile_test.go
- ast/term.go
- ast/term_bench_test.go
- ast/term_test.go
- format/testfiles/test.rego.formatted
- rego/example_test.go
- test/cases/testdata/partialsetdoc/test-issue-3819.yaml
Two different commits, two different approaches to fix the underlying problem that during evaluation, we may sort an object's key slice; and that could happen within the function passed to the object's `Iter()` method, causing the weird situation that on subsequent invocations of the passed function, the *same key* would be presented.
This example shows how it's possible, and I believe that this is what happened in #3819.
The partial set memo work that seemed to be the cause of the problem must have changed one thing: before, the document under `data.external["test.target"]` would _not_ have been Compare'd to anything, and afterwards, it would. (I haven't uncovered the complete code flow yet...)
----
This was introduced in https://github.com/open-policy-agent/opa/commit/2381824b168f0d776ec …
> ast/term: don't sort an object's keys slice in-place

- docs/Makefile
- docs/website/scripts/live-blocks/scripts/inject
With more and more version appearing, the argument count passed to the
`npm run` call through the shell glob had increased, too -- to a point
where execution was impossible because it had reached a hard limit.
The obvious fix would have been to use `find [...] -exec cmd {} +` or
`find [...] -print0 | xargs -0 cmd`, however, since the npm call builds
another command line that's executed, we'd step over that limit again.
So instead, we'll now run the npm script on batches of 200 files. It's
below the maximum (unclear what it is, I haven't dug that deep), and
still fast enough (running it file-by-file takes 15+minutes).
> netlify: fix build

- CHANGELOG.md
- ast/term_bench_test.go
- capabilities/v0.33.1.json
- format/format.go
- format/testfiles/test.rego.formatted
- format/testfiles/test_issue_3849.rego
- format/testfiles/test_issue_3849.rego.formatted
Before, it depended on the elements being passed in ordered by their rows.
Before https://github.com/open-policy-agent/opa/pull/3823, the iteration
order was the same as the row order; but with sorting the keys slice (which
determines iteration order) on creation, that was changed.
Now, we'll sort the elements within `groupIterable`.
Fixes #3849.
--------
For #3849, this means that the ordering that matters for formatting literal objects in rego code is
the row ordering. This PR reverts the behavioural change that would make the formatter print those
with their keys sorted.
> format: make groupIterable sort by row

- docs/website/scripts/live-blocks/package-lock.json
- docs/website/scripts/live-blocks/package.json
On my fork, this makes the `ansi-regex` dependabot alert go away.
None of these are likely to cause any real issues, it's just live-blocks, but I'd still prefer fixing over silencing them.
> deps(live-blocks): update mocha (9.1.2) to bump ansi-regex

- format/format.go
- format/testfiles/test.rego.formatted
- format/testfiles/test_fun_args_with_linebreaks.rego
- format/testfiles/test_fun_args_with_linebreaks.rego.formatted
- format/testfiles/test_issue_3836.rego
- format/testfiles/test_issue_3836.rego.formatted
This snippet,
r = contains(
input.x,
"y",
)
would have been formatted as
r = contains(input.x, "y")
before. Now, any new lines added between function arguments will be kept, and
the snippet will not be reformatted.
As a consequence, comments on the separate arguments we OK:
r = contains(
input.x, # haystack
"y",     # needle
)
and don't freak out the formatter.
Fixes #3836.
-------
Changes to the formatter often have the potential to be annoying, but with this, anything that had been formatted with a previous version _should_ still be formatted the same way. I.e., there would not be any breakage in people's CI running `opa fmt` on committed files.
It does, however, broaden the domain of accepted inputs, by not forcing all function arguments to be on one line.
> format: keep new lines in between function arguments

- bundle/store.go
- bundle/store_test.go
Using HasPrefix to compare a root path to the path of policy can result
in unexpected behaviour when different bundles have similarly named
roots.
This replaces the HasPrefix comparison with a comparison that treats the
paths as directories and checks if the policy path is the same path as
the root or a subdirectory of the root path.
Signed-off-by: Edward Paget <edward.paget@chime.com>
For a full explanation of this fix, I ran into this problem with our OPA deployment where I have bundles that are related to specific events. I have two events which I'll call `event_one` and another called `event_one_for_the_books`. They have policies packaged under `com/example/event_one` and `com/example/event_one_for_the_books`. I found that -- depending on the order the bundles were initialized on my …
> bundle: Replace HasPrefix in erasePolicy

- internal/config/config_test.go
- internal/strvals/parser.go
- internal/strvals/parser_test.go
This commit updates the parser for --set options
to return empty struct as return value when null
is specified. This is needed to set an empty object
with the CLI overrides for a null typed value.
Fixes: #3846
> internal: Update the return value for typed value null

- plugins/logs/encoder.go
- plugins/logs/encoder_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
This commit adds a chunk adaptive limit that acts as a
measure for encoding as many decisions into each chunk as possible.
This change should help fill-up the chunks close to their allowed
limit and thereby help reduce netwrok and memory resources.
> Add an adaptive limit for the upload chunk size

- cmd/version.go
- internal/report/report.go
- internal/report/report_test.go
- runtime/runtime.go
This commit updates the runtime to pass the logger to the plugin
manager and the reporter. In addition, the reporter is updated to pass
the logger into the rest client that it creates. With this change, we
no longer rely on the global logger and the logging configuration is
applied correctly.
To verify that this change is going to fix the problem, I have
searched for references to logrus and the logging package.
Grepping for references to logrus reveals that outside of the logging
package, we only refer to formatters and fields (never the global
logrus logger directly).
Grepping for references to logging.{New, Get, NewStandardLogger}
shows that we only create new loggers if one has not been injected
into the manager or rest client. Since we are passing/injecting the
logger from the …
> runtime: Fix logging configuration

- capabilities/capabilities.go
- capabilities/capabilities_test.go
- go.mod
Had to bump the lang directive for this, but our CI should ensure we'll
still be buildable for Go 1.15.
Fixes #3961.
> capabilities: add package-level embed.FS (go 1.16+)

- ast/compile.go
- ast/compile_test.go
The print call rewriting only worked for calls in the body of the
rule. If a call was embedded inside of a comprehension in the head of
the rule, it would not get rewritten. This change just updates the
compiler to use WalkBodies instead of WalkRules which ensures that all
ast.Body structures in the module get visited regardless of where they
are contained.
Fixes #3967
> ast: Fix print call rewriting for calls in head

- .github/workflows/post-tag.yaml
- Makefile
* Do not run ci-release-tag target--the tests have already been run
pre-merge and post-merge so there is little reason to run them again
post-tag. The only thing this would do is find non-deterministic
test failures--which begs the question: what do we do with the
release? We already run tests pre-merge, post-merge, and nightly so
it's unlikely that post-tag will help improve quality.
* Use the RELEASE_DIR from the makefile for the `hub release` asset
parameter rather than assuming the TAG <=> RELEASE_DIR (this is not
always true if tagging an arbitrary commit.) This enables us to cut
release candidates without commiting changes to the repo.
> ci: Tweak the post-tag workflow

- ast/term.go
- cmd/eval.go
- cmd/oracle.go
- internal/oracle/oracle.go
- storage/path.go
Also fixes a panic in `opa oracle find-definition file:12` is file
didn't exit.
> cmd,storage: fix int conversion type errors

- docs/website/scripts/load-docs.sh
The website deployment takes longer than it has to because we're
checking for binaries we don't really care about: those predating
the website, and those of release candidates.
Now, we'll only curl for those we don't skip.
> website/load-docs: skip first, check later

- docs/content/configuration.md
- plugins/rest/azure.go
- plugins/rest/azure_test.go
- plugins/rest/rest.go
This PR introduces an HTTP auth plugin for Azure managed identities. Tokens are acquired following [Azure docs](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http), and each of the HTTP request params can be specified using the plugin. 
Related to #2938 - adding a GCP metadata auth plugin
Fixes #3916 
Signed-off-by: David Lu david.scowluga@gmail.com
> plugins/rest: Add Azure Managed Identities Auth Plugin

- docs/content/configuration.md
- docs/content/extensions.md
- docs/content/policy-reference.md
- docs/website/config.toml
- docs/website/layouts/partials/docs/navbar-section.html
- docs/website/layouts/partials/docs/sidenav-section.html
- docs/website/layouts/shortcodes/danger.html
- docs/website/layouts/shortcodes/info.html
- docs/website/scripts/live-blocks/src/preprocess/index.js
- netlify.toml
For some reason, the "and" trick to step around undefined values no longer
worked. So now, we're wrapping {{ if }} conditionals instead: the outer one
checks that the value is defined, the inner one asserts something on its
value.
Somewhere between 0.55 and the most recent version, Hugo stopped emitting
that div on purpose for languages it didn't know.
Since we depend on it for further processing, we're adding it back.
Also, a trailing newline for code elements was introduced, and that broke
our codemirrors integration -- every code entry would be folllowed by an
empty line. Now, we're removing that in the same preprocess step.
Fixes #3787.
> Bump website to hugo 0.88.1

- test/e2e/testing.go
Some random benchmark test went down from 6s to 2s, so I have some hope that this will also reduce the time our _Go Perf_ check takes.
> test/e2e: silence logs by default with test params

- internal/merge/merge_test.go
Due to the fiddling with StartTimer/StopTimer in the inner loop, this
test ended up taking 5 minutes, even though the time per store size was
not that bad.
After playing with [righting the wrong](https://github.com/srenatus/opa/commit/3d1d5ae5c08868b9f5bb42252bb25874d89c30a4), I've concluded that we don't
gain too much from accurate numbers here -- less so than we did when
this change was introduced originally.
> internal/merge: remove InterfaceMaps benchmark

- rego/rego.go
Fix typo in rego option `SkipPartialNamespace` reported in https://github.com/open-policy-agent/opa/issues/3996
> fix opt SkipPartialNamespace

- ast/compile_test.go
- ast/pretty_test.go
- ast/term.go
- ast/term_test.go
- compile/compile_test.go
Before, we'd sort a set's `keys` slice in-place, and only when it
was actually compared to another set. This side-effect of a comparison
can be unexpected.
Now, we'll keep the `keys` slice sorted by inserting every new element
into its sorted position.
Note that we still sort in-place on Compare, because its possible the
sets values have been altered in different ways (e.g. test TestSetCopy).
Analogous to #3823, where we did this with objects' `keys` slices.
------
Also noticed a problem of #3823: the ordering could me messed up in ways different from inserting key/val pairs, e.g. by changing key names in Iter(), so we'll need to care about our invariant after the Iter() call.
------
🚧 Some discussion items below 👇
> ast/term: sort set's keys slice on insert

- docs/content/policy-language.md
- docs/content/rest-api.md
> docs: Add section on built-in function errors

- compile/compile.go
Previously, `opa build -O=1` would silently discard the support
module for the entrypoint if the entrypoint could not be PE-ed. This
could be somewhat confusing if users expect an optimized/ directory to
show up in the bundle. This change just adds a debug message to the
compiler so that we can see when this happens.
> compile: Add debug message if optimized entrypoint is discarded

- docs/content/management-decision-logs.md
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
Now any subset of service, plugin, console logger should be usable.
Fixes #4013.
> plugins/logs: allow for using service AND custom plugin

- cmd/inspect_test.go
- internal/bundle/inspect/inspect.go
- internal/bundle/inspect/inspect_test.go
Earlier we used an empty namespace for data file located
at bundle root. This change now uses "data" as the
namespace for a data file at root.
Fixes: #4022
> cmd/inspect: Add namespace for data file at root

- Makefile
Added support for building images based on ARM64 processor architecture. 
I've tested the building image process with the following command:
`make build GOARCH=arm64 GOOS=linux CGO_ENABLED=0 WASM_ENABLED=0`
> build: Add support for building images based on processor architecture

- server/buffer.go
- server/server.go
In 6b3c99f1141107e7d4ff21e9113ec1810c887288 the diagnostics buffer
was removed from the runtime params but we forgot to remove the
associated unused code from the server package. This commit completes that.
> server: Remove remaining code from the diagnostics buffer

- docs/content/policy-reference.md
Now that we support urlquery.decode_object the associated issue can
closed with this fix of the description (i.e., don't use the term
"serialize" in this context.)
Fixes #1592
> docs: Update description of urlquery functions

- .github/workflows/nightly.yaml
- .github/workflows/pull-request.yaml
It seldomly matters for PRs, since only a tiny subset of them alters
dependencies. Having the check run in nightlies, where a failure does
not block a PR, but we still notice it through the notifications,
seems like a good trade-off.
> workflow: move go-mod-proxy check into nightly tests

- plugins/rest/aws.go
A user on Slack is getting 500 responses from the AWS metadata API
using a configuration like the below:
```yaml
services:
- name: svc-bundle
url: https://opa-policies-dev.s3.amazonaws.com
credentials:
s3_signing:
metadata_credentials:
aws_region: us-east-1
iam_role: arn:aws:iam::1234:role/opa-bundles
```
It's really hard to know why this might be given how we currently
only log the HTTP status code under this error condition.
This tries to print the response body on debug level (if set).
> plugins/rest/aws: debug log metadata error

- internal/compiler/wasm/opa/callgraph.csv
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/opa_test.go
- wasm/src/malloc.c
Before, we'd either trap with out-of-bounds memory access, or other weird
behaviour.
Included some code cosmetics in pool.go, replacing `for` loop with a `copy`.
Added tests to opa_test.go.
> wasm: opa_abort if memory grow fails

- Makefile
- build/changelog.py
- build/gen-release-patch.sh
This commit improves the release-patch target to mention users in the
Miscellaneous section and warn if a GitHub token is not provided.
> build: Improve CHANGELOG mentions and token usage

- logging/logging.go
- logging/logging_test.go
- plugins/plugins.go
- runtime/runtime.go
The plugin manager was initializing the logger _after_ creating
service clients which meant that service clients ended up relying on
the global logger. Since the runtime package did not configure the log
level on the global logger, the logs from the service clients were
missing.
This commit updates the plugin manager to initialize the logger
_before_ creating service clients and updates the runtime package to
set the log level on the global logger as a fallback.
Fixes #4071
> plugins: Fix logger initialization on plugin manager

- rego/rego.go
- rego/rego_test.go
When using print() and PrepareForEval, subsequent Eval calls are now
able to supply their own `print.Hook`.
Since the result of PrepareForEval may be used by multiple concurrent goroutines, sharing one print hook (backed by one buffer) isn't going to work. Instead, every call to Eval can now provide its own buffer.
> rego: add EvalPrintHook() EvalOption

- cmd/inspect.go
- cmd/inspect_test.go
Inspect previously pretty printed only when -f pretty was specified. This change 
ensures that inspect pretty prints by default, and a user can specify --format=json
to avoid relying on implicit default behaviour.  
Fixes: #4021
Signed-off-by: Emily Tao
<tao.emily@yahoo.ca>
> cmd/inspect: Update inspect to pretty print by default (#4021)

- ast/compile.go
- ast/compile_test.go
- repl/repl_test.go
Before, the "undefined function" check stage in the compiler (and query
compiler) only asserted that the function was known.
Now, we'll also check that the number of arguments _could be_ valid. If
it really is valid will be determined by the type checker at a later
stage.
However, asserting the arity early allows us to give more on-the-spot
error messages.
Fixes #4054.
> ast/compile: check arity in undefined function stage

- docs/content/configuration.md
- go.mod
- go.sum
- plugins/rest/aws.go
- plugins/rest/aws_test.go
- plugins/rest/rest_auth.go
- vendor/github.com/go-ini/ini/.gitignore
- vendor/github.com/go-ini/ini/.golangci.yml
- vendor/github.com/go-ini/ini/LICENSE
- vendor/github.com/go-ini/ini/Makefile
- vendor/github.com/go-ini/ini/README.md
- vendor/github.com/go-ini/ini/codecov.yml
- vendor/github.com/go-ini/ini/data_source.go
- vendor/github.com/go-ini/ini/deprecated.go
- vendor/github.com/go-ini/ini/error.go
- vendor/github.com/go-ini/ini/file.go
- vendor/github.com/go-ini/ini/helper.go
- vendor/github.com/go-ini/ini/ini.go
- vendor/github.com/go-ini/ini/key.go
- vendor/github.com/go-ini/ini/parser.go
- vendor/github.com/go-ini/ini/section.go
- vendor/github.com/go-ini/ini/struct.go
- vendor/modules.txt
This change adds a new AWS credential provider which reads the credential file to fetch credentials for a named profile.
Replaces #4051.
> Add new credential provider for AWS credential files

- plugins/plugins.go
- runtime/runtime.go
Addresses #2777 by
* adding a private router property to the plugin manager along with get and set accessor methods
* adding a conditional override of the runtime param router value if set on the plugin manager
> Expose router in plugin manager

- config/config.go
- config/config_test.go
- plugins/discovery/discovery.go
Previously the discovery plugin would just log a generic error if any
plugins were enabled. With this commit, it will log an error that
mentions which plugins were enabled, making the source of the problem
a bit more obvious.
> plugins/discovery: Improve error message about prohibited config

- test/cases/testdata/arithmetic/test-arithmetic-minus-type-error.yaml
- topdown/arithmetic.go
> topdown: Fix confusing error message for minus operator

- topdown/http.go
- topdown/http_test.go
An inter-query cache is used to cache responses for http.send. This change allows users to gain insight into how the cache is performing by tracking the number of cache hits.
Fixes: #4023
Signed-off-by: Mira Yadav <mira.yadav620@gmail.com>
> http.send: Add metric for counting inter-query cache hits

- ast/compile.go
- ast/compile_test.go
For both partial and complete rules, when variables from destructured
arrays in assignments had been used in the rule head, the print rewriting
would fail.
Now, this situation is accounted for by starting the safe VarSet with
r.Head.Vars()
instead of
r.Head.Args.Vars()
The former will check each of the Args, Key and Value fields of Head: if
it's non-empty, it'll add .Vars() to the returned VarSet.
Fixes #4078.
> ast/compile: fix print rewriting for arrays in := and head vars

- ast/compile.go
- ast/compile_test.go
This reverts commit d1525c126c6c4c9f8b16898f3a92c2a997afdd9b.
> Revert "ast/compile: fix print rewriting for arrays in := and head vars"

- docs/content/kubernetes-primer.md
- docs/website/assets/js/app.js
- docs/website/config.toml
- docs/website/layouts/partials/docs/article.html
- docs/website/layouts/partials/feedback.html
Add an option for users to provide feedback on documentation. Feedback events are logged to Google Analytics.
Based on a Hugo template called Docsy https://www.docsy.dev/docs/adding-content/feedback/).
Changes:
- Add params.ui.feedback parameter to config.toml
- Add feedback.html partial template (based on https://github.com/google/docsy/blob/master/layouts/partials/feedback.html)
- Update article.html partial to include feedback
- Clicking "tell us how we can improve" links the user to create a new issue at https://github.com/open-policy-agent/opa/issues/new
- Add missing </div> to kubernetes-primer.md
- Change app.js to add padding to a separate div
Note: Add `hide_feedback: true` to a page's front matter to disable feedback for that page, for example:
**`docs/content/faq.md`**
```
--- …
```
> docs/website: Add feedback buttons to docs

- docs/Makefile
- docs/website/assets/sass/docs.sass
- docs/website/assets/sass/style.sass
- docs/website/config.toml
- docs/website/layouts/partials/docs/navbar.html
- docs/website/layouts/partials/docs/sidenav.html
Discussions "social link":
also on mobile nav, with the previously missing Contributing and Support sections:
And the bottom-left block of nothing is gone:
> website: misc smaller improvements

- format/format.go
- format/format_test.go
The current version of OPA shows unexpected behavior when formatting files that
contain operators in refs.  This is commonly used to get e.g. the last item out
of an array:
$ cat test.rego
package test
foo = x {
arr = [1, 2, 3]
x = arr[count(arr) - 1]
}
$ opa fmt test.rego
package test
foo = x {
arr = [1, 2, 3]
x = arr[minus(count(arr), 1)]
}
This fixes that issue by using `writeTerm()` rather than `String()` for the ref.
Another approach could be to change this in `String()`; I wasn't sure which one
was better.
> Fix opa fmt issue on refs containing operators

- plugins/rest/aws_test.go
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
Some cleanup in the code and tests, follow-up to [#2786 ](https://github.com/open-policy-agent/opa/pull/4067).
The tests can now run in isolation because one test case shouldn't depend on the env vars another test case has set.
> plugins/rest: refactor AWS credentials provider config validation

- ast/compile_test.go
- ast/unify.go
- ast/unify_test.go
outputVarsForExprEq, which is used in the rewriting of `print()` calls,
wasn't able to find `x` in
[_, x, _] = f(1)
and thus certain print expressions failed during the rewriting stage of
print() calls in the compiler.
Now, the "collection (array/object) = func call" is handled.
Furthermore, this adds calls to isRefSafe in a few places: as it turned
out, the test cases
{"array/ref", "[1,2,x] = a[_]", "[a]", "[x]"},
{"object/ref", `{"x": x} = a[_]`, "[a]", "[x]"},
would have, without the check, passed without "a" in "safe" (3rd field).
The fact that these cases are including "a" is evidence for this being
the correct behaviour.
Fixes #4078.
> ast/compile: fix print rewriting for arrays in unification

- Makefile
- docs/content/_index.md
Adds sha256 checksum to all binaries
These checksums can be used to verify file integrity.
Fixes #3448
> binary: add sha256 checksum to downloads

- docs/content/rest-api.md
- download/download.go
- metrics/metrics.go
- plugins/status/plugin.go
- server/server.go
- server/server_test.go
- server/types/types.go
This is the initial implementation of the v1/status endpoint. The server looks up the status plugin and fetches a snapshot of the status information to return the caller. If the status plugin is not enabled, the endpoint returns a 500 response.
> Add v1/status endpoint

- ast/builtins.go
- capabilities.json
- docs/README.md
- docs/content/contrib-adding-builtin-functions.md
- docs/content/contrib-development.md
- docs/content/policy-reference.md
- test/cases/testdata/cryptohmacmd5/test-cryptohmacmd5.yaml
- test/cases/testdata/cryptohmacsha1/test-cryptohmacsha1.yaml
- test/cases/testdata/cryptohmacsha256/test-cryptohmacsha256.yaml
- test/cases/testdata/cryptohmacsha512/test-cryptohmacsha512.yaml
- topdown/crypto.go
Add crypto.hmac.* built-in functions for the MD5, SHA-1, SHA-256 and SHA-512 hashing algorithms.
Add documentation for how to contribute new built-in functions.
Fixes: #1740
> topdown: Add built-in HMAC functions

- sdk/opa.go
- sdk/opa_test.go
Signed-off-by: orenzohar <oren.zohar@elastic.co>
Adds Runtime(Context) function to Go SDK.
Fixes #4050
> Adds runtime() to Go SDK

- format/format.go
- format/testfiles/test_in_operator_with_all_keywords_import.rego
- format/testfiles/test_in_operator_with_all_keywords_import.rego.formatted
- format/testfiles/test_in_operator_without_import.rego
- format/testfiles/test_in_operator_without_import.rego.formatted
When a module is formatted that has calls to `internal.member_2` or
`internal.member_3`, which get pretty-printed as infix `in` operator
calls, the formatter now ensures that the corresponding future keyword
import is present.
---
Fixes #4111.
> format: ensure future keyword import with `in`

- sdk/opa.go
- sdk/opa_test.go
Updates runtime generation to include the `opa.config`.  @oren-zohar added this functionality yesterday (thank you!), but when I was playing around with it, I noticed the provided config wasn't honored when initializing the SDK. This should take care of it.
> fix: Forward SDK config to runtime config

- plugins/plugins.go
- sdk/opa_test.go
The added test is in the SDK, because that's where the problem had
manifested (#3980): when calling Stop(ctx) through the SDK, the
plugins.Manager's Stop function had set a smaller timeout (0, due
to the structs default value that hadn't been set to anything else),
and that would effectively leave the plugins zero time to cleanup.
Fixes #3980.
---
Thanks to @brianchhun-chime for the thorough analysis, it's made this much quicker to do that it would have been otherwise.
> plugins: support graceful shutdown through SDK

- cmd/features.go
- cmd/run.go
- features/tracing/tracing.go
- go.mod
- internal/distributedtracing/distributedtracing.go
- rego/rego.go
- runtime/runtime.go
- server/features.go
- server/server.go
- test/e2e/distributedtracing/distributedtracing_test.go
- topdown/builtins.go
- topdown/eval.go
- topdown/http.go
- topdown/http_test.go
- topdown/query.go
- tracing/tracing.go
- vendor/modules.txt
This follows the same approach as the wasm feature: by default, importers
of
github.com/open-policy-agent/opa/rego
github.com/open-policy-agent/opa/topdown
will not get a transitive dependency on the otel libraries.
In terms of functionality, nothing changes for the server and runtime.
----
Follow-up to #4029, discussed on that PR.
> tracing: make otel dependency optional for rego+topdown

- compile/compile.go
- compile/compile_test.go
Currently, when setting three or more entrypoints from the same file to `opa build` / `compiler.Build`, only two artifacts get generated.
This appears to be due to a bug in  `compile.optimizer.getSupportModuleFilename`. The current logic  attempts to count the number of times a given filename has been used my bumping a count in a map, however, the key to that map is the mutated file name not the original file name.
Example:
consider three rules in the same policy file `my/policy`
`my/policy/entry_one`
`my/policy/entry_two`
`my/policy/entry_three`
* First rule `getSupportModuleFilename` is called for: 
* `used[my/policy]` gets set to 1 [here](https://github.com/open-policy-agent/opa/blob/main/compile/compile.go#L868)
* Second rule `getSupportModuleFilename` is called for 
* …
> Fix Bug Preventing 3 or More Optimization Entrypoints in a Single File

- docs/content/kafka-authorization.md
Rewrite the Kafka tutorial to use the new authorizer plugin,
and use the management APIs rather than reading policy from
disk.
One decision I made here was to no longer build a special
docker image of Kafka with client certificates bundled, but
rather have a separate script for creating these. This may
add a bit of complexity, but it also makes the process more
transparent to the reader, and they are free to use other
authentication mechanisms should they want to.
A big benefit of this approach is that we don't need to
build new Kafka images whenever Kafka is updated, and
readers can just use the images provided by Confluent.
Finally, the policy examples have been reworked to use
the new authorization input format used by later versions
of Kafka.
Signed-off-by: Anders Eknert …
> Kafka tutorial: new plugin + management APIs

- .github/policy/files.rego
- .github/policy/files_test.rego
- .github/workflows/pull-request.yaml
Since both contributors and reviewers (i.e. me!) seem
to easily miss the correct location of the logo for a new
integration - add checks that will fail the PR when this
happens.
This is admittedly mostly for fun, but I figured it would
be pretty cool to explore whether we could integrate Rego
policies into our own build pipeline. There are definitely
more things to explore using the GitHub API as a datasource
for build pipeline policies, but this is at least a start.
> Check PR for mistakes in ecosystem page change

- Makefile
- bundle/filefs.go
- bundle/filefs_test.go
- internal/wasm/sdk/opa/capabilities/capabilities_nowasm.go
I noticed OPA uses a relatively old golangci-lint version (v1.40.1, which was released on 14 May 2021) so I updated it to the latest v1.43.0 version (And also fixed some linter errors). Thank you for your review1
> Update golangci-lint to v1.43.0

- CHANGELOG.md
- capabilities/v0.36.0.json
- docs/devel/RELEASE.md
- version/version.go
> Prepare v0.36.0 release

- docs/content/integration.md
`some id` left after policy cleanup caused the Rego
compiler to rightfully protest when I tried integrating
OPA as a library today.
> docs: Fix integration policy

- plugins/rest/rest.go
- plugins/rest/rest_test.go
Currently when aiming to use a Plugin in credentials section, if the plugin is known then it will be resolved, if it isn't, it will be passed to the supported credentials and tried to be cast as HTTPAuthPlugin which ends up in a casting issue without further feedback on what was the plugin string.
> chore: improves auth plugin resolution.

- server/authorizer/authorizer.go
- server/authorizer/authorizer_test.go
- server/server.go
> Ensure http.send caching works in system.authz

- docs/content/management-bundles.md
Doc change to clarify that the S3 regional endpoint should be used when loading bundles from Amazon S3.
Using the global S3 endpoint can cause `Bundle load failed: server replied with HTTP 403` due to slow [DNS propagation]( https://aws.amazon.com/premiumsupport/knowledge-center/s3-http-307-response/) after creating a bucket.
When Amazon S3 responds to a "download bundle" request with a redirect, the follow up request from OPA doesn't have an `Authorization` header. This appears to be a deliberate design choice in the go http client:
```
When following redirects, the Client will forward all headers set on the initial Request except:
• when forwarding sensitive headers like “Authorization”, “WWW-Authenticate”, and “Cookie” to untrusted targets. These headers will be ignored when following …
```
> Add hint to docs to clarify that the S3 regional endpoint should be used

- docs/content/envoy-primer.md
- docs/website/layouts/shortcodes/detail-tag.html
This is for issue #4186 . The problem was the default renderer for Hugo doesn't consider these blocks to be safe so chose not to render them. This workaround was taken from [Hugo's discourse](https://discourse.gohugo.io/t/unable-to-use-collapsible-expand-markdown/32810). There is a secondary option of enabling `unsafe=true` for the Goldberg renderer that is detailed on that page.
> Add detail-tab for collapsable markdown

- topdown/encoding.go
While looking into #4140, I noticed that the topdown code for json.is_valid checks validity of json documents by unmarshaling them and checking if there is an error. This leads to allocations proportional to the size of the document, which could affect performance.
This change avoids unnecessary allocations and should offer improved speed and efficiency.
I do not think that changes to tests are necessary because:
- The functionality should be the same, as util.UnmarshalJSON uses the json library internally, except that
- It enables parsing numbers as `Number` instead of float, but I think that difference is only important for unmarshaling, and not validating.
Also, for reference, I wrote a simple benchmark to compare the two implementations here: …
> topdown: Use `json.Valid` instead of `util.UnmarshalJSON`

- docs/content/policy-reference.md
- internal/compiler/wasm/wasm.go
- wasm/src/encoding.c
- wasm/src/encoding.h
- wasm/tests/test.c
wasm: Add support for WASM and simple tests.
internal: Add opa_json_is_valid to map of wasm built-ins.
docs: Indicate that WASM support is now available for json.is_valid.
This code could also benefit from an allocation-less implementation as the change in #4203 was motivated by, but since that is not readily available I opted for this low-hanging version which I still think improves the codebase, and that can be changed to an allocation-less implementation at a later time by someone with capacity and know-how.
Fixes #4140
> Add WASM support for json.is_valid built-in.

- docs/website/scripts/load-docs.sh
With this change, we should get both a /docs/v0.36.1 and a /docs/latest
in our deployed docs.
Before, the symlink would have made hugo only build a /docs/latest,
but not the other link.
> website/load-docs.sh: add versioned docs for latest version

- CHANGELOG.md
- docs/README.md
- docs/content/contrib-adding-builtin-functions.md
- docs/content/contrib-development.md
- docs/content/contrib-docs.md
- docs/content/deployments.md
- docs/content/docker-authorization.md
- docs/content/kubernetes-introduction.md
- docs/content/management-bundles.md
- docs/content/management-status.md
- docs/content/policy-language.md
- docs/content/rest-api.md
- docs/content/security.md
- docs/content/ssh-and-sudo-authorization.md
- docs/content/terraform.md
This updates the linking for several items in the documentation. I noticed that several links pointed to non-existent items or 404s. I've gone through the pages on the left hand side panel and adjusted all that I could find. I did test this with the remote netlify site.
> docs: fixing broken links

- docs/content/management-bundles.md
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
Earlier errors encountered during loading and activating persisted
bundles would cause the OPA runtime to exit. This behavior is different
from when OPA downloads a bundle and activation errors if any would possibly
get resolved in successive download attempts. This fix adds a retry mechanism
to activate persisted bundles in an attempt to mimic the behavior seen during
bundle downloads. Errors if any encountered during the process will be
surfaced in the bundle's status update and not result in an abrupt exit.
Fixes: #3840
> plugins/bundle: Update persisted bundle activation mechanism

- ast/internal/scanner/scanner.go
- ast/parser.go
- ast/parser_test.go
When passing `ParserOptions{AllFutureKeywords: true}` or
`ParserOptions{FutureKeywords: []string{"in"}}` to the `ast` package's
parse methods, and when parsing a module that contains
import future.keywords.in
then we would previously have raised an error: when the parser
encountered the `in`, it complains about not expecting an "in" token
there.
Now, parsing imports is done with a scanner copy that knows nothing
about the future keywords.
> ast/parser: don't error when future kw import is redundant

- ast/capabilities.go
- ast/compare.go
- ast/internal/tokens/tokens.go
- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- ast/visit.go
- capabilities.json
- format/format.go
- format/format_test.go
- format/testfiles/test_every.rego
- format/testfiles/test_every.rego.formatted
- format/testfiles/test_every_with_key.rego
- format/testfiles/test_every_with_key.rego.formatted
This is the first slice of #2090. It will _parse_ and _format_ policies like
```rego
package p
import future.keywords.every
import future.keywords.in
r {
every x in [1,2,3] {
x > 0
}
every i, x in [1,2,3] {
x > i
}
}
```
In follow-up PRs (or piling into this one 🙈), the term rewriting, and the actual evaluation will be added.
(Technically, the visitor changes here wouldn't have been necessary, I think... but anyways it's here now. Rewriting will show if it's the right thing.)
-------
🚧 Open questions:
> ast: add `every` future keyword

- bundle/bundle.go
- bundle/bundle_test.go
When OPA verifies the content of the manifest file,
it first parses it into a JSON structure and then recursively orders
the fields of all objects alphabetically and then applies the
hash function. The same process was not followed while generating
the hash for the manifest content which would result in a digest
mismatch during verification. This can be observed with a manifest
that contains metadata.
Fixes: #4233
> bundle: Roundtrip manifest before hashing

- docs/website/assets/sass/style.sass
hero-body-padding-tablet was introduced in the latest bulma version:
https://github.com/jgthms/bulma/blob/0.9.3/CHANGELOG.md#improvements
Fixes #4253.
> website: change hero-body padding

- build/generate-cli-docs/generate.go
- docs/content/cli.md
So we don't end up with `/opt/buildhome` in our CLI docs:
> docs: de-evaluate $HOME in CLI docs

- docs/website/scripts/live-blocks/package-lock.json
- docs/website/scripts/live-blocks/package.json
This fixes a security issue with redirects:
https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
Rivals #4266.
> website/live-blocks: bump node-fetch (2.6.1 -> 2.6.7)

- .github/workflows/post-merge.yaml
- .github/workflows/post-tag.yaml
- .github/workflows/pull-request.yaml
- Dockerfile
- Makefile
- build/ensure-linux-toolchain.sh
- cmd/version.go
- cmd/version_test.go
- version/version.go
This change adds linux/arm64 binaries to the release. It also publishes an arm64 container image for all variants (standard, debug, rootless, static) and releases (dev, edge, latest).
The build and push process uses buildx to push the individual images by digest (i.e. untagged) and reference them in a single, tagged manifest list. This avoids cluttering Docker Hub's tag list with `<tag>-<arch>` tags.
Fixes #2233
> ci: publish multi-arch image manifest lists

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- storage/disk/disk_test.go
- storage/disk/example_test.go
`make test` was crashing on Mac OS due to "too many open files",
which could be traced to two different issues.
The first one was the disk based storage being opened but not closed
in some cases. This change takes the number of open file pointers
from >300 to ~30 after the disk based tests have run.
The second issue was a fixture HTTP server allowing keep-alive
connections, and since each test would call the server on a
random port, no connection reuse was possible. Since the test
ran over 400 iterations, and the max open file handles on Mac
OS by default is 256, things broke.
> test: fix "too many open files" issue on Mac OS

- .github/workflows/post-merge.yaml
- Makefile
....and silence the aws CLI output a bit.
> build: don't build and push non-static edge arm64 binaries

- topdown/eval.go
- topdown/trace.go
- topdown/trace_test.go
2 new methods of the Event structure:
* Input() to retrieve input document upon event
* Plug(Term) => Term to plug event bindings into Term. This works even if `PlugLocalVars` is false
Signed-off-by: Stan Lagun <stan@styra.com>
> topdown: ability to retrieve input and plug bindings in the Event

- .github/workflows/post-merge.yaml
- Makefile
1. The `aws s3 sync` change is a band-aid, we should fix the IAM policy eventually. We'll keep the stale files around, it should be OK as it doesn't affect the (next) release.
2. If the change to the workflow is what we need is a test; I believe it would make sense if it was the case, but we'll see.
> build: work around issues

- .github/workflows/post-merge.yaml
Now it is consistent with post-tag.yaml. No idea why it was like it was before we had removed it.
> build: use proper action token secret name

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/status/plugin.go
- plugins/status/plugin_test.go
Move the check for "emptiness" before validation and
injection of defaults, as there isn't a whole lot we
can do with a logging plugin that doesn't actually
log anything. Rather than error though, just return
nil to skip initialization of the plugin.
Fixes #4291
> Fix error when initializing empty logging plugin

- bundle/bundle.go
- bundle/bundle_test.go
- cmd/build.go
- compile/compile.go
- compile/compile_test.go
- docs/content/ir.md
- internal/compiler/wasm/wasm.go
- internal/ir/encoding/encoding_test.go
- internal/ir/ir.go
- internal/ir/marshal.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/planner/varstack.go
This PR adds a new "plan" target to the compile package and `opa build` command. This lets users compile their policies into the plan IR so that they could be further transpiled or interpreted outside of OPA.
@srenatus this is still WIP but it's probably worth getting your eyes on this...
- The encoding stuff for the IR is not the prettiest but it works. Maybe there's a cleaner way of doing this? I wanted to avoid having to add marshaling logic to every single statement struct.
- I think we should rename `LocalOrConst` to something a bit less verbose. Maybe just `Operand`?
- See my comment about wrapping the old `LocalOrConst` interface (currently called `LocalOrConstInterface`) in another struct to facilitate marshaling.
Assuming this direction is good, I could imagine:
- ~Adding json …
> Expose planner/IR output via compile package and build command

- ast/compile.go
- ast/compile_test.go
- ast/compilehelper.go
- ast/parser_ext.go
- ast/policy.go
- ast/term.go
- ast/visit.go
This PR covers the compiler doing it's job on `every`:
- resolve refs
- rewriting other declared vars in _domain_
- rewriting _its declared vars_ and others in _its body_
- rewriting dynamics in the body
- expanding expressions
- safety body reordering and var checking
> ast/compile: 'every' rewriting steps

- bundle/bundle.go
- compile/compile.go
- compile/compile_test.go
> Add metadata option to .manifest

- storage/inmem/inmem_test.go
- storage/inmem/txn.go
Currently the "-" character is used to append to
an array. Appends can be also be made by specifying the
array index as long as the specified index is not
greater than the number of elements in the array as
per RFC 6902.
> storage: Support index for array appends

- ast/compile.go
- ast/compile_test.go
Noticed that this would be nice to have in #4322.
Trivial change, I'll merge this when green.
> ast/compile: rewrite 'every' to always have a key

- docs/content/management-status.md
- download/download.go
- download/download_test.go
- plugins/bundle/plugin_test.go
- plugins/bundle/status.go
- server/server_test.go
Hi everyone,
this change adds `http_code` field to the status API.
The field is populated,  if the downloader's last request returned an erroneous HTTP status code.
Fixes https://github.com/open-policy-agent/opa/issues/4259.
Let me know what you think.
Cheers and thank you!
> Add http_code to status API

- CHANGELOG.md
- capabilities/v0.37.2.json
- format/format.go
- format/format_test.go
- storage/inmem/inmem_test.go
- storage/inmem/txn.go
- version/version.go
This is a bugfix release addressing two bugs:
1. A regression introduced in the formatter fix for CVE-2022-23628.
2. Support indices for appending to an array, conforming to JSON Patch (RFC6902)
for patch bundles.
> Prepare v0.37.2 patch release

- ast/capabilities.go
- ast/compile.go
- ast/internal/scanner/scanner.go
- ast/parser.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- capabilities.json
- format/format.go
- format/format_test.go
- format/testfiles/test_every.rego
- format/testfiles/test_every.rego.formatted
- format/testfiles/test_every_with_key.rego
- format/testfiles/test_every_with_key.rego.formatted
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/wasm/sdk/test/e2e/exceptions.yaml
- internal/wasm/sdk/test/e2e/external_test.go
- test/cases/testdata/every/every.yaml
- test/cases/testdata/every/textbook.yaml
- topdown/copypropagation/copypropagation.go
- topdown/eval.go
- topdown/topdown_partial_test.go
- topdown/topdown_test.go
This is another iteration on the "every" work. It includes:
TODOs for follow-ups:
> topdown: evaluate "every"

- go.mod
- go.sum
- vendor/github.com/bytecodealliance/wasmtime-go/README.md
- vendor/github.com/bytecodealliance/wasmtime-go/config.go
- vendor/github.com/bytecodealliance/wasmtime-go/func.go
- vendor/github.com/bytecodealliance/wasmtime-go/instance.go
- vendor/github.com/bytecodealliance/wasmtime-go/linker.go
- vendor/github.com/bytecodealliance/wasmtime-go/module.go
- vendor/github.com/bytecodealliance/wasmtime-go/store.go
- vendor/modules.txt
There's a security advisory in wasmtime that is fixed in 0.34.1,
but it doesn't affect the config available through the go module:
https://github.com/bytecodealliance/wasmtime-go/issues/121#issuecomment-1044721312
So, it's OK to update this to 0.34.0:
https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0340
> build(deps): bump wasmtime-go 0.33.1 -> 0.34.0

- ast/term.go
- ast/term_test.go
- rego/rego_test.go
With this change, we'll calculate hashes as soon as we create or update arrays/sets/objects. This way, we avoid the race detected in #4345 when using PrepareForEval.
❓ Any catastrophic consequences I haven't foreseen?
Fixes #4345.
> ast: hash containers on insert/update

- ast/annotations.go
- ast/annotations_test.go
- ast/check_test.go
- ast/compile.go
Basing compiled annotation set on module set, and not rule graph,
as that caused annotations in modules with only package and no rules
to not get picked up.
Fixes: #4369
> ast: Compiling annotations also for modules with solo package definition

- docs/content/rest-api.md
- server/server.go
- server/server_test.go
- server/types/types.go
This change enables consumers of Compile API to specify packages those should not be inlined in partial evaluation response.
Fixes: #4357
Signed-off-by: Serol Kosunda <skosunda@adobe.com>
> exposing disableInlining option via Compile API

- docs/content/ssh-and-sudo-authorization.md
- docs/website/static/community.html
The docs themselves shouldn't use the full URL to reference other
pages.
Also changes http -> https for the newsletter sign-up page.
> docs+website: two small links fixes

- CHANGELOG.md
- capabilities/v0.38.0.json
- version/version.go
> Prepare Release v0.38.0

- docs/website/static/css/community.css
The new community page looks fine at reasonably high resolution (3456 × 2234 on my machine)...
but there are yet much higher resolutions to be had out there!
If I emulate that by reducing the image (via `Cmd` + `-` several times) this artifact is revealed--notice the clouds no longer cover the full background:
And reducing even further, we get another artifact (I added a border just so you can delineate the edge of the image):
Even at highest resolution, we want the background image to maintain its full cover:
Visit the [netlify deploy preview](https://deploy-preview-4405--openpolicyagent.netlify.app/community)
Signed-off-by: Michael Sorens <msorens@styra.com>
> Stretch background so it covers on larger screens

- ast/parser.go
- ast/parser_test.go
This should inject a hint for when it's likely that a parsed
identifier `every` was meant to be a keyword.
By the usual hinting mechanism in the parser, if the parser proceeds
without any errors, the hint is going to be ignored.
> ast/parser: hint about 'every' future keyword

- Dockerfile
- runtime/runtime.go
First step in https://github.com/open-policy-agent/opa/issues/4295
Open to suggestions on the wording here.
Tested manually by running OPA as non-root (i.e. normally on my laptop) and via `docker run` (which runs as uid == 0).
> Warn on uid/gid == 0

- docs/content/annotations.md
Signed-off-by: Itay Shakury <itay@itaysk.com>
I noticed that the title annotation is missing from the table on top
> docs: add missing title to annotations index

- ast/compile_test.go
- internal/gojsonschema/schema.go
- internal/gojsonschema/testdata/draft4/pattern.json
- internal/gojsonschema/testdata/draft6/pattern.json
- internal/gojsonschema/testdata/draft7/pattern.json
We don't use the regex "pattern" attribute for type checking,
but this still caused problems parsing schemas where the pattern
specified contained things that the Go regex dialect did not
support, such as negative lookahead. Solved for now by simply
removing the regex compilation of pattern properties.
Fixes #4426
> JSON schema: skip pattern attribute compilation

- ast/compile.go
- ast/compile_test.go
When compiling modules containing `every v in vs { ... }`, it will
get rewritten to `every __local0__, v in vs { ... }`.
Sending that module through the compiler _again_, it will complain
about the generated var being declared (via every, it declares its
key and val variables) but unused.
Now, we'll check if the original variable was already a generated
variable, and suppress the error in that case.
Fixes https://github.com/open-policy-agent/opa/issues/4420.
> ast/compile: don't error on unused declared+generated vars (every)

- CHANGELOG.md
- ast/compile.go
- ast/compile_test.go
- capabilities/v0.38.1.json
- version/version.go
This is a bug fix release that addresses one issue when using `opa test` with the
`--bundle` (`-b`) flag, and a policy that uses the `every` keyword.
There are no other code changes in this release.
> Prepare 0.38.1 release

- download/download.go
- download/download_test.go
> downloader: log message on unexpected bundle content type

- ast/compile.go
- ast/compile_test.go
"with keyword target must start with input or data"
=>
"with keyword target must reference existing input or data"
Fixes #4431
> compiler: fix error message on missing with target

- ast/compile.go
- ast/compile_test.go
This is a folllow-up to #4377.
The approach I had advised to take in #4377 fell a little short in the case of shadowed vars: Considering
```rego
package p
import data.foo # unused
r { f(1) }
f(foo) = foo == 1
```
and
```rego
package p
import data.foo # unused
r { foo := true; foo }
```
we have a really hard time figuring out that the vars in those bodies are _not_ actually making use of the imports.
To remedy this, we'll need to do the same work done in resolveAllRefs, which turned out to be much more involved than an `ast.Walk*`.
In the last commit, we're merging the check with the resolveAllRefs stage, because it's avoiding some extra work; and gives us better coverage if there are ever any lazily loaded modules.
> ast/compile: unused imports follow up

- server/server.go
- server/server_test.go
- server/types/types.go
> Add warn when input attributes is missing

- docs/content/configuration.md
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
This change enables to add custom body parameters and headers to OAuth2 Client Credentials token request for non-standard authorization servers.
We use such auth-server which we would need to create a custom plug-in. The target is to help integration with similar systems out of the box without creating a custom plug-in.
Signed-off-by: skosunda <skosunda@adobe.com>
> Support for adding custom parameters and headers for OAuth2 Client Credentials Token request

- Makefile
- docs/Makefile
- docs/website/layouts/404.html
- docs/website/layouts/index.html
- docs/website/layouts/index.redirects
- docs/website/layouts/partials/docs/article.html
- docs/website/scripts/live-blocks/src/preprocess/acquireOPAVersion.js
- docs/website/scripts/load-docs.sh
- docs/website/static/community.html
With this change, the work done for local development, and the per-PR netlify preview changes:
_It will no longer include the website stuff for versions other than **edge**, the current working tree._
We thus save us the time, and the flakiness, involved with
1. checking if github has release binaries for all the versions
2. checking out their sources
3. fetching the release binaries to pre-hydrate old versions' live-blocks.
The previously-used, documented make target should still be intact. 
Fixes #4379 to some extent, I hope.
> website: make local dev not build everything

- go.mod
- go.sum
- vendor/github.com/yashtewari/glob-intersection/go.mod
- vendor/github.com/yashtewari/glob-intersection/match.go
- vendor/github.com/yashtewari/glob-intersection/tokenize.go
- vendor/modules.txt
https://github.com/yashtewari/glob-intersection/releases/tag/v0.1.0
For some reason, dependabot didn't think this was pickup-able:
```
updater | INFO <job_325977497> Checking if github.com/yashtewari/glob-intersection 0.0.0-20180916065949-5c77d914dd0b needs updating
updater | INFO <job_325977497> Latest version is 0.0.0-20180916065949-5c77d914dd0b
updater | INFO <job_325977497> No update needed for github.com/yashtewari/glob-intersection 0.0.0-20180916065949-5c77d914dd0b
```
> build(deps): bump github.com/yashtewari/glob-intersection to v0.1.0

- ast/compile.go
- ast/compile_test.go
The compiler was accidentally checking/rewriting print calls in the
body of else rules before the implicit args of the else rule were
processed. As a result, the compiler was generating false-positive
errors for refs to undeclared args. The root of the problem was the
usage of WalkBodies on the top-level rule (which implicitly walks the
bodies of else rules under the top-level rule). With this change, the
compiler will call WalkBodies on the head and body of each rule rather
than the entire rule itself (which includes the else chain).
Fixes #4489
> ast: Fix print call rewriting in else rules

- plugins/logs/plugin.go
We were incorrectly resetting the retry counter after
every error condition instead of using the incremented
value. As a result, retry delay would always be 0s.
This meant that if OPA encountered an error while
uploading decision logs it would immediately retry
instead of doing an exponential backoff.
Fixes: #4486
> plugins/logs: Fix broken retry logic

- plugins/rest/rest.go
- plugins/rest/rest_test.go
> logging: mask authorization header value in debug logs

- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
- format/testfiles/test_with.rego
- format/testfiles/test_with.rego.formatted
Fixes #4376
Do note though that this does not change how multiple
with statements are grouped. Although I agree with that,
it's IMHO a separate feature request, while the spacing
issue is a bug.
> Remove space from tabbed `with` indentation

- runtime/logging.go
- runtime/logging_test.go
This change omits the response body when using compression on metrics endpoint and when pprof is enabled.
Signed-off-by: Christian Altamirano <christian.altamirano.ayala@gmail.com>
> Improve log output for binary response when debug logging or pprof enabled

- ast/policy.go
- test/e2e/concurrency/concurrency_test.go
- test/e2e/metrics/metrics_test.go
- test/e2e/testing.go
- topdown/eval.go
What we previously did turned into a race condition with multiple
concurrent calls to /v1/compile.
With a change introduced with 0.38.0 (the `every` keyword), the
`nil` Terms of an `ast.Expr` node was surfaced: previously, it would
go unnoticed, but could potentially have yielded bad results.
The effect of this change is proven using a new e2e test that would
fail on the code we had previous.
> topdown/eval: copy without modifying expr, update test/e2e/concurrency

- docs/website/static/community.html
Not a hugo template 🤦 Sorry this slipped through when making local/PR previews faster.
> website: fix community site

- docs/content/misc-disk.md
- plugins/bundle/plugin_test.go
- server/server_test.go
- storage/disk/disk.go
- storage/disk/disk_test.go
- storage/disk/paths.go
> storage/disk: some follow ups

- docs/website/assets/sass/docs.sass
Adds some bottom margin to regular (non-live-blocks) code blocks:
> website/style: fix code block bottom margin

- .github/workflows/pull-request.yaml
- build/policy/files_test.rego
- opa 0.39.0 changed the `with` formatting
- we're using the `latest` version of OPA in there (by default) -- changed to `edge` to catch something like this earlier
> ci: fix rego check

- docs/website/layouts/index.html
To Fix:
```
2 errors occurred:
policy.rego:13: rego_compile_error: assigned var header unused
policy.rego:13: rego_compile_error: assigned var signature unused
```
Snapshot of the error
> Comment out unused variables to avoid error for homepage sample

- docs/website/layouts/partials/docs/article.html
Hopefully this is gets more attention than the yellow "older" button
in the version picker.
Tested locally, seems to be OK:
Note: this had to be tested locally since we've stopped building all the versions for a PR preview.
> website: show yellow banner for old version

- .github/workflows/pull-request.yaml
- Makefile
- topdown/exported_test.go
- topdown/topdown_test.go
Inadvertently stopped running these in CI when going to go1.18 and expanding our tests base. 😅 
Also turns the timeout higher for a cancellation tests that was flakey on macos in CI.
Also avoid building wasm for the compat builds.
> topdown: fix TestRego

- logging/logging.go
- logging/logging_test.go
- storage/disk/disk_test.go
Fixes #4373 
This is a new PR that was raised. The last PR was closed because of merging issues.
Old PR: #4507
> Fix: Deprecate or promote WARN level in logging package

- internal/bundle/inspect/inspect.go
Errors encountered during `inspect` command execution, when building the annotation-set are swallowed.
> inspect: Fixing issue where some inspect errors aren't reported

- topdown/tokens_test.go
[Go 1.18.1](https://groups.google.com/g/golang-announce/c/oecdBNLOml8) was released last night -- and while it doesn't change
the signatures, it changes what `runtime.Version()` returns.
Our test expectation didn't account for that.
We've been pulling in go1.18.1 because our .go-version has 1.18 in it,
and the docker image ref built from that for the `ci-go-*` make targets
will use golang:1.18, which refers to the latest patch release.
> topdown/tokens_test: adjust expected signature for go1.18.1

- bundle/bundle.go
- bundle/bundle_test.go
- bundle/store.go
- bundle/store_test.go
- download/download.go
- download/download_test.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
Currently etag from the HTTP response of activated bundles is not
persisted to store. Hence if OPA restarts and an activated bundle
loaded from the disk store is up-to-date, OPA may still download
the same version of the bundle and activate it. With this change,
OPA should include the right etag in the bundle download request
thereby avoiding unnecessary bundle download and activation.
Fixes: #4544
> Persist activated bundle etag to store

- docs/website/layouts/index.redirects
This will result in the _redirects page having a bunch of entries like this:
/docs/v0.38.0/* /docs/v0.38.1/:splat
/docs/v0.37.1/* /docs/v0.37.2/:splat
/docs/v0.37.0/* /docs/v0.37.2/:splat
/docs/v0.36.0/* /docs/v0.36.1/:splat
/docs/v0.34.1/* /docs/v0.34.2/:splat
/docs/v0.34.0/* /docs/v0.34.2/:splat
/docs/v0.33.0/* /docs/v0.33.1/:splat
/docs/v0.32.0/* /docs/v0.32.1/:splat
👉 https://docs.netlify.com/routing/redirects/redirect-options/#splats
Fixes https://github.com/open-policy-agent/opa/issues/4225.
> website: redirect previous releases to the latest patch release

- format/format.go
- format/testfiles/test_in_operator_without_import.rego.formatted
- format/testfiles/test_issue_4606.rego
- format/testfiles/test_issue_4606.rego.formatted
Also ensure that added imports have a location set.
Previously, `opa fmt` on the added test file would have panicked
because the import hadn't had a location.
Fixes #4606.
> format: don't add 'in' keyword import when 'every' is there

- cmd/eval_test.go
- format/format.go
- format/format_test.go
- internal/presentation/presentation.go
The presence of location-less nodes in the AST has been a problem before.
Most recently, it showed up here:
```
$ opa eval -p -fsource 'time.clock(input.x)==time.clock(input.y)'
time.clock(time.clock(input.x), input.y)
```
Fixes #4609.
What's intentionally left out for now is the bundle optimization path. While I still maintain that it's the proper thing to do; there may be more edge cases to consider, and I'd really like to fix the `opa eval -p` bug quickly.
> format,eval: don't use source locations when formatting PE output

- docs/website/layouts/partials/docs/navbar.html
Addressing one tiny bit of #4614.
> website: add playground button to navbar

- docs/content/kubernetes-debugging.md
- docs/content/kubernetes-introduction.md
change admission.k8s.io/v1beta1 -> admission.k8s.io/v1 #3785
> change-admission-v

- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/bundle/status.go
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
OPA has support for Delta Bundles. The status object already
contains valuable information such as last activation timestamp but
does not specify if the bundle was a canonical snapshot or delta.
This change updates the bundle.Status object to include the
bundle type string: either "snapshot" or "delta". This can be useful
for status endpoints to differentiate between the bundle types.
Issue: 4477
Signed-off-by: Bryan Fulton <bryan@styra.com>
> bundle/status: Include bundle type in status information

- ast/compile.go
- ast/compile_test.go
- docs/content/policy-language.md
- docs/content/policy-testing.md
- format/testfiles/test_with.rego
- format/testfiles/test_with.rego.formatted
- internal/planner/planner.go
- internal/planner/rules.go
- test/cases/testdata/withkeyword/test-with-function-mock.yaml
- topdown/cache.go
- topdown/eval.go
- topdown/topdown_partial_test.go
Follow-up to https://github.com/open-policy-agent/opa/pull/4540
We can now mock functions that are user-defined:
package test
f(_) = 1 {
input.x = "x"
}
p = y {
y := f(1) with f as 2
}
...following the same scoping rules as laid out for built-in mocks.
The replacement can be a value (replacing all calls), or a built-in,
or another non-built-in function.
Also addresses bugs in the previous slice:
* topdown/evalCall: account for empty rules result from indexer
* topdown/eval: capture value replacement in PE could panic
Note: in PE, we now drop 'with' for function mocks of any kind:
These are always fully replaced in the saved support modules, so
this should be OK.
When keeping them, we'd also have to either copy the existing definitions
into the support module; or create a function stub in …
> ast+topdown+planner: non-built-in function mocking

- format/format.go
- format/testfiles/test_with.rego
- format/testfiles/test_with.rego.formatted
> format: keep whitespaces for multiple indented same-line withs

- CHANGELOG.md
- capabilities/v0.40.0.json
- version/version.go
🎉 Here we go. Many first contributions in this release! 👏 Thanks a lot to every contributor!
> Prepare v0.40.0 Release

- docs/content/annotations.md
- docs/content/policy-reference.md
Also using `module` instead of `query` in `live:rego` blocks for annotation examples.
> docs: Adding example for `rego.metadata.role()` usage

- ast/builtins.go
- capabilities.json
- docs/content/policy-reference.md
- test/cases/testdata/units/test-parse-units-comparisons.yaml
- test/cases/testdata/units/test-parse-units-errors.yaml
- test/cases/testdata/units/test-parse-units.yaml
- topdown/parse_bytes.go
- topdown/parse_units.go
Add new built-in ~`units.parse_units`~ `units.parse` to resolve #1802 by enabling parsing of k8s CPU resource strings, such as "100m", "1.4k", etc.
This function works on all base decimal and binary SI units of the set: m, K/Ki, M/Mi, G/Gi, T/Ti, P/Pi, and E/Ei. This exactly matches the range of SI units that k8s' resource string parser understands.
> built-ins: Add units.parse function

- util/json.go
- util/json_test.go
This helper accepts JSON or YAML, and used to do this:
1. For YAML input, yaml.YAMLToJSON would parse it as yaml, marshal it to
JSON, and pass that back out to be passed to UnmarshalJSON
2. For JSON input, yaml.YAMLToJSON would also parse it as yaml, marshal it
to JSON, and pass that back out to UnmarshalJSON
Issue #4673 has shown that the theoretical "superset" propery of YAML doesn't
seem to hold in all cases.
So now, we'll do this:
1. For YAML input, yaml.YAMLToJSON would parse it as yaml, marshal it to
JSON, and pass that back out to be passed to UnmarshalJSON
2. For JSON input, json.Valid will determine that it's JSON, and we'll
feed it into UnmarshalJSON as-is.
The YAML path (1.) still seems suboptimal, but I also suspect that JSON is
more common. Also, this change shouldn't make …
> util/Unmarshal: if it's JSON, skip YAMLtoJSON

- download/oci_dowload.go
- download/oci_download_test.go
- go.mod
- sdk/test/test.go
- test/e2e/oci/oci_test.go
- vendor/modules.txt
Using the etag in the OCI downloader to store the SHA fixes issue https://github.com/open-policy-agent/opa/issues/4637
> OCI: Fix bundle reload and activation unconditionally

- docs/content/policy-reference.md
Small grammar fix in documentation. Fixes #4689
> Fix import rule. Package should be ref

- ast/location/location.go
- ast/parser.go
- ast/parser_ext.go
- bundle/bundle.go
- bundle/file.go
- bundle/verify.go
- bundle/verify_test.go
- cmd/sign.go
- compile/compile.go
- download/download.go
- internal/compiler/wasm/wasm.go
- internal/jwx/buffer/buffer.go
- internal/jwx/jwa/key_type.go
- internal/jwx/jwa/signature.go
- internal/jwx/jwk/ecdsa.go
- internal/jwx/jwk/headers.go
- internal/jwx/jwk/jwk.go
- internal/jwx/jwk/rsa.go
- internal/jwx/jwk/symmetric.go
- internal/jwx/jws/headers.go
- internal/jwx/jws/jws.go
- internal/jwx/jws/sign/ecdsa.go
- internal/jwx/jws/verify/hmac.go
- internal/runtime/init/init.go
- internal/wasm/encoding/reader.go
- plugins/status/plugin.go
- server/server.go
- test/cases/testdata/jwtencodesignheadererrors/test-jwtencodesignheadererrors-0380.yaml
- test/wasm/cmd/wasm-rego-testgen/main.go
- topdown/tokens.go
This package is deprecated, archived, and in maintenance mode, since Go
errors support wrapping natively.
Signed-off-by: Jason Hall <jason@chainguard.dev>
Progress toward https://github.com/open-policy-agent/opa/issues/2152
> Remove dependency on deprecated github.com/pkg/errors

- test/cases/testdata/units/test-parse-bytes-comparisons.yaml
- test/cases/testdata/units/test-parse-bytes-errors.yaml
- test/cases/testdata/units/test-parse-bytes.yaml
- test/cases/testdata/units/test-parse-units-comparisons.yaml
- test/cases/testdata/units/test-parse-units-errors.yaml
- test/cases/testdata/units/test-parse-units.yaml
Add "units_" prefix to all units-related test cases, so that they are
easier to find and run manually.
Signed-off-by: Philip Conrad <philipaconrad@gmail.com>
> test/units: Add "units_" prefix to units-related tests.

- docs/content/policy-language.md
In almost all cases now, order does matter, and using assignment
is no longer the exception but the rule. Move the "order doesn't
matter" text to the section on unification.
> Update docs on ordering expressions

- internal/jwx/jwa/signature.go
- internal/jwx/jwk/jwk.go
- internal/jwx/jws/headers_test.go
- internal/jwx/jws/jws_test.go
- topdown/tokens.go
- topdown/tokens_test.go
Additionally, improve the JWT verification process when a JWKS
is provided:
* If `kid` is present in JWT header, and exists in JWKS — verify using
that key only.
* If `kid` not present in JWT header, try verification only using keys
matching the `alg` provided in the JWT header (mandatory claim).
Fixes #4699
> Ignore keys of unknown alg when verifying JWTs with JWKS

- bundle/bundle.go
- bundle/bundle_test.go
Previously, when creating a signed bundle and either no `.manifest`
file is present or when the contents are the defaults, no `.manifest`
file would get written to the `.tar.gz` output but there would be an
entry for the manifest in the `.signatures.json` file when trying to
verify the bundle. I modified the signature process to skip hashing
the manifest when it is empty for whatever reason.
Fixes #4712
Signed-off-by: Matt F <15720856+friedrichsenm@users.noreply.github.com>
> bundle: dont sign manifest when empty

- cmd/fmt.go
- cmd/fmt_test.go
The change enables using --diff and --list together with --fail as discussed in https://github.com/open-policy-agent/opa/issues/4508, for example:
$ opa fmt [path [...]] --list --fail; exit $?
path/to/file-1.rego
path/to/file-2.rego
unexpected diff
2
Previously, the same command returned only the error:
$ opa fmt [path [...]] --list --fail; exit $?
unexpected diff
2
> format: Output list and diff changes with --fail flag (#4508)

- sdk/opa.go
- sdk/opa_test.go
- sdk/options.go
When calling the sdk the user can specify an opa id so that repeat calls to the sdk don't have a unique opa id
Fixes #4723
Signed-off-by: PrahathessRaghavan<prahathess@gmail.com>
> SDK: Allow configurable ID

- internal/planner/planner.go
- test/cases/testdata/withkeyword/test-with-builtin-mock.yaml
Before, we'd only plan a single rule functions when a function used
in that rule's body was mocked, instead of planning one rule function
for the mocked, and one for the un-mocked function.
This only affects uses where both the mocked and the un-mocked version
of the rule are queried, like
p {
q with time.now_ns as 1 # (1)
not q                   # (2)
}
Now, we plan g1.data.pkg.q for (1), and g0.data.pkg.q for (2), where
g1's plan uses the mocked function result, and g0's plan uses the
builtin.
> planner: shadow rule funcs if mocking functions

- rego/rego_wasmtarget_test.go
- tester/runner_test.go
- util/test/ci_skip.go
- util/test/ci_skip_darwin.go
Some care has been taken that these tests still run on development
machines. They'll only be skipped if the following is true:
1. the os is darwin
2. the CI env var is set to something
This approach, adding the skip calls manually on a case-by-case basis,
should allow us some fine-grained control. If we had used build tags,
we'd only be able to skip all the tests in one file together.
> ci: skip flakey darwin tests on PR runs

- .github/workflows/pull-request.yaml
- build/check-working-copy.sh
- builtin_metadata.json
We'll figure out how to do this in the release process, but for now, this
is enough to not have the builtin_metadata.json change appear in each PR.
> builtin_metadata: add v0.41.0 manually

- plugins/logs/mask.go
- plugins/logs/mask_test.go
Earlier the paths to the field to perform an upsert or
remove operation on were escaped using Go's url.QueryEscape
method. This results in incorrect behavior when the paths contain
a reserved character like ":". This change updates to using
url.PathEscape instead to escape the input and result paths.
Fixes: #4717
> plugins/logs: Update mechanism to escape field paths

- go.mod
- go.sum
- internal/prometheus/prometheus.go
- internal/prometheus/prometheus_go1.16.go
- internal/prometheus/prometheus_go1.17.go
- internal/prometheus/prometheus_test.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_go116.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector_latest.go
- vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
- vendor/modules.txt
Fixes #4697.
- three histograms lost their erroneous "_total" suffix
- one gc cpu fractions metrics is gone
Also, the tests now actually run on Go1.17+, I had misunderstood a build tag earlier.
We're using a deprecated option to keep all the metrics we had before.
In the future, it probably makes sense to use the advised collection only.
Alternatively, we could expose a config option.
> prometheus: bump client_golang, adjust setup and tests

- ast/compile.go
Inconsequential, I think; but better to fix anyways.
> ast/compile: fix util.HashMap eq comparison

- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
Currently OPA allows users to use unsigned discovery
bundles that themselves point to signed service bundles.
The discovery plugin checks if the keys in the service bundle
do not update those in the boot config. It's possible that
the signing config in the discovery object be a nil pointer.
This is change adds a check for that.
Fixes: #4656
> plugins/discovery: Check for empty key config

- ast/builtins.go
- builtin_metadata.json
- capabilities.json
- test/cases/testdata/subset/test-subset.yaml
- topdown/subset.go
- topdown/topdown_bench_test.go
This implements the new object.subset() builtin.
Fixes #4358
Signed-off-by: Charles Daniels <charles@styra.com>
> built-ins: add object.subset() builtin

- server/server.go
Currently a write transaction on the store is opened
inside the query API handler (ie. v1DataPost). What this
means is if the user wants to evaluate a policy while
OPA is activating a bundle, the api request would block
trying to open a write txn on the store till the bundle
was activated. If OPA is activating a large bundle,
the write lock is held longer and hence the client would
notice the latency in OPA's API response. This change updates
the query handler to open a read txn on the store which was
the case pre-v0.39.0.
> server: Open read storage txn in query api handler

- topdown/glob.go
- topdown/topdown_bench_test.go
Use strings.Builder to construct the ID for use in glob.match(). This
offers a slight performance improvement.
This also adds a benchmark to the glob.match() builtin.
Signed-off-by: Charles Daniels <charles@styra.com>
---
Before I made this optimization, this is what I got on the new benchmark:
```plain
pkg: github.com/open-policy-agent/opa/topdown
BenchmarkGlob/10-8         	   15644	     76413 ns/op
BenchmarkGlob/100-8        	    1770	    656534 ns/op
BenchmarkGlob/1000-8       	     178	   6645135 ns/op
BenchmarkGlob/10000-8      	      16	  69947432 ns/op
PASS
ok  	github.com/open-policy-agent/opa/topdown	9.025s
```
And after:
```plain
pkg: github.com/open-policy-agent/opa/topdown
BenchmarkGlob/10-8         	   19495	     61227 ns/op
BenchmarkGlob/100-8        	    2337	    511508 …
```
> built-ins: use strings.Builder in glob.match()

- Makefile
- build/gen-dev-patch.sh
- build/gen-release-patch.sh
- build/get-build-version.sh
- build/update-version.sh
- docs/devel/RELEASE.md
- internal/cmd/genbuiltinmetadata/main.go
Fixes #4754.
Rule number one of release-script changes: it'll break the next release. 🤞 
This is more convoluted than it has to be, but it's because of this outline of our release process:
- A clean checkout is used to generate the release patch,
1. it'll update the version/version.go file
2. it'll copy the capabilities files
- go isn't available in the docker container running that script (we're using python there)
- the golang script generate builtin_metadata.json consumes the capabilities files
So now, we'll bump the version in version/version.go and run `make generate` before handing stuff off to the python container with its release patch generation. With an extra conditional in the script generating the builtin_metadata.json when its version doesn't end in `-dev`, we'll add the …
> build: integrate builtin_metadata.json handling in release process

- internal/cmd/genbuiltinmetadata/main.go
This will suppress the
WARN: not categorized: type_name
lines that we expect.
> genbuiltinmetadata: suppress known uncategorized builtins

- runtime/check_user_darwin.go
- runtime/check_user_linux.go
- runtime/check_user_windows.go
- runtime/runtime.go
We don't need it, and it can cause issues and delays we could avoid.
> runtime: don't lookup current user on windows

- ast/compile.go
- ast/internal/tokens/tokens.go
- ast/parser.go
- ast/parser_test.go
- capabilities.json
- docs/content/_index.md
- docs/content/envoy-primer.md
- docs/content/envoy-tutorial-istio.md
- docs/content/envoy-tutorial-standalone-envoy.md
- docs/content/policy-language.md
- docs/content/policy-reference.md
- docs/content/policy-testing.md
- docs/website/scripts/live-blocks/src/preprocess/localEval.js
- format/format.go
- format/format_test.go
- format/testfiles/test_contains.rego
- format/testfiles/test_contains.rego.formatted
- format/testfiles/test_contains_if.rego
- format/testfiles/test_contains_if.rego.formatted
- format/testfiles/test_if.rego
- format/testfiles/test_if.rego.formatted
- format/testfiles/test_if_else.rego
- format/testfiles/test_if_else.rego.formatted
- format/testfiles/test_in_operator_with_all_keywords_import.rego.formatted
- internal/future/filter_imports.go
- test/cases/testdata/containskeyword/test-contains-future-keyword.yaml
This introduces another keyword to Rego: "contains"
It provides an alternative way to declare partial sets:
p contains x {
x := { "foo": "bar"
}
which is the same as
p[x] {
x := { "foo": "bar"
}
The keyword is enabled by importing `future.keywords.contains`, and
when it _is enabled_, the format will be used for all partial sets in
that file for pretty-printing.
With this change, we can use `if`, and an optional shorthand for
rule definitions:
The syntax is
NAME [if] { EXPR [EXPR...] }
and the shorthand allows dropping the braces around the expression
if there is only one:
NAME if EXPR
For example, this allows expressions like
allow if not deny
f(xs) if every x in xs { x != "foo" }
The one exception here are partial sets: they cannot use `if` UNLESS
they use `contains`:
p[x] { x := "foo" } …
> ast+format: introduce "contains" + "if" keywords

- cmd/bench.go
- cmd/bench_test.go
- cmd/flags.go
- server/server.go
This commit adds a new flag to the opa bench command which
allows users to run benchmarks against a running OPA server.
This mode can be used to evaluate the additional overhead the
server is going to introduce.
Co-authored-by: Anders Eknert anders@eknert.com
> Add e2e mode for opa bench

- ast/builtins.go
- ast/compile_test.go
- builtin_metadata.json
The names of function arguments have been mixed up:
the second argument is the string that will be searched for in the
string provided as first argument.
Additionally the documentation of the endswith function had a copy paste
mistake from the starswith documentation.
Signed-off-by: Max Hoehl <m.hoehl@sap.com>
> Fix documentation of startswith and endswith builtins

- Makefile
- ast/fuzz_test.go
- ast/policy.go
- ast/term.go
- cmd/inspect.go
- internal/presentation/presentation.go
- tester/reporter.go
Fixes #4765; at least in a way. None of the new findings were err-related.
⚠️ Note that golangci-lint tries hard to cut down the number of issues it presents the user:
```
level=info msg="[runner] Issues before processing: 429, after processing: 0"
```
which is why a plain `errcheck` run is expected to turn up more problems than a golangci-lint run of the `errcheck` linter.
> ci: bump golangci-lint to v1.46.2, fix some issues

- Makefile
This is an attempt to fix an obscure condition that started last week:
the `aws s3 sync` command in our `deploy-ci` make target started failing,
with only this output:
<botocore.awsrequest.AWSRequest object at 0x7f3198832f70>
A promising google hit suggests that it's got to do with "what's the best
region for me?" auto-discovery failing. Passing any region should then do
the trick.
Ref: https://florian.ec/blog/github-actions-awscli-errors/
> ci: pass --region to 'aws s3 sync' command

- docs/content/configuration.md
Signed-off-by: Li Wang <li.wang3@fmr.com>
> fix configuration docs

- build/check-working-copy.sh
- internal/cmd/genbuiltinmetadata/main.go
#4763 had overcompensated. Now we're not adding the latest version twice.
> release process: fix metadata logic

- server/server.go
- server/server_test.go
Before, the option InterQueryCache(...) passed to the authorizer's config
had set it to `nil` -- it wasn't set up yet.
Now, the ordering allows for caching in the system authz policies.
Fixes #4829.
> server: pass IQBC to authorizer

- CHANGELOG.md
- builtin_metadata.json
- capabilities/v0.42.0.json
- version/version.go
> Prepare release v0.42.0

- test/cases/testdata/jsonbuiltins/test-is-valid.yaml
- topdown/encoding.go
- topdown/graphql.go
- topdown/semver.go
- wasm/src/encoding.c
This PR changes the behavior of the `*.is_valid` builtins to consistently return **only** true/false values, with no runtime/builtin errors. No docs changes should be required, since this is the documented behavior of these functions.
The affected list of builtins:
Encoding:
- `base64.is_valid`
- `json.is_valid`
- `yaml.is_valid`
GraphQL:
- `graphql.is_valid`
Regex:
- `regex.is_valid` (already implements behavior)
Semver:
- `semver.is_valid`
Questionable additions to the list:
- `io.jwt.verifyX` functions?
Fixes #4760.
> topdown: Make *.is_valid function behavior more consistent

- docs/content/policy-testing.md
Fixes #4849.
------
ℹ️ Backport material for 0.42.1.
> docs/policy-testing: add missing future.keywords imports

- storage/inmem/inmem.go
- storage/inmem/inmem_test.go
A data write performed at a non-root nonexistent path
in the im-memory store during a trucnate op would cause a
storage not found error. This change creates a path if one
does not exist before writing data.
> storage/inmem: Create path if does not exist during truncate

- test/cases/testdata/units/test-issue-4856.yaml
- topdown/parse_units.go
Previously, we used `big.Float` for units parsing, but this resulted in occasional rounding issues, due to values like `0.001` not being perfectly representable in floating-point format.
This issue was fixed by switching units parsing to use `big.Rat`, since Rationals can generally handle such quantities with perfect precision.
A few new regression test cases have been added to the test suite, lifted almost verbatim from the original issue.
Fixes #4856.
> topdown/parse_units: Use big.Rat for units parsing.

- docs/website/scripts/live-blocks/package-lock.json
- docs/website/scripts/live-blocks/package.json
...for proper highlighting of "contains" and "if":
Before
After
> website/live-blocks: update codemirror-rego to 1.3.0

- docs/content/policy-language.md
This adds a section listing all future keywords to policy language.
I've once learnt that redundancy in docs is not necessarily a bad thing, so I've kept most of the info blocks intact.
> policy-language: add future keywords section

- storage/disk/disk.go
- storage/disk/disk_test.go
So for now, we'll properly create the symlinks without the wrong indirection.
Fixes #4869.
~I'm still looking into remediation logic: _if the symlink is wrong, fix it automatically_.~
Update: I think we should keep this as-is. The first is simple enough to guide the few people who could have run into it at this point to the proper steps.
> storage/disk: make symlinks work with relative paths

- bundle/store.go
filepath.Join can return paths with \ separators. So
when this command is run on Windows the paths are joined
using \ separator. But the bundle root check logic assumes the paths
are '/' separated. This change processes the result of filepath.Join
is ensure the path has '/' separators.
> bundle: Normalize paths before bundle root check

- cover/cover.go
- docs/content/policy-testing.md
Adds `covered_lines` and `not_covered_lines` to the test coverage report for each file and the total. This allows custom scripts to more easily parse the output and calculate its own coverage numbers skipping certain files, e.g. test files or external policy dependencies.
Whilst these numbers can be calculated manually, custom scripts would be much simpler having these numbers already present and it's also more clear to readers how coverage is calculated.
No tests were added as these fields use existing methods that are already tested.
> Add line count to test coverage report

- bundle/bundle.go
- bundle/bundle_test.go
This PR resolves this issue : #4859 
Signed-off-by: Joffref <mariusjoffre@gmail.com>
> Add support for .yml files in opa bundle command

- MAINTAINERS.md
Move Will Beason to emeritus status, add Ernest as a maintainer.
Looks like this needs a 2/3 vote at the organization level.
https://github.com/open-policy-agent/opa/blob/main/GOVERNANCE.md#changes-in-maintainership
> Change maintainers for Gatekeeper

- docs/content/graphql-api-authorization.md
:construction: This PR should be merged only once the matching GraphQL tutorial materials repo is live.
-----
This PR contains the draft of a basic GraphQL policy sample (modeled very heavily off of the [HTTP API Authz tutorial](https://www.openpolicyagent.org/docs/latest/http-api-authorization/)). The policies I came up with aren't pretty, but then again, neither are GraphQL ASTs! :sweat_smile:
> docs: Add initial GraphQL tutorial.

- docs/content/graphql-api-authorization.md
- docs/content/policy-reference.md
- docs/website/data/integrations.yaml
This commit fixes the formatting of "note" fields in the policy reference document that were block quotes before, and adds a note about supporting custom GraphQL `@directive` syntax in schemas.
It also corrects the GraphQL tutorial source code link, over in the GraphQL API authz tutorial.
> docs: Fix policy-ref formatting, GraphQL docs

- docs/content/kubernetes-tutorial.md
Two unrelated issues would break the Kubernetes tutorial in recent kube versions. The first one being the SHA1 hash used by default in at least older versions of OpenSSL, which is no longer accepted by Kubernetes. Easy fix.
The next one is definitely a head scratcher - for whatever reason, the `subjectAltName` previously provided in the config didn't seem to be picked up in certificate signing requests. Older versions of Kubernetes - or Go, really - would accept the common name (CN), but more recent ones require the use of `subjectAltName`, so it's possible this never "worked" as intended but was ignored as the CN was used instead.
The docs on the topic however all suggest that the previous config _should_ have worked, and after having spent a long time trying to figure out why it didn't, …
> docs: update kube tutorial cert install procedure

- docs/content/policy-reference.md
The `Grammar` section of the markdown document had an extra double-quote
that was throwing off the syntax highlighting. I removed it.
Fixes: #4915
Signed-off-by: Matt F <15720856+friedrichsenm@users.noreply.github.com>
> Remove extra quote in policy-reference.md

- ast/builtins.go
- builtin_metadata.json
- capabilities.json
- internal/cmd/genbuiltinmetadata/main.go
The type was `any<any>` before which is a bit much.
Also removes the "unclassified builtin" exception for "type_name" in the genbuiltinmetadata script.
> ast/builtins: fix 'type_name' type and docs

- runtime/check_user_unix.go
The check specific to macos is also valid on most other Unix-es.
Should fix the build on most other Unix-es.
This was noticed while building `opa` on NetBSD (but probably all non-Linux, non-macos or non-Windows platform are no longer okay since commit 9d4fc06f4d80224ccdab674e37161f46aa4917b7).
> runtime: Treat other Unix-es like macos

- .github/workflows/nightly.yaml
- .trivyignore
1. only check the edge-static image
There are a bunch of libc-related findings that are hard to address, and
likely not relevant for us: for example, Go will not use glibc's regexp
engine, even if linked against libc.
2. pull the image before checking it
I've noticed locally that `trivy image` will just use whatever image it
finds under the mentioned tag. So we pull first to ensure that we actually
scan the right 'edge' image.
3. split jobs
Before, the scan-repo step wouldn't ever happen if scan-image failed. Let's
do them both all the time instead.
4. for the repo scan, ignore go.mod files of the dependencies -- there's little
we can do about, say, grpc referencing a vulnerable yaml.v2 dep in its
go.mod. And there should also be little harm in it, since we're using a more
recent version …
> ci(nightly): various trivy-related tweaks

- ast/compile.go
- ast/compile_test.go
The included change resetting `c.sorted` in `(*Compiler).Compile(...)` was
necessary to test the repeated compilation without a panic.
Fixes #4910.
> ast/compiler: allow retaining parsed modules

- rego/rego.go
- topdown/copypropagation/copypropagation.go
- topdown/query.go
- topdown/topdown_partial_test.go
Before, a query of
input.a == input.a
would not survive copy-propagation.
With this change, it'll be recorded as removedEq, and subsequent processing
steps ensure that it's kept in the body.`
Fixes #4848.
--------
TODO:
> topdown/copypropagation: keep refs into livevars

- docs/content/rest-api.md
> docs: Add note about counter_server_query_cache_hit metric

- bundle/store.go
- bundle/store_test.go
- storage/disk/disk.go
- storage/disk/txn.go
- storage/inmem/inmem.go
- storage/interface.go
If OPA has an activated bundle that owns all roots
and a new bundle with empty roots is to be activated, the
old bundle's data should first be erased from the store.
Currently both the old and new data is kept in the store.
This commit attempts to fix this by providing an indication to
the truncate call about the scenario in which the root is to be
overwritten.
Fixes: #4940
> Clean old bundle data before new activation

- docs/content/_index.md
- docs/content/policy-language.md
- docs/content/policy-reference.md
While the information may have been there before, it's not been obvious enough.
This should change that.
> docs: add warning about importing 'future.keywords'

- test/cases/testdata/reachable/test-reachable-0326.yaml
- test/cases/testdata/reachable/test-reachable-0328.yaml
- test/cases/testdata/reachable/test-reachable-paths-0422.yaml
- topdown/reachable.go
- wasm/src/graphs.c
- wasm/tests/test.c
This PR adds operand type checks for the `graph.reachable` and `graph.reachable_paths` builtins, so that they will consistently return builtin errors about wrong types for *both* arguments.
Previous behavior was inconsistent about when errors would be returned, if at all.
Fixes #4951.
> topdown/reachable: Fix missing operand type checks.

- docs/devel/RELEASE.md
While cutting the last release, I ran into two issues while going through the instructions:
- I hadn't set up an SSH key when I started the process, so the first step failed for me.
- The release notes don't explicitly spell out the modern fork+feature-branch workflow we use.
This PR updates the `RELEASE.md` document to address both of those issues directly for the relevant steps.
> docs: Update release procedure with branch/fork workflow.

- docs/content/management-status.md
- download/download.go
- download/download_test.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/bundle/status.go
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
OPA has support for Delta Bundles. The status object already
contains valuable information such as last activation timestamp
and the type e.g., snapshot vs delta.
This change updates the bundle.Status object to include the
bundle size. This can be useful for status endpoints to differentiate
between the sizes of snapshot vs delta bundles.
Issue: 4477
Signed-off-by: Bryan Fulton <bryan@styra.com>
> bundle/status: Include bundle size in status information

- test/cases/testdata/units/test-units-precision.yaml
- topdown/parse_units.go
This commit cleans up the output of `units.parse` for integer values. Previously, all of them would have 10 places past the decimal, regardless of whether that much precision was actually needed.
Example of bad behavior:
```
opa eval -f raw 'units.parse("1G")'
1000000000.0000000000
```
Behavior change from this PR:
```
opa eval -f raw 'units.parse("1G")'
1000000000
```
Thanks @anderseknert for reporting this one!
> topdown/units_parse: Avoid extra decimal places for integers.

- ast/term.go
- ast/term_bench_test.go
- ast/term_test.go
This PR introduces _lazy key slice sorting_ for the Set datatype, similar to what was done in #4830 (Object Insertion Rework). After this change, `Set.Add()` will be an O(1) operation, and sorting of the Set type's key slice will be delayed until just-before-use, identically to how lazy key slice sorting is done for the Object type.
This will move the sorting overhead from construction-time for Sets over to eval-time, allowing much more efficient construction and use of enormous (500k+ item) Sets. In small-scale tests, this appears to be a performance-neutral change overall, while dramatically improving performance for the "large set" edge case.
This PR also introduces a 2x new benchmarks for Sets, to keep parity with what we introduced for Objects:
- `BenchmarkSetCreationAndLookup` …
> Set Insertion Rework

- bundle/store_test.go
- storage/disk/disk.go
- storage/disk/disk_test.go
Currently we backup the disk store and apply new bundle policy
and data on the new store. Since truncate is called within
a transaction, any uncommited changes on the store will not
be seen during the backup. For example, if the old bundle
data was erased prior to activating a new bundle, this change
would still be uncommited when the backup is done and as a
result both the old and new data would exist in the store.
To avoid this, we now backup the current store, then commit any
in-flight transactions on the current store and store the
current bundle on the store. The backup can be used if we need
to restore to the orignal store version in case we need to
abort the transaction.
Fixes: #4900
> storage/disk: Handle in-flight txn during truncate 

- ast/term.go
- ast/term_test.go
This PR fixes a race condition around keys slice sorting for Sets and Objects, using a `sync.Once` to ensure that the sorting operation only occurs _at most once_ between successive insertion operations.
The race condition could be readily triggered by using iteration methods, such as `.Iter()` or `.Foreach()`, on a Set/Object across multiple goroutines. The goroutines would race one another to sort the keys slice before iterating, with unfortunate results. Tests are included with this PR to exercise these problematic cases.
Benchmarks are encouraging, and suggest that the `sync.Once` guards have minimal effects on performance; mostly increasing variance in ns / op statistics by a few ns between runs.
> Fix multiple-reader race condition for Sets/Objects

- .github/workflows/pull-request.yaml
This is a first step into running less things all the time that don't need to
be run all the time.
It's a heuristic, and as such fallible: there could always be changes that
break something in the wasm code path, because I have forgotten that there's a
dependency of some sort.
Removing the quick-fuzz target, it's never brought any issues up; and still
runs in nightly tests.
> ci: remove quick-fuzz, guard wasm tests on changed files, limit concurrency

- topdown/exported_test.go
🧹 just a cleanup I had forgotten about when bumping the golang version.
> topdown/exported_tests: remove golang 1.16 x509 exception

- test/e2e/certrefresh/certrefresh_test.go
This PR adds a `(*File).Sync` to the `copy()` function in the test. This *should* eliminate slow disk writes as a potential failure cause for the certificate rotation test.
The certificate rotation test has been one of the two flakiest tests in the test suite for a good while now, so if this fixes the issue, we'll have ~40-50% fewer spurious test failures in CI.
> test/e2e/certrefresh: Add file.Sync() to eliminate slow write failures.

- docs/content/policy-language.md
Explicitly document and show that function overloading is unsupported
in order to reduce user confusion.
PR created in response to user feedback that is confusing to search
for Rego function overloading and find only a github issue discussing
obscure OPA internals.
Signed-off-by: Eric Kao <eric@styra.com>
> Document that function overloading is unsupported

- cmd/build.go
- cmd/build_test.go
- compile/compile.go
- compile/compile_test.go
With `.WithPruneUnused(true)`, the compiler (of the compile package) no longer
collects dependents of its entrypoints.
The resulting bundle, if used with the wasm target, will no longer be
semantically equivalent to the bundle built with the rego target.
Since we're unable to have entrypoints for functions, this allows building
modules that we couldn't build before.
Fixes #5035.
> cmd/build+compile: allow opt-out of dependents gathering

- docs/content/configuration.md
This PR fixes three issues with the AWS Signature section in the Configuration doc:
* Update broken link to the AWS EKS IAM Roles for Service Accounts doc (fixes https://github.com/open-policy-agent/opa/issues/5048)
* Move displaced note on service array/object definition to the Services section. Appears to have been displaced when AWS Signature section was added in https://github.com/open-policy-agent/opa/pull/1425
* Fix the formatting of a note under the Using EC2 Metadata Credentials section
> docs: Fix AWS Signature section in Configuration docs

- cmd/bench.go
This PR fixes the dreaded `err="listen tcp 127.0.0.1:18181: bind: address already in use"` errors that have cropped up in the `cmd` tests from time to time. The underlying cause was a function named `benchE2E()` that created a runtime instance bound to port 18181, but had no logic to handle multiple test goroutines trying to bind that address at the same time.
This commit fixes the port collision issue by having the `benchE2E()` function attempt to naively bind a port in a loop, starting at 18181, and incrementing the port number on each " bind: address already in use" failure, until it eventually finds an open port. 
This is an admittedly ugly solution, but it should result in correct behavior: no more "bind: address already in use" errors! :sweat_smile:
> cmd/bench: Fix port collision in utility function.

- build/docs-build-needed.sh
`main` on netlify is a really old branch, and we have no way to update it.
So instead, we'll use what netlify intended: cached vs latest ref. Let's see
if we run into problems.
Concretely, it'll mean that if a PR updates parts of the website in one commit,
netlify will build the PR branch. If a subsequent commit to that PR branch does
not change anything in the website as it was in the previously built commit, no
build will happen. This could be confusing, it also makes sense: it was already
built, why build it again?
Also adds the build/ folder to the list of watched files: much of the docs
generation logic lives there.
---
ℹ️ Nothing should change for merged commits: they had been using this ref before, successfully. Only PR branch builds are different now: they should rebuild …
> netlify: add debug output from 'ignore' script, simplify diff logic, include output

- cmd/exec.go
- cmd/internal/exec/exec.go
- cmd/run.go
- cmd/run_test.go
- docs/content/cli.md
- internal/logging/logging.go
- runtime/runtime.go
let user to configure the log's timestamp format by:
* cli argument `log-timestamp-format`
* environment variable `OPA_LOG_TIMESTAMP_FORMAT`
Closes #2413
Signed-off-by: Sergey Vilgelm <sergey@vilgelm.com>
> Configure log timestamp format

- ast/compile.go
- ast/compile_test.go
Before, we would have run all other "after" stages and ONE MORE ordinary
compiler stage before noticing that we had failed.
The oracle logic depends on a sentinel error, and without this fix, it would
run one compiler stage too much.
> ast/compile: return if an "after" stage failed

- wasm/tests/test.c
This commit fixes an issue around the WASM C tests breaking due to not getting updated during recent changes to the `is_type` builtin functions.
Surprisingly, this issue only came up locally when I ran `make test`, and apparently has not come up in CI at all.
> wasm/tests/test: Fix broken WASM C tests for is_type builtins.

- .github/workflows/pull-request.yaml
- wasm/Makefile
It had slipped my mind that those need docker, too. Previously, I've disabled
docker for those tests to avoid having them rebuild their wasm artifacts.
> ci: re-enable wasm lib tests

- ast/builtins.go
- capabilities.json
- features/wasm/wasm.go
- internal/rego/opa/options.go
- internal/wasm/sdk/internal/wasm/bindings.go
- internal/wasm/sdk/internal/wasm/pool_test.go
- internal/wasm/sdk/internal/wasm/vm.go
- internal/wasm/sdk/opa/opa.go
- rego/rego.go
- rego/rego_test.go
- topdown/builtins.go
- topdown/builtins/builtins.go
- topdown/eval.go
- topdown/http.go
- topdown/query.go
This PR implements support for caching the results of non-deterministic builtins for more complete Decision Logging support. Currently, only the `rego` module and its direct dependents have received the plumbing work this feature requires.
The NDBuiltinCache is ~just a `builtins.Cache`~ a custom 2-level map, modeled off of `builtins.Cache`, which is carefully propagated downwards into the `topdown.BuiltinContext` from the query/eval context. This allows non-deterministic builtins to trivially add cache entries during evaluation, which can later be recovered by higher-level library users.
Rough Usage Example (derived from the tests):
```go
// Set up the NDBuiltinCache, and insert some arbitrary data.
ndBC := builtins.NDBCache{}
ndBC.Put("experiment", 5, 3)
// Run a Rego query.
ctx := …
```
> Support Caching Output of Non-Deterministic Builtins

- bundle/store.go
- bundle/store_test.go
The raw bytes on the bundle object are only set if the bundle
contains any policy or data. So while activating a bundle w/o
policy or data in lazy mode we check if the raw bytes are set
and generate an error if not. This check would prevent valid
bundles from being activated if they contained no policy/data.
> bundle: Remove raw bytes check for lazy bundle loading mode

- build/policy/files.rego
- build/policy/files_test.rego
Something to hopefully help understand what goes wrong in https://github.com/open-policy-agent/opa/pull/5069
> cicd: dump response on http.send failure

- rego/rego.go
- rego/rego_test.go
- topdown/eval.go
This commit fixes the construction process for keys used to look up
entries in the non-deterministic builtins cache. The original cache
lookup process could use refs that were not fully-grounded, and this
meant that calling a builtin twice with differing parameters could
appear identical to the cache if they involved refs as parameters.
We now use fully-grounded terms for the cache keys during insertion/lookup,
meaning that non-deterministic builtin calls with different parameters
are now guaranteed to result in unique cache entries, even if hidden
behind a ref.
This commit also fixes a bug that prevented the NDBCache from being opt-in.
> topdown/eval: Fix key construction for NDBCache.

- rego/rego_test.go
> rego/rego_test: test with test server, not httpbin.org

- ast/builtins.go
- builtin_metadata.json
- compile/compile.go
- compile/compile_test.go
> opa build -t wasm|plan: fail on unmatched entrypoints

- ast/compile.go
- ast/compile_test.go
- rego/rego_test.go
The changes are necessary for both the Compiler and the QueryCompiler. Tests have been added to ensure that the code path through the rego package has also been fixed.
Fixes CVE-2022-36085.
> ast/compile: respect unsafeBuiltinMap for 'with' replacements

- CHANGELOG.md
- Makefile
- build/changelog.py
- builtin_metadata.json
- capabilities/v0.44.0.json
- version/version.go
Note: This release commit rolls in a small fix for the build/release tooling: an upgrade for the changelog-generator script from Python 2 -> Python 3. The script can now handle unicode in commit messages without breaking.
> Prepare v0.44.0 release

- Makefile
- build/get-build-commit.sh
- build/get-build-timestamp.sh
- version/version_go1.18.go
Two small moving parts less. The commit will now be included unabbreviated, but I think that's OK.
Edit: I had been misreading the stdlib docs, the VCS-related info is only available with go 1.18+. So, put that logic into a build-flag-file.
ℹ️ We're still running `make build` in Go 1.17 and 1.18 to ensure compatibility, but those binaries are not published. It is thus not that important that they have the correct VCS info in them.
> version: use runtime/debug.BuildInfo

- .trivyignore
```
$ trivy fs  --format table --exit-code  1 --ignore-unfixed --vuln-type  os,library --severity  CRITICAL,HIGH --skip-dirs vendor/ . --security-checks vuln
2022-09-09T14:13:05.483+0200	INFO	Vulnerability scanning is enabled
2022-09-09T14:13:05.598+0200	INFO	Number of language-specific files: 5
2022-09-09T14:13:05.598+0200	INFO	Detecting npm vulnerabilities...
2022-09-09T14:13:05.602+0200	INFO	Detecting gomod vulnerabilities...
$
```
We should still update, but we shouldn't be rushed by this CVE.
> trivyignore: add wasmtime-go CVE-2022-31169

- topdown/sets_bench_test.go
This PR is an experiment to try to improve performance for the set `intersection` builtin, inspired by work done in #4980 on the set `union` builtin.
The original logic for the builtin did pairwise `Set.Intersection` calls between the input sets, theoretically resulting in some wasted intermediate sets. Ideally, we'd like to minimize wasted allocations, and get a faster and more efficient solution.
> topdown/sets_bench_test: Add `intersection` builtin benchmarks.

- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- rego/rego.go
It's used from ParseBody() (and some of its sibling functions with opts) to
instruct the parser to NOT attempt to parse the token stream as ast.Rule.
Using this, we gain more leeway in dealing with tricky ambiguous cases.
Previously, the queries
set(); {1}
and
set()
{1}
haven't been equivalent, because the latter ended up being parsed as a rule.
Now, we can follow the caller intent: if that input string was parsed with
ParseBody(), we'll return the two expressions, same as is the case when parsing
with the (disambiguating) semicolon. If we have not been given ParserOptions
with SkipRules: true -- i.e., the default behaviour -- then it will be just
like before.
Also adds a panic to NewExpr to ensure we never construct anything unexpected
using it.
> ast: skip rules when parsing a body (or query)

- topdown/object.go
- topdown/object_bench_test.go
- topdown/object_test.go
This PR fixes a performance regression for the `object.union_n` builtin, discovered in issue #4985.
The original logic for the builtin did pairwise `mergeWithOverwrite` calls between the input Objects, resulting in many wasted intermediate result Objects that were almost immediately discarded. The updated builtin uses a new algorithm to do a single pass across the input Objects, respecting the "last assignment wins, with merges" semantics of the original builtin implementation.
In the included benchmarks, this provides a 2x speed and 2-3x memory efficiency improvement over using a pure-Rego comprehension to do the same job, and a 6-30x improvement over the original implementation on all metrics as input Object arrays grow larger.
Fixes #4985
The 3x relevant benchmarks are shown below:
- …
> topdown/object: Rework `object.union_n` to use in-place merge algorithm.

- docs/content/configuration.md
- docs/content/contrib-adding-builtin-functions.md
No quotes can give wrong values. Also fixed minor typo.
Signed-off-by: Anders Holmefjord <andersholmefjord@gmail.com>
> docs: Added quotes so both examples are consistent.

- ast/builtins.go
- topdown/save.go
This commit removes the `IgnoreDuringPartialEval` list in `ast/builtins`, and instead changes the partial evaluator to simply ignore all non-deterministic builtins. This keeps true to the intent of the original list, and reduces the potential for human error in maintenance in the future.
Fixes: #5171
> topdown+builtins: Block all ND builtins from partial eval.

- ast/compile.go
- ast/compile_test.go
- ast/schema.go
- ast/schema_test.go
This adds support for recursive json schemas, such as:
```json
{
"$schema": "https://json-schema.org/draft/2020-12/schema",
"$id": "https://github.com/open-policy-agent/opa/issues/5166",
"type": "object",
"properties": {
"Something": {
"$ref": "#/$defs/X"
}
},
"$defs": {
"X": {
"type": "object",
"properties": {
"Y": {
"$ref": "#/$defs/Y"
}
}
},
"Y": {
"type": "object",
"properties": {
"X": {
"$ref": "#/$defs/X"
}
}
}
}
}
```
The `parseSchema` method now hangs from a `schemaParser` struct. This allows the use of a cache that can be populated with definitions as they are seen, to prevent them being reparsed later. They are added to cache _*before*_ they are completely parsed, otherwise the recursive crash would still occur. Thus they are added to the cache with all properties without …
> fix: Add support for recursive json schema elements to prevent fatal error

- test/cases/testdata/jwtdecodeverify/test-jwtdecodeverify-invalid-exp-type.yaml
- test/cases/testdata/jwtdecodeverify/test-jwtdecodeverify-invalid-nbf-type.yaml
- topdown/tokens.go
topdown: In builtin jwt_decode_verify, assert that exp and nbf are number if present
Spec allows exp and nbf to be missing, but if they are present, they must be of type "number." Before this change, JWTs that violated this would result in OPA panic. Added assertion on expected type. Added test case for each.
Signed-off-by: Charlie Flowers <cflowers@gmail.com>
> topdown: In builtin jwt_decode_verify, assert that exp and nbf are number

- docs/content/annotations.md
Added Rego subheading to the annotations documentation section and added an example of using annotations, then below that a link to the Rego policy reference.
This is for #4937
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>
> Updated Annotations with new Rego subheading and example

- ast/builtins.go
- docs/content/extensions.md
- rego/example_test.go
- rego/rego.go
- topdown/save.go
This commit is a followup to the work done in PR #5172, and partially reverts the changes there to avoid breaking library users of OPA.
The fix restores the `IgnoreDuringPartialEval` list while still ensuring that non-deterministic builtins are not run during partial evaluation.
The docs example of creating a new non-deterministic builtin was also extended to provide context around the `Nondeterministic` field that has been added to the `rego.Function` struct.
> topdown+builtins: Restore legacy `IgnoreDuringPartialEval` list.

- internal/gojsonschema/jsonLoader.go
- internal/gojsonschema/jsonschema_test.go
Fixes a simple race condition in `gojsonschema`.
Note: the test is kind of weird-looking but it's just designed to fail when run with `-race` if concurrent writes aren't protected.
Resolves #5187 
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>
> fix: Fix race condition in gojsonschema

- ast/builtins.go
- builtin_metadata.json
- capabilities.json
- test/cases/testdata/regexreplace/test-regexreplace-0001.yaml
- topdown/regex.go
Fix: https://github.com/open-policy-agent/opa/issues/5162
though I'm not very confident in this part of the codebase, I wanted to raise a small PR to implement the proposal above. Thanks for the reviews in advance :)
> feat: add regex.replace(s, p, v) to builtin
