open-policy-agent/opa

- Makefile
- opalog/opalog.peg
- opalog/parser_ext.go
- opalog/parser_test.go
- opalog/policy.go
- opalog/policy_test.go
- opalog/term.go
- opalog/term_test.go
See the commit message for a description of what's contained in these changes.
These changes do not include:
- Mangling of underscore variables e.g., p :- a.b[_] => p: - a.b[$1]
- Safety checks on recursion, negation, unbound arguments
- Re-ordering of expressions
I felt like this was a good place to pause and review the grammar/parsing before getting into the rest of the compilation.
> Flesh out the grammar

- .gitignore
- Makefile
For now the target fails because there are no tests for the "cmd" package.
Since this is being used manually for now, this is acceptable.
> Add Makefile target to run coverage

- Makefile
- eval/compare.go
- eval/compare_test.go
- eval/storage.go
- eval/storage_test.go
- eval/topdown.go
- eval/topdown_test.go
- opalog/opalog.peg
- opalog/policy.go
- opalog/term.go
See the commit message for what's included and what's not done yet.
I felt like this was a good place to stop and review the current implementation. The missing pieces may trigger some refactoring but hopefully they will be mostly additive.
> Add beginning of top down evaluation

- eval/compare.go
- eval/hashmap.go
- eval/hashmap_test.go
- eval/storage.go
- eval/topdown.go
- eval/topdown_test.go
- eval/tracer.go
- eval/tracer_test.go
- opalog/policy.go
- opalog/term.go
- opalog/term_test.go
> Fleshing out initial top down implementation

- .gitignore
- Makefile
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- ast/rego.peg
- ast/term.go
- ast/term_test.go
- docs/CONCEPTS.md
- docs/DEVELOPMENT.md
- docs/LANGUAGE.md
- eval/hashmap.go
- eval/hashmap_test.go
- eval/index.go
- eval/storage.go
- eval/storage_test.go
- eval/topdown.go
- eval/topdown_test.go
- main.go
- runtime/repl.go
- runtime/repl_test.go
/cc @timothyhinrichs 
Renaming the language to "Rego" and the package to "ast".
> Rename the language to Rego

- README.md
- docs/_config.yml
- docs/about.md
- docs/docs/arch.md
- docs/docs/lang.md
A few of the links in the language reference were broken when switching over
to Jekyll. Also, the table formatting was broken by the switch to redcarpet.
> Fix broken links

- runtime/runtime.go
- runtime/server.go
Previously there was no error message and the exit code was zero; this was
quite confusing.
> Log server error and exit with non-zero status

- ast/compile.go
- ast/compile_test.go
- ast/parser_test.go
- ast/rego.peg
- ast/term.go
- ast/term_test.go
- docs/docs/examples/repl.md
- storage/datastore.go
- topdown/topdown.go
- topdown/topdown_test.go
These changes add support for nested references. See the first commit message for details.
Essentially, instead of writing...
```
q = 1
p :- x = q, data.a[x] = ...
```
You can now just write...
```
q = 1
p :- data.a[q] = ...
```
> Nested References

- ast/compile.go
- ast/compile_test.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/rego.peg
- ast/term.go
- repl/repl.go
- repl/repl_test.go
- runtime/runtime.go
- runtime/server.go
- storage/policystore.go
- topdown/arithmetic.go
This is a small set of changes that improve the error messages mostly reported by the compiler. Specifically, the error messages now include the line/column/file location in the Rego file where the error was encountered.
There are more improvements to be made in the topdown package. I'll get to those in a future PR.
> Improve error messages

- Makefile
- build/cross-compile.sh
This PR just removes the dependency on "gox" for cross-compiling. "go build" makes it very easy to cross compile for other platforms so it's not worth pulling down a dependency here.
> Remove dependency on gox

- ast/builtins.go
- site/documentation/how-do-i-write-policies/index.md
- topdown/builtins.go
- topdown/regex.go
- topdown/strings.go
- topdown/topdown.go
- topdown/topdown_test.go
A couple built-ins to perform basic regex and string manipulation. Encountered the need for these while working on an admission controller prototype in Kubernetes.
> Add regex and string built-ins

- ast/compile.go
- runtime/server.go
- runtime/server_test.go
If the query compile failed while rendering index.html, a panic would occur
because the dummy rule was not initialized with a location value.
Also, added a utility function to compile query strings. This may be useful in
other places.
> Fix panic in index.html error handling

- README.md
- cmd/commands.go
- runtime/server.go
- site/_config.yml
With the site refresh, we have begun referring to services being policy
enabled instead of applications. These changes just update a few spots that
were not touched in the refresh.
> Update OPA "policy enable" tag line

- runtime/server.go
- runtime/server_test.go
Add a query parameter that lets callers control whether result is
pretty-printed or not. This is useful in environments where 'jq' or similar is
not available or inconvenient to use (e.g., when displaying headers and
message body in console.)
> Add pretty flag to Data and Query APIs

- site/_assets/js/collapse.js
- site/_assets/js/dom.js
- site/_assets/stylesheets/style.scss
- site/_config.yml
- site/_includes/footer.html
- site/documentation/how-do-i-write-policies/index.md
This change adds JS and CSS, which automatically collapses all code
blocks on a page above a specified height (currently 320px). The user
can selectively expand code blocks. Collapsed code blocks scroll
internally and independently of the page.
The parameters (for example, the maximum height of a code block
before it will be collapsed) are configurable via the
`OPA_COLLAPSE_CONFIG` object.
> Add expand/collapse to code blocks.

- site/_assets/stylesheets/style.scss
- site/_includes/nav-documentation.html
- site/documentation/references/rest/README.md
- site/documentation/references/rest/example-patch.json
- site/documentation/references/rest/example.json
- site/documentation/references/rest/example1.rego
- site/documentation/references/rest/example2.rego
- site/documentation/references/rest/example3.rego
- site/documentation/references/rest/gen-examples.sh
- site/documentation/references/rest/index.md
The REST API has been manually documented in
site/documentation/references/rest/index.md.
Each of the API endpoints is listed with:
- HTTP method and path
- Query parameters
- Response status codes
- Example request/response transactions
In the future, we could consider modelling the REST APIs using a framework
like Swagger, however, at this point in time, the existing Go-based solutions
either (1) require implementing the entire API inside of another framework
(e.g., go-restful) or (2) lack sufficient support for comment-based
annotations (e.g., go-swagger).
For now, given the relatively small size of the API, it should be OK to
manually update the docs as the API evolves.
> Add REST API documentation

- site/_assets/stylesheets/style.scss
Changes to the generic `<ol>` and `<ul>` styling ended up pushing the “Open Policy Agent” link in the main navigation 60 pixels to the right. This change aligns it to the left edge of the rest of the content.
> Fix OPA home link alignment.

- ast/term.go
- repl/repl.go
- runtime/server.go
- runtime/server_test.go
Also, add helper function to check if a variable is a wildcard (instead of
relying on strings.HasPrefix everywhere).
Rename self reference on Var functions to "v" which is more idiomatic.
> Fix server to exclude wildcard variable bindings

- repl/repl.go
- topdown/topdown.go
- topdown/topdown_test.go
If the expression consists of a single ref to a base doc, the ref must be
looked up before the "truth check" to determine if evaluation continues.
In 34b1c86 we modified the evaluation behaviour to continue as long as
the term is not Boolean(false). In doing so, we forgot to handle the case
where a reference refers to a "false" value in storage.
This is confusing in cases where you have some reference to a flag on an
object, e.g., "..., data.servers[i].interfaces[j].enabled, ...".
This problem does not arise with references to virtual docs because the
reference would be bound in the context.
With this change, the REPL had to be updated, otherwise we would not display
"false" values when evaluating a non-ground reference. E.g., given data = {"x":
[false,true]}, data.x[i] should print …
> Fix expression evaluation for refs to base docs

- topdown/aggregates.go
- topdown/arithmetic.go
- topdown/casts.go
- topdown/strings.go
- topdown/topdown_test.go
Previously, built-ins were not hanlding references in output positions
properly. Specifically, they were just calling Equals() on the term in the
output position against the built-in function result. The Equals() call would
return false and evaluation would stop.
Now, the built-ins just call the unify function which handles references
correctly and will also work in cases where a composite value (potentially
containing variables and/or references) is given in the output position.
> Fix built-in output handling for base doc refs

- repl/example_test.go
- repl/repl.go
- repl/repl_test.go
- runtime/runtime.go
Other projects that embed OPA and use the REPL will probably not set the OPA
build version, timestamp, etc.   Give projects embedding the REPL control over
what is printed.
> Make REPL banner configurable

- ast/term.go
- ast/term_test.go
- repl/example_test.go
- repl/repl.go
- repl/repl_test.go
- runtime/runtime.go
- server/server.go
- server/server_test.go
- storage/datastore.go
- storage/datastore_test.go
- storage/dump.go
- storage/index.go
- storage/index_test.go
- storage/interface.go
- storage/storage.go
- storage/storage_test.go
- storage/transaction.go
- storage/trigger.go
- test/scheduler/scheduler_bench_test.go
- test/scheduler/scheduler_test.go
- topdown/eq.go
- topdown/example_test.go
- topdown/topdown.go
- topdown/topdown_test.go
- topdown/tracer_test.go
The commit message summarizes the changes. The main addition is the Storage object to represent the storage layer and integration of the Storage object with the topdown package.
There are still a few TODOs but this is a good place to review and I think it can be merged as is.
Still TODO:
1. Implement transaction management. This will just be done with simple locking for now. We can do something more sophisticated in the future if it's warranted.
1. Refactor reference evaluation to avoid unnecessary reads against mounted stores when attempting to determine if reference refers to a virtual document. 
1. Implement analysis to determine the documents in use for a given query. The result of the query analysis (i.e., document hints) can be provided to storage backends so they can prepare for …
> Initial support for pluggable storage backends

- Makefile
- ast/compile.go
- ast/compile_test.go
- ast/policy.go
- ast/term.go
- ast/term_test.go
- repl/repl.go
- runtime/runtime_test.go
- server/server.go
- server/server_test.go
- storage/datastore.go
- storage/datastore_test.go
- storage/errors.go
- storage/policystore.go
- storage/policystore_test.go
- test/scheduler/scheduler_bench_test.go
- test/scheduler/scheduler_test.go
- topdown/example_test.go
- topdown/topdown.go
- topdown/topdown_test.go
- topdown/tracer_test.go
- util/test/subtest.go
- util/test/subtest17.go
...again, sorry for the size of this...
The main change is in 8646239a73ef9f7e53a663f25fec32962db84048. It is the improvement to query evaluation to better handle refs. Specifically:
- support iterating over virtual documents.
- support referring to base AND virtual documents with a single ref.
- avoid accessing storage eagerly while evaluating refs.
The other large-ish change here is the removal of rules from built-in store. Previously, topdown would only see rules if they were installed into the built-in store. Now, topdown obtains rules from the compiler. To assist this, there's a new tree data structure (RuleTree) exposed on the compiler. I made this change because (1) topdown will come to depend on compile/analysis-time data structures soon; at that point, rules will be available …
> Improve query evaluation support & misc. improvements

- ast/builtins.go
- ast/parser.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- ast/rego.peg
- ast/term.go
These changes make the ast.Module string representation parse-able.
For example, this means that Go code can write:
```
a := ast.MustParseModule(`
package example
p :- true
`)
b := ast.MustParseModule(a.String())
fmt.Println(a.Equal(b))
#
```
> Parse-able string representations of all AST types

- server/server.go
- server/server_test.go
- site/documentation/references/rest/index.md
The PUT API allows callers to create documents at arbitrary paths. The server
will ensure the path exists (creating ancestors as necessary) before writing
the document to storage.
> Add support for PUT /data/{path}

- server/server.go
- test/scheduler/scheduler_bench_test.go
- test/scheduler/scheduler_test.go
- topdown/example_test.go
- topdown/topdown.go
- topdown/topdown_test.go
- topdown/tracer_test.go
Before, each topdown.Query call opened a new transaction. This was a bit too
simplistic. In some cases, callers may want to execute multiple topdown.Query
calls (without relying on topdown.Eval) or perform writes in the same
transaction. The scheduler POC expects the latter.
> Update QueryParams to include Transaction

- runtime/runtime.go
- server/server.go
- server/server_test.go
Previously, the compiler was being created before calling into
http.ListenAndServe. This prevented users from obtaining the server's compiler
on startup.
> Initialize server compiler in New

- ast/compile.go
- server/server.go
- server/server_test.go
The server was using the cached compiler to compile ad-hoc queries. The
problem with this was that an invalid ad-hoc query would invalidate the
cached compiler (thus breaking subsequent use of it).
Since ad-hoc queries do not have to use the cached compiler, simply don't use
it. If ad-hoc queries need to make use of the cached compiler in the future,
we can change the compiler to not invalidate data structures, be immutable,
etc.
> Fix bug in ad-hoc query execution over HTTP

- runtime/logging.go
- runtime/logging_test.go
Callers currently provide globals as query parameters. Because the query
params are often JSON values, they need to be escaped. This results in the
access logs being very noisy.
This change removes the "global" query params from the access logs at
V(2) and pretty prints them on a separate line at V(3).
> Suppress globals in HTTP access logs

- server/server.go
- server/server_test.go
- site/documentation/references/rest/index.md
- site/examples/docker-authorization/index.md
The commit message has the details, but essentially, the {"IsUndefined": true} response included in 404s for GET /data/... is no longer required and is just cruft at this point.
The Docker Authorization Plugin has been made compatible.
> Remove undefined response from API

- ast/term.go
- ast/term_test.go
- topdown/topdown.go
- topdown/topdown_test.go
The cache that was added to the topdown implementation assumed rules
producing objects would always yield hashable/scalar keys. If the key was not
hashable, the cache lookup would cause a panic.
This change updates the topdown implementation to check the type of the object
key that was produced and return an intelligible error message if necessary.
> Fix panic on unhashable key type

- ast/map_test.go
The string representation of ast.ValueMap does not order keys.
> Fix bug in ast.ValueMap String() test

- ast/map_test.go
ast.Object.Equal is sensitive to ordering, so just compare result to both
possibilities.
> Compare strings in value map test

- Makefile
- docs/RELEASE.md
- version/version.go
This will make it easier to version other artifacts (e.g., docker image,
documentation, etc.)
> Move versioning into Makefile

- build/run-perf-regression.sh
The build on Travis CI was succeeding even though the performance regression
was not running due to a bad git command.
> Fix performance regression script

- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/rego.peg
- runtime/runtime.go
As mentioned in the comment, this is a workaround for an issue in the parser.
If the parser does not find a match for any of the rules, it returns a bogus
error location.
> Fix error messages if no parser match found

- ast/compile.go
- ast/compile_test.go
- ast/errors.go
- ast/errors_test.go
- ast/parser_ext.go
- ast/term.go
- server/server.go
- server/server_test.go
Previously, errors returned by the parser and compiler would encode the
location information in the error string. Now, the location information is
structured and can be readily used by consumers.
/cc @timothyhinrichs @mikol
> Include location attribute on ast errors

- ast/compile.go
- ast/compile_test.go
- ast/parser.go
- ast/parser_test.go
- ast/policy.go
- ast/rego.peg
These changes add support for references in the head of rules. This is achieved by rewriting rules that contain references in the head so that the terms from the head are bound to vars in the body. These generated vars replace the original terms in the head.
> Updates to support references in rule heads

- topdown/topdown.go
- topdown/topdown_test.go
This went unnoticed for quite a while. If users dereferenced a set, e.g.,
p[x].foo.bar (where p is a set and foo.bar is the suffix), topdown would
continue and ignore the suffix.
With this change, topdown will now return a type error.
> Fix set dereference bug in topdown

- site/README.md
- site/_assets/stylesheets/style.scss
- site/_includes/nav-documentation.html
- site/documentation/how-do-i-write-policies/index.md
- site/documentation/references/language/index.md
This is intended to be a concise reference for Rego. Details about built-in
functions and the grammar have been moved out of the How Do I Write Policies
document (into the Language Reference document).
Also, update site/README.md with local development steps.
> Add Language Reference document

- ast/parser.go
- docs/DEVELOPMENT.md
Also update docs for dependency management. The last time the vendor directory
was updated, the parser was not regenerated.
> Update generated parser code

- ast/compare.go
- ast/compare_test.go
- ast/compile.go
- ast/compile_test.go
- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- ast/rego.peg
- ast/term.go
- ast/term_test.go
- ast/transform.go
- ast/transform_test.go
- ast/visit.go
- ast/visit_test.go
- site/documentation/how-do-i-write-policies/index.md
- site/documentation/references/language/index.md
- topdown/eq.go
- topdown/ineq.go
- topdown/topdown.go
- topdown/topdown_test.go
These changes add support for set literals. E.g., 
```
> {1,2,3}
[
1,
2,
3
]
```
or 
```
> count(set(), 0)
true
```
The main motivation was to fix the "not implemented" error callers would receive when querying arbitrary locations in the global document that have sets embedded underneath them. For example, users can now simply query for /v1/data and get back *everything* (assuming there are no rules that depend on query inputs!)
> Add support for set literals

- ast/compile.go
- ast/compile_test.go
- ast/policy.go
The recursion check was not catching cases such as:
package ex
p :- data.ex
In this case, data.ex implicitly refers to data.ex.p.
The fix was to update the visitor that builds the rule graph.
> Fix recursion check

- runtime/merge.go
- runtime/merge_test.go
- runtime/runtime.go
Commit messages contain more details. Basically, instead of simply overwriting top-level keys, recursively merge JSON inputs if possible. This makes it easier to deal with namespaced data. For example:
file1.json
```
{
"com": {
"example": {
"servers": [...]
}
}
}
```
file2.json
```
{
"com": {
"example": {
"networks": [...]
}
}
}
```
usage
```
opa run file1.json file2.sjon
OPA 0.1.1-dev (commit 77d0c86, built at 2016-11-04T15:25:58Z)
Run 'help' to see a list of commands.
> data.com.example[k] = _
+------------+
|     k      |
+------------+
| "networks" |
| "servers"  |
+------------+
```
> Improve command-line JSON input handling

- ast/compile.go
- ast/compile_test.go
- ast/example_test.go
- ast/policy.go
- ast/term.go
- repl/repl.go
- repl/repl_test.go
- runtime/runtime.go
- runtime/runtime_test.go
- server/server.go
- storage/example_test.go
- storage/policystore.go
- storage/policystore_test.go
- storage/storage.go
Previously, the compiler would mutate the parsed modules and store them as
output. This made it difficult to reason about the state of modules
constructed programatically in places like the REPL.
This change adds a Copy() function to the AST types that are stored by
reference. This allows the compiler to deep copy the parsed modules before
operating on them. This removes the challenge of reasoning about how the
compiler will behave when compiling the same input multiple times.
Various callers had to be modified to deal with the new calling convention.
Unit tests have been added to verify the new behaviour.
Fixes #158
> Deep copy modules in compiler

- topdown/topdown.go
- topdown/topdown_test.go
This change addresses two issues with evaluation of refs to set literals:
1) If the set or lookup value contained references, they were not being
resolved before checking for membership. So for example,
{data.a[0]}.contains("a") would fail even if data.a[0] = "a". This is solved
by simply resolving all references in the set and lookup value before
performing the membership check.
2) Set literals embedded inside other collections were not being evaluated.
For example, [{"a", "b"}] = x, x[0]["a"] would be false. This solved by
refactoring the branch that handles sets to behave more closely to the ones
for arrays and objects.
Fixes #149
> Fix evaluation of refs to set literals

- topdown/topdown.go
- topdown/topdown_test.go
If refs have intersecting vars, the bindings produced by the index and the
evaluation of the non-indexed term may conflict. In this case, evaluation
should not continue as it means the variable did not unify.
Also, refactored check performed to determine if indexing can be used.
Fixes #153
> Fix indexing usage for refs with intersecting vars

- ast/compile.go
- ast/compile_test.go
- ast/errors.go
- ast/example_test.go
- ast/parser_ext.go
- ast/policy.go
- repl/repl.go
- repl/repl_test.go
- server/server.go
- topdown/example_test.go
- topdown/explain/explain_test.go
These changes are mostly refactoring with the goal of fixing the "data" query in the REPL. The main change is the introduction of a separate interface (`ast.QueryCompiler`) to compile ad-hoc queries.
The `ast.QueryCompiler` can be obtained from an instance of an `ast.Compiler`.
This avoids the need to construct fake modules/rules in order to compile ad-hoc queries and also avoids the need to re-compile every module each time an ad-hoc query has to be compiled.
Fixes #150
> Fix "data" query in REPL and refactor query compilation

- ast/policy.go
- repl/repl.go
- repl/repl_test.go
New REPL help output looks like this:
```
(dev)torin:~/go/src/github.com/open-policy-agent/opa$ ./opa_darwin_amd64 run
OPA 0.2.2-dev (commit e83a083, built at 2016-11-25T01:40:36Z)
Run 'help' to see a list of commands.
> help
Examples
========
> data               # show all documents
> data[x] = _        # show all top level keys
> data.repl.version  # drill into specific document
Commands
========
<stmt> : evaluate the statement
package <term> : change active package
import <term> : add import to active module
show : show active module definition
unset <var> : undefine rules in currently active module
json : set output format to JSON
pretty : set output format to pretty
trace : toggle full trace
truth : toggle truth explanation
dump [path] : dump raw data in storage
help : print this …
```
> REPL improvements

- cmd/run.go
- repl/errors.go
- repl/repl.go
- repl/repl_test.go
- runtime/runtime.go
- runtime/runtime_test.go
Can now evaluate queries from the command line, for example:
```
$ opa run -f json -e 'data.repl.version[x] = y'
```
Fixes #152
> Add command line flag to eval, print, and exit

- server/server.go
- server/server_test.go
The server was not correctly checking the return code from the binding
conversion.
Fixes #183
> Fix error handling bug in Query API

- site/examples/docker-authorization/index.md
The search-replace as part of the request changes did not catch "req.Headers"
in valid_user_role.
> Fix docker authorization example

- ast/parser_ext.go
- ast/parser_test.go
With the request document changes, the "request" var in "request = <term>"
is transformed into a ref. As a result, the body to rule conversion was not
working (and returning an error).
Fixes #202
> Fix body to rule conversion bug

- ast/parser_test.go
- ast/policy.go
- server/server.go
- server/server_test.go
- site/documentation/references/rest/index.md
- topdown/request.go
- topdown/request_test.go
Make the ":" in the request parameter value optional. Typical use case will
be for callers to supply the entire request value in one parameter.
Fixes #201
> Improve request parameter handling

- ast/builtins.go
- ast/compile.go
- ast/compile_test.go
- ast/policy.go
- ast/unify.go
- ast/visit.go
- site/documentation/references/language/index.md
The built-in operator names should never have been added to the ReservedVars
set. These changes remove them from the ReservedVars set so they are not
considered global/safe when performing the safety checks.
Fixes #206
> Catch unsafe vars with built-in operator names

- .gitignore
- Dockerfile_release-builder.in
- Makefile
- build/build-release.sh
- build/gen-release-patch.sh
- docs/RELEASE.md
- site/README.md
- Add script to build release artifacts from inside a container. In the past,
release artifacts have been created from a clean checkout, but this should be
much more reliable.
- Add script to generate release patch from tip. In the past, the release
patch changes have been made manually.
> Improve release infrastructure

- runtime/logging.go
- runtime/logging_test.go
- server/server.go
- server/server_test.go
Return an error if the request parameter is empty. This indicates an error in
the caller.
Fixes #212
> Fix empty request parameter parsing

- ast/parser.go
- ast/parser_test.go
- ast/policy_test.go
- ast/rego.peg
- ast/term.go
- ast/term_test.go
- topdown/topdown_test.go
This PR addresses the usability issue of floating point literals that came up recently (e.g., .5 instead of 0.5). At the same time, this identified two issues introduced by the move away from float64 as the underlying number representation.
> Improve support for floating point literals

- ast/parser.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/rego.peg
- ast/strings.go
- repl/repl.go
These changes improve the details of the error messages, catch multiple package directives (which are invalid), and report all parse errors (instead of stopping on the first).
> Improve module parsing errors

- server/server.go
- server/server_test.go
- site/_scripts/rest-examples/gen-examples.sh
- site/documentation/how-does-opa-work/index.md
- site/documentation/references/rest/index.md
This change is not backwards compatible.
The response wrappers encapsulate the result of the operation so that in the
future, additional metadata (e.g., pagination, extents, etc.) can be returned.
> Add response wrappers to the REST APIs

- ast/parser.go
- ast/parser_test.go
- ast/rego.peg
The string parsing we had from the original version of the JSON parser
was incorrect in two ways...
1. It did not handle escaped slash (aka solidus) characters.
2. It did not handle lower-case and upper-case hex digits.
> Fix parsing of escaped strings

- ast/compile.go
- ast/compile_test.go
- ast/errors.go
- ast/example_test.go
- repl/repl.go
- server/server.go
- server/server_test.go
- topdown/input.go
- topdown/topdown.go
- topdown/topdown_test.go
These changes update OPA to analyze queries to determine if an input
document is required. In the future, more sophisticated checks could be
performed (e.g., JSON schema validation).
If an input document is required but not provided, OPA will return HTTP
400 (per the documentation). This was broken in #197.
Fixes #227
> Fix handling of missing input document

- repl/repl.go
- repl/repl_test.go
> Fix input document definition in REPL

- repl/repl_test.go
- site/examples/working-with-the-opa-repl/index.md
- topdown/errors.go
- topdown/topdown.go
- topdown/topdown_test.go
In the past, topdown would bind set[x] to true. This resulted in
confusion when people attempted to write joins with set elements.
With this change, topdown treats sets like objects/arrays, except that
set[x] is bound to x. This allows users to write queries that
dereference sets just like objects and arrays.
Also, fix handling of self-joins where previously a recursive binding
could be added. The "self-join" test case was added to cover this.
Fixes #243
> Allow sets to be treated like objects/arrays

- Makefile
- rego/example_test.go
- rego/rego.go
This PR adds a new top-level package to OPA: "rego". The new package provides a high-level interface for performing query evaluation. The package tries to hide the underlying usage of the ast/storage/topdown packages as much as possible.
A couple open questions:
1) What's the right API for returning results? It would be nice if this interface was future proof for features like pagination. Perhaps chan[result] would work. Perhaps we can find a good example in another project.
2) All errors should include a location. Perhaps we need a top-level errors package that defines the location interface.
> High level API

- cmd/run.go
- runtime/runtime.go
- server/server.go
- server/server_test.go
With this change, OPA will listen for HTTPS connections if the `--tls-private-key-file` and `--tls-cert-file` arguments are given.
This is related to #272
> Add support for server-side HTTPS

- README.md
- runtime/logging.go
- runtime/logging_test.go
The new request logging uses httputil.DumpRequest which is much cleaner
than the old approach of trying to extract values from the request.
Also, the new approach adds a unique id on each line for correlation.
Also, move slack link around.
Fixes #281
> Improve request logging

- .travis.yml
- Makefile
- build/travis-utils.sh
Only re-tag on releases. Latest development build can still be gotten with the `:<version>-dev` tag.
> Update docker 'latest' tagging

- server/server.go
- server/server_test.go
- server/types/types.go
- site/_scripts/rest-examples/example1.rego
- site/_scripts/rest-examples/example2.rego
- site/_scripts/rest-examples/example3.rego
- site/_scripts/rest-examples/example4.rego
- site/_scripts/rest-examples/gen-examples.sh
- site/documentation/references/deployments/index.md
- site/documentation/references/rest/index.md
As part of this change, the /policies/{id}/raw API has been removed in
favour of a "source" query parameter. When GET
/policies/{id}?source=true is received, the server returns the
raw/source of the policy.
Also, cleaned up handling of boolean query params.
Fixes #292
> Allow slash in policy id/path

- site/_includes/nav-main.html
These navigation links were not being set deterministically before. With
this change, they should always point to the introductory material.
> Fix top-level navigation links

- topdown/topdown_bench_test.go
The existing benchmarks exercise data scale; another dimension to
investigate is the size of policies/number of virtual docs.
> Add virtual document evaluation benchmark

- Makefile
- ast/builtins.go
- ast/builtins_test.go
- ast/check.go
- ast/check_test.go
- ast/compile.go
- ast/compile_test.go
- ast/env.go
- ast/errors.go
- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- ast/term.go
- ast/term_test.go
- ast/visit.go
- repl/repl.go
- repl/repl_test.go
- topdown/example_test.go
- topdown/explain/explain.go
- topdown/topdown_test.go
- types/types.go
- types/types_test.go
- util/graph.go
- util/graph_test.go
- util/queue.go
- util/queue_test.go
These changes add basic support for type inference and type checking.
Type inference covers queries (i.e., terms/vars inside queries) as well as virtual docs. Type information for base docs is not available yet--and type checking treats base docs as having "any" type.
Type inference and checking are performed in one pass. The output of the type checking phase is a type environment that contains all relevant type information (for the query or rule set).
Type inference and checking for virtual docs is performed bottom-up after topologically sorting the rules. In the future, we could investigate relaxing this so that type errors/conflicts in base documents could be detected.
Currently, type checking handles the following:
1) Built-in arguments
2) Reference arguments
> Initial type checking implementation

- ast/compile.go
- ast/compile_test.go
- ast/index.go
- ast/index_test.go
- ast/policy.go
- ast/term.go
- ast/term_test.go
- repl/repl_test.go
- server/authorizer/authorizer_test.go
- server/server_test.go
- topdown/topdown.go
- topdown/topdown_bench_test.go
- topdown/topdown_test.go
These changes add a simple rule indexing implementation to OPA. In the future, we can add more sophisticated strategies and perform analysis on queries to determine which indices ought to be used.
The first indexing strategy supports expressions of form eq(ref, term) (or vice versa) where ref is a ground, non-nested reference to a base document (input or data) and term is scalar, non-nested array, or var. The implementation builds a trie from the expressions in rule sets that match this pattern. The trie shrinks the search space required at evaluation time.
> Add simple rule indexing implementation

- Makefile
- metrics/metrics.go
- metrics/metrics_test.go
- rego/rego.go
- server/server.go
- server/server_test.go
- server/types/types.go
- site/documentation/references/rest/index.md
- topdown/topdown.go
This is a relatively simple change that adds some basic performance metrics to OPA. The metrics can be requested when making an API call. The collected values are returned alongside the response result.
Eventually, we'll want to have metrics collection available out-of-band. We can add that later.
Closes #271
> Add basic performance metric collection

- ast/parser_ext.go
ParseTerm should have been checking if body was exactly size 1. This was
allowing the form in index.html to trigger a panic if the input field
was empty.
> Fix bug in ast.ParseTerm

- site/tutorials/http-api-authorization/index.md
- site/tutorials/working-with-the-opa-repl/index.md
Depends on https://github.com/open-policy-agent/contrib/pull/19 having its docker image pushed. Also requires a release of OPA that has `io.jwt.decode`.
> Add tutorial for doing API authorization with JWTs

- ast/compile.go
- ast/compile_test.go
- ast/parser.go
- ast/parser_ext.go
- ast/rego.peg
- ast/term.go
- ast/visit.go
- ast/visit_test.go
See commits for details. In addition to fixing the term locations, these changes update the AST walker to provide the Term object (which was being skipped before.)
> Fix term locations

- cmd/fmt.go
If the provided file name does not exist, `opa fmt` would panic
due to filepath.Walk passing in a nil `os.FileInfo`. The WalkFunc
now checks the incoming error properly to catch this case.
> Correct `opa fmt` panic on missing files

- rego/rego.go
- rego/rego_test.go
- topdown/cancel.go
- topdown/errors.go
- topdown/topdown.go
- topdown/topdown_test.go
These changes add a custom query cancellation mechanism to topdown which
allows callers to terminate in-progress queries that taking too long.
> Add support for query cancellation

- Makefile
- build/build-release.sh
When release script was updated as part of the site refresh, the changes
broke the RELEASE.md steps.
> Fix release script to expect version not tag

- ast/parser.go
- ast/parser_test.go
- ast/rego.peg
The grammar definition was ambigious to whether a lone Set Comprehension
was a Set Comprehension at all, instead parsing it as a Body. An example
is:
`{k | a = [1, 2, 3]; a[k]}`
The parser would interpret this as a Body with the expressions
`[1, 2, 3] = k | a` and `a[k]`, which is not the intended result. To
resolve this, the parser now prioritizes `NonWhitespaceBody`s over
`BraceEnclosedBody`s in order to parse Set Comprehensions passed to
the REPL or as queries properly.
Fixes #377
Co-Authored-By: Torin Sandall <torinsandall@gmail.com>
> Correct ambiguous syntax around Body and Set Comprehensions

- ast/check.go
- ast/check_test.go
- ast/compile.go
Since language builtins never change, they can be inserted into the
TypeEnv before any compilation takes place.
> Insert language builtins into the TypeEnv on compiler creation

- ast/parser.go
- ast/parser_test.go
- ast/rego.peg
- docs/book/how-do-i-write-policies.md
- docs/book/language-reference.md
- topdown/topdown_test.go
This allows for easier construction of regex patterns, as things don't
need to be double escaped.
Fixes #265
> Add support for raw strings

- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
Currently format turns them into properly escaped quoted strings, which maintains correctness, but not desired.
> Update format package to support raw strings

- Makefile
This way when new packages are added, the Makefile does not fall out of
date.
> Refactor Makefile to remove hardcoded PACKAGES

- cmd/fmt.go
When computing diffs, `opa fmt` created temporary files in order to use
the diff utility. However, it did not properly clean up after itself,
leaving these temporary files behind.
> Properly remove temporary files when running `opa fmt -d`

- docs/book/kubernetes-admission-control.md
The ResourceQuota admission controller should run after the webhook so
that quota consumption is consistent.
> Update admission controller flag for best practice

- docs/book/http-api-authorization.md
Before we were using the "latest" tag in the tutorial. This caused an
issue because we thought the JWT token support added to the toy server
had been built and published under the latest tag however it had not.
Since the toy server functionality is somewhat coupled to the tutorial,
hardcoding the version number here is acceptable.
> Fix image version in HTTP API tutorial

- Makefile
- build/gen-dev-patch.sh
- docs/devel/RELEASE.md
This removes some of the manual labour of performing a release. Namely,
in the typical case, the Makefile and CHANGELOG don't have to edited by
hand.
> Add dev-patch target to improve release process

- ast/builtins.go
- docs/book/language-reference.md
- topdown/example_test.go
- topdown/topdown_test.go
- topdown/walk.go
While working on Terraform policies we encountered JSON documents that
can be nested arbitrarily, e.g.:
```
foo:
bar:
baz:
v: 1
qux:
v: 2
corge:
v: 3
```
In the Terraform case, we want to process objects at foo.bar.baz,
foo.bar.qux, and foo.corge, however, we don't know ahead of time what
these paths will be.
To handle this, we add a new built-in function 'walk' that traverses all
documents nested under the input.
> Add walk built-in function

- ast/parser_ext.go
- ast/parser_test.go
- ast/policy.go
- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
- repl/repl.go
- repl/repl_test.go
- topdown/topdown_test.go
These changes allow partial docs to be defined without a body in Rego
source files. Before, the rules would have to include a `{true}` body
for the parser to allow them. Now, the body can be omitted.
Rules defined this way (inside modules) cannot be copy/pasted as-is into
the REPL. This could be addressed by creating a "paste mode" in the REPL
similar to ipython and other interactive shells.
These changes build on https://github.com/open-policy-agent/opa/pull/412
with a few differences:
- Dynamic values are allowed in the head.
- Partial sets are allowed.
Both of these changes are based on personal experience writing policy.
Dynamic values are fine to allow as the compiler will catch unsafe vars
and rewrite the head to handle refs and comprehensions.
> Add support for partial doc shorthand

- docs/book/rest-api.md
- metrics/metrics.go
- server/server.go
- server/server_test.go
- server/types/types.go
These changes update the Policy API responses to:
- Return empty objects for PUT/DELETE with optional support for ?metrics
- Return AST and raw/source for GET
Support for the ?source param has been removed as the raw/source version is now included by default.
> Policy API refactoring

- ast/parser.go
- ast/parser_test.go
- ast/rego.peg
- format/format_test.go
The new version of mna/pigeon fixes the location bug that prevented
accurate line/column numbers from being reported on unmatched input.
In the future we can investigate improvements to the error messages by
adding negative matches that return higher-level errors as long as the
location information is not impacted.
Fixes #214
> Remove panic workaround in parser

- ast/compile.go
- ast/errors.go
- repl/repl.go
- server/server.go
- server/server_test.go
- server/types/types.go
- server/writer/writer.go
In b23cb4e the compiler was changed to allow queries to refer to the
input document without the input document being defined. Those changes
did not remove all of the code associated with input errors.
These changes remove the remaining (dead) code associated with input
errors and also update the server to allow Data API POST requests that
do not specify an input document.
> Remove dead code associated with input doc errors

- ast/parser_ext.go
- ast/parser_test.go
- repl/repl.go
- repl/repl_test.go
These changes refactor the parser extensions that convert bodies into
rules if they can interpreted as such. The cases that can be converted
are clearer now and the test coverage is improved.
Fixes #433
> Fix incorrect REPL interpretation of some exprs

- topdown/eq.go
- topdown/topdown_test.go
The evalEqUnify implementation was not returning undo objects in cases
where it should: if unification failed after binding a var, the binding
was not undone and backtracking would proceed with an incorrect binding.
For this to manifest, a query would likely be iterating and performing
pattern matching on a composite value.
Fixes #436
> Fix unify to return undos in all cases

- ast/check.go
- ast/check_test.go
These changes modify the type checker to run on closures contained in
the expression before the containing expression. This way the type
checker can suppress less specific/actionable match errors in the same
way it does for ref errors.
Fixes #438
> Suppress match errors if closures contained errors

- cmd/check.go
- cmd/errors.go
- cmd/fmt.go
- cmd/run.go
- cmd/test.go
- cmd/version.go
- loader/errors.go
- loader/loader.go
- loader/loader_test.go
- loader/merge.go
- loader/merge_test.go
- runtime/runtime.go
- runtime/runtime_test.go
- tester/reporter.go
- tester/reporter_test.go
- tester/runner.go
- tester/runner_test.go
- util/test/doc.go
- util/test/tempfs.go
Most of these changes are refactoring. The actual `opa test` sub-command bits are in the last commit (82e22ba).
> Add support for policy tests

- docs/book/how-do-i-write-policies.md
Apparently we missed one instance of the hold comma-based syntax when we
moved over to semicolons.
> Fix syntax error in comprehension example

- Dockerfile_alpine.in
- Makefile
In some cases, users will want to obtain a shell inside the container
running OPA. Currently, we need a way to run opa fmt --diff (which
relies on the diff program) as part of the open-policy-agent/library
build/CI process. This image makes that possible.
> Add alpine-based Docker image

- cmd/fmt.go
Overwriting is not the default and policies are usually stored in a VCS.
As a result, the backup files are not likely to be needed.
> Remove backup creation from fmt subcommand

- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
Do not format strings before writing them to output. String formatting
was only being used for concatenation and caused problems for Rego
strings that contain printf verbs.
> Remove use of sprintf in formatter

- cmd/run.go
- runtime/runtime.go
- runtime/runtime_test.go
Previously, the runtime could only be initialized and started in one
shot. In some cases, callers want to be able to separate these into two
steps, especially since the start call will block.
> Refactor runtime to separate init and start

- runtime/runtime.go
Users embedding the runtime package will need to be able to specify the
decision ID generator function.
> Expose decision ID factory parameter

- build/install-deps.sh
Go now defaults to ~/go so this is no longer required.
> Remove GOPATH warning from build scripts

- cmd/test.go
- tester/runner.go
- tester/runner_test.go
This allows testers to provide input data in raw JSON/YAML files as
opposed to copying them into Rego files.
> Refactor test runner to accept Store argument

- ast/parser_ext.go
- ast/parser_test.go
Now that the AST walker can visit terms (as well as values) it's better
to just walk all terms in the statement and mangle them (rather than
relying on speical handling for collections of terms, which is bound to
break over time.)
Fixes #480
> Fix wildcard mangling in rule head

- ast/builtins.go
- docs/book/language-reference.md
- topdown/aggregates.go
While I agree with the comment on https://github.com/open-policy-agent/opa/issues/466, it would still be tedious to perform the product of members of an array without a function. Feel free to close if you disagree.
> Add Product to calculate the product of array or set

- design/REGO_V2_PROPOSAL.md
The proposed language changes preserve the expressiveness of Rego,
but add clarity with additional keywords and closer alignment with
syntactic constructs in popular languages.
The proposal also introduces a concept of trigger declarations which
may be used to invoke additional functionality in servicing the policy
the decision.
> Rego v2 proposal

- topdown/topdown.go
- topdown/topdown_test.go
Topdown was trying to use the data index when iterating over modules.
This change modifies how topdown uses the rule tree to determine if the
reference refers to one or more rules.
Fixes #490
> Fix index usage for virtual docs

- ast/compile.go
- ast/compile_test.go
Rule args need to be rewritten just like the key/value terms in the rule
head.
Fixes #497
> Rewrite refs in rule args

- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
Call expressions written with infix notation were being incorrectly
formatted using the logic for arithmetic operations.
> Fix bug in expression formatting

- ast/compile.go
- ast/compile_test.go
The dynamic term rewriting was not copying with modifiers so terms would
be evaluated with the correct input. This was affecting tests in the
library.
> Fix dynamic rewriting to copy with modifiers

- README.md
Pretty self-explanatory. The current README doesn't provide enough info for people landing on GitHub instead of openpolicyagent.org.
> Improve the README with examples and more links

- ast/term.go
- ast/term_test.go
In the past, callers have tried to load JSON data without using
json.Number. These changes should make it easier for callers to supply
native Go values as int64, float64, and int will be converted
automatically. Also, add a case for map[string]string which is used
inside of projects like Istio to represent generic key/value
collections.
Fixes #473
> Improve InterfaceToValue to handle other Go types

- topdown/eval.go
- topdown/topdown_test.go
In #502 the conflict detection for complete docs was broken. E.g., given `default p = 1`, `p = 2`, and `p = 3 { false }`, topdown would yield `p = 2` and `p = 1` (instead of just `p = 2` because the third rule would fail and clear the value of `prev` in the evaluator.
> Fix bug in conflict detection

- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
The formatter was not handling else statements for functions properly.
The function args were being written after the else keyword which
resulted in rules that did not parse.
> Fix formatting of else statements with functions

- docs/book/docker-authorization.md
There is a new version of the plugin available that fixes build issues
with the latest version of the Docker framework. Also, remove
unnecessary section that creates a policy directory (this is a hold over
from when OPA would store policies on disk.)
> Update Docker tutorial version

- ast/check.go
- ast/compare.go
- ast/compile.go
- ast/compile_test.go
- ast/env.go
- ast/index.go
- ast/parser.go
- ast/parser_ext.go
- ast/policy.go
- ast/rego.peg
- ast/term.go
- ast/term_bench_test.go
- ast/term_test.go
- ast/transform.go
- ast/unify.go
- ast/visit.go
- dependencies/deps.go
- format/format.go
- storage/path.go
- topdown/aggregates.go
- topdown/arithmetic.go
- topdown/bindings.go
- topdown/builtins/builtins.go
- topdown/eval.go
- topdown/input.go
- topdown/partial_test.go
- topdown/strings.go
- topdown/topdown_test.go
- topdown/walk.go
Previously sets and objects were simply implemented as lists of terms (or lists of term tuples). Now sets and objects are backed by hash tables to provide constant time lookup.
> Improve AST Set and Object implementations

- docs/book/how-do-i-write-policies.md
For clarity, removed third else clause that was not being exercised in
the examples.
> Tweak else keyword example

- topdown/eval.go
- topdown/topdown_test.go
In the unification refactor, unordered collections were not handled
correctly. As a result, comparisons between sets containing bound vars
was failing (e.g., x=1;y=2;{x}={y}) because OPA was checking for
syntactic equality.
> Fix unification for unordered collections

- runtime/runtime.go
- server/types/types.go
Removing redundant `err != nil` checks detected during `make check`
> Remove lint errors detected during 'make check'

- build/install-deps.sh
If the pigeon dependency is updated, the parser is regenerated and
committed back to the repo. Other developers need to re-install pigeon
whenever this happens (otherwise they will regenerate a stale version of
the parser.)
> Remove guards in deps installer

- repl/repl.go
- repl/repl_test.go
I have not added a specific test case, but altered the existing one
slightly -- hope that's fine.
Fixes #435.
> fix #435: deduplicate paths in completion

- docs/book/language-reference.md
Makes it easier to find the `re_match` builtin.
> Modify Language Reference in Docs

- docs/book/language-reference.md
I'm not sure about the use of _one_ or _two_ backticks there, but I've
tried to make it a little more uniform.
> language-reference: remove superfluous backticks

- rego/rego.go
Update the rego package to NOT start/stop the query evaluation latency
timer. The topdown package does this already--and the duplicate call was
causing higher than expected latency to be reported.
> Fix query evaluation timing in rego package

- rego/example_test.go
- rego/rego.go
- server/server.go
- server/server_test.go
These changes update the Rego package to provide convenient access to the partial evaluation feature added in v0.6.0. The Rego package implicitly treats the input document as unknown. This behaviour can be overridden by the caller explicitly setting the unknowns.
These changes also refactor the server to use the partial evaluation setup from the rego package instead of the initial ad-hoc setup that was implemented directly in the server.
> Add partial evaluation support to Rego package

- ast/check.go
- ast/check_test.go
The type checker was not unioning inferred types when processing
expressions that iterate over heterogenous collections. As a result, the
inferred types did not accurately reflect the data being generated
(e.g., instead of any<string, number> the inferred type would only be
any<number>.)
> Fix type inferencing to handle unioning properly

- ast/builtins.go
- docs/book/language-reference.md
- topdown/builtins.go
- topdown/http.go
- topdown/http_test.go
Added a new builtin to execute HTTP requests.
The builtin **http.send** executes a HTTP request and returns the response. For example, http.send({"method": "get", "url": "http://www.openpolicyagent.org/"}, output). output is an object containing keys status, status_code and body which represent the HTTP status, status code and response body respectively. Sample output, {"status": "200 OK", "status_code": 200, "body": null}
Addresses  issue https://github.com/open-policy-agent/opa/issues/510
> Http built in

- ast/builtins.go
- docs/book/language-reference.md
- topdown/sets.go
- topdown/sets_test.go
The builtin performs set union and intersection for the given input sets.
Ex1:  `x = {{1,2,3,4},{2,3,4}, {1,2,3}}`
`intersection(x, output)`
output => {2, 3}
Ex2: ` x = {{1,2,3,4},{2,3,4}, {1,2,3}}`
`union(x, output)`
output => {1, 2, 3, 4}
> added builtin for n-way set union and intersection

- ast/compile.go
- ast/compile_test.go
Expression term rewriting was not copying the with modifier to expanded
expressions which led to non-obvious evaluation results.
> Fix expr term rewriting to include with modifiers

- ast/compile.go
- ast/compile_test.go
Previously the rewriting step was not walking the comprehension head. As
a result, vars embedded inside composites were not rewritten. This
change updates the rewriting to use a visitor to resolve the issue.
> Handle local vars in composite head better

- ast/compile.go
- ast/compile_test.go
- ast/visit.go
Previously, vars in function args were resolved like other vars in the
head. In most cases though, authors expect function args to shadow
globals. As a result, the old behaviour lead to unexpected results when
functions with resolved args were called.
> Update resolving to skip function args

- ast/compile.go
- ast/compile_test.go
- rego/rego.go
- rego/rego_test.go
Since assigned vars are rewritten, we need to allow callers to lookup
whether a generated var corresponds to a var in the parsed query.
Previously, no generated vars needed to be reported to the callers of
the rego package (and so they are filtered out from the ResultSet). Now,
that generated vars correspond to vars the caller may care about, the
rego package has to map generated vars back to ones the user knows
about.
> Update QueryCompiler to report rewritten vars

- topdown/regex.go
Alias is the same as the package name.
> Remove redundant package alias "gintersect".

- docs/book/language-reference.md
Builtin name is regex.globs_match, and not globs_match.
> Fix bad builtin name globs_match in docs.

- ast/term.go
- ast/term_bench_test.go
We recently encountered an issue where an old version of siphash
(v1.0.0) was vendored along with OPA. The combination of this version of
siphash and use of unsafe.Pointer to obtain a byte slices caused
back-to-back ast#Term.Hash calls to return different values! Ultimately
this lead to incorrect evaluation results.
Previously, we used unsafe.Pointer to improve performance in the
scheduler benchmark. At this point though, reverting to []byte conversion
during hashing does not introduce a noticeable performance regression.
If the extra allocation during hashing becomes a bottleneck in the
future, we can revisit this.
> Remove use of unsafe.Pointer for string hashing

- server/server.go
- server/server_test.go
- topdown/errors.go
- topdown/eval.go
- topdown/topdown_test.go
We were not catching merge failures when combining base and virtual
documents. As a result, a term with a nil value (which is invalid) was
being created and returned.
It's arguable that these kinds of conflicts should be caught when data
or policies are inserted. Alternatively, we should revisit whether
policy decisions should be obtained by querying the same root document
as raw data (e.g., decisions could be namespaced under a separate root
document.)
Fixes #601
> Fix panic due to nil term value

- ast/compile.go
- ast/compile_test.go
- ast/parser_ext.go
- ast/parser_internal.go
- ast/parser_test.go
- ast/policy.go
- ast/strings.go
- ast/term.go
- rego/rego.go
- server/types/types.go
- topdown/aggregates.go
- topdown/arithmetic.go
- topdown/builtins/builtins.go
- topdown/casts.go
- topdown/strings.go
Previously we had constants defined for AST type names. These were used
in error messages in various places. The original goal was to make error
messages consistent, however, this approach made it difficult to locate
the source of the error in code.
> Refactor AST type name strings

- docs/book/kubernetes-admission-control.md
- docs/book/tutorials/kubernetes-admission-control-validation/admission-controller.yaml
- docs/book/tutorials/kubernetes-admission-control-validation/ingress-conflicts.rego
- docs/book/tutorials/kubernetes-admission-control-validation/ingress-whitelist.rego
The v1.9 webhook support contains a bug that causes CONNECT operations
to fail. We can add the privileged exec example back once that's fixed.
Fixes #567
> Update Kubernetes Admission Control tutorial

- server/server.go
- server/server_test.go
- Support for DELETE(ing) /data resources
- Deleting non existing resources returns 404
- Deleting a resources and then GETting it returns 200
with empty body
- GETting resources that were not explicitly deleted before
will return 200OK with body {"result": {}}
- Fixes #609
-
> Delete method support

- repl/repl.go
- repl/repl_test.go
Assignment was not special cased in the REPL before. As a result,
assigned vars would not be available in subsequent expressions.
Fixes #615
> Fix REPL assignment support

- docs/book/kubernetes-admission-control.md
Due to https://github.com/kubernetes/kubernetes/issues/59759, we should
not recommend registering webhooks that match the CONNECT operation as
this can break exec/port-forward functionality.
> Update webhook registration in Kubernetes tutorial

- ast/compile.go
- ast/compile_test.go
This bug was introduced in 051157f. If not output value is specified in
a call expression, the ref outputs are still safe.
Fixes #625
> Fix safety check bug for call args

- ast/compile.go
- ast/compile_test.go
- repl/repl.go
The query compiler was not deep copying queries like the compiler does
for modules. As a result, the parsed query in the REPL was being
recompiled and the rewritten var mapping was not correct. E.g.,
rewritten vars were not be displayed properly.
> Update query compiler to deep copy parsed query

- ast/index.go
- ast/index_test.go
This is a simple change that updates the rule index to support the == operator that was added in v0.7.
> Update rule index to support ==

- ast/builtins.go
- docs/book/language-reference.md
- topdown/crypto.go
- topdown/crypto_test.go
- topdown/encoding.go
- topdown/topdown_test.go
This PR adds an extra pair of base64 encoding functions. The pair currently in OPA works with the URL safe version of the standard.
> Add built-in function to parse X.509 certificates

- topdown/eval.go
- topdown/save.go
- topdown/topdown_partial_test.go
Previously, partial eval was not checking call args recursively for
terms in the save set. As a result, if a call expression passed a term
that had an unknown embedded, the call would be evaluated, which could
potentially result in an internal error.
Fixes #621
> Update partial eval to check call args recursively

- ast/builtins.go
- topdown/eval.go
- topdown/topdown_partial_test.go
Some buillt-in functions should not be partially evaluated because they
are not pure functions (e.g., http.send and time.now_ns are two exampels
we currently have.)
In the future, we may need to add variants of these functions that can
be evaluated during partial evaluation.
Fixes #622
> Ignore some built-in calls during partial eval

- ast/builtins.go
- docs/book/language-reference.md
- topdown/tokens.go
- topdown/topdown_test.go
A builtin to verify RS256 JWT signatures
Issue - https://github.com/open-policy-agent/opa/issues/421
Fixes #421
> Rs256 jwt signature verification

- docs/book/language-reference.md
- topdown/tokens.go
For encoding and decoding the different parts of the JWT use standard base64 encoding.
> Use standard base64 encoding for tokens

- build/gen-release-patch.sh
- docs/book/tutorials/kubernetes-admission-control-validation/admission-controller.yaml
The script was not searching for version numbers in YAML files in the
docs. As a result the Kubernetes admission controller tutorial was out
of date.
> Update release patch script to cover YAML files

- topdown/eval.go
- topdown/topdown_partial_test.go
Previously, partial evaluation would save negated expressions and not
perform any inlining. With these changes, partial evaluation inlines
negated expressions into support rules and rewrites the original
expression to refer to the support rule.
These changes will improve the coverage of partial evaluation which
improves the applicability of rule indexing and other optimizations.
Fixes #623
> Generate support rules for negated expressions

- ast/builtins.go
- docs/book/language-reference.md
- server/types/types.go
- topdown/trace.go
* Check if node is non-nil to prevent panic
* Omit empty message field from API response
* Use native string type for message fields
/cc @jyoverma
> Minor changes to note support

- rego/rego.go
- storage/inmem/inmem.go
- util/json.go
- util/json_test.go
With this, where before we've gotten
ast: illegal value: []string
and had worked around it by converting all our `[]string` inputs to
`[]interface{}`, it now would work to pass in the `[]string` values as-is.
This could be expanded to the other cases (`[]int`, `[]bool`, etc), but I
haven't found a way to do that which does not end up in much duplicated
code.
Decided to ask four y'alls opinion before proceeding. Would you think it's worthwhile to add these cases, or should we just pull ourselves together and keep converting the inputs? 😉
> ast: allow passing in []string, not only []interface{}

- cmd/check.go
- cover/cover.go
This allows tools to consume the output of the check command programmatically.
> Add JSON output format to check command

- ast/term.go
- topdown/casts.go
Apparently, the latter, `strconv.Itoa`, is a little cheaper. Also simplifying some type
re-wrapping in the process -- the outcome should be the same in any
case.
> Replace some fmt.Sprintf("%d", i) by strconv.Itoa(i), remove some double type wrapping

- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
If the rule defines a constant value or is part of an incremental
definition, then the value must not be elided because that would result
in a syntax error or change the meaning of the rule.
> Do not elide rule head value of true in some cases

- topdown/eval.go
- topdown/save.go
- topdown/topdown_partial_test.go
Previously, support rules generated for negated expressions did not
include arguments. Assuming the negated expression did not depend on
unknowns in the calling query this is fine. However, if that's not the
case, then the support rule must be able refer to the unknowns,
otherwise, the partial evaluation result will yield false positives.
The unknowns cannot be pushed down to the support rule via the binding
lists because the bindings do not support references, only vars and
values. To workaround this, we generate support rules that include
arguments which can be used to push the unknwons down.
> Improve partial eval of negated expressions

- topdown/bindings.go
- topdown/topdown_partial_test.go
During partial evaluation, comprehensions were not being plugged before
being returned to callers. If the comprehension closed over a variable
that was not included in the result, the comprehension would become
unsafe.
With this change, comprehensions are plugged before being returned to
callers. This will prevent these variables from becoming unsafe.
In the future, when comprehensions are evaluated during partial
evaluation, this may be unnecessary.
Fixes #656
> Plug comprehensions in partial eval results

- docs/book/rest-api.md
- Added HTTP request snippet
- JSON payload needs to be an array. sprintf requires an array
as second operand.
See server_test.go tests for data/system for reference
> Fixing un-versioned example (data/system)

- docs/book/bundles.md
- runtime/runtime.go
The initial implementation allowed for N bundles to be configured. While
this is more flexible, it introduces unnecessary complexity around
management (e.g., how do you know which bundle a decision was comoputed
from?) and performance (e.g., you would expect OPA to dedup data between
bundles.)
Moving to a single bundle DOES NOT prevent admins from bundling
multiple policies and data sets together.
/cc @koponen-styra
> Refactor bundle configuration to be singleton

- cmd/check.go
- loader/errors.go
The check subcommand was not formatting parse errors as JSON if
requested. Also, since the loader package returns a set of errors, parse
errors are unpacked to avoid double nesting.
> Fix check subcommand parse error printing

- runtime/runtime.go
The runtime was starting the bundle and status plugins even if the
config was missing.
> Only start plugins if config provided

- docs/book/decision_logs.md
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/logs/buffer.go
- plugins/logs/buffer_test.go
- plugins/logs/encoder.go
- plugins/logs/encoder_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/rest/rest.go
- runtime/runtime.go
- server/buffer.go
- server/server.go
- server/server_test.go
- server/types/types.go
- server/writer/writer.go
- storage/errors.go
- storage/storage.go
Previously, decisions were recorded in an in-memory buffer and could be queried via the REST API. While this is useful for debug purposes, it's not a reliable way to audit policy decisions or debug policy decisions at scale.
These changes extend the decision logging capability in OPA to upload batches of decision logs to remote HTTP servers.
> Improve support for decision logging in OPA

- runtime/logging.go
- server/server.go
Now, GET /v1/data/foo%2fbar will construct a query string of
data["foo/bar"]
allowing to retrieve the key mentioned in issue #695.
However, I believe further work would be necessary, as the code path for
POST/PATCH/DELETE is different. (That has also blocked added a test for
this change, unfortunately.)
I also couldn't get this to work with POST /v0/data/foo%2fbar. (But I also
haven't tried very long, to be honest.)
>  server: handle foo%2fbar in path (#695)

- server/server.go
- server/server_test.go
- storage/path.go
- storage/path_test.go
These changes extend #702 to include writes. If the path segments are
escaped, the should be unescaped during parsing. This allows callers to
write keys like "foo/bar" into storage.
Fixes #695
> Handle escaped paths in data writes

- topdown/eval.go
- topdown/eval_test.go
- topdown/query.go
- topdown/topdown_partial_test.go
- topdown/topdown_test.go
This is for issue #707.
I didn't go all the way to adding the partial test including `not` -- but this should cover the other bits.
Fixes #707
> topdown: introduce queryIDFactory for unique queryIDs

- docs/book/terraform.md
Due to the deprecation of the `-e`/`--eval` flag of the run command in release 0.8, the Terraform tutorial is no longer accurate. This commit updates the tutorial to use the new `eval` command which replaces the old flag.
----
I've been investigating OPA at work for the past few days (specifically for usage with Terraform plans) and this was a pretty big head-scratch moment. It's not yet clear to me what the best practices are with the `eval` command when it comes to `--data` vs `--input`, so please let me know if I'm abusing the flags here.
> Update Terraform tutorial commands to v0.8

- Makefile
The VERSION value was not updated properly during the last release. As a
result, the -dev images were being cut under 0.8.0 instead of 0.8.1.
Whoops!
> Fix Makefile VERSION

- cmd/eval.go
This allows the specification of multiple data/policy files, mirroring
the old behaviour of the run command's eval flag.
Resolves #713.
Signed-off-by: Brendan Devenney <brendan.devenney@cloudreach.com>
----
I think I've updated all of the necessary references for this, but there may be some documentation which I've missed. Please advise if so and I'll update it!
> Make eval command's data flag repeatable (Resolves #713)

- ast/compile.go
- ast/compile_test.go
These changes update the compiler to rewrite with modifiers to allow
refs or other terms that require evaluation as values. For example,
before this change, the following would not be allowed:
allow with input as data.test.some_test_input
Because the with value (data.test.some_test_input) requires evaluation.
After this change, the expression will be rewritten so that the with
value is bound to a variable earlier in the query and then substituted
with a variable.
This change will make tests cleaner as users will not have to bind
inputs to variables explicitly inside their test cases.
Fixes #701
> Rewrite with modifiers to allow refs as values

- README.md
- SECURITY_RELEASE_PROCESS.md
This process is copied from Envoy and Kubernetes. As part of setting up
this process we have created new mailing lists for managing
vulnerability reporting and announcements.
> Add security vulnerability reporting process

- topdown/cache.go
- topdown/cache_test.go
The virtual document cache was not being invalidated. As a result, if
the same rule was evaluated twice where the first expression included a
with modifier, the result on the second evaluation may be incorrect.
Fixes #736
> Fix virtual document cache invalidation

- tester/reporter.go
- topdown/aggregates.go
The following failures were fixed:
tester/reporter.go:84:2: can probably use "var results []*Result" instead
topdown/aggregates.go:88:11: should omit type ast.Value from declaration of var max; it will be inferred from the right-hand side
> Fix go-fmt failures

- rego/rego.go
- rego/rego_test.go
- storage/inmem/inmem.go
- storage/inmem/inmem_test.go
- util/json.go
- util/json_test.go
This should fix #722. It's a slight variation of the code snippet provided
there:
I wasn't sure what the reflect.Interface part was for, so this is using
only reflect.Ptr. Also, there existing tests would fail without the added
check for reflect.Invalid.
Adds a test case for inmem -- in a new method, as I couldn't quite fit it
into the schema of TestInMemoryWrite.
Also, util.Reference() ensures that the returned value is a pointer to
something -- and not a pointer to a pointer to something. While this wasn't
part of the issue #722, it felt weird not to solve the general problem, but
only the edge case. :)
> storage/inmem: support pointers to structs

- docs/book/get-started.md
There is still a need to improve the output of references to set docs
that include variables. In those cases, the expression value AND the
variable bindings are displayed. Only the bindings should be displayed.
> Fix output in REPL examples for getting started

- docs/book/bundles.md
The service authentication configuration docs were included inte token
scheme in the token value. If users configured OPA this way,
authentication would fail.
> Fix service authentication configuration docs

- topdown/bindings.go
- topdown/http_test.go
- topdown/save.go
- topdown/topdown_partial_test.go
- topdown/topdown_test.go
These changes update the topdown test suite to run tests using normal
evaluation and then again against the result of partial evaluation. In
the second pass, input is treated as unknown.
This additional coverage uncovered an issue in the namespacing applied
before partial evaluation results are returned to callers. Specifically,
reference heads and with values were not being namespaced.
The http.send POST test was also updated to avoid keeping track of
request bodies as this broke when the case was executed twice.
> Improve partial evaluation testing

- cmd/run.go
- server/server.go
This adds the option --domain-socket to the server, which gets the
server to listen on a UNIX domain socket. This option supersedes the
addr and insecure-addr options.
> Add support for listening on a UNIX domain socket

- docs/book/kubernetes-admission-control.md
Add `--wrap=0` flag to the `base64` command to disable line wrapping.
Without the flag the `yaml` contains extra new lines and it is invalid:
```
Error from server (BadRequest): error when creating "webhook-configuration.yaml": ValidatingWebhookConfiguration in version "v1beta1" cannot be handled as a ValidatingWebhookConfiguration: v1beta1.ValidatingWebhookConfiguration: Webhooks: []v1beta1.Webhook: v1beta1.Webhook: ClientConfig: v1beta1.WebhookClientConfig: Service: CABundle: decode base64: illegal base64 data at input byte [...]
```
> Update a command in the Kubernetes Admission Control tutorial

- server/server.go
The socket removal was using the URIs path, which is fine for absolute
paths, but doesn't work properly with relative ones.
The socket itself is listening on the Host + Path, which works for
relative paths, so we use that same path for the removal.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> Fix unix socket removal to take relative paths as well

- docs/book/how-does-opa-work.md
The example wrongly covered the servers, ports and networks keys under
the "data" key. It shouldn't have been that way (probably a typo?). So I
removed that.
Also fixed the policy definition example in the same document.
> Fix examples in "Putting it all together" doc

- server/server.go
This refactor consists of two things:
* Accept 'http(s)' as a scheme
* Move the code so it's easier to add new protocols to --addr
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> Refactor server listen to take 'http(s)' scheme in URL

- cmd/run.go
- runtime/runtime.go
- server/server.go
- server/server_test.go
This makes the --addr CLI parameter to be a slice and refactors the code
to allow several addresses to be passed. Hence we can listen on as many
HTTP and UNIX sockets as we want.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> Allow passing multiple addresses to the server

- runtime/runtime.go
- server/server.go
@JAORMX take a look at this.
I've basically just split the getListenerForHTTPServer function so that it only deals with HTTP. There's a new getListenerForHTTP**S**Server function for HTTPS. And then the --insecure-addr case is handled outside the loop (so it should be easier to rip out later.)
> Refactor HTTP and HTTPS listener creation

- server/server.go
- server/server_test.go
The partial cache was not be invalidated when data changed. As a result,
callers would receive stale results when data updated.
Fixes #589
> Fix partial cache invalidation for data changes

- ast/check_test.go
- ast/compile_test.go
- ast/parser_test.go
- ast/policy_test.go
- ast/transform_test.go
- dependencies/deps.go
- format/format.go
- loader/errors.go
- metrics/metrics.go
- rego/example_test.go
- repl/repl_test.go
- server/server_test.go
- storage/interface.go
- topdown/strings.go
- topdown/tokens.go
- watch/watch.go
- watch/watch_test.go
This is all rather trivial. 😃 But should get `opa` to 100% in some of these: https://goreportcard.com/report/github.com/open-policy-agent/opa
Couldn't fix govet (that error just seems wrong, there's an upstream issue for it); ran out of time before looking at gocyclo. No idea about the golint one, either.
> fix some go reportcard issues

- ast/parser_internal.go
- cover/cover_test.go
- server/server.go
- topdown/save.go
Follow-up to #770. Hadn't realised I was fixing a 5-month-old view of the code when I did that. (goscorecard required manual refreshes, by clicking a button on the site.)
It really doesn't matter, but this PR should get us to 100% for all but go vet and gocyclo.
> fix new go scorecard issues

- ast/builtins.go
- docs/book/language-reference.md
- topdown/tokens.go
- topdown/topdown_test.go
Signed-off-by: Henri Bouvier <henribouvier@yahoo.com>
Thanks for the review, I appreciate it.
Pull request feedback:
[x] (@tsandall) verify_secret was renamed to verify_hs256 in builtins.go
[x] (@tsandall) language-reference.md correct the naming from rs256 to hs256
[x] (@srenatus) corrected the comment of the HS256 JWT verification function
[x] (@srenatus) refactored common code from builtinJWTDecode, builtinJWTVerifyRS256 and builtinJWTVerifyHS256 into decodeJWT() and decodeSignature()
[x] (@srenatus) verify and bubble up error from io.writer
[x] (@srenatus) simplify returning result (remove unnecessary if condition)
NOTES:
- I realize that re-creating the pull request was probably not the best way of doing this (e.g. we will lose the review comments/feedback). Therefore, I tried to …
> Add Secret JWT signature verification built-in function

- ast/builtins.go
- topdown/encoding.go
Wrote two new builtins:
urlquery.fromjson takes as input a JSON map of key value pairs, where the values can either be single strings or array of strings, and produces a properly encoded query string (minus the ?). 
url.generate takes as input a host, a path and a JSON object (empty object for no query string) and produces a properly formatted http:// URL 
Signed-off-by: vrnmthr <varun.mathur@live.com>
> Added URLGenerate and URLQueryFromJSON builtins for URL generation

- ast/builtins.go
- topdown/encoding.go
- topdown/topdown_test.go
These changes just update the built-in declaration to include types for
the call argument and refactor the errors returned by the built-in
implementation to use the helpers in topdown.builtins.
> Tweak urlquery.encode_object implementation

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
The decision logger was using strings.TrimLeft when it should have been
using strings.TrimPrefix. As a result, the prefix was not being trimmed
correctly--leading characters in the cutset "data." were being removed.
Fixes #783
> Fix query to path conversion in decision logger

- server/authorizer/authorizer.go
- server/authorizer/authorizer_test.go
> Add query parameters to input

- docs/book/decision_logs.md
- plugins/logs/buffer.go
- plugins/logs/plugin.go
This change removes the default decision log buffer limit to avoid
unintentionally dropping decision logs. If users are concerned about
memory usage they can set the limit, but by default they will not be
surprised by log discards.
> Remove decision log buffer limit

- repl/repl.go
- repl/repl_test.go
Previously, the REPL command to declare unknowns was 'partial' which is
somewhat confusing. These changes just rename the command to 'unknown'.
> Rename REPL command to set unknowns

- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
See second commit for detailed description.
> Fix 794: update error status when transient errors pass

- ast/builtins.go
- docs/book/language-reference.md
- topdown/time.go
- topdown/topdown_test.go
> Add time.weekday builtin

- ast/builtins.go
- docs/book/language-reference.md
- topdown/casts.go
- topdown/casts_test.go
I think the to_set and to_array functions require no justification.
For the others: I realized this would be useful to have when I was
doing http calls that returned a types.A and thus when I parsed my code
on occasion it only threw type errors at runtime when I attempted to use
the result in another builtin. It would be great to have some way to
throw these type errors at compile time as well if the
user likes, hence these functions.
Signed-off-by: Varun Mathur <varun.mathur@live.com>
> Added casts for all types

- topdown/copypropagation/copypropagation.go
- topdown/topdown_partial_test.go
Previously, copy propagation was not substituting ref heads with the
root from the union-find structure. The result was inconsistent queries
being returned. Ref heads were not substituted because the visitor
short-circuits on refs to apply the binding list and then only recurses
on the tail terms.
With these changes, copy propagation substitutes vars and ref heads with
the union-find roots at the same time.
Secondly, these changes fix buggy logic for setting the union-find root
constant. Previously, if the root constant was non-nil, and the copy
propagator tried to unset it, the check would fail and be silently
ignored. In this case, removing the helper function makes the logic
clearer and fixes the bug.
Fixes #816
> Fix copy propagation substitution for ref heads

- cmd/eval.go
- cover/cover.go
- profiler/profiler.go
- profiler/profiler_test.go
Changes to add a Rego expression profiler. 
Sample output for an expression:
`{
"index": 0,
"totalTimeNs": 72225,
"numEval": 4,
"numRedo": 4,
"row": 1,
"col": 1,
"text": "x = 1"
}
`
> Rego profiler

- repl/repl.go
- repl/repl_test.go
These changes are fairly self-explanatory. Previously, the REPL would only print the string representation of partial evaluation results. In debugging cases, it's useful to be able to inspect the AST in JSON (e.g., if there are wildcard variables.)
> Add JSON output format to REPL partial evaluation output

- Dockerfile.in
- Dockerfile_debug.in
- Makefile
These changes modify the build to leave CGO enabled (as opposed to
disabling it explicitly.) This will make it possible to load Go
libraries dynamically.
Since CGO is enabled, we have cannot use the scratch or alpine base
images any more. To replace them, we are using the "distroless" images
from GoogleContainerTools[1]. These images are intended to run
statically compiled languages like Go and Rust. They have a minimal
number of dependencies (importantly, glibc) and produce relatively small
images (~30MB.) The old images were ~20MB in size.
These changes enable a second "debug" image flavor which is based off
distroless "debug". This image includes a shell and other things that
are useful for debug purposes. In addition, the image includes the
"diff" program which is used by opa fmt …
> Update build to enable CGO

- topdown/eval.go
- topdown/topdown_partial_test.go
This should address #833. I'm not sure if the case for `ast.Object` is sufficient (can we match keys?).
This is the errors we get on master with the added test cases:
```
--- FAIL: TestTopDownPartialEval/save:_call_composite_result_(array) (0.00s)
/Users/stephan/go/src/github.com/open-policy-agent/opa/topdown/topdown_partial_test.go:911: startswith(x, "foo"): eval_type_error: startswith: operand 1 must be string but got var
--- FAIL: TestTopDownPartialEval/save:_call_composite_result_(array,_nested) (0.00s)
/Users/stephan/go/src/github.com/open-policy-agent/opa/topdown/topdown_partial_test.go:911: startswith(x, "foo"): eval_type_error: startswith: operand 1 must be string but got var
--- FAIL: TestTopDownPartialEval/save:_call_composite_result_(object) (0.00s) …
```
> Safe composite returns containing unknown values in partial eval

- cmd/eval.go
- docs/book/SUMMARY.md
- docs/book/book.json
- docs/book/profiler.md
- presentation/presentation.go
- profiler/profiler.go
- profiler/profiler_test.go
- repl/repl.go
This pull request has changes to add the `profiler` to the `eval` command.
This PR depends on https://github.com/open-policy-agent/opa/pull/808 .
> Add profiler to OPA eval command

- server/server_test.go
- topdown/eval.go
- topdown/example_test.go
- topdown/topdown_partial_test.go
Previously, partial eval would always generate a support rule when it
evaluated a rule with a default value. These changes tweak this
behaviour so that support rules are only generated if the default value
is required in the partial eval output. It's better to avoid generating
support rules as it simplifies the assumptions that the consumer of
partial eval can make.
Fixes #820
> Remove support rule if default value is not needed

- ast/parser.go
- ast/parser_ext.go
- ast/parser_internal.go
- ast/parser_test.go
- ast/rego.peg
For example, given: `p { true; }`, instead of:
```
1 error occurred: 1:11: rego_parse_error: no match found, expected: "#", "(", "-", ".", "0", "[", "\"", "`", "false", "not", "null", "set(", "true", "{", [ \t\r\n], [ \t], [1-9] or [A-Za-z_]
```
Print:
```
1 error occurred: 1:11: rego_parse_error: no match found
p { true; }
^
```
> Improve parser errors

- docs/book/bundles.md
- loader/loader.go
- loader/loader_test.go
- loader/merge.go
- loader/merge_test.go
Previously OPA would only load JSON/YAML/Rego files off the command
line. With these changes, OPA will load .tar.gz files and interpret them
as bundles. This is useful if you want to test your bundles locally with
OPA without running OPA as a server, configuring it to pull down the
bundle, etc.
Fixes #870
> Add support for command line bundle loading

- CONTRIBUTING.md
The text is largely taken from https://github.com/open-policy-agent/opa/pull/878
Signed-off-by: Richard Kettlewell <Richard.Kettlewell@thalesesecurity.com>
> CONTRIBUTING.md: commits must be signed off

- docs/book/docker-authorization.md
Previously the example policy at the end of the tutorial would allow
operations if the Authz-User was contained in the input headers but not
in the user mapping. This change makes sure that the user is defined in
the mapping.
Also, update the example to use := and == instead of = (which is
functionaly the same but better practice because they avoid capturing
globals.)
Fixes #880
> Improve Docker tutorial example

- docs/book/terraform.md
In de828cd we added any and all built-in functions. This broke the
example policy in the terraform tutorial that was expecting "all" to be
a variable. We fix this by replacing the unification expressions ("=")
with assignments (":=").
Fixes #888 
> Fix terraform tutorial type check errors

- cmd/plugins.go
We will probably want to use -p at some other point and this feature is
not likely to be needed in interactive environments.
> Remove shorthand for --plugin-dir flag

- cmd/eval.go
- internal/presentation/presentation.go
- repl/repl.go
- repl/repl_test.go
These changes update the eval subcommand to support partial evaluation.
As part of these changes, the pretty formatting of partial evaluation
results has been refactored and moved into the presentation package. The
new version uses the tablewriter like other output values.
> Add --partial/--unknown flags to eval subcommand

- docs/book/kubernetes-admission-control.md
By default kube-mgmt will try to load policies out of configmaps in the opa namespace OR configmaps in other namespaces labelled openpolicyagent.org/policy=rego.
Signed-off-by: Nikhil Bhatia <nbhatia@microsoft.com>
> Update tutorial for default policy load ns

- docs/book/how-do-i-write-policies.md
The output from running the interactive
interpretter with v0.9.1 does not match
a few of the examples list in the
How Do I Write Policies section.
This updates the examples to match
the examples observed from running
the v0.9.1 cli.
Signed-off-by: Travis Tripp <os.travis.tripp@gmail.com>
> v0.9.1 How Do I Write Policies example output fix

- README.md
The FOSSA license scan recently began failing for some (unknown) reason.
Since the vendoring has not been updated lately, it seems like this is
not a valid warning. FOSSA has not responded to support requests for
several days now, so I removing the badge until we can get the issue
reoslved.
> Removing FOSSA badge from README

- ast/policy.go
- format/format.go
- format/format_test.go
- internal/presentation/presentation.go
Previously, if an empty ast.Body was passed to the formatting package,
it would trigger a panic because the location getter would try to index
into an empty slice.
These changes make the location getter tolerate empty bodies and the
format package tolerate nil locations on empty bodies.
Fixes #909
> Improve formatting of empty ast.Body

- topdown/copypropagation/copypropagation.go
- topdown/topdown_partial_test.go
The copy propagator was not taking the union-find subsitutions into
account when building the headvar set. As a result, bindings were being
added for call expressions when the var would later be substituted for a
ref head (which ultimately would cause a panic when the ref head was
substituted for the call).
These changes update the copy propagator to add the union-find root to
the headvar set instead of the headvar. This way the headvar
construction is consistent with the binding plug and update below.
Fixes #912
> Fix copy propagator type assertion panic

- topdown/copypropagation/copypropagation.go
- topdown/query.go
- topdown/topdown_partial_test.go
Previously copy propagation was only being applied to queries returned
by partial eval. The assumption was that clients would typically be
implemented to deal with queries and that support rules would be
unhandled. In some cases though, clients may be capable of handling
support rules. For them, it's better if we apply copy propagation to
both queries and rule bodies.
Note, we ensure that rule bodies are non-empty so that comparisons to
parsed rules that are equivalent (but lacking a body) succeed.
Fixes #911
> Apply copy propagation to support rules

- docs/book/security.md
- server/authorizer/authorizer.go
- server/identifier/identifier.go
- server/identifier/identifier_test.go
With these changes, the identity will be undefined if a token is not
specified. This is less surprising than the empty string that would be
set prior to these changes.
Fixes #901
> Improve token authentication docs and handler

- server/server.go
- server/server_test.go
Previously the query/input/error forms were being returned to the client
unescaped. This would allow for XSS attacks against admins with access
to the OPA debug page. While this scenario is quite uncommon (e.g., OPA
should be configured to listen on localhost/unix domain, authenticate
and authorize requests, etc.) it's still a possibility.
These changes escape the query/input/error forms returned to the browser
to prevent XSS attacks.
> Fix XSS in debug page

- ast/policy.go
- ast/policy_test.go
If users are constructing modules programatically they may accidentally
construct package paths with illegal values. Before this change, calling
.String() on the package would result in a panic. With these changes the
.String() function will no longer panic, instead it will return a string
representation that does not parse and indicates the source of the
issue.
> Fix Package stringer to handle bad inputs

- topdown/http_test.go
> Update http.send test to work w/o internet access

- docs/book/how-do-i-test-policies.md
Currently in the docs an old flag `--cover` is used for the coverage. This PR corrects the flag and makes the example run again.
> Fix coverage flag for test command

- docs/book/how-do-i-test-policies.md
- tester/reporter.go
- tester/reporter_test.go
- tester/runner.go
- tester/runner_test.go
Previously the test runner would set fail to the value generated by the
test rule or false on undefined. The intent was to communicate the value
generated by the rule. In practice users are not writing tests that
generate values other than true so this is essentially unnecessary.
Fixes #954
> Update test runner to set Fail to true

- ast/parser_ext.go
- ast/parser_test.go
The parser was panic-ing when constructing an error detail because it
could index into the line with a negative offset. These changes improve
the improve the checks against the position input.
Fixes #948
> Fix panic in parser error detail construction

- ast/visit.go
- topdown/bindings.go
- topdown/copypropagation/copypropagation.go
- topdown/eval.go
- topdown/query.go
- topdown/save.go
- topdown/topdown_partial_test.go
Previously partial eval would generate support rules for the result of
negated expressions. With these changes, the result of partially
evaluating a negated expression may be inlined into the containing
query.
The result of partially evaluating a negated expression may be inlined
if:
- The query set resulting partial eval does not contain any positive,
non-ground expressions. E.g., p[x] cannot be safely negated so it
would still result in support rules.
- The size of the cross product that represents the inlined result is
not larger than 16. This limit is arbitrary and in the future we can
make it configurable as needed.
In the future it may be possible to make the inlining decision more
sophisticated. For now though, because copy propagation is applied to
the result, it's often possible …
> Inline negated expressions during partial eval

- topdown/eval.go
- topdown/topdown_partial_test.go
The inlining changes introduced a bug in the support calls that are made
when the negation cannot be inlined. The support rule was being created
with one argument for each unknown in the entire save set. Since some of
those variables may not be preserved in the final result, it was
possible for the support call to become unsafe. To resolve this we only
add call args for the intersection of unknowns and vars that appear in
the result of partially evaluating the negated expression.
> Fix unsafe support calls

- docs/book/language-reference.md
For some reason, this was missing from the language reference.
> Add array.concat built-in to language ref

- ast/term.go
This removes about 15% of the mallocs and speeds up the set operations
roughly the same.
> Remove heap allocations from AST set with open addressing.

- cmd/test.go
- tester/reporter.go
- tester/reporter_test.go
- tester/runner.go
This should be following the outline of https://github.com/open-policy-agent/opa/issues/856#issuecomment-408908578 closely.
I tend to agree that #961 would be quite cool, but I guess this is one step into the right direction, at least? 😃
> opa test: add traces on errors

- .travis.yml
This should prevent the linux executable from being deleted (it's
require by the image build.)
> Add skip_cleanup: true to .travis.yml

- tester/reporter.go
- tester/reporter_test.go
- tester/runner.go
- tester/runner_test.go
Fixes #976.
This follows the same logic as Go's `t.Run()` when called with duplicate
names, i.e.
func TestTest(t *testing.T) {
t.Run("duplicate", func(t *testing.T) { t.Fail() })
t.Run("duplicate", func(t *testing.T) {})
}
would output
--- FAIL: TestTest (0.00s)
--- FAIL: TestTest/duplicate (0.00s)
--- PASS: TestTest/duplicate#01 (0.00s)
`opa test` now behaves the same (see [updated tests](https://github.com/open-policy-agent/opa/pull/982/files#diff-7a209e3ecd96215c78bf56d6ddfd0d58R48)).
> cmd/test: rewrite duplicate test_* rule names

- ast/compile.go
- ast/compile_test.go
In a660d8f2 we added a rewriting stage that converts == to unification.
This simplifies evaluation and allows the rule index to be used,
however, the rewriting was incorrectly applied to == expressions that
are intended to yield a true/false value (and not undefined).
Fixes #995
> Fix == rewriting on embedded terms

- ast/builtins.go
- cmd/eval.go
- cmd/test.go
- docs/book/language-reference.md
- internal/runtime/runtime.go
- rego/rego.go
- repl/repl.go
- runtime/runtime.go
- server/authorizer/authorizer.go
- server/server.go
- tester/runner.go
- topdown/builtins.go
- topdown/eval.go
- topdown/query.go
- topdown/runtime.go
- topdown/runtime_test.go
- watch/watch.go
These changes add support for accessing runtime information inside of
policies. In some cases, policies need to access environment variables
or configuration that OPA was booted with. These changes add a built-in
function that allows policies to gain access to this information. The
built-in function itself is relatively trivial. Most of the required
changes were plumbing the runtime information from the entrypoint down
into the evaluation engine. The alternative would have been to introduce
a global variable containing this information however that would be have
been harder to reason about in library integrations.
Fixes #420
> Add built-in function to get runtime info

- docs/book/configuration.md
- docs/book/rest-api.md
- runtime/runtime.go
- server/authorizer/authorizer.go
- server/authorizer/authorizer_test.go
- server/server.go
- server/server_test.go
Previously, OPA would serve POST requests with an empty URL path by
querying data.system.main and returning the generated value. In some
cases, it's useful to be able to reconfigure OPA to use a different
document to serve these kinds of requests. The same goes for the OPA
authorization policy.
These changes make the default decision and default authorization
decision paths configurable.
> Add default decision configuration

- cmd/eval.go
- cmd/eval_test.go
Adds support for non-zero exit code when providing the --fail flag to
the eval command. 0 means no error, 1 means undefined result and 2 means
an error.
Fixes #981
> Add support for non-zero exit code

- topdown/eval.go
- topdown/trace.go
- topdown/trace_test.go
Previously the tracing interfaces took interface{} because ast.Node did
not exist. Now that we have ast.Node we should use that instead as it
makes it easier to access generic AST information like source location.
> Refactor tracing interfaces to take ast.Node

- topdown/bindings.go
- topdown/eval.go
- topdown/query.go
- topdown/topdown_partial_test.go
These changes address the panic that was happening during copy
propagation when a ref inside of a comprehension was plugged with a
composite value (or any value that would lead to an illegal ref). For
example:
x = [0]; [true | x[0] = 0]
In this case, when partial eval ran, the saved expression before copy
propagation ran would be the comprehension itself. The problem was that
the binding x/[0] would be plugged into the comprehension resulting in:
[true | [0][0] = 0]
While this could be considered legal, we don't currently support refs
like this (in the parser and in the evaluator). As a result, when copy
propagation encountered this ref, it panic-ed because it would assume
the ref head was a variable.
To deal with this issue, we have refactored how partial evaluation
handles …
> Fix copy propagation panic in comprehensions

- format/format.go
- repl/repl_test.go
opa fmt should only add one newline at the end of the file
> Only write one trailing newline at end of file

- docs/book/configuration.md
- plugins/rest/rest.go
- plugins/rest/rest_test.go
Adds support for usings client certificates to authenticate against service endpoints. It also enables users to allow insecure TLS connections to service endpoints.
Fixes #684
> Add support for client certificates 

- build/gen-opa-wasm.sh
- main.go
The WASM changes broke cross-compiling because go generate executes go
run ... which inherits the GOOS and GOARCH environment variables. To
resolve this we just wrap the go rnu ... command in a script that
overwrites the environment variables so that the host GOOS and GOARCH
are used. For some reason go generate does not allow you to specify
environment variables inline, e.g., FOO=BAR go run ...
> Fix cross-compile issue in go generate step

- docs/book/rest-api.md
This didn't look like it was processed in any way, and showed up as-is
on the website:
> docs(rest-api): remove '{: .opa-tip}'

- cmd/test.go
- cover/cover.go
- cover/cover_test.go
- tester/reporter.go
This PR fixes issue #1029 by providing these changes.
Extend `opa test` to compute the code coverage percentage of each file and the overall one.
The `opa test --coverage` now returns the code coverage percentage per file and globally:
```
./opa_linux_amd64 test --coverage example
{
"files": {
"example/example.rego": {
"covered": [
{
"start": {
"row": 8
},
"end": {
"row": 11
}
}
],
"not_covered": [
{
"start": {
"row": 3
},
"end": {
"row": 5
}
}
],
"coverage": 57.15
},
"example/example_test.rego": {
"covered": [
{
"start": {
"row": 11
},
"end": {
"row": 12
}
},
{
"start": {
"row": 15
},
"end": {
"row": 16
}
}
],
"coverage": 100
}
},
"coverage": 72.75
}
```
User can now specify a desired code coverage threshold that causes `opa test` to exit with an error when the global code coverage is …
> opa test: handle code coverage percentage

- cover/cover.go
- cover/cover_test.go
The helper function to compute coverage doesn't have to be exported
since the coverage is set as a field on the FileReport. Removing the
helper function in the spirit of minimizing the surface area of the
package.
> Unexport helper function to compute coverage

- internal/ir/ir.go
This change just makes it clearer that the assignment operand is an IR
constant type not some arbitrary Go type.
> Add type markers to IR constants

- docs/book/decision_logs.md
- docs/book/rest-api.md
When decision logging is enabled, API calls for decisions will return a
decision ID, e.g., {"result": true, "decision_id": "abcdef1234"}.
Fixes #1061
> docs: Add decision ID note in API docs

- docs/book/language-reference.md
Looks like @msorens didn't get around to fixing this. So, here we go.
> book(language reference): fix "alteration" typo

- tester/runner.go
- tester/runner_test.go
The test runner was using the rule name as the cache key for
deduplication purposes. If test rules in two different packages had the
same name, the second one would be rewritten which could cause
unexpected errors.
These changes simply update the runner to use the rule path (which is
the package path + rule name) because that ought to be unique.
> Fix bug in test runner rule name dedup

- rego/rego.go
- repl/repl.go
- repl/repl_test.go
- topdown/builtins.go
- topdown/eval.go
- topdown/query.go
- topdown/trace.go
- topdown/trace_test.go
Previously the topdown evaluator only supported a single tracer. As a
result it was not easy to use multiple trace-based features (e.g.,
tracing and profiling) in conjunction.
These changes modify the evaluator to support multiple tracers. Instead
of adding a new interface to register N tracers, these changes just
overload the existing WithTracer function to add the passed tracer.
> Add support for multiple tracers

- ast/compile.go
- ast/compile_test.go
These changes fix an annoying issue where the ordering of errors across
multiple files was non-deterministic. This was caused due to the fact
that iteration over maps in Go is non-deterministic.
> Refactor compiler to iterate over modules in order

- topdown/eval.go
- topdown/save.go
- topdown/topdown_partial_test.go
Previously we were not applying the bindings to vars before adding them
to the save set. This meant the biunifier and the save set were out of
sync, e.g., a the biunifier would have (w/(x,1), 2) while the save set
had (w, 2). Therefore, when an expression like w = y was applied, the
result would be x = y which would not be saved. These changes modify
evaluation to apply vars before adding them to the save set. This way
the save set would correctly have (x, 1) in the case above.
Also, add String() function to save set for future debugging.
Fixes #1074
> Fix partial eval to apply saved terms

- topdown/eval.go
- topdown/topdown_test.go
The input on the evaluator was being set incorrectly when the with
keyword is handled in the evaluator. These changes just update evalWith
to set the input term correctly.
Fixes #1083
> Fix panic caused by input being set incorrectly

- topdown/eval.go
- topdown/topdown_test.go
In 986d82f we added support for applying the with keyword to the data
document. In the implementation, the ref resolver had to be updated to
check an additional cache. Those changes contained a bug that caused the
ref resolver to exit early and indicate that the ref was undefined if
the cache did not contain a value for the ref (partial or complete).
Fixes #1110
> Remove incorrect early exit from ref resolver

- ast/compile.go
- ast/compile_test.go
During the assignment rewriting stages, variables that have been
assigned locally are rewritten, e.g., k := "foo"; {k: 1} becomes
__local0__ = "foo"; {__local0__: 1}. Previously, the rewriting would
simply mutate all of the term values without considering where the term
was defined. The problem with this was that it would corrupt the
object's hashtable if the rewritten term was an object key.
This commit resolves the issue by making a copy of the object key before
mutating the term value. This approach requires the compiler to copy the
object as well. If this proves to be a performance bottleneck, we can do
something more clever.
Note, it's arguable that the Object struct should not allow keys to be
mutated at all. This would be tricky given the current Object interface.
Perhaps we can …
> Fix panic caused by assignment rewriting

- cmd/test.go
- tester/reporter.go
- tester/runner.go
- tester/runner_test.go
Fixes #961
Added new option to opa test command (-l)
Verbose (-v) as precedence over (-l)
Example run:
opa test test.rego -l
data.foo.test_a: FAIL (754ns) (test.rego:4)
data.foo.test_b: FAIL (382ns) (test.rego:8)
-------------------------------------------------------
FAIL: 2/2
> Show line of failure in `opa test`

- ast/compile.go
- ast/compile_test.go
The rewriting was accidentally including the ref head (i.e., input or
data) in the seen stack when recursing on the right hand side of the
declaration statement. This meant that if multiple with modifiers were
applied within the term (e.g., inside a comprehension), then the 2nd
would cause the subsequent with target semantic check to fail.
The fix simply updates the rewriting step to ignore the with target in
this case (like we already do for other statements.)
> Fix bug in local declaration rewriting

- server/server.go
- server/server_test.go
Fixes #1086
curl -v http://:8181/health
*  Trying ::1...
* TCP_NODELAY set
* Connected to  (::1) port 8181 (#0)
> GET /health HTTP/1.1
> Host: :8181
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 07 Jan 2019 20:09:36 GMT
< Content-Length: 2
<
* Connection #0 to host  left intact
{}%
> Add /health endpoint to OPA HTTP server

- ast/parser_ext.go
- ast/parser_internal.go
- ast/parser_test.go
- ast/policy.go
The parser was accumulating comments in a parser-global slice. If the
parser backtracked, the comments were not thrown away. Because most
successful parses seem to backtrack, this meant that most ASTs contained
duplicated comments.
This change simply modifies the parser to accumulate the comments in a
set that just gets sorted at the end.
Fixes #426
> Fix parser to avoid duplicate comments in AST

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
Fixes #1089 
Decision logs now contain build version. All tests pass.
=== RUN   TestPluginStartSameInput
--- PASS: TestPluginStartSameInput (0.02s)
=== RUN   TestPluginStartChangingInputValues
--- PASS: TestPluginStartChangingInputValues (0.01s)
=== RUN   TestPluginStartChangingInputKeysAndValues
--- PASS: TestPluginStartChangingInputKeysAndValues (0.01s)
=== RUN   TestPluginRequeue
--- PASS: TestPluginRequeue (0.00s)
=== RUN   TestPluginReconfigure
time="2019-01-09T09:34:03-08:00" level=info msg="Starting decision log uploader." plugin=decision_logs
time="2019-01-09T09:34:03-08:00" level=info msg="Log upload skipped." plugin=decision_logs
time="2019-01-09T09:34:03-08:00" level=info msg="Stopping decision log uploader." plugin=decision_logs
time="2019-01-09T09:34:03-08:00" level=info …
> Add OPA version to decision logs

- .gitignore
- cmd/plugins_test.go
- docs/book/SUMMARY.md
- docs/book/configuration.md
- docs/book/plugins.md
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/plugins.go
- runtime/runtime.go
This PR contains two commits. The first improves the plugin system so that custom plugins can be managed more like bundles/status/logs. The second makes the decision logger backend pluggable.
I considered implementing the decision logger feature in a more generic manner that would have worked for other components like status and bundle but eventually decided against that (it felt like overkill). If we find ourselves needing to make the other components pluggable, we could revisit the implementation.
> Plugin improvements and custom decision loggers

- .travis.yml
- Makefile
No idea why we shouldn't do this. Is there a reason? 😃
> chore: use go 1.11.4

- Dockerfile_release-builder.in
- Makefile
- docs/devel/DEVELOPMENT.md
Also, remove gulp installation as that's not required with the new frontpage.
> chore: Update release-builder for Go 1.11

- ast/term.go
- ast/term_test.go
- topdown/topdown_test.go
The find operation on sets was returning "not found" for non-empty
refs which was unexpected and resulted in evaluation failing. This
problem would only manifest if sets were provided as input or used
when mocking data. Since input is typically JSON (and does not
include sets) and data mocking is relatively new, we only ran into
this recently.
> ast: Fix find operation on sets for non-empty refs

- docs/book/decision_logs.md
- docs/book/rest-api.md
- metrics/metrics.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- server/buffer.go
- server/buffer_test.go
- server/server.go
- server/server_test.go
- server/types/types.go
This PR contains a handful of small changes to the decision logging feature. At a high-level:
* Add metrics in events
* Add server_handler timer to metrics
* Add errors to events
* Fix input attribute modelling
* Fix path/query modelling
* Fix error events to include decision ID
> Improvements to decision logging

- docs/book/language-reference.md
Remove "instructions", include "object-compr" and "set-compr" in "term".
Fixes #1187
Signed-off-by: Nischal Sheth <nsheth@ves.io>
> docs: Correct a couple of issues in grammar documentation

- docs/book/kubernetes-admission-control.md
- docs/book/tutorials/kubernetes-admission-control-validation/admission-controller.yaml
This PR fixes a few typos found while taking this tutorial: https://www.openpolicyagent.org/docs/kubernetes-admission-control.html
While those typos are trivial, the tutorial is user-facing and therefore I believe it would benefit from being typos-free.
> Fixed various typos on user-facing tutorials

- config/config.go
- docs/book/decision_logs.md
- docs/book/status.md
- plugins/discovery/discovery_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/status/plugin_test.go
Adds OPA version to the config labels, so that the version
appears in status updates. Previously, decision logs had a
top-level version field. This removes that field because
version will be contained in the labels instead.
This introduces a non-backwards compatible change to the 
decision log EventV1 struct
Signed-off-by: Andy Curtis <arcurtis@gmail.com>
> config: add version to labels

- ast/compile.go
- ast/compile_test.go
- ast/conflicts.go
- cmd/test.go
- docs/book/how-does-opa-work.md
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- rego/rego.go
- rego/rego_test.go
- runtime/runtime.go
- server/server.go
- server/server_test.go
- storage/storage.go
- storage/storage_test.go
Previously there were no checks in place to ensure that base and
virtual documents do not overlap. As a result, if users loaded raw
JSON and rules into OPA that overlapped, the evaluation results were
not well defined. With these changes, we can detect the overlap and
reject updates (to policies or data) that would cause inconsistent
results.
Fixes #1207
> Add path conflict checks

- ast/term.go
- ast/term_test.go
- bundle/bundle.go
- bundle/bundle_test.go
- docs/book/SUMMARY.md
- docs/book/bundles.md
- internal/manifest/manifest.go
- loader/loader_test.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- server/server.go
- server/server_test.go
These changes update OPA to support scoping on bundles. See #1201 for more information. In the future, we can extend scoping so that API callers can declare their own roots.
> Add support for scoped bundles

- docs/book/plugins.md
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- runtime/runtime.go
- server/server.go
- server/server_test.go
Previously, the decision logger interface did not allow plugin
implementations to return an error. In some cases, implementations may
prefer to make OPA fail-closed if the event cannot be emitted.
This is a backwards incompatible change to the custom decision logger
API that was added in v0.10.3 and it deprecates the old diagnostic
interface as well.
> decision_logs: Update interface to return error

- server/server.go
See https://github.com/open-policy-agent/opa/issues/1231.
Should I adjust the documentation for this change? If yes, where would be the right place?
> metrics: Add go default metrics

- docs/book/best-practice-identity.md
Previously the docs were not as clear as they could be about whether
OPA includes an LDAP/AD connector.
This patch adds a few clarifying remarks.
> docs: Clarify identity/LDAP best-practices doc

- topdown/arithmetic.go
- topdown/builtins/builtins.go
- topdown/topdown_test.go
Fixes #1245
Currently modulo operator (%) panics when the input is a floating point number. This change adds support to perform floating-point remainder operation on floating point numbers.
> Fix panic for modulo on floating-point numbers

- README.md
In the past we've released regular roadmap updates. Going forward we
will track the roadmap in this slide deck and simply move old slides
to the back as the project progresses.
> Add public roadmap slides to the README

- server/server.go
- server/server_test.go
In the Data API, the `path` attribute of `PATCH` operations was not handling escaped `~` and `/` values (escaped as `~0` and `~1`, respectively) according to the JSON-Pointer RFC.
The API was using (and continues to support) URL escaping of these characters (so `%7E` and `%2F`, respectively), but this was not documented and is not strictly correct according to the documentation. However, this is being left unchanged to preserve backwards compatibility for anyone who stumbled across this behaviour.
With this change, `~0` and `~1` in the `path` attribute of `PATCH` operations will be unescaped into `~` and `/` as defined in the RFC.
Fixes #1254.
> server: Fix patch path escaping

- docs/book/ssh-and-sudo-authorization.md
Fixes #1260
The Policy comment had backticks around some words which when pasted in the terminal were incorrectly interpreted as bash commands and file names.
> docs: Replace backticks with quotes in ssh policy comments.

- docs/book/get-started.md
Simple change in the docs to add instructions for installing OPA with the loved-by-many Homebrew tool.
> Add OPS installation instructions for Homebrew

- Dockerfile_rootless.in
- Makefile
Added a new `openpolicyagent/opa:latest-rootless` and `openpolicyagent/opa:${version}-rootless` image that does not run as root.
Did this instead of switching the existing image to maintain backwards compatibility for people who may be deploying the image as `root` and using the associated privileges to bind to privileged ports.
Fixes #1267.
> Build and tag rootless Docker image

- topdown/eval.go
- topdown/topdown_test.go
Previously errors that occurred during tree enumeration were being
silently ignored. This would result in an undefined value for the
virtual document defined by the failing error.
Fixes #1272
> Return errors during eval tree enumeration

- docs/style.css
The landing page of [OPA's main website](https://www.openpolicyagent.org/) overflows in the X direction because of the rock animation of the boat object.
On desktops:
On mobile devices:
On desktops:
On mobile devies:
> Fix overflow of landing page

- docs/book/faq.md
In #1268, JSON Web Tokens are mistakenly referred to as Java Web Tokens. This PR addresses that.
> Update JWT reference

- docs/book/comparison-to-other-systems.md
As mentioned in #1282 , the wildcard expressions aren't allowed in `regex.globs_match`. This fixes the expression to be appropriate regex.
* This PR does not include code changes
> Fix IAM sample regex

- docs/code/kubernetes-admission-control-validation/admission-controller.yaml
The tutorial for the admission controller was using an older release of the
kube-mgmt sidecar. This just updates to the latest (as of now) tagged release.
Tested following the full tutorial and all steps work as expected with the new
version being used instead of 0.6.
> Bump kube-mgmt container version to 0.8 in tutorial

- ast/builtins.go
- docs/content/docs/language-reference.md
- topdown/cidr.go
- topdown/cidr_test.go
This adds two new builtin CIDR helpers:
`net.cidr_intersects(cidr1, cidr2)` -- Returns true if cidr1 overlaps at all with cidr2
`net.cidr_contains(cidr, cidr_or_ip)` -- Returns true if cidr_or_ip is contained entirely inside cidr
Both support IPv4 and IPv6.
The `net.cidr_contains` is replacing the `net.cidr_overlap` function (now deprecated) that checked if
an ip was in a given cidr. This function is still available for backwards compatibility but is now
implemented via the same underlying code as `net.cidr_contains`.
Fixes: #1289
> Add additional net CIDR builtins

- docs/layouts/docs/section.en.html
- docs/layouts/docs/single.en.html
This PR adds documentation page titles. The main documentation page will have the title "Open Policy Agent | Documentation" and specific docs will have the title "Open Policy Agent | <title>" (e.g. "Open Policy Agent | Decision Logs").
> Add documentation page titles

- topdown/cidr.go
- topdown/cidr_test.go
The calculation for the last ip of a block had a typo switching the buffer
we created the last ip address from.. This meant we always returned the
first IP address in the range as the last one.
There was also a gap in the unit tests for these cases. Both are corrected
with this patch.
Fixes: #1303
> Fix `net.cidr_contains` for partial match cases

- docs/.gitignore
- docs/Makefile
- docs/config.toml
- docs/layouts/partials/docs/article.html
- docs/layouts/partials/home/banner.html
- docs/scripts/load-docs.sh
@tsandall Okay, I've come up with a solution:
https://deploy-preview-1301--openpolicyagent.netlify.com/docs/v0.10.6/language-reference/
> Fix documentation loading script

- docs/content/docs/policy-primer-k8s.md
Previously the documentation for writing policies was based on
examples from the traditional compute-networking-storage arena.
This policy primer was purpose-built to introduce people to
writing policy for the Kubernetes admission control use case.
> docs: Add k8s policy primer

- docs/assets/sass/docs.sass
- docs/layouts/partials/docs/article.html
- docs/layouts/partials/docs/dashboard.html
There's a window width issue that's clearly visible if you zoom out on the current docs pages:
https://openpolicyagent.netlify.com/docs
Compare with the fixed version:
https://deploy-preview-1312--openpolicyagent.netlify.com/docs/v0.10.6/
This PR fixes that.
> Fix window width issue

- cmd/run.go
- runtime/runtime.go
- server/server.go
- server/server_test.go
There is a new CLI option to configure the grace period:
`--shutdown-grace-period`
The option defaults to 10 seconds.
When a SIGINT or SIGTERM is sent the runtime will catch them and
attempt to gracefully shutdown the http servers. If the timeout is reached
it will log an error and continue with exiting (in a less graceful way).
Unit testing is a little bit light on this. Its touching some parts of the
code that aren't super easy to mock out. We can probably refactor
things in the future to make it easier.
Fixes: #1291
> Add support for graceful shutdown of OPA server

- cmd/run.go
- docs/content/docs/configuration.md
- internal/strvals/doc.go
- internal/strvals/parser.go
- internal/strvals/parser_test.go
- runtime/config.go
- runtime/config_test.go
- runtime/runtime.go
- runtime/runtime_test.go
There are two new CLI options added with this change for the `opa run`
sub command.
`--set`
`--set-file`
These allow for overriding config options on the CLI using `key=value`
options to reference the YAML/JSON config structures. The `--set` value
expects to take in the value you want to set while the `--set-file` value is
a path to a file which will be read for the value of the file. This is primarily
useful for secrets mounted as files on a host.
In addition this adds in some simple environment variable injection so that a
deployer can specify environment variables in the config via ${NAME} syntax.
At the time the config is loaded from file it will inject in the environment vars.
This applies to strings set via the `--set` variable too.
Some things to note:
* This won't work for configs …
> Add CLI config overrides and ENV injection

- rego/rego.go
Just fixing a typo I noticed browsing around the code.
> Fix typo in docstring

- ast/compile.go
- rego/rego.go
- rego/rego_test.go
Similar to what is done with module compilation we will rewrite “==“ to
“=“ operators in queries when using the `/compile` REST API or
`Rego.Partial(..)` API.
This does potentially mean a difference in API behavior for existing
OPA clients.
Fixes: #1280 
> Rewrite == to = in queries passed to the compile API

- docs/layouts/partials/docs/navbar.html
At the moment, the mobile navbar dropdown is showing all docs for all versions. With this PR, only the docs in the currently selected version are shown.
> Fix mobile navbar dropdown

- CHANGELOG.md
- docs/content/docs/how-do-i-test-policies.md
- topdown/builtins.go
- topdown/errors.go
- topdown/http_test.go
Previously unexpected built-in errors resulted in topdown returning
the eval_internal_error code. This makes it hard for callers to
differentiate between actual internal errors in topdown and errors
that are caused by, e.g., invalid built-in inputs.
> Return eval_builtin_error instead of eval_internal_error

- docs/layouts/index.redirects
The older gitbook urls had the pages suffixed with `.html` but the newer netlify ones do not.
This provides a redirect shim to help keep old links alive.
Fixes: 1346
> Add legacy gitbook url redirect for doc pages

- docs/static/css/home.css
The boat rocking was causing the webpage to allow for scrolling sideways at some points due to the 100% width element rotating slightly.
Rather than doing weird calculations to reduce it's size or put it in the middle or w/e it seemed easiest to allow it to rotate off the screen but have the overflow be hidden.
There seems to be no adverse effects when resizing in Firefox however it could be worth trying in other browsers.
> Hid the overflow within .headline caused by the boat rocking

- runtime/runtime.go
The other logrus messages emitted by the runtime are all punctuated.
> nit: Punctuate runtime shutdown log messages

- CHANGELOG.md
- ast/compile.go
- ast/compile_test.go
- ast/example_test.go
- metrics/metrics.go
- rego/example_test.go
- rego/rego.go
- rego/rego_test.go
- repl/repl.go
- test/authz/authz_bench_test.go
- topdown/topdown_partial_test.go
There are a handful of commits changing things, each has some details in their commit messages. High level view of the changes:
* Add `PrepareForEval()` function to Rego objects. This will parse modules and queries, then compile the modules and query (in turn parsing the imports and packages, as needed). The results are stored on the Rego object which is referenced from a PartialResult for future use...
* Add `PrepareForPartial()` function to Rego objects. Similar to `PrepareForEval` it handles parsing/pre-compiling as much as possible, but tailored for doing `Partial()` evaluations.
*  Add `PreparedEvalQuery` object with an `Eval` function which can then use the prepared parts of the queries. This Eval differs from the one on the Rego object by (optionally) taking in a new input, metric, …
> Add Prepare API's to Rego objects

- ast/check.go
- ast/check_test.go
Given an = expression where both sides are unknown (e.g,. a = [1,x]
where a is ??? and x is ???) the inferencing will produce any types
for variables. However, there was a bug in the case that handles
objects where any was not produced for object _keys_, only
_values_. As a result, the object's type would remain partially
unknown and the checker generated errors.
This commit just corrects the inferencing to assign any to object keys
when the other side of the = expression is of type any.
Fixes #1361
> Fix type inferencing on object keys

- docs/content/ceph-authorization.md
- docs/content/decision-logs.md
- docs/content/deployments.md
- docs/content/get-started.md
- docs/content/http-api-authorization.md
- docs/content/kafka-authorization.md
- docs/content/kubernetes-admission-control.md
- docs/content/ssh-and-sudo-authorization.md
- docs/content/status.md
- docs/website/layouts/shortcodes/current_docker_version.html
- docs/website/layouts/shortcodes/current_version.html
- docs/website/layouts/shortcodes/latest.html
- docs/website/layouts/shortcodes/latest_version.html
The older markdown still had `v{{< version >}}` shortcodes being used
which broke when the version changed to include the “v” in it.
This adds in some backwards compatibility logic for the shortcode and
adds newer, more specific, ones to replace it going forward. Part of
The issue is that typically the documentation will only want to
Reference the version that it is documenting and not always the
latest.
Fixes: #1382
> Fix extra ‘v’ in older versions of the docs

- docs/website/layouts/index.redirects
- docs/website/layouts/partials/docs/article.html
- docs/website/layouts/partials/docs/dashboard.html
- docs/website/layouts/partials/docs/sidenav-link.html
- docs/website/layouts/partials/docs/sidenav.html
- docs/website/layouts/partials/home/banner.html
Before this the links were built with the explicit version, we now
check for whether some page is the latest version and swap in “latest”
for the url instead.
With this someone browsing the docs should get everything with the "latest" url and
only need to use the versioned ones for older versions. If you navigate to the latest
version explicitly it will still work but the links anywhere else will have the "latest"
alias used in them instead so it should get them back on track the next time they
navigate somewhere.
> Use “latest” in sidenav instead of explicit version

- bundle/bundle.go
- bundle/bundle_test.go
- docs/content/bundles.md
When we parse modules we won’t get an error back if the module contents
is empty, but we do get back a `nil` module value.
In the bundle loader we need to catch this before going further with
trying to load the module as it is not actually a valid module and
will break assumptions made about it.
According to the docs Modules must, at a minimum, have a package
declaration. With that in mind this seems like the right behavior to
enforce on the bundled rego files since we treat them as modules.
Fixes: #1393
> Raise error when loading empty module in bundle

- docs/content/rest-api.md
- server/server.go
- server/server_test.go
- server/types/types.go
(I did not create an issue for this as it seemed a quite straightforward minor feature.  If that is desired, please let me know and I'll write one up...  -PWM) 
This patch-set adds a new query parameter to OPA.  The _provenance=true_ parameter will include build/version information in the response to v1 Data GET/POST requests if specified on the URL.
The intent is to enable callers to obtain OPA provenance data along with specific policy responses, certain use cases my want/need to log this information along with other caller-specific datum.
A sample output (prettied) might look like:
```
{
"provenance": {
"build_commit": "61639aab",
"build_hostname": "foo.bar.com",
"build_timestamp": "2019-04-29T23:51:06Z",
"revision": "playful-puppies with-kittens-and-unicorns",
"version": "0.10.8-dev" …
```
> Add 'provenance' query parameter

- docs/content/deployments.md
- docs/content/monitoring.md
- docs/content/rest-api.md
- server/server.go
- server/server_test.go
- server/types/types.go
There is a new parameter for /health REST API which will include the
Configured bundle activation in the response. Example:
GET /health?bundle=true HTTP/1.1
Without the parameter the behavior stays the same, with it the server
will respond with 500’s until the status has been updated with an
activation time.
The docs for kubernetes ready probe has been updated to show this as
it makes for a better ready check than the original behavior when
remote bundles are being used.
Fixes: #1153
> Add param to include bundle activation in /health response

- docs/Makefile
- docs/README.md
- netlify.toml
There are a few drawbacks to different dev approaches with modifying
and testing the website and docs content. This updates the makefile
to include a handful of options and info about when to use them.
This also changes to not use a “live” Hugo service behind netlify when
we run it locally in dev mode. This allows for the local netlify
preview to more accurately reflect the “real” build.
> Update docs dev readme and netlify dev configuration

- ast/term.go
- ast/term_test.go
The deep copy operation was not calling Copy on the set elements. This
manifested in issues in the REPL where parsed queries are retained and
used after the query compile runs. Since the query compile deep copies
the parsed query before mutating it, the REPL's parsed query was
getting corrupted.
Fixes #1406
> ast: Fix set deep copy

- docs/content/code/kubernetes-admission-control-validation/ingress-whitelist.rego
Adds operation support for both CREATE and UPDATE.
This allows OPA to prevent updates to an Ingress when
it conflicts with another namespace.
Only enforcing on CREATE could allow an actor to first
apply a valid ingress and then update to a conflicting one.
> Checks for Ingress on UPDATE

- CHANGELOG.md
- ast/compile.go
- ast/compile_test.go
- docs/content/rest-api.md
- rego/rego.go
- rego/rego_test.go
- repl/repl.go
Each stage of the compiler now has its own timer when instrumentation
is enabled.
To keep things consistent the naming follows the lowercase and
underscore style that the existing ones have. Each stage now needs
to define not only its name but its metric name too.
This does make a change to the ast compiler API by requiring the
additional naming information when adding extra stages.
And example of the new metrics:
```
+----------------------------------------------------------+--------------------+
|                          METRIC                          |       VALUE        |
+----------------------------------------------------------+--------------------+
| counter_eval_op_virtual_cache_miss                       | 1                  |
| histogram_eval_op_plug_75% …
```
> Add additional compiler metrics for each stage

- cmd/eval.go
- cmd/flags.go
- cmd/test.go
- repl/repl.go
- repl/repl_test.go
- server/server.go
- server/server_test.go
- server/types/types.go
- topdown/eval.go
- topdown/notes/notes.go
- topdown/notes/notes_test.go
- topdown/trace.go
- topdown/trace_test.go
These changes extend OPA with an explanation mode that filters trace output to show note events. In addition, to the note events, the filter also includes enter/redo events that explain the rule where the note was emitted. The goal of the filter is to give users a way to easily inspect notes emitted by their policies during debugging.
> Add explanation mode to filter notes

- ADOPTERS.md
Since Automate was made OSS in April, we can link the sources here, I'd think.
> ADOPTERS.md: add some links (Chef)

- docs/Makefile
- docs/content/ceph-authorization.md
- netlify.toml
Some of the behavior for shortcodes inside markdown changed in hugo 0.55.0, and with the old version the shortcodes to insert image tags in our content wasn't working as expected.
Newer versions of hugo handle it correctly, so updating to use the newer version with netlify corrects the problem.
The ceph example also had the wrong shortcode :(
> Fix opa docker image versions in markdown templates

- docs/content/guides-kubernetes-admission-control.md
- docs/content/kubernetes-admission-control.md
Avoid OPA policies stopping changes to OPA's own configuration.
Do the same thing for kube-system.
> docs: Add namespace selector to k8s tutorial

- Makefile
- build/run-wasm-tests.sh
- cmd/build.go
- internal/compiler/wasm/wasm.go
- internal/ir/ir.go
- internal/ir/walk.go
- internal/planner/functrie.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- internal/wasm/instruction/control.go
- internal/wasm/module/module.go
- rego/rego.go
- test/wasm/assets/002_iteration.yaml
- test/wasm/assets/007_complete.yaml
- test/wasm/assets/008_functions.yaml
- test/wasm/assets/009_default.yaml
- test/wasm/assets/010_else.yaml
- test/wasm/assets/011_partialsets.yaml
- test/wasm/assets/012_partialobjects.yaml
- test/wasm/assets/013_extent.yaml
- test/wasm/assets/test.js
- test/wasm/cmd/testgen.go
The PR enables basic support for planning & compiling rules.
There was a bit of churn in the planner as more rule kinds were supported but not too bad. At this point all rules are handled by the same code path. Soon we will want to generate secondary functions for partial object/set rules but that'll likely take a different path.
The next step will be to flesh out support for references to virtual docs. Only refs that refer to the entire virtual doc are supported right now. The next PR will add support for dereferencing and iteration.
> wasm: Add support for rules

- tester/runner.go
The tester.Result#String function was unnecessarily converting the
tester.Result#Duration field into microseconds. This made the reported
latency off by 3-orders of magnitude. This change was only tested
manually because asserting on an expected duration is going to be
flaky.
Fixes #1432
> tester: Fix tester.Result by removing conversion

- build/run-wasm-tests.sh
- test/wasm/cmd/testgen.go
These changes remove the -it flags from the docker run command used to
execute the Wasm tests. This will fix the original issue. In addition,
these changes update the test runner to catch interrupts so that
developers can still ctrl+c out of the test run.
Lastly, update the test generation program to create the directory
hierarchy instead of expecting the caller to do that.
Fixes #1431
> wasm: Fix test runner to catch interrupts

- docs/content/security.md
- server/authorizer/authorizer.go
- server/authorizer/authorizer_test.go
These changes update the server to include request headers in the
authorization input document.
Fixes #1456
> server: Add request headers to authorization input

- docs/website/layouts/partials/home/use-cases.html
In bb0d4e271b9adfbbfed174ae097a45174c7cb4a9 whitespace in the
these sections got wiped out which removed the indentation from the examples.
> website: Fix example indentation on frontpage

- docs/content/configuration.md
- docs/content/decision-logs.md
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/logs/ptr.go
- plugins/logs/ptr_test.go
- rego/rego.go
- rego/rego_test.go
These changes enhance the in-built decision logger to support masking
of input and result fields for cases where sensitive information is
passed to OPA (or generated by the policy.)
Also, fix rego package to avoid panic-ing on programmatically created
queriest that lack Location information.
Fixes #779
> logs: Update decision logger to support masking

- ast/builtins.go
- docs/content/language-reference.md
- topdown/time.go
- topdown/topdown_test.go
Adds timezone support per https://github.com/open-policy-agent/opa/issues/1422.
Signed-off-by: Craig Hooper <craig.hooper@gmail.com>
> Add timezone functionality to builtin time/date functions

- server/server.go
- server/server_test.go
The server was leaking the write transaction when parsing failed which
caused subsequent updates to block. In future we should refactor the
handler implementations to avoid having to manually abort on each
error path.
Fixes #1478
> server: Abort write transaction when parsing fails

- cmd/eval.go
- rego/rego.go
- topdown/eval.go
- topdown/instrumentation.go
- topdown/query.go
- topdown/save.go
- topdown/save_test.go
- topdown/topdown_partial_bench_test.go
- topdown/topdown_partial_test.go
This PR adds basic support for disabling inlining on specific virtual docs. This allows callers with knowledge of the policy to control how much inlining is performed. In some cases this can reduce partial eval latency significantly (e.g., by not having compute cross-products.) In the future we can extend OPA to automatically disable inlining based on a budget, knowledge of underlying base doc collection sizes, etc.
> Add parameter to control partial eval inlining

- docs/content/how-do-i-write-policies.md
This actually goes back to the very first draft of the language
reference.
Fixes #1477
> docs: Fix mention of reference head var

- bundle/bundle.go
- bundle/bundle_test.go
- docs/content/bundles.md
These changes simply update the bundle reader to accept data.yaml
files in addition to data.json files. This allows callers to supply
YAML files to OPA without having to convert them into JSON.
Fixes #1471
> bundle: Add support for loading YAML files from bundles

- cmd/eval.go
- cmd/eval_test.go
It was getting parsed from string -> ast.Term but the generated
parser is (apparently) not as performant as the json parser and then
using `ast.InterfaceToValue`.
Fixes: #1488
> Change `opa eval` input to parse as json first

- docs/content/configuration.md
- docs/content/decision-logs.md
- docs/content/plugins.md
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- runtime/runtime.go
- test/e2e/logs/console_decision_logger_test.go
- test/e2e/testing.go
Add option to log decision logs locally. They'll get logged via
Logrus at info level.
To enable configure OPA with something like:
```
decision_logs:
console: true
```
This will work alongside remote services and plugins. It will also
log the masked events in the case a masking policy is set.
Fixes: #1334
> logs: console decision logging option 

- docs/content/decision-logs.md
A very small change to the docs but I found the current explanation a bit obscure.
https://www.openpolicyagent.org/docs/latest/decision-logs/#masking-sensitive-data
For people who are familiar with JSON Pointers, I thinks it's obvious to use array indices, but for others, maybe it's better to show examples.
In addition, was thinking about adding a detailed example like below but left it as a simple phrase.
`mask["/input/secrets/0"]`
Result (Example of pointers to array not taking effect)
```bash
{
"decision_id": "6b8fda76-ae6c-4b63-b1bb-34384c8c3c7c",
"erased": ["/input/password"],
"input": {
"name": "bob",
"resource": "user",
"secrets": [{ "value": "secret1" }, { "value": "secret2" }]
},
"labels": {
"id": "75f51a30-3906-46b5-bb1e-4da3496de0f6",
"version": "0.13.0-dev"
},
"level": "info", …
```
> Add example of JSON pointers using array indexes.

- docs/website/layouts/partials/docs/navbar-link.html
- docs/website/layouts/partials/docs/navbar.html
We did this for the sidenav urls but the mobile version was still using hard versions instead of "latest".
> docs: Update mobile navbar links to use "latest" tag

- docs/website/assets/js/app.js
- docs/website/assets/sass/toc.sass
- docs/website/layouts/partials/css.html
- docs/website/layouts/partials/docs/sidenav-link.html
- docs/website/layouts/partials/javascript.html
The ToC will now show deeper heading levels as needed, and gives
some visual indication of where you are on the page. This helps a
ton with browsing around and referencing different parts of the docs.
Especially on the REST API and language reference docs that have
a large amount of content between bigger headings.
> docs: Dynamic ToC on website

- cmd/eval.go
- rego/rego.go
- rego/rego_test.go
These changes just add another option to the API to supply parsed
modules directly. This allows tools that rely on the file loader to
skip parsing of modules for a second time when running evaluation. For
large sets of modules this can reduce latency quite a bit.
> rego: Add ParsedModule option to API

- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/plugins.go
- storage/inmem/inmem.go
- storage/inmem/inmem_test.go
- storage/inmem/txn.go
- storage/interface.go
These changes resolve #1515 by caching the compiler created during bundle activation and passing it through to the manager's trigger callback. See the commit messages for a bit more info.
> Fix performance impact of bundle activation on policy queries

- ast/term.go
- topdown/cache.go
- topdown/cache_bench_test.go
- topdown/cache_test.go
Previously the virtual cache was implemented using a
map[ast.Value]... which works for scalar key terms but not composites
(because they're not comparable.) This change updates the virtual
cache to use a util.HashMap that supports all term kinds. This
prevents the virtual cache lookup/insert from panicing when a key like
data.x.y[[1]] is received.
In addition to fixing the virtual cache, this change updates the
Term.Equal() function to include an early-exit for types that do not
allocate in their Equal() functions.
The early-exit was added because swapping out the map[ast.Value]...
for util.HashMap introduced allocations into the virtual cache
lookup/insert operations which doubled the benchmark latency. See
below for benchmark results before/after this commit.
```
BEFORE
======
goos: …
```
> topdown: Fix virtual cache to allow composite key terms

- ast/compile.go
- ast/compile_test.go
- ast/term.go
- ast/term_test.go
These changes just update the safety errors to report the line of the
expression where the error occurred instead of the rule/query that
contains the expressionm. Better locality should make it easier to
identify safety error causes.
Fixes #1497
> ast: Report safety errors on line where expression starts

- topdown/copypropagation/copypropagation.go
- topdown/topdown_partial_test.go
Mutating term values used as object keys (or set elements) is not safe
because the underlying hashtables get corrupted. This a known issue
that was previously fixed in the compiler (#1125). The simplest
solution in this case is to use the ast.Transform helper instead of
ast.Walk so that a copy of object and set terms is made.
Fixes #1177
> topdown: Fix corrupt object panic caused by copy propagation

- ast/index.go
- ast/index_test.go
- docs/content/faq.md
- rego/rego.go
This PR adds support for indexing glob.match statements which are naturally found in policies that interpret wildcards in data (e.g., IAM policies found in #1443). See the commit message for more info/detail.
> Index glob.match statements

- ast/builtins.go
- docs/content/language-reference.md
- topdown/casts.go
> docs: Remove cast_xyz functions from docs

- docs/content/how-do-i-write-policies.md
- docs/content/language-cheatsheet.md
This is a common question that comes up. Until we have a keyword that
lets users express "FOR ALL" we should have docs we can point to.
Fixes #1307
> docs: Add section on how to express "FOR ALL" in Rego

- runtime/runtime.go
- server/server.go
- server/server_test.go
- test/e2e/testing.go
To do this we needed a way to get the actual address that was bound.
To do that we needed to refactor the server and runtime code a tad
to let us create our own `net.Listener`s and get their address _after_
they had been started. The code is pretty much 1:1 with what is in the
official `http` package.
Now when the tests run using the helpers to stand up server runtimes
they should all be on separate ports.. in theory we could run the
unit tests in parallel without concern (for the e2e parts anyway).
Fixes: #1533
> Change e2e tests to bind on :0 instead of :8181

- server/types/types.go
This just tweaks the error string format introduced in #1530 to be
consistent with other error strings in OPA (e.g., topdown, ast, etc.)
> server: Tweak server error string format

- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- server/buffer.go
- server/server.go
These changes update the server to pass the server's open transaction
to the decision logger. This prevents the same goroutine from
recursively opening a new transcation when the log masking decision is
evaluated.
Alternatively we could update the server to close it's transaction
before logging the decision however this could lead to the log masking
decision being generated from a different policy revision. Another
alternative would be extend the storage layer to support recursive
transactions however this would be quite a bit more work.
We should investigate whether we can cheaply detect recursive
transactions in the store to avoid potential deadlocks in the future.
Also, delete opa binary that was accidentally committed to the repo.
Fixes #1543
> server: Pass transaction in decision log event

- .travis.yml
- Makefile
Previously, the Travis configuration would only trigger deployments
for the master branch. Also, the release-travis step would re-tag
:latest which is not what we want for release branches.
These changes add a new Travis deployment for release branches that
does not re-tag :latest and _will_ trigger for tags on release
branches.
> travis: Update Travis deployments to support release branches

- docs/content/configuration.md
It is not very discoverable as to how the `--set` options work when
keys have `.` characters in them. This adds in a section to the config
docs on how to do it.
> docs: Add details for `.`'s in `--set` keys

- internal/storage/mock/mock.go
- plugins/logs/plugin.go
- rego/rego.go
- rego/rego_test.go
This changes a few things transaction related..
* Update the Rego prepared query objects to no longer re-use old storage transactions from the original Rego object. The txn must be specified on each Eval() if you want to use a specific one, otherwise a new one will be opened and closed automatically
* Pass the transaction through to the decision log mask eval
Check out the individual commit messages for some more details.
> Less aborted txns

- docs/content/how-do-i-write-policies.md
The preceding example uses `x>y`, without which the variable `y`
is unused.
> docs: Tweaks to improve consistency

- internal/version/version.go
- plugins/rest/rest.go
- plugins/rest/rest_test.go
- topdown/http.go
- topdown/http_test.go
This can be overridden by custom header configuration for services,
or requests but will default to something like:
`Open Policy Agent/<version> (<os>, <arch>)`
This is set on all outbound requests for status, decision logs, bundle
and discovery downloads, http requests from policies, etc.
> Add User-Agent to rest client as default header

- cmd/fmt.go
Fixes the usage of the `fmt` command to indicate that you can (and must) provide a set of files / paths. This is consistent with other commands like `check`. 
This behavior can be replicated locally by running:
```bash
opa fmt 
```
which hangs forever.
This block of code also indicates this functionality: 
https://github.com/open-policy-agent/opa/blob/1a673b8fd6cc48ec6959cda44994b809dd333e91/cmd/fmt.go#L60-L74
> fixes usage of fmt command

- Makefile
- internal/storage/mock/mock.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/logs/plugin.go
- plugins/plugins.go
- rego/rego.go
- rego/rego_test.go
- storage/inmem/inmem.go
- storage/inmem/inmem_test.go
- storage/inmem/txn.go
- storage/interface.go
This PR backports for the fixes in #1516 and #1551 to the 0.12 release.
> Backport bundle activation performance and log mask race condition fixes 

- cmd/eval.go
- cmd/flags.go
- cmd/test.go
- repl/repl.go
- repl/repl_test.go
- server/server.go
- server/types/types.go
- topdown/lineage/lineage.go
- topdown/lineage/lineage_test.go
These changes add a new explanation mode for filtering fail events during evaluation. These changes also update the tester to use the new mode when running in verbose mode. Since tests only pass if all statements in the test rule succeed, reporting failures should help better identify the source of errors. Once this lands we can explore adding support for output expected vs. actual values (#1581).
> Add new explanation mode "fails"

- ast/compile.go
- ast/compile_test.go
- rego/rego.go
- rego/rego_test.go
- server/server.go
- server/server_test.go
This patch moves the check for unsafe built-ins from the server to the
compiler, so it can be used by the Go API as well as the HTTP API.
This was previously discussed in #1570.
> Move unsafe built-in check to compiler

- docs/content/kubernetes-admission-control.md
I expect many install OPA following this guide (as we did). Recent PRs have made steps to 'productionize' this (e.g. [#1435](https://github.com/open-policy-agent/opa/pull/1435))
We had an incident involving the controller where a stuck container was not restarted. We would have been helped if a liveness probe was configured. We copied the docs and this is our bad but we'd like to do our best to make sure others don't make the same mistake.
I figured it'd be ok to use the health endpoint [here](https://github.com/open-policy-agent/opa/blob/master/docs/content/rest-api.md#health-api)
We've made this change and it seems to be working ok for us.
> Add livenessProbe to demo deployment

- ast/compile.go
- ast/compile_test.go
- ast/errors.go
- ast/parser.go
- ast/parser_ext.go
- ast/parser_internal.go
- ast/parser_test.go
- ast/policy.go
- ast/policy_test.go
- ast/rego.peg
- docs/content/how-do-i-write-policies.md
- docs/content/language-reference.md
- format/format.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
- repl/repl.go
- repl/repl_test.go
These changes remove one of the main differences between the REPL and modules by allowing policies to declare rules with the `:=` operator. The `:=` operator can be used at most once per variable per package. In that sense it behaves similarly to the `:=` operator on variables in queries.
> Add support for declaring rules with := operator

- rego/rego.go
The documentation was updated part way through adding the Prepare
helpers on the Rego object. Later on when PrepareForEval and
PrepareForPartial helpers were added and we stopped re-using
PartialResult this was left behind and is now incorrect.
Fixes: #1619
> rego: Fix godoc for rego.Rego() API

- .travis.yml
- Makefile
These changes update the travis build to produce windows/darwin
binaries in addition to the linux binary and push them to the S3
bucket holding the edge binaries. This lets users on windows/darwin
easily obtain the binary for tip of master. It also enables the live
docs build which is coming soon.
> travis: Build and push windows and darwin edge binaries

- ast/check.go
- ast/check_test.go
- ast/errors.go
Previously the type checker would not sort errors before returning
them. As a result, the ordering of errors would depend on the order of
rules passed to the type checker (which is non-deterministic due to Go
map iteration order.)
These changes update the type checker to sort errors by location
before before returning them. This way the errors reported by opa test
and opa check and everything else are consistent across runs.
Fixes #1620
> ast: Fix ordering of rule type checking errors

- cmd/eval.go
- cmd/run.go
- loader/loader.go
- loader/loader_test.go
The file loader splits paths on the first colon character and uses the
left-hand side for the prefix to root the document at under data. On
windows this is problematic because of drive lettesr (e.g., C:\X\Y\Z
is interpreted as load file at \X\Y\Z under data.C.
This change updates the loader to accept file:// URLs. This way
callers can unambiguously specify filenames that contain colon
characters. For now this will mainly be used by VS Code and other
programmatic callers. In future we can support other schemes (e.g., http).
Ref #1505
> loader: Update to accept file:// URLs.

- format/format.go
- format/testfiles/test_issue_1560.rego
- format/testfiles/test_issue_1560.rego.formatted
The formatter was not starting a new line after writing comments that
preceed an expression. As a result the first part of the expression
written (e.g., "not", function name, "some", etc.) would be written
without any indentation.
Fixes #1560
> format: Fix formatter to start line after writing comments

- server/server.go
- server/server_test.go
Previously the server didn't wrap the error messages which made it
hard to determine the source of internal errors coming back from OPA
when deployed with a custom decision logger.
Fixes #1367
> server: Wrap decision log error messages

- bundle/bundle.go
- bundle/bundle_test.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
We would previously detect overlapping roots on partial path segments
for bundle roots defined in manifests.
This changes to make them be full path segments or else they won't
conflict.
Fixes: #1654
> bundle: Fix for root overlaps on partial segments

- docs/content/bundles.md
- docs/content/monitoring.md
The behavior has since changed and we do check for overlaps.
The warning has been updated to give advice on monitoring for errors
and to describe the somewhat racy nature of loading multiple bundles.
> docs: Update warning for multi-bundle root overlap

- docs/README.md
- docs/website/scripts/live-blocks/README.md
- docs/website/scripts/live-blocks/src/constants.js
- docs/website/scripts/live-blocks/src/web/index.js
- docs/website/scripts/live-blocks/src/web/style.css
- Allow "open" button for read_only blocks.
- Remove erroneous CSS.
- Added a tag for showing line numbers.
> docs: Minor live blocks fixes and improvements.

- ast/compile.go
- ast/compile_test.go
- rego/rego.go
- rego/rego_test.go
- test/e2e/concurrency/concurrency_test.go
Previously the rego package was modifying the compiler's unsafe
built-in set each time a query was evaluated or prepared. This
resulted in concurrent write panics in the server (since the server
and other callers assume the compiler is immutable and can be shared
across goroutines.)
These changes update how unsafe built-ins are specified. The query
compiler continues to inherit the set from the compiler but there are
two important differences:
1. Callers can provide unsafe built-ins to the query compiler. This
allows callers to override the behaviour of the compiler if they need
to.
2. The rego package does not set unsafe built-ins if the compiler is
provided by the caller. This ensures that the compiler is not modified
concurrently.
With these changes the rego package doesn't union …
> ast, rego: Refactor unsafe built-in handling

- internal/wasm/encoding/reader.go
`break` will break switch, `continue` will run next for loop. the two expression get the same result, but continue will eliminate the error in staticcheck [SA4011](https://staticcheck.io/docs/checks#SA4011)
> fix static check error in reader.go

- docs/README.md
- docs/website/scripts/live-blocks/src/constants.js
- docs/website/scripts/live-blocks/src/helpers.js
- docs/website/scripts/live-blocks/src/preprocess/index.js
- docs/website/scripts/live-blocks/src/preprocess/localEval.js
- docs/website/scripts/live-blocks/src/web/index.js
- docs/website/scripts/live-blocks/src/web/playground.js
- docs/website/scripts/live-blocks/test/errors.test.js
- docs/website/scripts/live-blocks/test/helpers.test.js
This is contingent on multi-module support being added to the playground.
> live-blocks: Added an `include(<group name>)` tag.

- server/server.go
- server/server_test.go
The issue was that with bundles loaded from the file system we would
not initialize the mutex used for checking bundle status.
This fixes the initialization and prevents the error. Health status
works as expected now.
Fixes: #1703
> server: Fix panic in /health?bundle=true

- server/server.go
- server/server_test.go
The issue was that with bundles loaded from the file system we would
not initialize the mutex used for checking bundle status.
This fixes the initialization and prevents the error. Health status
works as expected now.
Fixes: #1703
(cherry picked from commit 3248c2d7189d9062590dfbe0637c6cb40c1f4a85)
> [0.13.x] server: Fix panic in /health?bundle=true

- bundle/bundle.go
- bundle/bundle_test.go
- bundle/store.go
- bundle/store_test.go
- cmd/build.go
- cmd/check.go
- cmd/deps.go
- cmd/eval.go
- cmd/eval_test.go
- cmd/run.go
- cmd/test.go
- internal/file/archive/tarball.go
- internal/file/loader.go
- internal/file/loader_test.go
- internal/storage/mock/mock.go
- loader/loader.go
- loader/loader_test.go
- metrics/metrics.go
- plugins/bundle/plugin.go
- rego/example_test.go
- rego/rego.go
- rego/rego_test.go
- runtime/runtime.go
- runtime/runtime_test.go
- tester/runner.go
- util/test/tempfs.go
This adds a `-b`/`--bundle` CLI param to opa eval, build, and test. To support this there are a bunch of underlying changes in the loader and bundle packages. Check out the individual commits for some more details. At a high level it changes:
* Support for multiple bundles being activated at the same time.
* Adds abstraction for loading files from a directory tree (archived or on the filesystem)
* Adds APIs to the Rego object to provide a path to either directory or file and load it as a bundle or via the file loader with a filter.
* Change some transaction lifecycle stuff in the Rego object to support writes/commits when loading files.
* Adds thee CLI parameters that use the new Rego params.
> Add support for loading bundles via CLI params

- cmd/eval.go
- cmd/eval_test.go
- docs/Makefile
This fixes the formatting for the output of `opa eval` and makes a quality of life change to the docs makefile to ease troubleshooting.
> Fix eval formatting

- bundle/bundle.go
- bundle/bundle_test.go
- bundle/store.go
- bundle/store_test.go
- cmd/check.go
- cmd/deps.go
- cmd/eval_test.go
- plugins/bundle/plugin_test.go
- plugins/discovery/discovery.go
- rego/rego.go
- tester/runner.go
Previously we would internally reference modules by only their `path`
which was, for data files, the system path but bundles it is relative
to the root of the bundle. In theory data paths and bundle paths could
collide, but the real trouble is caused by multiple bundles. It was
very easy to have two bundles with identical file paths but different
packages and policies defined in them.
Internally we now reference bundle module id's as a combination of the
bundle name (or the file path for the bundle if loaded from CLI) and
the path within the bundle.
This does change the `id` a particular policy will show up at via the
storage ListPolicies and in turn REST API for OPA. This only affects
users that have switched to the `bundles` configuration option, or
that are using the `-b`/`--bundle` …
> bundles: Fix duplicate file names overriding modules

- cmd/eval.go
- cmd/fmt.go
- internal/file/url/url.go
- internal/file/url/url_test.go
- loader/loader.go
Users should be able to pass file:// URLs to any of the
sub-commands. In 3be55ed6 the eval and fmt sub-commands were not
updated to accept file:// URLs for the input file and normal paths
(respectively).
This commit just moves the unexported cleanFileURL function from the
loader package into it's own internal package so that it can be shared
in OPA.
> cmd: Fix eval and fmt to support file:// URLs

- bundle/bundle.go
We would previously use whatever host specific paths we got but this
could potentially cause problems. This now forces all paths to be
`/` separated to help simplify some of the code handling them
internally.
Fixes: #1713
> bundle: Normalize paths to use `/` separators

- docs/content/management.md
- plugins/discovery/config.go
- plugins/discovery/config_test.go
Signed-off-by: omerlh <omerl@soluto.com>
close #1714
In the issue, we also discussed enabling to change only services that are not used by discovery. I think this should be moved to a separate issue, as currently it is not supported at all to change service by discovery.
I'll be happy to get feedback on the changes - added `Service` field to discovery, exactly like in bundle source. If that looks good, I'll add tests + documentation.
> allow to configure more then 1 service with discovery

- docs/website/layouts/404.html
- docs/website/layouts/index.redirects
In the re-org we got rid of the getting started section and instead
have a more comprehensive/interactive introduction page. This change
adds a redirect to send /docs/latest/get-started URLs to /docs/latest
instead.
We also remove the link to it in the custom 404 page. Its the same
as the documentation URL now.
> docs: Add redirect for /docs/latest/get-started

- Dockerfile.fuzzit
The build is failing and the fuzzer output does not indicate what is
going wrong. The newest fuzzit behaves differently and seems to do
more work during the local-regression job. Updating to the latest to
see if this fixes it.
> build: Update to latest version of fuzzit

- repl/repl.go
- repl/repl_test.go
The REPL's internal state was getting corrupted if an invalid unknown
term was given. For example `unknown x-1` would result in the unknown
set being allocated but it would contain an illegal nil element.
This fix just updates the REPL to avoid corrupting the internal state
if any of the unknown arguments are invalid.
Fixes #1670
> repl: Fix unknown argument processing

- bundle/bundle.go
Turns out on windows the filepath.Dir() call will give back paths that
are using `\` separators. This is problematic when we then go to split
the path with `/` to get the key. We need to make sure they are always
normalized to `/` separators.
Fixes: #1713
> bundle: Ensure data paths use `/` separators for key

- docs/content/_index.md
- docs/website/layouts/index.redirects
This gives nicer download URLs for OPA binaries via:
`https://openpolicyagent.org/downloads/<version>/<binary>`
Under the hood we just use Netlify to rewrite the url to the normal
github and s3 locations.
With this you can also use:
`https://openpolicyagent.org/downloads/edge/<binary>`
and
`https://openpolicyagent.org/downloads/latest/<binary>`
For quick links to the current master and latest release binaries.
Fixes: #1771
> docs: Add pretty download URLs

- docs/website/layouts/shortcodes/current_opa_istio_docker_version.html
Since the url for the latest released version of the docs does not contain the OPA version, this change updates the shortcode to use the latest-istio tag for the opa-istio image for latest and edge versions of the OPA docs.
> docs: Fix opa-istio image version for latest version of the docs

- docs/content/management.md
- docs/content/rest-api.md
We pulled the config docs out into their own section from the
/management page. In the process we missed some links that needed
updating.
> docs: Fix config reference doc links

- CHANGELOG.md
- Dockerfile.fuzzit
- Makefile
- bundle/bundle.go
- docs/content/_index.md
- docs/content/management.md
- docs/content/rest-api.md
- docs/website/layouts/index.redirects
- docs/website/layouts/shortcodes/current_opa_istio_docker_version.html
- docs/website/scripts/live-blocks/src/preprocess/acquireOPAVersion.js
This PR includes a handful of cherry-picked fixes for documentation and bundle manifests for windows. I grouped them together with the updates to prep a v0.14.1 release.
> v0.14.1 backports and release prep

- ast/check.go
- ast/compile.go
- ast/compile_test.go
Previously, references to undefined functions were caught after the
safety check ran. As a result, if the function call contained one or
more unsafe variables, the compiler would report safety errors instead
of undefined function errors. This would hide the source of the
problem and result in confusion. For example, before:
> data.deadbeef(x)
1 error occurred: 1:1: rego_unsafe_var_error: var x is unsafe
After:
> data.deadbeef(x)
1 error occurred: 1:1: rego_type_error: undefined function data.deadbeef
Fixes #1141
> ast: Check for undefined functions before safety check

- bundle/bundle.go
- bundle/bundle_test.go
- internal/merge/merge.go
- internal/merge/merge_test.go
- loader/loader.go
This fixes the issue where the order of data files changed the end resulting data object loaded from bundles.
The main issue being that we were not merging the data files consistently, we would allow later data files to overwrite keys, or (if at the root path) the entire document.
This now shares the same merge algorithm that the loader uses.
Fixes: #1763
> bundle: Fix for overwriting data file keys

- Dockerfile
We use the gcr.io/distroless/base:debug tag for the *-debug images of
OPA. At the point where we switched to the multi-stage build we dropped
defining the `VARIANT` argument so it wasn't being picked up correctly.
This lead to us just using gcr.io/distroless/base for the *-debug
image.. which isn't what we wanted.
> Fix *-debug docker images to be ":debug" tag based

- docs/content/configuration.md
- docs/content/management.md
- plugins/discovery/config.go
- plugins/discovery/config_test.go
This makes the configuration of discovery bundles match the newer
`bundles` config style more closely.
The older style configuration with `prefix` is still supported (the
default behavior is still there if neither `resource` or `prefix` is
provided). It has just been marked as deprecated.
Fixes: #1597
> discovery: Support `resource` configuration option

- topdown/eval.go
- topdown/eval_test.go
- topdown/topdown_test.go
Previously this would raise an error when attempting to build the
storage path for some ref like `data.foo[["bar"]]`, but there isn't
really any reason why it should halt evaluation. It should just
be undefined.
This changes to look for this type of ref _before_ handing it off to
the store and will just return undefined now instead.
Fixes: #1057
> topdown: Base document dereference with composite

- ast/parser_ext.go
- ast/parser_test.go
- cmd/check.go
- cmd/eval.go
- cmd/eval_test.go
- cmd/parse.go
- internal/presentation/presentation.go
- internal/presentation/presentation_test.go
- loader/errors.go
- loader/loader.go
- rego/rego.go
- repl/repl.go
- server/server_test.go
Previously if the errors passed into the presentation Output were not
structured w/ JSON tags for marshaling the error would be an empty
string.
This changes to wrap the errors with a struct in cases where they
would otherwise not be formatted. We do this by forcing every error
into a structure and translating known error types into it.
> Ensure all errors are in JSON formatted CLI output

- internal/ir/pretty.go
- internal/planner/planner.go
- internal/planner/planner_test.go
- test/wasm/assets/014_comprehensions.yaml
This PR adds support for comprehensions in wasm compiled policies. The backend did not have to be changed since we already have built-ins for constructing collections dynamically.
> wasm: Add support for comprehensions in the planner

- internal/planner/planner.go
- test/wasm/assets/002_iteration.yaml
This commit updates the planner to support composite reference
operands, e.g., p[[1,x]]. The planner generates a dot operation if
the operand does not contain any free variables. Otherwise the
planner generates a scan operation and then unifies the scan key
with the reference operand before continuing.
> wasm: Add support for composite reference operands

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/strings.go
- topdown/strings_test.go
This commit adds the following string trimming builtins
- TrimLeft(s string, cutset string) string
- TrimPrefix(s, prefix string) string
- TrimRight(s string, cutset string) string
- TrimSuffix(s, suffix string) string
- TrimSpace(s string) string
Signed-off-by: Hasit Mistry <hasitnm@gmail.com>
> Add Additional String Trimming Functions

- internal/file/loader.go
When loading files we would build the list with, on windows, potential
paths with backslashes rather than forward slashes. This is
problematic because the check to trim the prefix for returning file
descriptors based on the root of the bundle.. On windows it could, in
some cases, fail to do so. This results in additional prefixes on the
loaded data.
> file/loader: Standardize on forward slash paths

- topdown/bindings.go
- topdown/eval.go
- topdown/query.go
- topdown/topdown_partial_test.go
This change fixes an issue in partial eval where variables in negated
expressions were getting plugged with the wrong set of caller
bindings. The caller bindings identify the context in which plugging
is being performed so that variables can be namespaced and conflicts
can be avoided.
For example, given the query `p[x]` and the rule `p[y] { y = input;
not y = 1; ... }` the first expression in the rule body would
eventually be plugged in the context of the calling query whereas the
second expression would be plugged using a special set of bindings
that ensured namespacing was performed. The problem was that the
partial eval negation implementation was incorrectly choosing the
special binding set.
This change updates partial eval to use the bindings from the top of
the evaluator stack in …
> topdown: Fix namespacing to use caller bindings

- docs/content/envoy-authorization.md
- docs/content/extensions.md
There was one dangling reference to plugin directory in the [Custom Plugins for OPA Daemon|https://www.openpolicyagent.org/docs/latest/extensions/#custom-plugins-for-opa-daemon] documentation and one to plugin-dir in the envoy authorization example.
> Remove mention of plugin directory

- docs/website/scripts/live-blocks/src/constants.js
- docs/website/scripts/live-blocks/src/preprocess/acquireOPAVersion.js
- netlify.toml
This changes to no longer download the `edge` release binary (we still
publish one for anyone who wants to use the current master). This way
for PR's and for development we are going to process the `edge`
documentation with the version of OPA that is the current HEAD. For
the live site this will always be the current master branch.
> docs: Preprocess live-blocks with current OPA HEAD

- topdown/parse_bytes.go
> topdown: Fix units.parse_bytes implementation to use int64

- ast/index.go
- ast/index_test.go
- rego/rego.go
- rego/rego_test.go
- topdown/eval.go
- topdown/query.go
For debugging we would like to have the ability to retrieve all rules
from the Index rather than the filtered ruleset. This API will simply
walk the tree and collect all of the rules.
This allows a client making evaluations to disable the rule indexing,
which particularly useful for debugging purposes.
Essentially this boils down to just calling `AllRules()` versus using
the `Lookup()` API on the index.
There is plumbing included to pass the flag in from the rego API's
down through to the topdown eval.
> Add API to disable rule indexing for evaluation

- ast/compile.go
- ast/compile_bench_test.go
- ast/compile_test.go
- ast/example_test.go
This adds a map of rewritten variables to the `ast.Compiler` and makes them unique from `queryCompiler` variables which now will be in the form of `__qlocalX__` to distinguish them.
The map of rewritten variables will be handy for resolving names for user facing messages (errors, tracing, etc).
> Add map of rewritten vars to Compiler

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/regex.go
- topdown/regex_test.go
- topdown/strings.go
- topdown/strings_test.go
Added the following functions inside the stdlib of go.
* [Regexp.FindAllStringSubmatch](https://golang.org/pkg/regexp/#Regexp.FindAllStringSubmatch) -> `regex.find_all_string_submatch_n`
* [Replacer.Replace](https://golang.org/pkg/strings/#Replacer.Replace) -> `replacer.replace`
Related Issue: #1804 
I'm not sure about the name of the function 🤔 Seems a bit long but couldn't come up with a better one.
Also, this is my first contribution to the code base. Apologies if I'm missing something.
> Add builtins related to string replacement

- docs/content/policy-reference.md
This commit fixes a typo in `policy-reference.md` file where the second parameter in `trim_suffix(...)` function should be `suffix`.
Signed-off-by: Hasit Mistry <hasitnm@gmail.com>
> Fix typo in Strings section of policy-reference.md

- docs/content/kubernetes-debugging.md
- docs/content/kubernetes-introduction.md
- docs/content/kubernetes-primer.md
- docs/content/kubernetes-tutorial.md
Previously the docs detailing the OPA-k8s integration only distinguished
between v1 (kube-mgmt) and v3 (gatekeeper) in the introduction page.
The debugging, primer, and tutorial pages did not explicitly state
which version they were detailing.
This change clarifies that those pages refer to the kube-mgmt
version and provide a pointer to the Gatekeeper readme.
> docs: Clarify kube-mgmt/Gatekeeper K8s docs

- cmd/eval.go
- cmd/eval_test.go
b0c875c374b7f9723612269ebdc4db55d5b8bb42 missed the profiling
tracer. As a result, the profiling tracer was not being used during evaluation.
> cmd: Fix opa eval to specify profiler tracer correctly

- ast/map.go
- cmd/eval.go
- cmd/eval_test.go
- tester/reporter_test.go
- topdown/eval.go
- topdown/trace.go
This adds a new option for eval which will disable indexing so
that variable bindings for rules that would otherwise not evaluate
can be found.
This also adds to (and corrects) the JSON marshalled trace events. We
now have extra metadata about the local variables, a working JSON
marshaller for the `Locals` (which includes type info), and the event
nodes location information.
Fixes: #1697
> Add debug tracing mode

- cmd/test.go
- tester/runner.go
- tester/runner_test.go
Implement the test timeout at individual test level to make it easier to scale rego test when using the --timeout flag.
Fixes #1788
> Timeout flag on individual test cases in opa test command

- bundle/bundle.go
- bundle/bundle_test.go
- loader/loader.go
- rego/rego.go
The newer output ensures that the bundle name is shown, the roots being used, and a better representation of the path in question.
> bundle: Add more details to manifest root errors

- docs/content/_index.md
The introduction referred to partial set rules as incremental rules
which is a bit misleading/confusing. This change just updates the
introduction to refer to partial rules instead of incremental rules.
> docs: Fix introduction to refer to rules consistently

- rego/rego.go
- topdown/eval.go
- topdown/query.go
- topdown/trace_test.go
This plumbs through the query compiler to the topdown query and eval
objects. We then use it to get rewritten vars when creating trace
events.
> topdown: Provide rewritten query vars in traces

- ast/policy.go
- ast/policy_test.go
Previously when a module was unmarshalled from JSON the rules
contained in the module would not have their module pointers set. This
would cause the Path() function on the rule objects to panic.
This change updates the module struct to walk the rules and set the
module pointer accordingly.
This was discussed in #1780
> ast: Fix module JSON unmarshalling

- types/types.go
- types/types_test.go
If a negative array index was hardcoded in the policy it would cause a
panic (e.g., arr[-1]). This patch just fixes the select function to
return nil like it does for out-of-bounds.
> types: Fix constant select on array types

- internal/planner/planner.go
- test/wasm/assets/013_virtual.yaml
This change updates the planner to generate breaks when the virtual
node is empty. Previously the planner was NOT generating breaks which
meant that if the base path dereferencing failed, execution would
simply continue from the next statement in the query (or if this was
the last statement in the query, a result would be generated.)
> wasm: Fix planning of virtual document extent

- build/run-wasm-rego-tests.sh
- test/wasm/cmd/wasm-rego-testgen/main.go
This patch has a few small changes to the generator and bash script:
* Accept out-of-tree asset directory in run script
* Accept YAML _and_ JSON asset files
* Accept runner path as separate argument
These changes make it easier to run tests from places other than the
in-tree asset dir.
> wasm: Small improvements to the test generator

- internal/planner/planner.go
- test/wasm/assets/009_default.yaml
The planner was assuming that default rule values were always
constants however they just need to be guaranteed to be defined at
runtime. The semantic checks in the compiler permit comprehensions so
the planner has to run query planning on the rule body.
> wasm: Plan default rule bodies

- internal/planner/planner.go
- test/wasm/assets/008_functions.yaml
The planner was not checking call expression results for false return
values that ought to cause evaluation to fail. This meant that
evaluation would continue to the next expression.
> wasm: Fix planner to check call expression for false return value

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
- topdown/topdown_test.go
Instead of changing the behaviour of the body parameter (which is
always sent as JSON) just add a new parameter that gives the caller
complete control over the message body.
Fixes #1903
> topdown: Add raw_body parameter to http.send

- bundle/bundle.go
- bundle/file.go
- bundle/file_test.go
- loader/loader.go
Previously we had it in an internal package but used by a public API,
which basically means it can't actually be used outside of OPA.
Initial thinking was that this was an OK situation, but by popular
demand we are making it available to everyone so OPA as a lib users
can use the bundle loading API's.
Fixes: #1840
> bundle: Make the DirectoryLoader public

- docs/website/scripts/live-blocks/src/web/playground.js
The playground changed to just return a null result rather than
returning a 4xx error for the response. We need to catch this case
and raise the expected OPAError in the live blocks scripts to keep
the UI behavior the same.
> live-blocks: Fix for new playground undefined eval response

- docs/content/integration.md
- docs/content/wasm.md
Based on the changes in #1899 this adds in docs for how to use the Wasm feature.
There is probably more we can/should include but this seemed like a pretty good starting point.
> Add wasm doc content

- cmd/eval_test.go
- topdown/eval.go
- topdown/trace.go
- topdown/trace_test.go
For the longest time, topdown traces have included rewritten/mangled
variable names. This makes it difficult for people to understand the
trace because the variable names they used in their policy do not show
up in the trace. Now that we have the rewritten variable map readily
available during evaluation we can easily provide the user-supplied
variable names.
Technically this commit just fixes the presentation problem. The
inclusion of the variable mapping was done in
d1522c647594264ef5996621d3ae3d0d739d19b1.
This change also updates the trace emitting code to include local
metadata for all vars that appear in the AST node instead of just vars
that have bindings. This allows us to unmangle all variables in the
node (e.g., otherwise it would not be possible unmangle Enter nodes.)
Fixes …
> topdown: Fix trace to unmangle variables

- topdown/tokens.go
- topdown/tokens_test.go
We were previously ignoring any keys beyond the first index in a set
of keys contained in a JWKS provided to the JWT builtins. We now will
attempt to use any of the keys found.
In addition we no longer raise an error if the key type doesn't match
the header. We will return the correct result as if the verification
failed (because it did..)
Fixes: #1901
> topdown/tokens: Fix verifying with multi-key JWKS

- docs/content/wasm.md
- docs/website/assets/sass/docs.sass
- docs/website/assets/sass/style.sass
We use the `opa-keep-it-together` class all over in the policy
reference page, but it wasn't actually defined anywhere. At some point
we must have lost it.
This adds back in a definition for it and configures things so that
the function signatures will no longer word wrap.
Going along with this is a tweak to the bulma content width by
slimming down the `$gap` size for `.container`'s. For more info see:
https://bulma.io/documentation/layout/container/
End result is that the doc content is now taking up more of the
available space on the screen which helps display the tables of
built-in functions a little bit better. We may want to consider a
different format for the in the future.
> docs: Fixup style for function signatures

- docs/content/_index.md
Without a default value the example would try and use `allow` for
the default query, which then fails.
This also completes the CLI commands to reference the policy file
shown earlier in the docs.
This makes it behave the way the guide seems to assume it will.
> docs: Update intro for running OPA as server

- docs/website/scripts/live-blocks/src/constants.js
- docs/website/scripts/live-blocks/src/web/index.js
This was changed as part of the homepage rework but ended up being
both unused and broken.. so reverting it back to the way it was
before.
The live blocks on the home page are not interactive, so this works
out fine as-is. In the future we may need to revisit.
> docs/website: Fix live-blocks interaction on edge/live pages

- bundle/store.go
- rego/rego_test.go
Previously we would have a value for the `timer_rego_module_compile_ns`
metric but it was always 0.
Turns out we never actually called start() and stop() on it. The unit
tests were just checking if it existed so this slipped by.. This
commit fixes both issues.
> bundle: Fix for module compile metric

- bundle/bundle.go
- cmd/check.go
- cmd/deps.go
- docs/content/configuration.md
- docs/content/management.md
- download/download.go
- internal/presentation/presentation_test.go
- loader/errors.go
- loader/loader.go
- loader/loader_test.go
- metrics/metrics.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/bundle/status.go
- plugins/logs/plugin.go
- plugins/status/plugin.go
- plugins/status/plugin_test.go
- rego/rego.go
- runtime/runtime.go
- tester/runner.go
This combines a few commits that are all related to correct and enhance metrics for parsing/compiling bundles and other files with OPA.
At a high level:
* Adds a new more easily extendable (and mock-able) interface for loading files. The first of these extensions is an API for supplying metrics.
* Update the implementation of the file loader and bundle reader to use metrics objects everywhere that we parse or compile anything.
* Plumb through metrics from downloader to bundle status updates.
* To make it easier to test/see the bundle status updates I added the `console` logging option for status.
> Fix parse metrics and plumb through to bundle status

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/builtins.go
- topdown/cidr.go
- topdown/cidr_test.go
- topdown/eval.go
In some cases, policies may need to expand CIDRs to check if hosts in
the range are valid (e.g., due to limitations of external APIs being
accessed from inside the policy.)
This change adds a built-in function to enumerate the addresses in a
CIDR. The built-in function supports cancellation in case the range is
too large and taking too long to generate.
> topdown: Add net.cidr_expand built-in function

- CHANGELOG.md
- metrics/metrics.go
- rego/rego.go
- server/cache.go
- server/cache_test.go
- server/server.go
- server/server_test.go
This adds in caching of prepared queries for versioned and unversioned
data queries (POST/GET to `/`, `/data`, and `/v1/data`).
The cache has a max size of 100 and just starts acting as a circular
buffer for queries (FIFO, no smarts for LRU caching or anything). It
seems like it would be unlikely for these API's to hit the cache max
size. Most OPA use-cases have a single query that is re-used over
and over with different inputs.
There is a new metric `counter_server_query_cache_hit` which will
show whether or not a request used the query cache or not. It is there
primarily to help explain away why sometimes a handful of the other
metrics aren't there (the query parse/compile/etc).
In the future this could be added to the query API's too. This change
does not touch anything other than the …
> server: Cache PreparedEvalQuery's for data requests

- bundle/bundle.go
- bundle/bundle_test.go
- loader/loader.go
- loader/loader_test.go
When reading a bundle from a directory we should be using the full
system path for the module files. This helps greatly with reducing
complexity of trying to read error messages. It also makes the
integration with tools like VSCode work better as they can provide
links from the console output file paths to the file in question.
This will not affect bundles loaded from tarballs.
> bundle: Use full system path for bundle dir

- ast/compile.go
- ast/compile_test.go
- ast/parser.go
- ast/parser_internal.go
- ast/parser_test.go
- ast/rego.peg
- ast/term.go
- ast/term_test.go
- docs/content/policy-language.md
- docs/content/policy-reference.md
- topdown/topdown_test.go
This allows the reference operator to work in more places, namely:
-  After partial rules, e.g.:
split("foo.bar", ".")[1]
-  After array/set/object terms, e.g.:
[1, 2, 3][i]
{"foo": 1}.foo
-  After array/set/object comprehensions, e.g.:
concat(", ", ["Hello", name]) | {"Tom", "Jerry"}[name]][1]
This change was originally requested in #1868.
> Allow indirect references

- cmd/build.go
Before, this would only return an error if there was no query argument.
However, I've run into this recently, running the erroneous command
opa build -o out.wasm 'data.simplest.allow = x' simplest.rego
which produced no error, the resulting wasm file wasn't what I was
expecting.
With this change, the bad command line would give an error; and might
prompt the user to re-read the usage text and provide the proper command
instead,
opa build -o out.wasm -d simplest.rego 'data.simplest.allow = x'
----
Alternatively to how it's done here, we could have provided the cobra
field
Args: cobra.ExactArgs(1),
but the PreRunE function has a more specific error message. So, I've
taken the message from `opa deps`.
> cmd/build: return error if there is more than one positional argument

- docs/content/rest-api.md
fix a minor indentation issue with API doc:
https://www.openpolicyagent.org/docs/latest/rest-api/#create-or-update-a-policy
Signed-off-by: Long Zhou <longz@vmware.com>
> Fix API doc indentation

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/crypto.go
- topdown/crypto_test.go
**What**
This PR extends REGO with three hashing functions: md5, sha1, and sha256.
**Why**
Since starting using OPA, we've been struggling with exceptions. With this PR, dealing with exceptions becomes easier as the `input` can be hashed and saved in rego as part of an exception list (the example below is using conftest - see _deny[msg]_):
```rego
package pr_demo
exceptions_list = [
"227bddb92cf471d1ca0e549cefcffa77783289be74eb4008d5b108f817669586",
"e29b6884b1bdf94598f8a64b252323224ab037ba647aa830bf0993e7949567c0",
]
is_an_exception {
i := sha256(json.marshal(input))
i == exceptions_list[_]
}
whitelist_images = [
"alpine",
]
image_is_whitelisted  {
input[i].Cmd == "from"
val := input[i].Value
contains(val[0], whitelist_images[_])
}
deny[msg] {
not is_an_exception
not image_is_whitelisted …
```
> Extending REGO with hashing functions

- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
Previously it would pass a reference to the status map on the plugin,
which is potentially dangerous as the map can be changed (happens
explicitly on plugin reconfigure).
This now gives each bulk listener their own copy of the map.
Fixes: #1962
> plugins/bundle: Pass copy of status to bulk listeners

- docs/content/kubernetes-tutorial.md
Minor PR to update the docs for more recent K8s versions as current tutorial will fail.
> Add note for more recent Kubernetes versions

- Makefile
changes the user id for the rootless image from 1 to 1000, to keep it out of the system allocated uid range (0-99)
> changes user id form 1 to 1000

- ast/compile.go
- ast/compile_test.go
- topdown/topdown_test.go
As @tsandall commented in #1868, there appeared to be a problem with
indirect references that have user-defined functions:
> f(x) = [x] { true }
Rule 'f' defined in package repl. Type 'show' to see rules.
> f(1)[0]
1 error occurred: 1:1: rego_type_error: undefined function f
The problem is that this `f` was not resolved to `data.repl.f` by the
`ResolveRefs` phase: with the new AST that supports indirect references,
we need to recursively call `ResolveRefs` in more cases.
> Resolve references inside indirect references

- docs/website/scripts/live-blocks/src/web/style.css
Very minor PR because I'm an idiot (See #1995) and didn't notice the buttons on existing docs site in the liveblocks. 
This makes them bigger, left is with change. Right is without change. 
Note: Made the change based off the browser devtools, do I need to deploy to netify to test as part of the PR, felt relatively contained so haven't done so.
> Bigger buttons on liveblocks

- ast/index.go
- ast/index_test.go
The rule indexer was incorporating expressions that met the = or
glob.match requirements even if they had a with statement
applied. This caused false negatives for the index lookup result. In
practice, it's highly unlikely that users would write expressions that
could be indexed that also include with statements (e.g., `input.a = 1
with ...`) so it's unlikley that anyone is affected.
> ast: Do not index expressions containing with statements

- rego/rego.go
- rego/rego_test.go
There was a typo from a while back that caused problems with this. It
would only occur in cases where the Rego object was created without
tracers, prepared, and then partially evaluated with tracers supplied
as part of the evaluation context. Any of the other code paths would
actually work as the original Rego object would still have them and
the (wrong) reference wouldn't cause a panic.
At some point more recently we changed `opa eval` to split up its
options for the Rego object and evaluation. Doing this caused the
problem to surface when doing anything with `opa eval -p --explain ..`
Fixes: #2007
> rego: Fix panic when partial evaluating w/ tracers

- topdown/trace.go
- topdown/trace_test.go
This commit fixes a bug in the var rewritting improvement that was
introduced in v0.16.0. With this change the rewriting is performed on
the deep copied node as it should be. Also, this change updates the
rewriting to use the ast.TransformVars helper instead of the generic
visitor so that object keys and sets are handled properly.
Fixes #2022
> topdown: Fix bug in var rewriting during trace formatting

- ast/check.go
- ast/compile.go
- ast/index.go
- ast/parser_internal.go
- ast/policy.go
- ast/pretty.go
- ast/term.go
- ast/term_test.go
- ast/unify.go
- ast/visit.go
- ast/visit_test.go
- dependencies/deps.go
- format/format.go
- rego/rego.go
- repl/repl.go
- topdown/bindings.go
- topdown/eval.go
Unlike the generic Walk implementations, they don't necessitate allocating the visitor itself from heap.
This deprecates ast.Visitor, ast.BeforeAndAfterVisitor, ast.Walk, and ast.WalkBeforeAndAfter.
Benchmarks changed:
name                                  old time/op    new time/op    delta
PartialEval/1-16                        6.41µs ± 1%    6.35µs ± 1%   -1.01%  (p=0.001 n=10+10)
PartialEval/10-16                       6.47µs ± 1%    6.37µs ± 1%   -1.48%  (p=0.000 n=10+10)
PartialEval/100-16                      6.81µs ± 1%    6.78µs ± 1%   -0.44%  (p=0.041 n=9+10)
PartialEval/1000-16                     6.64µs ± 2%    6.57µs ± 2%   -1.02%  (p=0.037 n=10+10)
PartialEvalCompile/1-16                 3.08ms ± 0%    2.99ms ± 0%   -2.73%  (p=0.000 n=8+9)
PartialEvalCompile/10-16 …
> ast: Generic/BeforeAfter/Var Visitor specific Walk implementations.

- docs/content/envoy-authorization.md
Before, this would have been valid rego, but its meaning probably wasn't what was intended, compare:
```
> 1 < 2 <= 3
true
> 1 < 2
true
> true <= 3
true
> 1 < 1 < 3
true
> 1 < 1
false
```
> envoy-authorization: fix token validity code

- docs/content/envoy-authorization.md
I wasn't aware of time.now_ns() _caching_:
https://github.com/open-policy-agent/opa/blob/89c7f4b28fe84/topdown/time.go#L25-L39
To not give anyone the same (false) impression, let's fix this.
> envoy-authorization: de-clutter time.now_ns() usage

- ast/parser_ext.go
- ast/parser_test.go
If the module contained a some statement the parser would panic. This
change fixes the parser to just return an error indicating the some
statement cannot be interpreted as a rule.
> ast: Fix panic in module parsing

- CHANGELOG.md
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- server/server.go
The logger was swapping `.`'s with `/`'s but this isn't safe when a
valid path should be /foo/a.b.c/main. The server was already doing
the right thing by passing in the url path where applicable, or only
specifying a query instead of the path.
This might affect anyone using the decision logger golang API passing
in something in dot-notation and expecting it to come out with paths.
Anyone using the HTTP server should be unaffected.
Fixes: #2031
> decision logger: Leave the path unchanged for decisions

- topdown/glob.go
- topdown/glob_test.go
The documentation says that the default delimeter for glob is `["."]`
but the implementation did not actually do this (for the normal built
in).
This corrects the implementation to actually default to the correct
value when it is omitted.
Fixes: #2039
> topdown: Correct glob default delimeter

- docs/content/policy-reference.md
We may want to wait with merging this until #2039 has been fixed as it will ensure that the built-in function works as intended.
> Fix glob docs

- docs/content/extensions.md
- docs/content/kubernetes-tutorial.md
- docs/content/management.md
- docs/content/monitoring.md
- docs/content/rest-api.md
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/logs/plugin.go
- plugins/logs/plugin_test.go
- plugins/plugins.go
- plugins/plugins_test.go
- plugins/status/plugin.go
- plugins/status/plugin_test.go
- server/server.go
- server/server_test.go
- server/types/types.go
This PR adds in a concept of plugin's being able to report their own status to the plugin manager. There is then plumbing added for status update listeners, which the status plugin does. The OPA server has been updated to use the plugin statuses for the bundle and discovery plugin to more correctly report on `/health?bundle=true` for readiness probes (it used to not include discovery at all). In addition the server has a new option for `/health?plugins` that will return a status based on _all_ plugins registered (and reporting status). This gives plugin developers a way to influence the result of the health check if a plugin goes into an error state or needs time to initialize.
Its broken up into smaller bite-sized commits, each with a commit message explaining more about what changed. …
> Add plugin status plumbing and update server to use it

- docs/content/management.md
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/bundle/status.go
This commit updates the bundle plugin to record the last successful
download _attempt_ timestamp in the bundle status. This way Status API
implementations can easily check whether the OPA has been able to
recently check-in for bundle updates.
Fixes #2009
> plugins/bundle: Include last successful request timestamp in status

- ast/compile.go
- ast/compile_test.go
Vars declared as rule args were not being rewritten which lead to
namespace conflicts with built-in functions. For example, definitions
like `f(object) { object[x] = 1 }` would generate type checking errors
because the checker would treat `object[x] = 1` as referring to the
`object` built-in function namespace.
This change updates the compiler to rewrite rule arguments just like
it does other declared variables.
Fixes #2080
> ast: Fix rewriting vars in rule args

- internal/presentation/presentation.go
- repl/repl_test.go
- topdown/trace.go
- topdown/trace_test.go
This PR adds another method to the topdown trace package for printing traces with location information. The location information max length is capped at 19 characters (15 for file size, a colon, and 3 for line information). Filenames will be concatenated if over 15 characters long.
Fixes #2070
Signed-off-by: Lennard Eijsackers <lennardeijsackers92@gmail.com>
> Add location information into pretty printed trace output.

- dependencies/deps.go
In iterating the refs, the skipping state was not resetted between
iterations.
This is an unintended regression of
c44f3d714c15d4b345022d5ee8f93a8e81d608d3.
> dependencies: resolveRemainingVars incorrectly does not skip the refs.

- build/gen-opa-wasm.sh
- build/run-goimports.sh
- build/run-pigeon.sh
- build/utils.sh
There are a handful of scripts that were making `go run` calls without
the required environment vars setup force go to use modules and only
use the vendor directory.
For golang 1.11/12 if OPA was in a path outside of the GOPATH it would
switch into module mode automatically (by default) and then try to
fetch packages and stuff remotely rather than use the vendor dir.
For golang 1.13+ any directory for OPA would (by default) result in
trying to use the remote modules rather than vendor dir.
Fixes: #2063
> build: Force module mode and using only the vendor directory

- cover/cover.go
- cover/cover_test.go
They would previously show up as not-covered in any report. This
changes to simply omit them. They will never be int the resulting
covered or not-covered lists, or count against the % covered.
Fixes: #1972
> cover: Exclude `some` expressions in coverage report

- docs/content/_index.md
There is a link in `/docs/content/_index.md` which is a css id anchor for the same page.
Anchors are case-sensitive.
The link was capitalised, whereas the id used on the page is lowercase.
Changing the capitalisation to be lowercase fixed the link.
No tests added as this change is docs related.
> Fix broken link in index.md

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
Previously it would ignore the provided CA parameters unless client
cert info was provided. This change now allows for providing CA info
without any client auth details.
Fixes: #1976
> topdown: http.send use provided CA without client certs

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
- topdown/topdown_test.go
There is a new optional `timeout` option to specify with `http.send`
which will set a client timeout on the request. This will override the
default 5 second timeout.
This change also corrects the request to use the builtin context. This
means that if the evaluation is canceled the request will also now be
canceled.
There is an environment variable for adjusting the default timeout
which we should aim to remove in future OPA versions (when
appropriate). For now though it is still supported, and will panic if
supplied with an invalid value rather than previously ignoring it and
effectively disable the timeout (0 == unlimited).
Fixes: #2099
> Add timeout for `http.send` builtin

- topdown/http.go
- topdown/http_test.go
Previously it just used a string key with the method and url. This
causes problems if headers or body contents affect the response, and
users were seeing cached responses returned for different requests.
The new version takes into account the entire parameters object that
is provided to the builtin function.
Fixes: #1980
> topdown: Make http.send() caching use full request

- topdown/builtins.go
- topdown/cidr_test.go
- topdown/object_test.go
The older RegisterFunctionalBuiltinX functions would do this and it
gave the builtin error messaging/typing a nice uniform look and feel.
This changes the newer RegisterBuiltinFunc to do the same thing, so
any builtin will now either return a nil error or a `*topdown.Error`.
With an appropriate code, location, and message.
Fixes: #2101
> topdown: Wrap all builtin functions for errors normalization

- CHANGELOG.md
- ast/compilehelper.go
- ast/parser_ext.go
- ast/parser_test.go
- bundle/bundle.go
- loader/loader.go
- loader/loader_test.go
- rego/rego_test.go
The documentation is pretty clear that a module must at least contain
a package, so it is safe to say that an empty file isn't valid.
Previously the helper would just return a nil module and nil error, it
will now return an error.
Fixes: #2054
> ast: Return an error when parsing an empty module

- docs/content/configuration.md
In [0], some header is incorrectly placed 7 levels deep, causing the #
to show in the markdown documentation. This patch set corrects the
level so the documentation renders correctly.
Closes-Issue: #2072
[0] https://www.openpolicyagent.org/docs/latest/configuration/
Signed-off-by: Tin Lam <tin@irrational.io>
> docs: Fix incorrect header level

- cmd/check.go
Was doing some parsing of the `test` and `check` commands from the console and noticed that `test` was outputting to `stderr`, but `check` was not.
> cmd/check: use stderr if command returns an error

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/json.go
- topdown/json_test.go
This adds in a new built-in function `json.remove` which will take in
an object and list of json pointer paths (similar to `json.filter`)
and create a new object with all of the paths removed from the base
object.
Reference: #1617
> Add `json.remove` builtin

- docs/content/policy-performance.md
> docs: Fix typo in equality statement

- docs/content/configuration.md
> Correct invalid key for decision logs in examples

- cmd/parse.go
In f1b9c758 (Ensure all errors are in JSON formatted CLI output,
2019-09-11), the existing error check was moved into the JSON output
case, but the default case wasn't updated to handle errors.
> cmd/parse: fix panic when parsing invalid JSON

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/bits.go
- topdown/bits_test.go
- topdown/builtins/builtins.go
I'm interested in this project and thought it'd be fun to tackle a "low-hanging-fruit" issue.
Fixes #1919
Sign off in commit.
> Add bitwise operators after `bits.`.

- go.mod
- go.sum
- vendor/github.com/OneOfOne/xxhash/.travis.yml
- vendor/github.com/OneOfOne/xxhash/go.mod
- vendor/github.com/OneOfOne/xxhash/xxhash.go
- vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
- vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
- vendor/modules.txt
In Go 1.14 a 'checkptr' test was added to the -race build option to check for correct usage of unsafe.Pointer. Version 1.3.2 of OneOfOne/xxhash fails these checks causing OPA to fail these checks.
Version 1.3.6 of xxhash fixes these issues.
Tested with our previously failing code with OPA _replaced_ with these changes and runs as expected in Go 1.14.
Signed-off-by: Dan Dooley <dan@dooley.ac.nz>
> Bump xxhash to workaround checkptr errors with Go 1.14

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
If the headers map given to `http.send` includes the `Host` header, hoist
it up to the request. This lets users specify the server to connect to
and the `Host` header to send independently, much like curl.
> topdown: Add Host header support to http.send()

- CHANGELOG.md
- Makefile
- cmd/parse.go
- go.mod
- go.sum
- vendor/github.com/OneOfOne/xxhash/.travis.yml
- vendor/github.com/OneOfOne/xxhash/go.mod
- vendor/github.com/OneOfOne/xxhash/xxhash.go
- vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
- vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
- vendor/modules.txt
Release includes a fix for go 1.14 and a fix for an `opa parse` panic with the pretty output format.
> Prepare v0.17.3 release

- topdown/eval.go
- topdown/topdown_partial_test.go
- topdown/topdown_test.go
In `evalNot` when it succeeds we were calling `e.next(..)` to continue
evaluation, but if the previous expression was from `evalWith` the
original state was not being restored. This caused the patched data
to persist for subsequent expression evaluation(s) until `iter()` was
used.
Similar treatment was required in `evalNotPartial` for the partial
evaluation case.
Fixes: #2142
> topdown: Invoke iterator when evaluating negation

- ast/check_test.go
- ast/env.go
Previously if there was a non-json key it would `panic("unreachable")`
but it can fall back to using the dynamic property for these types.
Fixes: #2183
> ast: Fix type check for objects with non-json keys

- docs/content/kubernetes-primer.md
This PR adds a backtick to the live code block to fix
formatting issues in the documentation. This addresses the
examples in the `/docs/kubernetes-primer.md` document. The current
document/site does not render the live code block.
Signed-off-by: Rachel Leekin <rleekin@vmware.com>
Fixes #2177
> docs: Fix code fence in kubernetes-primer.md

- docs/website/layouts/index.redirects
Coming in the next few weeks the old redirects defined in `_redirects`
will not behave the same. To keep them working the same as before we
need to tell Netlify to force them (rather than looking for shadowed
pages). By specifying the return code and adding a `!` we achieve the
original behavior.
> docs: Force netlify redirects

- cmd/parse.go
- cmd/parse_test.go
There was an issue a little while back where we had a panic in the
command but there is zero test coverage exercising it... so we never
noticed.
This at least will get us some bare-bones test coverage to ensure
it isn't crashing on some basic use-cases.
> cmd: Add very basic parse cmd coverage

- docs/website/layouts/index.html
This patch set removes the first, possibly duplicate, set of the "Learn More"
link as outlined in issue #2208.
Closes: #2208
Signed-off-by: Tin Lam <tin@irrational.io>
> docs(homepage): remove link

- topdown/http.go
- topdown/http_test.go
If the `http.send` builtin is called with both `tls_insecure_skip_verify`
and another TLS configuration, the verificate setting will get lost as
the TLS configuration is overwritten. Ensure that we update the same
TLS configuration in all cases so that it is consistent.
> topdown: Fix lost `tls_insecure_skip_verify` setting

- .gitignore
- docs/Makefile
- docs/README.md
This updates the Makefile targets to remove the hugo-only options for
development, as well as clarifying/simplifying the requirements for
a dev environment. There are now really two options: just look at the
markdown preview with your editor/ide, or install the tools locally
and deploy the full site.
We can likely improve the dev experience some more (would be nice to
get back to the live content updating dev experience) but for now this
should help remove some confusion about how to build and run the site.
> docs: Update dev instructions and make targets

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
If the caller sets the Host header, then we can reasonably impute that
they wanted to use that at the TLS layer as well. To handle test cases
where the caller needs to explicitly set the TLS server name, add a
`tls_server_name` parameter that overrides both the `Host` header and
the Go default.
> topdown: Add http.send support for setting the TLS server name

- docs/content/editor-and-ide-support.md
Add Emacs major mode in the editor integration documentation
Signed-off-by: Sibi Prabakaran sibi@psibi.in
> Add Emacs mode for rego language

- ast/parser.go
- ast/parser_test.go
- format/testfiles/test.rego
- format/testfiles/test.rego.formatted
We were not setting locations on `with` expressions. This adds in
support for doing so.
> ast: Fix for `with` node locations

- ast/check.go
- ast/check_test.go
Earlier if a rule/function contained an error, the type checker would not update the env with subsequent independent rules resulting in errors such as "undefined functions". This change add erroneous rules/functions to the env to avoid such type errors.
Fixes #2155
Fixes #2091
> ast: Add rules/functions that contain errors to the type env

- docs/content/extensions.md
- rego/example_test.go
- rego/rego.go
This commit extends the rego package to export helpers that register
custom built-in functions globally for the entire OPA runtime and
updates the extension page to contain an example.
> rego: Improve support for registering custom built-ins

- ast/builtins.go
- docs/content/policy-reference.md
- topdown/time.go
- topdown/topdown_test.go
New builtin for adding years, months and days to a time
This might be useful for computing a day in the future or past
more easily
Fixes #1990
Signed-off-by: Frederic <frederic.vanreet@icloud.com>
> Add time.add_date builtin

- topdown/http_test.go
The Go HTTP library may quote the URL in a HTTP error message, possibly
depending on platform or Go version. Since the URL doesn't matter for
verifying the error, we can just remove it from the match target.
> topdown: make the TLS server name test more robust

- ast/check_test.go
- ast/compile.go
- ast/compile_test.go
- ast/env.go
We now will rewrite any calls found in rule heads (specifically in
arguments).
The PR also includes a couple of small fixes for things I noticed while looking around in these files fixing the issue.
Fixes: #2081
> ast: Rewrite rule arguments

- cmd/fmt.go
There was an explicit check that would prevent writing to stdout if
the formatting didn't change anything.
This makes sense for the "write to file" or "diff" options as we can
save work by bailing out early, but if configured to write the file
contents to stdout we should do so in all cases.
Fixes: #2235
> cmd/fmt: Always write to stdout

- internal/lcss/README.md
- internal/lcss/lcss.go
- internal/lcss/lcss_test.go
- internal/lcss/qsufsort.go
- repl/repl_test.go
- topdown/eval.go
- topdown/trace.go
- topdown/trace_test.go
Previously we had a hard set width for location info in pretty trace
outputs. This changes to use a dynamic width up to a reasonable max
and then starts to shorten paths as possible by swapping in `...` for
the longest common substring of all paths.
To get the longest substring this brings in a couple files from
https://github.com/vmarkovtsev/go-lcss which implements an efficient
algorithm for it (rather than us implementing something fancy from
scratch). It's pretty isolated and is unlikely to need any updates
over time so the maintenance should be low.
Fixes: #2143
This also includes a fix for locations on "save" trace events.
> topdown: Improve pretty trace location details

- ast/compile.go
- ast/compile_test.go
Earlier if a reference to the root of the input document was passed as operand in a call, it would not be rewritten to a local variable and substituted in the call. Refs to non-root input/data document would be rewritten. This was happening because we were updating the value of the input root ref term to a variable and as a result the compiler stage that rewrites the body of dynamic terms ('rewriteDynamicTerms') would not rewrite the input root ref. These changes modify the 'rewriteLocalVars' stage so that the value of root ref term is updated only if it has already been rewritten to a local variable. If it isn't, then it will be rewritten in a later stage.
Fixes #2084
> ast: Rewrite input document when passed as an operand to a call

- docs/website/data/integrations.yaml
Integration pam_authz has been renamed pam_opa
Cf. https://github.com/open-policy-agent/contrib/commit/80435207
> Fix contrib link: pam_authz has been renamed pam_opa

- docs/content/policy-reference.md
- topdown/http.go
- topdown/http_test.go
Previously we left them off the returned AST object, this will now
just massage them into valid types and pass them along into the
return value.
Fixes: #2238
> topdown: Return response headers with `http.send`

- rego/rego.go
- rego/rego_test.go
- server/server.go
- server/server_test.go
This is a combination of two changes to fix #2247 
First up we change the way that `rego.Rego` objects generate the partial result modules on the compiler. We will name them with more dynamic module id's so that >1 query can be partially evaluated sharing the same compiler.
Next we adjust the OPA server to specify a namespace when doing partial evaluation so that cached results have unique query paths.
> Use unique query paths and module id's for partial eval in the server

- cmd/test.go
- cmd/test_test.go
- topdown/lineage/lineage.go
- util/enumflag.go
- util/enumflag_test.go
This is adding support for two features (related enough to group together in a single PR).
First up is making the `opa test` `--explain` flag automatically turn on verbose output. This should help for anyone who is trying to see a trace (by providing the flag) and then being surprised when no trace output is shown.
The second one is to make it so that the default trace output shown when _only_ specifying `-v`/`--verbose` includes both "fail" and "note" events. This should help users more easily troubleshoot why tests failed without having to use `--explain full` and sifting through all of the output.
Closes: #2068
Closes: #2069
> Improve opa test --verbose and --explain flag usage

- plugins/rest/aws_test.go
It seems as though go 1.14 changes some of the url errors to have
quotes around some fields. To make things compatible across a wider
number of platforms we can relax the checks a tiny bit to only look
at the actual error string and ignore the quoted part.
> Fix url error checking for go 1.14

- format/format.go
- format/format_test.go
The formatter would normally just use the stringer for ast.Var which
would swap in `_` for any wildcard variables (internally represented
with a `$xx` syntax). This works fine except for AST dumped into the
formatter that might have the same wildcard variable used multiple
times. This can be seen by using partial evaluation creating multiple
statements from a single original source. In the formatted output if
we swap in `_` it can affect the resulting logic if they were supposed
to be the same variable.
The formatter now will check for any wild cards that show up >1 time
in the AST passed in to be formatted. Any it finds will be assigned
a new variable name like `__wilcardxx__` and in the resulting output
will use that name instead of the `_` syntax.
Fixes: #2053
Signed-off-by: Patrick …
> format: Print var if wildcard is used multiple times

- rego/rego.go
- rego/rego_test.go
- server/server_test.go
Any time we do a compilation in the Rego object (or helpers) we need
to be careful to setup a conflict check that is valid for the current
context (both literal golang ctx and current storage transaction).
This isn't much of a concern if the Rego instance owns the compiler,
but if an external one was provided we need to be careful to update
the conflict check before compiling.
This was already doing the "right thing" when activating bundles, but
for partial evaluation results that were being updated on the compiler
it was not.
Fixes: #2197
> rego: Avoid re-using transactions in compiler

- topdown/eval.go
- topdown/topdown_partial_test.go
Earlier while partially evaluating comprehensions, we would namespace the variables in the comprehension and then save it. This would result in the mutation of the comprehension expression in the orginal query and as a result the same expression containing missing terms when re-encountered would not be PE-ed and hence produce incorrect results. This change does a deep copy of the comprehension before namespacing so that the original query is not modified.
Fixes #2243
> topdown: Save comprehensions containing unknown terms

- profiler/profiler.go
- profiler/profiler_test.go
Previously the profiler would panic if it encountered an expression with no location info. This change groups such expressions by giving them a fake location so that their evaluation results can be captured.
Fixes #2134
> profiler: Group expressions with missing locations

- bundle/file.go
- bundle/file_test.go
Previously if we provided a "root" to the bundle directory loader that
was a relative path, it would matter whether or not it was prefixed
with "./". The logic to trim that path from the paths found walking
the root was not taking into account the prefix so the resulting ones
that had "./" would leave behind the root path.
Later on the bundle loader would generate a "full" path to set on the
module file for its location which is the root+path.. which resulted
in duplicate "root"s on those id's.
To fix this we just normalize the relative paths in the directory
loader so that we can not worry about what type of relative path it
is.
Fixes: #2117
> bundle: Remove extra root name in bundle file id's

- docs/content/policy-reference.md
A user pointed out that our EBNF grammar did not quote a few of the
terms correctly. This commit fixes those cases.
> docs: Fix EBNF grammar to quote terms correctly

- docs/content/policy-reference.md
- topdown/crypto.go
- topdown/http.go
- topdown/http_test.go
`http.send` already supports TLS keys and certificates obtained from
external files and environment variables. Add support for specifying
certificates and keys as direct parameters to `http.send`. This is
useful when you already have policy variables with this data.
There are 3 options that this affects: client certificates, client
keys and CA bundles. All of these can now be specified from either a
file, an environment variable or from raw data. In the case of client
certificates and keys, each access method must use a matched pair (e.g.
both the certificate and the key must come from environment variables).
CA certificate bundles are the union of all the specified access methods.
> topdown: support inline TLS certificates and keys

- docs/content/management.md
- download/download.go
- download/download_test.go
- plugins/bundle/plugin.go
- plugins/bundle/plugin_test.go
- plugins/discovery/discovery.go
This change updates how the Etag on the downloader object is set. See the commit message for more details.
Fixes #2220
Fixes #2279
> Update downloader's Etag based on bundle activation

- docs/content/configuration.md
- plugins/rest/rest_auth.go
- plugins/rest/rest_test.go
This change updates the bearer token config to allow clients to specify
a path to the token. With this refreshing tokens becomes easier as OPA
will now reload the token from file.
Fixes #2241
> plugins: Add support to specify bearer token path

- cmd/fmt.go
- cmd/fmt_test.go
Fixes an issue introduced in https://github.com/open-policy-agent/opa/pull/2249
where we would now always list the filename, regardless of whether or
not the file had changes.
This corrects the behavior to only do it when there are changes in the
formatted output and the original content.
Fixes: #2295
> cmd/fmt: Only list files if there were changes

- CHANGELOG.md
- metrics/metrics.go
This change is not backwards compatible but it is only a minor
inconvience for anyone who has re-implemented metrics.Metrics (which
feels highly unlikely anyway.)
> metrics: Include Add(uint64) on Counter object

- docs/content/management.md
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/rest/rest.go
Earlier with discovery enabled updates to the 'services' configuration
was not allowed to protect against accidental changes to the discovery service
itself. Since adding new services could be useful, this change allows modifications
to the 'services' configuration. The only exception is that the service used to download
the discovery bundle cannot be modified.
Fixes #2058
> plugins: Additive updates to services when discovery enabled

- topdown/array.go
- topdown/array_test.go
The built-in function implemented clamping in an odd way. With this
change, the stopIndex will always be [0, len(arr)] and the startIndex
will always be [0, clamped_stopIndex].
Fixes #2320
> topdown: Fix panic in array.slice due to incorrect clamping

- build/build-release.sh
We will be doing the packaging steps in a separate workflow from the
current one that uses build-release.sh. For now this means just
removing the calls to make the deb file from the script.
> build: Remove packaging step from build-release.sh

- Makefile
- topdown/http_slow_test.go
- topdown/http_test.go
The test case timeout parameters have been lowered by a few orders of
magnitude (but still large relative gaps) becaue otherwise the time
the topdown package jumps to >20s. If we see flakyness in CI we could
look at tagging these as "slow" and then only running them if requested.
> topdown: Fix data race in http.send test case

- ast/compile.go
- ast/compile_test.go
- topdown/copypropagation/copypropagation.go
- topdown/copypropagation/unionfind.go
- topdown/copypropagation/unionfind_test.go
- topdown/eval.go
- topdown/http_test.go
- topdown/query.go
- topdown/topdown_partial_test.go
First set of changes are just refactoring which change a couple of things to make the copypropagation code a little more simple/readable/re-usable.
- Split out the unionfind data structure (and add tests for it)
- Add support for any type of ast.Value in the unionfind and copy propagation "bindings"
- Rename "bindings" to something that makes the code easier to understand.
The last commit addresses issue #2045. See the commit message for more details but the high level change is that we check if any removed equality was required for safety of some var in the result. If it is we add it back in the result.
> topdown/copypropagation: Refactor and fix for safety of resulting queries

- topdown/uuid_test.go
The recent copy propagation fix requires the compiler during partial
evaluation. In the new uuid built-in function test case, the compiler
was not being provided so it caused a panic.
> topdown: Fix panic in partial eval test of uuid built-in

- CHANGELOG.md
- Makefile
- plugins/plugins.go
- runtime/runtime.go
Cherry picking the bug fix for https://github.com/open-policy-agent/opa/issues/2343 onto the 0.19 release branch and preparing for a 0.19.2 release
> Prepare v0.19.2 release

- docs/content/management.md
- internal/config/config.go
- plugins/discovery/discovery.go
- plugins/discovery/discovery_test.go
- plugins/plugins.go
- plugins/rest/rest.go
Earlier with discovery enabled, there was no protection against accidental
changes to the discovery service. This change prevents the discovery service
from being modified by checking it's config in the service bundle.
Fixes #2058
> Additive updates to services when discovery enabled

- ast/parser.go
- ast/parser_test.go
In other places where the body can be implied, the parser includes a
body containing a single "true" expression. Do the same for else.
Fixes #2353
> ast: Fix parser to include body on else if needed

- ast/parser.go
- ast/parser_test.go
- format/format.go
- format/testfiles/test.rego.formatted
- format/testfiles/test_issue_2299.rego
- format/testfiles/test_issue_2299.rego.formatted
We used to always force empty lines between else blocks and their
parent rule. Recently we changed to force them into a compact/inline
style as long as there were no comments between blocks.. now we will
preserve the original style, favoring the compact style.
This should make the change that happened more backwards compatible
and allow policy authors to use either style without the formatter
forcing one over the other.
Previously we didn't have the correct rule location text (for the full
rule, head, value, else's, etc). This changes to set the text and adds
some tests to validate.
This affects the formatter somewhat with how it decides where to place
comments. The current output now more accurately reflects their
placement in the original policies.
There is one little hack to set the …
> format: Preserve "else" style 

- docs/content/external-data.md
> docs: Correct the link to opa bulitins in external data page
