open-policy-agent/opa

test/cases/testdata/aggregates/test-aggregates-0027.yaml
test/cases/testdata/strings/test-strings-0889.yaml
test/cases/testdata/strings/test-strings-0890.yaml
test/cases/testdata/strings/test-strings-0891.yaml
test/cases/testdata/strings/test-strings-0892.yaml
test/cases/testdata/strings/test-strings-0893.yaml
test/cases/testdata/strings/test-strings-0894.yaml
topdown/aggregates.go
topdown/strings.go

This is done by working with the runes directly, both when counting length of strings as well as when slicing them to substrings.
Fixes #2799

Fix substring and count unicode handling

---

cmd/run.go
runtime/runtime.go
server/server.go
test/e2e/h2c/h2c_test.go

Finally. For context see #1590.

runtime: Remove --insecure-addr flag

---

plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

Earlier when loading bundles from disk, we weren't providing
the bundle verification config that would be needed to read
a signed bundle that may have been persisted to disk in the past.
This changes adds support for loading signed bundles from disk by
providing the bundle verification config (if any) to the bundle
reader.
Fixes: #2824

plugins/bundle: Support for loading signed bundles from disk

---

cmd/run.go
runtime/runtime.go
test/e2e/shutdown/shutdown_test.go

Fixes #2764
Signed-off-by: Björn Carlsson <bjorn.carlsson@bisnode.com>

Add flag to allow setting a shutdown wait period

---

wasm/src/strings.c
wasm/tests/test.c

wasm: Fix split built-in function to deal with empty strings

---

wasm/src/glob-compiler.cc
wasm/src/glob-lexer.cc
wasm/src/glob-parser.cc
wasm/src/malloc.c
wasm/src/malloc.h
wasm/tests/test-glob.cc

wasm: glob builtin memory leak fixes

---

topdown/http.go
topdown/http_test.go

Fixes #2841
CC @ashutosh-narkar 

Override Cache-Control: no-store on force_cache

---

CHANGELOG.md
capabilities/v0.25.0-rc1.json
version/version.go

Prepare v0.25.0-rc1 release

---

CHANGELOG.md
capabilities/v0.25.0-rc2.json
version/version.go

Prepare v0.25.0-rc2 release

---

Makefile

This target was not updated with the wasmer test changes, and is not
passing without wasmer being enabled. We needed to plumb the newer
test tags through to it.

build: Fix `make test` target

---

CHANGELOG.md
capabilities/v0.25.0-rc3.json
version/version.go

Prepare v0.25.0-rc3 release

---

compile/compile.go
compile/compile_test.go

compile: Error out if the input module URLs not unique.

---

CHANGELOG.md
capabilities/v0.25.0-rc4.json
version/version.go

Prepare v0.25.0-rc4 release

---

topdown/parse_bytes.go
topdown/parse_bytes_test.go

topdown: Fix units.parse_bytes panic when zero-length string given

---

MAINTAINERS.md

MAINTAINERS.md: Add Oren Shomron

---

docs/content/kubernetes-tutorial.md

Added some error info for OPA policy fail

---

docs/content/http-api-authorization.md

Fixes #2917 : adding url in string

---

docs/website/data/integrations.yaml

docs: Add link to Bisnode's Spring Security library

---

internal/wasm/sdk/internal/wasm/vm.go

internal/wasm/sdk/internal: A missing wasm memory free.

---

Makefile
build/check-vet.sh
build/run-goimports.sh
resolver/wasm/nop.go
resolver/wasm/wasm.go

Makefile: Future proof the wasm runtime flag

---

CHANGELOG.md
capabilities/v0.25.0.json
version/version.go

Prepare v0.25.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.26.0 development

---

CHANGELOG.md
capabilities/v0.25.1.json
version/version.go

Prepare v0.25.1 release

---

docs/website/data/integrations.yaml

Not sure what (if anything) to add under "inventors". Do you have a suggestion, @scholzj ?
Signed-off-by: Anders Eknert <anders@styra.com>

Add Strimzi to Kafka integrations

---

CHANGELOG.md
capabilities/v0.25.2.json
version/version.go

Prepare v0.25.2 release

---

.github/workflows/codeql-analysis.yml

Since this more than doubled build times, run only on pushes to master/release branches and not on each PR.

Reduce CodeQL frequency

---

docs/content/oauth-oidc.md

Closes #2096 and arguably also #2057
Signed-off-by: Anders Eknert <anders@styra.com>

Add Oauth2/OpenID Connect docs under "misc"

---

ADOPTERS.md

Signed-off-by: amitkanfer <amit@build.security>

Adding build.security to the adopters page

---

CHANGELOG.md
docs/content/configuration.md
plugins/bundle/config.go

bundle: Add deprecation warning for old 'bundle' configuration

---

docs/content/policy-reference.md
internal/compiler/wasm/wasm.go
test/wasm/assets/018_builtins.yaml
wasm/src/graphs.c
wasm/src/graphs.h
wasm/tests/test.c

wasm: Add native support for graph.reachable builtin function

---

docs/content/policy-reference.md

docs: Add 'some' to reserved names

---

docs/content/editor-and-ide-support.md

Syntax highlighting for nano

---

docs/content/external-data.md

* raise_error setting allows policy evaluation to proceed on errors
* Remove experimental label as function is well tested by now

docs: Minor http.send updates

---

ast/builtins.go
capabilities.json
docs/content/policy-reference.md
internal/compiler/wasm/wasm.go
test/cases/testdata/arithmetic/test-arithmetic-0824.yaml
test/cases/testdata/arithmetic/test-arithmetic-0825.yaml
topdown/arithmetic.go
wasm/src/arithmetic.c
wasm/src/arithmetic.h
wasm/tests/test.c

Add ceil and floor built-ins

---

cmd/build.go
cmd/flags.go
cmd/sign.go
docs/content/management.md

docs/website: update link to signing section
cmd: Update help text to link to signing format section
Fixes: #3027

Update Signing Links

---

docs/content/editor-and-ide-support.md

Update links to IntelliJ IDEA plugin

---

cmd/eval.go
cmd/eval_test.go

The topdown package re-uses location information from AST nodes that
it saves and the format package attempts to squash blank lines between
adjacent expressions. As a result, the pretty/source formatted output
from the eval subcommand would often contain spurious blank lines that
make the output feel inconsistent.
This change modifies the cmd package to overwrite the location info on
all expressions so that the format package doesn't have to squash any
blank lines. The cmd package walks the expressions and sets the row
number in-order.
Before:
+----------+------------------+
| Query 1  | "R1" = input.foo |
|          |                  |
|          | "L1" = input.bar |
+----------+------------------+
After:
+----------+------------------+
| Query 1  | "R1" = input.foo |
|          | "L1" …

cmd: Fix eval subcommand to remove blank lines from partial output

---

docs/website/data/integrations.yaml

Adding a new JAVA integration that also includes annotations to make it easy to pass permissions requirements and other conditions to OPA
Signed-off-by: amitkanfer <amit@build.security>

Adding JAVA spring intergation

---

CHANGELOG.md
version/version.go

Prepare v0.27.0 development

---

tester/fixture_go1.14_test.go
tester/fixture_go1.16_test.go
tester/reporter_test.go

tester: differentiate expected output by golang version

---

internal/planner/planner.go
internal/planner/planner_test.go
internal/wasm/sdk/opa/opa_test.go
rego/rego.go

In our previous optimization change, #3058, we've been falling back to the old behaviour (with introduces cross-products) whenever our optimization didn't seem to apply.
This PR extends that a little: when there are only leaves (matching our optimization lookup) that do not have rules (i.e. empty packages), we decide that nothing package-related is to be done _at all_. So, we'll go on **looking at base data only**.
With this in place, the planner case added,
```
{
note:    "cross product with non-ground refs to packages, 'no rules leaves' case",
queries: []string{`x := "aaa"; y := data.foo[x].bar.baz`},
modules: []string{`package foo.aaa.bar`, `package foo.bbb.bar`},
},
```
goes from this IR,
```
*ir.Policy Policy
| *ir.Static Static (7 strings, 1 files)
| | *ir.StringConst &{Value:x}
| | …
```

wasm: have planner optimize case without rules in leaves (do nothing) 

---

codecov.yaml

This has been annoying to a few people now, let's drop it.
Docs: https://docs.codecov.io/docs/github-checks-beta

codecov.yaml: disable annotations

---

cmd/test.go
docs/content/policy-testing.md
tester/reporter.go
tester/reporter_test.go
tester/runner.go
tester/runner_test.go

Rules prefixed "todo_test_" will be now counted as tests but skipped and marked
as such in the test report.
Closes #3104

Allow skippable tests

---

bundle/keys_test.go
internal/jwx/jws/sign/sign.go
plugins/rest/rest_test.go

Allow PKCS8 encoded private keys

---

CHANGELOG.md
cmd/bench.go
cmd/eval.go
cmd/flags.go
cmd/test.go
internal/rego/opa/nop.go
internal/rego/opa/opa.go
rego/rego.go
rego/rego_test.go
repl/repl.go
repl/repl_test.go
runtime/runtime.go
tester/runner.go

Add target flag to OPA subcommands

---

docs/content/security.md
server/authorizer/authorizer.go
server/authorizer/authorizer_test.go

I've taken over with #3078; updating test docs and the test according to nitpicks. The bulk of the work is @ajanthan's!
📢 @ajanthan: I hope you don't mind me running with this!

custom reason in authz policy

---

cmd/eval.go

If we print the warning to stdout we will break programs that parse
the output.

cmd: Print explain warning to stderr not stdout

---

README.md
docs/website/layouts/index.html

And increase number of built-ins somewhat..

Graduation!

---

docs/website/layouts/docs/ecosystem.html.html

This commit updates the logic used to order
integrations on the ecosystem page. Multiple
links from the same domain in the blogs
and tutorials sections will be counted only once
while calculating the order of that integration on the page.

docs: Update the logic to order integrations

---

CONTRIBUTING.md

I was reviewing the CONTRIBUTING.md file that we have had in place
forever and realized that we never used the mailing list
seriously--discussion has moved to Slack or GitHub issues.

CONTRIBUTING.md: Just file issues

---

ADOPTERS.md

Add cluetec.de to the ADOPTERS.md file.

Add cluetec.de to ADOPTERS.md

---

test/e2e/concurrency/concurrency_test.go
topdown/topdown_bench_test.go

```
test/e2e/concurrency/concurrency_test.go:51:6: call to (*T).Fatal from a non-test goroutine
test/e2e/concurrency/concurrency_test.go:54:6: call to (*T).Fatalf from a non-test goroutine
topdown/topdown_bench_test.go:161:7: call to (*B).Fatalf from a non-test goroutine
topdown/topdown_bench_test.go:164:7: call to (*B).Fatalf from a non-test goroutine
```
See https://golang.org/doc/go1.16#vet

Fix "make check" failures with go version 16+

---

docs/website/data/integrations.yaml

Add Fairwinds Insights to integrations

---

plugins/logs/plugin.go
plugins/logs/plugin_test.go

Addresses #3197
Signed-off-by: Stan Lagun <stan@styra.com>

logs: do not block Stop if there are no logs to publish

---

docs/website/data/integrations.yaml

Signed-off-by: amitkanfer <amit@build.security>

Adding PHP Symfony middleware to ecosystem page

---

CHANGELOG.md

Update the CHANGELOG in preparation for next release

---

CHANGELOG.md
capabilities/v0.27.0.json
version/version.go

Prepare v0.27.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.28.0 development

---

docs/content/configuration.md

docs: Add missing discovery.service field to table

---

docs/content/_index.md
docs/website/data/integrations.yaml
docs/website/layouts/index.html

The envoy-authorization page was a 404, probably after
the recent refactoring of those docs.

Fix envoy links

---

CHANGELOG.md
capabilities/v0.27.1.json
version/version.go

😅 I had done the things the script would have done manually when I discovered the script. Hope this is OK, please copy-edit as you see fit!

prep 0.27.1 release

---

test/e2e/authz/authz_bench_integration_test.go

Correct ineffassign

---

rego/rego.go
rego/rego_wasmtarget_test.go

wasm target: add missing error check

---

topdown/http.go
topdown/http_test.go

Previously when inserting an item in the inter-query cache, only
the size of the raw string representing the HTTP response message body
was used to calculate the amount of memory used by the item. This was
errornous as the actual item inserted in the cache would hold not only the
raw string but also the JSON representation of the message body.
The deserialized JSON body would end up consuming as much as 20x more memory compared
to the JSON encoded version of the same data. As a result, the cache would end
up consuming more memory than the user-defined cache size limit.
This change serializes the data that will be inserted in the inter-query cache
so as to get a more accurate representation of the size of the cache.
Fixes: #3042

topdown: Insert serialized data in inter-query cache

---

topdown/http.go
topdown/http_test.go

Earlier if the value for the Expires header was set
to an invalid date like 0, we would return an error and
fallback to the normal cache (ie.we would not use
the inter-query cache).
Servers can sometimes set `Expires: 0` to indicate
expired content. This change ignores the errors
resulting from parsing the Expires header.
Fixes: #3284

topdown: Ignore errors during parsing Expires header

---

bundle/keys_test.go
internal/jwx/jws/sign/sign.go

Fixes #3283
Signed-off-by: Andre Håland <andre.haland@gmail.com>

Allow PKCS8 encoded EC private keys

---

build/commit-wasm-bins.sh

This was a surprise, I thought I had changed that. Anyways, following the merge of this PR, the files in master should be up-to-date again.

wasm-updater: also commit callgraph.csv

---

go.mod
go.sum
vendor/github.com/bytecodealliance/wasmtime-go/.gitignore
vendor/github.com/bytecodealliance/wasmtime-go/BUILD.bazel
vendor/github.com/bytecodealliance/wasmtime-go/README.md
vendor/github.com/bytecodealliance/wasmtime-go/WORKSPACE
vendor/github.com/bytecodealliance/wasmtime-go/linker.go
vendor/github.com/bytecodealliance/wasmtime-go/shims.c
vendor/github.com/bytecodealliance/wasmtime-go/shims.h
vendor/modules.txt

https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0250
✔️ ran `make wasm-sdk-e2e-test` on macos, we're OK.

deps: bump wasmtime-go (v0.24.0 -> v0.25.0)

---

docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/scripts/install-deps

Also print info when deps are not installed.

docs: Commit package-lock.json

---

CHANGELOG.md

Updating the CHANGELOG with mid-release notes

---

MAINTAINERS.md

Update maintainer status

---

ast/check.go
ast/check_test.go
ast/compile.go
ast/compile_test.go
ast/env.go
ast/policy.go
ast/schema.go
ast/schema_test.go
cmd/check.go
cmd/eval.go
cmd/eval_test.go
loader/loader.go
loader/loader_test.go
rego/rego_test.go

This PR just contains a few follow on changes from #3123. See the commit messages for details. If you're reviewing the changes, I would recommend looking at each commit separately as they are fairly independent.
cc @vazirim @aavarghese

Misc. refactoring and improvements on type checker

---

plugins/logs/plugin_test.go

#1593 indicates that the upload size is not reconfigurable which does not
seem to the case as the encoder is re-created as seen [here](https://github.com/open-policy-agent/opa/blob/master/plugins/logs/plugin.go#L609).
This change adds a test to check the upload limit is updated when the plugin is reconfigured.

plugins/logs: Add test to check upload size limit on reconfig

---

plugins/discovery/discovery_test.go

The log drop check test does not setup a remote
decision logging endpoint to upload logs. Hence when the
decision log plugin tries to upload a log, it fails. Now when
the plugin tries to requeue the log it causes the log
drop count to increase as the rate limit has already exceeded.
This change updates the test to take into account the drop count
increase caused due to such a scenario.
Flaky test run -> https://github.com/open-policy-agent/opa/runs/2321840187?check_suite_focus=true

plugins/discovery: Fix log drop flaky test

---

compile/compile.go

Issue #2260 shows me that we did that last summer. Let's keep doing it.

build: dump policy IR if passing --debug

---

.gitignore

Otherwise running opa build in the directory dirties the working copy.

Add bundle.tar.gz to gitignore

---

docs/website/data/integrations.yaml

Points to the JTW-OPA Integration in [massenz/jwt-opa](https://github.com/massenz/jwt-opa).
Signed-off-by: M. Massenzio (marco@alertavert.com)

Added Integration entry for Spring Security Reactive

---

docs/website/layouts/docs/ecosystem.html.html

Hopefully this makes it easier for people to discover and update the
ecosystem page.

docs: Update ecosystem page link to github

---

docs/website/data/integrations.yaml

Add instructions for contributing

---

docs/website/layouts/index.redirects

Since this file does not update with releases but with deployments,
we'll need to revert this until the release tomorrow.

Temporary fix of redirects

---

CHANGELOG.md

Update CHANGELOG with latest release notes

---

CHANGELOG.md
capabilities/v0.28.0.json
version/version.go

Prepare v0.28.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.29.0 development

---

docs/website/layouts/index.redirects

This reverts commit 0a374befeef530c6e1931c3ac3b0b1f3cf3c0bc0.

Fix redirects post release

---

docs/content/wasm.md

👉 https://www.openpolicyagent.org/docs/latest/wasm/#advanced-compiling-options current paragraph

website/wasm: fix markup around link without target

---

ADOPTERS.md

Add jetstack to adopters

---

ADOPTERS.md

Signed-off-by: rtfee <ryan.fee625@gmail.com>

Added Scalr to adopters

---

ADOPTERS.md

Signed-off-by: rtfee <ryan.fee625@gmail.com>

Fixed a typo in the Scalr adopters section

---

SLACK.md

Add guidelines for Slack community

---

sdk/opa_test.go
sdk/test/test.go

This commit updates the test server so that callers can control when
the server becomes ready. This allows us to test the async option on
the SDK without worrying about race conditions. I.e., we can block
server readiness and assert that the SDK returns undefined until ready.

sdk: Add readiness signal to the test server

---

bundle/bundle.go
bundle/bundle_test.go
bundle/store.go
docs/content/management-bundles.md
plugins/bundle/plugin_test.go

This tries to implement #3431.

Add a manifest key for bundle metadata

---

docs/website/scripts/live-blocks/package-lock.json

Bump lodash dependency

---

download/download.go
download/download_test.go
plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

This commit fixes couple of issues that could result
in blocking OPA:
1) When the bundle plugin attempts to stop the bundle
downloader, it first grabs the lock on the plugin and then
stops the downloader. The downloader in-turn calls the plugin’s
callback function which now waits for the lock to be released
by the plugin's stop function. This results in a deadlock.
This commit fixes this issue by making sure the plugin's stop
function releases the lock before stopping the downloader.
2) Another issue that could block OPA is when the stop function
on the same downloader gets called multiple times.
Fixes: #3363

Fix OPA deadlock while stopping bundle plugin

---

topdown/eval.go
topdown/eval_test.go

Now, function results (not built-ins, but functions defined in rego)
will be cached: the function and its arguments are put into the cache,
such that any subsequent evaluation with the same arguments is taken
from the cache.
None of this happens in partial eval.
------
Fixes #3417 (for the rego target at least)

topdown: memoize function outputs

---

plugins/logs/plugin.go

Adjust logging level and message

---

download/download.go
download/download_test.go
plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

Earlier with bundle persistence enabled, the bundle
plugin would save the bundle object to disk. In
scenarios where the downloaded bundle has multiple
data files, OPA would first read the bundle and merge
data in the bundle under the bundle.Bundle struct's
Data field. Then before persisting the bundle to disk,
the bundle plugin would use the bundle writer to write
the bundle to the provided output stream. The result
of this is that all the data files in the original
bundle are consolidated into one data.json file.
Now if signature verification is enabled, it will fail
since the files includes in the bundle's signature will not
match the ones in the persisted bundle.
This commit resolves this issue by persiting the bytes
of downloaded bundle to disk which then loaded
from disk maintain the …

Persist bundle bytes to disk

---

CHANGELOG.md
capabilities/v0.29.0.json
version/version.go

Prepare v0.29.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.30.0 development

---

.github/workflows/post-tag.yaml
CHANGELOG.md
capabilities/v0.29.1.json
version/version.go

Prepare v0.29.1 release

---

CHANGELOG.md
version/version.go

Prepare 0.30.0 development

---

.github/workflows/post-merge.yaml

build: fix post-merge action

---

CHANGELOG.md
capabilities/v0.29.4.json
version/version.go

🤞 Last patch release of the 0.29 series 😅

Prepare v0.29.4 release

---

Makefile

Update make image target to build static binary

---

cmd/bench.go

cmd: Do not print nil errors in bench subcommand

---

server/server.go

Fixes: #3533
Signed-off-by: Aman Ali <76710693+amanymous-net@users.noreply.github.com>

 Support Abstract Unix Domain Sockets

---

docs/content/_index.md

Change default linux download

---

docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/package.json

Bump all dependencies to latest.
Netlify preview for review: https://anders-opa.netlify.app/docs/edge/

Bump live blocks dependencies

---

rego/rego.go
rego/rego_test.go

rego: Expose random seeding in rego package

---

docs/content/kubernetes-introduction.md

Signed-off-by: Dave Baker <dbaker@redhat.com>
Fixed typo in docs, to match actual URL being referenced.

typo in docs

---

docs/content/extensions.md

Just a small typo on "Extending OPA" doc page.

Small typo on "Extending OPA" doc

---

docs/content/policy-reference.md

https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

syntax highlighting EBNF grammar

---

docs/content/envoy-performance.md

Previously we provided actual performance benchmarks
for the OPA-Envoy plugin by running it in an experimental
setup. Although it maybe useful to document real numbers,
the results depend a lot on the environment in which OPA-Envoy
is run, OPA features being used and also on the methodology
used to generate them (eg. how a particular load test tool
measures latency).
Hence this commit provides guidance and best practices for
benchmarking the OPA-Envoy plugin which users can adopt in
their own environments.

docs: Add guidance for OPA-Envoy benchmarks

---

CHANGELOG.md
version/version.go

Prepare 0.31.0 development

---

test/cases/testdata/strings/test-strings-0887.yaml
test/cases/testdata/strings/test-strings-indexof-unicode.yaml
topdown/strings.go

Use whole string for comparison, not just first char.

Fix indexof regression

---

CHANGELOG.md
capabilities/v0.30.1.json
version/version.go

Patch release to fix #3606 via #3610.

Prepare 0.30.1 release

---

internal/wasm/sdk/internal/wasm/bindings.go

If the random seed is not supplied, initialize it. This finishes off #3622.

internal/wasm: Lazily initialize the random seed

---

Makefile

build: Add static image variant

---

plugins/rest/aws.go
plugins/rest/aws_test.go

This will prevent the token from being leaked in the query string when the request fails.

Use POST for retrieving STS credentials from AWS

---

ast/builtins.go
capabilities.json
topdown/numbers.go

feat rand.intn: generate random number 0-n

---

docs/content/configuration.md

docs: clarify special characters for key

---

CHANGELOG.md
capabilities/v0.30.2.json
plugins/rest/aws.go
plugins/rest/aws_test.go
version/version.go

Release 0.30.2

---

CHANGELOG.md
capabilities/v0.30.2.json

Copying v0.30.2 release notes and capabilities into main

---

CHANGELOG.md
capabilities/v0.31.0.json
version/version.go

🎉 Please review the release notes 📜

Prepare v0.31.0 release

---

docs/content/policy-language.md

docs/policy-language: fix typo

---

docs/content/kubernetes-debugging.md
docs/content/kubernetes-introduction.md
docs/content/kubernetes-primer.md
docs/content/kubernetes-tutorial.md

Seems like a better link target there 🤔

website/content/kubernetes-*.md: link GK to GK website

---

docs/content/kubernetes-introduction.md

It's been a while since GK was beta. 🎉

docs/kubernetes-introduction: update GK recommendation

---

rego/rego.go
rego/rego_test.go

This is useful if one does not prefer to use the ast.JSON(WithOpt) to do the
conversion.

rego: Add support for custom JSON marshaling of results.

---

CHANGELOG.md
capabilities/v0.32.0.json
version/version.go

Prepare v0.32.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.33.0 development

---

docs/content/envoy-tutorial-standalone-envoy.md

docs: Update the envoy standalone tutorial to use mgmt APIs

---

docs/devel/RELEASE.md

This URL is tied to the branch name which we changed to main a few
months ago. Needed to update the URL.

docs/devel: Update release curl command to trigger site deploy

---

CHANGELOG.md
capabilities/v0.32.1.json

This commit concludes the bugfix release process for 0.32.1.

Release 0.32.1: update CHANGELOG.md and capabilities

---

docs/content/kubernetes-tutorial.md

docs: Update the Kubernetes tutorial to use mgmt APIs

---

CHANGELOG.md
ast/check.go
ast/check_test.go
internal/presentation/presentation_test.go
types/decode.go
types/types.go
types/types_test.go

This PR lays the groundwork for the print() function.

Add initial support for varargs

---

cmd/eval.go

A command that previously just ran for a very long time can now be given
a deadline (analogously to `opa test`):
$ opa eval -fpretty --timeout 1s 'numbers.range(1, 100000000)[_] > 10000000'
1 error occurred: eval_cancel_error: numbers.range: timed out before generating all numbers in range

opa eval: add --timeout flag

---

docs/content/rest-api.md
server/server.go
server/server_test.go

- Add a new /health/{path} route to the server
- This route will eval policy defined at system.health with a query
based on the url path.
- If the policy returns true, the route will respond with a 200.
Otherwise, a 500.
- ~Log health check errors to provide clarity when health check fails.~ Return errors in response body
Fixes #3759

server: Policy-based health check

---

docs/content/rest-api.md
server/server.go
server/server_test.go
server/types/types.go

* Wrap entire plugin state get/set operation with mutex
* Tweak error messages returned to clients
* Tweak docs explaining use case for custom checks

server: Tweak custom health check implementation

---

ADOPTERS.md

Xenit AB is a fan of OPA and wants to express support. Great work, everyone!
As requested by @anderseknert .

Add Xenit AB as adopter

---

CHANGELOG.md
capabilities/v0.33.0.json
version/version.go

Prepare v0.33.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.34.0 development

---

docs/content/external-data.md

docs: fix typo in docs about external data

---

sdk/opa.go
sdk/opa_test.go
sdk/options.go

Fixes issue #3826. I'm openning this pretty early because I haven't committed to OPA before and am pretty new to Golang generally. I'll update this with documentation changes, but wanted to get feedback if this was an appropriate approach and any golang-style issue.

sdk: Allow map of plugins to be passed to SDK

---

cmd/test.go

issue: 3773 - change exit status when tests are skipped

---

CHANGELOG.md
docs/Makefile
docs/website/scripts/live-blocks/scripts/inject
format/format.go
format/testfiles/test.rego.formatted
format/testfiles/test_issue_3849.rego
format/testfiles/test_issue_3849.rego.formatted

This is #3851 + CHANGELOG entry.

Prepare 0.33.1 bugfix release

---

docs/content/deployments.md

This reverts commit d0a6f96, reversing changes made to b5e7139.

Revert inadvertent merge commit

---

docs/content/docker-authorization.md

Docker tutorial: Use bundle server

---

docs/content/deployments.md

These two capabilities-related things hadn't been documented before.

website/deployments/capabilities: mention Wasm ABI and future keywords

---

CHANGELOG.md
capabilities/v0.34.1.json
cmd/version.go
internal/report/report.go
internal/report/report_test.go
runtime/runtime.go
version/version.go

Cut v0.34.1 release with bugfix for logging configuration

---

CHANGELOG.md
capabilities/v0.34.1.json

Update CHANGELOG for v0.34.1 release

---

docs/website/assets/sass/docs.sass

Meeting https://github.com/open-policy-agent/opa/issues/3955
(needs to be tested)

Make version dropdown scrollable

---

.github/workflows/post-release.yaml
docs/content/development.md

ci: Add post release job to kick the netlify deploy

---

docs/website/scripts/load-docs.sh

This should avoid transient errors when the site builds while the
release is still in-progress.

website: Do not build for versions without a GitHub release

---

ast/parser.go
ast/parser_test.go
ast/term.go
storage/path.go
storage/path_test.go

Nothing dramatic, but all of them are worth fixing, I think 🤔 See the individual tiny commits, please.

ast: fuzzed parser bug, two codeql issues

---

README.md

- Minor language changes
- Replaced broken links
- Pointed to new contributor guides
- Removed examples section
- Added videos to the presentation section
- Updated headers to all be H2 for better readability

Readme updates Nov 2021

---

README.md

Tweak the README resource bullet list

---

CHANGELOG.md
capabilities/v0.34.2.json

Update CHANGELOG for v0.34.2 release

---

.github/workflows/codeql-analysis.yml

Disable autobuild for codeql

---

.github/workflows/codeql-analysis.yml

ci/codeql: Fix indentation issue

---

docs/content/management-decision-logs.md

This commit updates the decision log docs to include information about
some of recent improvements added to the decision log plugin around
rate limiting, log chunking etc.
Fixes: #3976

docs: Update decision log docs to cover controls for large-scale env

---

topdown/http.go

Fixes to http.send to prevent unnecessary client creation
and to disable HTTP keep-alives. See commits for details.
Fixes: #4016
Fixes: #4015

Fixes to http.send built-in

---

ast/check.go
ast/compile.go
ast/compile_test.go

ast/compile: replace rewritten declared vars for undefined func error

---

.github/stale.yml

.github: Add stale bot to mark issues & PRs after a period of inactivity

---

internal/wasm/sdk/internal/wasm/pool_test.go
internal/wasm/sdk/internal/wasm/vm.go

This is the analogous issue of https://github.com/open-policy-agent/npm-opa-wasm/issues/89.
Thanks to @nichenqin-treelab for reporting.
--------
Reproduced the error with a giant json blob from https://www.json-generator.com/ (put `'{{repeat(5000, 7000)}}',
` in the second line):
```
$ opa-0.34.1 eval -t wasm --input ~/Downloads/generated\ \(1\).json input
panic: runtime error: slice bounds out of range [:7626905] with capacity 1048576
goroutine 1 [running]:
github.com/open-policy-agent/opa/internal/wasm/sdk/internal/wasm.(*VM).Eval(0xc00026a400, {0x55dc0b0, 0xc00021c008}, 0x6ce5d00, 0xc0029cb210, {0x55e78b0, 0xc002b5b6e0}, {0x0, 0x0}, {0x0, ...}, ...)
/Users/runner/work/opa/opa/internal/wasm/sdk/internal/wasm/vm.go:313 +0x7ba
github.com/open-policy-agent/opa/internal/wasm/sdk/opa.(*OPA).E …
```

wasm/vm: grow memory if input exceeds available space (ABI 1.2)

---

runtime/runtime.go

runtime: Remove deprecated runtime.Params#DiagnosticsBuffer

---

server/authorizer/authorizer.go
server/authorizer/authorizer_test.go
server/server.go

Make print work for system.authz

---

docs/content/oauth-oidc.md

* Use raw body from JWKS response to avoid extra marshalling
* Simplify key rotation scenario by using kid as cache key

Improve OAuth2 / OIDC examples

---

CHANGELOG.md
capabilities/v0.35.0.json
version/version.go

Prepare v0.35.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.36.0 development

---

docs/content/comparison-to-other-systems.md
docs/content/docker-authorization.md
docs/content/envoy-performance.md
docs/content/envoy-primer.md
docs/content/envoy-tutorial-istio.md
docs/content/envoy-tutorial-standalone-envoy.md
docs/content/faq.md
docs/content/http-api-authorization.md
docs/content/integration.md
docs/content/kubernetes-debugging.md
docs/content/kubernetes-primer.md
docs/content/oauth-oidc.md
docs/content/policy-language.md
docs/content/policy-performance.md
docs/content/schemas.md
docs/content/security.md
docs/content/ssh-and-sudo-authorization.md
docs/content/terraform.md

Make sure that we try to follow our own recommended
best practices here. There's probabably more inconsistencies
out there, but you've gotta start somewhere.
Also fixed a few indentation issues and typos along the way.
I skipped the Kafka tutorial as I'll be working on that
separately.

Review docs on assignment, equality, comparison

---

plugins/logs/plugin.go
plugins/logs/plugin_test.go

Make print() work in decision masking policy

---

docs/content/contrib-code.md
docs/content/contrib-development.md
docs/content/contrib-docs.md
docs/content/contributing.md

This PR updates the layout of the contributing docs and adds a section for contributing new docs.

Update Contributing Docs

---

docs/content/policy-language.md

Add simple destructuring assignment example

---

docs/devel/DEVELOPMENT.md

DEVELOPMENT.md linked to non-existing development guide URL at https://www.openpolicyagent.org/docs/edge/development/; changing link to https://www.openpolicyagent.org/docs/latest/development/.
Fixes: #4083

docs/devel: Fixing broken link to development guide

---

COMMUNITY_GUIDELINES.md

Changed description for vendors to include any cloud-native services.

Update vendor guidelines

---

download/download_test.go
plugins/rest/rest.go
plugins/rest/rest_auth.go

Not much of consequence here, a few code cleanups in tests and interfaces.

download+rest: code cosmetics

---

go.mod
go.sum
vendor/github.com/bytecodealliance/wasmtime-go/README.md
vendor/modules.txt

Becasue dependabot won't do it.

build(deps): bump github.com/bytecodealliance/wasmtime-go from 0.31.0 to 0.32.0

---

docs/website/data/integrations.yaml

Signed-off-by: Or Weis<or@permit.io>

Authorizon rebranded as Permit.io

---

CHANGELOG.md
version/version.go

Prepare v0.37.0 development

---

.github/workflows/post-tag.yaml

Build darwin/arm64 in post tag workflow

---

docs/content/configuration.md

docs: fix configuration example

---

docs/content/ssh-and-sudo-authorization.md

Docs Update Add Missing Filename in SSH tutorial

---

cmd/eval.go

Add description for `--format=source` and
`--format=raw` to `opa eval -h` output.

opa eval: add description to all formats

---

docs/content/policy-performance.md

Must have missed these last iteration..

docs: Consistent indentation

---

cmd/inspect.go

People aren't going to find it unless we show it's there.

opa inspect: unhide command

---

build/changelog.py

Since Github will automatically link to user profiles mentioned
by their username, _and_ create a "Contributors" section for the
release notes with user avatars, it seems good to follow that
convention.

cicd: Update release notes mentions

---

.github/workflows/post-tag.yaml
CHANGELOG.md
capabilities/v0.36.1.json
docs/content/configuration.md
docs/content/integration.md
docs/content/security.md
docs/content/ssh-and-sudo-authorization.md
version/version.go

Docs fixes, and the experimental darwin/arm64 binary.

Prepare 0.36.1 Release

---

build/policy/files.rego

Follow redirects in http.send Rego checks

---

.github/workflows/post-merge.yaml
build/commit-cli-docs.sh
build/gen-cli-docs.sh
build/generate-cli-docs/generate.go
cmd/build.go
cmd/eval.go
cmd/flags.go
cmd/run.go
cmd/sign.go
docs/Makefile

Add CLI section to docs

---

.github/workflows/post-merge.yaml

Commit generated code/docs in same job

---

docs/content/policy-testing.md

docs: Add reference to rule indexing wrt coverage

---

.github/workflows/pull-request.yaml

Change setup-opa action to new location

---

ADOPTERS.md

ADOPTERS.md: Add Appsflyer to the list

---

tester/runner.go
tester/runner_test.go

See the detail description on: https://github.com/open-policy-agent/opa/issues/4245
Fixes: #4245
Signed-off-by: Stefano Del Tufo <stefano.deltufo@mia-platform.eu>

tester: Runner supports also custom builtins

---

sdk/opa_test.go
test/e2e/certrefresh/certrefresh_test.go

Changing some delays, hoping for the best 🤞

address macos-latest test flakes

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/collector.go
vendor/github.com/prometheus/client_golang/prometheus/go_collector_go117.go
vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
vendor/modules.txt

This reverts commit 42a559c99ae646613e6f6bdf9940fb076febae6a.

Revert "build(deps): bump github.com/prometheus/client_golang (#4307)"

---

CHANGELOG.md
capabilities/v0.37.1.json

Pull CHANGELOG and capabilities updates into main from v0.37.1

---

ast/compile.go
ast/compile_test.go
ast/index_test.go
ast/internal/tokens/tokens.go
ast/parser.go
ast/parser_test.go

Please see the individual commits. So far, nothing is evaluated, so this should do little harm.

ast: misc changes re: 'every'

---

internal/planner/planner.go
internal/wasm/sdk/test/e2e/exceptions.yaml
test/cases/testdata/every/every.yaml
test/cases/testdata/every/textbook.yaml

planner: fix plan for 'every'

---

docs/content/_index.md
docs/content/policy-language.md
docs/content/policy-reference.md

This:
- adds a brief not to the index page
- adds a section on "Every Keyword" to policy-language
Part of #2090.

docs: every keyword

---

docs/README.md

This adds instructions to the docs readme file to show how to check google analytics.

Include Google Analytic Instructions in Readme

---

docs/content/envoy-primer.md

Previously, the Envoy primer provided samples of policies for
status-code, body, and headers that explicitly returned an object
in individual rules instead of the more common and recommended
approach of using separate variables for each concern.
This change replaces those sample policies with ones that use
variables for each of allow, status_code, headers, body,
and it adds a section on the output expected by Envoy,
where we include the snippet combining those variables into
the JSON object expected by Envoy.

docs: Update Envoy primer to use variables instead of objects

---

Makefile

make: Disable WASM by default on darwin/arm64

---

CHANGELOG.md
version/version.go

Prepare 0.39.0 dev

---

ast/annotations_test.go

Example code mirrors that in documented in docs/content/annotations.md, to make sure it compiles and behaves as expected.

ast: Adding example test for ast.AnnotationSet.Flatten()

---

.github/workflows/pull-request.yaml
Makefile

Use gid=1000 in -rootless images

---

cover/cover.go
cover/cover_test.go

Thanks @srenatus for the suggested fix.
Fixes #4393

coverage: remove duplicates from coverage report

---

docs/content/_index.md

These are two common questions that come up and we do not mention this
anywhere else in the docs.

docs: mention who created OPA and who owns it

---

docs/website/data/integrations.yaml

- Use keys for "software"
- Remove duplicate
- Remove commented out entries

Fixup: integrations.yaml

---

go.mod
go.sum
vendor/github.com/bytecodealliance/wasmtime-go/README.md
vendor/modules.txt

https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0350

build(deps): bump wasmtime-go 0.34.0 -> 0.35.0

---

.github/workflows/pull-request.yaml
build/policy/files.rego
build/policy/files_test.rego
build/policy/helpers.rego

cicd: verify logo name matches integration

---

docs/README.md

Signed-off-by: Omri Gazitt <ogazitt@gmail.com>
This PR adds a brief note about potential version mismatches for 
Hugo. Current builds (0.94) are incompatible with the Hugo version 
required by the OPA documentation site (0.88.1). This note will 
hopefully save other the effort of discovering this the hard way.

Added a note to the README about Hugo version mismatch errors.

---

docs/content/management-bundles.md

docs: Update format of the delta bundle patch file

---

docs/content/envoy-primer.md

This commit adds documentation for the new control headers
for the upstream and downstream client supported by the
OPA-Envoy plugin.

docs: Update Envoy policy primer with new control headers

---

docs/website/static/support.html

docs/website: Update support link for Styra

---

docs/website/layouts/index.redirects

bug introduced when merging https://github.com/open-policy-agent/opa/pull/4474

website: fix download link redirect

---

docs/website/layouts/index.redirects

I doubt it matters much, but it's still nicer without rough edges.

website: fix whitespace in _redirects file

---

Makefile

Looks like we've done that for a while now? 🤔 
☝️ Just when we've done it once we'll do it again. Let's avoid that.

website: don't run generate twice

---

MAINTAINERS.md

Sorry @tsandall , I thought I had pushed the "make alphabetical" fix before merging.
Signed-off-by: Max Smythe <smythe@google.com>

Make maintainers list alphabetical

---

sdk/opa.go

Ensure that the same state is processed in the `executeTransaction`.

sdk: avoid using different state

---

docs/content/management-bundles.md

This commit adds some clarification to the bundle doc regarding
the format of bundle signatures and manifest behavior for delta
bundles.

docs: Add clarifications for docs describing bundle signing and delta features

---

docs/content/management-bundles.md

docs/management-bundles: replace quotations with info boxes

---

docs/content/aws-cloudformation-hooks.md

Add AWS CloudFormation Hook tutorial.
Some own thoughts:
* Should we shorten the title to just CloudFormation. It's currently longer than the rest in the section..
* Obviously missing is deployment of OPA to AWS. This will come in the next iteration.

Add CloudFormation tutorial

---

CHANGELOG.md
capabilities/v0.39.0.json
version/version.go

Prepare v0.39.0 release

---

docs/website/static/support.html

website: fix styra support link

---

ADOPTERS.md

Signed-off-by: hannahyeates <hannahgrey06@gmail.com>

Add Wealthsimple to list of adopters

---

docs/website/assets/sass/docs.sass

Signed-off-by: orweis <orweis@gmail.com>

remove right margin on sidebar

---

ADOPTERS.md

adopters: Add Wiz

---

docs/content/ssh-and-sudo-authorization.md

Update SSH tutorial to use bundle api

---

docs/content/annotations.md

to reflect that they are a mapping and not a list.

docs: Updating 'custom' annotation docs

---

ADOPTERS.md

ADOPTERS: update Wiz text

---

docs/website/layouts/index.html
docs/website/layouts/partials/javascript.html

website: add SRI to static html files

---

docs/content/kubernetes-primer.md

docs: bump number of built-ins

---

ast/compile.go
cmd/eval_test.go

Small oversight in the larger `rego.metadata.*` built-in work in #4537

ast: Respecting capabilities built-ins for rego.metadata.* functions

---

ast/compile.go
topdown/trace_test.go

Adding missing location data for replaced rego.metadata.* calls

---

docs/content/policy-language.md

We should really start with `every`, then offer alternatives, and
call out common mistakes in those alternatives after having presented
the proper solution.
Also replaces some one-letter-rule names in the detailled presentation
of `every`.
Fixes #4603.

docs/policy-language: reorder Universal Quantification content

---

docs/content/policy-testing.md

Additionally, simplify one test example.

Use assignment operator in mocks

---

docs/website/layouts/index.html

Update links for the Kubernetes examples in the website to examples using the latest schema, as specified in #3991.

Update k8s examples to the latest schema

---

docs/content/policy-reference.md

docs: Fix incorrect padding claims

---

docs/website/data/integrations.yaml

Add Sansshell entry to OPS integrations

---

docs/content/external-data.md

Thanks @pvsone for pointing this out!

Remove bullet point on missing function mocking

---

docs/content/kubernetes-introduction.md

Remove Katakoda link

---

ADOPTERS.md

Signed-off-by: Ali Khajeh-Hosseini <alikhajeh1@googlemail.com>

Add Infracost to ADOPTERS.md

---

CHANGELOG.md
capabilities/v0.41.0.json
version/version.go

Prepare v0.41.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.42.0 development

---

docs/content/configuration.md

Closes: https://github.com/open-policy-agent/opa/issues/4680

Update configuration docs - usage of private images from OCI registries

---

test/cases/testdata/withkeyword/test-with-builtin-mock.yaml

testcases/withkeyword: add package extent query for function mocks

---

.github/workflows/pull-request.yaml

It's more hassle than it's worth right now

ci: remove npm-opa-wasm check

---

test/cases/testdata/aggregates/test-aggregates-0028.yaml
test/cases/testdata/objectfilter/test-objectfilter-0314.yaml
test/cases/testdata/objectfilter/test-objectfilter-0315.yaml
test/cases/testdata/objectfilter/test-objectfilter-0316.yaml
test/cases/testdata/objectfilter/test-objectfilter-0317.yaml
test/cases/testdata/objectremove/test-objectremove-0294.yaml
test/cases/testdata/objectremove/test-objectremove-0295.yaml
test/cases/testdata/objectremove/test-objectremove-0296.yaml
test/cases/testdata/objectremove/test-objectremove-0297.yaml
topdown/aggregates.go
topdown/object.go

Fix wrong type error message in count, object.filter, object.remove

---

docs/content/kubernetes-tutorial.md

docs: remove unused assignement in Kubernetes tutorial example

---

test/cases/testdata/comparisonexpr/test-comparisonexpr-0619.yaml
test/cases/testdata/comparisonexpr/test-comparisonexpr-0620.yaml

Add a few int/float comparison tests

---

test/e2e/oci/oci_test.go

Fix https://github.com/open-policy-agent/opa/issues/4748

Prevent flaky oci e2e test

---

builtin_metadata.json
internal/cmd/genbuiltinmetadata/main.go

build: omit empty descriptions of function args

---

docs/website/layouts/index.html

~🛑 This needs to wait until 0.42.0 is released and the playground is updated for the playground links to work.~
ℹ️ Merges to the website frontpage are instantaneous, so if we merge this, openpolicyagent.org will be updated right away -- not on the next release. So it's OK merge this after the next release has been cut and the playground has been updated. (We should use that moment to check the published links.)

website/frontpage: update examples

---

docs/website/scripts/live-blocks/src/preprocess/localEval.js

This had been failing for a while now and nobody noticed 🙈 
This should fix it, but ultimately, we'll see post-merge 🤞

website: fix deployment to openpolicyagent.org

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.42.1.json
docs/content/policy-testing.md
server/server.go
server/server_test.go
storage/inmem/inmem.go
storage/inmem/inmem_test.go
version/version.go

Prepare patch release 0.42.1

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.42.1.json

ℹ️ This should fix the empty built-in functions docs sections for 0.42.1 and latest, too.

CHANGELOG,caps,metadata: integrate v0.42.1

---

docs/website/layouts/partials/docs/dashboard-panel.html
docs/website/layouts/partials/docs/navbar.html

Resolves #3353
This was done so that the Navbar text does not vanish once the screen resolution hits 1024px, it will instead shrink the navbar with the content until it hits tablet size and the hamburger menu will appear.
Tested locally with Netlify Dev and it looks okay.

Docs navbar resizing issue

---

storage/disk/disk.go

storage/disk: Unlock mutex on error

---

README.md

Signed-off-by: Peter ONeill <peteroneilljr@gmail.com>

README updated for new office hours format

---

docs/content/graphql-api-authorization.md

docs: Replace OPA docker image tag with shortcode

---

storage/inmem/inmem.go
storage/inmem/inmem_test.go

While writing data to the in-memory store via truncate op,
OPA reads data at the current path before adding
new data to the store to ensure the path exists.
A bundle that contains data files at non-root locations will
trigger a read on the store for each file and hence for a large
bundle this can cause an increase in the bundle activation time
and also resource usage.
This change attempts to avoid multiple read ops by merging all the data
in the bundle and performing a single write on the store.

storage/inmem: Avoid unnecessary read operation

---

ADOPTERS.md

Adding GKE Policy Automation to the ADOPTERS file. The tool is already present in the integrations site.
Signed-off-by: Mikolaj Stefaniak <mstefaniak@google.com>

ADOPTERS: added GKE Policy Automation

---

docs/website/data/integrations.yaml

Add missing video section, and update a few links.

Update Styra DAS ecosystem entry

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.43.0.json
version/version.go

Version 0.43.0 is almost ready to ship!
Review/comments appreciated. :+1:

Prepare v0.43.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.44.0 development

---

test/cases/testdata/cryptox509parsersaprivatekey/test-cryptox509parsersaprivatekey-1.yaml
test/cases/testdata/helloworld/test-helloworld-1.yaml
test/cases/testdata/regometadatachain/test-regometadatachain-1.yaml
test/cases/testdata/regometadatarule/test-regometadatarule-1.yaml

Hacking on IR implementations for the builtins revealed
some missing tests, which are added here.
Also brought back the comment providing instructions for
running the tests in the helloworld directory, as this was
mistakenly removed by the massive cleanup PR some month back.

Add a few missing tests

---

test/cases/testdata/units/test-parse-bytes-errors.yaml
test/cases/testdata/units/test-parse-units-errors.yaml

Add error type to units.* builtin test assertions

---

docs/content/graphql-api-authorization.md

- Use port 6000 to the tutorial mac and linux friendly
- put bundles to a folder

Docs: GraphQL update serving port and make bundles folder

---

plugins/rest/aws.go

Add query param in canonical request of aws Sigv4 signature to avoid 403 from aws
Fixes #4954
Signed-off-by: Ankit Kumar Sinha <ankitsinhaiitg@gmail.com>

Fix aws Sigv4 signature

---

docs/content/annotations.md

docs: Fixing related_resources annotations example

---

bundle/store_test.go
storage/disk/disk.go
storage/disk/disk_test.go
storage/inmem/inmem.go
storage/inmem/inmem_test.go

Fixes https://github.com/open-policy-agent/opa/issues/4958
Signed-off-by: Martin Johansen <martinjohansen1705@gmail.com>

fixes #4958

---

ADOPTERS.md

As discussed at #4945, I create a pull request to add my organization(VNG Cloud) to [Adopters](https://github.com/open-policy-agent/opa/blob/main/ADOPTERS.md) file.

VNG Cloud has adopted OPA

---

docs/content/policy-reference.md

Fixing typo `higer > higher` in metadata example, #5018 
No update to tests required
No code changes performed
Signed-off-by: Eric Cimino <ecimino@vailsys.com>

fixing typo in metadata

---

docs/content/kafka-authorization.md
docs/website/data/integrations.yaml

Update links to opa-kafka-plugin

---

.github/workflows/nightly.yaml
.github/workflows/post-merge.yaml
.github/workflows/post-release.yaml
.github/workflows/post-tag.yaml
.github/workflows/pull-request.yaml

Tried this in #5030 before, looked good. Will merge when green.

ci: ubuntu 18.04 -> 22.04

---

cmd/eval.go
cmd/eval_test.go

cmd: Add optimize flag to OPA eval command

---

ast/builtins.go
builtin_metadata.json

Fix typo in semver.compare docs

---

bundle/file.go
bundle/file_test.go
bundle/filefs.go
bundle/filefs_test.go
cmd/build_test.go
internal/runtime/init/init.go
internal/runtime/init/init_test.go
loader/filter/filter.go
loader/loader.go

Fix opa build in bundle mode to work with ignore flag

---

docs/website/data/integrations.yaml

Link for Minio/OPA integration has moved. Fix the broken link

Fix broken link

---

test/cases/testdata/objectunionn/test-objectunionn-0001.yaml
topdown/object.go

fix unchecked err in union_n

---

ast/builtins.go
ast/compile_test.go
builtin_metadata.json
docs/content/strict.md
internal/cmd/genbuiltinmetadata/main.go

Additionally, propagate deprecated status (if deprecated = true)
to the builtin_metadata.json file.
Fixes #5072

Add deprecated flag to all deprecated builtins

---

docs/website/data/integrations.yaml

ecosystem: add article on using OPA for data filtering in Kafka

---

docs/website/data/integrations.yaml

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

Added some links to Rönd.

---

.github/workflows/nightly.yaml

Let's see how this plays out.  See https://go.dev/security/vuln/ for details.

ci: try govulncheck from nightly

---

.github/workflows/nightly.yaml

Since one of them had been failing for two weeks, unnoticed...

ci(nightly): send notifications for trivy and govulncheck checks

---

docs/website/static/css/security.css

Signed-off-by: orweis <orweis@gmail.com>

Quick facelift for security page :)

---

util/backoff.go

It has a negligible impact, but since security scanners like gosec will pick this up, let's do it in a way that'll pass inspection.

util/backoff: seed math/rand source

---

ast/compile.go
test/cases/testdata/withkeyword/test-withkeyword-1054.yaml

Signed-off-by: liu-du <duliujimmy@hotmail.com>

rewrite declared variables in function call in with clause

---

docs/content/configuration.md
plugins/logs/encoder.go
plugins/logs/encoder_test.go

Fixes https://github.com/open-policy-agent/opa/issues/5155

decision logging: Improve error message when chunk size > limit 

---

ast/compile.go
ast/compile_test.go
test/cases/testdata/withkeyword/test-withkeyword-1054.yaml

Signed-off-by: liu-du <duliujimmy@hotmail.com>

recursively rewrite local variables in with value

---

docs/content/philosophy.md

Credits to @rahulratnagiri-wmt

Fix typo in OPA document model docs

---

cmd/deps.go
cmd/eval.go
cmd/test.go
docs/content/ir.md

Update examples for CLI commands

---

cmd/run.go
docs/content/cli.md
docs/content/privacy.md
internal/report/report.go
internal/report/report_test.go

internal/report: Include heap usage in the telemetry report

---

README.md
docs/content/contrib-code.md
docs/content/contrib-docs.md
docs/content/contributing.md

No tests: these are doc changes only.

docs: Update mentions of #development to #contributors

---

ast/compile.go
ast/compile_test.go

Resolves #5183 
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>

fix: Fix race condition in json schema parsing with reused references

---

docs/content/envoy-tutorial-gloo-edge.md

Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>
Hey @ashutosh-narkar 
Sorry, fixed my branch and re-opened a pull request.
This is for the Gloo Edge tutorial, I have tested this myself and it seems to work fine.
For #3199 😁
Thank you!

Added tutorial for Gloo Edge

---

docs/content/contrib-development.md

Also, update docs to clarify that forking is needed before cloning, as that was not immediately apparent.

docs: provide some tips for style fixes

---

internal/planner/planner.go
test/cases/testdata/planner-ir/test-array-ir-unify.yaml

planner: unify array and array comprehension

---

MAINTAINERS.md

Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
This needs a 2/3 vote at the organization level per https://github.com/open-policy-agent/opa/blob/main/GOVERNANCE.md#changes-in-maintainership

Move chewong to emeritus

---

test/cases/testdata/functionerrors/test-conflicts.yaml
topdown/eval.go

topdown: capture prev function result in the "false" case, too

---

wasm/README.md

Update Wasm README

---

cmd/test.go
cmd/test_test.go

add a range check to threshold, fix #5284
Signed-off-by: Bin Liang <hzliangbin@foxmail.com>

fix: coverage limit overflow

---

.github/workflows/post-tag.yaml

Very silly typo here https://github.com/open-policy-agent/opa/actions/runs/3384020392/jobs/5620518946

workflow/post-tag: fix typo

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.46.1.json
version/version.go

The code of 0.46.1 and 0.46.0 is identical. This bufix release is because of pipeline woes.

Prepare fix release v0.46.1

---

CHANGELOG.md
version/version.go

Prepare development v0.47.0

---

ast/annotations.go
cmd/eval_test.go

This commit adds type coercion guards around the AST annotation set building logic, to avoid panics when nil values appear.
Nil node values can happen here after copy-propagation, because the AST nodes can be ripped out from under the annotation system when they are pruned away or inlined into other rules.
Fixes: #5368

ast/annotations: Add type coercion guards to avoid panics.

---

ast/compile.go
cmd/eval.go
cmd/eval_test.go
docs/content/cli.md
rego/rego.go

Working on adding strict flag to opa eval
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>

Add strict flag opa eval

---

docs/website/data/integrations.yaml

As per their request. They will re-add it themselves once approved internally.

Remove Datadog from ecosystem page

---

ast/parser.go
ast/parser_test.go
format/testfiles/test_issue_5348.rego
format/testfiles/test_issue_5348.rego.formatted

Fix assignment rewrite in else formatting

---

download/oci_dowload.go
download/oci_download_test.go
download/testharness.go

Fixes: https://github.com/open-policy-agent/opa/issues/5212
Signed-off-by: carabasdaniel <dani@aserto.com>

OCI download - Set auth credentials for docker authorizer if needed

---

.github/workflows/nightly.yaml

This has been broken for a few nights after moving the performance job...

ci: fix nightly job

---

docs/content/policy-reference.md

docs: mention base64 URL encoding specifically

---

docs/website/data/integrations.yaml

integrations: fix malformed inventors item

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.46.2.json
capabilities/v0.47.1.json

This should conclude the release process. When the website builds for this commit, the patch releases should show up on it.

Integrate v0.46.2 and v0.47.1

---

docs/content/_index.md

This should help users new to OPA learn about bundle file structure if they're confused at this point in the introduction.

docs: Update opa eval flags to link to bundle docs

---

sdk/opa.go
sdk/opa_test.go
sdk/test/test.go

https://github.com/open-policy-agent/opa/pull/5459 has been merged so ready for a review here now :)
This completes the work on #5176 by returning provenance information
Fixes https://github.com/open-policy-agent/opa/issues/5176

sdk: Return provenance information in Result types

---

plugins/discovery/discovery_test.go
plugins/plugins.go
plugins/plugins_test.go
server/server.go

Add support to enable ND builtin cache via discovery

---

README.md

For some reason, it wasn't even mentioned here.

docs: make SDK first option for Go integraton

---

docs/content/annotations.md
docs/content/configuration.md
docs/content/contrib-adding-builtin-functions.md
docs/content/contrib-code.md
docs/content/policy-reference.md
docs/content/rest-api.md
docs/content/schemas.md
docs/content/wasm.md

Fix doc typos

---

ast/visit_test.go

probably overlooked in https://github.com/open-policy-agent/opa/pull/5515
found when reading the recent works

chore: fix len in the error msg

---

ADOPTERS.md

Digraph is using OPA to power its rules engine to test IAC for compliance

Adding Digraph to ADOPTERS.md

---

build/changelog.py

But no need to mention when maintainers are issue reporters, so keep that as is.
Signed-off-by: Anders Eknert <anders@styra.com>

Remove changelog maintainer mention filter

---

docs/content/security.md

Fixes #5521
The fix is adding `-sha256` to use SHA 256 digests for certificates rather than SHA1. Since go 1.18, SHA1 is rejected by go TLS. (https://github.com/golang/go/issues/41682)
This PR also updates the tutorial to use ECDSA keys, reduces the lifetimes of the certs used and updates the sample logs to match what OPA and curl show today.

[docs] Update TLS-based Authentication Example

---

docs/content/philosophy.md

update philosophy.md, fix typo

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.48.0.json
version/version.go

Here's the WIP release PR for `v0.48.0`! :smile: 
My main items of concern for these release notes:
- Typos or anything I might have missed cleaning up the commit messages.
- Should we call out the new AWS SigV4A support for bundle fetching?

Prepare v0.48.0 release

---

docs/website/data/integrations.yaml

ccbr tool join in opa ecosystem
update code file:docs/website/data/integerations.yaml
history discussion:
https://github.com/open-policy-agent/opa/pull/5088
Signed-off-by: Zhi Niu yulinniuzhi@163.com

ccbr tool join in opa ecosystem

---

cmd/build.go
docs/content/annotations.md
docs/content/cli.md

with note about transitive dependencies enumerated as "extra" entrypoints.
Fixes: #5565

docs: Updating entrypoint documentation

---

ast/builtins.go
builtin_metadata.json

Related to https://github.com/open-policy-agent/opa/issues/5584

Clarify crypto.x509.parse_certificates docs

---

docs/content/management-bundles.md

docs: Add missing folder argument in build example

---

docs/content/management-bundles.md

https://github.com/open-policy-agent/opa/issues/5562
In the official do under [Amazon S3 Authentication section](https://www.openpolicyagent.org/docs/latest/management-bundles/#authentication) the information related to web_identity_credentials is missed. The [information present here](https://github.com/RichiCoder1/opa/blob/276166593ac8b7cb80c336868b17d2b67281008f/docs/content/configuration.md#using-eks-iam-roles-for-service-account-web-identity-credentials) should be present in the main doc website.
I was facing the issue by using the Metadata Credentials mentioned in the official docs. However, my issue is solved when I used web_identity_credentials.

Added AWS S3 Web Identity Credentials info in docs

---

docs/website/data/integrations.yaml

The existing link was broken, this patch contains the updated one.

Update OPAL tutorials link

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.49.0.json
version/version.go

Prepare v0.49.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.50.0 development

---

docs/content/policy-reference.md

Change from "affect" to "effect" in print built-in description

Fix policy reference doc typo

---

docs/content/policy-language.md

docs: Add comment on comprehension in default assignment

---

docs/content/management-bundles.md

Fixes https://github.com/open-policy-agent/opa/issues/5629

docs: Clarify delta bundle behavior

---

cmd/run.go
docs/content/configuration.md
runtime/runtime.go
runtime/runtime_test.go

cli: allow remote bundle URL shorthand for run command

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.49.1.json

Integrate patch release v0.49.1

---

docs/devel/RELEASE.md

docs: Fix patch file name in bugfix rel steps

---

cmd/oracle.go
cmd/oracle_test.go

Try and fix errors issues reported here:
https://github.com/open-policy-agent/vscode-opa/issues/81
1. Only include .rego files in definition location checks
2. Don't hang if input not provided on stdin

cli: try fix issues reported in 'oracle' command

---

docs/content/_index.md

- Fixes broken 'future keywords' URL link

chore(docs): Fixes broken 'future keywords' URL link

---

builtin_metadata.json
internal/cmd/genbuiltinmetadata/main.go

docs: ignore deprecated built-ins in reference

---

cmd/capabilities.go
docs/website/layouts/shortcodes/builtin-table.html

* Use two spaces to indent JSON, not one
* Fix wrong closing tag in built-in reference

chore: capbilities fixes

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.49.2.json

Integrate patch release v0.49.2

---

docs/content/kubernetes-introduction.md

- Just fix broken link in docs

[docs]: fix broken link

---

bundle/bundle.go
bundle/bundle_test.go

bundle: merge should not set data to nil

---

ast/visit.go

And point developers to what to use instead

chore: Use proper deprecated comments

---

ADOPTERS.md

I have also updated the CTA at the bottom of the file
Fixes https://github.com/open-policy-agent/opa/issues/5729

Add 2U to adopters.md

---

docs/content/management-status.md

docs: Add example of decision log error surfaced via status

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.50.0.json
version/version.go

Prepare v0.50.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.51.0 development

---

docs/content/integration.md

`ctx` is used before it is defined in the example.

docs: move definition of ctx before first use

---

docs/content/security.md

In https://github.com/open-policy-agent/opa/pull/5742 we added support for more advanced authz policy. This PR updates the docs to explain how to use this new functionality with a best-practice example based on SPIFFE IDs.

Update TLS authentication docs

---

bundle/bundle.go
bundle/file.go
bundle/store.go

Use Normalized policy paths as compiler module keys and store ids

---

CHANGELOG.md
ast/compile.go
ast/compile_test.go
builtin_metadata.json
bundle/bundle.go
bundle/file.go
bundle/store.go
capabilities/v0.50.1.json
compile/compile_bench_test.go
version/version.go

Release 0.50.1

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.50.1.json

Integrate patch release v0.50.1

---

ast/compile.go
ast/compile_test.go

Fix: #5662 
This adds a for loop to query the location of the unassigned variables in `checkUnusedAssignedVars()` thru the body.
Is there a better way to get the location of a variable? 
Tests:
assume you have the following
```rego
package test
allow {
input.message == "world"
input.test == "foo"
input.x == "foo"
input.y == "baz"
a := 1
b := 2
x := {
"a": a,
"b": "bar",
}
input.z == "baz"
c := 3
}
```
so the result would be as the following
```shell
{
"errors": [
{
"message": "assigned var b unused",
"code": "rego_compile_error",
"location": {
"file": "check-error-loc.rego",
"row": 9,
"col": 5
}
},
{
"message": "assigned var x unused",
"code": "rego_compile_error",
"location": {
"file": "check-error-loc.rego",
"row": 10,
"col": 5
}
},
{
"message": "assigned var c unused",
"code": …
```

bug(ast): fix the location of the unused variables

---

download/download.go

The need would be if `d.persist` is true: we're writing it into a file in a later code path.
However, if we don't have bundle persistency enabled, this should allow us to get rid of one copy of the bundle in memory. To achieve that, the mechanism used to figure out the bundle size is replaced:
- Before, we'd write it into a buffer that we might not need, and use its Len()
- After, we're writing it into a no-op io.Writer that only keeps track of the bytes read.

download: copy bundle into buffer only if needed

---

docs/website/assets/sass/docs.sass

Fixes https://github.com/open-policy-agent/opa/issues/5774

[docs/website] Fix floating navbar anchor issue

---

CHANGELOG.md
ast/compile.go
ast/compile_test.go
builtin_metadata.json
capabilities/v0.50.2.json
version/version.go

Release 0.50

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.50.2.json

Integrate patch release v0.50.2

---

go.mod

Following future advice on: https://github.com/golang/go/issues/58925

Update retract directive comment

---

plugins/rest/rest.go
plugins/rest/rest_test.go

This commit updates the client debug log to include the full HTTP response in case of non-200 status codes. Recording the response in the logs can help to provide more information to debug error scenarios.
Fixes: #2961

plugins/rest: Include truncated HTTP response in logs

---

docs/content/_index.md

Update _index.md, adding Windows checksums file name information

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.51.0.json
version/version.go

Prepare v0.51.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.52.0 development

---

.github/PULL_REQUEST_TEMPLATE.md

This change updates the PR template structure to
help authors explain their changes thereby resulting in efficient reviews.

Update PR template structure

---

MAINTAINERS.md

@srenatus I think you are the only person who technically has a non-expired membership. Not sure if we want to be technocratic about this, (IMO keep the old +1 quorum), but we should get this taken care of.
@ashutosh-narkar
@ritazh 
@sozercan 
@srenatus 
@timothyhinrichs
@tsandall

Refresh maintainers, Add gatekeeper-library maintainers.

---

docs/website/data/integrations.yaml

Update to ecosystem page for https://docs.reposaur.com project

Add Reposaur

---

cmd/eval.go

When using `--profile-sort` on opa eval it's not clear from the CLI help what the valid options are.
Add valid options for `--profile-sort` to help command

Profile sort options

---

docs/content/configuration.md
plugins/rest/aws.go
plugins/rest/aws_test.go

for aws rest plugin
Fixes: #5915

rest: Making Amazon AWS STS domain configurable

---

README.md

We're pausing on running these for now, but might bring them back in the future if there's demand.

Remove office hours sign-up

---

.github/stale.yml

.github: Update stale issue comment to clarify issue status

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.53.0.json
version/version.go

Prepare v0.53.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.54.0 development

---

download/oci_download.go
download/oci_download_test.go
download/testharness.go

Public docker repositories require an authorization hand shake where the client needs to respond to challenges marked by the WWW-Authenticate header of a 401 Unauthorized response. Currently, we assume not authorization is necessary for public repositories which causes the error in #5902.
This commit passes requests to the docker.Authorizer after our custom plugin authorization. Any 401 response will be challenged by it.

download: Pass request to docker.Authorizer

---

loader/loader.go
loader/loader_test.go

loader: add WithReader to pass io.Reader directly

---

docs/website/static/community.html
docs/website/static/css/community.css
docs/website/static/css/home.css

This is not something that we're promoting at the moment.
https://github.com/open-policy-agent/opa/assets/1774239/402ad2ab-fab1-423b-afcf-c5cba161c645

Remove newsletter sign-ups

---

docs/content/kubernetes-debugging.md

annotation was changed in PR163 in kube-mgmt, see also https://github.com/open-policy-agent/kube-mgmt/pull/163 and doc fix in kube-mgmt https://github.com/open-policy-agent/kube-mgmt/pull/213
updates to documentation
see PR links above
N/A

[docs] Update kube-mgmt annotation 

---

docs/website/data/integrations.yaml

Other integrations explain a little more about their use case in the title.

Clarify Regal linter title

---

docs/website/data/integrations.yaml

Also update project description to match styra.com copy

[docs] Update 404 links in Styra Enterprise OPA listing

---

topdown/eval.go
topdown/topdown_partial_test.go

topdown: fix panic in partial eval with ref head rule

---

server/server.go
server/types/types.go
server/writer/writer.go

Mixed bag of code cleanups in `server/server.go`, without any changes in functionality. I've been meaning to do this for a long time 😅

server: cleanup some handler code

---

server/server.go

This came up in the discussion of the previous cleanup PR, but I hadn't gotten around to include it back then.
(#6057)

server: extra cleanup

---

build/gen-dev-patch.sh
build/gen-release-patch.sh

Updating release patch scripts to not include CR in output

---

download/oci_download.go
internal/wasm/sdk/opa/opa.go
plugins/discovery/discovery_test.go
plugins/status/plugin_test.go
test/e2e/authz/authz_bench_integration_test.go

package "github.com/open-policy-agent/opa/internal/wasm/sdk/opa/errors" is being imported more than once
package "oras.land/oras-go/v2" is being imported more than once
package "github.com/open-policy-agent/opa/bundle" is being imported more than once
package "github.com/prometheus/client_golang/prometheus" is being imported more than once
package "github.com/open-policy-agent/opa/test/authz" is being imported more than once

chore: pkg imported more than once

---

ast/builtins.go
builtin_metadata.json
capabilities.json
test/cases/testdata/cryptoparsersaprivatekeys/test-cryptoparsersaprivatekey-1.yaml
topdown/crypto.go
topdown/crypto_test.go

see #6076
This change allow us to compare the public key of a private key with a csr and a certificate. This allows us to verify complete pairs and complements `crypto.x509.parse_certificate_request` and `crypto.x509.parse_certificates` in that it returns the same values.
* Added a new block(`blockTypeEcPrivateKey`) to `getRSAPrivateKeyFromPEM`  to allow parsing `EC PRIVATE KEY`
* new method `parsePrivateKey()`
See tests in `TestParsePrivateKey()` in `/topdown/crypto_test.go`

#6076 crypto parse private key

---

docs/content/envoy-tutorial-standalone-envoy.md

This line appears to have been truncated.

[docs] Correct envoy tutorial mistake

---

download/oci_download.go

Comment should have the following format 'XXX...' (with an optional leading article)

chore: Comment should with an optional leading article

---

docs/content/deployments.md

OPA has an endpoint for health check, but it's missing the "livenessProbe" configuration in the documentation.
Specify "path" for "livenessProbe"

docs: specify "path" for livenessProbe

---

ast/builtins.go
builtin_metadata.json

Fixes https://github.com/open-policy-agent/opa/issues/6131

Explain date normalization in time.add_date

---

docs/devel/RELEASE.md

https://github.com/open-policy-agent/opa/issues/6133#issuecomment-1666152457

Add note about updating search index after release

---

CONTRIBUTING.md

Fixes https://github.com/open-policy-agent/opa/issues/6146

[docs] Update contributing page link to latest not edge

---

ast/check.go

From the Go docs:
> "For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/2TugLncT_ob
Removes an unnecessary nil check around the loop in AST.
The diff looks weird but the change is just
Before:
```go
if schemaAnnots := getRuleAnnotation(as, rule); schemaAnnots != nil {
for _, schemaAnnot := range schemaAnnots {
...
}
}
```
After:
```go
schemaAnnots := getRuleAnnotation(as, rule)
for _, schemaAnnot := range schemaAnnots {
...
}
```

ast: remove unnecessary nil check

---

server/authorizer/authorizer.go

server/authorizer: inline readBody

---

cmd/run_test.go
internal/gojsonschema/jsonschema_test.go
runtime/logging_test.go
runtime/runtime_test.go
server/server_test.go
test/e2e/diagnostics/diagnostics_test.go
test/e2e/distributedtracing/distributedtracing_test.go
test/e2e/h2c/h2c_test.go
test/e2e/testing.go

Bind test server to localhost interface

---

topdown/eval.go
topdown/eval_test.go

topdown: Fixing issue where key override rule is allowed to modify object value of partial object rule

---

docs/website/layouts/support/section.html.html

[docs] Use links on support page

---

rego/rego_test.go
rego/rego_wasmtarget_test.go

to not fail when running `make test`.

Moving wasm test

---

.github/dependabot.yml

To avoid 5 PRs for each version bump.

deps: group otel deps

---

docs/website/content/integrations/dependency-management-data.md
docs/website/content/organizations/jamie-tanna.md

Adds dependency-management-data as an Ecosystem project, as I've just added support for OPA, and I'd love to shout out about it more 🚀

Add dependency-management-data to the Ecosystem

---

rego/rego.go
rego/rego_test.go

This allows processes, such as doc generation, to have additional information about custom builtin functions.
It is now possible to set a description on custom builtin functions.
See https://github.com/open-policy-agent/opa/issues/6449 for additional context.

Propagate description of custom builtins

---

docs/website/assets/sass/docs.sass
docs/website/layouts/ecosystem/section.html.html
docs/website/layouts/ecosystem/single.html.html
docs/website/layouts/integrations/single.html.html
docs/website/layouts/partials/ecosystem-cta.html

We're trying to encourage users to list their projects, this will hopefully be a good prompt.
https://github.com/open-policy-agent/opa/assets/1774239/b86bfbb4-52eb-4617-befb-f5d4ef744f87

docs: Add CTA for ecosystem submissions

---

.github/workflows/post-merge.yaml

This PR attempts to fix the failures seen in the post-merge workflow by updating the token used in the checkout action.

.github/workflows: Update checkout action token

---

docs/content/configuration.md

Updating documentation to describe two new parameters introduced in commit: f063c90

Add documentation for new cache config parameters

---

docs/website/content/integrations/rond.md

We migrated our blog and the URLs of the blog post changed.
I updated the links of the blog posts with the new ones, adding also another resource.

Updated Rond links

---

docs/content/docker-authorization.md

Updated docs to reflect the updated plugin version in order to run the examples

Update docker-authorization.md to use new plugin version

---

docs/website/layouts/integrations/single.html.html

Issue identified in https://github.com/open-policy-agent/opa/pull/6543

docs: Correctly size integration logos

---

docs/website/layouts/index.html
docs/website/static/css/styles.css

Fixes https://github.com/open-policy-agent/opa/issues/6557

docs: add Linux Foundation trademarks note

---

ADOPTERS.md

Added Mia-Platform to the OPA adopters list
Mia-Platform has built all of its application security on-top of OPA and it is helping us a lot ❤️ 
Changed the adopters file to include Mia-Platform with a brief description

update: ADOPTERS.md

---

docs/content/debugging.md

docs: fix typo

---

ADOPTERS.md

ADOPTERS.md: Add Facets.cloud to the list

---

CHANGELOG.md
ast/policy.go
docs/website/scripts/live-blocks/README.md
internal/gqlparser/validator/rules/overlapping_fields_can_be_merged.go
server/writer/writer.go
test/e2e/oci/oci_test.go
util/hashmap.go

Remove repetitive words

---

server/server.go

The cost of this can become non-trivial with larger inputs.

server: Remove an unnecessary AST-to-JSON conversion for the eval input.

---

docs/content/configuration.md

docs/configuration: Tidy up headers in Services section

---

docs/content/policy-language.md

Rather simple, but I'm not sure we need more.
Fixes #6727

docs: Add arrays to composite values section

---

docs/website/content/integrations/nodejs-express.md
docs/website/content/softwares/java.md

https://github.com/open-policy-agent/opa/pull/6811
In the above PR, some pages were moved or renamed. This adds some aliases to those pages so that redirects are handled by Hugo correctly.

[docs] Add page aliases for moved or renamed pages.

---

.github/workflows/scorecards.yml

Fixes #6839 
PR to add the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action).

Added the scorecard github action

---

CHANGELOG.md

CHANGELOG.md: add 'opa exec' format

---

.github/PULL_REQUEST_TEMPLATE.md
ast/builtins.go
builtin_metadata.json

1. Been awhile since I did a PR on this repo so did not remember how the commits needed to be signed. The PR template was not clear how to get to the needed details, so adding them here.
2. Found assorted typos.
As above.

typos and clarification on signing commits

---

.github/workflows/codeql-analysis.yml

Ref: https://github.com/github/codeql-action?tab=readme-ov-file#permissions

.github/workflows: Update GHA token perms for CodeQL workflow

---

docs/content/contributing.md

I have removed the references to the regular meetings, but also made a number of other updates to this page to make it clear where we need help and how to get started.

docs: Update contrib docs

---

docs/content/envoy-tutorial-istio.md

This docs-only PR fixes a typo that incorrectly describes using the Istio `EnvoyFilter` resource, which has now been superseded in OPA docs by the `AuthorizationPolicy` resource.
Update language and link in conclusion of the Istio tutorial.

Fix misnomer in Istio docs

---

util/json.go
util/json_test.go

Strip BOM from input JSON when found

---

ir/encoding/encoding_test.go
loader/internal/embedtest/bar/bar.rego
loader/loader_test.go
profiler/profiler_test.go
refactor/refactor_test.go

Updating tests in packages:
* ir
* loader
* profiler
* refactor

rego-v1: Future-proofing various smaller pkg tests to be 1.0 compatible

---

topdown/lineage/lineage_test.go

rego-v1: Future-proofing `lineage` pkg tests to be 1.0 compatible

---

docs/content/envoy-tutorial-istio.md

"required_roles" was a misnomer, and some other things got a minor face lift while at it. For fun, also testing the underscore prefix convention for the first time in the OPA docs.

docs: Simplify the the Istio example policy

---

ADOPTERS.md

Add Marsh McLennan to ADOPTERS.md

---

ADOPTERS.md

As requested via Slack. Thanks, APIwiz!

Add APIwiz to adopters

---

README.md

Follows https://github.com/open-policy-agent/opa/pull/7066

docs: Another minor update to README.md

---

.github/workflows/nightly.yaml

Maybe this helps with the nightly trivy failures.

nightly: try other trivy fix, use ECR

---

docs/website/content/integrations/regocpp.md

The documentation on the rego-cpp integration is out of date.
I updated the compatibility information on the rego-cpp integration. Please see [rego-cpp](https://github.com/microsoft/rego-cpp) for more information if needed.

Updating compatibility information on the regocpp integration

---

MAINTAINERS.md

Updating myself to emeritus status

Update Andrew Peabody to emeritus

---

ast/builtins.go
ast/builtins_test.go
builtin_metadata.json

Add description to all built-in function args and return values

---

ADOPTERS.md

Adding VFZ as adopters!
Added VFZ to the adopters file.
N/A
Thanks! 👋

Add VodafoneZiggo as Adopters

---

MAINTAINERS.md

Adding myself as Gatekeeper maintainer.

adding gatekeeper maintainer

---

docs/website/layouts/index.redirects

This is just for the latest version.
Fixes https://github.com/open-policy-agent/opa/issues/7256

docs: Redirect opa-1 to v0-upgrade

---

docs/content/_index.md

This PR introduces minor improvements for consistent formatting and clearer wording.
- Capitalized the first letter of an info block
- Replaced double quotes with backticks in a variable reference
- Added `to` to the sentence for clarity
N/A
N/A

docs: formatting and wording fixes

---

v1/test/cases/testdata/v1/numbersrange/test-numbersrange-issue-7269.yaml
v1/topdown/numbers.go

Fix out of range error in numbers.range

---

docs/content/ir.md

Updated links mentioned in #7320

Fixed invalid links to examples (docs:ir)

---

CHANGELOG.md

Dropping redundant dep. update note in CHANGELOG

---

v1/plugins/rest/auth.go
v1/plugins/rest/auth_test.go

This change should fix https://github.com/open-policy-agent/opa/issues/7092, https://github.com/open-policy-agent/opa/issues/7189 and https://github.com/open-policy-agent/opa/issues/6590
I've tested this with AWS, but I would appreciate if someone can please test this with ACR

Fix bearer plugin OCI cloud registries issues

---

.golangci.yaml
cmd/parse.go
v1/storage/inmem/inmem.go

Seeing @thevilledev adding this in conftest, and thinking we had it here already. We didn't! Fixing the two issues it reported where we checked for conditions that couldn't possibly be met.

Add nilness linter from govet

---

v1/ast/annotations.go

From my long list of not-yet-submitted perf PRs. I figured I need to split up that work for it to be manageable.. so this is a small one!
No need to allocate memory every time we print a known attribute from annotations. Also some minor cleaning up.

perf: intern annotation terms

---

internal/prometheus/prometheus_test.go
v1/plugins/rest/aws_test.go
v1/topdown/crypto_test.go
v1/topdown/tokens_test.go

CI build will have to determine whether they also work in Go 1.23 :)

Fix test failures with Go 1.24

---

docs/content/terraform.md

This reverts commit d506db305c8bd26d9357ddf7fb7d0c423ad677a4.
This was committed to main in error and should be merged via PR instead.

Revert "docs: Update terraform examples"

---

docs/content/terraform.md

Related to https://github.com/open-policy-agent/opa/issues/7388
x-ref https://github.com/open-policy-agent/opa/pull/7428, https://github.com/open-policy-agent/opa/commit/d506db305c8bd26d9357ddf7fb7d0c423ad677a4

docs: Update terraform docs output examples to be clearer

---

docs/content/contrib-code.md
docs/content/contributing.md

Namely, as it relates to the DCO and licensing requirements.

docs: Add some notes about AI assisted OPA patches

---

docs/content/envoy-tutorial-standalone-envoy.md

Fix typo in envoy-tutorial-standalone-envoy.md

---

.github/dependabot.yml

deps: Grouping deps in dependabot

---

docs/content/contributing.md
docs/content/v0-upgrade.md
docs/website/content/community/_index.md
docs/website/layouts/partials/nav.html

This redirect has been reconfigured.

docs: Revert slack link change

---

ADOPTERS.md

Cloudsmith's implementation of OPA allows Cloudsmith users to manage and trace policies at scale for better compliance.

Cloudsmith adds support for OPA

---

docs/content/v0-upgrade.md

(Issue #7452)
Upon clicking the Link , it is broken and I see - "Sorry, looks like this page was lost at sea!
Perhaps you could use one of the following:"
Markdown file was changed
To reproduce the problem
Go to https://www.openpolicyagent.org/docs/latest/v0-upgrade/#upgrading-rego
Scroll down to the section which has text If you need to use v0 functionality, you can still use v1 packages. Please see the [Backwards Compatibility](https://www.openpolicyagent.org/docs/latest/v0-upgrade/v0-compatibility/) documentation for more details.
Click on the "Backwards Compatibility" link.
Link is broken and I see - "Sorry, looks like this page was lost at sea!
Perhaps you could use one of the following:"
Since this is docs related, no tests are required as this is not source code.

fix: fixed broken docs link

---

docs/content/rest-api.md

Improve REST APIs documentation by adding some missing headers.
Adding/Updating `Request Headers` section for some REST APIs
Resolves #7456

docs: improve request headers documentation in REST APIs

---

docs/new/docs/index.md
docs/new/src/pages/assets/README.md
docs/new/src/theme/MDXComponents.js

This updates the docs index examples to be live again using the new `RunSnippet` component.

docs: Update docs index examples to be live again

---

docs/new/docs/aws-cloudformation-hooks.md
docs/new/docs/comparison-to-other-systems.md
docs/new/docs/deployments.md
docs/new/docs/docker-authorization.md
docs/new/docs/envoy/index.md
docs/new/docs/envoy/performance.md
docs/new/docs/envoy/primer.md
docs/new/docs/envoy/tutorial-gloo-edge.md
docs/new/docs/envoy/tutorial-istio.md
docs/new/docs/extensions.md
docs/new/docs/faq.md
docs/new/docs/graphql-api-authorization.md
docs/new/docs/http-api-authorization.md
docs/new/docs/integration.md
docs/new/docs/kafka-authorization.md
docs/new/docs/kubernetes/debugging.md
docs/new/docs/kubernetes/index.md
docs/new/docs/kubernetes/primer.md
docs/new/docs/management-decision-logs.md
docs/new/docs/oauth-oidc.md
docs/new/docs/policy-performance.md
docs/new/docs/policy-testing.md
docs/new/docs/rest-api.md
docs/new/docs/security.md
docs/new/docs/ssh-and-sudo-authorization.md
docs/new/docs/wasm.md
docs/new/src/lib/sidebars.js

Following #7572, this completes the work started in #7581 and https://github.com/open-policy-agent/opa/pull/7577.

docs: Replace final live examples

---

docs/README.md
docs/docs/contrib-docs.md

Some of these details have changed with the arrival of the new site.

docs: Update contrib-docs page

---

docs/docs/contrib-docs.md

There was an error in the entr command, have added some other adjustments too.

docs: Update contributing docs

---

docs/src/components/FeedbackForm/index.js
docs/src/components/FeedbackForm/styles.module.css
docs/src/theme/DocItem/Content/index.js

This will only show when the user has been on the page for 10s and has scrolled.
Why? because we have some really long pages and I fear that users might not complete the form if they don't make it to the bottom of the page.
Clearly this is not a perfect solution, but I hope it'll get some users to input feedback and help us target our efforts to improve the docs.
https://github.com/user-attachments/assets/adff0c9a-f1d3-4234-914b-9f5ada3568f4
https://github.com/user-attachments/assets/14bfc244-a99e-4f8f-9913-26ba7638073c

docs: Show a feedback popup on the docs site

---

cmd/parse.go

cmd/parse: expose --v0-compatible flag

---

docs/docs/index.md

This is following some additional feedback from the reporter of https://github.com/open-policy-agent/opa/pull/7677
Ultimately, I'd like to rework this page more significantly, but I hope this might help avoid some confusion for now.

docs: Add another OR note in AND section

---

v1/ast/oracle/oracle.go
v1/ast/oracle/oracle_test.go

Fixes an issue files in Regal: https://github.com/StyraInc/regal/issues/1591
Before
https://github.com/user-attachments/assets/79097eca-a9c0-4870-a4ca-37cc03ae9a81
After
https://github.com/user-attachments/assets/b8713f7b-51f1-4f98-b16e-2720423067f9

oracle: Support object refs in FindDefinition

---

docs/docs/deployments.md

We had this feedback from on the website form:

docs: Update rego in deployment examples

---

docs/src/components/BuiltinSearch/index.js

As the search function added to the builtins section is case sensitive
Changes the BuiltinSearch component to normalise letter case
Can be found under built-ins in policy ref in the docs

docs: Fix bug where the search match respects case

---

v1/ast/parser.go
v1/ast/parser_test.go

Fixes https://github.com/open-policy-agent/opa/issues/7725

ast: Ensure surplus leading zeros always error

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

These are what we ought to eventually be using rather than the bug and feature request labels.

.github: Use types for issues

---

cmd/version.go
cmd/version_test.go
internal/report/report.go
internal/report/report_test.go
v1/plugins/plugins.go
v1/plugins/plugins_test.go
v1/runtime/runtime.go
v1/runtime/runtime_test.go
v1/version/version.go

report: Fetching latest OPA release version from GH

---

cmd/build.go
cmd/build_test.go

-b must be set for the user defined manifest to be used.
Related to https://github.com/open-policy-agent/opa/issues/7806

build: Show a warning when .manifest is ignored

---

docs/src/pages/index.js
docs/src/pages/index.module.css

Updating the frontpage to remove Styra logo.

docs: update frontpage

---

netlify.toml

We can switch this back after the next release. cc @johanfylling @charlieegan3

Update website to build from tip of main

---

docs/docs/policy-language.md

Inconsisten examples in [Policy Language documentation](https://www.openpolicyagent.org/docs/policy-language#variable-keys). Based on dicsussion in #7855.
- Creates a set also in the Python example to be consistent with the rego code above.
- Deletes an extra space
None.
None.

 docs(policy-language.md): Use set in the Python code example for consistence

---

internal/report/report.go

Previously, we've allowed overriding the GitHub API endpoint. Now, we can also allow overriding the GitHub Repo slug used in the API call.
A concrete use is EOPA checking for new EOPA versions, as opposed to comparing its version against OPA's version.

internal/report: allow overriding GitHub repo

---

docs/docs/ocp/authentication.md

Bring in https://github.com/open-policy-agent/opa-control-plane/commit/adc834f408767fc47a5cd5ab78babedf7271d4e9

docs: Update OCP api-key

---

.github/PULL_REQUEST_TEMPLATE.md
docs/docs/contrib-code.md
docs/docs/contrib-docs.md

Some ideas from the team, some from myself and the rest from these resources here:
* https://github.com/open-telemetry/community/blob/main/policies/genai.md
* https://www.linuxfoundation.org/legal/generative-ai

docs: Add some more detail to the AI guidelines

---

docs/docs/ocp/api-reference.md

1. missing DELETE handlers
2. secrets API

docs: OCP HTTP API updates
