open-policy-agent/opa

docs/dev/RELEASE.md
docs/dev/SITE.md

/cc @timothyhinrichs here are the steps to build the website

Add doc with steps to build and publish the site

---

topdown/topdown.go
topdown/topdown_test.go

A few small changes to topdown eval to support previously un-handled cases.

Add support for vdoc references without suffix

---

ast/compile.go
ast/compile_test.go
ast/parser_test.go
ast/rego.peg
ast/term.go
ast/term_test.go
repl/repl.go
repl/repl_test.go
runtime/runtime.go
runtime/server.go
runtime/server_test.go
topdown/builtins.go
topdown/ineq.go
topdown/topdown.go
topdown/topdown_test.go

These changes were queued up while I was working on the experimental scheduler. I think they're fairly straightforward.

Misc. fixes and improvements

---

CHANGELOG.md
CONTRIBUTING.md
docs/_config.yml
docs/about.md
docs/dev/SITE.md
docs/docs/arch.md
docs/docs/examples/hello-world.md
docs/index.html
runtime/server.go
runtime/server_test.go
storage/datastore_test.go
version/version.go

/cc @timothyhinrichs 
Bunding a few changes together.
- Fixed issue in Data API patch handling
- Added "Hello World" example that users can try
- Reverting the version (we know the release process works now!)

A few improvements to prepare for the initial release

---

runtime/server.go
runtime/server_test.go
topdown/topdown.go
topdown/topdown_test.go

These are two small changes that improve the REST API. The commit messages describe them in more detail.

Support global vars in REST API and translate topdown.Undefined

---

topdown/topdown.go
topdown/topdown_test.go

Example of what works now:
```
torin:~$ cat test.rego
package ex
p = "hello" :- false
p = "goodbye" :- true
torin:~$ curl http://localhost:8181/v1/policies/test --data-binary @test.rego -X PUT
{
"ID": "test",
"Module": {...}
}
torin:~$ curl http://localhost:8181/v1/data/ex/p
"goodbye"
```
Previously, we would have received HTTP 500 with an error message.
If there is a conflict, the (e.g., both p's evaluate successfully), HTTP 500 w/ an error message is returned:
```
torin:~$curl http://localhost:8181/v1/data/ex/p
{
"Code": 500,
"Message": "evaluation error (code: 2): multiple values for [ex p]: rules must produce exactly one value for complete documents: check rule definition(s): p"
}
```

Add query support for multiple complete docs

---

ast/term.go
ast/term_test.go
runtime/server.go
runtime/server_test.go
topdown/topdown_test.go

Improve global variable support in REST API

---

ast/builtins.go
docs/docs/lang.md
topdown/aggregates.go
topdown/builtins.go
topdown/topdown_test.go

I've also added a small section to the docs about the supported built-ins. At some point, the built-in references should probably get generated from code/schema but until then having a short description is good enough.

New built-in: max

---

ROADMAP.md

A few items from Future were already done and planning for next release is to
be determined.

Roadmap cleanup

---

.gitignore
ast/parser.go

This is required to use "go get github.com/open-policy-agent/opa".

Add generated parser code

---

README.md
ast/compile.go
ast/doc.go
ast/example_test.go
cmd/doc.go
repl/example_test.go
repl/repl.go
runtime/doc.go
storage/doc.go
storage/example_test.go
topdown/doc.go
topdown/example_test.go
util/doc.go
version/version.go

This PR adds a few GoDoc improvements. Namely, it adds package-level descriptions with overviews in ast and topdown as well as examples on how to use the ast, topdown, storage, and repl packages.

GoDoc improvements

---

site/_scripts/rest-examples/gen-examples.sh
site/documentation/references/rest/index.md

Also, fix grammar and tweak wording in a few places.

Add GET /policies/<id>/raw to specification

---

Makefile
runtime/runtime.go
runtime/runtime_test.go
runtime/server_test.go
server/doc.go
server/server.go
server/server_test.go

These changes refactor the server to live in another package. This will enable other packages to depend on the server and embed it into their applications.

Refactor server into separate package

---

ast/compile.go
ast/compile_test.go

Also, use the visitor function to ensure that nested expressions are checked
(e.g., closures were not being checked before).

Update built-in check to catch unknown functions

---

ast/compile.go
ast/compile_test.go
ast/errors.go
ast/errors_test.go
ast/example_test.go
repl/repl.go
runtime/runtime.go
server/server.go
server/server_test.go
storage/policystore.go
storage/policystore_test.go
test/scheduler/scheduler_bench_test.go
test/scheduler/scheduler_test.go
topdown/topdown_test.go

See commit message for details. This is a small functional change, mostly refactoring.

Fix compiler error reporting

---

.travis.yml
Makefile
README.md
build/check-lint.sh
build/install-deps.sh
docs/DEVELOPMENT.md

Small improvement to on-boarding experience for new developers. README links off to DEVELOPMENT.md and "make" should just do the right thing now, i.e., it will automatically install pigeon if not already present.

Improve experience for on-boarding new developers

---

ast/compile.go
ast/compile_test.go
ast/parser_ext.go
repl/repl.go
repl/repl_test.go
server/server.go
server/server_test.go
site/_scripts/rest-examples/gen-examples.sh
site/documentation/references/rest/index.md
topdown/eq.go
topdown/explain/explain.go
topdown/explain/explain_test.go
topdown/topdown.go
topdown/topdown_test.go
topdown/trace.go
topdown/trace_test.go

These changes include a bit of refactoring. The main changes are found in 	76acefa.

Add initial support for explanations

---

ast/parser.go
ast/parser_test.go
ast/rego.peg

This deals with the same issue addressed in #118.

Fix parse error handling between statements

---

misc/syntax/vim/README.md
misc/syntax/vim/ftdetect/rego.vim
misc/syntax/vim/syntax/rego.vim

Add Vim plugin for Rego

---

ast/builtins.go
docs/adding-builtins.md
topdown/casts.go

@timothyhinrichs have a look at this and see if it's enough to help you write your built-in functions.

Add docs for detailing steps to add built-ins

---

.travis.yml
Makefile
build/utils.sh

*fingers crossed* here's hoping this works!

Add automatic Docker image build and push

---

repl/repl.go
repl/repl_test.go

Fix output for references iterating sets

---

repl/repl_test.go
topdown/topdown.go
topdown/topdown_test.go

Remove conflict error for same key/value pairs

---

ast/compile.go
ast/compile_test.go
topdown/explain/explain.go

Check rule types for conflicts

---

ast/compile.go
ast/compile_test.go
ast/term.go

Check package declarations for conflicts

---

ast/compile.go
ast/compile_test.go

These changes update the compiler to include a hook that can be used to load
additional modules at compile time. This is useful if the caller needs to
dynamically include modules based on resolved references in an existing set of
modules.

Add lazy loading of modules during compilation

---

ast/term.go
ast/term_test.go
repl/repl.go
runtime/runtime.go
runtime/runtime_test.go
server/server.go
server/server_test.go
storage/datastore.go
storage/datastore_test.go
storage/errors.go
storage/example_test.go
storage/index.go
storage/interface.go
storage/path.go
storage/path_test.go
storage/storage.go
storage/storage_test.go
storage/trigger.go
test/scheduler/scheduler_bench_test.go
topdown/eq.go
topdown/topdown.go
topdown/topdown_test.go

Commentary given in the "Updates to use new storage.Path type" commit message.

Refactor storage paths to simplify storage interfaces

---

site/examples/docker-authorization/index.md

The authorization plugin has been renamed and the plugin's command line
arguments were changed to require the policy file explicitly.

Update Docker Authorization example

---

ast/parser_ext.go
ast/parser_test.go
repl/repl.go
repl/repl_test.go
runtime/loader_test.go
runtime/runtime.go
runtime/runtime_test.go

Closing a few open, low-hanging fruit tickets.

Misc. bug fixes and improvements

---

ast/compile.go
ast/compile_test.go

Small fix for bug caught after "request' changes went in.

Fix bug in reference resolver

---

site/documentation/references/rest/index.md

Add cURL note to REST API docs

---

ast/compare_test.go
ast/compile_test.go
ast/example_test.go
ast/parser_ext.go
ast/parser_test.go
ast/policy.go
ast/policy_test.go
ast/transform_test.go
ast/visit_test.go
repl/repl.go
repl/repl_test.go
runtime/logging.go
runtime/logging_test.go
server/server.go
server/server_test.go
site/_scripts/rest-examples/example3.rego
site/_scripts/rest-examples/example4.rego
site/_scripts/rest-examples/gen-examples.sh
site/documentation/how-do-i-write-policies/index.md
site/documentation/how-does-opa-work/index.md
site/documentation/references/rest/index.md
test/scheduler/scheduler_bench_test.go
test/scheduler/scheduler_test.go
topdown/example_test.go
topdown/input.go
topdown/input_test.go
topdown/topdown.go
topdown/topdown_test.go

Naming is hard. The "request" document is now the "input" document.

Rename the request document

---

ast/errors.go
ast/policy.go
ast/policy_test.go
ast/strings.go
ast/term.go
server/server.go
server/server_test.go
server/types.go
site/_scripts/rest-examples/gen-examples.sh
site/documentation/references/rest/index.md

Also, move server types into file separate from server.
Fixes #222

Refactor to use snake_case in API models

---

ast/compare.go
ast/compile.go
ast/compile_test.go
ast/parser.go
ast/parser_ext.go
ast/parser_test.go
ast/policy.go
ast/policy_test.go
ast/rego.peg
ast/transform.go
ast/visit.go
ast/visit_test.go
misc/syntax/atom/language-rego/grammars/rego.cson
misc/syntax/textmate/Rego.tmLanguage
misc/syntax/vim/syntax/rego.vim
misc/syntax/visualstudio/rego/syntaxes/Rego.tmLanguage
repl/repl.go
server/server_test.go
site/documentation/how-do-i-write-policies/index.md
site/documentation/references/language/index.md
test/authz/authz_bench_test.go
test/authz/authz_test.go
test/scheduler/scheduler_test.go
topdown/errors.go
topdown/explain/explain.go
topdown/topdown.go
topdown/topdown_test.go
util/json.go

This PR contains a few changes:
1. Support for the "default" keyword (Fixes #196)
2. Fix for #238 
3. Basic REST API auth/z use case benchmark

Default keyword, evaluation bug fix, new benchmark

---

rego/example_test.go
rego/rego.go

Fix rego eval of negated single-term expressions

---

server/authorizer/authorizer_test.go
topdown/arithmetic.go
topdown/builtins.go
topdown/regex.go
topdown/topdown_test.go

Fix stray built-in error messages

---

site/_includes/nav-main.html

/cc @mikol I think this is all we need but it would be good if you could double check. Thanks!

Add top-level navigation link to the blog

---

site/_assets/stylesheets/style.scss
site/_includes/nav-documentation.html
site/documentation/references/deployments/index.md

Added a new document that describes how to deploy OPA using Docker, Kubernetes, etc.

Add deployment documentation

---

ast/compile.go
ast/compile_test.go
ast/policy.go
ast/unify.go
rego/rego.go
rego/rego_test.go
topdown/topdown.go
topdown/topdown_test.go

These changes close the open issues.

Fixes for open issues

---

runtime/loader.go
runtime/loader_test.go
runtime/merge.go
runtime/merge_test.go

The file loader now handles empty modules properly (previously, it would
include an empty/nil module in the results which resulted in a panic
later on).
Also, the file loader now accumulates errors instead of bailing on the
first one. This makes it easier to find and fix errors when loading
files into OPA.

Improve file loader error handling

---

site/documentation/how-do-i-write-policies/index.md
site/documentation/references/language/index.md

Add docs for JSON built-ins

---

server/server.go
server/server_test.go
server/types/types.go
site/_includes/nav-documentation.html
site/documentation/references/rest-v0/index.md
site/documentation/references/rest-v1/index.md
site/documentation/references/security/index.md

Add new /v0 API for webhook integrations.

---

runtime/logging.go
site/documentation/references/deployments/index.md

Improve OPA logging

---

ast/builtins.go
ast/builtins_test.go
ast/check.go
ast/check_test.go
ast/compile.go
ast/parser.go
ast/parser_test.go
ast/policy.go
ast/policy_test.go
ast/rego.peg
ast/unify.go
ast/visit.go
ast/visit_test.go
repl/repl.go
site/documentation/how-do-i-write-policies/index.md
site/documentation/references/language/index.md
topdown/builtins.go
topdown/example_test.go
topdown/topdown.go
topdown/topdown_test.go

See first commit for the details. The second commit is just refactoring.

Add support for built-in function namespacing

---

topdown/topdown.go
topdown/topdown_test.go

If evaluation failed on a negated expression using the with modified,
the caches were not invalidated. This meant the search would fail if
backtracking caused the expression to be re-evaluated.

Fix bug in with modifier evaluation

---

Makefile
build/build-release.sh

See commit for specifics. Makes it easier to build releases locally.

Refactor release build script

---

cmd/check.go
runtime/loader.go
runtime/runtime.go

Add check command to verify that modules parse and compile

---

ast/parser.go
ast/rego.peg

Also removes a redundant location set on the body of default rules.

Properly set location on default rules

---

ast/check.go
ast/check_test.go
ast/compare.go
ast/compile.go
ast/compile_test.go
ast/env.go
ast/parser.go
ast/parser_ext.go
ast/parser_test.go
ast/policy.go
ast/policy_test.go
ast/rego.peg
ast/strings.go
ast/transform.go
ast/transform_test.go
ast/visit.go
ast/visit_test.go
format/format.go
format/testfiles/test.rego
format/testfiles/test.rego.formatted
repl/repl.go
repl/repl_test.go
site/documentation/how-do-i-write-policies/index.md
site/documentation/references/language/index.md
topdown/builtins.go
topdown/topdown.go
topdown/topdown_test.go

Implement User Functions

---

docs/book/styles/website.css

Fix mobile view navigation bug

---

Makefile

Add format package to makefile

---

ast/check.go
ast/compare.go
ast/compare_test.go
ast/compile.go
ast/compile_test.go
ast/env.go
ast/index.go
ast/parser.go
ast/parser_test.go
ast/policy_test.go
ast/rego.peg
ast/term.go
ast/term_test.go
ast/transform.go
ast/unify.go
ast/visit.go
ast/visit_test.go
docs/book/SUMMARY.md
docs/book/how-do-i-write-policies.md
docs/book/language-reference.md
format/format.go
format/testfiles/test.rego
format/testfiles/test.rego.formatted
topdown/topdown.go
topdown/topdown_test.go

Implement Set and Object comprehensions, as well as a fixes for a few discovered bugs.

Set/Object Comprehensions

---

format/format.go

Add godoc package description for format

---

CONTRIBUTING.md

Also update a reference to the mailing list to refer to the slack
instead.

Update CONTRIBUTING.md with Pull Request squashing conventions

---

ast/compile.go
ast/compile_test.go
cmd/check.go
cmd/run.go
repl/example_test.go
repl/repl.go
repl/repl_test.go
runtime/runtime.go
runtime/runtime_test.go
server/server.go

Configurable compiler error reporting

---

ast/parser_ext.go
watch/watch_test.go

Watch test

---

cmd/run.go
docs/book/rest-api.md
runtime/runtime.go
server/buffer.go
server/buffer_test.go
server/server.go
server/server_test.go
server/types/types.go

Implement a diagnostic buffer in the server.

Diagnostics

---

ast/parser.go

The previous parser changes were committed without reinstalling pigeon.

Regenerate parser

---

ast/builtins.go
ast/check.go
ast/check_test.go
ast/env.go
types/types.go
types/types_test.go

See last commit for important bits. The first two commits were done to make the important part clearer.

Improve dynamic object property support

---

types/types.go
types/types_test.go

Without custom marshalling, type hints are lost.
Fixes #391

Add custom JSON marshelling for type system

---

loader/loader.go

Previously, the loader would read the input file for each guess. For
non-file inputs (e.g., process substitution) this would fail. Now you
can pipe command output into OPA over the command line!
$ opa run <(echo '{"foo":"bar"}') -e 'data.foo'
"bar"

Refactor loader to read inputs once

---

ast/compile.go
ast/compile_test.go
ast/term.go
ast/transform.go

Substitute comprehension terms requring eval

---

cmd/run.go
docs/book/rest-api.md
runtime/runtime.go
server/buffer.go
server/server.go
server/server_test.go
server/types/types.go

Misc. observability changes

---

loader/loader.go
loader/loader_test.go
runtime/runtime.go
runtime/runtime_test.go
storage/storage.go

Fix file watch bug causing panic in server mode

---

docs/book/language-reference.md

The pipe character was breaking the table presentation.

Fix docs example of set union

---

docs/book/SUMMARY.md

Fix function link in docs

---

topdown/topdown_test.go

Add test cases for product built-in

---

ast/check.go
ast/check_test.go

Fix match error panic

---

topdown/eval.go
topdown/topdown_test.go

If object keys (or set elements) are vars, then they must be plugged
before lookup is attempted, otherwise lookup will fail and expression
will be undefined. This could result in poor performance if rule outputs
are large enough. In that case, we could revisit how the rule outputs
are constructed (e.g., we could construct outputs with the first level
of set/object plugged and propagate binding lists for each key/value
pair.)
Also, updated test runner to accept OPA_TRACE_TEST environment var to
selectively enable tracing output. This is useful for debugging
purposes.
Fixes #505

Fix eval of objects/sets containing vars

---

docs/book/how-does-opa-work.md

change the transactions list from a bullet list to a numbered list since the list is referred as numbers in the text below

minor edits

---

repl/repl.go
repl/repl_test.go

The REPL output was broken by the recent rewriting changes. In some
cases, generated vars were being displayed and in other cases ref values
were not being displayed, only true/false was being printed based on
whether the ref was defined or not.
These changes refactor the REPL to evaluate queries and output their
results with less duplication.

Fix REPL printing of generated vars

---

docs/book/how-do-i-write-policies.md

Fix an example that was not parsing, and some hyperlinks

Fix opa docs

---

docs/book/http-api-authorization.md

- Fixes to python integration code example snippet
- Provided more comments behind code choices

Fix to Python example code in Docs

---

.gitignore
docs/book/get-started.md

And small change to .gitignore to work properly with JetBrain's GoLand IDE

Fixes #532

---

design/REGO_V2_PROPOSAL.md

Updates include:
- Revisions to the `@rule` and `@trigger` execution behavior
- Introduction of `@test` with an example of `with-as` operator
- Inclusion of `for-all` and `for-any` reducing operations
The proposal does not yet document the `with-as` operator in the
grammar, but does provide a note indicating that this is still under
review. The intent is to be able to bind partial state to the execution
or a function for the purposes of testing and adhoc queries.
The introduction of `for-all` and `for-any` is to ensure that these
reducing functions within the context of list/map iteration behave
as though they were a series of hand-written `&&` statements in
the `all` case or `||` in the `any` case. All other forms of iterators
and reducing functions have non-boolean accumulators and so …

Rego v2 proposal updates

---

ast/builtins.go
ast/term.go
docs/book/how-do-i-write-policies.md
topdown/aggregates.go
topdown/topdown_test.go

Fixing documentation on "else" keyword

---

ast/builtins.go
ast/term.go
topdown/aggregates.go
topdown/topdown_test.go

- Fix built-in type declaration
- Make built-in implementation copy slice to avoid accidental mutation

Tweak sort built-in

---

server/server.go
server/server_test.go
server/writer/writer.go

Catch all REST handlers for forbidden methods

---

ast/compile.go

Extra dependencies were being added to the rule graph for else clauses
which affected the order that the recursion check ran in. As a result
the error messages were not deterministic.

Fix flaky recursion check

---

ast/builtins.go
docs/book/how-do-i-write-policies.md
docs/book/how-does-opa-work.md
docs/book/language-reference.md
docs/book/ssh-and-sudo-authorization.md
topdown/topdown_test.go
topdown/type.go
topdown/type_name.go

Added builtin commands to check the type of the given input and also to validate the type of input.

Added new builtin commands for validating input types

---

repl/repl.go
topdown/bindings.go

See second commit for details.

Add early exit into binding list apply

---

ast/builtins.go
ast/term.go
topdown/builtins.go
topdown/builtins/builtins.go
topdown/eval.go
topdown/http.go
topdown/http_test.go
topdown/topdown_bench_test.go
topdown/topdown_test.go
topdown/walk.go

These changes allow built-in functions to exploit partially ground output values.

Improvements to the built-in function API

---

ast/builtins.go
ast/check_test.go
ast/compare.go
ast/compile.go
ast/compile_test.go
ast/example_test.go
ast/parser.go
ast/parser_ext.go
ast/parser_internal.go
ast/parser_test.go
ast/policy.go
ast/policy_test.go
ast/rego.peg
ast/strings.go
ast/term.go
ast/term_test.go
ast/transform.go
ast/visit.go
format/format.go
format/format_test.go
format/testfiles/test.rego
format/testfiles/test.rego.formatted
server/server_test.go
topdown/topdown_partial_test.go
topdown/trace_test.go
watch/watch_test.go

Add support for call terms

---

ast/compile.go
ast/compile_test.go

References must be resolved first because resolution may lazily load new
modules.

Resolve refs before rewriting assignments

---

docs/book/language-reference.md

Move re_match and regex.globs_match into a separate "Regex" section in the language reference.

Add docs for regex.globs_match.

---

docs/book/SUMMARY.md
docs/book/rosetta-stone.md

Finished RBAC, RBAC-SOD, ABAC, AWS.

docs: Add rosettastone docs

---

ast/builtins.go
docs/book/language-reference.md
topdown/time.go
topdown/topdown_test.go

Add time.clock built-in function

---

ast/builtins.go
ast/check_test.go
ast/compile.go
ast/env.go
rego/rego.go
rego/rego_test.go
repl/repl.go
repl/repl_test.go
tester/runner_test.go
topdown/builtins.go
topdown/comparison.go
topdown/eval.go
topdown/regex.go
topdown/strings.go
topdown/topdown_test.go
types/types.go
types/types_test.go

Improve call support

---

design/REGO_V2_PROPOSAL.md

Proposal update to introduce separate `rule` declaration
The update abandons the concept of `@rule` and `@trigger` in
favor of a `rule` declaration which conditionally produces a decision.
Additionally, the `rule` declaration supports overloading through
redeclaration. As redeclaration is not supported for variables and
functions, this was a key difference which warranted a separation
of concerns.
The notion of a conditional decision for a `rule` also plays nicely with
trigger use cases which had been previously identified, allowing the
proposal to reduce some of the language complexity and simplify
the getting started experience.

Updates to the Rego v2 proposal based on last design meeting.

---

rego/rego.go
rego/rego_test.go
repl/repl.go
repl/repl_test.go
server/server.go
server/server_test.go
server/types/types.go

Misc. small fixes

---

topdown/strings.go
topdown/topdown_test.go

Fix substring built-in bounds checking

---

ast/builtins.go
docs/book/language-reference.md
topdown/arithmetic.go
topdown/topdown_test.go

* Add eval test
* Add item to language reference
* Fix type declaration
/cc @llofberg

Update modulo support

---

ast/parser_ext.go
ast/term.go
ast/term_test.go

Two small fixes for issues encountered in `opa fmt`.

Fixes for opa fmt

---

ast/builtins.go
docs/book/language-reference.md
server/types/types.go
topdown/builtins.go
topdown/eval.go
topdown/trace.go
topdown/trace_test.go

Changes for issue: https://github.com/open-policy-agent/opa/issues/637 
Adding a Note in Trace to capture debugging information.

Trace builtin

---

ast/compile.go
ast/compile_test.go
ast/term.go

See second commit for details. Also included Compare function for locations. Useful for sorting by location!

Fix for #661

---

runtime/runtime_test.go

We were seeing intermittent failures on Travis CI for this test case.
The error being delivered was an empty file parse error. With these
changes, the test will wait for up to 1 second to observe the expected
type error.

Fix test case to wait for correct error

---

docs/book/ssh-and-sudo-authorization.md

Tutorial now uses display and pull policies to request authorization context.
Separate policies for sudo and SSH have been merged into one for simplicity.
Signed-off-by: Yash Tewari <yashtewari1996@gmail.com>

Update SSH PAM tutorial to include new features.

---

cmd/eval.go

Fill in eval subcommand help text

---

plugins/plugins.go
runtime/runtime.go
server/server.go
server/server_test.go

Adding the compiler to the plugin manager. This would be useful for plugins while evaluating policies.

Added compiler instance to the plugin manager

---

plugins/plugins.go
runtime/runtime.go
server/server.go

Remove unnecessary comments

---

ast/builtins.go
docs/book/language-reference.md
topdown/encoding.go
topdown/topdown_test.go

Add URL query encoding built-ins

---

docs/book/SUMMARY.md
docs/book/kafka-authorization.md

Add Kafka authorization tutorial

---

docs/devel/RELEASE.md

Update release process docs with signoff flag

---

README.md

Evict the original Netflix meetup talk as the newer introduction talk
is a better starting point for people.

Add latest OPA talks to the list

---

server/server_test.go
topdown/eval.go
topdown/trace.go
topdown/trace_test.go

Add trace event for rule index lookups

---

GOVERNANCE.md

This is copied from #689 with an extra point about maintainership expiring after one year with ability to self-renew (per @TristonianJones's suggestion.)

Define governance model for OPA

---

README.md

Update OPA meeting schedule

---

cmd/eval.go

Improvements to the eval subcommand

---

ast/index.go
ast/index_test.go
ast/term.go
topdown/eval.go
topdown/topdown_partial_test.go

Improve rule indexing to be used during partial evaluation

---

ast/term.go
ast/term_test.go
topdown/copypropagation/copypropagation.go
topdown/query.go
topdown/topdown_partial_test.go

See second commit message for detail.

Add basic copy propagation optimization

---

docs/book/rest-api.md
rego/example_test.go
rego/rego.go
server/server.go
server/server_test.go
server/types/types.go

These commits are fairly self-describing. The docs are a good starting point for the overview.

Add initial support for /v1/compile API

---

docs/book/SUMMARY.md

Fix docs summary.md to include Compile API

---

docs/book/docker-authorization.md

Update docker engine version in docker authz tutorial

---

ast/policy.go
ast/policy_test.go
docs/book/rest-api.md
server/server_test.go

See first commit message for details.

Fix representation of empty queries in Compile API

---

docs/book/faq.md

Fix broken link in FAQ (invalid markdown link)

Fix link in FAQ

---

ast/builtins.go
docs/book/language-reference.md
topdown/aggregates.go
topdown/aggregates_test.go
topdown/topdown_test.go

- Added tests
- Added docs
- No added interfaces/refactoring of AST package
Signed-off-by: Varun Mathur <varun.mathur@live.com>

Added any/all builtins

---

topdown/eval.go

In 6f9ed62 we fixed an issue in partial eval that was causing vars
embedded inside composites to not be added to the save set when they
should have been.
This change simply refactors that fix to use ast.Walk and rely on the
same logic in both saveUnify and saveCall.
Note, the plug call on the var terms has been removed as it's not needed
since we are already plugging terms (or applying) when checking if terms
are contained in the save set.

Refactor save set updating to use ast.Walk

---

ast/compile.go
ast/compile_test.go
rego/example_test.go
topdown/bindings.go
topdown/copypropagation/copypropagation.go
topdown/eval.go
topdown/topdown_partial_test.go

This PR contains a few small improvements to partial evaluation that I've made in the process of building out the SQL data filtering proof of concept.

Misc. small improvements to partial eval

---

ast/builtins.go
docs/book/language-reference.md
topdown/parse.go
topdown/parse_test.go

Add built-in function to parse Rego modules

---

cmd/eval.go
internal/presentation/presentation.go
metrics/metrics.go
repl/example_test.go
repl/repl.go
repl/repl_test.go

Fix strange REPL output issue and refactor presentation to remove duplicated logic

---

topdown/eval.go
topdown/topdown_partial_test.go

Previously the partial check for built-in and user-defined function
calls was performed in the same place. This prevented user-defined
functions from being partially evaluated if any of the inputs were
unknown.
With these changes, user-defined functions will get partially evaluated
even if inputs are unknown (just like partial set and partial object
rules.)
Fixes #774

Refactor partial check for calls

---

Makefile
topdown/topdown_bench_test.go

The commits are self-explanatory.

Fix partial eval benchmark test and CI around benchmarks

---

ADOPTERS.md

Update ADOPTERS.md with a couple other users

---

ast/builtins.go
topdown/array.go
topdown/array_test.go
topdown/builtins/builtins.go

Add array.concat built-in function

---

ast/builtins.go
docs/book/language-reference.md
topdown/regex.go
topdown/topdown_test.go

Add regex split builtin

---

docs/book/get-started.md

Signed-off-by: ken5scal <kengoscal@gmail.com>
#869  : original issue
#879  : Pull Request I have cherry picked into this pr

fixed typo

---

cmd/plugins.go
cmd/plugins_test.go
plugins/plugins.go
runtime/runtime.go
util/test/tempfs.go

Will add docs once approved.
Signed-off-by: Varun Mathur <varun.mathur@live.com>

Added ability to dynamically load .so objects

---

ADOPTERS.md

…c contact information to the extent its useful for those interested to have a conversation.
Signed-off-by: Lee Calcote <leecalcote@gmail.com>

Adding contact info for reference

---

cmd/deps.go
dependencies/deps.go
dependencies/deps_test.go
internal/presentation/presentation.go

Adding a simple CLI for analyzing policies for dependencies.

Add deps subcommand

---

docs/book/how-do-i-write-policies.md

Fix whitespace in REPL example of language guide

---

ast/check_test.go
ast/policy.go
ast/term.go
ast/visit.go
format/format.go
format/format_test.go
internal/presentation/presentation.go

See second commit for details.

Improve format package to tolerate nil Location values

---

docs/book/language-reference.md
topdown/http.go
topdown/http_test.go

Add option to enable http redirects.

---

bundle/bundle.go

This was tested manually.
Fixes #920

Update bundle reader to cap buffer size

---

docs/book/http-api-authorization.md
docs/book/kafka-authorization.md
docs/book/ssh-and-sudo-authorization.md
docs/book/tutorials/kubernetes-admission-control-validation/admission-controller.yaml

Link to security docs in tutorials

---

server/server.go
server/server_test.go

validate queries by checking unsafe builtins

---

repl/repl.go

The REPL was reporting module compile time as query compile time. This
lead to confusion when investigating performance in a particular use
case with several thousand rules.
Also, as part of these changes, refactor the REPL so that the compiler
is only loaded once in the query eval happy path. Previously the
compiler was being loaded three times! Once when generating the REPLs
special input document, once when compiling the query, and then once
more for the actual query evaluation.

Fix compile timing in the REPL

---

docs/book/how-does-opa-work.md

Signed-off-by: Johannes M. Scheuermann <joh.scheuer@gmail.com>
This fixes the issue described here: https://github.com/open-policy-agent/opa/issues/934

Correct example policy fixes #934

---

README.md

Update the calendar invite for OPA bi-weekly meeting

---

topdown/copypropagation/copypropagation.go
topdown/topdown_partial_test.go

The first commit does not change behaviour in any way.

Fixes and improvements in copy propagation 

---

repl/repl.go
repl/repl_test.go

Previously the REPL would just silently define rules. This is a bit
confusing for new users--because they come to assume that x = y should
define a rule but then become confused when x = y acts as a query.

Add message when rule defined in REPL

---

ast/builtins.go
docs/book/language-reference.md
topdown/builtins.go
topdown/regex.go
topdown/regex_template.go
topdown/regex_template_test.go
topdown/regex_test.go

Add `regex.template_match` built-in

---

ADOPTERS.md

Add Nefeli Networks to ADOPTERS.md

---

cmd/test.go
tester/reporter.go
tester/reporter_test.go
tester/runner.go

@srenatus can you take a look? Thanks!

Misc. changes in response to #975

---

tester/reporter_test.go

Fix unkeyed literal vet error from go1.11

---

docs/book/language-reference.md
topdown/http.go
topdown/http_test.go

Please review and provide comments

Httpsend #749

---

ast/term.go
ast/term_bench_test.go

Iterate over smaller set when intersecting

---

ast/builtins.go
docs/book/language-reference.md
topdown/regex.go
topdown/regex_test.go

Implement support for regex search, returning all the matching values
Fixes #747

Implement regex.find_n

---

ast/compile.go
ast/compile_test.go

Add the resolved target term in the error message
Fixes #343

Improve with modifier target error

---

CONTRIBUTING.md

Update CONTRIBUTING.md with mention of Fixes

---

rego/example_test.go

Add GoDoc sample for using rego.Tracer

---

docs/book/rest-api.md
server/server.go
server/server_test.go

Also, remove printlns from redirection test cases.

Add YAML input support to webhook APIs

---

server/server.go

This allows callers to embed the OPA HTTP server inside another HTTP
server (e.g., under a path prefix like /opa).

Add router option to the HTTP server

---

docs/book/how-do-i-write-policies.md

Update with keyword description to include data as a target

---

server/server.go
server/server_test.go
server/types/types.go

* add POST method for /query
Signed-off-by: Nikhil Bhatia <nbhatia@microsoft.com>

add POST method for /query

---

bundle/bundle.go

Previously, the bundle reader code would only load data.json files
prefixed with / characters. This meant that if the data file was
located under a subdirectory it would load fine in all cases, but if it
was contained at the root, the tar file would have to be written to
include the slash prefix. By default running tar on a directory will not
do this--which meant that data.json files would not be picked up if the
bundle was created using the tar command.
These changes modify the bundle reader to accept data.json files in all
of these cases. The behaviour between opa run . and opa run
bundle.tar.gz is consistent regardless of whether the bundle was written
by OPA or by tar.
Fixes #1019

Update bundle reader to allow relative data.json

---

cmd/run.go
docs/book/configuration.md
plugins/plugins.go
plugins/rest/rest.go

See commit for details. Other commit is just fixing a typo.

Add support for specifying services as object

---

docs/book/configuration.md

Add note to configuration reference about -c flag

---

ast/compilehelper.go
metrics/metrics.go
rego/example_test.go
rego/rego.go
rego/rego_test.go

I wrote some simple code the other day that used OPA as a library. In the process I realized there were a few things that could be clearer. This PR has a collection of patches that improve the user experience the first time around.

Small UX improvements for using OPA as a library 

---

format/format.go
format/format_test.go
format/testfiles/test.rego
format/testfiles/test.rego.formatted

Fix issues in opa fmt

---

ast/check.go
ast/compile.go
ast/compile_test.go
ast/compilehelper.go
ast/parser_internal.go
ast/policy.go
repl/repl.go
repl/repl_test.go

This PR contains a few commits that resolve issues discovered after running go-fuzz on OPA. The fuzzer can be found here: https://github.com/tsandall/fuzz-opa.

Panic at the parser.

---

bundle/bundle.go
bundle/bundle_test.go
loader/loader.go
loader/loader_test.go
plugins/bundle/plugin.go

Add manifest metadata to bundle data

---

docs/book/rest-api.md

Signed-off-by: Nikhil Bhatia <nbhatia@microsoft.com>
#1082

Update REST API specification with POST endpoint on Query API

---

docs/book/language-reference.md

Updates the doc for the built-in function count to mention strings.
Fixes #1122
Signed-off-by: Fraser Cobb <frasercobb@gmail.com>

Update count function doc to mention strings

---

cmd/test.go

Remove stray comment

---

SECURITY_RELEASE_PROCESS.md

SECURITY_RELEASE_PROCESS: fix "maintainers" link

---

docs/book/how-do-i-write-policies.md

Signed-off-by: Oksana Chuiko <oksana@styra.com>

fix docs: multiple links in policies tutorial were incorrect

---

internal/compiler/wasm/wasm.go
internal/ir/ir.go
internal/ir/walk.go
internal/planner/planner.go
test/wasm/assets/001_eq.yaml
test/wasm/assets/003_comparison.yaml
test/wasm/assets/004_negation.yaml
test/wasm/assets/005_references.yaml
test/wasm/assets/test.js

This PR contains a few small changes in the planner/compiler. The next thing to add is unification.

Miscellaneous Wasm compiler improvements that were queued up

---

ast/compile.go
ast/compile_test.go

This PR contains two fixes for assignment rewriting-related issues.

Fix two assignment rewriting-related issues 

---

docs/book/SUMMARY.md
docs/book/ceph-authorization.md

Add documentation for OPA-Ceph Integration.

---

docs/book/bundles.md

This is a common question so it should be answered at the beginning of
the documentation section on bundles.

docs: Update bundle docs with note about merging

---

docs/book/get-started.md

docs: Add note about inserting blank line to end multi-line

---

docs/book/SUMMARY.md
docs/book/discovery.md

Update Discovery docs with a realistic example.

---

plugins/rest/rest.go
server/server_test.go

[Please see the comments here](https://github.com/open-policy-agent/opa/compare/master...srenatus:sr/bugfix/default-transport#diff-f4076aa50c92ccd52544c8f6e44238e6R165); the fix in `server_test.go` is in the same vein, but less important 😃

plugin/rest: use proper settings for http.Transport

---

docs/book/language-reference.md
docs/book/styles/website.css

docs: Fix Regex doc horizontal alignment

---

PULL_REQUEST_TEMPLATE.md

This will be displayed when users submit a PR. This is a living
document. We can change/tweak/improve the text as needed.

Add PULL_REQUEST_TEMPLATE.md with frequent reminders

---

docs/book/bundles.md

There was a minor issue with capitalization.

docs: Tweak bundle documentation

---

cmd/eval.go
cmd/eval_test.go
internal/presentation/presentation.go

cmd: Add coverage support to eval subcommand

---

docs/book/rest-api.md

Fixes #1181
There are a couple of things reported in this PR: lack of 405 error and
missing return codes.
I decided to go through the entire REST API manual while comparing with
the code and found more discrepancies. These are the changes I've done:
1 - Restructured the sections to read
..rest api spec
..example
as opposed to:
..part of rest api spec
..example
..part of rest api spec.
As I went through the manual this break in the spec made things
confusing. If I was going to implement a client I would prefer to have
the complete spec for a certain method followed by an example as
opposed to the example break.
2 - Fixed missing or inconsistent return codes
There were quite a few of these.
3 - Added an overall 405 return code.
Since the sections are per method it does not make sense to …

Add documentation in the REST API section for error 405

---

cmd/plugins_test.go

Fix cmd integration tests to cleanup plugin directory

---

docs/book/comparison-to-other-systems.md

Signed-off-by: Sebastien de Menten <sdementen@gmail.com>

typo in example: change tickerAttributes to ticker_attributes to make it run properly

---

docs/book/http-api-authorization.md

- simplify python code (use json=, use strip)
- do not rename input as http_api (quite confusing, better to keep input everywhere in all tutorials
- reorder statement to always have input.user as first item in the rule
Signed-off-by: Sebastien de Menten <sdementen@gmail.com>

improve http-api tutorial

---

docs/book/how-do-i-write-policies.md

Document different between = and := in rules

---

internal/version/version.go
repl/repl.go
repl/repl_test.go
runtime/runtime.go
runtime/runtime_test.go
server/server.go
server/server_test.go

Refactor build version info and REPL module instantiation

---

cmd/run.go
runtime/runtime.go
server/server.go

See https://github.com/open-policy-agent/opa/issues/1232
Just let me know if docs should be updated in any way.

server: Add pprof endpoints & flag to enable/disable them

---

ADOPTERS.md
README.md

Update ADOPTERS.md with more detail

---

ADOPTERS.md

Add Cyral to list of adopters

---

ADOPTERS.md

More updates to the ADOPTERS.md file

---

ast/term.go

Improve hash distribution for objects.

---

cmd/eval.go
cmd/eval_test.go

The eval subcommand currently supports a --fail flag that causes the
subcommand to exit with a non-zero status when the query result is
undefined. While this is useful in some cases, runners often want to
see an error message explaining _why_ the exit status is
non-zero. Since the query result is undefined, policy authors can't
surface information in the result set
With these changes, the eval subcommand includes a new --fail-defined
flag has the opposite behaviour: exit with non-zero status if the
query result is defined/non-empty. This works well for deny lists that
are commonly found in admission use cases.

cmd: Add --fail-defined flag to eval subcommand

---

ast/compile.go
ast/compile_test.go

Add compiler stages

---

docs/book/layouts/header.html
docs/index.html

Update site with link to playground

---

README.md

Remove duplicate word in Roadmap description.

---

README.md

Also, use https:// throughout.

Add playground link in README

---

docs/book/faq.md

Enhance FAQ with additional answers

---

ast/compare.go
ast/compare_test.go

This improves the performance AST set benchmarks about 15%.

Remove two allocs from the AST number comparison.

---

ast/compare.go

Remove extra type cast

---

ast/term.go

This helps when the set/object size is known in advance, as it is with
set intersection, for instance:
SetIntersection/5-4                    2.96µs ±15%    2.58µs ± 9%  -12.86%  (p=0.000 n=14+15)
SetIntersection/50-4                   29.3µs ± 9%    28.6µs ± 8%     ~     (p=0.116 n=15+15)
SetIntersection/500-4                   308µs ± 7%     307µs ± 7%     ~     (p=0.683 n=15+15)
SetIntersection/5000-4                 3.30ms ±10%    3.22ms ± 5%     ~     (p=0.202 n=15+15)
SetIntersectionDifferentSize/4-4       2.14µs ± 5%    2.05µs ± 4%   -4.07%  (p=0.001 n=15+14)
SetIntersectionDifferentSize/50-4      2.19µs ± 5%    2.11µs ± 5%   -3.93%  (p=0.000 n=13+15)
SetIntersectionDifferentSize/500-4     2.24µs ± 8%    2.13µs ± 6%   -5.32%  (p=0.000 n=14+15)
SetIntersectionDifferentSize/5000-4 …

Remove unnecessary resizing allocs from AST set and object.

---

docs/content/docs/guides-identity.md
docs/content/docs/guides-kubernetes-admission-control.md
docs/content/docs/rego-cheatsheet.md
docs/layouts/partials/docs/navbar.html
docs/layouts/partials/docs/sidenav.html

Misc. improvements to guides

---

ast/builtins.go
docs/content/docs/language-reference.md
topdown/array.go
topdown/array_test.go

Fixes #1243
Signed-off-by: Ravi Soni <soniravi829@gmail.com>

Add array.slice built-in function

---

docs/content/docs/language-reference.md
topdown/array.go
topdown/array_test.go

Change clamping behaviour on array.slice to match expectation

---

docs/content/docs/faq.md
docs/content/docs/guides-kubernetes-admission-control.md
docs/content/docs/kubernetes-admission-control.md

This PR fixes a handful of remaining broken links

More link fixes

---

docs/Makefile
docs/README.md
docs/layouts/partials/docs/dashboard.html
docs/layouts/partials/docs/sidenav.html
docs/layouts/partials/docs/sidenav/local.html
docs/layouts/partials/docs/sidenav/production.html
docs/layouts/partials/home/banner.html

This PR provides a local development experience for the site/docs. When running the site locally, only docs from the current branch are visible (making pre-release docs visible/editable).
To try this out, you'll need to check out this PR and run the site locally):
```bash
cd /path/to/opa
git remote add lucperkins https://github.com/lucperkins/opa
git fetch lucperkins
git checkout lucperkins/lperkins/local-dev
cd docs
make serve
```
Then navigate to http://localhost:1313/docs
cc @tsandall

Provide local documentation development experience

---

docs/config.toml

Fix link to blog in site navbar

---

CONTRIBUTING.md
README.md

Add note about vendoring and move roadmap link to the top based on
recent conversations.

Updating README.md and CONTRIBUTING.md

---

README.md

Signed-off-by: Dan Kohn <dan@linuxfoundation.org>

OPA is now an incubating-level project!

---

server/server.go
server/server_test.go

To make this work it adds in a new shim interface for the server
to interact with the `http.Server`(s). We mock one out and can then
have it return errors on `Shutdown`.
This doesn't get explicit coverage of the timeout, we rely on the `http.Server`
implementation to behave correctly with deadline contexts.

Add unit tests for http server shutdown timeout

---

docs/Makefile
docs/layouts/partials/docs/dashboard.html
docs/layouts/partials/docs/sidenav/production.html

Add version dropdown navigation

---

docs/content/docs/how-does-opa-work.md

Fixes #1293
No tests, doc only changes as requested in #1293 
I also had a bit of confusion figuring this out, so figured others would benefit from this

Better documentation for providing the "input" document over http.

---

docs/content/docs/how-does-opa-work.md

The request and body are separate boxes on the other examples, noticed too late
after merging :(
Fixing it here.

Fixup docs formatting

---

docs/README.md

There was a typo on the makefile target and an additional required step to get things working.
Fixes: #1348

Update readme for  local Hugo docs in docker

---

docs/layouts/index.redirects

This means that instead of getting redirected to a specific version of a URL
we can browse with the “latest” version in the url.
Fixes: #1350

Change docs “latest” version to rewrite the url

---

docs/content/docs/how-does-opa-work.md

Update the input example http request to match the others

Add markdown highlighting keys to input example

---

docs/code/deployments-kubernetes/example-pod.json

To unblock the hugo production build we need to have this file re-added (was
removed in 41d201566562eb970f6a689dcc7f8039b400bf9d )
Partially Fixes: #1352

Add back in example-pod.json (temporary fix)

---

docs/code/deployments-kubernetes/deployment-opa.yaml
docs/code/kubernetes-admission-control-validation/admission-controller.yaml

These two YAML files were recently removed from the documentation sources. Unfortunately, these files are necessary to build an earlier version of the documentation (v0.10.6).

Add missing YAML files used in docs

---

docs/content/docs/deployments.md
docs/content/docs/monitoring.md

Add docs on health check API endpoint

---

docs/content/docs/discovery.md

- The discovery.name field has to be specified so remove paragraph in
the introduction that indicate it is not.
- Update the API description to clarify URL that OPA will fetch
discovery bundles from.
- Update the API description to show a more realistic configuration.
- Use the term "boot configuration" to refer to the configuration that
OPA is started with initially.
- Wrap long lines for readability in editors.

Improve discovery feature documentation

---

docs/content/docs/guides-kubernetes-admission-control.md

Add Kubernetes admission control debugging tips

---

docs/content/docs/security.md

Add hardened configuration example to security page

---

docs/Makefile
docs/assets/sass/style.sass

Add smooth scrolling

---

docs/content/docs/bundles.md

Update bundle docs with caching info

---

docs/content/docs/language-reference.md

The minor mistake in the documentation of array.slice function is corrected.
Signed-off-by: Sedat Gokcen <sedat@sedooe.com>

 Correct the doc of array.slice function

---

docs/layouts/index.redirects

We used to host them on GitHub pages, but didn’t bring them over to metlife.
Stop-gap fix is to just proxy to the old content.

Add rewrite rules in netlify for bundle content

---

README.md

This should at least give a little heads up as to whether or not the
docs are being published as expected.

Add netlify badge to README

---

build/gen-release-patch.sh
docs/devel/RELEASE.md

The process is pretty easy, just add a new line in RELEASES with the
version number. Once that git tag is available it will start to show
up on subsequent builds.

Update release process for newer docs

---

server/server.go
server/server_test.go

These changes update the server to compare the body of the HTTP
request with the existing policy in the store. If the bytes are equal,
the server returns immediately.
These changes are being made to workaround poor parser performance
given deeply nested JSON objects that are commonly found in Kubernetes
use cases. Specifically, we've observed very high parse times (e.g.,
over a second) when processing policies in production
environments. The problem becomes worse when kube-mgmt is being used
because it periodically resyncs the policies causing load even if the
policies are not changing.

server: Add early exit on PUT /v1/policies

---

docs/website/layouts/404.html

It's nothing too fancy, but it beats the default Netlify 404 page and is something we can iterate on later.
Here's the page in action:
https://deploy-preview-1395--openpolicyagent.netlify.com/foobar

Add basic 404 page

---

docs/content/security.md

docs: Update security docs with query parameter example

---

docs/content/deployments.md

docs: Add note about HTTP_PROXY and friends

---

internal/planner/planner_test.go

planner: Uncomment test rule

---

build/build-release.sh

We don’t need to make release bundles of the website content anymore.
They are continuously deployed from git as changes are merged.

remove `make site` from build-release.sh

---

build/test-wasm.sh

wasm: Remove unused wrapper script

---

docs/content/rest-api.md

The documentation for the /data API mentioned 404 status code which is incorrect. I removed it.

remove 404 status code

---

docs/website/static/support.html

Signed-off-by: lphamilton <lphamilton@berkeley.edu>

Fixing text alignment and footer on zoom/ hi-res display

---

docs/content/configuration.md
plugins/rest/aws.go
plugins/rest/aws_test.go
plugins/rest/rest.go
plugins/rest/rest_auth.go
plugins/rest/rest_test.go

Support AWS signing as REST authentication option

AWS signing as REST authentication option

---

docs/content/how-do-i-write-policies.md

Moved from https://github.com/open-policy-agent/opa/pull/1438 and signed off so DCO checks will pass.

Correct some typos

---

cmd/eval.go

cmd: Add --instrument flag to eval subcommand

---

docs/content/bundles.md

When reading the documentation of the `.manifest` file, it was a bit unclear, and just after looking at the code I could understand what it does. I tried to make it a bit clearer.

Improve bundle docs

---

ast/compile.go

This makes it easier for external projects to traverse dependencies.
Tests should not be needed as this is a rename of a function that is called once in the same package.
Signed-off-by: Max Smythe <smythe@google.com>

Make newGraphTraversal public

---

docs/content/rest-api.md

Updating additional instance where input document in a request is misrepresented as outlined in https://github.com/open-policy-agent/opa/issues/1293.

#1293: docs(): updating query api input example to match expected

---

docs/content/configuration.md

Add docs for empty config options

---

docs/content/rest-api.md

This reverts commit b0e5ce55d3c5b15193591fbe5a5145bc584ac430.
The doc example before was actually correct with regards to the input format for the default query endpoint.

Revert "docs(): updating query api input example to match expected"

---

docs/content/how-do-i-write-policies.md

Minor corrections

---

docs/content/configuration.md
plugins/discovery/config.go
plugins/discovery/config_test.go

close #1474 
Please LMK what you think, I'll update the doc if this is a good direction.

allow user to define the query used for discovery

---

docs/content/how-does-opa-work.md

docs: Remove mention of persistent storage

---

docs/Makefile

There was a typo in one and we didn't remove the generated releases.yaml

docs: Correct Makefile clean step

---

test/authz/authz_bench_test.go
test/authz/authz_test.go
test/authz/testing.go
test/e2e/authz/authz_bench_integration_test.go
test/e2e/testing.go

These will spin up a server runtime and perform similar tests to
The other authz benchmarks, except that they do it through the full
OPA server stack.

Add in end-to-end authz benchmark testing

---

docs/content/kubernetes-admission-control.md

This PR is fixing docs link in the kubernetes-admission-control-validation docs

Fix link in the kubernetes-admission-control docs

---

cmd/eval.go
cmd/eval_test.go

cmd: Fix double print of rego errors

---

docs/content/configuration.md
docs/content/decision-logs.md

Clarify the requirements/caveats for using the local decision logger
and include a blurb on the decision log.

docs: Clarify config for `console` decision logger

---

docs/content/comparison-to-other-systems.md

Signed-off-by: Xin Jin <xin@styra.com>
* No tests are updated since this is updates to docs. 
* This change is needed so that (1) SOD example can work when readers copy and paste. (2) AWS policy evaluation uses "principal" instead of "user" since "role" may also make API request.

docs: fix minor typos in example.

---

docs/content/language-reference.md

I believe that "=" was meant to be "==" as seen in the [comparison section](https://github.com/open-policy-agent/opa/blob/master/docs/content/language-reference.md#comparison).

content: Fixed typo in language-reference.md

---

CHANGELOG.md

Update CHANGELOG.md for v0.12.1

---

plugins/discovery/discovery_test.go

The goroutine polling the updates slice was not synchronized with the
goroutine that receives status updates. As a result, it was possible
for the polling goroutine to see partial values in the updates slice
(which would led to nil pointer dereferences.)

discovery: Fix race condition in test case

---

ast/compile.go
ast/compile_bench_test.go
ast/compile_test.go
ast/policy.go
ast/visit.go

This PR helps with performance when compiling large numbers of rules (e.g., that are output from partial evaluation.)

Improve rewrite dynamics performance

---

ast/builtins.go
ast/index.go
internal/planner/planner.go
internal/storage/mock/mock.go
plugins/plugins.go

Just a bunch of nitpicky typo fixes.

Fixed typos in code

---

internal/version/version.go

internal/version: Fixup docstring for UserAgent

---

.travis.yml

travis: Update install to include awscli

---

CHANGELOG.md

Updating the changelog for v0.12.2 (#1595)

Update CHANGELOG.md for v0.12.2

---

docs/content/language-cheatsheet.md

This is answers a common question that was recently raised in #1588.

docs: Add example of merging two objects

---

.travis.yml
Makefile
docs/website/layouts/shortcodes/current_docker_version.html

This tag will follow the current master branch and lines up with what
is in the docs as the `edge` version alias.

Add an `edge` tag for opa docker images

---

rego/example_test.go
storage/inmem/inmem.go
storage/inmem/txn.go

Some small improvements to the in-memory store to catch improper use of transactions.

storage: Add safety checks to in-memory store

---

server/server.go

This commit adds `http_request_cancellations` counter to the Prometheus
metrics. Having such a counter helps identify requests that were timed
out or the client just got disconnected before the request result was
computed.
Signed-off-by: Stan Lagun <stan@styra.com>

Monitor cancelled HTTP requests with Prometheus metrics

---

docs/content/bundles.md
docs/content/security.md

The configuration was using the old 'bundle' key when it should be
using the new 'bundles' key.

docs: Fix bundle configuration example

---

ADOPTERS.md

ADOPTERS.md: add Fugue

---

cmd/fmt.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

cleanup up fmt.go help message typo

---

docs/content/how-do-i-integrate-opa.md

This is not complete (e.g., more detail on management APIs would be
great, detail on CLI invocation would be nice, detail on partial
evaluation would be very helpful, etc.) but it provides a starting
point.
Fixes #372

docs: Add initial stab at integration guide

---

repl/repl.go

I believe it should be "undefined" as adj :)

repl.go: command help message correction

---

.travis.yml
Makefile

Makefile, .travis.yml: bump Golang 1.11 -> 1.12

---

CHANGELOG.md

Update CHANGELOG.md for v0.13.2

---

server/types/types.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

cleanup: fix obvious typos in types.go

---

ast/compile.go
ast/compile_test.go

ast: Copy moduleLoader returned parsed Modules.

---

plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

This changes to detect bundle root conflicts when "activating" a
bundle. The bundle in question will go into an error state and be
prevented from loading its data or policies.
If multiple bundles are being used, and one didn't define roots or
have a manifest (ie they claim all roots), it will conflict with all
other bundles and raise errors.
**Note: This does NOT affect bundles loaded from CLI with --data**
Fixes: #1635

plugins/bundle: raise error on root conflict

---

loader/loader.go
runtime/logging.go
runtime/runtime.go
topdown/builtins.go
util/backoff.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

Cleanup: fix some typos in code comment

---

CHANGELOG.md

Update CHANGELOG.md for v0.13.3

---

docs/website/config.toml
docs/website/layouts/partials/css.html
docs/website/layouts/partials/docs/navbar.html
docs/website/layouts/partials/javascript.html
docs/website/layouts/partials/meta.html

Addresses issue #1504.
@tsandall @patrick-east @kenfdev Honestly, I'm slightly shocked at how easy this was.
The bad news is that it's 100% magic, so I don't think there's much we can do to improve the search results/experience. But for an out-of-the-box thing, I think it's pretty damned okay.
**WARNING**: if you select one of the search results, it will take you out of the deploy preview and onto the production site. So if you click on a search result and the search bar is suddenly missing, that's expected behavior.

Add initial implementation of search bar

---

ast/visit.go

Notable improvements are:
benchmark                                        old ns/op      new ns/op      delta
BenchmarkRESTAuthzForbidAuthn-8                  531944         481911         -9.41%
BenchmarkRESTAuthzForbidPath-8                   605428         559036         -7.66%
BenchmarkRESTAuthzForbidMethod-8                 615807         572775         -6.99%
BenchmarkRESTAuthzAllow10Paths-8                 608273         565498         -7.03%
BenchmarkRESTAuthzAllow100Paths-8                1203957        1126383        -6.44%
BenchmarkRESTAuthzAllow1000Paths-8               6377612        6456720        +1.24%
BenchmarkPartialEvalCompile/1-8                  4200311        3797585        -9.59%
BenchmarkPartialEvalCompile/10-8                 6882760        5234766        -23.94% …

ast: Remove noop walk visitor invocations.

---

docs/devel/DEVELOPMENT.md

docs: Add note about benchmark result page

---

ast/compare.go

Notable improvements are:
benchmark                                        old ns/op      new ns/op      delta
BenchmarkObjectLookup/5-8                        42.3           37.3           -11.82%
BenchmarkObjectLookup/50-8                       54.1           46.1           -14.79%
BenchmarkObjectLookup/500-8                      55.0           46.0           -16.36%
BenchmarkObjectLookup/5000-8                     51.1           46.5           -9.00%
BenchmarkSetIntersection/5-8                     2340           2280           -2.56%
BenchmarkSetIntersection/50-8                    26239          25365          -3.33%
BenchmarkSetIntersection/500-8                   276254         261412         -5.37%
BenchmarkSetIntersection/5000-8                  3050602        2880013 …

ast: Remove an unnecessary recursion in Compare with *Term types.

---

ast/compile.go
topdown/eval.go
topdown/save.go

Notable improvements are:
benchmark                                 old ns/op      new ns/op      delta
BenchmarkAuthzForbidAuthn-8               32946          31448          -4.55%
BenchmarkAuthzForbidPath-8                100565         98802          -1.75%
BenchmarkAuthzForbidMethod-8              106440         106324         -0.11%
BenchmarkAuthzAllow10Paths-8              102167         100737         -1.40%
BenchmarkAuthzAllow100Paths-8             633225         613168         -3.17%
BenchmarkAuthzAllow1000Paths-8            5987919        5490712        -8.30%
BenchmarkRESTAuthzForbidAuthn-8           525042         516558         -1.62%
BenchmarkRESTAuthzForbidPath-8            617314         594506         -3.69%
BenchmarkRESTAuthzForbidMethod-8          637980         601462 …

ast & topdown: Remove defers.

---

docs/website/static/support.html

This reverts commit 1f4a6e3f2227b007550471b268d4fc01e7037f46.
The url was fixed, no need for this change anymore.
Signed-off-by: Marco Sanvido <marco@styra.com>

Revert "Fix support link"

---

.travis.yml
Makefile
ast/fuzz.go
build/fuzzit.sh

This PR adds continuous fuzzing to OPA via [fuzzit](https://fuzzit.dev)
More details explained in this issue: https://github.com/open-policy-agent/opa/issues/1652
cc @tsandall

Continuous Fuzzing via Fuzzit

---

Makefile

Prepare v0.13.5 release

---

CHANGELOG.md

Adds comments for changes included in v0.13.5 patch release.

Update release notes for v0.13.5

---

docs/devel/RELEASE.md

Currently this is a bit manual. We can automate/improve it in the future.

docs: Update RELEASE.md file to include bugfix process

---

docs/content/management.md

Now that we have multi bundle support and the new `decision` field, it's time to update the docs.

added examples for decision and multi bundle

---

docs/content/policy-reference.md
internal/runtime/runtime.go

Exposed the runtime OPA version on `opa.runtime` - can be used in discovery, for example, to expose features based on OPA version (e.g. multi bundle is supported only from a specific version).

expose opa version as runtime information

---

docs/content/envoy-authorization.md
docs/website/layouts/shortcodes/current_opa_istio_docker_version.html

docs: Create tutorial for Envoy-OPA integration.

---

ast/compile.go
ast/compile_test.go
topdown/topdown_test.go

This is a first stab at solving #1565 using the approach suggested
there by Torin in the issue.

Prevent recursion using dynamic references

---

ast/fuzz.go

ast: Fix fuzzer blacklist to include (

---

docs/content/policy-reference.md
internal/runtime/runtime.go

runtime: Add build commit to runtime info

---

plugins/logs/plugin.go

Signed-off-by: omerlh <omerl@soluto.com>
added type to the decision logs, close #1716

added type field to decision logs

---

docs/website/config.toml

This was breaking the site.. reverting the change.

docs: Turn off canonifyURLs

---

Makefile

build: Fix bad makefile target

---

Makefile

The fuzzer wasn't receiving the API key so it was bailing out.

build: Pass FUZZIT_API_KEY to container

---

test/e2e/logs/console_decision_logger_test.go

This just updates the existing test to include the new field and
enforce that it has the right value.

decision logs: Add e2e coverage for tagged console log

---

ast/policy.go
ast/policy_test.go

Signed-off-by: Mikol Graves <mikol@thinbox.org>

Replace "var" with "some" in SomeDecl#String

---

docs/content/deployments.md

We have info for the `latest` tag, `*-dev` tags, and this just adds
a blurb about the `edge` tag.

docs: Add note about `edge` docker image tag

---

docs/website/layouts/index.redirects

These are no longer correct as the content was moved out of the
management page.

docs: Remove old redirects for `/monitoring` and `/configuration`

---

docs/content/terraform.md

Just fixing a couple of little things I noticed while following the
guide.

docs: Minor fixups to terraform guide

---

CHANGELOG.md

Update changelog for 0.14.1

---

docs/content/kubernetes-primer.md

docs: Update Kubernetes primer test to avoid false-positives

---

docs/website/scripts/live-blocks/scripts/inject
docs/website/scripts/live-blocks/src/errors.js
docs/website/scripts/live-blocks/src/preprocess/index.js
docs/website/scripts/live-blocks/src/preprocess/localEval.js

As of now the "edge" docs have a newer standardized format for output.
The preprocessing step for live-blocks needed to be updated to handle
parsing it.

live-blocks: Update to handle new JSON CLI format

---

Makefile
internal/file/loader.go
topdown/bindings.go
topdown/eval.go
topdown/query.go
topdown/topdown_partial_test.go

Release 0.14.2

---

CHANGELOG.md

Update CHANGELOG.md for v0.14.2

---

plugins/discovery/discovery.go

discovery: Fix log level message when on HTTP 304

---

docs/website/layouts/partials/home/banner.html

website: Update link to OPA summit page

---

cmd/eval.go
internal/presentation/presentation.go
internal/presentation/presentation_test.go

This is useful if you want to copy-paste the output of partial eval
into a file.

cmd: Add source output format for partial eval

---

ADOPTERS.md

ADOPTERS.md: add Yelp
Signed-off-by: Daniel Popescu <dpopes@yelp.com>

ADOPTERS.md: add Yelp

---

ast/term.go
internal/compiler/wasm/wasm.go
internal/ir/ir.go
internal/planner/planner.go
internal/wasm/instruction/numeric.go
test/wasm/assets/001_eq.yaml

This commit updates the planner and backend to support construction of
floating point numbers.

wasm: Add support for floating point numbers

---

ast/compile.go
ast/compile_test.go

When rewriting declared vars in objects the compiler was not rewriting
the object keys recursively during construction of the new
object. This meant the new object's hashtable would get corrupted when
the outer visitor ultimately performed the rewriting on ref keys.
Since the compiler already keeps track of whether the outer visitor
needs to recurse, the fix simply updates the compiler to rewrite
object key/value terms recursively when the new object is being
created and stops the outer visitor from recursing on the new object.
Sets are given the same treatment because they have the same
underlying hashtable (though it's unlikely we would see the issue for
sets since the hashtable is only used for Contains() and we rarely, if
ever, call Contains() w/ var terms).
Fixes #1852
Signed-off-by: …

ast: Fix object corruption during local rewrite

---

docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/package.json

This brings in syntax highlighting for the `some` keyword

docs/live-blocks: Update codemirror-rego to 1.1.0

---

docs/website/scripts/integration-index/integrations.yaml

Integration index

---

docs/website/static/css/home.css

Signed-off-by: Mikol Graves <mikol@thinbox.org>

website: Fix examples syntax highlighting

---

ADOPTERS.md

This PR adds a link to the second blog post on OPA usage by Very Good Security (VGS).

ADOPTERS.md: update Very Good Security (VGS)

---

docs/content/policy-language.md

Signed-off-by: John Reese <john@reese.dev>
Fix small typo found while reading through documentation

Change undefine to undefined

---

docs/website/scripts/integration-index/README

docs: Add integration-index README

---

topdown/topdown_test.go

If OPA_TEST_DUMP is set the tests will be dumped to the specified
directory on disk.

topdown: Add environment variable to dump tests to disk

---

test/wasm/assets/test.js
test/wasm/cmd/wasm-rego-testgen/main.go

Previously the generator would error out if the test case could not be
compiled. With this change, the generator just continues with the test
case marked as skipped. If the runner has verbose output enabled each
skip is reported. Once more built-in functions have been implemented
we can report skips by default.

wasm: Update test framework to support skipping tests

---

ast/policy.go
internal/compiler/wasm/wasm.go
internal/ir/ir.go
internal/ir/walk.go
internal/planner/planner.go
internal/wasm/instruction/numeric.go
test/wasm/assets/016_with.yaml

This PR fixes a couple issues in the with keyword implementation that were found using the dumped topdown test suite.

wasm: Improve with keyword implementation

---

internal/planner/planner.go

Previously the planner would never reuse local variables across
blocks. This becomes a problem for large query sets (e.g., due to
partial eval) or large rule sets (e.g., due to disjunction). This
change updates the planner to reuse local variables across
blocks. Anecdotally this became a problem with 10K rules that each
performed a 3-tuple check.
Also, restore the target variable after planning rules. Although this
does not matter the planner state should be fully restored when
planRules returns. Perhaps it's time to refactor so that planner state
does not have to be mutated so much.

wasm: Improve planner to reuse local variables

---

docs/content/wasm.md

We don't currently support compiling to Wasm via the HTTP API. In the
future this could be added.

docs: Fix note about options for compiling to Wasm

---

docs/website/layouts/index.html

website: Fix page title

---

docs/website/layouts/index.html

website: Change integrations link to /docs/latest/

---

docs/website/static/css/support.css
docs/website/static/support.html

Drop the viking ships in favor of blue clouds.

website: Theme /support the same as the homepage

---

ast/check.go
ast/check_test.go
ast/compile.go

Similar to 0b28390 this change updates the ref checker to unmangle
variables that are included in error messages.
Fixes #1430

ast: Fix type checker to unmangle variables

---

docs/content/policy-reference.md

This adds some highlights to sections that commonly trip up users and
gives some additional examples for how the functions work and can
interact.
Fixes: #1916

docs: Add some clarifications to JWT docs

---

docs/website/layouts/index.html
docs/website/static/support.html

This just updates the support page nav bar to match what is currently
in index.html.
The links for the OPA logo are also changed to point back to the home
page.

docs/website: Update support page header to match index.html

---

docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/package.json

There is a known security issue with the older version. Updating to
the latest mitigates the risk.

Update serialize-javascript for live-blocks tooling

---

ast/builtins.go
ast/term.go
ast/term_test.go
docs/content/policy-reference.md
topdown/json.go
topdown/json_test.go

The new builtin takes an object and list of paths to keep.
Reference: #1617

Add `json.filter` builtin

---

plugins/rest/rest.go
plugins/rest/rest_test.go

The HTTP client we were using for bundle downloads was being loaded
once and then re-used. This was problematic for users that configure
cert files and then have them change.
This updates the client wrapper in OPA to re-create the underlying
client for each request.
Fixes: #1898

Create new HTTP rest client for each download

---

Makefile

This was added accidentally during the last release cut. This only
affects the dev build so it's not a big deal.

make: Remove 'v' in Makefile VERSION

---

ADOPTERS.md

It would be an honor to have my startup listed among OPA adopters.

Add Spacelift to the list of adopters

---

ADOPTERS.md

Adding [Plex Systems](https://plex.com) to the list of adopters.

Add Plex Systems to Adopters

---

MAINTAINERS.md

Update MAINTAINERS.md file with company affiliations

---

Dockerfile

moves ARG USER down , to make it work as it should
Fixes #1982

Dockerfile move USER argument down

---

docs/content/_index.md

Was being silly and spent a while figuring out how to run the samples locally only to find the guide once I got to the end of the samples, to help out others this PR puts a mention of it at the start of the doc.
#1996

minor docs: mention local execution early in intro doc

---

CHANGELOG.md
Dockerfile
Makefile

This includes the bug fix for the rootless image.

Prepare for  v0.16.1 release

---

CHANGELOG.md

Just updating master to have the release notes for 0.16.1

Update changelog for v0.16.1

---

rego/rego.go
rego/rego_test.go

We would previously lose any builtin functions provided to the Rego
object after partially evaluating it. Upon creating a new Rego
instance from the PartialResult you would have to re-declare them
all again which breaks the simple case of just getting a new Rego
and evaluating. We should, at a minimum, make sure the Rego produced
by the PartialResult is able to be evaluated.
This change just passes along the declarations to the new Rego
instance. Everything is done with internal bits in the rego package
so we could adjust this later on if we want to.
Fixes: #1792

rego: Propagate custom builtins to PartialResult

---

docs/content/kubernetes-tutorial.md

The **bold** strings are consistently the filename to be created in the tutorial, except for the one fixed in this PR.
Signed-off-by: Dr Nic Williams <drnicwilliams@gmail.com>

Filename .rego suffix expected

---

Makefile
topdown/trace.go
topdown/trace_test.go

Release 0.16

---

build/changelog.py

build: Fix changelog.py to accept : in Fixes directive

---

CHANGELOG.md

Update CHANGELOG.md for v0.16.2 release

---

ast/visit.go

This changes the Visitor interface to be as before the Walk
deprecation.

ast: Maintain the Visitor interface backwards compatible.

---

ast/compile.go
server/server_test.go
topdown/crypto_test.go
topdown/eval.go
topdown/query.go
topdown/save.go
topdown/topdown_partial_test.go

This PR improves partial evaluation support. The 8058305 commit message explains the changes.

Improve partial evaluation coverage

---

docs/content/kubernetes-tutorial.md

docs: Fix Deployment manifest in ingress-conflict tutorial

---

docs/content/deployments.md

Fixes #1977
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>

Migrate apiVersion to support k8s 1.16+

---

CHANGELOG.md

Fix changelog to include note about glob.match

---

docs/content/kubernetes-tutorial.md

docs: Update tutorial with note about consistency

---

rego/rego.go
rego/rego_test.go

Signed-off-by: Xin Jin <xin@styra.com>

Initialize bundles correctly when creating Rego object.

---

docs/content/_index.md

...for our friends down under like @teq0.
Fixes #2106

docs: How to say "ray-go"

---

topdown/http_test.go
topdown/topdown_test.go

Somehow this was missed in the PR review.

topdown: Fix http.send/expected error test case

---

docs/content/envoy-authorization.md

Signed-off-by: Michael Wittig <michael@widdix.de>

Fix deprecation warning by using typed_config

---

docs/website/layouts/partials/docs/sidenav.html

Add link to Rego Playground on Sidenav in docs site

---

topdown/http_test.go

The original was using very short (1us) timeouts but it seemed to
be inconsistent, especially on travis. There are now larger deltas
between the timeouts and longer base ones. The overall impact to the
unit test times are still pretty minimal.

Increase timeout deltas for http.send timeout test

---

topdown/builtins.go

This is useful in reusing the golang builtin implementations with
wasm compiled policies running on golang.

topdown: Export builtin implementations outside the package.

---

docs/website/data/integrations.yaml

docs: Add Choria custom-app blog

---

CHANGELOG.md
Makefile

Prepare v0.17.2 release

---

CHANGELOG.md
Makefile

Prepare v0.18.0 development

---

docs/content/ssh-and-sudo-authorization.md

docs: Fix broken PAM module link

---

docs/content/kubernetes-introduction.md

Signed-off-by: Sharjeel Aziz <sharjeel.aziz@gmail.com>

Fix a typo in kubernetes-introduction.md

---

docs/content/_index.md

Without this patch, the popular tutorials are listed in a single
line, delimitated with asterisks.
This is ugly, and it was intended to be a list instead.
Fixes #2071

[doc] Render tutorials as list

---

bundle/bundle.go
bundle/bundle_test.go
docs/content/management.md

bundle: Dedicate policy.wasm for the compiled policy.

---

topdown/json_test.go

These were broken after rebasing and merging into master (the error
type check wasn't in place on the PR branch..). This corrects the test
errors.

topdown: Fix json.remove unit tests

---

docs/content/_index.md

Change Windows download from release link to direct download link

---

docs/content/kubernetes-primer.md

Generally values are assigned to variables so I rewrote the text to make it easier to read.
Signed-off-by: Sharjeel Aziz <sharjeel.aziz@gmail.com>

Rewrite paragraphs for clarity.

---

CHANGELOG.md

Update CHANGELOG for v0.17.3

---

docs/content/policy-reference.md

docs: minor typo `resposne` -> `response`

---

ast/parser_bench_test.go

Related to #1251, we have a new parser in the works.. but without
any benchmarks it is hard to definitively say we "fixed" the perf
issues. Adding these now with the "old" parser to get a baseline
started for tracking in
https://opa-benchmark-results.s3.amazonaws.com/index.html

ast: Add some parser benchmarks

---

Makefile
docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/package.json
docs/website/scripts/live-blocks/src/helpers.js
docs/website/scripts/live-blocks/test/helpers.test.js

Fixing https://github.com/advisories/GHSA-7fhm-mqm4-2wp7
This also fixes the unit tests (not sure how long they've been borken)
and makes them run as part of the netlify preview build, so any
regressions should be seen in PR's.

docs: Update acorn to fix CVE with dev tooling

---

docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/package.json

More follow on to fixing our dev tooling for the website for:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7598

docs: Update minimist dev tool dependency

---

CHANGELOG.md
Makefile

Prepare for v0.18.0 release

---

CHANGELOG.md
Makefile

Prepare v0.19.0 development

---

docs/content/_index.md

There were two small issues in the `opa eval` and `opa run` examples.

docs: Fix "try opa" section in intro

---

docs/content/policy-reference.md

docs: Fix spacing in policy reference

---

docs/content/management.md

This patch set adds a missing quote in the markdown documentation.
Closes: #2214
Signed-off-by: Tin Lam <tin@irrational.io>

docs(markdown): fix rendering

---

ast/builtins.go
docs/content/policy-reference.md
topdown/cidr.go
topdown/cidr_test.go

topdown: Add net.cidr_contains_matches built-in function

---

.travis.yml
Makefile
docs/website/scripts/load-docs.sh

Any release tag with a `rc` string in the semver version
will be ignored for the docs on the website and will _not_ update the
"latest" docker image tag, or "latest" downloads url.

Add support for release candidate version tags

---

docs/website/layouts/index.html
docs/website/static/css/home.css

This change is made so that it is more clear to people that
the examples do have an underlying playground example.
Fixes #2207

docs: Add a "Open In Playground" button below policy examples

---

repl/repl.go
repl/repl_test.go

This command is useful for removing packages from
the current REPL session without having to exit it
Fixes #2140

Add unset-package command to REPL

---

docs/website/layouts/index.html

Adds target="_blank" to the button links
Fixes #2209

Open homepage links in new tab

---

docs/content/kubernetes-primer.md

i found a littyle typo when writing kubectl command.

[DOCS UPDATE ] there is a little typo here in kubectl command at page kubernetes-primer/#detailed-admission-control-flow

---

docs/website/layouts/index.html

add download link from landing site

---

server/server.go
server/server_test.go

Previously we would iterate over all modules on the compiler and then
look them up by id in the store. This causes problems when there are
partial compilation results on the compiler that have not been put in
the store.
To correct this we will now reverse how it iterates, instead iterating
over a list of policies from the store and looking up their AST from
the compiler as needed.
Fixes: #2036

server: GET /v1/policies - Don't return partial modules

---

docs/website/layouts/partials/docs/navbar.html

We had changed the name of the docs section at some point and missed
updating one spot for the mobile site. This corrects the issue.
Fixes: #2074

docs/website: Fix mobile docs nav menu

---

topdown/topdown_bench_test.go

This commit adds a benchmark that exercises comprehensions that
perform cross products. This will give us a baseline for the
improvement tracked by #2276.

topdown: Benchmark comprehensions that perform cross products

---

README.md

Update meeting link for OPA bi-weekly

---

docs/content/configuration.md

docs: Add note about re-reading bearer token from file

---

CHANGELOG.md
Makefile

Prepare v0.19.1 release

---

CHANGELOG.md
Makefile

Prepare v0.20.0 development

---

ast/compile.go
ast/compile_test.go

See commit messages for details. Let's merge this after the release.

Fix bug in output var analysis and refactor to remove dead code

---

GOVERNANCE.md
MAINTAINERS.md

The previous governance model did not account for areas of expertise
like gatekeeper or other sub-projects. As the OPA project grows, it is
necessary to clarify responsibilities and ownership of different parts
of the project.
This commit updates the governance model to reflect (1) that we do not
hold votes on individual PRs (this was cargo-culted from an existing
CNCF document at the time and is not relevant) (2) organization voting
will be used to resolve conflicts and (3) maintainers statuses and
areas of expertise.

Update governance model to reflect areas of expertise

---

docs/content/monitoring.md

The 'glboal_scrape' key was renamed to 'global' at some point.
Fixes #2277

docs: Fix example prometheus config

---

docs/content/policy-reference.md

The rule-body non-terminal symbol did not quote the '=' symbol.
Signed-off-by: marco <marco@styra.com>

docs: Fix the EBNF for the '=' terminal symbol

---

CONTRIBUTING.md
docs/devel/DEVELOPMENT.md

Adds some additional links on some workflow steps and removes an older
unused section.
There is also a little bit more detail on the desired commit message
format.

Update dev docs

---

cmd/test.go
docs/content/policy-testing.md
rego/example_test.go
rego/rego.go
repl/repl_test.go
server/server_test.go
server/types/types.go
tester/reporter.go
tester/reporter_test.go
topdown/trace.go
topdown/trace_test.go

Recently we improved the trace pretty printing to include location
information on events. Unless there's a good reason we should use this
tracer printing throughout.

Report location info on pretty traces

---

docs/content/deployments.md
docs/content/policy-performance.md

There are many ways this question can be answered so this is not a
final answer but instead a starting point. In the future we can expand
on this section to include more use-case specific resource utilization
guidance however for the time being this is a good start.
Fixes #1601

docs: Add guidance around resource utilization

---

docs/content/management.md
plugins/discovery/discovery.go
plugins/discovery/discovery_test.go
plugins/rest/rest.go

This reverts commit d67c0f7f1331ccafa10d93f9a6bd1edb9abc7a27.

Revert "plugins: Additive updates to services when discovery enabled"

---

format/format.go
format/testfiles/test.rego.formatted
format/testfiles/test_issue_2299.rego
format/testfiles/test_issue_2299.rego.formatted

fix(style): opa fmt with else keyword

---

docs/website/static/css/home.css

Fixed the Home page UI hover issue 
Fixes: #2309
Signed-off-by: Arun Kumar <arunbsar@gmail.com>

Fixed home page hover issue #2206

---

ast/builtins.go
docs/content/policy-reference.md
go.mod
go.sum
internal/uuid/uuid.go
internal/uuid/uuid_test.go
runtime/runtime.go
topdown/uuid.go
vendor/modules.txt

Signed-off-by: Rene Klootwijk <rene.klootwijk@rencon.nl>
I included no test because the uuid command returns a random string which cannot be tested other than if it is a string.

A built-in command to create a version 4 uuid

---

ast/builtins.go
topdown/uuid.go

Also remove the prefix on the cache key since it's not needed (the
type alias is enough to prevent conflicts, e.g., uuidCachingKey("X")
!= "X".)

ast: Rename UUID symbol to avoid confusion

---

ast/builtins.go
topdown/builtins.go
topdown/eval.go
topdown/query.go
topdown/uuid.go
topdown/uuid_test.go

Also, prevent uuid function from being partially evaluated for
now. Eventually we will need better controls in place for this kind of
thing but for the time being it is safe to exclude from partial
evaluation like we do with http.send and time.now_ns.

topdown: Add test coverage for new uuid built-in function

---

docs/website/data/integrations.yaml

Kong version 1.0.0 introduced the Plugin Development Kit and updated all bundled plugins to use version 1.0 of the PDK.
All entities and concepts marked as deprecated in Kong 0.x have been removed in Kong 1.0 and a final version (0.15) that support plugins for Kong 0.x series as been released at the same time.
The TravelNest implementation has been done for Kong v0.13.x and has not been updated to work with versions > 1.0.x
This new implementation follows the new plugins project structure and has been tested with Kong 2.0.0.
Signed-off-by: Younes Zahidi <12915382+zahiyo@users.noreply.github.com>

docs: Add additional kong integration

---

server/server.go

This commit fixes another data race found by running go test
-race. The server was reading state modified by the trigger handler
without using a mutex or being inside of a transaction.
Note, we should think about how we can move away from relying on the
server transactions to implement critical sections in the server as
this is bound to bite us in the future.

server: Fix data races around state modified on reload

---

docs/website/layouts/index.html
docs/website/static/css/home.css

Fixed home page learn more buttons
[demo](https://opa-6816e6.netlify.app/)
Fixes #2205
Signed-off-by: Arun Kumar <arunbsar@gmail.com>

Fixed home page learn more buttons

---

CHANGELOG.md

Update release note for 0.19.2

---

ISSUE_TEMPLATE.md

Providing some examples of the kinds of info that are helpful in
reproducing bugs in OPA.

Flesh out the ISSUE_TEMPLATE.md file a bit

---

topdown/eval.go
topdown/topdown_partial_test.go

In dda04ef6cb241465c297faf2025bde20b2d0e881 we fixed a bug in PE that
caused unknown terms to get evaluated when they should have been
saved. However, the fix itself contained a bug inside evalTerm whereby
the evaluator would save the binding list from the query that produced
the unknown as opposed to the binding list for the reference suffix
that was being saved. This issue manifests in PE output with
references containing free variables instead of plugged values.
This commit fixes the issue by unifying the unknown value with a
generated variable associated with the reference suffix's binding
list. The reference to be saved is then constructed from the generated
variable. This ensures that all of the terms in the reference to be
saved are associated with the same, correct binding list. …

topdown: Fix partial eval to save correct binding list

---

GOVERNANCE.md

In 6a222dc we updated the model to reflect different
repos/subprojects/areas of expertise. However, there were still parts
of the model that were unclear so this commit addresses the gaps. The
following parts have been clarified/made explicit:
1. All maintainers can vote on creation of new repos. If this becomes
cumbersome we can revisit.
2. Contributors can be added to teams without being granted full
voting rights. This allows us to onboard subprojects, granting
new contributors admin rights over those areas without granting full
voting rights immediately. After those contributors remain active for
some period (e.g., a few months) they can be promoted to full
maintainer status by other maintainers.
3. Maintainers can be removed by a vote from other maintainers in the
same area. …

Update governance (again)

---

go.mod
plugins/bundle/config_test.go

To mainatin the consistency in project using github.com/ghodss/yaml as this is used for yaml utilities across the project.
@tsandall 
#2377

Remove gopkg.in/yaml.v2 dependency

---

ADOPTERS.md

Add T-Mobile to the ADOPTERS.md file.

Add T-Mobile to ADOPTERS.md

---

docs/README.md

Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>

docs: Update link to netlify.toml in README.md

---

CHANGELOG.md
Makefile

Prepare v0.20.2 release

---

CHANGELOG.md
Makefile

Prepare v0.21.0 development

---

CHANGELOG.md

Update CHANGELOG for v0.20.3 release

---

CHANGELOG.md
Makefile
format/format.go
format/format_test.go

Prepare v0.20.4 release

---

CHANGELOG.md

Update CHANGELOG for v0.20.4 release

---

CHANGELOG.md

Updating the master CHANGELOG for the 0.20.5 release (#2448)

Update changelog for 0.20.5 release

---

docs/content/philosophy.md

Small typo fix for the documentation.

Fix typo in philosophy.md

---

ADOPTERS.md

Per a conversation with @tsandall.

Adding Splash as an adopter

---

docs/content/_index.md

cheatsheet was merged into reference at comit https://github.com/open-policy-agent/opa/commit/f0c222c43370d661c0fe4362c5c6de3d7b36cad3#diff-e3e2a9bfd88566b05001b02a3f51d286

docs: remove cheatsheet from index page

---

ADOPTERS.md

Signed-off-by: Andrew Martin <sublimino@gmail.com>
Supersedes https://github.com/open-policy-agent/opa/pull/2476

docs: add ControlPlane to ADOPTERS

---

docs/website/layouts/index.redirects

docs: Add redirect for the old cheat sheet content

---

docs/content/policy-performance.md

docs: Fix mistake in the new optimization level docs

---

docs/content/deployments.md
docs/content/faq.md
docs/content/integration.md

Debated whether putting this content into the integrations and deployment pages or elsewhere.  The integrations comparison feels pretty natural.  The deployment docs feels less so, but not bad where it is; suggestions welcome.

Doc improvements for integrations and deployments

---

docs/content/integration.md

docs: Fix prometheus endpoint link

---

docs/content/kubernetes-tutorial.md

fixes: #2467
Attachments are related result for the fixed policy. Thanks the instruction from @tsandall.
`$ kubectl describe configmaps opa-default-system-main`
```
Name:         opa-default-system-main
Namespace:    opa
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
{"apiVersion":"v1","data":{"main":"package system\n\nimport data.kubernetes.admission\n\nmain = {\n  \"apiVersion\": \"admission.k8s.io/v1...
openpolicyagent.org/policy-status: {"status":"ok"}
Data
====
main:
----
package system
import data.kubernetes.admission
main = {
"apiVersion": "admission.k8s.io/v1beta1",
"kind": "AdmissionReview",
"response": response,
}
default uid = ""
uid = input.request.uid
response = {
"allowed": false,
"uid": uid,
"status": {
"reason": reason,
},
} {
reason = …
```

docs/content: fix kubernetes admission controller tutorial

---

docs/content/extensions.md

Removed `passing` in favor of `accepting`.
Signed-off-by: Ethan Rogers <ethanfrogers@gmail.com>

Small typo fix, remove redundant wording

---

rego/example_test.go

Fixes #2294
Signed-off-by: Gaga Pan <gaga5lala1013@gmail.com>

rego: use correct PartialResult in test

---

compile/compile_test.go
topdown/eval.go
topdown/topdown_partial_test.go

Fixes for two recent partial evaluation issues

---

docs/content/kubernetes-tutorial.md

The tutorial had not been updated to refer to the latest version which
has an important fixes to improve performance and consistency.

docs: Update kubernetes tutorial to refer to latest kube-mgmt release

---

.github/workflows/pull-request.yaml

We had `tags` specified but its looking for `flags`. This was causing
a warning on the tests.

Update Codecov action configuration

---

.github/workflows/post-merge.yaml

We were only doing it on the PR workflows, but we should have one
uploaded on master after merges to keep an up to date baseline.

Upload Codecov report on master after merge

---

codecov.yaml

This should help eliminate some noise being caused on the CI jobs
marking PR's as not passing tests.

Add Codecov threshold of 1% for project

---

docs/devel/RELEASE.md

With the new GitHub actions workflows the steps changed for releasing
bugfix changes. This commit updates to the latest steps and makes a
few clarifications/corrections.

docs/dev: Update RELEASE.md bugfix release steps

---

CHANGELOG.md

Update CHANGELOG.md in master with 0.21.1 note

---

docs/content/management.md

Fixed management.md for typo

---

.github/workflows/nightly.yaml

The step was skipped because the previous one failed. This should now
only upload on failures.

CI: Upload fuzz crashers on failure

---

runtime/runtime.go
server/server.go

There are two races that were being found (in multiple of our e2e test environments). See each commit for details.
With these changes `make race-detector` now passes consistently on my local machine.

Fix issues with `make race-detector`

---

CHANGELOG.md
Makefile

Prepare v0.22.0 release

---

CHANGELOG.md
Makefile

Prepare v0.23.0 development

---

.github/workflows/nightly.yaml

Update the conditional syntax to be valid and switch to a different
slack action helper that provides a better end result.

CI: Fix slack notifications

---

ast/term.go
ast/term_test.go

ast: Maintain object ground bit over object key updates.

---

Makefile

The previous version would default to literally setting it to "" (with
the double quote characters) rather than an actually empty string.

Makefile: Fix default value for TELEMETRY_URL

---

ast/term.go

This slightly increases the amount of memory allocated (but not the number of allocs), but it reduces the CPU load by avoiding unnecessary term hashing in the evaluation.
On a particular fairly complicated policy this reduced the evaluation time ~10%.

ast: Cache hashes for containers.

---

topdown/eval.go
topdown/input.go

topdown: Remove unnecessary term copying.

---

util/wait_test.go

The delays were too aggressive. Bumping them to be orders of magnitude
in difference.

util: Fix flakey wait function unit tests

---

ast/index.go
ast/index_test.go

Previously when glob.match statements were indexed, the index trie
node would have a mapper function set on it. The problem was that if
subsequent rules were added to the index and required a different
mapper (or none at all in the case of equality statements), the
original mapper would be overwritten. This would result in
false-negatives when the index was queried (i.e., the rule that was indexed
first would not be returned).
This commit fixes the issue by storing multiple mappers on the trie
node (one per delimiter in the case of glob.match). If multiple
mappers are encountered during traversal, each one will be tested.
Fixes #2617

ast: Fix rule indexing when multiple glob.match mappers are required

---

docs/website/scripts/live-blocks/package-lock.json
docs/website/scripts/live-blocks/package.json

Using `npm audit fix` update dependencies of the live-blocks tooling.
This corrects 9 of 11 vulnerabilities found by `npm`.

docs: Update live-blocks dependencies

---

docs/content/external-data.md
docs/website/layouts/index.redirects

docs: Update external data page description of sync-pull option

---

CHANGELOG.md
Makefile
capabilities/v0.23.0.json

Prepare v0.23.0 release

---

CHANGELOG.md
Makefile

Prepare v0.24.0 development

---

docs/devel/RELEASE.md

Update release steps to account for capabilities files

---

CHANGELOG.md
Makefile
capabilities/v0.23.1.json
docs/content/configuration.md
docs/content/management.md
plugins/discovery/discovery.go
plugins/discovery/discovery_test.go
plugins/rest/rest.go
plugins/rest/rest_auth.go
plugins/rest/rest_test.go

Prepare v0.23.1 release

---

CHANGELOG.md

CHANGELOG.md: Add v0.23.1 release note

---

CHANGELOG.md
Makefile
capabilities/v0.23.2.json
plugins/rest/rest.go

Prepare v0.23.2 release

---

CHANGELOG.md
capabilities/v0.23.1.json
capabilities/v0.23.2.json
docs/devel/RELEASE.md

CHANGELOG.md: Add v0.23.2 release note

---

ast/compile.go
ast/compile_test.go
ast/parser.go
ast/parser_ext.go
ast/parser_test.go

More fixes for panics caught during nightly fuzz

---

docs/content/management.md

fix spelling error

---

docs/content/extensions.md

docs: Add note about logs.EventV1 fields in extensions doc

---

docs/website/data/integrations.yaml

updated the Scalr integration title

---

docs/content/extensions.md
docs/content/rest-api.md

Signed-off-by: AlexsJones <alexsimonjones@gmail.com>
Spelling corrections in docs.
Regards

chore(spelling): fix spelling in extensions.md and rest-api.md docs

---

codecov.yaml

We were seeing too many false positives from the 'project' status
check. The 'patch' status check seems fine so leave that one alone for now.

build: Disable the 'project' status in codecov

---

docs/content/envoy-authorization.md

Updated envoy version and links. Updated service type and minikube commands to tunnel to the service for consistency across minikube versions and drivers
Signed-off-by: Peter Sullivan <pvsone@gmail.com>

docs/content: Update Envoy Authorization Tutorial

---

ast/compile.go
ast/compile_test.go

This commit fixes an issue similar to
e88579bfdae8fd6edd940915a2fb259ebdd21429: when a comprehension is
nested inside of a set or used as an object key, the rewriting needs
to be careful to make a copy of the set/object to avoid mutating the
elemenet/key in-place.
Fixes #2720

ast: Fix panic during local var rewriting

---

docs/content/editor-and-ide-support.md

Add link to new IDEA plugin

---

docs/content/management.md
plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

Store bundles under a specific sub-directory of the new working
directory (as the same directory may be useful in future for other
persitence features.) Also, update the docs to mention where the files
are saved to as this was unclear from the user's perspective.

plugins/bundle: Tweak bundle save directory

---

docs/content/security.md

docs: Mention that /metrics and /health are exposed on normal listener

---

docs/content/policy-language.md

docs: Add note about valid package syntax

---

CHANGELOG.md
capabilities/v0.24.0.json
version/version.go

Prepare v0.24.0 release

---

CHANGELOG.md
version/version.go

Prepare v0.25.0 development

---

plugins/logs/plugin.go
plugins/logs/plugin_test.go
plugins/plugins.go
runtime/runtime.go

..re-attempting until either the graceful shutdown period is over or all logs have been uploaded.
Fixes #780

Flush buffered decision logs on graceful shutdown

---

docs/content/_index.md

Fixes a minor typo in the [Introduction page](https://www.openpolicyagent.org/docs/latest/) of the OPA docs.
Change statement from "language that let’s you specify policy" to
"language that lets you specify policy."

docs/content: Fix typo in Introduction page.

---

plugins/logs/plugin_test.go
runtime/runtime_test.go

Handful of fixups for some unit tests. See individual commits for details.
Fixes #2792

Unit test fixups
