topdown/cache/cache.go
topdown/cache/cache_test.go

Signed-off-by: vinhph0906 <vinhph0906@gmail.com>
I have found an issue in the [inter-query cache](https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go) package. Specifically, [this loop](https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go#L133) will drop items in the cache until the cache's size is smaller than the limits. But this loop run exactly once. This is because [removing the key](https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go#L136) will be set `key.Next()=nil`, then the loop break with `key == nil`. So I added code and a test case to fix this issue.

fix InterQueryCache Insert only drop one when size over limit

---

format/format.go
format/testfiles/test.rego.formatted
format/testfiles/test_fun_args_with_linebreaks.rego.formatted

Currently, all multiline expressions, such as:
```rego
every x in y {
...
}
```
```
foo = concat(
...
)
```
will have a blank line after them when `opa fmt` is applied.  I traced the bug down to `offset` being weirdly set to 0, and updated it to compute the number of lines in the last expression.
The existing `.formatted` tests contain many examples of when the lines should be consecutive, or when there should be a blank line inserted, so I feel like it doesn't need a dedicated test, but I'm happy to add one if you feel it necessary.

fmt: fix blank lines after multiline expressions

---

docs/content/rest-api.md

Tiny documentation update to correction details on performance metrics. Not all Policy APIs support metrics and adding compile.

doc update on performance metrics

---

topdown/json.go
topdown/json_test.go

This commit fixes a panic discovered in the `json.filter` builtin that could be triggered with an empty JSON path parameter, such as `""`. This panic was caused by indexing logic in a helper function always assuming it had at least one path segment to work with, and thus indexing out-of-bounds when no path segment was present.
The issue was fixed by adding an extra check to the helper function for the null path case, and adding new unit tests to check for the issue.
Fixes: #5199

topdown/json: Fix panic in json.filter on empty JSON paths.

---

docs/content/policy-language.md

we need to use future.keyword**s**.* to import a future keyword as written in [every keyword section](https://www.openpolicyagent.org/docs/latest/policy-language/#every-keyword), right?

Fix typo in Future Keywords document

---

docs/content/integration.md

Add IR to integration docs

---

test/cases/testdata/rand/test-rand.intn.yaml

It looks like we didn't have any before. While it's inherently random, we still know that for the same inputs, within a single evaluation run, we should only get one output. So let's assert that.

test/cases: add test case for rand.intn

---

config/config.go
docs/content/configuration.md
docs/content/management-decision-logs.md
plugins/logs/mask.go
plugins/logs/plugin.go
plugins/logs/plugin_test.go
rego/rego.go
rego/rego_test.go
runtime/runtime.go
sdk/opa.go
sdk/opa_test.go
server/buffer.go
server/server.go
topdown/builtins/builtins.go

This PR integrates the non-deterministic builtins cache (introduced in #4926) into the OPA server and SDK, ensuring that the cache's contents are added to the decision logs generated by the decision logging plugin when the `nd_builtin_cache` key is set to `true`.
Fixes: #1514
-  ~~Should we be silently dropping the `nd_builtins_cache` key from DL entries when they are too large? Could we use the `Error` field to perhaps signal that all is not well? Is there maybe an out-of-band logging system that could be used?~~
(EDIT: @ashutosh-narkar suggested logging + a metrics counter, and I have implemented this in my latest changeset.)
- `sdk.Opa.Partial` has no support for the ND builtins cache, because partial evaluation will not run the ND builtins, as of #5172, and #5175 merging. I am fairly …

server+plugins: Integrate server + NDBCache in decision logs.

---

.trivyignore

.trivyignore: drop wasmtime-go

---

plugins/bundle/plugin_test.go
repl/repl_test.go
storage/disk/config_test.go
test/authz/authz_bench_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatalf("unexpected error %v", err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

docs/content/policy-reference.md

The semantic versioning format that the `semver` builtins accept isn't really documented anywhere, so I have added an example to the Policy Reference docs to cover it.

docs/policy-reference: Add semver examples.

---

.github/workflows/codeql-analysis.yml
.github/workflows/nightly.yaml
.github/workflows/post-merge.yaml
.github/workflows/post-tag.yaml
.github/workflows/pull-request.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

workflow: use GITHUB_OUTPUT, not ::set-output

---

ast/capabilities.go
ast/compile.go
ast/compile_test.go
capabilities.json

This allows us to guard the use of ref heads through capabilities. If we're given a caps file without
the proper feature enabled, and a policy file with ref head rules, this check will fail.
We can thereby ensure that a policy (bundle) works with a certain older version of  OPA that does
not know ref heads.
Similar features would be added for the follow-up steps: general refs `p[x].q[y].r = ...`; or package-less rego files.

ast: check caps for ref rules

---

ast/compile.go

This fixes this crasher, identified by the nightly fuzz run:
package A
A0 {
A(0).A(0)
}
👉 https://github.com/open-policy-agent/opa/actions/runs/3258760618/jobs/5351087330#step:6:7

ast/compile: don't lookup Call TreeNode children

---

internal/planner/planner.go
test/cases/testdata/refheads/test-regressions.yaml

The compiler ensures that all the keys we see there are scalars. For strings, nothing changes -- they're handled just like before -- but this now also allows numbers and booleans.
An example policy that exploded with a panic before is
package p
a[0] = true
when querying the full extent of `data.p` or `data.p.a`.
Fixes #5252.

planner: when planning a ref's extent, plan the keys as values

---

test/cases/testdata/globmatch/test-globmatch-issue-5273.yaml
topdown/glob.go

This PR resolves the issue discussed in #5273 where a deferred mutex unlock could result in evaluation deadlocking.
Fixes: #5273

topdown/glob: Fix deferred mutex unlock issue.

---

.github/workflows/nightly.yaml
.github/workflows/pull-request.yaml
.trivyignore
Makefile
build/docs-build-needed.sh
docs/website/scripts/live-blocks/package-lock.json

Please see the individual commits, testing locally, I get no findings anymore:
```
$ trivy fs . --security-checks vuln --skip-dirs vendor/,internal/gqlparser/validator/imported/
2022-10-21T10:17:03.233+0200	INFO	Vulnerability scanning is enabled
2022-10-21T10:17:03.363+0200	INFO	Number of language-specific files: 4
2022-10-21T10:17:03.363+0200	INFO	Detecting gomod vulnerabilities...
2022-10-21T10:17:03.367+0200	INFO	Detecting npm vulnerabilities...
```

nightly: address recent findings

---

ast/index.go
ast/index_test.go
test/cases/testdata/globmatch/test-globmatch-issue-5273.yaml
test/cases/testdata/globmatch/test-globmatch-issue-5283.yaml

We had been taking care of this case for equal(), but not for glob.match.
Now, we'll get the correct results for this policy, with and without indexing:
package play
p = x {
x := glob.match("/a/*/c", ["/"], input.path)
}
Fixes #5283.

ast/index: skip indexing if glob.match output is captured

---

ast/annotations.go
ast/parser.go
cmd/build.go
cmd/build_test.go
cmd/eval.go
cmd/eval_test.go
cmd/inspect.go
compile/compile.go
compile/compile_test.go
docs/content/annotations.md
docs/content/cli.md
docs/content/wasm.md
internal/runtime/init/init.go
internal/runtime/init/init_test.go
runtime/runtime.go

This PR implements basic support for entrypoint rule/package annotations in Rego. This feature means that optimized bundle builds, WASM, and Plan target compilation all no longer require a CLI argument for the entrypoint, so long as at least one rule was annotated as an entrypoint in the policies provided.
Fixes: #3459
-----
Remaining Work:

ast+compile: Support entrypoint annotations

---

test/e2e/http/http_test.go
test/e2e/testing.go
topdown/http.go
topdown/http_test.go

When force_cache is true, do not use the Date header set by the server as the value to use for TTL initialization, but rather create it from the current instant.
* Rename all current interQuery* tests to intraQuery*
* Add e2e test cases for forced http.send interQueryCaching
Fixes #4960

Ensure force_cache attribute ignores Date header

---

.github/workflows/pull-request.yaml

This should get us rid of the node 12 warning.

ci(pull-request): setup-opa@v1 -> setup-opa@v2

---

ast/builtins.go
builtin_metadata.json
capabilities.json
test/cases/testdata/netcidrisvalid/test_netcidrisvalid-0001.yaml
topdown/cidr.go
topdown/cidr_test.go

Allows for users to verify if a given string represents a valid network CIDR. To do the same thing through `regex` can get very complex to maintain over time and to use `net.cidr_expand` for the same purpose can take a lot of time.
The function works as follow: 
```
valid {
net.cidr_is_valid("192.168.0.0/24")
}
```
To parse IPv6 CIDRs is also supported.

cidr_is_valid: add function to validate network cidr

---

ast/visit.go
compile/compile_bench_test.go
types/types.go

This PR is intended to address some of the performance issues brought to light in issue #5216.
The Compile API's performance nosedives surprisingly quickly when working with large policy sets (>10k policy files), especially when policy selection at the top-level depends on a `Ref` type (such as something from the `input` document).
- New benchmark for the `compile` package (just builds a large policy set, attempts to run `Build()` on them)
- Optimizations to the type checker (a linear scan switched to binary search, 3-5x speedup for benchmark)
- Miscellaneous for loop optimizations in `ast/visit`, resulting in a 10-15% memory usage improvement.
- **Result**: This is caused by excessive slice copying in the [`Merge` function](https://github.com/open-policy-agent/opa/blob/f7ee81577cac1d0d563 …

compile+types: Speed up typechecker when working with Refs

---

internal/strvals/parser.go
internal/strvals/parser_test.go

The impact of this in OPA is minimal: when passing for example
--set "abc[9999999999999]=123"
to `opa run` or `opa exec`, it would run out of memory. With this change, it will return an error instead:
$ opa exec --set "abc[9999999999999]=123" .
{"err":"config error: failed parsing --set data: index of 9999999999999 is greater than maximum supported index of 65536",
"level":"error","msg":"Unexpected error.","time":"2022-10-27T10:24:01+02:00"}
Since these parameters are never user-controlled, or accessible at runtime, any attack vector here involves having access to a machines CLI, and is thus equivalent to already having local user rights. The affected instance of OPA would be the instance that is started -- so no others would be affected.
Thanks to @pjbgf for bringing this up.
See also …

internals/strvals: port helm strvals fix

---

topdown/http.go
topdown/http_test.go

In order to calculate if a cached entry expired or not, we would previously read the headers stored with the request, and parse each of the relevant date-related ones and use those to compare with the current time. #4960 improved this by allowing us to ignore the Date header completely when force_cache is enabled.
We now go one step further, and calculate and store an expiresAt value at the time the entry is created. This allows for a much simpler check of expiry, and avoids re-parsing the header values with each lookup.
Fixes #5300

Improve caching logic for http.send

---

ast/compile.go
ast/compile_test.go
docs/content/policy-language.md
internal/planner/planner.go
internal/wasm/sdk/test/e2e/exceptions.yaml
test/cases/testdata/withkeyword/test-with-builtin-mock.yaml
test/cases/testdata/withkeyword/test-with-function-mock.yaml
test/cases/testdata/withkeyword/test-with-function-mocks-issue-5299.yaml
topdown/eval.go

Before, this was OK:
test_a {
. mock_f := true
allow with f as mock_f
}
but this had panicked:
mock_f := true
test_a {
allow with f as mock_f
}
Which, from a user perspective, is quite incomprehensible. Technically, the first snippet was a (supported) replacement-by-value, and the second was an unsupported replacement by a rule that was not a function.
Furthermore, the second case wasn't properly caught in the 'with' validations.
Now, we'll capture the situation, and start supporting it. Both snippets will now work the same, as one would expect from the language surface.
Fixes #5299.

ast/compile: rewrite ref-replacements with non-function values

---

.golangci.yaml
bundle/bundle.go
cmd/test.go
download/oci_dowload.go
internal/compiler/wasm/wasm.go
internal/config/config_test.go
internal/gojsonschema/validation.go
internal/jwx/jwk/symmetric_test.go
internal/oracle/oracle_test.go
internal/prometheus/prometheus_test.go
internal/wasm/encoding/writer.go
internal/wasm/sdk/internal/wasm/vm.go
internal/wasm/sdk/opa/loader/http/util.go
plugins/logs/encoder.go
profiler/profiler_test.go
runtime/runtime.go
storage/errors.go
test/e2e/certrefresh/certrefresh_test.go
topdown/builtins.go
topdown/cache/cache.go
topdown/regex.go
topdown/strings.go
topdown/tokens.go

Got a few warnings from my IDE about redundant type conversions, so I decided to look into it. Added the unconvert linter to our checks, and fixed the violations. Added two ignore comments as I wasn't sure about whether they'd change the semantics of the code.

linters: add unconvert

---

ast/builtins.go
builtin_metadata.json
capabilities.json
test/cases/testdata/graphql/test-graphql-schema-is-valid.yaml
topdown/graphql.go

This commit adds a new GraphQL builtin for validating GraphQL schemas, applying stronger validation rules than what the current GraphQL parsing builtins apply by default.
Fixes: #5125

ast+topdown: Add `graphql.is_schema_valid` builtin.

---

bundle/bundle.go
cmd/build_test.go
cmd/check.go
cmd/check_test.go
cmd/parse.go
compile/compile.go
internal/runtime/init/init.go
internal/runtime/init/init_test.go
loader/loader.go
runtime/runtime.go

Before, the capabilities were plumbled through in most places:
1. checking which builtins exist
2. passed along to the optimizer
3. passed along to the planner
But they hadn't been passed along to the file loader. As such, it could not pass the caps along to the parser either. This is now done, but adding a new method to the FileLoader interface.
Fixes #5323.

cmd/{build,check}: respect capabilities for parsing

---

cmd/bench.go
cmd/bench_test.go

Currently the e2e bench mode doesn't support providing an OPA configuration to enable features like decision logging that can have an impact on the server overhead. This change adds a new flag to the bench cmd to specify the OPA configuration.
Fixes: #4899

cmd: Extend e2e benchmarking mode to include OPA config

---

docs/website/layouts/partials/docs/article.html
docs/website/layouts/partials/docs/dashboard-panel.html
netlify.toml

If a release is not among the last five releases, the "you're using an outdated version" banner will turn red.
You cannot see the effect in the deploy preview, but I've verified it locally:
-------

docs/website: make "outdated version" banner red if ancient

---

cmd/build.go
cmd/build_test.go
cmd/sign.go

Since `alg` has a default setting, we've gotten that error too often.
Follow-up to #5297 and #4972.

cmd/build: don't expect key if alg is non-empty

---

docs/content/policy-testing.md

docs/policy-testing: don't advise to "import future.keywords"

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.46.0.json
version/version.go

👀 please review the release notes

Prepare Release v0.46.0

---

.github/workflows/pull-request.yaml

The other one was broken; let's see what's going on here. Maybe it was related to the action used, maybe not...

ci/pull-request: change action used for wasm filter

---

topdown/copypropagation/copypropagation.go
topdown/topdown_partial_test.go

CP works as follows, it removes a bunch of questions (details omitted), and then re-adds them if they provide safety for some variable, or if they introduce refs and values that aren't "contained" in the existing body.
For that second part, checking containment, the code looked at all refs (all terms), regardless of whether they're in comprehensions or not.
Now, in the specific case,
p {
{ 1 | input.foo} # <-- present already
_ = input.foo    # <-- required?
}
the fact that `input.foo` is in the body already doesn't make the second expression any less meaningful: if `input.foo` is undefined, the comprehension would just be empty. For `p`, however, adding the second line makes a big difference.
Now, we'll skip comprehensions when checking if a previously-removed equation should be …

topdown/copypropagation: skip comprehensions when checking eqs

---

docs/content/comparison-to-other-systems.md

The permissions table wasn't matching the decisions table and sample rego for the RBAC example--thanks!!

[Nit] Small doc fix for the RBAC example in the comparison page

---

format/format.go
format/testfiles/test_assignments.rego.formatted
format/testfiles/test_if_else.rego.formatted
format/testfiles/test_issue_5348.rego.formatted

This fixes a long-standing annoyance where:
```rego
allow {
input.user.name == "foo"
} else := false
```
Formats into:
```rego
allow {
input.user.name == "foo"
} else := false {
true
}
```

fmt: remove { true } block following else head

---

.github/workflows/nightly.yaml
.github/workflows/pull-request.yaml

Few people ever look at the output of this, and yet everyone has to wait for it. Let's change that.

ci: move performance to nightly tests

---

ast/compile.go
ast/compile_test.go

This commit improves the accuracy of reported locations for "unused var" errors, specifically when `some ...` is involved.
Fixes: #4238

ast/compile: More accurate error locations for `some` with unused vars.

---

ast/parser.go
ast/parser_test.go

The previous behaviour had triggered a check in the formatter for multiple use of wildcard variables:
f(_) := true { true }
else := false
The formatter found `$1`, the `_` argument of f, again in else, and thus changed it into `_1`:
f(_1) := true { true }
else := false
There's no extra meaning to the copied wildcards in `else`, they should not count as second usage.
Fixes #5347.
⚠️ It does not fix the case where a rewriting is necessary, and clashes with an existing var. But it makes the rewriting a lot less likely; and notably doesn't do it just because there is an `else` defined for a function.

ast/parser: generate new wildcards for else

---

ast/builtins.go
builtin_metadata.json
docs/content/policy-reference.md

This commit adds documentation and examples around one of the bigger "gotchas" in handling time values in OPA: parsing date formats.
The issue is that users of `time.parse_ns` have to use the same "reference timestamp" values as Go's `time/format` module does, which can be deeply surprising behavior to newcomers to the Go language, and to OPA users as well.
By documenting this, the hope is that we'll help users make fewer mistakes around parsing date formats in OPA.
Reference: https://cs.opensource.google/go/go/+/master:src/time/format.go;l=9-100

docs: Document reference timestamp behavior for `time.parse_ns`

---

topdown/cache/cache.go
topdown/cache/cache_test.go

This fixes the issue where concurrent requests with identical cache keys cause the interquery cache size `usage` counter to become invalid, as discussed [here](https://github.com/open-policy-agent/opa/issues/5359#issuecomment-1303618978)

#5359 Fix interquery cache concurrency bug

---

compile/compile.go
internal/compiler/wasm/wasm.go
internal/planner/planner.go
internal/planner/planner_test.go
internal/planner/rules.go
rego/rego.go

With the introduction of ref heads in #4660, the planned IR still mostly worked, but it was bypassing the CallDynamic optimization when it shouldn't have.
This commit re-works some of the rule planning to more robustly handle ref heads.
Also adds a few test cases to get a grip on what should and should not happen.

planner: fix ref heads processing

---

docs/website/edge/badge.ts
docs/website/layouts/index.redirects
netlify.toml

If this works out, one should be able to include
https://openpolicyagent.org/badge/v0.46.1
as an image, say, in a github README, and it'll look nicely.
Furthermore, when 0.46.1 will no longer be the latest version, it'll turn from green to yellow.

website: experiment with badge endpoint

---

docs/website/edge/badge.ts

Who would have thought that this would work on the first try? 😅 
👉  ![here it is](https://img.shields.io/endpoint?url=https://openpolicyagent.org/badge-endpoint/v0.46.1) 🤦

website/edge: fix badge function schemaVersion

---

ast/parser.go
ast/parser_test.go

There was a case that slipped through the parser, but failed at a later stage. It's now caught early.

ast/parser: fix else handling with ref heads

---

ast/builtins.go
builtin_metadata.json

I decided against documenting that a preceding slash is not required in paths, as that deviation from spec seems like a bad habit to promote. 
Fixes #5328

json.patch: update docs to include behavior with sets

---

ast/parser.go
ast/parser_test.go

This is a spiritual follow-up to #5412.
A policy like
f(_) := 1 { true } { true } { true }
would have been pretty-printed as
f(_0) := 1
f(_0) := 1
f(_0) := 1
because of the duplicated wildcards.
They now get the same treatment as "else" gets: fresh wildcards.

ast/parser: fresh wildcards for chained function heads

---

docs/content/integration.md

* Move Go SDK above Go API
* Modernize code example snippet

docs: update integration page

---

CHANGELOG.md
builtin_metadata.json
capabilities/v0.47.0.json
version/version.go

Prepare v0.47.0 release

---

sdk/opa.go
sdk/opa_test.go

This allows the struct builtin errors functionality to be used in the SDK by passing the value in DecisionOptions & PartialOptions.
Related to https://github.com/open-policy-agent/opa/issues/5176

sdk: allow use of StrictBuiltinErrors

---

docs/website/data/integrations.yaml
vendor/github.com/spf13/cobra/projects_using_cobra.md

Signed-off-by: David Wertenteil <dwertent@armosec.io>
The Kubscape project has been moved from the [armosec](https://github.com/armosec) org to the [kubescape](https://github.com/kubescape) org.
In this PR I updated the relevant URLs.

docs: Updating kubescape repo links

---

build/docs-build-needed.sh

this change itself will also trigger the website build, since it contains a change in `build/`.

build: add CHANGELOG.md to website build triggers

---

sdk/opa.go
sdk/opa_test.go

This PR exposes functionality to the callers of `opa.Decision` & `opa.Partial` allowing a tracer implementing `topdown.QueryTracer` to be passed.
Related to #5176 

sdk: Allow use of a query tracer

---

docs/website/layouts/index.html

Small updates to the Learn More links section on the OPA website front page:
Additions:
* Add OPA GitHub button
* The only GitHub link on the front page is currently in the non-sticky top nav bar. If a visitor reads through the entire page and wants to visit the OPA GitHub org, they would need to remember to scroll up to the top to find the link. Adding a link toward the bottom of the page makes is easier for the user to get to the OPA GitHub org, and the Learn More links section seemed to be a good spot for this.
* Additionally, some ad blockers (such as uBlock Origin with cosmetic filters enabled) block/remove any elements identified as "social links", which blocks the OPA Twitter, Slack, and GitHub icon links in the nav bar. Adding an additional, non-social GitHub link on the page …

website/frontpage: update Learn More links

---

.github/workflows/nightly.yaml

As of last night, we see this error -- reproducible locally:
```
$ go install golang.org/x/vuln/cmd/govulncheck@latest
go: golang.org/x/vuln/cmd/govulncheck@latest: no matching versions for query "latest"
```
with the env vars set to bypass the infrastructure, it'll work:
```
$ GOPROXY=direct GOSUMDB=off go install golang.org/x/vuln/cmd/govulncheck@latest
go: downloading golang.org/x/vuln v0.0.0-20221208180742-f2dca5ff4cc3
go: downloading golang.org/x/tools v0.4.0
```
So let's do that for now.

ci: temporary workaround for golang proxy/sumdb bug

---

.github/workflows/nightly.yaml

This reverts commit 44c78a9e7425390cf9d71f79bad5ac5d37efd4b1.
It's been fixed: https://github.com/golang/go/issues/57185

Revert "ci: temporary workaround for golang proxy/sumdb bug (#5463)"

---

sdk/opa.go
sdk/opa_test.go

This brings the sdk closer to feature parity with `opa eval` for metrics related functionality. Users can now set a `metrics.Metrics`, `profiler.Profiler` and enable instrumentation in `DecisionOptions` and `PartialOptions` alike.
Related to https://github.com/open-policy-agent/opa/issues/5176

sdk: Allow use of metrics, profilers, and instrumentation

---

internal/providers/aws.go
plugins/rest/aws.go
plugins/rest/aws_test.go
topdown/providers.go

This commit refactors the shared AWS Sig v4 signing code, specifically to prevent the issue behind #5472. The underlying problem for #5472 was that the `"Authorization"` header was being appended *twice* to the request, but only for the AWS REST plugin, because the value was pulled twice from the signed headers map.
This was not caught by the unit tests, because the REST plugin's unit tests all assumed the header was single-valued and canonicalized.
We now test for this exact condition in the unit tests, and the signing code now returns the AWS headers map separately from the value for the `"Authorization"` header, reducing the potential for this mistake to happen in the future.
Fixes: #5472

providers/aws: Refactor + fix 2x Authorization header append issue.

---

docs/content/configuration.md
docs/content/management-bundles.md

Signed-off-by: Omri Gazitt <ogazitt@gmail.com>
This PR corrects a couple of docs pages where the config for an OCI service used "schema" instead of "scheme" as a key.

corrected OCI config section docs

---

tester/runner.go
tester/runner_test.go

This commit fixes a panic from a utility function in the `opa test` codepath. After the ref-heads change in #4660, this particular function could be fed a ref that it didn't know how to work with, such as the innocuous line `a[0] := 1`, and it would then panic.
This was fixed by returning a dummy value instead of panic'ing.
Fixes: #5496

tester/runner: Fix panic'ing case in utility function.

---

topdown/cache/cache.go
topdown/cache/cache_test.go

I thought we could fix the leak in #5381 by keeping track of the elements in `c.l` and remove them from the list whenever the corresponding cache values are removed. Since `c.l` is already a doubly linked list it's possible to add this with very little 
changes and with O(1) complexity
I can add some tests if this looks otherwise OK

Fix interquery cache memory leak

---

ast/visit.go
ast/visit_test.go

These had been overlooked, it seems. Adjusted the test element counts for the new nodes getting recorded.
It seems like there's no test coverage for the deprecated ast.Walk() and ast.WalkBeforeAndAfter() methods.
Fixes #5480.

ast/visit: add SomeDecl to visitor walks

---

docs/website/layouts/partials/docs/navbar-link.html
docs/website/layouts/partials/docs/navbar.html
docs/website/layouts/partials/docs/sidenav-link.html
docs/website/layouts/partials/docs/sidenav.html
netlify.toml

In https://github.com/gohugoio/hugo/releases/tag/v0.93.0 the hugo project deprecated the .URL fields in favor of Permalink and RelPermalink fields.
In this PR I have updated the netlify hugo version and these fields.
I have done this since v0.88.1 is not available for arm Macs. I hope this will make it easier to work on the docs site.

Update Hugo version, update deprecated Page fields

---

ast/index.go
ast/index_test.go
topdown/eval.go

Previously, we'd end up iterating and checking all rules BEFORE index lookup. Now, the groundness check is moved into index creation time, where it only happens once, and is cheap to retrieve.

ast+topdown: move all-ground-refs check into index build

---

ast/check.go
ast/compile_test.go
ast/parser.go
ast/parser_test.go

Previously, we did not detect misuses of the `contains` keyword, which is only valid as a syntactic sugar for partial set definition rules.
This PR adds some logic to detect when a function rule head has been paired with the `contains` keyword, which should generally be an error condition.
~~Note: We can't catch the following case, because the number of args is zero, and we can't distinguish `nil` from `[]` in Go.~~
EDIT: I was a smidge tired when I made the initial PR, and mixed up the nil rules in Golang around slices. It's `len()` that doesn't distinguish between `nil` and `[]`. Silly mistakes happen, even to the best of us. :sweat_smile: (Thanks for the correction, @srenatus!)
```rego
package test
p() contains x {
x := 1
}
q(a) contains x {
x := a
}
```
Fixes: #5525

ast/parser: Detect function rule head + contains keyword.

---

plugins/logs/plugin_test.go
rego/rego.go
sdk/opa_test.go
server/server_test.go

Fixes https://github.com/open-policy-agent/opa/issues/5511
This change will cause the operation to be timed if the store modules have already all been compiled and there are no rawModules. This might be undesirable. Updates to metric counts show the impact this has in our tested examples.

[rego] Check store modules before skipping parsing

---

Makefile

New base images don't contain openssl and are sourced from https://github.com/chainguard-images/images#chainguard-images.
I have also updated the static images to use their static base, though it is not impacted by the openssl issue.
Remaining to do, perhaps as part of this PR is to update the debug base images to something that doesn't contain openssl too. Currently there is no cc image in the chainguard collection that contains a busybox shell.

Update base images for non debug builds

---

test/cases/testdata/withkeyword/test-with-and-ndbcache-issue.yaml
topdown/eval.go
topdown/exported_test.go

Errors happening in the "cache hit" code path for NDBCache calls would come from the iterators called with the function call results retrieved from the cache. Now, these errors include the sentinel "early exit" errors, which would ordinarily be suppressed further up the call stack.
However, since the iter()-returned errors had been wrapped into topdown.Halt{}, they were not picked up by the suppression mechanisms.
Now, those iter-derived errors are no longer wrapped into Halt, and the code section that suggests that they should be has gotten a new comment explaining what's going on there.
To improve our blinds spots in testing, the Rego Yaml tests are now also run with NDBCache enabled. No further assertions are added, those are tested elsewhere, but it would have caught this problem. …

topdown: fix re-wrapping of ndb_cache errors

---

topdown/http.go
topdown/http_test.go

Currently if http redirects are enabled, we use the client's default redirect policy. We should instead check if the hosts http.send calls as part of the redirect are explictly allowed by the policy authors. This change updates the http client's CheckRedirect policy to verify the hosts the client calls when redirects are enabled.
Fixes: #5388

topdown: Specify host verification policy for http redirects

---

cmd/eval.go
cmd/eval_test.go

Earlier we were appending the address of the iterator variable to the slice. This results in unintended behavior of appending the same address to the slice. We fix this by copying the loop variable into a new variable and then appending.
Ref: https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable

cmd: Copy the loop variable into a new variable

---

docs/content/policy-language.md

This change fixes the spelling of a misspelled word found in the `Policy Language` documentation.
In `docs/content/policy-language.md`, a misspelled word forbdiden has been corrected to forbidden, [following Merriam-Webster's spelling of the word](https://www.merriam-webster.com/dictionary/forbidden).
Attached below is a screenshot of the word's location in the `future.keywords.contains` section on the `Policy Language` docs page.

Fix: Correct the spelling of forbidden on the Policy Language documentation page.

---

ast/parser.go
ast/parser_test.go

* Properly divine Rego location for yaml unmarshal errors
* Error hint for cases where non-legal space is used with yaml key/value separator `:`
Error message is augmented with a hint if the problem _could_ be a whitespace issue.
E.g. executing the following policy with `opa eval -f pretty -d policy.rego 'data.test'`
```rego
package test
p := rego.metadata.rule()
```
will spawn the following error message:
```
1 error occurred: /Users/johan/tmp/non-breaking_whitespace/policy.rego:5: rego_parse_error: yaml: line 3: could not find expected ':'
Hint: on line 5, symbol(s) ['B'] immediately following a key/value separator ':' is not a legal yaml space character.
```
Fixes: #4475

ast: Improving error information when metadata yaml fails to compile

---

types/types.go

Fixes https://github.com/open-policy-agent/opa/issues/5582
It is the intended behavior that nested named types are not allowed.
This PR adds GoDoc to `types.Named` and `types.NamedType` to avoid confusion.

types: Add GoDoc about name types

---

build/binary-smoke-test.sh
bundle/file.go
test/cli/smoke/.manifest

Signed-off-by: harikannan512 [harikannan512@gmail.com](mailto:harikannan512@gmail.com)
New PR opened to undo signed commit errors in the preovious PR
Command used:
Win: ./opa.exe inspect C:\sample_opa\opa_inspect\ -f json
Mac: ./opa inspect ~/Downloads/opa_inspect/ -f json
Resolves:
https://github.com/open-policy-agent/opa/issues/5503
Before:
`error: bundle Z:\sample_inspect_bundle: manifest roots [a/b/c a/b/d play play2] do not permit data at path '/Z:' (hint: check bundle directory structure)`
After:
```
{
"manifest": {
"revision": "",
"roots": [
"a/b/c",
"a/b/d",
"play",
"play2"
]
},
"signatures_config": {},
"namespaces": {
"data.a.b.c": [
"C:\\sample_opa\\opa_inspect\\authz.rego",
"C:\\sample_opa\\opa_inspect\\authz3.rego"
],
"data.a.b.d": [
"C:\\sample_opa\\opa_inspect\\authz2.rego" …
```

fix prefix error in `opa inspect` for bundle from root

---

docs/website/assets/sass/docs.sass
docs/website/layouts/partials/docs/article.html
docs/website/layouts/partials/docs/banner-version-warning.html
docs/website/layouts/partials/docs/dashboard.html

We have issues were some old pages still rank in search engines. This change is intended to make it clearer to users who land on the docs from such results that they are viewing outdated version of the docs.
https://user-images.githubusercontent.com/1774239/214556730-58a56ea8-108f-43c6-874a-4afe35a1ef80.mov

Show prominent warning when viewing old docs

---

server/server_test.go
server/writer/writer.go
test/e2e/distributedtracing/distributedtracing_test.go

When sending JSON back to the client — and we do a lot of that, use the streaming implementation of json.Encode rather than marshalling the data into an intermediate byte array.
One curious detail here is that the streaming implementation uses newlines to mark the end of the stream, so a few unit tests had to be updated to expect this. Previously we would only emit a trailing newline if "pretty" was configured.
Signed-off-by: Anders Eknert <anders@styra.com>

perf: use json.Encode to avoid extra allocation

---

docs/website/assets/js/app.js
docs/website/assets/sass/docs.sass
docs/website/layouts/partials/docs/banner-version-warning.html

Responding to feedback on https://github.com/open-policy-agent/opa/pull/5592 in the OPA slack. https://openpolicyagent.slack.com/archives/C02L1TLPN59/p1674674181401449
https://user-images.githubusercontent.com/1774239/214808668-39fa6fc2-790e-49e4-bedd-54e55dd56f7a.mov
'ancient' version banners cannot be dismissed.

Make warning banner closeable, edge banner is more understated

---

README.md

This is required since we moved the slack signup and the image is now 404ing.
We have links to the OPA slack prominently elsewhere in the readme.

Remove slack badge

---

docs/website/assets/sass/custom.sass
docs/website/assets/sass/docs.sass
docs/website/layouts/docs/section.en.html
docs/website/layouts/docs/single.en.html

There seems to be some feature of tocbot which changes the behavior of the menu based on its size.
I have also fixed the nav as the page scrolls so search is more readily accessible.
A horizontal scroll bar is also present to allow full built-in table contents to be viewed on narrow screen sizes. These are currently clipped.
Comparison showing browsable toc fix:
https://user-images.githubusercontent.com/1774239/215470841-a20c109b-24aa-4591-b457-60fad6ed9515.mov
Comparison showing fixed (sticky) nav while scrolling:
https://user-images.githubusercontent.com/1774239/215470885-f0c18cae-ef63-4e74-afc6-d0e54fbabe7c.mov
Comparison showing table clipping bug and h scrolling:
https://user-images.githubusercontent.com/1774239/215470896-ae6d896e-cc8a-4 …

Fix tocbot 100vh issue and fix navbar

---

docs/content/graphql-api-authorization.md

Note: This PR is a resubmission of the content of #5528, since the original author could not be reached for DCO signoff.
-----
This commit fixes a typo in the GraphQL tutorial, and changes the `optional` ID field to `required`, to better mimic real world usage.
Corresponding PR in the tutorial code repo: StyraInc/graphql-apollo-example#2
Original author: @dreglad (in PR #5528)

docs/graphql: non-nullable id argument and typo fix.

---

ast/index.go
test/cases/testdata/eqexpr/test-eqexpr-0599.yaml

Earlier the trie's scalar used map[ast.Value]trieNode. This resulted in unexpected key comparison results such as 1 != 1.0 when key types were ast.Number for example. This change updates the scalar to use a util.HashMap instead that will utilize ast.Compare to perfom key comparisons.
Fixes: #5585

Update rule index's trie node scalars to use custom map

---

docs/content/policy-reference.md
topdown/http.go
topdown/http_test.go

Currently http.send caches all responses. Now if the response had a status code of `500`(Internal Server Error ) for example, it's possible OPA will return a reponse from the cache for the next query. This can have unintened consequences as OPA will keep serving the cached response till it's fresh while at the same time it's possible the server has a proper response available. To avoid such as scenario this change updates the caching behavior to take into account the status code of the HTTP response before inserting a value into the cache. The list of status codes that can be cached is per https://www.rfc-editor.org/rfc/rfc7231#section-6.1.
Fixes: #5617

topdown: http.send to cache responses based on status code

---

Makefile

Following the workaround mentioned here: https://github.com/docker-library/golang/issues/452#issuecomment-1418911800
It's not beautiful, but since we're trying to get a release out the door -- let's unblock things and clean up later.

ci: pin golang image

---

logging/logging.go
logging/logging_test.go
server/server.go

Just a small cleanup in the server handler code. Ctx is for request-scoped data, so let's put the decision ID there, too.
Our Eval and Log helper methods have way too many arguments already.

server: pass decision_id via ctx, cleanup RemoteAddr -> RequestContext.ClientAddr

---

server/server.go

Similar to how https://github.com/open-policy-agent/opa/pull/5596 allowed streaming JSON from the response, do the same for the request. This has potentially bigger benefits, as the incoming request is commonly larger than the response (admission control, terraform, etc).

perf: stream JSON in request body

---

repl/repl.go
repl/repl_test.go

This PR fixes #5229. As noted by @burnerlee, to fix the issue it is necessary to avoid that arguments of command processed by [this line of code](https://github.com/open-policy-agent/opa/blob/50d4e31d6b41382f8fa4d29f8be30b6974e4da74/repl/repl.go#L1357) are converted to lower case.
@srenatus suggested an approach in which only the actual command is converted to lower case, while the arguments (in the case of the issue a file path) are not touched.
This PR realizes the proposed fix. In addition to that, the comment mentioning the fixed issue in the test [TestDumpPath](https://github.com/Trolloldem/opa/blob/9f700a7651e6a6c2c992ee9d743d3b5dd37c01bb/repl/repl_test.go#L277) has been removed and a new test called [TestDumpPathCaseSensitive](https://github.com/Trolloldem/opa/blob/9f700a7651e6a6c2c …

repl: only use ToLower on the input command

---

docs/website/config.toml
docs/website/layouts/partials/docs/article.html
docs/website/layouts/partials/google-analytics.html

- Closes #5384
- I've kept the `docs/website/layouts/partials/google-analytics.html` shortcode and updated it in case you ever decide to opt out of Netlify snippet injection. If you prefer, I can drop the shortcode too.
- Note that the UA ID is connected from the GA4 ID, so it will _continue to receive events_, until Google terminates support for UA
/cc @srenatus

Drop Google Universal Analytics (UA) code

---

topdown/json.go
topdown/json_bench_test.go

Now that #5494 has landed, this PR should be ready-for-merge! :smile: 
What follows below is the original PR text:
-----
This PR is an investigation (and hopefully remediation!) of performance issues around [`json.patch`](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-object-jsonpatch), triggered by the report in #4409, which actually is for a different subsystem. Based on preliminary findings, and a simple benchmark, the performance is not great, and has room to improve. Algorithmic improvements here *may* be useful as a blueprint for improving `PATCH` operations in the server as well.
To be able to dig into the performance issue here, I first constructed a Golang benchmark test that ensures `json.patch` is run in a very simple policy.
The patch list and source …

builtins: `json.patch` benchmark + rework

---

plugins/discovery/config.go
plugins/discovery/config_test.go
plugins/discovery/discovery.go
plugins/discovery/discovery_test.go

I ran into this error while working on https://github.com/open-policy-agent/opa/pull/5687
```
$ opa run -s --config-file=config.yaml
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-03-01T16:25:09Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101614e50]
goroutine 1 [running]:
github.com/open-policy-agent/opa/plugins/discovery.(*Discovery).loadBundleFromDisk(...)
/Users/charlieegan3/Code/opa/plugins/discovery/discovery.go:252
```
When using this config:
```
services:
example:
url: http://localhost:8080
discovery:
service: example
resource: /configuration/example/discovery.tar.gz
persist: true
```
To address this I have wrapped the problematic uses of …

[discovery] Catch missing discovery bundle name

---

docs/website/config.toml
docs/website/layouts/partials/css.html
docs/website/layouts/partials/docs/navbar.html
docs/website/layouts/partials/javascript.html

Hey! :wave: 
This PR is to update from the legacy (now unsupported) Algolia v2 to the new v3 :partying_face: 
As its not fully working yet I have marked it as [WIP] and as you can see there are still some debugging stuff in there to help get this over the finish line :sweat_smile: 
Right now I think there is an issue with the `{{ apiKey }}`, when you check the console after trying to make a search you get some `403`s
Thanks! :muscle: 
Thanks!

Updating DocSeach to v3 from v2

---

internal/prometheus/prometheus.go

Add a simple endpoint (`/metrics/alloc`) to quickly show memory utilization of OPA. This can be done via e.g. Prometheus already, but having a human friendlier interface for this is nice. 
```shell
$ opa run -s https://bundles.example.com/my-big-bundle.tar.gz
```
```shell
$ curl 'localhost:8181/metrics/alloc?pretty=true'
3.3GB
```
Without the `pretty` query string, the raw number of bytes is shown. I'm considering whether the pretty format should be the default, and something like `format=raw`, or `pretty=false` should be the option to show bytes, as that's likely less useful to a human operator. Ideas on that would be appreciated.
NOTE: There's a slight discrepancy between what Go reports and what top and other programs do (Go reports less memory used), but I think this is good enough …

Add metrics/alloc_bytes for showing memory allocated

---

docs/website/layouts/partials/docs/navbar.html
docs/website/layouts/partials/javascript.html

Hey Team :wave: 
I noticed after #5706 that the old search bar still appears in the Nav-bar.
This PR should hopefully address this issue, I also removed the `window.onload` function because I don't think it's needed, it should just load Algolia and not wait for the window to load.. but open to discussing this!
Thank you!

Old Search Box still appearing in UI (After Algolia Upgrade)

---

CHANGELOG.md
Dockerfile
Makefile
docs/content/graphql-api-authorization.md
docs/content/http-api-authorization.md
docs/content/kafka-authorization.md
docs/content/kubernetes-tutorial.md
runtime/check_user_linux.go

Currently all OPA image variants except "rootless" use
uid/gid 0 (i.e. root). Per container security best
practices it is better to run as non-root. So now OPA
defaults to non-root uid/gid in images. If root user
if needed, it can be explicitly set.
The "rootless" image variant is no longer needed and
will be not published in future releases.
Also currently the debug variant is published
for `linux/amd64` platform. For `linux/arm64` only static
images are generated. The debug variant can be useful
for debugging purposes and hence this change adds that
to the static image which can then be used on amd64 and arm64 arch.

Update OPA images to use non-root uid/gid by default 

---

docs/website/config.toml

The base URL is used to generate Permalinks in hugo:
https://gohugo.io/content-management/urls/
We then use page permalinks to generate the canonical URL:
https://github.com/open-policy-agent/opa/blob/09f1724270abe9b17a440c035d3837303688e268/docs/website/layouts/partials/meta.html#L47
This causes issues for the algolia crawler since www.openpolicyagent.org is the domain used in there, and not openpolicyagent.org.
Given that we don't seem to use it either:
```
$ curl -I https://openpolicyagent.org/docs/v0.43.1/policy-language/
HTTP/2 301
location: https://www.openpolicyagent.org/docs/v0.43.1/policy-language/
...
```
I think it makes sense to update this to www. This is being done as follow on from: https://github.com/open-policy-agent/opa/pull/5706

[docs] Use www domain for site base URL

---

plugins/logs/plugin.go

Since a cache was created per request, this did not work as intended. As it's unlikely that http.send is used in decision log drop/masking decisions, it should be alright to leave this out until this is requested, if ever.

decision logging: remove unused inter-query cache setup

---

docs/website/layouts/partials/docs/banner-version-warning.html
docs/website/layouts/partials/meta.html

This PR fixes two issues:
Firstly, I'm not sure when this slipped in but we see this:
(see https://www.openpolicyagent.org/docs/v0.49.2/)
I think I have addressed this in cd5a83267ddbc27e1c14ac1c27e21f0e086b3877 by also checking the version against the latest semver from the releases data.
This also makes the following change to search. Revert https://github.com/open-policy-agent/opa/pull/5730. It was a mistake to conflate 0.49.2 and latest as being the same. I think that we want to have these as two separate facet values so they can be searched independently. Otherwise, unless we ignore latest docs urls from indexing, there will be duplicates on latest and 0.49.2 which is undesirable. We might in future want to only index the latest version of the docs, however, for now, I think it makes …

Fix docs banner and search configuration

---

docs/content/management-status.md
plugins/logs/plugin.go
plugins/logs/plugin_test.go
plugins/logs/status/status.go
plugins/status/plugin.go
plugins/status/plugin_test.go

Currently errors encountered during decision log uploads are logged. This change now includes these errors as part of status updates  which can be useful for the control plane to determine if OPA is having any issues while processing, uploading logs etc.
Fixes: #5637

plugins: Surface decision log errors via status API

---

ast/annotations.go
ast/annotations_test.go
ast/marshal.go
ast/marshal_test.go
ast/parser.go
ast/parser_ext.go
ast/policy.go
ast/policy_test.go
ast/term.go
cmd/parse.go
cmd/parse_test.go

Fixes https://github.com/open-policy-agent/opa/issues/3143
This is being done so that the json representation of an ast parse can
be used more easily by automated tools which need the location
information. This location information is verbose for human users of the
data and has until now been excluded from JSON representation.
This PR makes it possible to configure the JSON marshalling with some
options. However, the functionality of the OPA parse command has been
left mostly unchanged.
The only with the json output is that the fields are in a different
order:
```
diff --git a/new.json b/old.json
index 5b9504fa..0fb9d4f2 100644
--- a/new.json
+++ b/old.json
@@ -13,15 +13,6 @@
},
"rules": [
{
-      "body": [
-        {
-          "index": 0,
-          "terms": {
-            "type": …
```

[ast/opa parse] Support marshalling of all ast location data

---

ast/annotations.go
ast/marshal_test.go

Makes sure that `jsonOptions` are preserved in NewAnnotationsRef.

ast: preserve `jsonOptions` in NewAnnotationsRef

---

ast/compile.go
ast/compile_test.go

Check is relaxed from requiring all arguments to be used in _all_ of the function's else-separated bodies, to only require all arguments to be used in _any_ of the function's else-separated bodies.
Fixes: #5758

ast: Relaxing strict-mode check for unused args in else-branching functions

---

plugins/logs/mask.go
plugins/logs/mask_test.go

Reading the code, I couldn't bear the use of a JSON roundtrip to convert from one kind of struct to another.
```
$ benchstat main.out pr.out
goos: darwin
goarch: amd64
pkg: github.com/open-policy-agent/opa/plugins/logs cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
│  main.out   │               pr.out                │
│   sec/op    │   sec/op     vs base                │
MaskingNop-16                       4.779µ ± 2%   4.892µ ± 1%   +2.38% (p=0.009 n=10)
MaskingRuleCountsNop/1Rules-16      4.859µ ± 3%   4.868µ ± 1%        ~ (p=0.754 n=10)
MaskingRuleCountsNop/10Rules-16     5.047µ ± 3%   4.872µ ± 0%   -3.47% (p=0.000 n=10)
MaskingRuleCountsNop/100Rules-16    5.089µ ± 4%   4.846µ ± 1%   -4.78% (p=0.000 n=10)
MaskingRuleCountsNop/1000Rules-16   4.894µ ± 4%   4.905µ ± 3%        ~ (p=0.684 …
```

mask: don't rely on JSON roundtrip to convert structs

---

runtime/logging.go

The watch feature was removed ~2.5 years ago in
faab37c37ebd87a262118d4fc3fcc4a8bded4854 so it should be fine to remove the corresponding log message.

runtime: Remove deprecation warning for ?watch flag

---

ast/compile.go
ast/compile_test.go

Previously, vars in the rule head were only rewritten for the "primary" rule,
and not for else branches. This has been fixed by walking the head of each branch
and rewriting all vars found.
Fixes: #5771

ast: Fixing bug where comprehensions in rule else-heads weren't rewritten correctly

---

Makefile

This completes the work started in https://github.com/open-policy-agent/opa/pull/5540
Fixes https://github.com/open-policy-agent/opa/issues/5544
We can't use distroless since they don't have a nossl cc image: https://github.com/GoogleContainerTools/distroless/issues/1210
Chainguard have added this (-dev rather than :debug) to their image collection: https://github.com/chainguard-images/images/issues/187
Following advice here, using their busybox is the best replacement for `gcr.io/distroless/static:debug` https://github.com/chainguard-images/images/pull/368#issuecomment-1478221177

Update debug build base images to remove openssl

---

cmd/fmt_test.go
format/format.go

This PR fixes #5646. As discussed in the issue, `opa fmt` crashes when  a built-in function with a corresponding `Infix` is processed by the [writeCall](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L763) function. This is due to the fact that, previously to this PR, this function assumed that the number of arguments provided is exactly the expected number. Due to this assumption, when these functions are processed in `writeCall` with only one argument, `opa fmt` panics due to an unhandled `index out of range` error.
As noted in #5646, this is not the only issue caused by the assumption used in `writeCall`. Currently, if the number of arguments provided to built-in functions with a corresponding `Infix` is larger than the expected number, only the first two are …

fmt: report wrong arity for built-in functions

---

plugins/discovery/discovery_test.go
plugins/logs/encoder.go
plugins/logs/plugin.go
plugins/logs/plugin_test.go

Previously in #5732 we updated the decision log plugin to surface errors via the Status API. However in that change certain events like encoder errors and log drops due to buffer size limits had no metrics associated with them. This change adds more metrics for these events so that they can be surfaced via the Status API.
Fixes: #5637

plugins: Surface more decision log errors via status API

---

cmd/run.go
cmd/run_test.go
docs/content/security.md
runtime/runtime.go
runtime/runtime_test.go

Hey @anderseknert! :wave: 
This is for #5090 
It explains why you should use localhost if you do not intend to expose the opa server to services outside of the same machine.
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>
Still need to check about adding a message to the server but wanted to make sure the text here is okay.
Thanks a lot!

Update to Security Docs

---

docs/devel/RELEASE.md

To help minimize bugs and regressions in the stable
release and also give users early access to test out features
and bug fixes that will end up in the stable release.
This PR introduces the creation of a release candidate prior to the stable release.

docs: Document pre-release process

---

runtime/check_user_linux.go

Since all published OPA images now run with a non-root uid/gid, there is no need to publish the rootless image tag. Currently if the rootless variant is run, a log message at the Warn level is printed.
This change increaes the log level for that message to Error in order to make it more explict to stop using this variant in the future.

runtime: Increase log level for rootless img msg

---

bundle/bundle.go
internal/bundle/inspect/inspect.go
internal/bundle/inspect/inspect_test.go
loader/loader.go
loader/loader_test.go

Fixes https://github.com/open-policy-agent/opa/issues/5826
```
opa $ opa inspect bundle.tar.gz -f json -a
{
"manifest": {
"revision": "",
"roots": [
""
]
},
"signatures_config": {},
"namespaces": {
"data": [
"/data.json"
],
"data.example": [
"/example/policy.rego"
]
},
"annotations": [
{
"annotations": {
"scope": "package",
"title": "Example Package"
},
"path": [
{
"type": "var",
"value": "data"
},
{
"type": "string",
"value": "example"
}
]
},
{
"annotations": {
"scope": "rule",
"title": "Example Rule"
},
"path": [
{
"type": "var",
"value": "data"
},
{
"type": "string",
"value": "example"
},
{
"type": "string",
"value": "allow"
}
]
}
]
}
opa $ go run main.go inspect bundle.tar.gz -f json -a
{
"manifest": {
"revision": "",
"roots": [
""
]
},
"signatures_config": {},
"namespaces": {
"data": …
```

[ast/inspect] Fix issue with unset annotation data

---

docs/content/management-discovery.md
plugins/discovery/discovery_test.go
plugins/plugins.go

This PR addresses issue #5832 and allows to add labels to the OPA configuration via discovery. This unlocks use cases where labels that are irrelevant for discovery but useful either in policies, status updates or decision logs.  
The current silent dropping of labels from discovery is changed to only drop changes. Additional labels are accepted and added to the runtime configuration. Additions are always based on the bootstrap configuration, i.e. multiple discovery updates behave as if just the last has happened.

Allow adding labels via discovery

---

rego/rego.go
rego/rego_test.go

When having a rego compilation error that has only 1 error element the string "1 error occurred" is printed twice. For example from real usage:
1 error occurred: 1 error occurred: main.rego:2: rego_parse_error: unexpected package
I used type conversion in the parse function in order to avoid "1 error occurred" duplication when only 1 error occured.
The test I added demonstrates how to reproduce the bug
the squashed commit of https://github.com/open-policy-agent/opa/pull/5834

rego: Fix printing duplication when parse errors length is 1

---

ast/parser_ext.go
ast/parser_test.go
cmd/parse_test.go

Prior to this PR, when the AST information were serialized to JSON, rules expressed as discussed in #5790 included only the location of their value and not the one of the rule ref var itself. This was due to the fact that these type of rule is processed by the function [ParseRuleFromBody](https://github.com/open-policy-agent/opa/blob/main/ast/parser_ext.go#L135), which does not set the value of the [jsonOptions](https://github.com/open-policy-agent/opa/blob/main/ast/policy.go#L193) field of the `Rule` struct created.
This PR adds the code necessary to set the correct value of the `jsonOptions` field in the function [parseModule](https://github.com/Trolloldem/opa/blob/138687d635e84f97a5fa213201aa558014fca802/ast/parser_ext.go#L609) using the same approach employed for the `Rule` structs …

parse: include rule head location when requested

---

test/cases/testdata/providers-aws/aws-sign_req.yaml
topdown/providers.go

Before signing a reqest for AWS, we convert the headers which is an AST value to a Go map. Previously we weren't initializing the map which this change now does.
Fixes: #5841

topdown/providers: Init map to operate on headers

---

cmd/eval_test.go
docs/content/policy-performance.md
internal/presentation/presentation.go
profiler/profiler.go
profiler/profiler_test.go

The number of EVAL/REDO counts in the profile result are sometimes difficult to understand. This is mainly due to the
fact that the compiler rewrites expressions and assigns the same location to each generated expression and the profiler
keys the counters by the location. So users have no idea that multiple expressions may be contributing to the profile
result for a given line in the policy.
This change attempts to provide more clarity to the profile output by including the number of generated expressions for
each given expression thereby helping to better understand the result and also how the evaluation works.
In this change we add a new column to the profile output which indicates the number of generated expressions. The other
approach considered was to have multiple rows w/ same …

profiler: Add number of generated expr to profile o/p 

---

ast/builtins.go
builtin_metadata.json
capabilities.json
test/cases/testdata/cryptohmacequal/test-cryptohmacequal.yaml
topdown/crypto.go

Add crypto.hmac.equal built-in function to safelly comparing hashes generated by MD5, SHA-1, SHA-256 and SHA-512 hashing algorithms.
The built-in function is a wrapped for the function Equal of package crypto/hmac.
PR to complement [topdown: Add built-in HMAC functions](https://github.com/open-policy-agent/opa/pull/4100)
Add support to compare hashes generated by built-in functions from crypto.hmac.*
- crypto.hmac.* built-in functions doesn't have a function to apply constant-time comparison.
- crypto.hmac.equal wraps [go hmac.Equal](https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/crypto/hmac/hmac.go;drc=ea5d7cbc2644643331bd675b1ebdf0aaac7419f1;l=175)
- There are scenarios where a secret-key can be used to validate request information instead of a jwt token.
e.g.:
```rego …
```

topdown: Add built-in HMAC compare function

---

docs/content/rest-api.md

This updates the text for the compile API description to include some more details on how the Compile API can be used as well as a link to
https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4
This is being done in order to help users understand if this endpoint is suitable for their use cases.

Clarify use cases for Compile API

---

ast/compile.go
ast/compile_test.go

ast: Not allowing multi-value rules to have other rules in their extent

---

ast/compile.go
ast/compile_test.go

The compiler should disallow single-value rules to have other rules within their extent. Previously, the compiler would erroneously allow such overlaps, where the immediate "child" rule of a partial object rule in the rule tree was also a partial object rule. This condition is not expected during evaluation, which will result in a broken object merge.
Fixes: #5855

ast: Disallowing partial object rules to have other partial object rule within their immediate extent

---

docs/content/configuration.md
download/oci_download.go
download/oci_download_test.go
download/testharness.go
internal/config/config.go
internal/providers/aws/ecr.go
internal/providers/aws/ecr_test.go
internal/providers/aws/signing_v4.go
internal/providers/aws/util.go
plugins/rest/auth.go
plugins/rest/auth_test.go
plugins/rest/aws.go
plugins/rest/aws_test.go
plugins/rest/azure.go
plugins/rest/rest.go
plugins/rest/rest_test.go

This PR is an attempt to address solutions 2) and 3) of https://github.com/open-policy-agent/opa/issues/5553.
It mainly starts using the (now exposed) `Config.AuthPlugin()` function of the `rest` package in the [`download.OCIDownloader`](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.48.0/download#OCIDownloader). This allows it to use any [`HTTPAuthPlugin`](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.48.0/plugins/rest#HTTPAuthPlugin) that is defined in the `Config.Credentials` section and makes it much more consistent with behavior of the `download.Downloader` and potential other uses of the `rest` package.
`Config.AuthPlugin()` was only used internally in the [`Client.Do()`](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.48.0/plugins/rest#Client.Do) function to …

Use available auth plugins in OCIDownloader

---

ast/index.go
rego/rego_test.go

We perform groundness checks at index creation time and then include result of that in the indexer's result. Previously we did not set this value on the indexer's AllRules call as a result of which rule evaluation for complete rules would get skipped. This change updates the indexer's AllRules call to include the result of the groundness checks.
Fixes: #5857

ast: Set result of groundness check on indexer's AllRules func

---

bundle/bundle.go
bundle/bundle_test.go
bundle/file.go
bundle/filefs.go
compile/compile.go
compile/compile_test.go
internal/runtime/init/init.go
internal/runtime/init/init_test.go
loader/loader.go
runtime/runtime.go
util/test/tempfs.go

PR for Issue [Compile to intermediate representation (IR) from a filesystem](https://github.com/open-policy-agent/opa/issues/5833)
* Add support for filesystems when loading paths across the `bundle`, `compile`, `loader` and `init` packages
* Add `WithTestFS` helper to `test` package which supports using a disk-based or memory-based filesystem in testing
* Change all `compile` tests to test both a disk-based (original) and memory-based (new) filesystem
* Change some `filefs` tests  to test both a disk-based (original) and memory-based (new) filesystem
* The `bundle` package already has a `NextFile()` method for each supported loader - `dirLoader`, `dirLoaderFS` and `tarballLoader` - and this PR lifts how file paths are formatted in the returned file `Descriptor` into one method: …

Add filesystem support to load bundles from

---

docs/content/integration.md
sdk/options.go

docs: mention ID property of sdk.Options and its benefits

---

cmd/run.go
runtime/runtime.go
server/server.go

Currently if OPA listens on a Unix socket, the socket file is created with 755 permissions. So if OPA is deployed on k8s for example and the socket path is shared via a volume between pods, due to the default permissions, the socket will not be reachable for the caller. One way around this is to match the user id for the OPA and caller containers but that is not always possible.
This change adds a new flag to the OPA runtime that allows to configure the permission of the socket file. In the k8s scenario, if the file permission is updated to 777 for instance, the caller will be able to connect to OPA via the socket.
I have tested this change with OPA deployed on k8s listening on a UDS and verifying another pod cannot connect to if w/o the file permissions changed to 777. I am not sure how …

Add ability to configure Unix socket permissions

---

docs/content/monitoring.md
plugins/status/metrics.go
plugins/status/plugin.go
plugins/status/plugin_go1.17_test.go

Add OPA environment information Gauge to Prometheus metrics
Closes issue https://github.com/open-policy-agent/opa/issues/5852
Provides version of OPA in a Prometheus gauge for observability
A new Prometheus metric has been added that includes a constant label for the version of OPA.

Add OPA environment information Gauge to Prometheus metrics

---

test/e2e/wasm/authz/authz_bench_integration_test.go

Unblocking the post-merge workflow. We still need to fix the underlying issue.

test/e2e/wasm: Unblock benchmarks

---

ast/index.go
test/cases/testdata/indexing/array-any.yaml

I found an issue in rule indexing, and managed to reduce it to a fairly small example. The following Rego currently fails `opa test`:
```rego
package example
is_tuple(val) {
[_, _] = val
}
test_this_works {
is_tuple([1, 2])
}
test_this_doesnt {
is_tuple([1, ["foo", "bar"]])
}
```
[example of a failed job](https://github.com/open-policy-agent/opa/actions/runs/4960888899/jobs/8877020568?pr=5916)
By moving the `isScalar` check down we allow `_` here to match against non-scalars as well.
N/A
I added a test case in the general test cases which reproduces it.  I'm not sure if there should be a separate test in `ast/index_test.go`, and I couldn't figure out how to write a nice test for this there.

fix issue with _ matching in rule indexing for arrays

---

test/cases/testdata/jwtdecodeverify/test-jwtdecodeverify-missing-iss-while-required.yaml
topdown/tokens.go

jwt_decode_verify function has a bug that permits missing "iss" property of a token even when "iss" is required. This change fixes this bug - when "iss" property is passed as a constraint, a token with missing "iss" is not allowed.
Fixes #5850

fix: jwt_decode_verify missing iss while required

---

plugins/status/metrics.go
plugins/status/plugin.go
plugins/status/plugin_go1.17_test.go
plugins/status/plugin_test.go

if `Prometheus` was enabled on active config change; and unregistering collectors if disabled.
Fixes: #5918

status: Registering Prometheus Collectors on Status-plugin reconfigure

---

format/format.go
format/testfiles/test_issue_5537_with_comprehension.rego
format/testfiles/test_issue_5537_with_comprehension.rego.formatted
format/testfiles/test_issue_5537_with_ref.rego
format/testfiles/test_issue_5537_with_ref.rego.formatted

Prior to this change, the `fmt` command produced invalid code when applied to the rego files presented in #5537, due to the fact that parentheses are not handle correctly in these edge cases.
With the changes in this PR, the `fmt` command is now able to handle the edge cases that produce invalid code in output.
This PR adds check to the following two methods: [writeRef](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L733) and [writeComprehension](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L911). 
As discussed noted in #5537, these two methods are responsible of calling the [writeTerm](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L686). When used, these method automatically strips parentheses from the formatted test. …

fmt: fix `fmt` producing invalid code

---

build/generate-cli-docs/generate.go
internal/gojsonschema/validation.go
sdk/test/test.go
topdown/regex.go

We can use alternative functions/methods to avoid unnecessary byte/string conversion calls.
1. `(*regexp.Regexp).Match([]byte(<a string>))` -> `(*regexp.Regexp).MatchString(<a string>)` [^1]
2. `utf8.RuneCount([]byte(<a string>))` -> `utf8.RuneCountInString(<a string>)` [^2]:
3. `(*bytes.Buffer).WriteString(string(<a []byte>))` -> `(*bytes.Buffer).Write(<a []byte>)` [^3]
[^1]: https://pkg.go.dev/regexp#Regexp.MatchString
[^2]: https://pkg.go.dev/unicode/utf8#RuneCountInString
[^3]: https://pkg.go.dev/bytes#Buffer.Write

perf: avoid unnecessary byte/string conversion

---

rego/plugins.go
rego/plugins_test.go
rego/rego.go
rego/rego_test.go

The handoff point for plugins right now is the IR: that, the store, and the open transaction is passed to `PrepareForEval`.
Rego target plugins  aren't plugged in through the plugin manager machinery, and they don't need to be enabled via configs. They are more akin to custom builtins, which also become available right away after having been registered with the ast package.
In the future, another option would be to pass the Wasm bytes: we could then have a wasmtime-based plugin, and a wazero-based one.
* rego.EvalContext: expose a few fields
* ()*Rego).Compile() is only used by our wasm tests, and doesn't even make sense for the "rego" target. Not added to the plugin interface.
* In rego.New, we now only gather plugins once, and have the plugins decide if a target is for them or not. This …

rego: allow for extending the rego targets with plugins

---

topdown/query.go
topdown/query_test.go

Aborting query-eval if the compiler has errors

---

format/format.go
format/testfiles/test_issue_5798.rego
format/testfiles/test_issue_5798.rego.formatted

As noted in #5798, the `fmt` command panicked when rego files processed contained a comprehension written on multiple lines with comments in these lines. The issue contains an example of such comprehension.
This allows to handle such cases.
The only part of the code that is changed by this PR is the first check 
performed in [writeComprehension](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L917).  Instead of starting a new line only when the comprehension and the first term processed are separated by at least two rows, now only one row is necessary to start a new line. This avoids that the [insertComments](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L498) panics when writing the second comment.
In addition to this, a test case for this issue …

fmt:fix `fmt` panic in comprehension with comments

---

cmd/eval_test.go
cmd/test.go
cmd/test_test.go
tester/runner.go

To enable schema validation on `opa test` the same way that is supported today by `opa eval`
On `test.go`:
- added schema flag usage
- refactored `opaTest()` to allow it to be used by `tests_test.go`, which included the following changes:
- added **testCommandParams** to be a parameter
- added **error** to be returned in addition to the **exit code**
- moved **testParams** and **testCommand** initialization to be inside the init method (similar to how is in `eval` today)
On `tests_test.go`:
- fixed existing InlineSchema test to use `opaTest()` instead of the SDK (as requested by @johanfylling)
- added 2 new Json Schema test
On `runner.go`
- added annotation reading
On `eval_test.go`
- removed unnecessary `rego.metadata.rule()` line from rego contents to test inline schema to avoid …

Add schema flag to test

---

sdk/opa.go
sdk/options.go

The store to use in the SDK is currently hard-coded to be `inmem`. This change allows providing new implementations.

sdk: allow passing in a separate store implementation

---

internal/planner/planner.go
test/cases/testdata/planner-ir/test-call-dynamic.yaml

So the check introduced before was too broad: it aborted optimizations at the wrong spot -- the resulting plan didn't add up: path lengths used in CallDynamicStmt didn't match path lengths that the planned funcs had.
So, while this change looks like over-fitting (also to me), we're really trying to make test previous fix more specific.
Generally looking at that section of the planner, it feels like the intro of general refs would be a good moment to nuke and start over: the way that refs-with-vars are put into the ruletrie seems like the root cause of our trouble here.
Fixes #5964.

planner: adjust check introduced in #5839

---

test/cases/testdata/subset/test-subset.yaml
topdown/subset.go

fix: Fixing the issue of the object.subset method failing to correctly compare array relationships
relative issue：[#5968](https://github.com/open-policy-agent/opa/issues/5968)
1. modify arraySubset method，fixing the incorrect assignment of `superElem` and adding array boundary checks
2. add testcases for the code change
--bug=[#5968](https://github.com/open-policy-agent/opa/issues/5968)
PTAL

fix: Fixing the issue of the object.subset method failing to correctly compare array relationships

---

internal/config/config.go
plugins/plugins.go
plugins/rest/rest.go
plugins/rest/rest_test.go
topdown/http_test.go

Addresses #5967, adds the ability to configure distributed tracing options to plugin manager and rest client. 
This allows using an existing distributed tracing infrastructure that is used for the http built-in for bundle downloads without relying in OpenTelemetry. 
* Adds `tracing.Options` to the relevant places to configure bundle download tracing

Add tracing to bundle/discovery download

---

topdown/object.go
topdown/object_test.go

To fix a bug with `object.union_n` in which the nested objects would be mutated. Related issue: https://github.com/open-policy-agent/opa/pull/5975
When inserting a nested object from `other` to `obj`, instead of inserting the original object, make a copy and insert the copy instead to make sure the original nested object is not copied, and thus prevent the objects passed in from being mutated

Fix a bug with object.union_n in which the nested objects would be mutated

---

cmd/run.go
cmd/test.go
cmd/test_test.go
internal/pathwatcher/utils.go
internal/pathwatcher/utils_test.go
runtime/runtime.go
runtime/runtime_test.go

Similar to the watch mode available in OPA when run as a server, this change adds a watch mode in OPA test which
reloads the policy on file-system changes and re-runs the tests. The watch mode in OPA test could be useful for example in TDD of policies.
Some of the watch/fsnotify code has been pulled out in a new `internal` package and is now shared with the `runtime`.

cmd: Add support for watch mode in opa test

---

rego/rego.go
topdown/builtins.go
topdown/errors.go
topdown/errors_test.go

OPA currently doesn't support wrapping errors returned by builtin functions from the higher-level evaluation methods like `(*rego.Rego).Eval` or `(*opa.SDK).Decision`. Retrieving a specific error from a builtin would give more context to users of these higher-level APIs to handle errors related to custom builtin functions.
An example use case that this PR allows:
```go
result, err := opa.Decision(ctx, sdk.DecisionOptions{Input: input, Path: path})
var customErr mybuiltins.BuiltinError
if err != nil && errors.As(err, &customErr) {
// Get additional error information from customErr
}
```
This PR introduces unwrap functionality for `topdown.Error` and modifies error handling for builtins to return a `topdown.Error` that wraps the error returned by a builtin implementation.

Add unwrap functionality to topdown.Error

---

docs/Makefile
docs/website/scripts/load-docs.sh

This was only added for dev in https://github.com/open-policy-agent/opa/pull/5984/files#diff-cdec797dddf8fc387304501d6bd4f318e1e9067c6fae012dfa8b69fd85fd3248R33
I missed this as I thought the preview would run the prod commands

[website] Include static hugo pages in prod build

---

bundle/bundle.go
bundle/bundle_test.go
download/download.go

Fix for the issue when OPA throws misleading error (storage_not_found_error) message while loading the delta bundle when persist property in config is true.
The fix is to prevent the loading of delta bundle when persist is true and give a more clear error message.
One Test function included TestReadWithPatchPersistProperty
Fixes #5959
a new persist property is created in Reader struct in bundle.go
WithBundlePersistence method is created on Reader
from download , this property is set in Reader
persist property is checked in Read() method to throw the error for delta bundles.

Fix for the issue when OPA throws misleading error (storage_not_found_error)

---

cmd/test.go
cmd/test_test.go

Fix: https://github.com/open-policy-agent/opa/issues/5986
This is to make `storage.Write` responsive when `removed` is detected
I came across the issue, as @ashutosh-narkar well-described,  while including some data.json into the folder using `mv`
```
./opa_darwin_arm64 test smoketest -w
```
then
```
mv smoketest/check_data.json ./
mv check_data.json smoketest
```

fix(test): re-evaluate storage when remove is detected

---

topdown/cache/cache.go
topdown/cache/cache_test.go
topdown/http.go
topdown/http_test.go

Concurrent evaluation of the http.send builtin for the
same object can sometimes result in the HTTP headers
map being concurrently accessed. This can happen for
example when a key already present in the inter-query
cache needs to be revalidated and multiple routines
may access the HTTP headers at the same time resulting
in a race.
This change adds a new Clone method to cache interface.
The idea is to give each routine its own copy of the cached object
which would mean it has a copy of the headers map and
thus should be able to avoid any sync issues.

topdown: Update cache interface with Clone method

---

bundle/bundle.go
bundle/bundle_test.go
bundle/file_test.go
bundle/sign_test.go
bundle/store_test.go
cmd/inspect_test.go
cmd/sign_test.go
internal/bundle/inspect/inspect_test.go
loader/extension/extension.go
loader/extension/extension_test.go
loader/loader.go
storage/disk/disk_test.go
storage/inmem/inmem_test.go
util/json.go

This
1. changes the extension.Handler type to make it more flexible
2. simplifies the extension usage -- it used to be called in many places, but it could all be handled through `util.Unmarshal` and `util.UnmarshalJSON` instead
We've previously marked it as "EXPERIMENTAL", so we should have enough leeway to change this now.

loader: change extension handler type

---

docs/website/layouts/docs/ecosystem.html.html

https://github.com/open-policy-agent/opa/pull/6029 introduced a bug where older versions of the ecosystem page in docs were not rendered correctly due to a missing template.
This PR restores the template referenced by the now-removed ecosystem.html file, which still exists in older versions.
This legacy template must be retained for as long as the older docs versions ecosystem pages need to function.

[bugfix] Restore legacy ecosystem template

---

docs/website/assets/sass/custom.sass

In #6029 I introduced a bug which caused scrollbars to show on some browsers in some viewports.
https://github.com/open-policy-agent/opa/pull/6029/files#diff-3707717b9bfb9dd7c7ac1dddba9600c1798ebc1528b2539eeca40e034a824f8fR65
This addresses the issues with a fix using a more conventional `max-width` value, though the result in this case is much the same.

[website/bugfix] Fix docs scrollbar issue

---

docs/content/policy-reference.md
topdown/time.go

Standard OPA images are based on cc-dynamic from Chainguard Images:
https://github.com/chainguard-images/images/blob/main/images/cc-dynamic/README.md
(now deprecated, see: https://github.com/open-policy-agent/opa/issues/6037)
This image doesn't include tzdata.
Our static images however are based on static.
https://github.com/chainguard-images/images/blob/main/images/static/README.md
This build includes tzdata:
https://github.com/chainguard-images/images/blob/main/images/static/configs/latest.apko.yaml#L8
How to see this:
```
$ docker run -it openpolicyagent/opa:0.53.1-static eval 'time.clock([time.now_ns(), "Asia/Shanghai"])'
{
"result": [
{
"expressions": [
{
"value": [
17,
54,
3
],
"text": "time.clock([time.now_ns(), \"Asia/Shanghai\"])",
"location": {
"row": 1,
"col": 1
}
}
]
}
]
}
$ …
```

Import `time/tzdata` for use when filesystem tzdata is missing

---

cmd/build.go
compile/compile.go
compile/compile_test.go

Currently the namespace for partially evaluated files in an optimized bundle cannot be modified. As a result if more than one optimized bundle is loaded in OPA, a root conflict error would occur as the optimized bundles have a root called "partial" automatially added to their
manifest. This change allows the namespace to be configured via the build command.
Fixes: #5933

Add ability to specify namespace for optimized files

---

internal/logging/logging.go

- There's a cheaper method to check if a byte slices is valid JSON: json.Valid.
- Also replaces spaces() by strings.Repeat().

internal/logging: nitpicks

---

Makefile

cc-dynamic has been deprecated.
https://github.com/chainguard-images/images/blame/main/images/cc-dynamic/README.md#L23
Fixes https://github.com/open-policy-agent/opa/issues/6037
Needs https://github.com/chainguard-images/images/pull/937 before merging.

Update to glibc-dynamic image

---

cmd/test.go
cmd/test_test.go

For less verbose test output, where some successful tests might get interpreted as failing.

Adding configurable error output `Writer` to test cmd

---

plugins/discovery/discovery.go

Currently discovery bundle tar balls are empty.
Add missing option `WithBundlePersistence` to the discovery plugin's downloader, so that the downloaded raw buffer gets populated. Before this change the `buf` (https://github.com/open-policy-agent/opa/blob/main/download/download.go#L366) would be empty when downloading the discovery bundle. This resulted in an empty bundle.tar.gz file produced here: https://github.com/open-policy-agent/opa/blob/main/plugins/discovery/discovery.go#L325
I have not added any tests due to contructor logic not being very testable. Currently it is only possible to access the downloader through the interface which makes it not possible to check if the "WithBundlePersistence" is set.
To test it, it would require a mock discovery server where the discovery plugin …

plugins/discovery: fix persistance of discovery bundle

---

Makefile

Buildx version >=0.10 generates a new OCI format
with support for provenance. As a result the
following error is generated on M1/M2 while inspecting the manifest
> OCI manifest found, but accept header does not support OCI manifests
The suggested fix is to temporarily disable provenance.
Fixes: #5877
Related: https://github.com/docker/buildx/issues/1533.
The other workaround is to pin `buildx` version to `v0.9.1`. If this fix does not work as intended we can pin the version.

Disable provenance attestations in buildx

---

config/config.go
config/config_test.go

Previously, extra keys in the OPA config file would be ignored in the /v1/config API, but included when evaluating `opa.runtime().config`.
With this change, they'll be collected into the Extra field, and included in the response of an API call to `/v1/config`, too.
Put this file on disk,
```yaml
foo: bar
baz:
quz: 100
decision_logger:
console: true
```
and start OPA via `opa run -a 127.0.0.1:8181 -c foo.yml -s`.
```interactive
$ curl "http://127.0.0.1:8181/v1/config?pretty"            
{
"result": {
"default_authorization_decision": "/system/authz/allow",
"default_decision": "/system/main",
"labels": {
"id": "617ef51a-5f78-42ec-ba04-d7ca758c307f",
"version": "0.53.1"
}
}
}
$ curl "http://127.0.0.1:8181/v1/query?pretty" -d '{"query": "x = opa.runtime().config"}'
{
"result": [
{
"x": { …
```

config: add extensible "Extra" field, use it ActiveConfig

---

docs/content/management-discovery.md
plugins/discovery/discovery_test.go
plugins/plugins.go

Before this change, if a discovery bundle didn't contain configuration
for `persistence_directory`, this would be deleted from the manager's
configuration. When enabling persistence of the discovery bundle this
doesn't make much sense, as the first discovery bundle would erase the
persistence settings.
This change ensures that discovery never erases `persistence_directory`.
Signed-off-by: Benjamin Nørgaard <mail@blacksails.dev>

plugins/discovery: Fix discovery erasing `persistence_directory` configuration

---

ast/term.go

This PR pulls out only the performance fix to `lazyObj` from #6040.

ast: Only realizing `lazyObj` when compared against other object

---

Makefile

[See this](https://github.com/docker-library/golang/issues/466), bumping the golang image used for building our release binaries changed our glibc lowest-possible-version inadvertently. This will turn that back.
At some point in the future, when a new debian release is out, the support for bullseye is going to be dropped, but we'll notice when trying to update Golang.

build: use -bullseye golang image

---

docs/content/configuration.md
internal/providers/aws/kms.go
internal/providers/aws/kms_test.go
plugins/rest/auth.go
plugins/rest/auth_test.go
plugins/rest/aws.go
plugins/rest/rest_test.go

This implementaion adds new configuration properties to "oauth2" aws_kms: AWS KMS key details
aws_signing: Infomation for signing AWS requestion, similar to s3_signing
References:
1) https://github.com/go-jose/go-jose/blob/v3/asymmetric.go#L501 
2) https://github.com/codelittinc/gobitauth/blob/master/sign.go#L101
Sample config file: https://gist.github.com/prasanthu/16e5e668ea864487d44dd7e95ff0d34b
Please refer to this Github issue for more details: https://github.com/open-policy-agent/opa/issues/5892

Add AWS KMS support for OAuth2 Client Credentials JWT authentication

---

plugins/discovery/discovery.go
plugins/discovery/discovery_test.go
sdk/opa_test.go

When the discovery plugin receives a a discovery bundle which omits the
discovery configuration, it deletes its own configuration from the
manager. In turn this means that `GET /v1/config` doesn't show the
configuration of the discovery plugin.
This change ensures that the plugin will never overwrite the discovery
configuration on the manager.
Signed-off-by: Benjamin Nørgaard <mail@blacksails.dev>

plugins/discovery: ensure discovery doesn't erase its own config

---

rego/rego.go
sdk/opa_test.go
server/server_test.go

Currently we parse store modules irrespective of whether there are modules on the Rego object. This will result in the compilation of those modules which triggers the bundle activation flow. Now as part of the module compilation we interact with the compiler's modules and run compilation on the input modules. If let's say there are concurrent health check requests (ie. /v1/health), this could result in a race during the compilation process while working with the compiler's modules.
This change avoids this situation by skipping parsing of the store modules when none are set on the Rego object. The assumption this change makes is that while using the rego package the compiler and store are kept in-sync.
Fixes: #5868
The PR reverts [this](https://github.com/open-policy-agent/opa/commit/8bb23b …

rego: Parse store modules iff modules set on the Rego object

---

cmd/commands.go
cmd/internal/deprecation/rootless.go
cmd/internal/deprecation/warning.go
cmd/internal/deprecation/warning_test.go
runtime/check_user_linux.go

I have added a system for showing fatal and non-fatal deprecation warnings. It's configurable by command and environment.
If we merge this PR, running a rootless image with any OPA command other than `opa run` will result in a fatal error and exit code 1.
It's possible for users to continue to use the image by unsetting: OPA_DOCKER_IMAGE_TAG=rootless.
`opa run` will show the message, but it's not fatal for this command. This is intended to avoid production disruption.
This PR has been added to allow us to one day do https://github.com/open-policy-agent/opa/pull/6086. It is a simpler version of my earlier PR for the same task https://github.com/open-policy-agent/opa/pull/5566.
Example showing how `opa build` will fail and exit with 1:
```
opa $ OPA_DOCKER_IMAGE_TAG=rootless go run main.go …
```

[cmd] Implement a rootless deprecation messages

---

compile/compile.go
compile/compile_test.go

Previously, bundle roots couldn't be provided and neither .manifest file couldn't be provided, because it was replaced by the .manifest generated by the compiler. This will help to build bundles from using the Go library for more advanced use cases with multiple bundles.
Added `WithRoots` option so caller can provide roots.
Fixes: #6085

compile: bundle roots can be provided by caller

---

sdk/opa.go
sdk/opa_test.go

The sdk package allows you to pass arbitrary Go objects as the input document. This is fine for evaluation (as long as the object can be parsed to an AST), but is problematic for decision log masking, as the masking logic expects the input on the event to be either a map[string]interface{} or a []interface{}. Currently, the decision log masking silently fails if the input object is not of the correct type.
This commit addresses this by checking if the input object is of the correct type, and if not, rebuilds it from the input AST before it is logged.
Also, a test is added to cover this case.
The SDK package allows you to specify Go structs as the input to a query. However, the decision log masking feature will fail silently when you do so, because the masking only allows the input to be …

sdk: Fix decision log masking of input object

---

sdk/opa.go
sdk/opa_test.go

This allows clients to specify the decision ID for the decisions returned by the `Decision` and `Partial` functions provided by the SDK package. If not provided, a uniquely generated identifier will be generated for the decision, just as before.
This option can be useful for clients that have already generated a decision ID prior to calling OPA. It would then be convenient to pass that decision ID through to OPA so decision logs use that same ID.
This fixes https://github.com/open-policy-agent/opa/issues/6100

Add option for specifying decision ID to SDK

---

ast/compile_test.go
ast/parser.go
ast/parser_test.go
internal/wasm/sdk/test/e2e/exceptions.yaml
test/cases/testdata/defaultkeyword/test-default-functions.yaml
test/cases/testdata/functions/test-functions-default.yaml
topdown/eval.go

Default functions satisfy the following properties:
* Same arity as other functions with the same name
* Arguments should only be plain variables ie. no composite values. For ex, default f([x]) = 1 is an invalid default function
* Variable names should not be repeated ie. default f(x, x) = 1 is an invalid default function
Fixes: https://github.com/open-policy-agent/opa/issues/2445

topdown: Honor default keyword on functions

---

docs/content/envoy-tutorial-standalone-envoy.md

The tutorial now uses [kind](http://kind.sigs.k8s.io) as well as updated versions for envoy.
I have made some adjustments to how the bundle is served and the test commands run to exercise the policy too.

[docs] Update the standalone envoy tutorial

---

docs/website/layouts/docs/ecosystem-single.html.html
docs/website/layouts/partials/ecosystem-project-list-for-feature.html
docs/website/layouts/shortcodes/ecosystem_feature_embed.html

Reproduce Bug:
* Visit: https://www.openpolicyagent.org/docs/edge/policy-language/#ecosystem-projects
* Click `view on the OPA ecosystem page`
I have also tried to use the titles from items in links when the titles are short enough.
Some photos to show the changed titles. Note that some show default text, and shorter titled items use the title in link. This should make the linked pages better detected in search engines.
* <img width="969" alt="Screenshot 2023-07-20 at 17 42 24" src="https://github.com/open-policy-agent/opa/assets/1774239/700c2fd8-6969-4d7a-befe-bd951204c53c">
* <img width="963" alt="Screenshot 2023-07-20 at 17 42 52" src="https://github.com/open-policy-agent/opa/assets/1774239/f571405b-0f00-477a-860c-3f203eca7d43">

[docs] Fix bug for broken ecosystem links

---

download/oci_download.go
download/oci_download_test.go
download/testharness.go

* add auth to oci_downloader for gitlab registries
* authentication has same workflow as public auth but with authenticated token fetch
OCI sourced bundles can not properly authenticate when using GitLab Registry.
See also: [authorizer.go#L299](https://github.com/open-policy-agent/opa/blob/39125a034c7268ba3a98f4a76f92313e51bea817/vendor/github.com/containerd/containerd/remotes/docker/authorizer.go#L299)
Adds a not so elegant solution to get the header explicitly to containerd on, while not only relaying on the client to add the header, which doesn't work for gitlab.
I'm not really sure if reflection is the way to go here, but it solves the problem quite elegantly and is only called on pulls.

plugins/download: GitLab registry header auth

---

docs/content/policy-performance.md

I referenced the docs in
https://github.com/orgs/open-policy-agent/discussions/475 and figured the formatting could be improved.
I also made some minor edits to the intro.

[docs] Brush up OPA profiling docs

---

ast/compile.go
ast/compile_test.go

This change updates the compiler strict error check message for unused function arguments to include a hint on how to
pass that check.

Update strict error check message for unused args

---

CHANGELOG.md
cmd/test.go
cmd/test_test.go

Closes #6126.
- Fixes the failed logic introduced in https://github.com/open-policy-agent/opa/commit/54f203c3843b23474afd9990787a1affdcaa40c5 to compute the exit code of a test run
- Adds unit tests to cover this area
I consider this is a BREAKING-CHANGE: all passing CIs that were launching `opa test --exit-zero-on-skipped` including both skipped and failed test rules will now break.

fix(cli): make `opa test --exit-zero-on-skipped` fail with failing test rules

---

docs/content/policy-reference.md

Fixes #6134 
- Added a line to correctly run the [Ordered(Else)](https://www.openpolicyagent.org/docs/latest/policy-reference/#ordered-else) example.

[docs] Missing hint "future.keywords.if" for "Ordered (Else)"

---

docs/content/policy-reference.md

- To improve user experience of the documentation.
- added # with `import future.keywords.in` where **in** is used.
- added # with `import future.keywords.if` where **if** is used.
- added # with `import future.keywords.contains` where **conatins** is used.

[docs] Added Missing Hints in policy-reference

---

format/format.go

The comment said the parser duplicated comments, but that does no longer seem to be the case. All tests pass without this and I was not able to reproduce it any other way.

chore: Remove dedup comment function in opa fmt

---

docs/website/data/integrations.yaml

We got this wrong again: https://github.com/open-policy-agent/opa/pull/6158#issuecomment-1680505381
The data used for the website is always using edge, not the latest release.
https://www.openpolicyagent.org/docs/latest/ecosystem/ is broken at the moment because of this.

[docs] Address issue OPA ecosystem missing items

---

docs/website/layouts/docs/baseof.html
docs/website/layouts/docs/ecosystem.html.html
docs/website/layouts/partials/nav.html

Edge works fine, so we'll do this:
1. link to /docs/edge/ecosystem
2. suppress the "you're viewing edge" banner from the
ecosystem page
We can revisit this when the next release is out, but it
makes the ecosystem page _less broken_ for the time until
then.
Small bonus: you can now directly visit the Ecosystem page from the preview, since it now links to "edge" (was "latest" before, there, too).

website: link ecosystem from edge

---

docs/README.md

This explains how different parts of the site are versioned as it seems to keep catching me out.
Following https://github.com/open-policy-agent/opa/pull/6170

[docs] Update note on site updates

---

ast/check.go
ast/check_test.go
ast/env.go
ast/env_test.go
test/cases/testdata/type/test-regressions.yaml

instead of static portion.
This change allows object unification/comparison between an object composed at eval-time (i.e. constructed by rules) and a static object that doesn't contain all keys declared by rules, as those might not be defined at eval-time.
e.g.:
```rego
package test
obj[k] := v {
v := ["a", "b", "c"][k]
}
obj.foo := "bar"
obj.baz := true { false }
compare {
obj == {
0: "a",
1: "b",
2: "c",
"foo": "bar"
}
}
```
Fixes: #6138

ast: Making partial object key rules contribute to dynamic portion of object type

---

download/oci_download.go
download/oci_download_unavailable.go
download/oci_downloader.go

xrel https://github.com/open-policy-agent/opa/issues/6160
I think it's best explained in the issue - https://github.com/open-policy-agent/opa/issues/6160
This pr adds an `opa_no_oci` build flag to exclude containerd dependency.
Look at the issue first - https://github.com/open-policy-agent/opa/issues/6160.
Nothing.

feat(download): add opa_no_oci flag to build without containerd

---

docs/content/management-decision-logs.md

Make it clear that dropped decisions are *not* logged, and modernize the Rego examples.

docs: make it clear dropped decisions aren't logged

---

cmd/test_test.go
tester/runner.go

When used `opa test --bundle` the flags `--ignore` were not used to filter the files.
Change the function `LoadBundles` to use the parameter `filter` received.
None.
None.

cmd: Fix opa test --ignore when used together with --bundle

---

rego/plugins_test.go
rego/prepare_test.go
rego/rego.go

This is used as a mechanism to inform custom rego target plugins about builtins that have been defined ad-hoc, via rego.Function1, rego.Function2, etc.
Before, in a setup like this:
```go
regoArgs = append(regoArgs,
rego.Target("my_custom_evaluator"),
// ...
rego.Function2(builtins.RegalParseModuleMeta, builtins.RegalParseModule),
rego.Function1(builtins.RegalJSONPrettyMeta, builtins.RegalJSONPretty),
rego.Function1(builtins.RegalLastMeta, builtins.RegalLast),
)
```
...the prepared eval state for the custom rego target would not be informed about the functions defined there ☝️ 
Now, the PrepareOptions that are passed to the target plugins are used to carry the information along. To do that, a new field was added, and an accessor function.
In the working stages of this, I had also added …

rego: expose PrepareOption, add BuiltinFuncs

---

internal/runtime/init/init.go
internal/runtime/init/init_test.go

Fixes #5879
This is fix to read tarball provided on cmd line as a bundle. It will be applied when OPA started with -s flag
ServerMode bool field is added to runtime parameters
This and BundleMode value is used to pass true value of BundleMode in LoadPaths method in init package. 
After running each command, I checked the value at http://localhost:8181/v1/data and they were correct after each run.
go run main.go run  -s -b bundle2.tar.gz bundle3.tar.gz  pass
go run main.go run  -s bundle2.tar.gz bundle3.tar.gz         pass
go run main.go run  -s bundle2.tar.gz bundle3.tar.gz bundle4.tar.gz  pass
go run main.go run  -s -b bundle2.tar.gz bundle3.tar.gz -b bundle_test pass
go run main.go run  -s bundle2.tar.gz bundle3.tar.gz -b bundle_test pass
go run main.go run  -s -b bundle2.tar.gz …

Fix for the issue when OPA doesnot load tarball on cmd line as a bundle.

---

docs/website/content/ecosystem/_index.md
docs/website/content/ecosystem/go-integration.md
docs/website/content/ecosystem/rest-api-integration.md
docs/website/content/ecosystem/wasm-integration.md
docs/website/layouts/ecosystem/section.html.html

[docs] Add intro text to Ecosystem sections

---

docs/website/layouts/partials/docs/navbar.html
docs/website/layouts/partials/docs/sidenav.html

There are the following issues with the docs menus at the moment:
* OPA ecosystem is shown 2x for some versions
* OPA ecosystem is not linked from the mobile nav in the latest version
* OPA ecosystem still appears under misc in earlier versions
In order to make changes based on page structure in earlier versions, I've had to filter how the pages are selected. I've opted to exclude all content based linking to the opa ecosystem and replace it with the hardcoded link to the now unversioned page /ecosystem.
The mobile enterprise support link has also been renamed to match the link text used on the desktop sidenav

[docs] Address issues with Ecosystem links in navs

---

ast/compile.go
ast/compile_test.go
bundle/store.go
cmd/run.go
cmd/run_test.go
docs/content/security.md
internal/compiler/utils.go
internal/compiler/utils_test.go
internal/runtime/runtime.go
plugins/bundle/plugin.go
plugins/bundle/plugin_test.go
runtime/runtime.go
runtime/runtime_test.go
schemas/authorizationPolicy.json
schemas/schemas.go
schemas/schemas_test.go

The schema of the input document for the authorization
policy is known to OPA. This feature leverages that
to perform automatic type checking on the authorization policy.
The checks happen on policies provided to OPA on start-up and
also those provided via bundles. This check is enabled by default
and can be disabled using the `--skip-known-schema-check` flag
on `opa run`. This feature will help catch errors such as
typos, mismatch types etc. in these policies and provide precise
feedback to the policy author.

Extend type checking for authz policies

---

compile/compile_bench_test.go
types/types.go
types/types_bench_test.go

I noticed an optimization opportunity for the type checker's `Any` type, specifically when merging two `Any` types together with the `Union` method.
This came up as part of a continuing investigation into #5216, and I realized I could carve off a useful set of changes along the way.
*Note: This **does not** significantly change the bottom line for #5216 sadly, since the bottleneck is distributed across 2-3x other places. :slightly_frowning_face:* 
This PR extends the `types/types_bench_test.go` benchmarks with **2x new benchmarks**, one for the frequently-called `(Any).Merge` function, and another for `(Any).Union`.
It also **implements a new algorithm** for `(Any).Union` which is dramatically more efficient than the original, and scales to larger sizes without pathological …

types: New benchmarks + new (Any).Union algorithm

---

.github/workflows/nightly.yaml

It's unlikely that anyone is looking at the results when there's a fresh run's results (of Sunday) awaiting you on Monday.

nightly: skip Fri/Sat night

---

ast/compile.go
ast/compile_test.go

Updating all vars in rule ref
Fixing issue where strict-mode would only see the last var in a rule head's ref as used, if that var is assigned in the rule body but only used in the ref.
E.g.
```rego
package test
p[q].r[s] := 1 {
q := "foo"
s := "bar"
}
```
would cause a reported `rego_compile_error: assigned var q unused` error when `--strict` is used, even though `q` is used in the rule head's ref.

ast: Fixing strict-mode unused var issue for general ref in rule heads

---

ast/compile.go
ast/compile_test.go
ast/parser.go
format/format_test.go
internal/planner/planner_test.go
test/cases/testdata/refheads/test-generic-refs.yaml
test/cases/testdata/refheads/test-refs-as-rule-heads.yaml
topdown/eval_test.go
topdown/topdown_partial_test.go

Removing EXPERIMENTAL_GENERAL_RULE_REFS feature flag

---

docs/content/policy-language.md

Fixes: #5996
Updating documentation with information about general refs in rule heads.
~🚧 ⚠️  These changes are contingent on #6235 getting merged; and should not be merged before those changes.~
Note: we use live code blocks to demonstrate general ref rule heads, and these will be broken until the Rego Playground is updated to use the latest OPA version.
To build the docs, and view the live code blocks, build the playground with `main`-branch OPA and run it locally; then point the docs to that instance by updating `PLAYGROUND` in `docs/website/scripts/live-blocks/src/constants.js`.

General refs/docs

---

docs/content/configuration.md
docs/content/management-bundles.md

When an object in GCS contains special characters such as slashes (/) these need to be url-encoded in the configuration. If not, the bundle will not be found.
e.g. `bundles/bundle.tar.gz` should be entered as `bundles%2fbundle.tar.gz`
This PR adds notes to help the reader know about this and corrects some existing (IMHO incorrect) documentation.
I tried to add a bundle using GCS (with a bundle in a subfolder) and stumbled upon the fact myself. Took me some time
to figure it out. I hope this helps the next reader of this part of the documentation.
Just some notes were added to the documentation regarding GCS bundles, some other parts were corrected.
Personally, I think this is enough. If preferred, though, we could elaborate a little more on it and e.g. link to
the GCS documentation page. …

Update documentation on GCS bundles

---

topdown/arithmetic.go

Currently for arithmetic operations like addition, subtraction etc. the operands are first converted to the big float type before operating on them. This conversion can be avoided for small numbers w/o impacting the accuracy of the result. 
This change attemtps to avoid the conversion for small numbers by caching them and thereby helping to speedup some operations.
The division operator (`/ `) was not changed as the result could lose precision with the mechanism used for other operators.

topdown: Improve arith operations by caching small numbers

---

ast/builtins.go
builtin_metadata.json
test/cases/testdata/walkbuiltin/test-walkbuiltin-wildcard-path.yaml
topdown/walk.go

We do a lot of `walk`-ing in [Regal](https://github.com/StyraInc/regal). So much that it's by far the single most expensive operation. That means any optimization of the `walk` built-in function will be a win for us.
Seeing as we rarely make use of the `path` component when `walk`-ing through AST inputs, I was curious to see if there was any optimization we could take when the path is a wildcard assignment, and as such clearly marked as unimportant. Turns out there is. Since the return value is provided in the operators list, we can check the value provided for the `path` part of the assigned array, and if it's a wildcard (`_`) skip path construction entirely. Example:
```rego
walk(input, [_, value]) # path is ignored
```
This greatly simplifies the walk, and the performance gains are …

Walk: skip path creation in wildcard assignment

---

cmd/test.go
cmd/test_test.go
cover/cover.go
tester/reporter.go

when `--verbose` flag is enabled.
Fixes: #2562

Adding lines not covered to test coverage threshold error message

---

.gitignore
docs/Makefile
docs/website/layouts/shortcodes/builtin-table.html
docs/website/layouts/shortcodes/builtin-tags.html
docs/website/scripts/load-docs.sh

Fixes https://github.com/open-policy-agent/opa/issues/6269
This fixes the issue by using the builtin_metadata.json file from each version, the assumption that docs content that depends on the data doesn't exist before this file was introduced.
I have removed the 'available' check since we haven't consistently updated the file in the past, e.g.
https://github.com/open-policy-agent/opa/blob/v0.41.0/builtin_metadata.json#L12710 https://github.com/open-policy-agent/opa/blob/v0.57.0/builtin_metadata.json#L563
These examples show that sometimes the current version is included, other times the file is updated after the release.
Video showing the correct content being displayed for various versions:
https://github.com/open-policy-agent/opa/assets/1774239/abf1af7d-9c59-4223-a019-c73d7550b322
To …

[docs] Fix unversioned built-in docs issue

---

cmd/test_test.go

to reduce risk of chasing down red herrings when troubleshooting a failing build.

Silencing expected error output in tests

---

internal/pathwatcher/utils.go
internal/pathwatcher/utils_test.go

Currently if a fsnotify watcher is specified for a particular directory, we incorrectly also add it's parent directory to be monitored. This happens because the function that determines which paths are to be watched calls `filepath.Dir` on each of them to get their directory. This is the right thing to do for files as their parent directory gets watched, but when done on a directory especially for the top-level directory adds an incorrect directory to be watched. This changes attempts to fix that.

internal/pathwatcher: Fix how paths to watch are determined

---

config/config.go
config/config_test.go
docs/content/configuration.md
internal/prometheus/prometheus.go
internal/prometheus/prometheus_go1.19_test.go
internal/prometheus/prometheus_test.go
plugins/server/metrics/config.go
plugins/server/metrics/config_test.go
runtime/runtime.go
runtime/runtime_test.go
server/server_test.go

http_request_duration has fixed, hardcoded number of buckets with no possibility to tweak them For cases when the most of the latencies are above 1ms, with only 4 available buckets there's no good insight on OPA's performance.
This implementation:
- adds the possibility for the buckets to be configurable in ```server.metrics.prom.http_request_duration_seconds.buckets``` key
- it's not a breaking change, if the buckets are not present in the configuration, the metric is configured with the existing values as a fallback
N/A
Fixes #6238

This change adds support to configurable prometheus buckets

---

docs/content/monitoring.md

Drop `EXPERIMENTAL` status of metrics reported via Prometheus in Status API. OPA's maintained these for a while now and there's no 3rd party dependency required to support these.
Fixes: #6298

Drop EXPERIMENTAL status of reported prom metrics

---

runtime/logging.go
server/server.go
server/server_test.go
server/types/types.go

The partial query parameter has been marked as deprecated since v0.23.0. It's also removed from the docs since that time.
Fixes: #2266

server: Remove partial query parameter

---

cmd/test_test.go
cover/cover.go
cover/cover_test.go

Perhaps it looks prettier, but this is only reported in JSON output, so I don't think we should decide on what precision to use there.
On coverage < threshold error, we still print using 2 decimals, which is Pretty ✨
Fixes #6307

Don't use rounding for coverage calculation

---

cmd/run.go
cmd/run_test.go
docs/content/_index.md
docs/content/deployments.md
docs/content/security.md
runtime/runtime.go
runtime/runtime_test.go

Currently OPA binds to the 0.0.0.0 interface by default, which allows the OPA server to be exposed to services running outside of the same machine. Though not inherently insecure in a trusted environment, it's good practice to bind OPA to the localhost interface by default if OPA is not intended to be exposed to remote services.
Fixes: #6286
Below is a log from the OPA server which shows `localhost:8181` as the default address.
```
$ go run main.go run -s
{"addrs":["localhost:8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-10-11T16:51:58-07:00"}
```

Bind OPA server to localhost interface by default

---

ast/compile_test.go

In OPA versions older than `0.56.0`, a recursion cycle could be hidden to the compiler if partial object rules were "properly" organized. This issue was fixed in OPA `0.56.0` without being reported, this PR adds a regression test.

Adding regression test for edge case where partial rule hides recursion cycle

---

plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

This PR tries to represent a bug in the code which causes the OPA container to become unhealthy and propose a fix for the same.
The bug happens on plugin readiness,  when `Reconfigure` is called the plugin state it NotReady and waits for all downloaders to be triggered again and reconcile the state to OK. However if all bundles received a 304 from the backend server the plugin state remains NotReady and causes the `/health?bundles=true` to start failing
The PR adds `checkPluginReadiness` an existing method in the branch where the downloaded bundle is Not Modified instructing the plugin to reconcile plugin readiness.
Adding tests around plugin state reconciliation on `Reconfigure` when one or all of the downloaded bundles can be Not Modified.

fix: plugin reconfigure state when downloaded bundle is Not Modified

---

format/format.go
format/testfiles/test_functions.rego
format/testfiles/test_functions.rego.formatted

This is especially nice for functions doing pattern matching on equality in its arguments.
Previously, we'd rewrite:
```rego
f(1)
```
into
```rego
f(1) = true
```
Now, we'll leave the shorter form alone, while still respecting explicit assignment, using either `=` or `:=`.

fmt: functions — don't add virtual `= true` value unless provided

---

go.mod
go.sum
server/server_test.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/gen.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
vendor/modules.txt

This version includes security fixes which addresses vulnerability CVE-2023-45142.More details can be
found at https://github.com/open-telemetry/opentelemetry-go-contrib/security/advisories/GHSA-rcjv-mgp8-qvmr.

deps: Bump OpenTelemetry-Go Contrib 0.45.0

---

.github/workflows/post-tag.yaml
build/github-release.sh

The `hub` tool is deprecated in favor of the GitHub CLI and is removed from GitHub's action runner images.
Fixes: #6326
[OPA-Envoy plugin's](https://github.com/open-policy-agent/opa-envoy-plugin) `Post Tag` workflow had the same issue. We fixed it there first and tested it with [this](https://github.com/open-policy-agent/opa-envoy-plugin/releases/tag/v0.57.1-envoy-3) release. Also manually tested the create and update of the release scenarios.

build: Migrate to GitHub CLI tool

---

ast/compile.go
rego/rego.go
rego/rego_test.go

Only topdown can make sense of rules and comprehension indices, so Wasm and any eval plugins should instruct the compiler to avoid that work.
Instrumentation metrics for a wasm-eval before:
```
+----------------------------------------------------------+--------+
|                          METRIC                          | VALUE  |
+----------------------------------------------------------+--------+
| counter_compile_stage_comprehension_index_build          | 0      |
| timer_compile_stage_check_duplicate_imports_ns           | 218    |
| timer_compile_stage_check_keyword_overrides_ns           | 337    |
| timer_compile_stage_check_recursion_ns                   | 3306   |
| timer_compile_stage_check_rule_conflicts_ns              | 20497  |
| …
```

ast+rego: disable compiler stages for IR-based eval paths

---

ast/compile.go
ast/compile_test.go
ast/internal/scanner/scanner.go
ast/parser.go
ast/parser_ext.go
ast/parser_test.go
ast/policy.go
docs/content/policy-language.md
format/format.go
format/testfiles/test_rego_v1.rego
format/testfiles/test_rego_v1.rego.formatted
internal/future/filter_imports.go

This change renames the `future.compat` import to `rego.v1`. The latter is clear that it's a declaration that
a module is compatible with a v1 version of OPA.

Rename future.compat import

---

ast/term.go
compile/compile.go
compile/compile_test.go
topdown/eval.go
topdown/save.go
topdown/topdown_partial_test.go

Issues fixed:
* production of support module with forbidden characters in first var of rule ref (#6338)
* panic when policy contains rules with a general ref in the head (#6339)

topdown: Fixing issues with optimizing rules with refs in the head

---

cmd/run.go
cmd/run_test.go
docs/content/_index.md
docs/content/cli.md
docs/content/deployments.md
docs/content/security.md
runtime/runtime.go
runtime/runtime_test.go

This change renames the `--future-compat` CLI flag on `opa run` to `--rego-v1`. The latter is clear that it's a declaration that gated features are compatible with a v1 version of OPA.

Rename --future-compat CLI flag

---

ast/parser_ext.go
ast/parser_test.go

The `rego.v1` import requires the `if` keyword before the rule body. We should make an exception for default rules.

ast: skip if keyword requirement for default rule

---

format/format.go
format/testfiles/test_rego_v1.rego
format/testfiles/test_rego_v1.rego.formatted

format: Not outputting any `future.keywords.*` imports when `rego.v1` import in policy

---

docs/content/policy-language.md

Unused local assignment and unused imports will remain strict mode checks even in OPA 1.0.

Update docs on rego.v1 / OPA 1.0

---

ast/parser.go
ast/parser_test.go

for rules/functions that only has value assignment for `else` but not "primary" head
Fixes: #6364

ast: Fixing erroneous missing value assignment error

---

internal/compiler/wasm/wasm.go
internal/planner/planner.go

Basically lifting [this compiler optiimization for the Wasm compiler](https://github.com/open-policy-agent/opa/blob/main/internal/compiler/wasm/wasm.go#L1094-L1113) into the planning stage: If we already know at plan time that a certain (in)equality check fails/succeeds, we don't need to do it. The less work, the better.
We should have our bases covered by the existing yaml tests 🤞

planner: don't plan superfluous Equal/NotEqualStmts

---

plugins/discovery/discovery.go
plugins/discovery/discovery_test.go
plugins/plugins.go
plugins/status/plugin.go
plugins/status/plugin_test.go
server/server_test.go

Fixes https://github.com/open-policy-agent/opa/issues/6343
In addition to what's changed here, we might want to consider making the status posts have a configurable timeout, but that'd be a change to config and something we might want to do in another PR.

discovery: Make status updates non blocking

---

docs/content/envoy-primer.md

Corresponding docs changes for https://github.com/open-policy-agent/opa-envoy-plugin/pull/479
Add `dynamic_metadata` as a supported `result` keyword in the `opa-envoy-plugin` docs, and provide a small example.
see https://github.com/open-policy-agent/opa-envoy-plugin/pull/479 for implementation.
N/A

Add docs for dynamic_metadata feature in opa-envoy-plugin

---

internal/compiler/wasm/opa/callgraph.csv
test/cases/testdata/regexfindallstringsubmatch/test-regexfindallstringsubmatch-large-input.yaml
wasm/src/regex.cc

When feeding a `char *` into `re->Match()`, it was converted to a StringPiece, taking its size as `strlen()`. For our (long) input, that wasn't resulting in the correct size, and did then freak out the re2 match input validation if the regular expression has an end anchor, but the endpos wasn't the same as its length. Since the endpos was taken from `s->len`, and the "length" taken via the mentioned StringPiece's strlen() call, they did indeed not match.
Worked around by feeding it a properly-constructed std::string instead. I'm a C++ novice at best, but it does the trick, and I'm reasonable certain it's less wrong than before.
Fixes #6376.

wasm: fix re2 bug

---

ast/json/json.go
ast/location/location.go
ast/location/location_test.go
ast/marshal_test.go
ast/parser_test.go

Repeating the name of the file in each location is often redundant, and large AST trees carry thousands of these attributes. Providing an option to have them removed at least for serialization (as anything more would be a breaking change) seems like a good compromise.
For reference, see https://github.com/StyraInc/regal/issues/408

Add ExcludeLocationFile JSON marshalling option

---

ast/annotations.go
ast/builtins.go
ast/check.go
ast/compile.go
ast/compile_test.go
ast/parser.go
ast/policy_test.go
ast/term.go

Reducing the reliance on deprecated functions makes it easier to delete them later. Fixing these warnings reduces IDE clutter as IDEs highlight these and show them in code reports, increasing noise that might help devs identify issues that could actually represent problems. 
- Replaced instances of deprecated .Path() with equivalent .Ref().GroundPrefix()
- Replaced instances of deprecated .Args() with equivalent .FuncArgs().Args
- Renamed variables to not collide with reserved words or imported packages

Fix IDE warnings and remove usage of several deprecated fields.

---

ast/compile.go
ast/compile_test.go

when:
* strict-mode is enabled
* `rego.v1` is imported
Fixes: #6291

ast: Disallow root document shadowing in leading term of rule refs

---

sdk/opa_test.go

Add two environment variable tests which illustrate how an environment variable can be used in OPA to verify a JWT.

sdk_test: add environment variable tests

---

ast/builtins.go
builtin_metadata.json
capabilities.json
test/cases/testdata/rendertemplate/rendertemplate.yaml
topdown/template.go

closes: #6371 
Adds a builtin function for template rendering.
Adds a new builtin function that accepts a templated string and a mapping of vars to inject, and returns the rendered string with the vars injected.
For this builtin function, I've set the `missingkey` option to `error`, so that if the template contains a variable that is not present in the given variable mapping, the function will not attempt to render the template and return an error. This was done to prevent silent failures from occurring.

feature(builtins): add a new builtin function to render templated strings

---

docs/content/configuration.md

Broken link for disk storage page on configuration page
Replaced broken link with current storage link

fix: Disk storage broken link

---

Makefile

The output is extremely noisy and there does not seem to be a good reason for it to be enabled all of the time.

chore: Disable verbose output in wasm-sdk-e2e-test

---

ast/capabilities_test.go
ast/internal/tokens/tokens.go
ast/parser_test.go
cmd/eval_test.go

In https://github.com/open-policy-agent/opa/issues/6432 @anderseknert pointed out that the ident string representation is not ideal. This PR just changes it to "identifier" so that it's a bit clearer.

Tweak the ident token string representation

---

cmd/check.go
cmd/check_test.go
cmd/filters.go

When non-rego files are included in a directory passed to `opa check`, the command fails with an error like this: 
```1 error occurred during loading: check-tests/test.json: merge error```. See https://github.com/open-policy-agent/opa/issues/6317 for more details.
This PR adds an option to the `loaderFilter` used by the `opa check` command that will exclude all files not ending in `*.rego`. This filter is optional but can be reused by other commands as necessary.

Add a default filter to `opa check` to only load and check `.rego` files

---

plugins/rest/rest.go
plugins/rest/rest_test.go

Decision logs had previously been configured to hide the value of the Authorization header, as that is considered sensitive information. However, there are cases when additional headers are provided that contain sensitive information, such as the X-AMZ-SECURITY-TOKEN header. These values were being logged in plaintext, despite being equally sensitive.
This PR creates an internal map of headers that should be masked, which can be expanded if additional headers are required. It then loops over the headers in a request, and performs a lookup on the internal map to see if any of them match those that should be masked. If so, it replaces their values with "REDACTED". An existing test was added to check both the header keys that should be masked, as well as a key that should not.
An existing …

plugins/rest: masks X-AMZ-SECURITY-TOKEN header in decision logs

---

docs/content/comparison-to-other-systems.md

The XACML Policy given as example in the [documentation page _Comparing to other systems_](https://www.openpolicyagent.org/docs/latest/comparison-to-other-systems/#xacml) is not valid XML/XACML.
This fixes several issues with the Policy:
- XML namespace undefined (`xmlns=...` is missing), therefore XACML version undefined. Fixed to use the latest [XACML 3.0](http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-en.html) standard.
- Missing mandatory `Version` attribute on Policy
- Missing mandatory `Category` and `MustBePresent` attributes on the `AttributeDesignators` in the `Rule`
- Old/obsolete syntax: Actions, ActionMatch, ActionAttributeDesignator (XACML 2.0?)
-  There is no check on the action in the OPA policy, so remove it from the XACML policy as well (useless).
N/A
N/A

Fixed the invalid XACML Policy in documentation (Comparing to Other Systems) to be XACML 3.0 compliant

---

cmd/fmt.go
cmd/fmt_test.go

There's a hidden dependency on the `diff` command, which can fail if there is no diff tool installed. 
- Replaces the call to `diff` with a call to the go-diff library, which is already installed
- Adds tests to the modified `formatFile` function to improve coverage
I wanted to add more tests to continue to improve coverage, specifically for the `-w` flag, but that's beyond the scope of this issue and would have taken some lengthy digging into the `util/test` package. Is there a general coverage improvement issue that can be used for things like that?
Fixes #6284

cmd: removes hidden dependency on diff command

---

docs/content/configuration.md

This option is only available when using OPA from go and not in the server.
Context: https://github.com/open-policy-agent/opa/issues/1336
This caused some confusion today in the OPA slack: https://openpolicyagent.slack.com/archives/CBR63TK2A/p1701966178974619

docs: Update note about use of manual triggers

---

README.md

This is a minor readme update to feature some more recent talks.

docs: add some more links to OPA talks

---

format/format.go
format/testfiles/test_functions.rego
format/testfiles/test_functions.rego.formatted

And add test cases using chained bodies, as that would previously get mistaken for implicit return without chaining.
Fixes #6467

fmt: restrict `= true` rewrite to functions with implicit true

---

test/cases/testdata/providers-aws/aws-sign_req.yaml
topdown/providers.go

Currently while all the headers are signed the headers in the returned object are missing all the original user provided headers This means that if you pass the object directly to http.send amazon will fail the request because the signed data doesn't match the canonical request. Users can work around it by using object.union to restore the original headers, but would be nice to avoid that extra step

Preserve user provided http headers in aws.sign_req

---

cmd/run.go
runtime/runtime.go
server/certs.go
server/server.go
server/server_test.go

Fixes https://github.com/open-policy-agent/opa/issues/5788
This PR makes the following changes:
* Adds a new `WithTLSConfig` option on the server to support the setting of a cert, key and ca cert at the same time. Previously, it was only possible to set the cert and key, in addition to a polling duration with `WithCertificatePaths`.
* Adds a test for this in `TestFSNotifyCertReloading` and the interval reloading in `TestIntervalCertReloading`. These tests are really verbose, and the cert fixture creation might be best if DRYed up some.
* Makes it possible to reload the CA certs when the pool file changes on disk. Previously, this was static post init.
* Retains the `WithCertificate` and `WithCertPool` runtime options as well as the polling behaviour if the interval is set in …

server: Support fsnotify reloading of certs

---

server/server.go

This was missed in https://github.com/open-policy-agent/opa/pull/6415
https://github.com/open-policy-agent/opa/actions/runs/7194437460/job/19595009978?pr=6476
We have a warning of this data race here:
```
==================
WARNING: DATA RACE
Write at 0x00c009b562e8 by goroutine 1815:
github.com/open-policy-agent/opa/server.(*Server).reloadTLSConfig()
/src/server/certs.go:65 +0x608
github.com/open-policy-agent/opa/server.(*Server).getListener.(*Server).certLoopNotify.func2()
/src/server/certs.go:174 +0x434
github.com/open-policy-agent/opa/server.TestCertPoolReloading.func1()
/src/server/server_test.go:5105 +0x4f
github.com/open-policy-agent/opa/server.TestCertPoolReloading.func2()
/src/server/server_test.go:5108 +0x41
Previous read at 0x00c009b562e8 by goroutine 1824: …
```

server: Use tlsConfigMtx when accessing certpool

---

internal/report/report.go
internal/report/report_test.go
plugins/plugins.go
plugins/plugins_test.go
runtime/runtime.go

This commit extends the telemetry report to include the
minimum compatible version of policies loaded into OPA.
This information can be helpful to get visibility into
era of Rego being adopted in the wild.
Fixes: https://github.com/open-policy-agent/opa/issues/6361
Co-authored-by: Stephan Renatus <stephan@styra.com>

Include OPA min compat version in telemetry report

---

tester/runner.go
tester/runner_test.go

It can be useful to know if Rego unit tests fail due to logic errors, or if a builtin raised an error, such as parsing JSON input that was typo'd.
Fixes #6489.

feat: Support raising builtin errors in the test runner

---

docs/content/policy-reference.md

Using the `sprintf` function to evaluate the type of a certain value, the current implementation is likely to cause confusion.
Clarify some of the intricacies when using `sprintf`.
See additional context in #6487

Docs: Explain %T behavior of sprintf

---

.github/workflows/post-merge.yaml

This PR attempts to fix the failures seen in the Post Merge workflow. Previously the token used in the checkout action had probably expired and a new token was generated to test out this hypothesis. Now that the Post Merge workflow [succeeds](https://github.com/open-policy-agent/opa/actions/runs/7254582557), we're renaming the token as before and updating the token value in the repo.

.github/workflows: Update name of the checkout action token

---

cmd/eval_test.go
internal/presentation/presentation.go

`nil` values for `any` are always rendered. I don't think there's a need to have `Location` be `interface{}` here, so I've changed it, cleaning up the output formatting without extra hurdles.
Random stackoverflow answer: https://stackoverflow.com/a/44321451/993018

internal/presentation: cleanup location handling

---

ast/compile.go
ast/parser.go
ast/parser_ext.go
ast/policy.go
bundle/bundle.go
bundle/store.go
bundle/store_test.go
cmd/build.go
cmd/build_test.go
cmd/check.go
cmd/check_test.go
cmd/eval.go
cmd/eval_test.go
cmd/flags.go
cmd/fmt.go
cmd/fmt_test.go
cmd/run.go
cmd/test.go
cmd/test_test.go
compile/compile.go
docs/content/cli.md
docs/content/opa-1.md
format/format.go
format/format_test.go
internal/runtime/init/init.go
loader/loader.go
rego/rego.go
rego/rego_test.go
tester/runner.go

This PR implements a small subset of the commands in #6463; namely `build` and `eval`. I'm not including more commands here to keep the scope of the PR tight, in part to make it easier to review, but also so that implementation of the remaining commands can be parallelized between multiple developers.
When applied, the `--rego-v1` flag will cause `opa build` and `opa eval` to behave strictly as they would in OPA 1.0 in regards to module parsing, compilation, and PE. The difference to the behavior of e.g. `opa fmt --rego-v1` is that this strict 1.0 behavior allows for policies using the `future` keywords without first importing `future.keywords` or `rego.v1`. E.g.:
```rego
package example
allow if {
input.x == 42
}
```
An open question is what this flag should be named. A couple of …

Adding `--v1-compatible` flag to `opa build` and `opa eval`

---

runtime/logging.go

Just to make @tsandall's comment reflect reality. 🌲

runtime/logging: actually do not panic when rctx is missing

---

docs/content/_index.md

missing 's' in the word 'public_server' in the code below data.example.public_server[s]

Fix a typo in _index.md

---

runtime/runtime.go
sdk/opa.go
server/server.go
topdown/cache/cache.go
topdown/cache/cache_test.go
topdown/http.go
topdown/http_test.go

* Regular clean up of cache entries that have expired for a more efficient use of memory. 
*  Removing stale entries regularly will make space for newer entries instead of forcefully evicting entries in a FIFO fashion which happens today. Sometimes entries in front might be long living cache entries (high TTL) that we would rather have in the cache.
Two new configurable parameters: 
* `inter_query_builtin_cache.forced_eviction_threshold_percentage`: By default `100`, an integer that denotes the percentage of `inter_query_builtin_cache.max_size_bytes` that cache usage can grow to before cache will start forcefully evicting entries in a FIFO fashion.
* `inter_query_builtin_cache.stale_entry_eviction_period_seconds`: By default `0`, an integer that represents the time period in seconds when …

Issue-5320 clean expired cache entries periodically

---

bundle/file.go
bundle/filefs.go

I compile bundle from key-value storage. But I can't implement DirectoryLoader for that beacause newDescriptor is private. I would like to use bundle.CustomReader. Is it possible? 
Thanks!

make func newDescriptor public

---

docs/website/layouts/partials/meta.html

This sets the default version for all non docs pages to latest.
We have recently started to list some pages in the search index from non docs pages, when a user makes a search, they search within the current version. This will make pages from the rest of the site available in the index when searching from 'latest'.

docs: update version for non docs pages

---

docs/website/layouts/partials/meta.html

https://github.com/open-policy-agent/opa/pull/6526 contained two errors, that I can see. First, it used `Permalink` rather than `RelPermalink`, this contains the host and scheme on build and so the older versions of pages were all getting version set to the latest.
Even if that had worked, the setting of version was incorrect and set a locally scoped var instead of the variable for the whole file.

docs: Fix issue in versioning docs for search

---

bundle/bundle.go
bundle/bundle_test.go
bundle/file.go
bundle/file_test.go
bundle/filefs.go
download/download.go

Previously we'd check the size limit *after* the file was read, which mostly defeats the point of the limit. Now we check the size from the header in the tar archive and exit early if it exceeds the configured limit.
In order to do this, I had to extend the `DirectoryLoader` interface with a method to set the max size. While I added implementations for the other (than tarball) loader types, the limit is not currently set anywhere for those. Perhaps we'll want to do that at some later point but it feels like this is mainly relevant when files are loaded via remote bundles.
Fixes #6514

Don't load files in tarball exceeding `size_limit_bytes`

---

cmd/run.go
cmd/run_test.go
runtime/runtime.go
server/server.go
test/e2e/tls/tls_test.go

This change adds a new flag to `opa run` to allow users to specify a list of enabled TLS 1.0–1.2 cipher suites. This allows users to control the cipher suites the OPA server supports during a TLS handshake.

Allow TLS cipher suites to be set for the OPA server

---

ast/parser.go
ast/parser_ext.go
format/format.go
loader/loader.go

to remove API ambiguity.
Also deprecating `ParserOptions.EffectiveRegoVersion()`, which will be removed in a future release.

Removing deprecated fields and functions related to rego-v1 compatibility

---

logging/logging.go
logging/logging_test.go

When only passing a single string into a Printf-style function, any %-format specs in it will be filled accordingly; but there will be no arguments to use.
So now, we'll avoid calling the `{Debug,Info,Warn,Error}f` functions when we lack arguments.

logging: avoid '%!F(MISSING)' in logs

---

docs/content/rest-api.md

This is a recognized content type now, so no need for the x prefix. Thanks @chendrix for making me aware of that.
I also fixed some language issues in the doc while at it.

docs: use application/yaml instead of application/x-yaml

---

docs/content/rest-api.md

This change updates the description of how the url path is used to access values inside object and array documents. For data patch operations, the description was updated to reflect the implementation.

docs: Udpate description of the url path usage for v1/data GET and POST

---

.github/workflows/pull-request.yaml
download/oci_download_unavailable.go

In https://github.com/open-policy-agent/opa/pull/6159 I introduced a disabled OCI downloader to get rid of dependency on containerd to minimise the CVE surface. https://github.com/open-policy-agent/opa/pull/6521/files#diff-f808512360f39e5c4f67342ca24d84117be5403637b032d67e82df3a425cdde9R139 broke our builds adding a method only to one of the implementations. 
In this PR I added an interface (should show up in IDE) and a CI check (makes sure building `make GO_TAGS="-tags=opa_no_oci" build` works) to see if everything builds with `GO_TAGS="-tags=opa_no_oci"`.
There supposed to be a long term solution for (getting rid of containerd) this but it seems that it was not implemented.
Hope you don't mind me doing a PR - if you want to move this to an issue and discuss - feel free to do so, or tell …

fix(oci): oci downloader unavailable missing WithBundleParserOpts method

---

docs/content/policy-language.md

This link should point to #annotations on the same page.

docs: fix broken schema link

---

format/format.go
format/testfiles/test.rego
format/testfiles/test.rego.formatted

This fix preserves the brackets around set union operations when the inflix operator (`|`) is used. Previously the formatter would remove the brackets around the union operation, interpreting the expression as a comprehesion which would yeild unexpected results.
Fixes: #6588

format: Preserve brackets around set union operation

---

docs/content/_index.md

And replace AMD64 option with ARM64 as that's likely what most Macs run with these days.
Fixes #6622

Docs: mention homebrew install option

---

docs/content/policy-reference.md
internal/providers/aws/signing_v4.go
internal/providers/aws/signing_v4a.go
plugins/rest/aws_test.go
test/cases/testdata/providers-aws/aws-sign_req-errors.yaml
test/cases/testdata/providers-aws/aws-sign_req.yaml
topdown/providers.go

To support uses cases where OPA is used for signing s3 requests whose payload is not known upfront or payload is big enough (big file upload) to be sent over wire, this PR adds support for unsigned payloads.
AWS signer has configurable option to use unsigned payload where the x-amz-content-sha256 is set to "UNSIGNED-PAYLOAD" and is included as part of signing process. This PR provides an option for unsigned payload if aws_config.disable_payload_signing is set to true. If payload signing is disabled, SignV4 method will not compute the content sha from the request body but instead use "UNSIGNED-PAYLOAD" string literal for x-amz-content-sha256 header during signature computation.
References:
https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html …

aws: support for Unsigned Payload or provided content sha256 in AWS signing (#6581)

---

docs/content/aws-cloudformation-hooks.md

This is a simple PR which adds Tunnelmole as an open source tunneling option in the Cloudformation hook documentation.

Add Tunnelmole as an open source tunneling option in the Cloudformation hooks documentation

---

build/generate-cli-docs/generate.go

Not sure where to put this really as we don't have much in terms of docs on the CLI outside of the generated ones. If there are more places where this could be mentioned, let me know and I'll add it there too.

Add some docs on using env vars in place of CLI flags

---

test/e2e/logs/remote/remote_decision_logger_benchmark_test.go

This PR fixes a tiny issue: a missing import in `test/e2e/logs/remote/remote_decision_logger_benchmark_test.go`, which comes up as part of the `make perf-noisy` makefile target.
The missing import shows up in VS Code like this:
And appears in the makefile run like so:
```sh-session
$ make perf-noisy 
make[1]: Entering directory '/home/.../opa-conradp/wasm'
make: '_obj/opa.wasm' is up to date.
make: '_obj/callgraph.csv' is up to date.
make[1]: Leaving directory '/home/.../opa-conradp/wasm'
cp wasm/_obj/opa.wasm internal/compiler/wasm/opa/opa.wasm
cp wasm/_obj/callgraph.csv internal/compiler/wasm/opa/callgraph.csv
CGO_ENABLED=1 GOFLAGS=""-buildmode=exe"" go generate
CGO_ENABLED=1 GOFLAGS=""-buildmode=exe"" go test -tags=opa_wasm,slow,noisy -timeout 30m -run=- -bench=. -benchmem ./... …
```

test/e2e: Fix missing import in benchmark.

---

CHANGELOG.md
cmd/exec.go
cmd/exec_test.go
cmd/internal/exec/exec.go
docs/content/cli.md

This PR adds a `--timeout` duration flag to the `opa exec` CLI command. This flag helps out in use cases such as CI, where stalling indefinitely is undesirable behavior.
Fixes: #6613
Also included:
- Unit test under `cmd/exec_test.go`
- Release notes section under the `## Unreleased` banner (so the CHANGELOG automation *should* hide it by default, until someone moves the text under the next release header).
- CLI docs updated.

cmd/exec: Add timeout flag to help prevent infinite hangs.

---

bundle/store.go
docs/content/management-bundles.md

Running remove operation on data that is not present should not return an error.
In function `applyPatches` call `suppressNotFound` function on the output of `store.Write` if operation is remove

Suppress not found error when applying remove operation

---

ast/builtins.go
builtin_metadata.json
capabilities.json
topdown/crypto.go
topdown/crypto_test.go

parse and verify x509 certificates with additional options in package x509.crypto was requested
a new builtin function was added.  Following files are modified
ast/builtins.go
topdown/crypto.go
topdown/crypto_test.go
builtin_metadata.json
capabilities.json

Adding a new function crypto.x509.parse_and_verify_certificates_with_options

---

download/download.go
download/download_test.go
download/testharness.go

This change logs the error response body at debug level. Since the errors could contain senstive info we don't include them in the status message. So this approach helps to get more information about the error at debug log level which is mostly used in a non-prod setup.
Fixes: #6609

download: Surface bundle download errors via debug logging

---

sdk/opa.go
sdk/opa_test.go
sdk/options.go

This commit adds the possibility to configure the plugin manager with custom options.
It will allow SDK users to override the options already provided by the SDK and to futher customize it with configurations that were not previously available. This is an advanced feature as it requires some knowledge about the inner workings of OPA.
One use case for this is to provide a prometheus registerer and have the status plugin metrics available for the client to use it in a /metrics endpoint, for example.
resolves #6662
Currently there is no way to customize the options of the plugin manager. As an example, if I use the OPA SDK in a golang 
http server, I cannot export the prometheus metrics provided by the status plugin in a `/metrics` endpoint.
I have exposed the manager options in the SDK …

Expose manager options

---

compile/compile.go
compile/compile_test.go

This PR fixes a panic that could occur when `opa build` was provided an entrypoint from both a CLI flag, and via entrypoint metadata annotation.
The fix is simple: deduplicate the slice of entrypoint refs that the compiler uses, before compiling WASM or Plan targets.
Fixes: #6661
Thanks to @dxh9845 for reporting this one, and for putting together the initial repro test case!

compile/compile: Fix panic from CLI + metadata entrypoint overlaps.

---

server/server.go
server/server_test.go

This time for v0QueryPath, v1DataGet, and v1DataPost.

server: Remove unnecessary AST-to-JSON conversions.

---

server/certs.go
server/server_test.go

In workflow runs like this:
https://github.com/open-policy-agent/opa/actions/runs/7803493290/job/21283458848#step:3:317
We can see two problems, the test flakes and there is a lot of output. This PR is meant to address them.
**First**, the test failed with this message:
```
expected unknown certificate authority error but got: Get "https://127.0.0.1:38699/v1/data": write tcp 127.0.0.1:52786->127.0.0.1:38699: write: connection reset by peer
```
Now this step in the test is retried like the other steps in the test since it can fail too.
**Second**, the error `failed to reload TLS config` appears many times in the logs for that test. This issue is caused by the server attempting to read the new cert, key, and CA contents from disk while they are still being written to. This PR also …

server: Retry cert reloading & test case step

---

dependencies/deps.go
dependencies/deps_bench_test.go

Improving memory footprint and execution time of `deps` command for policies with high dependency connectivity.
Fixes #6685

deps: Improving `deps` command performance

---

docs/content/policy-language.md

The change involves using a cuboid rather than a cube to explain concepts of sets and composite values in policy-language section of documentation.
The changes are in a single file i.e. policy-language.md

fixes #6206; using cuboid rather than cube

---

.github/workflows/post-merge.yaml
.github/workflows/post-tag.yaml
.github/workflows/pull-request.yaml

This PR updates the `upload-artifact` and `download-artifact` Github actions to the latest version (v4), which should eliminate the deprecation warning spam we're seeing in CI.
<details>
<summary><i>Screenshot of an older CI run's warnings (non-exhaustive)</i></summary>
</details>
**Note to reviewers:** The release (`post-tag`) and `post-merge` workflows have been updated as well, with the same general strategies used for the more complex `pull-request` workflow.

ci: Update Github Actions for Node 20.

---

ast/parser.go
ast/parser_test.go
cmd/bench_test.go
cmd/eval_test.go
rego/rego.go

When `rego.v1` is in the list of imports directly applied on the `rego.Rego` SDK struct, this import, and it's effects, is applied to the query when parsed. 
This change affects the `eval` and `bench` commands when the `--imports` flag is used.
Fixes: #6701

rego: Setting query Rego-version from configured imports

---

Makefile
build/run-wasm-rego-tests.sh

This change updates the WASM Rego test generation docker command to address CVE-2022-24765 in Git which could cause it to execute arbitrary commands.
The error was seen when running the `make wasm-rego-test` target on darwin/arm64.
Fixes: #6703

build: Update WASM Rego test generation setup

---

plugins/rest/auth.go

We are currently leaking sockets. These are open unclosed sockets from 7 days ago
```
ls -l /proc/1/fd/*|grep socket
lrwx------    1 core     core            64 Apr 16 13:00 /proc/1/fd/3 -> socket:[22595818]
lrwx------    1 core     core            64 Apr 16 13:00 /proc/1/fd/7 -> socket:[94892]
lrwx------    1 core     core            64 Apr 16 13:00 /proc/1/fd/8 -> socket:[22592372]
lrwx------    1 core     core            64 Apr 16 13:00 /proc/1/fd/9 -> socket:[22589424]
```
Close the response body after requesting a token

auth: requestToken close response body

---

CHANGELOG.md
docs/content/management-discovery.md
plugins/discovery/discovery.go
plugins/discovery/discovery_test.go
plugins/logs/plugin.go
runtime/runtime.go
sdk/opa.go

Previously if Discovery was enabled, other features like bundle downloading and status reporting could not be configured manually. The reason for this was to prevent OPAs being deployed that could not be controlled through discovery. It's possible that the system serving the discovered config is unaware of all options locally available in OPA. Hence, we relax the configuration check when discovery is enabled so that the bootstrap configuration can contain plugin configurations. In case of conflicts, the bootstrap configuration for plugins wins. These local configuration overrides from the bootstrap configuration are included in the Status API messages so that management systems can get visibility into the local overrides.
**In general, the bootstrap configuration overrides the discovered …

Relax configuration check when Discovery is enabled

---

server/server.go
server/server_test.go

This change attempts to keep the default decision path used by the server in sync with the one defined on the manager's config. Currently the server only updates the default decision path when it's initialized and when there is a commit on the store. The issue happens when the default decision path is updated via the discovered config. In this case, the manager's config is updated but there could be no store txn. Hence the updated value of default decision path is not taken into account by the server.
Fixes: #6697

server: Keep default decision path in-sync with manager's config

---

.github/workflows/post-merge.yaml
.github/workflows/post-tag.yaml
.github/workflows/pull-request.yaml

Close https://github.com/open-policy-agent/opa/issues/6720
To release pre built binaries for darwin/amd64.
- Pin GitHub Actions macos runner version to `macos-14`
- CPU architecture of `macos-latest` was changed from amd64 to arm64. To avoid the same issue, we should pin the version
- Build and release a pre built binary for darwin/amd64
Please see https://github.com/open-policy-agent/opa/issues/6720 .

ci: pin GitHub Actions macos runner version and build for darwin/amd64

---

docs/content/policy-testing.md

Best practice according to https://docs.styra.com/regal/rules/testing/test-outside-test-package is to have tests in a package with `_test` suffix, but this is not documented anywhere. 
Updating the examples is an easy way to teach readers the best practice
Changes to the example rego test files and output snippets

Use best practice package name in test examples

---

internal/providers/aws/util.go

Currently we only read response body if the response is 200 or if we have debug flag enabled.
As the go package documentation states
```
If the Body is not both read to EOF and closed, the [Client](https://pkg.go.dev/net/http#Client)'s underlying [RoundTripper](https://pkg.go.dev/net/http#RoundTripper) (typically [Transport](https://pkg.go.dev/net/http#Transport)) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.
```
A typical production server that receive errors responses from AWS will be less efficient. 
Always read the response.

aws: util always read resp.body

---

internal/providers/aws/util.go

We don't need to check if debug is enabled, before using logger.debug, its already explicit.
Should have caught this in, https://github.com/open-policy-agent/opa/commit/7c0278eebd2030a334750e29aade091ef9e56cb0
Remove if logger level is debug

fix: aws util remove if debug clause

---

plugins/rest/auth.go
plugins/rest/aws_test.go

I am attempting to address https://github.com/open-policy-agent/opa/issues/6580
ECR serves OCI blobs by redirecting to S3 using pre-signed URLs. Currently, OPA adds the ECR auth header to the S3 request in addition to the pre-signed parameter, and S3 returns a 400 Bad Request:
```
Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified
```
I removed the auth header from the redirects to S3.
I hesitated between checking whether the request is generated by a 307 redirect, or whether the request host matches the host specified in the OPA OCI config. I went for the second option because http auth is usually tied to a specific origin, and should not be shared across origin. The `Prepare` …

auth: Disable the Authorization header for ECR redirects.

---

runtime/runtime.go
runtime/runtime_test.go

When running OPA with the distributed tracing option enabled, the OpenTelemetry trace exporter is not gracefully shut down when the server is stopped.
This PR fixes that issues by moving the trace exporter shutdown in the gracefulServerShutdown function.
Picked up from https://github.com/open-policy-agent/opa/pull/6664
Fixes #6651.
This bug seems to have been introduced by this [commit](https://github.com/open-policy-agent/opa/commit/f063c90275bed61c4381db771162724e191f2d3c).

Fix OpenTelemetry graceful shutdown.

---

ast/term.go
internal/compiler/wasm/wasm.go
internal/planner/planner.go
ir/ir.go
test/cases/testdata/every/every.yaml
test/cases/testdata/every/non_iterable_domain.yaml
topdown/eval.go

Asserting `every` domain is an iterable type before evaluation

---

docs/content/policy-reference.md

Found via https://github.com/FallenAngel97/tree-sitter-rego , which used the OPA grammar for its tree-sitter implementation, and had this missing.

Add remainder operator to grammar

---

plugins/rest/auth.go

Fixes: #6769
Shared struct field map modifications were replaced with method local map modification

Fix issue #6769

---

ast/parser.go
ast/parser_test.go

This one has been among my top annoyances, and thanks to @johanfylling, it was easy to finally track down. Had to update a few tests, but not too many.
Fixes #6563

Fix blanket "unexpected assign token" error message / usability issue

---

docs/content/monitoring.md

This PR marks the `go_memstats_gc_cpu_fraction` metric on the [Monitoring page](https://www.openpolicyagent.org/docs/latest/monitoring/) as removed, with a link to the upstream Prometheus issue. (See issue #6783)
Alternately, we could just remove the offending table row, instead of modifying it in-place with styling. Let me know which solution is better!

docs/content/monitoring: Drop missing Prometheus metric `go_memstats_gc_cpu_fraction`

---

internal/providers/aws/util.go

- To decide whether to use an or a: https://www.merriam-webster.com/grammar/is-it-a-or-an
- Spelling of HTTP: https://en.wikipedia.org/wiki/HTTP

Fix spelling and grammar of an HTTP

---

docs/content/policy-language.md

docs: mention that default functions may not evaluate

---

loader/errors.go
loader/loader_test.go

Use a better error message when trying to merge non-objects

---

ast/parser.go
ast/parser_test.go

Previously it would just say '# METADATA'
Fixes #6779

Include original text in annotation location text attribute

---

ast/parser.go
ast/parser_test.go

Fix wrong location on metadata parse errors on first line

---

bundle/bundle.go
bundle/file.go
bundle/file_bench_test.go

This PR reduces the max [RSS][rss] memory usage of OPA during bundle loading by about 5-6%, and greatly improves GC performance at lower values of GOMAXPROCS.
[rss]: https://en.wikipedia.org/wiki/Resident_set_size
This improves OPA's performance particularly for container and low-resource use cases by reducing the peak of the spike in memory usage, and also reduces garbage collector overheads.
This PR adds logic to preallocate buffers when loading files from both tarballs and on-disk bundle directories. The change results in lower max RSS memory usage at runtime, and better garbage collector performance, especially when at lower values of `GOMAXPROCS`.
For very large bundles (>1 GB in size), this change can lower startup times for OPA by as much as a full second.
Huge thanks to …

bundle: Preallocate buffers for file contents.

---

Makefile

As some people may have restrictions that don't let them user other docker image registries.

build: use chainguard images from dockerhub

---

cmd/exec.go
cmd/exec_test.go
cmd/internal/exec/exec.go
cmd/internal/exec/exec_test.go
cmd/internal/exec/json_reporter.go
cmd/internal/exec/json_reporter_test.go
cmd/internal/exec/params.go
cmd/internal/exec/params_test.go
cmd/internal/exec/parser.go
cmd/internal/exec/parser_test.go
cmd/internal/exec/std_in_reader.go
cmd/internal/exec/std_in_reader_test.go
docs/content/cli.md

- adds `--std-in` flag to `exec` command
- adds test coverage to `cmd/internal/exec` package
- updates `exec` command docs with new flag
Can test with input piping, e.g. `echo "{\"foo\": 8}" | opa exec ...` or manual entry via Stdin.
Fixes #6538

cmd/exec: adds --stdin-input (-I) flag for input piping or manual entry

---

cmd/exec.go
cmd/internal/exec/exec.go
cmd/internal/exec/exec_test.go

Previously, `opa exec --stdin-input input1.json input2.json` would read input from stdin, but ignore the provided input file paths.

cmd/exec: Supporting simultaneous input from stdin and files

---

ast/compile.go
ast/compile_test.go
test/cases/testdata/every/every.yaml

ast: expanding nested expressions in `every` domain

---

server/authorizer/authorizer.go
server/server.go
server/server_test.go
util/read_gzip_body.go

This PR fixes an issue where an OPA running authorization policies would be unable to handle gzipped request bodies.
Example OPA CLI setup:
```shell
opa run -s --authorization=basic
```
Example request:
```shell
echo -n '{}' | gzip | curl -H "Content-Encoding: gzip" --data-binary @- http://127.0.0.1:8181/v1/data
```
This would result in unhelpful error messages, like:
```json
{
"code": "invalid_parameter",
"message": "invalid character '\\x1f' looking for beginning of value"
}
```
The cause was that the request body handling system in the `server/authorizer` package did not take gzipped payloads into account. The fix was to borrow the gzip request body handling function from `server/server.go`, to transparently decompress the body when needed.
Fixes: #6804

server/authorizer: Fix gzip payload handling.

---

cmd/exec.go
docs/content/cli.md

This makes it safer to process this text into markdown and other formats. (`<path>` is tricky as it looks like an HTML tag.
CLI output would look like this:
```
$ go run main.go exec --help
...
e.g., opa exec --decision /foo/bar/baz ...
Usage:
main exec <path> [<path> [...]] [flags]
Examples:
Loading input from stdin:
main exec [<path> [...]] --stdin-input [flags]
```

docs: Use Example field for alternative commands

---

bundle/bundle.go
bundle/file.go
bundle/filefs.go
cmd/build.go
cmd/build_test.go
compile/compile.go
internal/pathwatcher/utils.go
internal/runtime/init/init.go
loader/loader.go
runtime/runtime.go

Per https://github.com/open-policy-agent/opa/issues/6495, it is important to users using build systems like babel to allow `opa build` to include symlinked files in the bundle directory. Bazel and other build tools create sandboxes of symlinked files before building. As it stands today, `opa build` only includes regular files and directories by default.
This PR adds a boolean flag, `--follow-symlinks` to the `opa build` command to allow users to build directories with symlinked files, and have the contents of those symlinked files included in the built bundle.
I've included tests for the build command but would appreciate a critical eye as to any other areas that could use testing. Also, I've kept the symlink changes as constrained to the `build` features as possible, but there are many …

Add flag to follow symlinks when running opa build

---

docs/content/http-api-authorization.md
docs/content/integration.md
docs/content/rest-api.md

The SDK support is there for many languages now and these are likely a preferred way to use OPA's REST API for many application developers.
This PR adds some links to make sure these are featured in suitable locations so they are not missed as people browse the docs.

docs: Better link language SDKs

---

ast/policy.go
ast/rego_v1.go
cmd/fmt.go
format/format.go
format/testfiles/rego_v1/keywords.rego
format/testfiles/rego_v1/keywords.rego.error

format: Produce error when `--rego-v1`  formatted module has rule name conflicting with keyword

---

download/oci_download.go
go.mod
go.sum
vendor/github.com/containerd/containerd/errdefs/errdefs_deprecated.go
vendor/github.com/containerd/containerd/version/version.go
vendor/modules.txt

Refer https://github.com/open-policy-agent/opa/pull/6875 for release details.

build(deps): bump github.com/containerd/containerd from 1.7.19 to 1.7.20

---

cmd/inspect.go
cmd/inspect_test.go
internal/bundle/inspect/inspect.go
util/maps.go
util/maps_test.go

Resolves https://github.com/open-policy-agent/opa/issues/6799 by adding the ability for the `opa inspect` command to handle single files in addition to the currently supported bundle directory and tarball options. This PR is necessary to improve the UX of inspecting annotations in a single file.
Adds a new method and decision tree to the `opa inspect` command that will process a single file if the argument passed to the command ends with `.rego`. Will follow other `opa inspect` processing semantics and behavior - changes are constrained to loading the single file and processing it as its own entity outside of the scope of a bundle.
I'm not terribly familiar with OPA's WASM capabilities yet - @anderseknert is there anything in this issue you were thinking would extend to WASM as well that …

Add ability for opa inspect to inspect a single file outside of any bundle

---

CHANGELOG.md
config/config.go
config/config_test.go
docs/content/configuration.md
plugins/server/decoding/config.go
plugins/server/decoding/config_test.go
server/authorizer/authorizer.go
server/handlers/decoding.go
server/server.go
server/server_test.go
server/types/types.go
util/decoding/context.go
util/read_gzip_body.go

In a [recent bugfix PR][opa-pr-6825], I discovered some performance issues around how request bodies are handled in OPA, particularly when the request is gzipped. This PR is a follow-up to that one, and changes how OPA reads request bodies.
The main performance benefits of this PR come from reducing the workload of the Golang GC, and also by removing redundant `Read` operations on the request body.
This PR preallocates the entire buffer for a request body (and also for its decompressed payload) when possible. This reduces max [RSS][wikipedia-rss] for large requests by around 5-10%, and reduces GC overhead by 33-66% for large requests, while not penalizing small (<1kb) requests.
The changes are structured as follows:
- `docs/`: Updated for the new config options.
- …

server+util: Limit max request sizes, prealloc request buffers

---

docs/content/management-bundles.md
repl/repl.go
runtime/runtime.go
runtime/runtime_test.go

This change updates the repl so that the modules in the
provided bundle are parsed based on the `rego_version` attribute
in the bundle manifest. Currently that is ignored which leads
to parsing failures.
Fixes: https://github.com/open-policy-agent/opa/issues/6872

repl: Add support for correctly loading bundle modules

---

server/server.go

To enable missing functionality referenced by the REST API docs.
Add handling for the `types.ExplainFailsV1` type to the server code.

server: Add missing handling for `explain=fails` to the REST API.

---

docs/content/configuration.md
plugins/rest/aws.go
plugins/rest/aws_test.go

Support loading credentials from the AWS_CONTAINER_CREDENTIALS_FULL_URI metadata endpoint which is helpful for AWS SnapStart lamdbas
Fixes #6893
---
Not modifying any tests as it doesnt look like we test this url resolution anyway. 
See [AWS Docs](https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html#:~:text=Note%3A%20This%20setting%20is%20an%20alternative%20to%20AWS_CONTAINER_CREDENTIALS_RELATIVE_URI%20and%20will%20only%20be%20used%20if%20AWS_CONTAINER_CREDENTIALS_RELATIVE_URI%20is%20not%20set.) for more information on why this is needed

fix: Support AWS_CONTAINER_CREDENTIALS_FULL_URI metadata endpoint

---

CHANGELOG.md
server/handlers/decoding.go
server/server_test.go
util/decoding/context.go
util/read_gzip_body.go

This PR fixes a request handling bug introduced in #6868, which caused OPA to treat all incoming chunked requests as if they had zero-length request bodies.
The fix detects cases where the request body size is unknown in the DecodingLimits handler, and propagates a request context key down to the `util.ReadMaybeCompressedBody` function, allowing it to correctly select between using the original `io.ReadAll` style for chunked requests, or the newer preallocated buffers approach (for requests of known size).
This change has a small, but barely visible performance impact for large requests (<5% increase in GC pauses for a 1GB request JSON blob), and minimal, if any, effect on RPS under load.
Fixes: #6904
- A new context key is passed down from the `DecodingLimits` handler wrapper in …

util+server: Fix bug around chunked request handling.

---

plugins/bundle/plugin.go

This change attempts to fix a race condition that could occur when a reconfiguration on the bundle plugin occurs in parallel with the activation of a downloaded bundle.
One scenario where this could occur is when the discovery plugin attempts to reconfigure the bundle plugin and concurrently a bundle gets downloaded and needs to be activated. A reconfig operation will perform a write on the plugin's config. During a bundle activation, the plugin's config is read. Currently we hold a lock when the config is being updated. This change locks the config while reading thereby avoiding the race.
Fixes: #6849
Co-authored-by: Pushpalanka Jayawardhana <pushpalanka.jayawardhana@zalando.de>

plugins/bundle: Avoid race during bundle reconfiguration and activation

---

build/run-wasm-rego-tests.sh

Tackling this "TODO":
https://github.com/open-policy-agent/npm-opa-wasm/blob/92b8aa0234a7e487f2bd335ea1544351718972f7/.github/workflows/ci.yml#L50-L52
as I'm in the same situation:
https://github.com/andreaTP/opa-chicory/blob/d37da558e054510e50da53bf7a1933e0bc19a136/.github/workflows/ci.yml#L33-L34
Add the handling for an env var `WASM_BUILD_ONLY` so that, running:
```
WASM_BUILD_ONLY=true make wasm-rego-test
```
Would not run the tests saving time and container images downloads.
Attempted to do the least intrusive possible change.
An additional step would be to upload the resulting `testcases.tar.gz` to GH releases, but I'm looking for feedback before doing the changes.

Make it possible to only build wasm testcases

---

ast/compile_test.go
ast/index.go

Only appending rule to trieNode values list if it has declared value.
Fixes: #6930

ast: Fixing nil pointer dereference in compiler for partial rule edge case

---

loader/loader.go
loader/loader_test.go

If a UNC path is provided to OPA it won't read it
and instead return an error. This applies to paths
to load bundles and individual data/policy files.
One reason behind blocking UNC paths is they could
trigger a NTLMv2 hash leak. For example, if a SMB share
is provided, OPA will attempt to open it triggering LLMNR
queries which contain the client's NTLMv2 hash which can be cracked
using some tools. This could be exploited by a malicious user.

loader: Avoid reading UNC paths by default

---

.github/workflows/codeql-analysis.yml
.github/workflows/nightly.yaml
.github/workflows/post-merge.yaml

To improve the scorecard score and security of the project
fixed the token-pemission issue reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/open-policy-agent/opa) by adding the top-level read-only permissions block
Part of #6938 
None
None

fixed the token-pemission issue

---

ast/marshal_test.go
ast/policy.go

When the JSON option to include term locations have been set, they should be included in all parts of the head where terms appear.
Fixes #6860

Include term locations in rule heads when requested

---

ast/check.go

Just a small improvement from looking into #6946
This doesn't necessarily solve all issues reported there, but I figured I might as well commit this anyway.

Make type checker `copy` method copy all values

---

download/oci_download.go
download/oci_download_test.go

This commit fixes an issue related to zero-sized bundles being saved to disk, which can cause OPA to fail to start if a remote OCI repository is unavailable.
Fixes: #6939

download: Fix saving OCI bundles on disk

---

docs/content/configuration.md
docs/content/policy-language.md

It wasn't obvious when configuring the inter-query cache might be needed, as it wasn't mentioned which built-in made use of it.
Also fixed the docs on annotations where it said `scope` only applies to `schemas`.

docs: mention `http.send` in inter-query cache config docs

---

.github/workflows/codeql-analysis.yml

The CodeQL workflow uploads the results to GitHub so it needs a write value on the contents permission.

.github/workflows: Update CodeQL workflow contents perm

---

logging/logging.go
runtime/logging.go
runtime/logging_test.go
server/server.go
server/server_test.go

Previously the HTTP request context was included in the request context at the info access log level. This means if the access log level was set to error for instance, the context would not include the http request context and hence it would not be surfaced via decision logs.
This change always add the http request context to the request context so that HTTP info like headers will be surfaced via decision logs irrespective of the access log level.
Fixes: #6951

Always include HTTP request context in incoming req context

---

CHANGELOG.md
docs/content/configuration.md
internal/distributedtracing/distributedtracing.go
plugins/plugins_test.go
runtime/runtime.go
server/server_test.go

Adding a resource_attributes map to the distributed_tracing config. Entries in this map will be passed through to the OpenTelemetry SDK where they will be added as resource attributes. Resource attributes are typically service.namespace, service.version, service.name and service.instance.id, see https://opentelemetry.io/docs/specs/semconv/resource/
Fixes: #6942 
Allows extra OpenTelemetry resource attributes to be added to a trace, such as service.namespace
Adds an optional config `distributed_tracing.resource_attributes`, which is map of strings. Values here are
added via the opentelemetry SDK as resource attributes.
I didn't find any tests which verify the telemetry (trace) output, but I did apply the following config and observe this output:
<details>
<summary>config:</summary>
```yaml …
```

distributedtracing: adding distributed tracing resource attributes

---

plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

In Windows there are some reserved characters that cannot be used in the names of files and directories (eg. ?, *). If a bundle name contains these and if it's configured to be persisted, the operation will fail on Windows. This change attempts to fix this on Windows systems by escaping any encountered reserved characters before using them in the bundle persistence path.
Fixes: #6915

plugins/bundle: Escape reserved chars used in persisted bundle directory name

---

ast/policy.go
docs/content/configuration.md
docs/content/docker-authorization.md
docs/content/extensions.md
docs/content/management-discovery.md

And update some references throughout the docs.
Fixes #6959

Docs: suggest using `opa-config.yaml` as name for config file

---

ast/parser.go
ast/parser_test.go

Just an idea, if we ever introduce an
import awesome
and people start receiving "unknown import" errors on outdated OPA versions, they'll at least give a hint.
This could be extended to cover the other synthetic imports, like `rego.*` and `future.*`, but it's a start...

ast/parser: add hint to future-proof imports

---

ast/annotations.go
ast/annotations_test.go
cmd/build_test.go
compile/compile.go
compile/compile_test.go
docs/content/policy-language.md

And automatically change implied `scope` from `rule` to `document` when no `scope` is provided (on rule metadata).
Whether this can be included in a "normal" release, or will have to wait until OPA 1.0, I'll let others decide. But I think it's worth pointing out that this is a breaking change to address a **bug**, and that a scope of `rule` makes no sense for an entrypoint.
One alternative could perhaps be to only change this behavior when `import rego.v1` is included in a file, as that's meant to be a glimpse of the future anyway. But at this time, no such considerations have been taken.

Change required scope of `entrypoint` from `rule` to `document`

---

go.mod
go.sum
runtime/logging_test.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/modules.txt

In addition to the vendor update, a test case was updated to account for a prometheus change where the Content-Encoding header is unset if data is uncompressed.

build(deps): bump github.com/prometheus/client_golang from 1.20.1 to 1.20.2

---

ast/compile.go
ast/compile_test.go

It might be uncommon to do this, but it's not wrong to expect this to work.
Fixes #6979.

ast/compile: also replace declared vars in with's target

---

ast/check.go

This PR adds caching of schema types.
Fixes: https://github.com/open-policy-agent/opa/issues/6969

perf: cache schema types

---

ast/parser.go
bundle/bundle.go
compile/compile.go
compile/compile_test.go
format/format.go
rego/rego.go

Future-proofing `compiler` package tests to continue working when we flip the default rego-version to `v1` in OPA 1.0.
Also updating a few places that depended on `v0`-by-default assumptions.

rego-v1: Future-proofing `compiler` pkg tests

---

ast/policy.go
ast/policy_test.go
compile/compile_test.go
rego/rego_test.go

Fixes: #6973
This is also helpful for the v1 refactoring of tests we're currently doing.

ast: Make `Module.String()` include `if`/`contains` for v1 modules

---

topdown/http.go

Fixes incorrect `Timer` measuring in case of error. Without calling `Stop()` method when e.g. `eval_cancel_error` happens the last delta is not added to the accumulated `Timer` value.
I discovered it by investigating `eval_cancel_error` when the caller gave up but according to OPA metrics it looked like `http.send` did not cause it (I would expect near 10s value in `timer_rego_builtin_http_send_ns` too):
```
{"counter_rego_builtin_http_send_interquery_cache_hits":1,
"counter_server_query_cache_hit":1,
"timer_rego_builtin_http_send_ns":124580,
"timer_rego_input_parse_ns":4771,
"timer_rego_query_eval_ns":9770617400,
"timer_server_handler_ns":9770659804} 
```

Fix Timer stopping in http.send

---

plugins/rest/aws.go
plugins/rest/aws_test.go

Fixes #6724 
PR #6894 adds support for the [AWS container credential provider](https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html) but it is missing support for providing the token as file via the `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` environment variable. This mechanism is used by [EKS pod identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html).
When using the container credential provider we will attempt to load the token from file if `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` is set.  If both `AWS_CONTAINER_AUTHORIZATION_TOKEN` and `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` are set the former takes precedence.
The changes in this PR have been confirmed working in EKS.

Support reading AWS token from the filesystem

---

.github/workflows/pull-request.yaml
docs/website/layouts/partials/css.html
netlify.toml

In https://github.com/open-policy-agent/opa/pull/7033, I hoped to upgrade the Hugo version used to build the site. However, this was not as simple as it seemed...
While the site preview built ok, it was actually missing the docs content. When running on main, this broken the netlify build.
Issues I encountered while attempting to update:
- .File.Path was nil
- `kind` in YAML frontmatter is not allowed, but we use it to structure the site's navbars
I have added a note next to the Hugo versions that upgrading the site's version is challenging for these reasons as the new Hugo version also needs to work with all the old versions of the content. We'd got away with this in recent updates, but it seems now we need to do a lot of work before we can consider upgrading again.

docs: Downgrade Hugo

---

test/cases/testdata/v0/reachable/test-reachable-paths-0422.yaml

Due to insufficient indentation, this file would be rejected by compliant YAML parsers. This small fix resolves the issue.
Some blocks in this file are indented such that they are YAML compliant.
There are no code changes in this PR, just a whitespace change to a test file.
If you copy the file as-is into a YAML checker (e.g. https://yamlchecker.com/) it will highlight the issue I've fixed here.

Fixes incorrect indentation in v0/test-reachable-paths-0422.yaml.

---

.github/workflows/nightly.yaml

This ran into TOOMANYREQUESTS too often lately. Let's see if this helps.

nightly: pass GITHUB_TOKEN to avoid rate limit error

---

ast/annotations.go
ast/parser_test.go

Previously, annotations were missing on rules that had variable components in the ref head. Now we annotate the rule using the path up to the first var.
Fixes #7050

Fix: attach annotation to static part of rule ref

---

debug/debugger.go
debug/debugger_test.go
debug/thread.go

Adding `RegoOption` launch option to debugger for setting custom rego options.
Fixes: #7045

debug: Configurable rego-options on debugger

---

docs/content/configuration.md
internal/rego/opa/options.go
plugins/discovery/discovery_test.go
plugins/plugins.go
plugins/plugins_test.go
rego/rego.go
rego/rego_test.go
sdk/opa.go
server/authorizer/authorizer.go
server/authorizer/authorizer_test.go
server/server.go
topdown/builtins.go
topdown/cache/cache.go
topdown/cache/cache_test.go
topdown/eval.go
topdown/glob.go
topdown/glob_test.go
topdown/query.go
topdown/regex.go
topdown/regex_test.go
topdown/topdown_test.go

This commit adds a new inter-query value cache that built-in
functions can use to cache information across queries.
For example, the `regex` and `glob` builtins can use this
to cache compiled regex and glob match patterns respectively.
The number of entries in the cache can be configured via the OPA
config. By default there is no limit.
Fixes: https://github.com/open-policy-agent/opa/issues/6908

Add a new inter-query value cache to cache data across queries

---

README.md

I have made a number of updates to the readme to highlight more up-to-date information about the project and how to get started.

docs: Readme updates

---

topdown/glob.go
topdown/regex.go

No functional changes, just
- using ast.String(..) instead of ast.StringTerm(..).Value
- using const where package-level strings never change (metrics names)
<!--

topdown: glob|regex code nitpicks

---

debug/debugger_test.go
debug/thread.go

even when there are no explicit `input` and `data` documents.
This makes discoverability of the scopes much better, as users will know to expect them. Whereas, if it's only enabled/visible when there is an actual document, a user who has not come across it before might not realize it should appear, and can therefore be slow to realize scenarios where their setup is expecting an `input` document, but is missing it for some reason.

debug: Always including `Input` and `Data` variable scopes

---

.golangci.yaml
cmd/exec_test.go
cmd/internal/exec/exec_test.go
compile/compile_test.go
topdown/http.go

This flags unnecessary conversions of byte->string and vice versa

Add `mirror` linter

---

docs/content/configuration.md
topdown/jsonschema.go
topdown/jsonschema_test.go

I figured I'd test this out anyway, and this seemed like a good case given that there was an actual issue on this.
Testing response times with OPA running as a server, and the first request is ~800 ms while the following ones are ~10 ms.
Fixes #7011

Use new value cache for `json.match_schema`

---

download/download.go
download/oci_download.go
internal/wasm/sdk/opa/loader/file/loader.go
internal/wasm/sdk/opa/loader/http/loader.go
plugins/logs/plugin.go
topdown/http.go
util/time.go

This commit adds a utility for explicitly creating cancelable timers, to avoid possible memory leaks caused by some `time.After` timers in `select` statements never being GC'd properly. This issue is fixed in Go 1.23, but since we're still on Go 1.21, this will resolve the possibility of leaks in the mean time.
The patch fixes every instance in OPA of `<-time.After(...)` that we have, so this *should* fix the issue until OPA eventually upgrades to Go 1.23 (which [changes the behavior of `time.After`](https://go.dev/doc/go1.23#timer-changes)).
**Note**: One of these instances occurs in `topdown/http.go`, so after this fix is integrated into an OPA release, we may want to poke some OPA memory leak reporters again, especially if they were using `http.send` extensively in their policies.
- …

util+plugins: Fix potential memory leak with explicit timer cancellation.

---

test/cases/testdata/v0/time/test-time-0947.yaml
test/cases/testdata/v1/time/test-time-0947.yaml

There is a bug in test-time-0947 (see #7038).
The unification in the test has been replaced by an explicit equality check, to aid in readability and fix the bug.
Fixes #7038

Fixing test-time-0947

---

docs/content/configuration.md
plugins/rest/azure.go
plugins/rest/azure_test.go

As you can see on the discussion https://github.com/orgs/open-policy-agent/discussions/592 , opa server cannot connect azure blob storage on Azure App Service using managed identity.
It seems that IMDS(Instance MetaData Service) endpoint is not available on Azure App Service/Container Apps. It should use special endpoint for getting token instead.
See :
https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#connect-to-azure-services-in-app-code
https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=bicep%2Chttp#connect-to-azure-services-in-app-code
IDENTITY_ENDPOINT and IDENTITY_HEADER envirnnment variables are defined on Azure App Service for getting the token.
Detect these variables and switch the endpoint and header value …

Support managed identity for Azure App Service/Azure Container Apps

---

.github/workflows/nightly.yaml

This version of the action should use the cache, so it'll download the DB less often. Also, it supports referecing two DBs, if the one errors, it should use the other.

nightly: update trivy action, setup two DBs

---

server/writer/writer.go

If the encoding of a result of some sort -- any payload passed to `writer.JSON()` or `writer.JSONOK()` -- failed, we'd emit a log line like 
```
2024/10/11 12:30:21 http: superfluous response.WriteHeader call from github.com/open-policy-agent/opa/runtime.(*recorder).WriteHeader (logging.go:254)
```
and nobody likes these. Also, the encoding error would be the response payload, but the status code had still been 200.
Now, errors encoding the payload properly lead to 500 statuses, without extra logs.
Also headers should be set using Set(), not Add(), to avoid response headers like
```
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Content-Type: application/json
< Date: Fri, 11 Oct 2024 11:52:22 GMT
< Content-Length: 120
```

server/writer: properly handle result encoding errors

---

ast/check.go
cmd/check_test.go

`v0.69.0` caused a regression in `opa check` where a file that referenced non-provided schemas now fails validation. This PR fixes the regression and restores the behavior from `v0.68.0`.
Resolves https://github.com/open-policy-agent/opa/issues/7116 by only adding the `useTypeCheckAnnotations` option if the user has provided a path to schemas to validate. 
This regression was introduced in https://github.com/open-policy-agent/opa/commit/76f7038ea2d18f7d543950847260e61e6a80faaf. In that commit, the signature of the `processAnnotations` method changed: https://github.com/open-policy-agent/opa/commit/76f7038ea2d18f7d543950847260e61e6a80faaf#diff-d23ff3bfce1aa610d34183f8ccab5ecfd112e19dd9ebca55d69f231a29b62337R227. The annotation's `path` will nearly always exist, causing the checker to …

opa check: only check schema types when user provides schemas

---

ast/parser.go
ast/parser_test.go

Since there is no body, the location of the head is a better option than simply using the fist scanned token for location.
Fixes #7128

Fix location for multivalue rules with generated bodies

---

docs/content/management-bundles.md

ORAS CLI has changed. Therefore the tutorial breaks as the --manifest-config option is not available in the most recent version of ORAS v1.2
The current tutorial is broken. This changes fixes this.
Docs change to fix the issue with a deprecated argument

:bug: fix: oras cli changed to --config

---

cmd/check.go
cmd/check_test.go

Make `opa check` respect `--ignore` when `--bundle` flag is set

---

topdown/eval.go

Running `regal lint` on Regal's own policies, this accounts for ~1.4 million allocations 😵
**Before**
```
BenchmarkRegalLintingItself-10    1	3314104416 ns/op	6720813824 B/op	128361292 allocs/op
```
**After**
```
BenchmarkRegalLintingItself-10    1	3185755333 ns/op	6684952216 B/op	126912887 allocs/op
```

eval: don't build trace message when tracing disabled

---

topdown/eval.go

The construction of intermediate throwaway `ast.Array`s caused almost 5 million allocations when running `regal lint` against its own bundle.
While the results are likely more impressive for Regal policies than the average one, this is still a substantial improvement across a large group of policies.
**regal lint OPA main**
```
BenchmarkRegalLintingItself-10    1	3317838417 ns/op	6611412800 B/op	124873123 allocs/op
```
**regal lint this branch**
```
BenchmarkRegalLintingItself-10    1	3140384416 ns/op	6590159176 B/op	120098613 allocs/op
```

Optimize biunify for term slices

---

cmd/fmt_test.go
format/format.go

Resolves https://github.com/open-policy-agent/opa/issues/6999.
When a comprehension is followed by a index retrieving a value from the comprehension, the OPA AST treats that as a `ref`. `ref`s of this sort may contain comments, but the formatter did not write them inline. Since the formatter did not write them inside the comprehension body, the comments were left over and written at the end of the document.
The `else` handling for the formatter is getting a bit gnarly. Constructing a fake ref for the `else` feels like something that can be handled better, but is not in scope for this PR imo.

Fix improper formatter behavior when comprehension contains comment

---

ast/compile.go
ast/compile_test.go

Resolves https://github.com/open-policy-agent/opa/issues/6897.
When there are multiple default rules in a package, the OPA compiler will error out with an unhelpful error message only providing the location of one default rule. This is confusing for users and can be improved by adding all default rule locations to the error message.
Provide the location of all default rules in the resultant error when there are more than one default rule in the fileset compiled.

provide a more useful error message when there are conflicting default rules

---

cmd/exec_test.go
plugins/bundle/errors.go
plugins/bundle/errors_test.go
plugins/bundle/plugin.go
plugins/bundle/plugin_test.go

When using opa as a library you may want to directly control when and how opa interacts with the bundle registry.
When switching to manual trigger mode and triggering the the bundle plugin directly you may want to react to errors that occurred when downloading the bundles. 
The current capability of using the bundle status requires configuring a listener and wait for it to be triggered which differs from the approach taken f.ex. in the discovery plugin.
By returning the downloader errors directly in the bundle plugin trigger method you can f.ex. check for HTTPError and its status code so to determine if a retry can be successful (status code 5xx) or will yield the same result (4xx).
- creating an error type for the bundle plugin similar to ast.Errors that will collect the different errors …

enable direct error handling for bundle plugin trigger method

---

debug/debugger.go
debug/debugger_test.go

By using the unmarshal function from util instead of the stdlib

Debugger: allow YAML to be used as input

---

cmd/run_test.go
runtime/runtime.go
server/server.go
server/server_test.go

Updating `/v1/policies` RESTful endpoint to respect the `--v0-compatible`/`--v1-compatible` flags.

Respect runtime rego-version in RESTful policy API

---

cmd/eval.go
cmd/eval_test.go

- This fixes #7127 when multiple unknowns are passed as array to unknowns flag
- We are doing a regex match for the presence of array in the argument passed to unknowns flag. If it matches with array then we return error.

fix: returns error with illegal args with unknowns flag (#7127)

---

rego/rego.go
topdown/builtins.go
topdown/eval.go
topdown/http.go
topdown/http_test.go
topdown/query.go
topdown/topdown_test.go

We use Rego (via `topdown`) in [Minder](https://github.com/mindersec/minder), an OpenSSF project.  We'd like to be able to customize the `http.send` for a number of use cases, such as automatically adding service-managed credentials (JWTs represent a specific project in a multi-tenant system, similar to GitHub Actions IDs) to outgoing requests.  To do this, we'd need to inject our own `http.RoundTripper`, while respecting the existing flags and arguments to make it easier to transfer Rego knowledge from one environment to another (and to avoid rewriting the builtin `http.send`, which does a lot of useful stuff).
Adds an `EvalHTTPRoundTrip` EvalOption and query-level `WithHTTPRoundTrip` option.  Both use a new function type which converts an `http.Transport` configured by `topdown` to an …

Add the ability to wrap the http.RoundTripper from Go code

---

ast/builtins.go
ast/index.go
ast/internal/scanner/scanner.go
ast/map.go
ast/term.go
builtin_metadata.json
format/format.go
internal/edittree/edittree.go
internal/planner/planner.go
internal/strvals/parser.go
rego/rego.go
topdown/eval.go
topdown/graphql.go
topdown/object.go
types/types.go

**main**
```
BenchmarkLintAllEnabled-10    1	2640715625 ns/op	6385110200 B/op	116296633 allocs/op
```
**pr**
```
BenchmarkLintAllEnabled-10    1	2597179708 ns/op	6183614112 B/op	108421141 allocs/op
```
(I renamed the benchmark, but this is the same as "regal linting itself" used in the past)
Another 8 million allocations cut off from `regal lint bundle`, and a whopping 10% improvements to wall clock time!
The most significant improvement is the Equal implementation for refs, since that is called all over the place. But there are many other fixes here, and they all contribute something substantial (and fixes that only have had marginal impact have been left out).

Even less allocs

---

.golangci.yaml
cmd/bench_test.go
cmd/eval.go
debug/debugger.go
storage/disk/config_test.go
storage/disk/disk_test.go
storage/disk/partition_test.go
storage/disk/paths_test.go
topdown/crypto_test.go
topdown/errors_test.go
topdown/eval_test.go
topdown/exported_test.go
topdown/http_test.go
topdown/input_test.go
topdown/json_test.go
topdown/jsonschema_test.go
topdown/lineage/lineage_test.go
topdown/print_test.go
topdown/query_test.go
topdown/regex_template_test.go
topdown/tokens_test.go
topdown/topdown_test.go
topdown/trace_test.go

This isn't needed anymore, so now we don't. Also enabled the copyloopvar linter in case we accidentally do this in the future.

Avoid copying loop vars (Go 1.22+)

---

cmd/build.go

PR adds an option for `opa build` to preserve print statements (#7194)
New argument `--enable-print-statements` added
N/A
N/A

opa build: provide an option to preserve print statements (#7194)

---

rego/rego_test.go
tester/runner_test.go
topdown/eval.go
topdown/eval_test.go

While the `eval_cancel_error: caller cancelled query execution` error is useful in identifying requests that stopped, I propose that it's a little too vague because it absorbs both `context.Canceled` and `context.DeadlineExceeded` errors. It's useful to differentiate these errors as it gives a clue to whether the user intentionally stopped the request, or the request exeeded some deadline from the caller. Without a change similar to this, it's much more difficult to tell why a call to `Eval` failed.
This adds logic to `topdown/eval.go` to differentiate context errors. It has the same `eval_cancel_error` prefix as before, but can now return an error that gives more clues:
```
eval_cancel_error: context deadline exceeded
eval_cancel_error: context canceled
```
An alternative here could be …

Update eval_cancel_error logic to separate context canceled, timeout errors

---

test/cases/testdata/v1/casts/test-casts-0828.yml
topdown/casts.go

closes #7200 
The `to_number` built-in function in OPA currently allows inputs such as `"Inf"`, `"Infinity"`, and `"NaN"` because these are accepted by Go's `strconv.ParseFloat` function. However, these values are not valid JSON numbers and can cause errors during JSON marshaling or undefined behavior. This change ensures that `to_number` explicitly rejects these inputs, aligning with OPA's expected behavior for numeric conversions.
- Added validation to the `to_number` function to explicitly reject string inputs `"Inf"`, `"Infinity"`, and `"NaN"`.
- Updated the logic to raise a clear `NewOperandTypeErr` when these invalid strings are encountered.

to_number : built-in function now rejects "Inf", "Infinity" and "NaN" values

---

topdown/cache/cache.go
topdown/cache/cache_test.go

In https://github.com/open-policy-agent/opa/pull/7180, I got a few test failures in untouched code in `./topdown/cache`.  Running the tests with `go test -count 200 ./topdown/cache` (which takes around 400s), I got 5 failures across a few different tests.
The underlying cause seems to be the timing of the ticker in comparison te the tests.  The tests create a cache with a 1s expiry scan (which starts a timer to tick at 1s, then re-creates the timer to run 1s later, etc), and then immediately goes on to create objects with 1s expiry.  The test then sleeps for 2s, and checks to see if the items have been evicted.  Unfortunately, the following timing can happen:
* Ticker is created at +0.000s
* Cache item is created, expiring at +1.001s
* Ticker ticks for cache cleanup at +1.000s, the item …

Fix flakes in ./topdown/cache

---

topdown/eval.go
topdown/eval_test.go

The topdown Cancel machinery is there because it's cheap to check. ctx.Err() is not.
This change moves the "Is the context the cause for cancellation?" check into the branch were evaluation has been aborted through the topdown.Cancel call.
When evaluation has already been cancelled, an expensive check no longer matters much -- when it's still ongoing, it'll affect the overall performance.

topdown: move context.Context cancellation check

---

cmd/build_test.go
cmd/fmt.go
cmd/fmt_test.go
v1/format/format.go
v1/format/testfiles/v1/test_future_kw_import.rego
v1/format/testfiles/v1/test_future_kw_import.rego.formatted
v1/format/testfiles/v1/test_rego_v1.rego
v1/format/testfiles/v1/test_rego_v1.rego.formatted

to maximize compatibility surface across OPA versions.
Adding `--drop-v0-imports` flag to `opa fmt` for opting in to dropping redundant v0 imports.

Updating formatter to not drop `rego.v1` and `future.keywords` imports for v1

---

v1/runtime/runtime.go
v1/runtime/runtime_test.go

When an OPA instance runs for a long time, it seems odd to send version reports every hour. I think it's unlikely that someone watches the logs at that point.
So this change makes OPA report every 6 hours (plus a random time between 0 and 60 minutes), after it has reported hourly (+spray) for 6 times.

runtime: send version report less often when long-running

---

v1/ast/check.go
v1/ast/policy.go
v1/ast/term.go
v1/ast/visit.go
v1/rego/rego.go
v1/rego/rego_bench_test.go
v1/rego/testdata/ast.json
v1/topdown/bindings.go
v1/topdown/eval.go
v1/topdown/object.go
v1/topdown/providers.go
v1/topdown/strings.go
v1/topdown/strings_bench_test.go
v1/topdown/tokens_test.go
v1/topdown/walk.go
v1/util/performance.go
v1/util/performance_test.go

My last PR for a while in the ongoing "reduce allocations in eval" quest. Motivated initially mostly to speed up `regal lint`, but most of the changes here positively impacts evaluation performance for most policies.
The changes with the highest impact in this PR:
* Use `sync.Pool`s to avoid the most costly allocations, includuing heavy `*eval` pointers created each time a child or closure scope is evaluated.
* When tracing is disabled, avoid variable escaping to heap in `evalStep` function whose value is only read when tracing is enabled.
* Save one allocation per iteration in `walkNoPath` by reusing an AST array instead of creating a new one for each call.
Also a few minor fixes here and there which either fixed some correctness issue, or had a measurable (although minor) positive …

Reduce allocations, chapter III

---

docs/content/kubernetes-primer.md

There is a small typo in the documentation page of Kubernetes primer (https://www.openpolicyagent.org/docs/latest/kubernetes-primer/) at line 53 of the Markdown file.
The original phrase is: "The admission review request to sent to OPA would look like this:" which have a grammatical error with "to sent".
The PR change the phrase adding "be" to adhere to a future/passive form ("to be sent").

docs: fix typo in k8s primer

---

docs/content/envoy-primer.md

A new attribute `query_parameters_to_remove` has been added to Envoy plugin.
Ref https://github.com/open-policy-agent/opa-envoy-plugin/pull/621
Documentation of Output Document

docs: update output document of Envoy plugin.

---

.golangci.yaml

We started using `golangci-lint` in PR https://github.com/open-policy-agent/opa/pull/3465. However, the configuration name `linter-settings` is incorrect, which caused the configuration for the `lll` and `misspell` linters to not be applied.
https://github.com/open-policy-agent/opa/blob/3568eab2f4f12d70b9e056346466d6c8611ec14d/.golangci.yaml#L140-L145
The correct configuration name is `linters-settings`, as noted in https://golangci-lint.run/usage/configuration/#linters-settings-configuration
Due to this configuration error, we have accumulated many US spelling errors in the codebase. Some of these would cause breaking changes for existing users because they require renaming functions and error strings.
> [!tip]
> Hyrum's law 
> https://github.com/golang/go/blob/go1.23.4/src/net/http/reque …

golangci: fix invalid `linter-settings` configuration name

---

docs/content/management-decision-logs.md
v1/plugins/logs/mask.go
v1/plugins/logs/mask_test.go

Fixes https://github.com/open-policy-agent/opa/issues/6883
Users are often interested using the masking feature to redact a dynamic list of fields, commonly these include array elements.
This PR changes the functionality for masking such that array values can be replaced and upserted in much the same way as object keys.

plugins/logs: Add support for masking with array keys

---

cmd/eval_test.go
internal/presentation/presentation.go

Fixing issue in the `opa eval` command where `--v0-compatible` was ignored for PE support modules when used in combination with the `pretty` output format; producing v1 support modules instead of v0.
Fixing: #7248

cmd: Respect `--v0-compatible` for `opa eval` support modules

---

v1/tester/reporter.go
v1/tester/runner.go

No functional changes, just a bit of cleanup 🧹

tester: code nitpicks

---

cmd/fmt.go

Without this, the `--` are rendered in HTML as `–` making the commands with flags incorrect in the docs.
before
after

docs: Use preformatted strings in fmt help

---

docs/content/http-api-authorization.md

Per #7264: "OPA 1.0+ server now binds only to localhost by default". Adding the --addr flag allows the container to spin up with the correct binding, allowing it to be reachable.
New results with updated docker-compose.yml:
```
$ curl --user alice:password localhost:5000/finance/salary/alice
Success: user alice is authorized 
$ curl localhost:8181
...
</pre>
Open Policy Agent - An open source project to policy-enable your service.<br>
<br>
Version: 1.0.0<br>
...
```

docs: Update docker-compose.yml to include addr

---

internal/edittree/edittree_test.go
internal/planner/planner.go
v1/ast/compare.go
v1/ast/compile.go
v1/ast/interning.go
v1/ast/map.go
v1/ast/parser.go
v1/ast/parser_ext.go
v1/ast/strings.go
v1/ast/strings_bench_test.go
v1/ast/term.go
v1/ast/term_test.go
v1/format/format.go
v1/rego/rego.go
v1/topdown/aggregates.go
v1/topdown/array.go
v1/topdown/builtins/builtins.go
v1/topdown/crypto.go
v1/topdown/crypto_test.go
v1/topdown/glob.go
v1/topdown/http.go
v1/topdown/json.go
v1/topdown/jsonschema.go
v1/topdown/object.go
v1/topdown/print.go
v1/topdown/runtime.go
v1/topdown/strings.go
v1/topdown/subset.go
v1/util/performance.go

Having worked on performance improvements in OPA on the side for almost a month now, there's a lot of code piling up 😅 So much that a single PR would be way too much to review. Instead, I'm splitting the work into chunks, and will submit the next PR as soon as this one is merged. Using the same benchmark as before — Regal linting itself, these new changes in total reduce the number of allocations by ~13 million, and quite a substantial amount of evaluation time saved as well.
This first PR is isolated to improvements to terms, values and built-ins, and saves ~3M allocations. The details can be found below for each change, and of course in the code :)
**BenchmarkRegalLintingItself-10 Before**
```
1885978209 ns/op    3497157312 B/op    69064779 allocs/op
```
**BenchmarkRegalLintingItself-10 …

Perf: improvements to terms and built-in functions

---

cmd/bench.go
cmd/inspect.go
internal/pathwatcher/utils.go
internal/providers/aws/signing_v4.go
v1/ast/compile.go
v1/ast/compile_test.go
v1/ast/varset.go
v1/bundle/hash.go
v1/cover/cover.go
v1/loader/loader.go
v1/server/server_test.go
v1/tester/runner.go
v1/util/compare.go
v1/util/maps.go

And use them to reduce imperative boilerplate throughout the codebase.
Additionally, replace use of sort.Slice with slices.SortFunc which is more efficient since it is generic and as such avoids allocations related to `interface{}` casts.
Also a few performance-related minor fixes, but not the main theme of this PR.
```
BenchmarkRegalLintingItself-10 before / after
1832684458 ns/op    3453470360 B/op    66125422 allocs/op
1826601250 ns/op    3449619024 B/op    65999164 allocs/op
````

Add util.Keys and util.KeysSorted

---

v1/topdown/eval.go
v1/topdown/eval_test.go
v1/util/performance.go

Another PR to reduce allocations, split up from my rather huge local changeset. Here are a few tricks to avoid heap allocations in the eval hotpath, mainly by not letting variables escape their scope, and to make sure we don't evaluate code for partial evaluation when that's not the mode we're running with.
About 3.3 million allocations less reported by the `regal lint bundle` benchmark.
**BenchmarkRegalLintingItself-10 before / after**
```
1822641834 ns/op    3464916080 B/op    66300871 allocs/op
1762596000 ns/op    3380345056 B/op    62983984 allocs/op
```

eval: reduce allocations in hot path

---

.github/workflows/nightly.yaml

The offending vanity import proxy probably won't get fixed anytime soon. Also, I kind of forgot why we had this check, so it can't be that important.

ci(nightly): remove vendor w/o modproxy check

---

cmd/bench.go
cmd/bench_test.go

The numbers reported by `opa bench` would often be misleading, as they would include the cost of generating "JSON" (interface{}) values from the result.
**Before**
```
> opa bench 'numbers.range(1, 500)'
+-------------------------------------------+------------+
| samples                                   |      19736 |
| ns/op                                     |      61062 |
| B/op                                      |      65905 |
| allocs/op                                 |       1086 |
+-------------------------------------------+------------+
```
**After**
```
> opa bench 'numbers.range(1, 500)'
+-------------------------------------------+------------+
| samples                                   |      53263 |
| ns/op                                     |      21836 |
| B/op …
```

opa bench: don't generate JSON from result

---

v1/rego/rego_bench_test.go
v1/rego/testdata/aci/api.rego
v1/rego/testdata/aci/data.json
v1/rego/testdata/aci/framework.rego
v1/rego/testdata/aci/input.json
v1/rego/testdata/aci/policy.rego

Seeing the performance comparison of Regorus and OPA in the Regorus [docs](https://github.com/microsoft/regorus?tab=readme-ov-file#performance) made me curious to try it out myself. This PR adds the test files from their repo (MIT licensed) and two benchmark tests that evaluates the policy using the same parameters as the `opa eval` command from their example.
The benchmarks show that doing the full `opa eval` dance where we build/compile the bundle from scratch is about as fast/slow as their example shows (~30 milliseconds here, but that's without the overhead of the eval command line tool).
However, building the bundle and query beforehand — as would be done in the case of a real OPA deployment — and measuring only _evaluation time_, shows something else entirely: ~0.09 milliseconds, or …

perf: add Regorus ACI benchmark tests

---

cmd/inspect.go
v1/repl/repl.go
v1/repl/repl_test.go

Also found a place in the inspect command code with the same issue, so fixed it there too.
Fixes #7301

repl: Fix printed represenation of ref head rules

---

v1/bundle/store.go
v1/bundle/store_test.go
v1/plugins/bundle/plugin_test.go

Only writing a module's rego-version to storage if it diverges from the runtime rego-version.

bundle: Optimizing rego-version management in bundle activation

---

v1/bundle/store.go
v1/bundle/store_test.go
v1/plugins/bundle/plugin.go
v1/plugins/bundle/plugin_test.go
v1/tester/runner.go

if module rego-version is missing in bundle manifest
* Passing runtime rego-version to deactivation options
* Preferring to pull rego-version from parsed modules if present
This solves an edge case when using the OPA SDK, and should not affect standalone OPA.
Fixes: #7297

Fixing issue where bundle plugin could panic on reconfiguration 

---

cmd/eval.go
docs/content/rest-api.md
v1/rego/rego.go
v1/server/server.go
v1/server/types/types.go
v1/topdown/query.go
v1/topdown/save.go
v1/topdown/topdown_partial_test.go

Some use cases of PE, notably generating queries that are to be translated into filters of some sort (think SQL), require the evaluation of non-deterministic builtins. This is because the result of the builtin informs what queries are returned.
Imagine that the user associated with a request is known at PE-time, but we need extra information from an HTTP API to determine the filters that should be applied.
Previously, that was just impossible to do. Now, we can opt-in to evaluate non-det builtins during PE from the Rego API.
Note that it would probably make sense to include this in the inlining controls, as sent to the Compile API. (Considered out of scope for this PR.)
Also note that this will take highest precedence over the `ast.IgnoreDuringPartialEval` map and the "Nondeterministic" …

topdown+rego+server: allow opt-in for evaluating non-det builtins in PE

---

v1/ast/interning.go
v1/ast/syncpools.go
v1/ast/term.go
v1/storage/internal/ptr/ptr.go
v1/topdown/cache.go

Mostly just some things I improved as I learnt more about how the storage system works. Reducing some allocations, and just general improvements.
- Move some sync.Pool's to a common location
- Allow object.Map to skip items when mapper returns nil key
- Eliminate allocation in object.Find and array.Find when a scalar is encountered.
- Use term pointer pool for temporary terms created only for the sake of calling object.Get in ptr.go

Eliminate allocation in Value.Find

---

v1/rego/rego_bench_test.go
v1/topdown/eval.go

Since we do a lot of this in Rego, I was curious to learn what the cost of that was, and if it was possible to do better. I identified the two main costs as these:
- `handleErr` wrapper allocating in each iteration, even though the normal condition is to not handle an error
- `biunify` callback function literal leaking to the heap in each iteration, with an _high_ cost associated for such a simple one-liner function. While it wasn't possible to change that (as it referenced the outer scope) it *was* possible to inline the whole biunify flow for the array iteration case, as that turned out to be quite simple when stepped through with a debugger.
Ideally we'd be able to inline iteation over sets and objects too, but that's much more complex (see comment in code), so I left that for the …

eval: optimize iteration

---

MAINTAINERS.md

This commit adds Anders and Charlie as maintainers under the `opa` area of expertise. This reflects active contributions to the project and aids in managing the project's relationship with the CNCF. Maintainer status is required for various KubeCon related activities and to open support tickets.
Since this does not add any new organizations, it does not impact the project governance.

MAINTAINERS: Add Anders and Charlie as maintainers

---

v1/rego/rego.go
v1/topdown/cache.go
v1/topdown/eval.go
v1/topdown/query.go
v1/topdown/resolver.go

The same way it's possible to provide a VirtualCache, it should be possible to bring your own BaseCache. In clients like Regal (when invoked via `regal lint`), the base data is only ever loaded once and doesn't change later. Yet currently, each evaluation (of which there are hundreds) will have a new cache instantiated, leading to unnecessary cache misses.
Since our inmem-store is AST-based, we could also try to have the base cache tap directly into the store for a 100% hit ratio, avoiding the more costly storage queries. But that's still untested this point 🤓
(The tiny changes in resolver.go are unrelated to this feature but fix a perf issue I noticed last night as I was testing that functionality. Too small fix to warrant a PR of its own.)

Go API: Allow providing custom base cache

---

ast/policy.go
v1/ast/index.go
v1/ast/policy.go

Saving 7 bytes per index result. Not much, but adds up to ~10Mb in the `regal lint` benchmark. Changing the underlying type is technically a breaking change I suppose, but in the unlikely case anyone used this outside of OPA (we barely use it ourselves!), they'd still have to do and int() conversion to work with it as an int, which will still work.

Use byte for RuleKind and DocKind

---

v1/ast/term.go
v1/ast/term_test.go

1. `ast.InterfaceToValue` walks through json encode/decode for the native `ast.Value` type. It doesn't make sense as far as the function returns `ast.Value`.
2. Regarding `[]string` case, it reduces the number of iterations
Updates in `ast.InterfaceToValue` function.

feat: support []string and ast.Value in ast.InterfaceToValue

---

cmd/run.go
docs/content/cli.md
docs/content/management-bundles.md

outside the v1 upgrade guide and v0 compatibility docs to describe `--v0-compatible` behaviour instead.

docs: Updating `--v1-compatible` mentions

---

docs/content/configuration.md
internal/distributedtracing/distributedtracing.go
v1/server/server_test.go

Fixes #7322
Adds the "deployment.environment" resource attribute to those that can be configured for OpenTelemetry. This was done as some collectors, including Datadog, require this value to properly classify traces.
Changes are simply to accept the new value and update the associated documentation and tests.

Add Additional Resource Attributes for OpenTelemetry

---

v1/bundle/bundle.go
v1/bundle/store.go
v1/bundle/store_test.go
v1/plugins/bundle/plugin_test.go
v1/plugins/plugins.go

where the bundle has been manually constructed containing v0 Rego modules and no `rego_version`/`file_rego_versions` fields are declared in the bundle manifest.
This affects bundle deactivation in the bundle store lifecycle used when for `opa run` in server mode (`-s`).

bundle: Fixing issue where `--v0-compatible` isn't respected for custom bundles

---

v1/rego/rego_bench_test.go
v1/storage/inmem/test/testutil.go
v1/storage/internal/errors/errors.go
v1/storage/internal/errors/errors_test.go
v1/storage/path.go
v1/storage/path_test.go
v1/topdown/eval.go

Some code I had left from the weekend, where I looked into the cost of querying the store during eval, and if that could be improved. The code here is mostly benchmarks that I found useful for that purpose, but also includes a few optimizations of code that is on the hot path for these lookups and as such has a high impact — as the benchmarks demonstrate.
The small change in eval.go is the first use of the new feature of object.Map added some days ago, where a map function returning a nil key means skipping that key/value pair.

Improve storage lookup performance

---

cmd/fmt.go
v1/format/format.go
v1/format/format_test.go
v1/format/testdata/bench.rego

We have a [Regal](https://github.com/styrainc/regal) rule checking that a file [is formatted](https://docs.styra.com/regal/rules/style/opa-fmt), making the performance of the formatter more important than it normally might be.
Since I did some work on this in Regal recently, I was curious to see if this could be improved. Turned out to be a few bottlenecks that we could remove with great results. The Regal policies are possibly not representative for all kinds of Rego, and one thing that stands out is thay they have a *lot* of metadata annotations. Turned out that comment processing was the main bottleneck, so improving this meant a huge boost for formatting a typical Regal policy. The improvements here should make formatting of any file faster though.
**BenchmarkFormatLargePolicy-10 …

perf: `opa fmt` 3x faster formatting

---

ast/annotations.go

Fix: add missing `BuildAnnotationSet` to `ast` v0

---

v1/ast/compile.go
v1/ast/term.go
v1/rego/rego_bench_test.go
v1/topdown/eval.go

Refs copied for the purpose of modification often don't need _all_ parts deep-copied, but only those to be modified. It turns out that in most cases in the context of eval, **no** parts of the ref needs copying, as those refs are static. This PR adds a simple new method to refs that allows smarter copying, saving a million and a half allocations in the `regal lint` benchmark, and hundreds to thousands of allocations in common policy evaluation.
**Before**
```
1716967000 ns/op	3125089752 B/op	62201992 allocs/op
```
**After**
```
1679479541 ns/op	3086159368 B/op	60630066 allocs/op
```

perf: Add ref.CopyNonGround

---

cmd/test.go
cmd/test_test.go

Handle failing tests in `opa test --bench`

---

v1/ast/oracle/oracle.go
v1/ast/oracle/oracle_test.go

Verified that this works in Regal.

Allow passing own compiler to oracle

---

v1/ast/check.go
v1/ast/compare.go
v1/ast/compile.go
v1/ast/compile_test.go
v1/ast/env.go
v1/ast/index.go
v1/ast/map.go
v1/ast/map_test.go
v1/ast/schema.go
v1/dependencies/deps.go
v1/rego/rego.go
v1/topdown/cache.go
v1/topdown/cache/cache.go
v1/topdown/copypropagation/unionfind.go
v1/topdown/http.go
v1/util/hashmap.go

This is a simpler version of util.TypedHashMap where the keys implement a `.Hash()` method and as such won't need one to be passed in, and where the values are largely ignored by the map. These maps are smaller / more performant, but most importantly, they are nicer to work with.
Perf wise, this saves about 600k+ allocs and 40 MB allocated memory in `regal lint bundle`:
```
1207614875 ns/op	3293454016 B/op	64802095 allocs/op
1197978125 ns/op	3256960504 B/op	64164871 allocs/op
```
Also:
- Use `strings.Builder` instead of `fmt.Sprintf` in one location
- Remove `ValueMap.Copy` as it was only used in a test

Add util.HasherMap

---

Makefile
cmd/bench_test.go
docs/content/contrib-development.md
v1/plugins/bundle/plugin_test.go
v1/plugins/plugins_test.go
v1/plugins/rest/rest_test.go
v1/server/server_test.go
v1/storage/disk/disk_test.go
v1/storage/disk/txn_test.go
v1/test/e2e/oci/oci_test.go
v1/tester/runner_test.go

By tagging the worst offenders, we can make use of `go test -short` to avoid them for a quicker dev-test cycle. Compare:
```
make test       200.69s user 209.81s system 170% cpu 4:01.20 total
```
```
make test-short  70.32s user  29.17s system 350% cpu 28.367 total
```
From 4 minutes down to under 30 seconds. The short tests can either be run with `go test -short ./...` or `make test-short`.
We'll still run the full test suite in CI, naturally.
Also:
- Remove section on benchmarking that linked to a no longer used resource.

Add `make test-short` task

---

v1/ast/internal/scanner/scanner.go
v1/ast/internal/tokens/tokens.go

A couple of micro-optimizations, really. But when applied together makes enough of a difference to be taken seriously.
Benchmark showing the difference in the `BenchmarkRegalNoEnabledRules` test in Regal, which was used here simply because the change has no impact outside of parsing.
```
499003281 B/op	 9746024 allocs/op // before
496497404 B/op	 9677104 allocs/op // after
```
A modest improvement, but an improvement nonetheless.

perf: slightly more efficient policy scanning

---

v1/ast/builtins.go
v1/ast/check.go
v1/ast/check_test.go
v1/ast/env.go
v1/server/handlers/compress.go
v1/tester/runner.go
v1/types/decode.go
v1/types/types.go

And make shorthand types boxed types to avoid allocations at runtime.
Below stats show the difference running Regal lint with all rules disabled (to better highlight compilation costs). @srenatus will be pleased by this format, I'm sure.
```
goos: darwin
goarch: arm64
pkg: github.com/styrainc/regal/pkg/linter
cpu: Apple M4 Pro
│  main.txt   │              pr.txt               │
│   sec/op    │   sec/op     vs base              │
RegalNoEnabledRules-12   190.8m ± 2%   181.8m ± 2%  -4.72% (p=0.002 n=6)
│   main.txt   │               pr.txt               │
│     B/op     │     B/op      vs base              │
RegalNoEnabledRules-12   474.4Mi ± 0%   471.3Mi ± 0%  -0.65% (p=0.002 n=6)
│  main.txt   │              pr.txt               │
│  allocs/op  │  allocs/op   vs base              │ …
```

perf: use GetByValue to avoid boxing to interface{}

---

cmd/exec_test.go
cmd/internal/exec/json_reporter.go

I don't think the current output format was documented anywhere, but if it is, let me know and I'll have that updated.

Add decision ID to `opa exec` output

---

v1/ast/term_test.go

I was confused when InterfaceToValue base64-ed the byte array, and decided to explicitly add a test for it.
Just a test case

add test for []byte

---

docs/website/layouts/index.html

Also use example.com for the domain in the examples.
The v1 import is no longer needed post OPA 1.0.
I have removed the import from the homepage examples.
I have updated the example domain to be example.com rather than hooli.com, as hooli.com feels less topical in 2025.

docs: Update homepage examples to drop v1 import

---

.github/workflows/post-merge.yaml
.github/workflows/post-tag.yaml

An attempt to deal with [failing](https://github.com/open-policy-agent/opa/actions/runs/13561553364/job/37905498515) nightly Trivy scans.

Explicitly fetching fetching git tags for CI builds

---

.github/workflows/post-merge.yaml
.github/workflows/post-tag.yaml
.github/workflows/pull-request.yaml

Tags aren't fetched unless complete git history is pulled with `fetch-depth: 0`

ci: Using `fetch-depth` when fetching tags

---

v1/ast/interning.go
v1/ast/parser.go
v1/topdown/object.go
v1/topdown/regex.go
v1/topdown/strings.go

Mostly by having more built-in functions check that they actually *did* something, or can return an operand instead of allocating a result.
This saves about 200k allocations in `regal lint bundle`.

perf: various small improvements

---

.github/workflows/nightly.yaml
.github/workflows/post-merge.yaml
.github/workflows/post-release.yaml
.github/workflows/post-tag.yaml
.github/workflows/pull-request.yaml

The older `ubuntu-22.04` runner is [deprecated](https://github.com/actions/runner-images/issues/11101) and has started getting brownouts.

Bumping GHA runner to `ubuntu-24.04`

---

v1/tester/reporter.go
v1/tester/reporter_test.go

This aligns with not including PASS:ing non-parameterized tests in non-verbose test report summary.
verbose:
```
data.foo.qux.test_cases: FAIL (0s)
bar: FAIL
baz: PASS
foo: PASS
```
non-verbose:
```
data.foo.qux.test_cases: FAIL (0s)
bar: FAIL
```

tester: Only including failed sub-test cases in report summary when non-verbose

---

docs/content/envoy-primer.md

This PR adds support for the `query_parameters_to_set` field in responses. This sets or overrides query parameters in the original request before it's forwarded to upstream services. 
Update documentation to include the new field
- https://github.com/open-policy-agent/opa-envoy-plugin/pull/663

docs: add query_parameters_to_set

---

internal/planner/planner.go
internal/planner/planner_test.go
v1/test/cases/testdata/v1/planner-ir/test-call-dynamic.yaml

We previously only checked if there were any children at all. As #7399 showed, that could have lead into a cul-de-sac.
With this change, we're attempting to look one step ahead, so situations like that one can be ruled out. That said, both the unit test and the yaml tests are _very_ close to the original issue, at risk of of overfitting the solution. But all the previous tests still pass, so this might be OK.
Fixes #7399.

planner: adjust check in ruletree scanning

---

v1/ir/encoding/encoding_test.go
v1/ir/marshal.go

Adds the support for unmarshalling `IsSetStmt` which was omitted when this was originally added.
Also fixes the error handling for unmarshaling unsupported value and statement types, which would previously panic with a nil pointer deref.
Note to reviewer: it wasn't obvious how I should add tests for this, there doesn't seem to be much coverage of this existing code apart from one basic test in `v1/ir/encoding/encoding_test.go`
Fixes: https://github.com/open-policy-agent/opa/issues/7415

Fix nil pointer deref in Unmarshal() when handling IsSetStmt

---

v1/sdk/opa.go

I am verifying some lint idea in my project see https://github.com/alingse/sundrylint/pull/10
it report the function call with repeat args from a sub-function call.
we think the sub-function call is heavy, so the repeat args probably a copy-and-paste mistake.
I check the top 4000 github repos, and found this repo has this case.
remove duplicate code

fix: repeat args from sub-func call

---

v1/format/format.go
v1/format/format_test.go
v1/format/testfiles/v0/test_ref_heads.rego.formatted
v1/format/testfiles/v1/test.rego.formatted
v1/format/testfiles/v1/test_grouping.rego
v1/format/testfiles/v1/test_grouping.rego.formatted
v1/format/testfiles/v1/test_in_operator_with_parenthesis.rego.formatted
v1/format/testfiles/v1/test_issue_5537_with_ref.rego.formatted
v1/format/testfiles/v1/test_ref_heads.rego.formatted

While the double newline added by the formatter after each rule makes sense for most rules, short one-liner rules should be groupable. This PR changes the behavior of the formatter, so that if the user does:
```rego
x := 1
y := 2
```
That is no longer formatted into:
```rego
x := 1
y := 2
```
If the user **wants** double newlines between one-liner rules, the formatter respects those when present.
Note that the `default` rules are excepted even when a one-liner, as presenting these separately helps understanding the policy.
Fixes #6760
Do note that the issued mentioned doing this only for incremental rules, i.e. to group only rules of the same name. I changed my mind on that though, as grouping "constants" should be possible too.

fmt: allow one liner rule grouping

---

docs/content/envoy-tutorial-standalone-envoy.md

Statement on license key was confusing and redundant.
Delete the line from the documentation
Please check the license is indeed unneeded.
Apparently setting a license key is not (longer?) needed. The tutorial doesn't mention it in the rest of the text as the deleted line promises. I couldn't find a hidden statement about a license key in the config files. Not does the page on installing opa using docker mention a license key. https://www.openpolicyagent.org/docs/latest/deployments/

Delete reference to license key in envoy-tutorial-standalone-envoy.md

---

docs/content/envoy-tutorial-standalone-envoy.md

Old text explaining kind and docker usage was confusing and redundant.
Remove confusing part
For me installing docker (desktop on Mac) wasn't enough to use kind. I had to install kind. This is compatible with the kind installation instruction which specifies to install kind after installing docker. Additionally just installing docker isn't enough. It needs to be running. The docker info is a bit confusion in this regard, because if it's installed but not running, it will show output compatible with the example in the tutorial.  Since this tutorial isn't (much) about docker, and the kind installation instructions I'd suggest to strike the rest of the text and just refer to the kind usage/installation instruction, which was already there.

Simplify 'kind' usage instruction envoy-tutorial-standalone-envoy.md

---

v1/topdown/strings.go
v1/topdown/strings_bench_test.go

Similar to how some other built-in functions have been optimized previously, the `lower` and `upper` functions now return the operand as-is when the string wasn't modified by the operation. The impact of this check is negligible when the string is modified, and as the benchmarks demonstrate, quite an improvement for the cases where it isn't. For those, we no longer need to allocate at all.

perf: zero alloc lower/upper unless changed

---

docs/website/content/community/_index.md

With the trailing slash, the link is 500ing

docs: Update community slack inviter link

---

v1/topdown/query.go
v1/topdown/topdown_partial_test.go

Turns out it wasn't an overflow.
This wrong `!` never mattered because without evaluation of nondeterministic builtins (as it was done for ages, the configurable is rather new), time.now_ns() always remained in the PE results, it wasn't evaluated.
Fixes #7490.

topdown: fix wall clock time init for PartialRun()

---

docs/content/policy-language.md

This change addresses issue #5744. The documentation for using schemas with the Rego type checker primarily focused on providing schemas via external files (`-s` flag). This made the alternative method of using inline `@schema` annotations less discoverable for users. Adding an explicit mention and link near the start of the relevant section improves visibility.
This PR modifies `docs/content/policy-language.md` by adding a single sentence to the "Using schemas to enhance the Rego type checker" section. This sentence explicitly mentions both methods (external file and inline annotation) for providing schemas and includes a link to the existing detailed section on inline annotations.
This is a documentation-only change. No code modifications were made, and therefore no tests are required …

docs: Add link to inline schema annotations

---

docs/website/content/integrations/traefik-api-gateway.md

https://github.com/edgeflare/traefik-opa-proxy has been archived for 2 years, so have updated with some new, more recent options.

ecosystem: Update traefik integration docs

---

Makefile

After merging: https://github.com/open-policy-agent/opa/pull/7501
Main failed: https://github.com/open-policy-agent/opa/actions/runs/14380716317/job/40323708024
with the error `$WORK/b001/_pkg_.a(resource.syso): 765938: unknown ARM64 relocation type 3`
This happens because windows is built and then `ci-go-ci-build-linux-static` which doesn't like that `resource.syso` exists in the directory. `resource.syso` gets generated each time anyway so safe to clean it up after a windows build.

fix: remove resource.syso after building windows binary

---

internal/gqlparser/README.md
internal/gqlparser/ast/definition.go
internal/gqlparser/ast/directive.go
internal/gqlparser/ast/document.go
internal/gqlparser/ast/fragment.go
internal/gqlparser/ast/operation.go
internal/gqlparser/ast/selection.go
internal/gqlparser/ast/type.go
internal/gqlparser/ast/value.go
internal/gqlparser/remove-position-marshal.sh

Annotate internal/gqlparser/ast structs not to include Position when marshaled to JSON.
This makes the JSON roundtrip succeed without allocating a ton of memory for JSON fields that will be subsequently pruned.
```sh
$ time ./reproducer-pre-fix
Now passing 1262568 bytes to builtinGraphQLParseSchema() to reproduce the issue in ast.InterfaceToValue()
Alloc = 4159 MiB   TotalAlloc = 5625 MiB   Sys = 5584 MiB  NumGC = 18
Alloc = 8312 MiB   TotalAlloc = 11169 MiB  Sys = 11125 MiB NumGC = 19
Alloc = 8312 MiB   TotalAlloc = 11169 MiB  Sys = 11125 MiB NumGC = 19
Alloc = 16615 MiB  TotalAlloc = 22247 MiB  Sys = 22209 MiB NumGC = 20
Alloc = 16615 MiB  TotalAlloc = 22247 MiB  Sys = 22209 MiB NumGC = 20
Alloc = 16615 MiB  TotalAlloc = 22247 MiB  Sys = 22209 MiB NumGC = 20
Alloc = 38765 MiB …
```

Add JSON annotation in internal/gqlparser/ast to Position fields

---

docs/content/configuration.md
v1/plugins/discovery/discovery_test.go
v1/topdown/graphql.go
v1/topdown/graphql_bench_test.go
v1/topdown/graphql_test.go

This commit stores parsed GraphQL schemas to the cache, which improves the performance of GraphQL operations that parse the schema more than once.
Queries are not cached.
```
pkg: github.com/open-policy-agent/opa/v1/topdown
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkGraphQLSchemaIsValid/Trivial_Schema_-_string-16	                   15519            100178 ns/op
BenchmarkGraphQLSchemaIsValid/Trivial_Schema_with_cache_-_string-16               371311              3383 ns/op
BenchmarkGraphQLSchemaIsValid/Trivial_Schema_-_object-16                            2133            542355 ns/op
BenchmarkGraphQLSchemaIsValid/Trivial_Schema_with_cache_-_object-16                 3471            528579 ns/op
BenchmarkGraphQLSchemaIsValid/Trivial_Schema_-_AST_object-16 …
```

v1/topdown/graphql: Cache GraphQL schema parse results (#5377)

---

docs/website/layouts/partials/docs/dashboard-panel.html

No versioned archive deploy is available/maintained for this tag.

docs: update edge links to use /docs/edge/ path

---

docs/website/edge/version-redirect.ts
netlify.toml

Following #7528, we also need to route any requests using the old versioned paths to the correct location.
Related to https://github.com/open-policy-agent/opa/issues/7037
Pages like https://www.openpolicyagent.org/docs/v1.0.1/ still exist and while they are not in the version nav, they still serve the page. These pages are not going to be there in future so I am creating these redirects.

docs: Point path versioned requests to new sites

---

README.md

At the moment I am seeing this badge in the README: https://github.com/open-policy-agent/opa/workflows/Post%20Merge/badge.svg?branch=main where it says `no status`
removing the `?=branch=main` part it shows `passing`. because the post merge workflow only runs on main it should be ok to drop that part?
https://github.com/open-policy-agent/opa/workflows/Post%20Merge/badge.svg

docs: fix post merge badge

---

v1/ast/term.go
v1/ast/term_bench_test.go
v1/ast/term_test.go

Fix issue - https://github.com/open-policy-agent/opa/issues/7550
After some investigation, it looks like after https://github.com/open-policy-agent/opa/pull/7172, Ref.String() in ast/term.go (around line 1124) stopped using p.String() (which produces a JSON-escaped literal, it uses strconv.Quote(string(str)) under the covers) and instead writes the raw contents of the String term. As a result, sequences like "\t" in a reference key now become an actual tab (ASCII 9) instead of the two‐byte escape (\ + t, ASCII 92,116).
Hence have this PR to address the regression.
Per the discussion in https://github.com/open-policy-agent/opa/issues/7550, this function is called a lot, so avoiding strconv.Quote is desirable if possible as it allocates. So I add a simply check for \ in the string and use …

Bug fix for issue 7550, only use JSON-escaped literal when needed in Ref.String()

---

v1/rego/rego.go

Saw this by accident, and while I'm not sure how common this is, there's really never any point in serializing a JSON value unless it is known to be used later.

Don't generate JSON values for wildcard/generated keys in result set

---

netlify.toml

This had been set only for previews before when testing #7534.
This is needed to use docusaurus, the framework used to build the new site.
10.x as used before is eol too and was only needed for live block injection. Live blocks have been removed as we transition to the new site. Live blocks which need Node 10 and cannot work with newer versions.

docs: Use Node 22 for all contexts

---

docs/new/src/pages/ecosystem/index.js

At the moment, showing the long list is not ideal without categorizing the items. However, search helps a little as well as the existing categorization earlier in the page.
This PR also adds a small note to show how the page is ordered.
https://github.com/user-attachments/assets/9fd57af4-7810-4a68-bc1e-824dbd482173

docs: Allow searching of ecosystem page

---

docs/new/src/pages/_examples/admin/config.json
docs/new/src/pages/_examples/admin/input.json
docs/new/src/pages/_examples/admin/policy.rego
docs/new/src/pages/index.js

This is shorter and more representative of a real use case where the policy uses input.
Input is hidden but can be seen in the playground.
https://github.com/user-attachments/assets/760b7773-bb33-4c9a-959e-64628674c766
This PR also addresses some v overflow on mobile.

docs: Use simple RBAC example for homepage 

---

cmd/bench.go
v1/rego/rego.go
v1/rego/rego_bench_test.go
v1/topdown/cache.go
v1/topdown/eval.go
v1/topdown/query.go
v1/topdown/resolver.go

It's been irritating me for long how `opa bench` has such a high baseline metric for even the most trivial queries, as in order to know the cost of "your" Rego you'll need to first subtract the number OPA adds for just getting eval set up. This improves this somewhat by not initiating some caches until they're needed. We don't need to cache comprehensions to eval the value '1', or a functionMockStack, and so on. In fact, we may never need one. The gain here is miniscule for real policy evaluation, but helps some with making `opa bench` approach a more reasonable baseline.
We *can* have 10 allocs more removed if we initialize and reuse a base cache and a virtual cache across all runs. This works as the query is the same for all runs. However, since those are normally initialized per "run" …

perf: improve "baseline" metrics of opa bench for trivial queries

---

docs/new/src/pages/_examples/admin/config.json
docs/new/src/pages/_examples/admin/input.json
docs/new/src/pages/_examples/admin/policy.rego

This showcases Rego nicely with an ABAC example instead.
This is intended to be clearer to understand and is based on some feedback I've had on the new site.

docs: Use ABAC example on new OPA homepage

---

docs/new/docs/cli.md

The contents of the CLI documentation is being manually updated while we prepare the new site.
original change: c50c7eedcc5c2db625687967fc8bc38aa24bd1f8

docs: Port c50c7e CLI docs update to new docs site

---

internal/planner/planner.go
internal/planner/rules.go
internal/planner/rules_test.go
internal/wasm/sdk/test/e2e/exceptions.yaml
v1/test/cases/testdata/v1/withkeyword/test-with-builtin-mock.yaml
v1/test/cases/testdata/v1/withkeyword/test-with-function-mock.yaml

This change still follows the approach thought up in #6996, but now does it more consistently: the extra args accumulated through (multiple) with-replacements using variables are now put into the funcstackj, and consistently affect the planning of functions in "higher" gens.
Fixes #5311.

planner: deal with var-for-function replacement in indirect calls

---

internal/ref/ref.go
v1/topdown/object.go

- Check for array without allocating error
- Pre-allocate array path for given length

perf: faster object.get

---

v1/ast/term.go
v1/ast/term_bench_test.go

This is a marginal improvement, but considering this is one of the most called functions in OPA, the overall impact is still substantial. Concretely, this simple change reduces the number of allocations done in the `regal lint bundle` benchmark by about 655K(!)
**main vs. change**
```
BenchmarkRefString/SingleTerm-12     56586423      20.70 ns/op       16 B/op      1 allocs/op
BenchmarkRefString/SingleTerm-12     581425396      2.07 ns/op        0 B/op      0 allocs/op
```

perf: ref.String() shortcut on single var term ref

---

docs/src/components/BuiltinTable.js

This was missed in the redesign of the built in table.

docs: Use colors on built in table

---

.github/workflows/post-merge.yaml
docs/Makefile
docs/bin/smoke-test.sh

This is easier to test in post merge, then we don't need to work out the preview URL of the netlify deployment.

docs: Add simple post-merge smoke test website

---

docs/static/_redirects

https://github.com/open-policy-agent/opa/issues/7603 appears to be happening often enough in netlify data that we should be redirecting here.
Fixes https://github.com/open-policy-agent/opa/issues/7603

docs: Add Tutorial Redirects

---

docs/src/pages/ecosystem/index.js
docs/static/_redirects

Some pages have been removed from the ecosystem section in the new site and we need to redirect them to somewhere more helpful.
Fixes https://github.com/open-policy-agent/opa/issues/7604
Fixes https://github.com/open-policy-agent/opa/issues/7605

docs: Redirect to search for ecosystem pages

---

docs/functions/badge-endpoint.ts
netlify.toml

This retains the badge behaviour from the old site and still uses a function for all badge related requests.
Test like this: https://img.shields.io/endpoint?url=https://deploy-preview-7618--openpolicyagent.netlify.app/badge-endpoint/config/v1.3.1

docs: Revert badge endpoint to old path

---

docs/functions/badge.ts
netlify.toml

We have callers using /badge and /badge-endpoint
https://github.com/StyraInc/regal/blob/main/README.md?plain=1#L4
https://github.com/StyraInc/enterprise-opa/blob/main/README.md?plain=1#L1C15-L1C100
There are likely others mixing the use so I think we should continue to support both.

website: Fix badge endpoint

---

docs/src/EcosystemEntry.js
docs/src/data/ecosystem/entries/regal.md

This makes a guess at a more human-friendly link for ecosystem entries, without us needing to go around and get all the link titles.
https://github.com/user-attachments/assets/6a4055a1-1b90-408e-8af4-164172712f59

docs: Add a HumanLink for ecosystem entries

---

v1/server/server.go

When OPA is hosted from non root path it's not possible to use test `index.html` page
Changed `index.html` template to use relative fetch path. this will fix wrong path when opa is hosted from non root folder

fix: query url when opa is served not from root path

---

docs/functions/badge.ts
netlify.toml

We have been having some issues with the badge endpoints and have opted to standardize on the `/badge` as the public API for this feature.
e.g. https://openpolicyagent.org/badge/v1.5.0

website: Fix badge endpoints

---

v1/metrics/metrics.go
v1/metrics/metrics_bench_test.go

This PR preallocates maps where possible in the `v1/metrics` package, which we were not doing before. This provides a small, but reliable/stable boost to the performance of several operations on the hot path for serialization of metrics, mostly from reducing allocations.
I built a benchmark for the hot path that I'm the most interested in: JSON serialization when several metrics are present.
This fully exercises most of the `v1/metrics` package, and shows the full benefit of the prealloc changes.
Here's the [benchstat](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) diff of 40x runs of main (as of yesterday) versus 40x runs of this PR:
```
% benchstat main.txt pr.txt
goos: linux
goarch: amd64
pkg: github.com/open-policy-agent/opa/v1/metrics
cpu: Intel(R) Core(TM) i7-8650U CPU @ …
```

v1/metrics: Prealloc maps + add benchmark

---

v1/metrics/metrics.go
v1/metrics/metrics_bench_test.go
v1/metrics/metrics_test.go

This PR fixes a potential bug that could occur with `metrics.Timer`. Whenever `timer.Stop()` was called, the timer would add the current delta from the start time to its accumulated value so far, *regardless of whether it had been restarted with `timer.Start()` or not*.
This could lead to confusing metrics in some places if `timer.Stop()` was accidentally called twice. (Value would be much larger than expected.)
The fix is to use a `sync.Once` guard around the accumulating step. This adds about 20 nanoseconds to timer start/stop in benchmarks, and 16 bytes to the underlying timer struct, but no extra allocs or other performance impacts.
go test -timeout 30s github.com/open-policy-agent/opa/v1/metrics -count=1
go test -benchmem -run=^$ -bench ^BenchmarkMetricsTimerStartStop$ …

v1/metrics: Fix restartable timer bug.

---

internal/prometheus/prometheus.go
v1/metrics/metrics.go
v1/plugins/logs/plugin.go
v1/server/authorizer/authorizer.go
v1/server/server.go
v1/server/server_bench_test.go
v1/server/server_test.go

Since we don't use OPA's HTTP API in Regal, I hadn't looked at this from a performance POV before, but it was a fun side quest :)
A pretty decent reduction of the baseline cost for the most common request type, v1/data POST. Changes:
- Add NoOp implementation of `Metrics` for when metrics aren't needed
- Cheaper `metrics.New` instantiation avoiding unnecessary lock
- Avoid cost of decision logging if decision logging isn't enabled
- Only call request.URL.Query() if URL.RawQuery isn't empty, avoiding allocating an empty map with each request
While the target was v1/data POST handling, some of the changes above have a positive impact on all or most handlers. All changes have been run through the existing tests, and a new benchmark to measure the impact of the fixes have been added, showing: …

perf: more efficient data/v1 POST handler

---

docs/src/components/FeedbackForm/index.js

In response to feedback, the feedback pop-up will now be hidden indefinitely if the user chooses to dismiss it. This change is intended to improve user experience by preventing the pop-up from reappearing after being dismissed on one page and then re-appearing on another.

website: Hide feedback pop-up forever if dismissed

---

v1/server/server.go
v1/server/server_test.go

The `/v1/data` endpoint's PUT, PATCH, and DELETE methods all report incorrect timer information (zeroed out timers). This is caused by the `Timer.Stop()` calls being `defer`'d in those method handlers. The problem is that the timers don't record a time value until you `Stop` them, and so when the metrics are reported, all of those timers are still storing their initial zero values.
I fixed this issue by manually calling `Timer.Stop()` right before metrics collection on each endpoint, similar to how we handle many other endpoints in the server.
Fire up an OPA with `opa run -s`, then:
```shell
curl -X PUT -H "Content-Type: application/json" --data '{"x": 1}' 'localhost:8181/v1/data?metrics'
```
On `main` right now, you should see something like this returned:
```json …
```

v1/server: Fix deferred metrics timers for `/v1/data` PUT, PATCH, and DELETE.

---

docs/src/Archive.js

This updates the archive list to only show the latest patch release for each minor version. This is to reduce the total number of entries on the archive page. (and it is what we used to do with the old site too!)

website: Only show latest patch in archive

---

docs/docs/policy-reference/index.md

This used to be rendered as a pre block on the old site, but it was broken as our mdx formatter does not do that now.
I have made it a nice list instead.

docs: policy-reference, update sig algs formatting

---

docs/docs/index.md

I have tried to make a number of small improvements to the installation Instructions.
We have tabs now, which is a commit UX pattern for multi platform steps like this.
I have also added links to OPA packages for linux.
https://github.com/user-attachments/assets/d5943875-240f-48f3-9bb3-e99e51ffd332

docs: Install/Download Instruction Update

---

.github/workflows/pull-request.yaml

In: https://github.com/open-policy-agent/opa/actions/runs/15607457047/job/43960850907?pr=7693
The output is really unclear that it's the race job that failed.
Since it's the summary that is the required check, it should be give the author some hint about what to do next to fix the issue rather than just saying "one of the required checks failed".

build: Make summary failure source clearer

---

v1/topdown/http_test.go

noticed two recent failures:
* https://github.com/open-policy-agent/opa/actions/runs/15607457047/job/43960307228
* https://github.com/open-policy-agent/opa/actions/runs/15581030615/job/43876209064
this test was flaky before: https://github.com/open-policy-agent/opa/pull/7616
I think the 1ms timeout is causing the issue which isn't required anymore.
Ran it multiple times without issue, but hopefully this actually fixes it.
`go test -count 1000 -failfast -run TestRaisingHTTPClientQueryError ./v1/topdown/. -v`

fix flaky TestRaisingHTTPClientQueryError

---

cmd/bench.go
cmd/bench_test.go
cmd/build.go
cmd/check.go
cmd/check_test.go
cmd/deps.go
cmd/deps_test.go
cmd/eval.go
cmd/eval_test.go
cmd/filters.go
cmd/flags.go
cmd/formats/formats.go
cmd/inspect.go
cmd/inspect_test.go
cmd/internal/exec/params.go
cmd/parse.go
cmd/parse_test.go
cmd/refactor.go
cmd/run.go
cmd/test.go

A tiny first step to have more tooling correctly report virtual and base document conflicts, as detailed in #7694.
This PR fixes the `opa check` command to report conflicts of this type when the `-b`/`--bundle` flag is provided. The bundle flag is required as without that, `opa check` should only verify policies and not load data at all.
While I was in the `cmd` directory, I got annoyed with how many of these commands store the same constants for their `--format` flag, so I decided to fix that too, even if it wasn't related to what I originally planned to do. I hope it's not too distracting.

opa check --bundle report virtual/base doc conflicts

---

docs/docs/cicd.md
docs/src/lib/sidebars.js

Fixes https://github.com/open-policy-agent/opa/issues/3798
This at least makes a start on some basic docs showing how to use OPA in CI/CD use cases for gluing things together. Ideally, we'd have some more examples here on the page, but they can come in time. I have for now commited an example for test coverage and linked to an example from the OPA repo.

docs: Add basic docs covering CI/CD use case

---

go.mod
go.sum
v1/test/cases/testdata/v1/graphql/test-graphql-schema-is-valid.yaml
vendor/github.com/vektah/gqlparser/v2/gqlerror/error.go
vendor/modules.txt

The test case added here will verify that a crashing bug is fixed.
Adds a test case to ensure that #7699 is fixed.
Upstream issue: https://github.com/vektah/gqlparser/issues/375
Upstream PR: https://github.com/vektah/gqlparser/pull/376

Bump gqlparser v2.5.27 -> v2.5.28

---

docs/docusaurus.config.js
docs/src/components/NavbarItems/CurrentVersionNavbarItem.js

Docs are updated as we push to main, this means the version is not the latest, but rather the edge version. This is to avoid confusion while still showing fixes to the docs site as we make them, since it's still an active area of development after we released the new version.
I have left in the component as we will want to make it so that this shows the latest tag when building an archived deployment and will use this component for that, but for now, it's just always shows edge.

docs: Show edge rather than latest release

---

cmd/inspect.go
cmd/inspect_test.go
internal/bundle/inspect/inspect.go

inspect: Fixing missing annotations location in `opa inspect` with JSON format

---

docs/docs/index.md

This PR fixes a typo in the installation section in order to properly spell NetBSD.
NetBSD was accidentally spelled as NetBSB.
Just a mechanical s/NetBSB/NetBSD/ in the docs.
N/A
Thanks for mentioning the pkgsrc package!

docs: Correctly spell NetBSD

---

docs/src/data/ecosystem/entries/opa-playground.md

We are attempting to not use hardcoded pg links as they go stale eventually.
Instead I just point to the example group.

docs: Remove link to OPA playground share

---

cmd/eval.go
cmd/test.go
cmd/test_test.go
v1/rego/plugins_test.go
v1/repl/repl.go
v1/repl/repl_test.go

This is allowing the _default_ target plugin to be changed.
The use case is this: An application wrapping OPA, using a different rego target plugin, wants to have that target plugin be used "by default", i.e. for `opa eval` and `opa test` without a specified `-t` argument.
With this change, that can be achieved by having the target plugin _claim ""_.
Testing this is tricky, because a replaced _default_ might affect other tests. I have thus tried to centralize the tests using a different default plugin to one test case in the cmd package.

cmd+repl: only plumb through target if it was set

---

cmd/test.go
internal/bundle/inspect/inspect.go
internal/pathwatcher/utils.go
internal/runtime/init/init.go
internal/runtime/init/init_test.go
v1/compile/compile.go
v1/loader/loader.go
v1/loader/loader_test.go
v1/rego/rego.go
v1/runtime/runtime.go

This PR comprehensively plumbs in the bundle lazy loading mode option in the `compile`, `runtime`, `rego`, and `bundle` packages. It also includes the bare minimum plumbing to allow the path watcher utilities to also toggle the option on.
In nearly all places where a default is expected, the lazy loading mode is set to `false` (disabled) to avoid behavior changes.

loader+internal: Add bundle lazy loading mode across the runtime.

---

docs/static/_redirects

Fixes https://github.com/open-policy-agent/opa/issues/7755
Also removes an old todo.

docs: Fix /docs/envoy-authorization/ 404

---

docs/src/components/BuiltinTable/index.js
docs/src/components/BuiltinTable/styles.module.css

This makes a number of changes to how the built in functions are displayed to ensure that there is no horizontal scrolling when viewing builtin in tables with longer function names.
https://github.com/user-attachments/assets/5e368415-b966-4a88-88b1-504aa549ae2d

website: Ensure no hscroll on built-in tables

---

v1/hooks/hooks.go
v1/runtime/runtime.go
v1/runtime/runtime_test.go
v1/server/server.go

When an plugin http handler or some other mechanism wants to do rego evaluations, too, it's beneficial to share the caches with the server.
This change introduces two new hook types to allow retrieving those caches during server startup.

server: add hooks wiring + new hooks for inter-query caches

---

v1/ast/capabilities.go

If I add this to `main.go` (imagine another executable including OPA),
```diff
diff --git a/main.go b/main.go
index 9d5aea6c7c..5126479107 100644
--- a/main.go
+++ b/main.go
@@ -8,9 +8,11 @@
"os"
"github.com/open-policy-agent/opa/cmd"
+	"github.com/open-policy-agent/opa/v1/ast"
)
func main() {
+	ast.RegisterFeatures("foo", "bar", "baz")
if err := cmd.RootCommand.Execute(); err != nil {
os.Exit(1)
}
```
and I subsequently run `opa capabilities --current`, we'll find (other stuff omitted):
```json
{
"features": [
"bar",
"baz",
"foo",
"keywords_in_refs",
"rego_v1"
]
}
```
This complements _builtins_, which can already be registered from the outside.

ast: add feature registration from the outside

---

docs/docs/graphql-api-authorization.md

Fixes https://github.com/open-policy-agent/opa/issues/6586
I have also revised the intro to the page to reduce the number of short sections.
We also had some recent feedback on this point again:

docs: Update warning note in GraphQL API docs

---

internal/config/config.go
v1/plugins/discovery/discovery.go
v1/plugins/discovery/discovery_test.go

This allows simple setups -- those feeding the OPA discovery plugin with a static JSON file -- to still do env variable replacements.
This should be possible already, by using a policy to construct the disco config, but it becomes easier now.

plugins/discovery: Replace environment variables after evaluation.

---

v1/logging/logging.go
v1/plugins/logs/plugin.go
v1/plugins/logs/plugin_test.go
v1/server/buffer.go

This commit adds a new `batch_decision_id` field to Decision Log entries, allowing batches of decisions to be correlated together later. This has a different intent and purpose than the preexisting `request_id` field-- you might have several decisions that are logically part of the same batch, but are initiated from multiple individual requests.
The point of this PR is to provide the minimal scaffolding to allow eventual batching of requests/decisions/queries.

server+logging: Add BatchDecisionID field to Decision Logs.

---

cmd/eval.go
v1/ast/rego_compiler.go
v1/rego/rego.go
v1/rego/rego_test.go
v1/tester/runner.go

This allows builtins to retrieve the compiler from the context to do wonders with them.

test+eval: add helper to smuggle compiler through context

---

v1/plugins/plugins.go
v1/runtime/runtime_test.go
v1/server/authorizer/authorizer.go
v1/server/authorizer/authorizer_test.go
v1/server/server.go

This PR provides an extension mechanism for the server authorizer, allowing plugins and other server extensions to inform the authorizer about the methods and paths it should allow.

server/authorizer: Allow adding paths to validator.

---

v1/plugins/logs/plugin.go
v1/plugins/logs/plugin_test.go
v1/server/buffer.go
v1/server/server.go

This PR adds an experimental "intermediate results" field to decision logs, and provides some basic plumbing in the server package for eventually attaching the intermediate results of an eval to the request context.
The feature can be enabled with the environment variable `OPA_DECISIONS_INTERMEDIATE_RESULTS`, like so:
export OPA_DECISIONS_INTERMEDIATE_RESULTS=1 ./opa run -s mypolicy.rego --set
The intermediate results are not populated with anything exciting yet, so it should have no effect on decision logs.

plugins/logs: Add experimental intermediate results field.

---

v1/loader/loader.go

It seems correct to give the bundle a name, after all. It's just metadata.

loader: pass bundle name in AsBundle()

---

build/generate-cli-docs/generate.go
build/generate-man/generate.go
cmd/bench.go
cmd/build.go
cmd/capabilities.go
cmd/check.go
cmd/commands.go
cmd/deps.go
cmd/eval.go
cmd/exec.go
cmd/flags.go
cmd/fmt.go
cmd/inspect.go
cmd/oracle.go
cmd/parse.go
cmd/refactor.go
cmd/run.go
cmd/sign.go
cmd/test.go
cmd/version.go
main.go
v1/runtime/runtime.go

This change allows users that build their own executable or "spin" of OPA to give it a name, and have it reference itself properly in help texts.
It's a vanity thing, but I think some people would appreciate it, hat tip to the international association of pedants.

cmd: allow branding

---

docs/docs/index.md
docs/docs/policy-language.md
docs/src/css/custom.css

- added link to playground
- removed some examples I felt were redundant
- made the constants example relevant to the example domain
- minor wording changes and fixes

docs: Revise docs index page wording

---

Makefile
docs/Makefile
docs/bin/build-latest.sh
netlify.toml

⚠️ This should be merged *after* v1.7.0 is released as the v1.6.0 website is not going to have: https://github.com/open-policy-agent/opa/pull/7783, which is needed by the versioned deployments to toggle their out of date state.
This is intended to make the default view of the OPA site and docs from the latest release, rather than from edge.
Deploy preview command will need to show edge, but using that to test the prod command atm.
When `make netlify-latest` was used on the preview, we see that the site was built from the latest release:

website: Use latest release rather than edge

---

cmd/parse.go

This PR moves an accidental package-level definition of the `opa parse` CLI subcommand to a local variable inside the `initParse` function, similar to how we do command initialization for all other OPA CLI subcommands.
Before this change, it was possible to see panics from the package variable `cobra.Command` in `parse.go` having some of its flags redefined. This fix makes it possible for `make generate-cli-docs` to run without error again.
- Try running `make -C docs generate-cli-docs`, and see if the docs generate correctly.
- For an example failure, see this [error from the recent Post Merge workflow](https://github.com/open-policy-agent/opa/actions/runs/16655123404/job/47138042468)

cmd/parse: Move accidental pkg var to local var.

---

v1/runtime/runtime_test.go

I saw a panic here: https://github.com/open-policy-agent/opa/actions/runs/16652495113/job/47128828522 and think it's related to the server init check returning before the addrs are set.
I update all cases where a similar check on logs is done.
I am unsure how the log could come before the server is initialized, but sometimes funny things happen in race detector ordering and this looks more correct to me.

runtime: Update server init check in runtime tests

---

v1/download/download.go
v1/plugins/bundle/plugin_test.go
v1/test/e2e/print/print_test.go
v1/util/backoff.go

I ran into an issue when testing an earlier change:
https://github.com/open-policy-agent/opa/actions/runs/16646981900/job/47110035165
I found that this test generated around 100,000 lines of errors showing the bundle downloader running.
This can be be tested using: (should be 22 instances now)
```
go test -v ./v1/plugins/bundle -count=1 2>&1 | grep -c "request failed"
```
This commit closes managers and plugins correctly.
[logs](https://github.com/user-attachments/files/21534949/11_Go.Test.linux.txt)

plugin/bundle: Correct bundle delay behavior

---

v1/config/config.go
v1/config/config_test.go
v1/plugins/bundle/plugin.go
v1/plugins/bundle/plugin_test.go
v1/plugins/discovery/discovery.go
v1/plugins/discovery/discovery_test.go
v1/plugins/plugins.go
v1/plugins/plugins_test.go
v1/rego/rego.go
v1/runtime/runtime.go
v1/runtime/runtime_test.go
v1/sdk/opa.go
v1/server/server.go
v1/server/server_test.go
v1/topdown/cache/cache.go
v1/topdown/cache/cache_test.go
v1/util/test/populate.go

I ran into this race condition on another PR:
https://github.com/open-policy-agent/opa/actions/runs/16655603110/job/47139789057
I've created GetConfig which clones the config from the manager and updated callers to use this instead. I believe that I've found all the manager config access and updated them all.

v1/plugins: Address race in config access

---

docs/docs/contrib-code.md
docs/docs/contributing.md

We've seen an increase in AI generated contributions lately, and often where issues have been picked seemingly at random. This change updates the docs on contributing to OPA to address some of the issues we've seen around that.

docs: Add note on using LLMs in PR discussions

---

v1/server/handlers/compress.go

Fixes race condition in initGzipPool() that was causing go race test failures when multiple tests run concurrently. The package-level gzipPool variable was being unsafely reassigned across without synchronization.
RWMutex ensures that the gzipPool is only initialized once.

handlers: add thread-safe initialization for gzipPool

---

v1/ast/capabilities.go
v1/ast/fuzz_test.go
v1/ast/term.go
v1/ast/term_bench_test.go

Experimenting with using an ast.Object for a cache in Regal led me to find this, and to rule out that idea until this is released :)
The `.rehash()` method would consistently allocate a new slice for hashes, making it more expensive to add a new value to an existing key than inserting a new key-value pair! Added benchmarks to verify.
Before:
```
BenchmarkObjectInsert
existing_key_and_value-12   126126	      8923 ns/op	   19200 B/op	     200 allocs/op
existing_key,_new_value-12  129670	      9024 ns/op	   19200 B/op	     200 allocs/op
new_key-12                  244428	      5016 ns/op	    2400 B/op	     100 allocs/op
new_key,_new_value-12       220352	      5172 ns/op	    2400 B/op	     100 allocs/op
```
After:
```
existing_key_and_value-12   261966	      4610 ns/op	       0 B/op	       0 …
```

perf: fix issue in Object.Insert on existing key

---

docs/src/pages/_examples/ai/policy.rego
docs/src/pages/index.js

Example on the OPA home page in the AI category was broken.
Previously output of default rego was this, i.e. the available models list was empty:
```
[
"Model 'model-2' is not in your accessible models: "
]
```
Output of default rego is now this:
```
[
"Model 'model-2' is not in your accessible models: ^model-\\d+-stage$, model-1"
]
```
* Corrected path to the input element. 
* PR bonus: added explanatory text to aid new users.
NA
NA

home page example fix

---

docs/docs/ocp/concepts.md

Fixes https://github.com/open-policy-agent/opa-control-plane/issues/73.

docs/ocp: fix wrong example on concepts page

---

docs/docs/ocp/api-reference.md

These names were added in
https://github.com/open-policy-agent/opa-control-plane/pull/71

docs/ocp: update API reference

---

docs/docs/ocp/api-reference.md

The previous rego policy snippet wasn't valid. It's got to be a query, either referencing a rule defined in one of the sources, or an inline query like in the updated example.

docs/ocp: fix inline-transform example

---

docs/docs/rest-api.md

We have more extensive docs to port over, but this isn't the right place for those. So let's get these in first.
Follow-up for #7887.

docs/rest-api: add basic Compile API docs

---

v1/topdown/http.go
v1/topdown/http_test.go

This PR implements issue #6838 by adding a counter metric to track the number of actual HTTP network requests made by the `http.send` builtin.
- **New metric**: `rego_builtin_http_send_network_requests` 
- **Purpose**: Track actual HTTP network calls made during policy evaluation
- **Scope**: Counts only network requests, excludes cache hits
The counter increments in both cache implementations:
- `interQueryCache.ExecuteHTTPRequest()` - for inter-query cache misses
- `intraQueryCache.ExecuteHTTPRequest()` - for intra-query cache misses
This ensures all actual network requests are counted while cache hits are properly excluded.
When querying with `?metrics=true`, the response will include:
```json
{
"metrics": {
"counter_rego_builtin_http_send_network_requests": 3, …
```

feat: Add counter metric for http.send network requests

---

docs/docs/rest-api.md
e2e/api/compile/e2e_test.go
e2e/api/compile/logs_test.go
internal/compile/compile.go
v1/ast/annotations.go
v1/ast/parser.go
v1/ast/parser_test.go
v1/rego/compile/compile.go
v1/server/compile_handler.go
v1/server/compile_handler_checks_test.go
v1/server/compile_handler_test.go
v1/server/failtracer/failtracer.go
v1/server/failtracer/hints_test.go
v1/server/server.go
v1/server/testdata/bench_filters.rego

This used to be
```
custom:
unknowns: [ ... ]
mask_rule: ...
```
and now becomes
```
compile:
unknowns: [ ... ]
mask_rule: ...
```
TODO:

ast: add compile annotation key

---

cmd/test.go
internal/bundle/utils.go
internal/presentation/presentation_test.go
internal/runtime/init/init.go
v1/debug/thread.go
v1/plugins/bundle/plugin_test.go
v1/rego/example_test.go
v1/rego/rego.go
v1/repl/repl.go
v1/storage/inmem/inmem.go
v1/storage/inmem/inmem_bench_test.go
v1/storage/inmem/inmem_test.go
v1/storage/inmem/txn.go
v1/storage/path.go
v1/storage/path_test.go
v1/test/authz/authz_bench_test.go
v1/tester/runner.go

Mainly making transactions cheaper to create, and read transactions much cheaper.
- Add exported RootPath shorthand var
- Don't return path on ParsePathEscaped failure
- Allocate nothing for read transactions, other than the transaction itself
- Lazy init of write update collections to avoid needless allocations
- Add benchmarks
**Before**
```
BenchmarkNewTransaction/Read-16                     26707234            44.78 ns/op      144 B/op          3 allocs/op
BenchmarkNewTransaction/Write-16                    20344212            59.44 ns/op      192 B/op          4 allocs/op
BenchmarkReadOne/Go_store_(roundtrip)-16            21963003            54.41 ns/op      144 B/op          3 allocs/op
BenchmarkReadOne/Go_store_(no_roundtrip)-16         22217593            54.18 ns/op      144 …
```

Some small improvements to inmem storage

---

docs/docs/kubernetes/primer.md

https://openpolicyagent.slack.com/archives/C08V59T3NAF/p1759159399901459
The feedback is positive, but I thought we could make it clearer and get rid of the line numbers in comments.

docs: remove k8s primer line numbers comments

---

v1/ast/builtins.go
v1/ast/performance.go
v1/ast/performance_test.go
v1/ast/term.go
v1/ast/term_bench_test.go
v1/rego/plugins_test.go
v1/topdown/eval.go

I was meant to do slides for a talk, but here we are. Fun exercise in "writing" a string without actually writing one, but rather by trying to exclude all other possible built-in function names to compare against ref as early as possible in order to make the operation inexpensive. And it worked! Down from a few allocations (worst case) and at least 3 digit ns/op, to no allocations and lower end of the 2 digit ns/op scale.
For reference, this PR accounts for 700K allocations gone in `regal lint bunde`, as we do millions of builtin function calls as part of that benchmark.
Another 300K+ allocs gone by revisiting the `canSkipBctx` field on the AST builtin struct, and making it public sp that client like Regal may benefit. And we did :)

Ref String() and greatly improved builtin lookup cost
